var dir_cbd7f246bdf7dc0a50281a272327e6ed =
[
    [ "bitcoinkernel.cpp", "bitcoinkernel_8cpp.html", "bitcoinkernel_8cpp" ],
    [ "bitcoinkernel.h", "bitcoinkernel_8h.html", "bitcoinkernel_8h" ],
    [ "bitcoinkernel_wrapper.h", "bitcoinkernel__wrapper_8h.html", "bitcoinkernel__wrapper_8h" ],
    [ "blockmanager_opts.h", "blockmanager__opts_8h.html", "blockmanager__opts_8h" ],
    [ "caches.h", "kernel_2caches_8h.html", "kernel_2caches_8h" ],
    [ "chain.cpp", "kernel_2chain_8cpp.html", "kernel_2chain_8cpp" ],
    [ "chain.h", "kernel_2chain_8h.html", "kernel_2chain_8h" ],
    [ "chainparams.cpp", "kernel_2chainparams_8cpp.html", "kernel_2chainparams_8cpp" ],
    [ "chainparams.h", "kernel_2chainparams_8h.html", "kernel_2chainparams_8h" ],
    [ "chainstatemanager_opts.h", "chainstatemanager__opts_8h.html", "chainstatemanager__opts_8h" ],
    [ "checks.cpp", "checks_8cpp.html", "checks_8cpp" ],
    [ "checks.h", "checks_8h.html", "checks_8h" ],
    [ "coinstats.cpp", "coinstats_8cpp.html", "coinstats_8cpp" ],
    [ "coinstats.h", "coinstats_8h.html", "coinstats_8h" ],
    [ "context.cpp", "kernel_2context_8cpp.html", null ],
    [ "context.h", "kernel_2context_8h.html", "kernel_2context_8h" ],
    [ "cs_main.cpp", "cs__main_8cpp.html", "cs__main_8cpp" ],
    [ "cs_main.h", "cs__main_8h.html", "cs__main_8h" ],
    [ "disconnected_transactions.cpp", "kernel_2disconnected__transactions_8cpp.html", null ],
    [ "disconnected_transactions.h", "disconnected__transactions_8h.html", "disconnected__transactions_8h" ],
    [ "mempool_entry.h", "mempool__entry_8h.html", "mempool__entry_8h" ],
    [ "mempool_limits.h", "mempool__limits_8h.html", "mempool__limits_8h" ],
    [ "mempool_options.h", "mempool__options_8h.html", "mempool__options_8h" ],
    [ "mempool_removal_reason.cpp", "mempool__removal__reason_8cpp.html", "mempool__removal__reason_8cpp" ],
    [ "mempool_removal_reason.h", "mempool__removal__reason_8h.html", "mempool__removal__reason_8h" ],
    [ "messagestartchars.h", "messagestartchars_8h.html", "messagestartchars_8h" ],
    [ "notifications_interface.h", "notifications__interface_8h.html", "notifications__interface_8h" ],
    [ "types.h", "kernel_2types_8h.html", "kernel_2types_8h" ],
    [ "warning.h", "warning_8h.html", "warning_8h" ]
];