.TH "src/crc32c/.ycm_extra_conf.py" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crc32c/.ycm_extra_conf.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBiverbatim\fP"
.br
.RI "YouCompleteMe configuration that interprets a \&.clang_complete file\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDirectoryOfThisScript\fP ()"
.br
.ti -1c
.RI "\fBMakeRelativePathsInFlagsAbsolute\fP (\fBflags\fP, build_root)"
.br
.ti -1c
.RI "\fBFindNearest\fP (target, path, build_root)"
.br
.ti -1c
.RI "\fBFlagsForClangComplete\fP (file_path, build_root)"
.br
.ti -1c
.RI "\fBFlagsForFile\fP (filename, **kwargs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBBASE_FLAGS\fP"
.br
.ti -1c
.RI "list \fBPATH_FLAGS\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DirectoryOfThisScript ()"

.PP
.nf
Returns the absolute path to the directory containing this script\&.
.fi
.PP
 
.SS "FindNearest ( target,  path,  build_root)"

.PP
.nf
Looks for a file with a specific name closest to a project path\&.

This is similar to the logic used by a version-control system (like git) to
find its configuration directory (\&.git) based on the current directory when a
command is invoked\&.

Args:
  target: The file name to search for\&.
  path: The directory where the search starts\&. The search will explore the
      given directory's ascendants using the parent relationship\&. Should be an
      absolute path\&.
  build_root: A directory that acts as a fence for the search\&. If the search
      reaches this directory, it will not advance to its parent\&. Should be an
      absolute path\&.

Returns:
  The path to a file with the desired name\&. None if the search failed\&.

.fi
.PP
 
.SS "FlagsForClangComplete ( file_path,  build_root)"

.PP
.nf
Reads the \&.clang_complete flags for a source file\&.

Args:
  file_path: The path to the source file\&. Should be inside the project\&. Used
    to locate the relevant \&.clang_complete file\&.
  build_root: The current directory when running the Clang compiler for this
      file\&. Should be an absolute path\&.

Returns:
  A list of strings, where each element is a Clang command-line flag\&.

.fi
.PP
 
.SS "FlagsForFile ( filename, ** kwargs)"

.PP
.nf
Implements the YouCompleteMe API\&.
.fi
.PP
 
.SS "MakeRelativePathsInFlagsAbsolute ( flags,  build_root)"

.PP
.nf
Expands relative paths in a list of Clang command-line flags\&.

Args:
  flags: The list of flags passed to Clang\&.
  build_root: The current directory when running the Clang compiler\&. Should be
      an absolute path\&.

Returns:
  A list of flags with relative paths replaced by absolute paths\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list BASE_FLAGS"
\fBInitial value:\fP
.nf
1 =  [
2     '\-Werror',  # Unlike clang_complete, YCM can also be used as a linter\&.
3     '\-DUSE_CLANG_COMPLETER',  # YCM needs this\&.
4     '\-xc++',  # YCM needs this to avoid compiling headers as C code\&.
5 ]
.PP
.fi

.SS "list PATH_FLAGS"
\fBInitial value:\fP
.nf
1 =  [
2     '\-isystem',
3     '\-I',
4     '\-iquote',
5     '\-\-sysroot='
6 ]
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
