.TH "src/node/abort.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/abort.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/abort\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <node/interface_ui\&.h>\fP
.br
\fR#include <node/warnings\&.h>\fP
.br
\fR#include <util/signalinterrupt\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <cstdlib>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAbortNode\fP (const std::function< bool()> &shutdown_request, std::atomic< int > &\fBexit_status\fP, const \fBbilingual_str\fP &message, \fBnode::Warnings\fP *warnings)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
