.TH "ActionUnserialize" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionUnserialize
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <serialize\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr bool \fBForRead\fP ()"
.br
.ti -1c
.RI "template<typename Stream, typename\&.\&.\&. Args> static void \fBSerReadWriteMany\fP (Stream &s, Args &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "template<typename Stream, typename Type, typename Fn> static void \fBSerRead\fP (Stream &s, Type &&obj, Fn &&fn)"
.br
.ti -1c
.RI "template<typename Stream, typename Type, typename Fn> static void \fBSerWrite\fP (Stream &s, Type &&, Fn &&)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "constexpr bool ForRead ()\fR [inline]\fP, \fR [static]\fP, \fR [constexpr]\fP"

.SS "template<typename Stream, typename Type, typename Fn> void SerRead (Stream & s, Type && obj, Fn && fn)\fR [inline]\fP, \fR [static]\fP"

.SS "template<typename Stream, typename\&.\&.\&. Args> void SerReadWriteMany (Stream & s, Args &&\&.\&.\&. args)\fR [inline]\fP, \fR [static]\fP"

.SS "template<typename Stream, typename Type, typename Fn> void SerWrite (Stream & s, Type && , Fn && )\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
