.TH "AddedNodeParams" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddedNodeParams
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <net\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBm_added_node\fP"
.br
.ti -1c
.RI "bool \fBm_use_v2transport\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "std::string m_added_node"

.SS "bool m_use_v2transport"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
