.TH "AddressTableModel" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddressTableModel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <addresstablemodel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBColumnIndex\fP { \fBLabel\fP = 0, \fBAddress\fP = 1 }"
.br
.ti -1c
.RI "enum \fBRoleIndex\fP { \fBTypeRole\fP = Qt::UserRole }"
.br
.ti -1c
.RI "enum \fBEditStatus\fP { \fBOK\fP, \fBNO_CHANGES\fP, \fBINVALID_ADDRESS\fP, \fBDUPLICATE_ADDRESS\fP, \fBWALLET_UNLOCK_FAILURE\fP, \fBKEY_GENERATION_FAILURE\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddressTableModel\fP (\fBWalletModel\fP *parent=nullptr, bool pk_hash_only=false)"
.br
.ti -1c
.RI "\fB~AddressTableModel\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const QString \fBSend\fP = 'S'"
.br
.ti -1c
.RI "static const QString \fBReceive\fP = 'R'"
.br
.in -1c
.SS "Methods overridden from QAbstractTableModel"

.in +1c
.ti -1c
.RI "class \fBAddressTablePriv\fP"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const override"
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const override"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &\fBindex\fP, int role) const override"
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &\fBindex\fP, const QVariant &value, int role) override"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const override"
.br
.ti -1c
.RI "QModelIndex \fBindex\fP (int row, int column, const QModelIndex &parent) const override"
.br
.ti -1c
.RI "bool \fBremoveRows\fP (int row, int count, const QModelIndex &parent=QModelIndex()) override"
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &\fBindex\fP) const override"
.br
.ti -1c
.RI "QString \fBaddRow\fP (const QString &type, const QString &label, const QString &address, const \fBOutputType\fP address_type)"
.br
.ti -1c
.RI "QString \fBlabelForAddress\fP (const QString &address) const"
.br
.ti -1c
.RI "std::optional< \fBwallet::AddressPurpose\fP > \fBpurposeForAddress\fP (const QString &address) const"
.br
.ti -1c
.RI "int \fBlookupAddress\fP (const QString &address) const"
.br
.ti -1c
.RI "\fBEditStatus\fP \fBgetEditStatus\fP () const"
.br
.ti -1c
.RI "\fBOutputType\fP \fBGetDefaultAddressType\fP () const"
.br
.ti -1c
.RI "QString \fBGetWalletDisplayName\fP () const"
.br
.ti -1c
.RI "void \fBupdateEntry\fP (const QString &address, const QString &label, bool isMine, \fBwallet::AddressPurpose\fP purpose, int status)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Qt model of the address book in the core\&. This allows views to access and modify the address book\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBColumnIndex\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILabel \fP
User specified label 
.TP
\f(BIAddress \fP
Bitcoin address 
.SS "enum \fBEditStatus\fP"
Return status of edit/insert operation 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIOK \fP
Everything ok 
.TP
\f(BINO_CHANGES \fP
No changes were made during edit operation 
.TP
\f(BIINVALID_ADDRESS \fP
Unparseable address 
.TP
\f(BIDUPLICATE_ADDRESS \fP
Address already in address book 
.TP
\f(BIWALLET_UNLOCK_FAILURE \fP
\fBWallet\fP could not be unlocked to create new receiving address 
.TP
\f(BIKEY_GENERATION_FAILURE \fP
Generating a new public key for a receiving address failed 
.SS "enum \fBRoleIndex\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BITypeRole \fP
Type of address (\fBSend\fP or \fBReceive\fP) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAddressTableModel\fP (\fBWalletModel\fP * parent = \fRnullptr\fP, bool pk_hash_only = \fRfalse\fP)\fR [explicit]\fP"

.SS "~\fBAddressTableModel\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "QString addRow (const QString & type, const QString & label, const QString & address, const \fBOutputType\fP address_type)"

.SS "int columnCount (const QModelIndex & parent) const\fR [override]\fP"

.SS "QVariant data (const QModelIndex & index, int role) const\fR [override]\fP"

.SS "Qt::ItemFlags flags (const QModelIndex & index) const\fR [override]\fP"

.SS "\fBOutputType\fP GetDefaultAddressType () const"

.SS "\fBEditStatus\fP getEditStatus () const\fR [inline]\fP"

.SS "QString GetWalletDisplayName () const"

.SS "QVariant headerData (int section, Qt::Orientation orientation, int role) const\fR [override]\fP"

.SS "QModelIndex index (int row, int column, const QModelIndex & parent) const\fR [override]\fP"

.SS "QString labelForAddress (const QString & address) const"
Look up label for address in address book, if not found return empty string\&. 
.SS "int lookupAddress (const QString & address) const"

.SS "std::optional< \fBwallet::AddressPurpose\fP > purposeForAddress (const QString & address) const"
Look up purpose for address in address book, if not found return empty string\&. 
.SS "bool removeRows (int row, int count, const QModelIndex & parent = \fRQModelIndex()\fP)\fR [override]\fP"

.SS "int rowCount (const QModelIndex & parent) const\fR [override]\fP"

.SS "bool setData (const QModelIndex & index, const QVariant & value, int role)\fR [override]\fP"

.SS "void updateEntry (const QString & address, const QString & label, bool isMine, \fBwallet::AddressPurpose\fP purpose, int status)\fR [slot]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBAddressTablePriv\fP\fR [friend]\fP"

.SH "Field Documentation"
.PP 
.SS "const QString Receive = 'R'\fR [static]\fP"
Specifies receive address 
.SS "const QString Send = 'S'\fR [static]\fP"
Specifies send address 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
