.TH "src/qt/addresstablemodel.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/addresstablemodel.h
.SH SYNOPSIS
.br
.PP
\fR#include <optional>\fP
.br
\fR#include <QAbstractTableModel>\fP
.br
\fR#include <QStringList>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAddressTableModel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinterfaces\fP"
.br
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
