.TH "src/addresstype.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/addresstype.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <addresstype\&.h>\fP
.br
\fR#include <crypto/sha256\&.h>\fP
.br
\fR#include <hash\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <script/solver\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/hash_type\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <vector>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< unsigned char > \fBvaltype\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCKeyID\fP \fBToKeyID\fP (const \fBPKHash\fP &key_hash)"
.br
.ti -1c
.RI "\fBCKeyID\fP \fBToKeyID\fP (const \fBWitnessV0KeyHash\fP &key_hash)"
.br
.ti -1c
.RI "\fBCScriptID\fP \fBToScriptID\fP (const \fBScriptHash\fP &script_hash)"
.br
.ti -1c
.RI "bool \fBExtractDestination\fP (const \fBCScript\fP &scriptPubKey, \fBCTxDestination\fP &addressRet)"
.br
.ti -1c
.RI "\fBCScript\fP \fBGetScriptForDestination\fP (const \fBCTxDestination\fP &dest)"
.br
.ti -1c
.RI "bool \fBIsValidDestination\fP (const \fBCTxDestination\fP &dest)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<unsigned char> \fBvaltype\fP"

.SH "Function Documentation"
.PP 
.SS "bool ExtractDestination (const \fBCScript\fP & scriptPubKey, \fBCTxDestination\fP & addressRet)"
Parse a scriptPubKey for the destination\&.

.PP
For standard scripts that have addresses (and P2PK as an exception), a corresponding \fBCTxDestination\fP is assigned to addressRet\&. For all other scripts\&. addressRet is assigned as a \fBCNoDestination\fP containing the scriptPubKey\&.

.PP
Returns true for standard destinations with addresses - P2PKH, P2SH, P2WPKH, P2WSH, P2TR and P2W??? scripts\&. Returns false for non-standard destinations and those without addresses - P2PK, bare multisig, null data, and nonstandard scripts\&. 
.SS "\fBCScript\fP GetScriptForDestination (const \fBCTxDestination\fP & dest)"
Generate a Bitcoin scriptPubKey for the given \fBCTxDestination\fP\&. Returns a P2PKH script for a \fBCKeyID\fP destination, a P2SH script for a \fBCScriptID\fP, and an empty script for \fBCNoDestination\fP\&. 
.SS "bool IsValidDestination (const \fBCTxDestination\fP & dest)"
Check whether a \fBCTxDestination\fP corresponds to one with an address\&. 
.SS "\fBCKeyID\fP ToKeyID (const \fBPKHash\fP & key_hash)"

.SS "\fBCKeyID\fP ToKeyID (const \fBWitnessV0KeyHash\fP & key_hash)"

.SS "\fBCScriptID\fP ToScriptID (const \fBScriptHash\fP & script_hash)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
