.TH "AddressTableEntryLessThan" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddressTableEntryLessThan
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBAddressTableEntry\fP &a, const \fBAddressTableEntry\fP &b) const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBAddressTableEntry\fP &a, const QString &b) const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const QString &a, const \fBAddressTableEntry\fP &b) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool operator() (const \fBAddressTableEntry\fP & a, const \fBAddressTableEntry\fP & b) const\fR [inline]\fP"

.SS "bool operator() (const \fBAddressTableEntry\fP & a, const QString & b) const\fR [inline]\fP"

.SS "bool operator() (const QString & a, const \fBAddressTableEntry\fP & b) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
