.TH "AddrInfo" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddrInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <addrman_impl\&.h>\fP
.PP
Inherits \fBCAddress\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBAddrInfo\fP, obj)"
.br
.ti -1c
.RI "\fBAddrInfo\fP (const \fBCAddress\fP &addrIn, const \fBCNetAddr\fP &addrSource)"
.br
.ti -1c
.RI "\fBAddrInfo\fP ()"
.br
.ti -1c
.RI "int \fBGetTriedBucket\fP (const \fBuint256\fP &nKey, const \fBNetGroupManager\fP &netgroupman) const"
.br
.RI "Calculate in which "tried" bucket this entry belongs\&. "
.ti -1c
.RI "int \fBGetNewBucket\fP (const \fBuint256\fP &nKey, const \fBCNetAddr\fP &src, const \fBNetGroupManager\fP &netgroupman) const"
.br
.RI "Calculate in which "new" bucket this entry belongs, given a certain source\&. "
.ti -1c
.RI "int \fBGetNewBucket\fP (const \fBuint256\fP &nKey, const \fBNetGroupManager\fP &netgroupman) const"
.br
.RI "Calculate in which "new" bucket this entry belongs, using its default source\&. "
.ti -1c
.RI "int \fBGetBucketPosition\fP (const \fBuint256\fP &nKey, bool fNew, int bucket) const"
.br
.RI "Calculate in which position of a bucket to store this entry\&. "
.ti -1c
.RI "bool \fBIsTerrible\fP (\fBNodeSeconds\fP now=\fBNow\fP< \fBNodeSeconds\fP >()) const"
.br
.RI "Determine whether the statistics about this entry are bad enough so that it can just be deleted\&. "
.ti -1c
.RI "double \fBGetChance\fP (\fBNodeSeconds\fP now=\fBNow\fP< \fBNodeSeconds\fP >()) const"
.br
.RI "Calculate the relative chance this entry should be given when selecting nodes to connect to\&. "
.in -1c

Public Member Functions inherited from \fBCAddress\fP
.in +1c
.ti -1c
.RI "\fBCAddress\fP ()"
.br
.ti -1c
.RI "\fBCAddress\fP (\fBCService\fP ipIn, \fBServiceFlags\fP nServicesIn)"
.br
.ti -1c
.RI "\fBCAddress\fP (\fBCService\fP ipIn, \fBServiceFlags\fP nServicesIn, \fBNodeSeconds\fP time)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCAddress\fP, obj)"
.br
.in -1c

Public Member Functions inherited from \fBCService\fP
.in +1c
.ti -1c
.RI "\fBCService\fP ()"
.br
.ti -1c
.RI "\fBCService\fP (const \fBCNetAddr\fP &ip, uint16_t \fBport\fP)"
.br
.ti -1c
.RI "\fBCService\fP (const struct in_addr &ipv4Addr, uint16_t \fBport\fP)"
.br
.ti -1c
.RI "\fBCService\fP (const struct sockaddr_in &addr)"
.br
.ti -1c
.RI "uint16_t \fBGetPort\fP () const"
.br
.ti -1c
.RI "bool \fBGetSockAddr\fP (struct sockaddr *paddr, socklen_t *addrlen) const"
.br
.ti -1c
.RI "bool \fBSetSockAddr\fP (const struct sockaddr *paddr, socklen_t addrlen)"
.br
.ti -1c
.RI "sa_family_t \fBGetSAFamily\fP () const"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBGetKey\fP () const"
.br
.ti -1c
.RI "std::string \fBToStringAddrPort\fP () const"
.br
.ti -1c
.RI "\fBCService\fP (const struct in6_addr &ipv6Addr, uint16_t \fBport\fP)"
.br
.ti -1c
.RI "\fBCService\fP (const struct sockaddr_in6 &addr)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCService\fP, obj)"
.br
.in -1c

Public Member Functions inherited from \fBCNetAddr\fP
.in +1c
.ti -1c
.RI "\fBCNetAddr\fP ()"
.br
.ti -1c
.RI "\fBCNetAddr\fP (const struct in_addr &ipv4Addr)"
.br
.ti -1c
.RI "void \fBSetIP\fP (const \fBCNetAddr\fP &ip)"
.br
.ti -1c
.RI "void \fBSetLegacyIPv6\fP (std::span< const uint8_t > ipv6)"
.br
.ti -1c
.RI "bool \fBSetInternal\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "bool \fBSetSpecial\fP (std::string_view addr)"
.br
.ti -1c
.RI "bool \fBIsBindAny\fP () const"
.br
.ti -1c
.RI "bool \fBIsIPv4\fP () const"
.br
.ti -1c
.RI "bool \fBIsIPv6\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC1918\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC2544\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC6598\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC5737\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC3849\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC3927\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC3964\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC4193\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC4380\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC4843\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC7343\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC4862\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC6052\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC6145\fP () const"
.br
.ti -1c
.RI "bool \fBIsHeNet\fP () const"
.br
.ti -1c
.RI "bool \fBIsTor\fP () const"
.br
.ti -1c
.RI "bool \fBIsI2P\fP () const"
.br
.ti -1c
.RI "bool \fBIsCJDNS\fP () const"
.br
.ti -1c
.RI "bool \fBHasCJDNSPrefix\fP () const"
.br
.ti -1c
.RI "bool \fBIsLocal\fP () const"
.br
.ti -1c
.RI "bool \fBIsRoutable\fP () const"
.br
.ti -1c
.RI "bool \fBIsInternal\fP () const"
.br
.ti -1c
.RI "bool \fBIsValid\fP () const"
.br
.ti -1c
.RI "bool \fBIsPrivacyNet\fP () const"
.br
.ti -1c
.RI "bool \fBIsAddrV1Compatible\fP () const"
.br
.ti -1c
.RI "enum \fBNetwork\fP \fBGetNetwork\fP () const"
.br
.ti -1c
.RI "std::string \fBToStringAddr\fP () const"
.br
.ti -1c
.RI "bool \fBGetInAddr\fP (struct in_addr *pipv4Addr) const"
.br
.ti -1c
.RI "\fBNetwork\fP \fBGetNetClass\fP () const"
.br
.ti -1c
.RI "uint32_t \fBGetLinkedIPv4\fP () const"
.br
.RI "For IPv4, mapped IPv4, SIIT translated IPv4, Teredo, 6to4 tunneled addresses, return the relevant IPv4 address as a uint32\&. "
.ti -1c
.RI "bool \fBHasLinkedIPv4\fP () const"
.br
.RI "Whether this address has a linked IPv4 address (see \fBGetLinkedIPv4()\fP)\&. "
.ti -1c
.RI "std::vector< unsigned char > \fBGetAddrBytes\fP () const"
.br
.ti -1c
.RI "int \fBGetReachabilityFrom\fP (const \fBCNetAddr\fP &paddrPartner) const"
.br
.ti -1c
.RI "\fBCNetAddr\fP (const struct in6_addr &pipv6Addr, const uint32_t scope=0)"
.br
.ti -1c
.RI "bool \fBGetIn6Addr\fP (struct in6_addr *pipv6Addr) const"
.br
.ti -1c
.RI "bool \fBIsRelayable\fP () const"
.br
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBNodeSeconds\fP \fBm_last_try\fP {0s}"
.br
.RI "last try whatsoever by us (memory only) "
.ti -1c
.RI "\fBNodeSeconds\fP \fBm_last_count_attempt\fP {0s}"
.br
.RI "last counted attempt (memory only) "
.ti -1c
.RI "\fBCNetAddr\fP \fBsource\fP"
.br
.RI "where knowledge about this address first came from "
.ti -1c
.RI "\fBNodeSeconds\fP \fBm_last_success\fP {0s}"
.br
.RI "last successful connection by us "
.ti -1c
.RI "int \fBnAttempts\fP {0}"
.br
.RI "connection attempts since last successful attempt "
.ti -1c
.RI "int \fBnRefCount\fP {0}"
.br
.RI "reference count in new sets (memory only) "
.ti -1c
.RI "bool \fBfInTried\fP {false}"
.br
.RI "in tried set? (memory only) "
.ti -1c
.RI "int \fBnRandomPos\fP {\-1}"
.br
.RI "position in vRandom "
.in -1c

Data Fields inherited from \fBCAddress\fP
.in +1c
.ti -1c
.RI "\fBNodeSeconds\fP \fBnTime\fP {TIME_INIT}"
.br
.RI "Always included in serialization\&. The behavior is unspecified if the value is not representable as uint32_t\&. "
.ti -1c
.RI "\fBServiceFlags\fP \fBnServices\fP {\fBNODE_NONE\fP}"
.br
.RI "Serialized as uint64_t in V1, and as CompactSize in V2\&. "
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBCAddress\fP
.in +1c
.ti -1c
.RI "enum class \fBFormat\fP { \fBDisk\fP, \fBNetwork\fP }"
.br
.in -1c

Public Types inherited from \fBCNetAddr\fP
.in +1c
.ti -1c
.RI "enum class \fBEncoding\fP { \fBV1\fP, \fBV2\fP }"
.br
.ti -1c
.RI "enum \fBBIP155Network\fP : uint8_t { \fBIPV4\fP = 1, \fBIPV6\fP = 2, \fBTORV2\fP = 3, \fBTORV3\fP = 4, \fBI2P\fP = 5, \fBCJDNS\fP = 6 }"
.br
.in -1c

Static Public Attributes inherited from \fBCAddress\fP
.in +1c
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV1_NETWORK\fP {{\fBCNetAddr::Encoding::V1\fP}, \fBFormat::Network\fP}"
.br
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV2_NETWORK\fP {{\fBCNetAddr::Encoding::V2\fP}, \fBFormat::Network\fP}"
.br
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV1_DISK\fP {{\fBCNetAddr::Encoding::V1\fP}, \fBFormat::Disk\fP}"
.br
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV2_DISK\fP {{\fBCNetAddr::Encoding::V2\fP}, \fBFormat::Disk\fP}"
.br
.in -1c

Static Public Attributes inherited from \fBCNetAddr\fP
.in +1c
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV1\fP {\fBEncoding::V1\fP}"
.br
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV2\fP {\fBEncoding::V2\fP}"
.br
.in -1c

Protected Attributes inherited from \fBCService\fP
.in +1c
.ti -1c
.RI "uint16_t \fBport\fP"
.br
.in -1c

Protected Attributes inherited from \fBCNetAddr\fP
.in +1c
.ti -1c
.RI "\fBprevector\fP< ADDR_IPV6_SIZE, uint8_t > \fBm_addr\fP {ADDR_IPV6_SIZE, 0x0}"
.br
.ti -1c
.RI "\fBNetwork\fP \fBm_net\fP {\fBNET_IPV6\fP}"
.br
.ti -1c
.RI "uint32_t \fBm_scope_id\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extended statistics about a \fBCAddress\fP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAddrInfo\fP (const \fBCAddress\fP & addrIn, const \fBCNetAddr\fP & addrSource)\fR [inline]\fP"

.SS "\fBAddrInfo\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int GetBucketPosition (const \fBuint256\fP & nKey, bool fNew, int bucket) const"

.PP
Calculate in which position of a bucket to store this entry\&. 
.SS "double GetChance (\fBNodeSeconds\fP now = \fR\fBNow\fP<\fBNodeSeconds\fP>()\fP) const"

.PP
Calculate the relative chance this entry should be given when selecting nodes to connect to\&. 
.SS "int GetNewBucket (const \fBuint256\fP & nKey, const \fBCNetAddr\fP & src, const \fBNetGroupManager\fP & netgroupman) const"

.PP
Calculate in which "new" bucket this entry belongs, given a certain source\&. 
.SS "int GetNewBucket (const \fBuint256\fP & nKey, const \fBNetGroupManager\fP & netgroupman) const\fR [inline]\fP"

.PP
Calculate in which "new" bucket this entry belongs, using its default source\&. 
.SS "int GetTriedBucket (const \fBuint256\fP & nKey, const \fBNetGroupManager\fP & netgroupman) const"

.PP
Calculate in which "tried" bucket this entry belongs\&. 
.SS "bool IsTerrible (\fBNodeSeconds\fP now = \fR\fBNow\fP<\fBNodeSeconds\fP>()\fP) const"

.PP
Determine whether the statistics about this entry are bad enough so that it can just be deleted\&. 
.SS "SERIALIZE_METHODS (\fBAddrInfo\fP , obj )\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "bool fInTried {false}"

.PP
in tried set? (memory only) 
.SS "\fBNodeSeconds\fP m_last_count_attempt {0s}"

.PP
last counted attempt (memory only) 
.SS "\fBNodeSeconds\fP m_last_success {0s}"

.PP
last successful connection by us 
.SS "\fBNodeSeconds\fP m_last_try {0s}"

.PP
last try whatsoever by us (memory only) 
.SS "int nAttempts {0}"

.PP
connection attempts since last successful attempt 
.SS "int nRandomPos {\-1}\fR [mutable]\fP"

.PP
position in vRandom 
.SS "int nRefCount {0}"

.PP
reference count in new sets (memory only) 
.SS "\fBCNetAddr\fP source"

.PP
where knowledge about this address first came from 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
