.TH "AddressPosition" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddressPosition
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <addrman\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (\fBAddressPosition\fP other)"
.br
.ti -1c
.RI "\fBAddressPosition\fP (bool tried_in, int multiplicity_in, int bucket_in, int position_in)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const bool \fBtried\fP"
.br
.ti -1c
.RI "const int \fBmultiplicity\fP"
.br
.ti -1c
.RI "const int \fBbucket\fP"
.br
.ti -1c
.RI "const int \fBposition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Location information for an address in \fBAddrMan\fP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAddressPosition\fP (bool tried_in, int multiplicity_in, int bucket_in, int position_in)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool operator== (\fBAddressPosition\fP other)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "const int bucket"

.SS "const int multiplicity"

.SS "const int position"

.SS "const bool tried"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
