.TH "src/test/fuzz/addrman.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/addrman.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <addrdb\&.h>\fP
.br
\fR#include <addrman\&.h>\fP
.br
\fR#include <addrman_impl\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <merkleblock\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <test/fuzz/util/net\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/asmap\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <ctime>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_addrman\fP ()"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (data_stream_addr_man,\&.\fBinit\fP=\fBinitialize_addrman\fP)"
.br
.ti -1c
.RI "\fBCNetAddr\fP \fBRandAddr\fP (\fBFuzzedDataProvider\fP &fuzzed_data_provider, \fBFastRandomContext\fP &fast_random_context)"
.br
.ti -1c
.RI "void \fBFillAddrman\fP (\fBAddrMan\fP &addrman, \fBFuzzedDataProvider\fP &fuzzed_data_provider)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (addrman,\&.\fBinit\fP=\fBinitialize_addrman\fP)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (addrman_serdeser,\&.\fBinit\fP=\fBinitialize_addrman\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void FillAddrman (\fBAddrMan\fP & addrman, \fBFuzzedDataProvider\fP & fuzzed_data_provider)"
Fill addrman with lots of addresses from lots of sources\&. 
.SS "FUZZ_TARGET (addrman , \&. init = \fR\fBinitialize_addrman\fP\fP)"

.SS "FUZZ_TARGET (addrman_serdeser , \&. init = \fR\fBinitialize_addrman\fP\fP)"

.SS "FUZZ_TARGET (data_stream_addr_man , \&. init = \fR\fBinitialize_addrman\fP\fP)"

.SS "void initialize_addrman ()"

.SS "\fBCNetAddr\fP RandAddr (\fBFuzzedDataProvider\fP & fuzzed_data_provider, \fBFastRandomContext\fP & fast_random_context)"
Generate a random address\&. Always returns a valid address\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
