.TH "src/addrman.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/addrman.h
.SH SYNOPSIS
.br
.PP
\fR#include <netaddress\&.h>\fP
.br
\fR#include <netgroup\&.h>\fP
.br
\fR#include <protocol\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <unordered_set>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBInvalidAddrManVersionError\fP"
.br
.ti -1c
.RI "struct \fBAddressPosition\fP"
.br
.ti -1c
.RI "class \fBAddrMan\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
