.TH "AddressBookSortFilterProxyModel" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddressBookSortFilterProxyModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits QSortFilterProxyModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddressBookSortFilterProxyModel\fP (const QString &type, QObject *parent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBfilterAcceptsRow\fP (int row, const QModelIndex &parent) const override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAddressBookSortFilterProxyModel\fP (const QString & type, QObject * parent)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool filterAcceptsRow (int row, const QModelIndex & parent) const\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
