.TH "AES256CBCEncrypt" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AES256CBCEncrypt
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <aes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAES256CBCEncrypt\fP (const unsigned char key[AES256_KEYSIZE], const unsigned char ivIn[AES_BLOCKSIZE], bool padIn)"
.br
.ti -1c
.RI "\fB~AES256CBCEncrypt\fP ()"
.br
.ti -1c
.RI "int \fBEncrypt\fP (const unsigned char *data, int size, unsigned char *out) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAES256CBCEncrypt\fP (const unsigned char key[AES256_KEYSIZE], const unsigned char ivIn[AES_BLOCKSIZE], bool padIn)"

.SS "~\fBAES256CBCEncrypt\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "int Encrypt (const unsigned char * data, int size, unsigned char * out) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
