.TH "AmountSpinBox" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AmountSpinBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits QAbstractSpinBox\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBvalueChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAmountSpinBox\fP (QWidget *parent)"
.br
.ti -1c
.RI "QValidator::State \fBvalidate\fP (QString &text, int &pos) const override"
.br
.ti -1c
.RI "void \fBfixup\fP (QString &input) const override"
.br
.ti -1c
.RI "\fBCAmount\fP \fBvalue\fP (bool *valid_out=nullptr) const"
.br
.ti -1c
.RI "void \fBsetValue\fP (const \fBCAmount\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBSetAllowEmpty\fP (bool allow)"
.br
.ti -1c
.RI "void \fBSetMinValue\fP (const \fBCAmount\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBSetMaxValue\fP (const \fBCAmount\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBstepBy\fP (int steps) override"
.br
.ti -1c
.RI "void \fBsetDisplayUnit\fP (\fBBitcoinUnit\fP unit)"
.br
.ti -1c
.RI "void \fBsetSingleStep\fP (const \fBCAmount\fP &step)"
.br
.ti -1c
.RI "QSize \fBminimumSizeHint\fP () const override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBevent\fP (QEvent *event) override"
.br
.ti -1c
.RI "StepEnabled \fBstepEnabled\fP () const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
QSpinBox that uses fixed-point numbers internally and uses our own formatting/parsing functions\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAmountSpinBox\fP (QWidget * parent)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool event (QEvent * event)\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP"

.SS "void fixup (QString & input) const\fR [inline]\fP, \fR [override]\fP"

.SS "QSize minimumSizeHint () const\fR [inline]\fP, \fR [override]\fP"

.SS "void SetAllowEmpty (bool allow)\fR [inline]\fP"

.SS "void setDisplayUnit (\fBBitcoinUnit\fP unit)\fR [inline]\fP"

.SS "void SetMaxValue (const \fBCAmount\fP & value)\fR [inline]\fP"

.SS "void SetMinValue (const \fBCAmount\fP & value)\fR [inline]\fP"

.SS "void setSingleStep (const \fBCAmount\fP & step)\fR [inline]\fP"

.SS "void setValue (const \fBCAmount\fP & value)\fR [inline]\fP"

.SS "void stepBy (int steps)\fR [inline]\fP, \fR [override]\fP"

.SS "StepEnabled stepEnabled () const\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP"

.SS "QValidator::State validate (QString & text, int & pos) const\fR [inline]\fP, \fR [override]\fP"

.SS "\fBCAmount\fP value (bool * valid_out = \fRnullptr\fP) const\fR [inline]\fP"

.SS "void valueChanged ()\fR [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
