.TH "IterationLogic" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IterationLogic
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nanobench\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterationLogic\fP (\fBBench\fP const &bench)"
.br
.ti -1c
.RI "\fBIterationLogic\fP (IterationLogic &&)=delete"
.br
.ti -1c
.RI "\fBIterationLogic\fP & \fBoperator=\fP (\fBIterationLogic\fP &&)=delete"
.br
.ti -1c
.RI "\fBIterationLogic\fP (IterationLogic const &)=delete"
.br
.ti -1c
.RI "\fBIterationLogic\fP & \fBoperator=\fP (\fBIterationLogic\fP const &)=delete"
.br
.ti -1c
.RI "\fB~IterationLogic\fP ()"
.br
.ti -1c
.RI "\fBANKERL_NANOBENCH\fP (NODISCARD) uint64_t numIters() const noexcept"
.br
.ti -1c
.RI "void \fBadd\fP (std::chrono::nanoseconds elapsed, \fBPerformanceCounters\fP const &pc) noexcept"
.br
.ti -1c
.RI "void \fBmoveResultTo\fP (std::vector< \fBResult\fP > &results) noexcept"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IterationLogic (\fBBench\fP const & bench)\fR [explicit]\fP"

.SS "IterationLogic (IterationLogic && )\fR [delete]\fP"

.SS "IterationLogic (IterationLogic const & )\fR [delete]\fP"

.SS "~\fBIterationLogic\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void add (std::chrono::nanoseconds elapsed, \fBPerformanceCounters\fP const & pc)\fR [noexcept]\fP"

.SS "ANKERL_NANOBENCH (NODISCARD ) const\fR [noexcept]\fP"

.SS "void moveResultTo (std::vector< \fBResult\fP > & results)\fR [noexcept]\fP"

.SS "\fBIterationLogic\fP & operator= (\fBIterationLogic\fP && )\fR [delete]\fP"

.SS "\fBIterationLogic\fP & operator= (\fBIterationLogic\fP const & )\fR [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
