.TH "PerformanceCounters" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PerformanceCounters
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nanobench\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerformanceCounters\fP (PerformanceCounters const &)=delete"
.br
.ti -1c
.RI "\fBPerformanceCounters\fP (PerformanceCounters &&)=delete"
.br
.ti -1c
.RI "\fBPerformanceCounters\fP & \fBoperator=\fP (\fBPerformanceCounters\fP const &)=delete"
.br
.ti -1c
.RI "\fBPerformanceCounters\fP & \fBoperator=\fP (\fBPerformanceCounters\fP &&)=delete"
.br
.ti -1c
.RI "\fBPerformanceCounters\fP ()"
.br
.ti -1c
.RI "\fB~PerformanceCounters\fP ()"
.br
.ti -1c
.RI "void \fBbeginMeasure\fP ()"
.br
.ti -1c
.RI "void \fBendMeasure\fP ()"
.br
.ti -1c
.RI "void \fBupdateResults\fP (uint64_t numIters)"
.br
.ti -1c
.RI "\fBANKERL_NANOBENCH\fP (NODISCARD) \fBPerfCountSet\fP< uint64_t > const &val() const noexcept"
.br
.ti -1c
.RI "\fBANKERL_NANOBENCH\fP (NODISCARD) \fBPerfCountSet\fP< bool > const &has() const noexcept"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PerformanceCounters (PerformanceCounters const & )\fR [delete]\fP"

.SS "PerformanceCounters (PerformanceCounters && )\fR [delete]\fP"

.SS "PerformanceCounters ()"

.SS "~\fBPerformanceCounters\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "ANKERL_NANOBENCH (NODISCARD ) const &\fR [noexcept]\fP"

.SS "ANKERL_NANOBENCH (NODISCARD ) const &\fR [noexcept]\fP"

.SS "void beginMeasure ()"

.SS "void endMeasure ()"

.SS "\fBPerformanceCounters\fP & operator= (\fBPerformanceCounters\fP && )\fR [delete]\fP"

.SS "\fBPerformanceCounters\fP & operator= (\fBPerformanceCounters\fP const & )\fR [delete]\fP"

.SS "void updateResults (uint64_t numIters)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
