.TH "Config" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nanobench\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfig\fP ()"
.br
.ti -1c
.RI "\fB~Config\fP ()"
.br
.ti -1c
.RI "\fBConfig\fP & \fBoperator=\fP (\fBConfig\fP const &other)"
.br
.ti -1c
.RI "\fBConfig\fP & \fBoperator=\fP (\fBConfig\fP &&other) noexcept(\fBANKERL_NANOBENCH\fP(NOEXCEPT_STRING_MOVE))"
.br
.ti -1c
.RI "\fBConfig\fP (Config const &other)"
.br
.ti -1c
.RI "\fBConfig\fP (Config &&other) noexcept"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBmBenchmarkTitle\fP = 'benchmark'"
.br
.ti -1c
.RI "std::string \fBmBenchmarkName\fP = 'noname'"
.br
.ti -1c
.RI "std::string \fBmUnit\fP = 'op'"
.br
.ti -1c
.RI "double \fBmBatch\fP = 1\&.0"
.br
.ti -1c
.RI "double \fBmComplexityN\fP = \-1\&.0"
.br
.ti -1c
.RI "size_t \fBmNumEpochs\fP = 11"
.br
.ti -1c
.RI "size_t \fBmClockResolutionMultiple\fP = static_cast<size_t>(1000)"
.br
.ti -1c
.RI "std::chrono::nanoseconds \fBmMaxEpochTime\fP = std::chrono::milliseconds(100)"
.br
.ti -1c
.RI "std::chrono::nanoseconds \fBmMinEpochTime\fP = std::chrono::milliseconds(1)"
.br
.ti -1c
.RI "uint64_t \fBmMinEpochIterations\fP {1}"
.br
.ti -1c
.RI "uint64_t \fBmEpochIterations\fP {0}"
.br
.ti -1c
.RI "uint64_t \fBmWarmup\fP = 0"
.br
.ti -1c
.RI "std::ostream * \fBmOut\fP = nullptr"
.br
.ti -1c
.RI "std::chrono::duration< double > \fBmTimeUnit\fP = std::chrono::nanoseconds{1}"
.br
.ti -1c
.RI "std::string \fBmTimeUnitName\fP = 'ns'"
.br
.ti -1c
.RI "bool \fBmShowPerformanceCounters\fP = true"
.br
.ti -1c
.RI "bool \fBmIsRelative\fP = false"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::string > \fBmContext\fP {}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Config ()"

.SS "~\fBConfig\fP ()"

.SS "Config (Config const & other)"

.SS "Config (Config && other)\fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBConfig\fP & operator= (\fBConfig\fP && other)\fR [noexcept]\fP"

.SS "\fBConfig\fP & operator= (\fBConfig\fP const & other)"

.SH "Field Documentation"
.PP 
.SS "double mBatch = 1\&.0"

.SS "std::string mBenchmarkName = 'noname'"

.SS "std::string mBenchmarkTitle = 'benchmark'"

.SS "size_t mClockResolutionMultiple = static_cast<size_t>(1000)"

.SS "double mComplexityN = \-1\&.0"

.SS "std::unordered_map<std::string, std::string> mContext {}"

.SS "uint64_t mEpochIterations {0}"

.SS "bool mIsRelative = false"

.SS "std::chrono::nanoseconds mMaxEpochTime = std::chrono::milliseconds(100)"

.SS "uint64_t mMinEpochIterations {1}"

.SS "std::chrono::nanoseconds mMinEpochTime = std::chrono::milliseconds(1)"

.SS "size_t mNumEpochs = 11"

.SS "std::ostream* mOut = nullptr"

.SS "bool mShowPerformanceCounters = true"

.SS "std::chrono::duration<double> mTimeUnit = std::chrono::nanoseconds{1}"

.SS "std::string mTimeUnitName = 'ns'"

.SS "std::string mUnit = 'op'"

.SS "uint64_t mWarmup = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
