.TH "PerfCountSet< T >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PerfCountSet< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <nanobench\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBT\fP \fBpageFaults\fP {}"
.br
.ti -1c
.RI "\fBT\fP \fBcpuCycles\fP {}"
.br
.ti -1c
.RI "\fBT\fP \fBcontextSwitches\fP {}"
.br
.ti -1c
.RI "\fBT\fP \fBinstructions\fP {}"
.br
.ti -1c
.RI "\fBT\fP \fBbranchInstructions\fP {}"
.br
.ti -1c
.RI "\fBT\fP \fBbranchMisses\fP {}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "template<typename \fBT\fP> \fBT\fP branchInstructions {}"

.SS "template<typename \fBT\fP> \fBT\fP branchMisses {}"

.SS "template<typename \fBT\fP> \fBT\fP contextSwitches {}"

.SS "template<typename \fBT\fP> \fBT\fP cpuCycles {}"

.SS "template<typename \fBT\fP> \fBT\fP instructions {}"

.SS "template<typename \fBT\fP> \fBT\fP pageFaults {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
