.TH "src/util/any.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/any.h
.SH SYNOPSIS
.br
.PP
\fR#include <any>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButil\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP * \fBAnyPtr\fP (const std::any &any) noexcept"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
