.TH "Arena::Stats" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arena::Stats
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lockedpool\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBused\fP"
.br
.ti -1c
.RI "size_t \fBfree\fP"
.br
.ti -1c
.RI "size_t \fBtotal\fP"
.br
.ti -1c
.RI "size_t \fBchunks_used\fP"
.br
.ti -1c
.RI "size_t \fBchunks_free\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Memory statistics\&. 
.SH "Field Documentation"
.PP 
.SS "size_t chunks_free"

.SS "size_t chunks_used"

.SS "size_t free"

.SS "size_t total"

.SS "size_t used"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
