.TH "src/common/args.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/common/args.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/args\&.h>\fP
.br
\fR#include <chainparamsbase\&.h>\fP
.br
\fR#include <common/settings\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/fs_helpers\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <map>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <string>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <variant>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBKeyInfo\fP \fBInterpretKey\fP (std::string key)"
.br
.ti -1c
.RI "std::optional< \fBcommon::SettingsValue\fP > \fBInterpretValue\fP (const \fBKeyInfo\fP &key, const std::string *value, unsigned int \fBflags\fP, std::string &error)"
.br
.ti -1c
.RI "std::optional< std::string > \fBSettingToString\fP (const \fBcommon::SettingsValue\fP &value)"
.br
.ti -1c
.RI "std::string \fBSettingToString\fP (const \fBcommon::SettingsValue\fP &value, const std::string &strDefault)"
.br
.ti -1c
.RI "std::optional< int64_t > \fBSettingToInt\fP (const \fBcommon::SettingsValue\fP &value)"
.br
.ti -1c
.RI "int64_t \fBSettingToInt\fP (const \fBcommon::SettingsValue\fP &value, int64_t nDefault)"
.br
.ti -1c
.RI "std::optional< bool > \fBSettingToBool\fP (const \fBcommon::SettingsValue\fP &value)"
.br
.ti -1c
.RI "bool \fBSettingToBool\fP (const \fBcommon::SettingsValue\fP &value, bool fDefault)"
.br
.ti -1c
.RI "bool \fBHelpRequested\fP (const \fBArgsManager\fP &\fBargs\fP)"
.br
.ti -1c
.RI "void \fBSetupHelpOptions\fP (\fBArgsManager\fP &\fBargs\fP)"
.br
.ti -1c
.RI "std::string \fBHelpMessageGroup\fP (const std::string &message)"
.br
.ti -1c
.RI "std::string \fBHelpMessageOpt\fP (const std::string &option, const std::string &message)"
.br
.ti -1c
.RI "bool \fBHasTestOption\fP (const \fBArgsManager\fP &\fBargs\fP, const std::string &test_option)"
.br
.ti -1c
.RI "\fBfs::path\fP \fBGetDefaultDataDir\fP ()"
.br
.ti -1c
.RI "bool \fBCheckDataDirOption\fP (const \fBArgsManager\fP &\fBargs\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char *const \fBBITCOIN_CONF_FILENAME\fP = 'bitcoin\&.conf'"
.br
.ti -1c
.RI "const char *const \fBBITCOIN_SETTINGS_FILENAME\fP = 'settings\&.json'"
.br
.ti -1c
.RI "\fBArgsManager\fP \fBgArgs\fP"
.br
.ti -1c
.RI "const std::vector< std::string > \fBTEST_OPTIONS_DOC\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool CheckDataDirOption (const \fBArgsManager\fP & args)"

.SS "\fBfs::path\fP GetDefaultDataDir ()"

.SS "bool HasTestOption (const \fBArgsManager\fP & args, const std::string & test_option)"
Checks if a particular test option is present in -test command-line arg options 
.SS "std::string HelpMessageGroup (const std::string & message)"
\fBFormat\fP a string to be used as group of options in help messages

.PP
\fBParameters\fP
.RS 4
\fImessage\fP Group name (e\&.g\&. "RPC server options:") 
.RE
.PP
\fBReturns\fP
.RS 4
the formatted string 
.RE
.PP

.SS "std::string HelpMessageOpt (const std::string & option, const std::string & message)"
\fBFormat\fP a string to be used as option description in help messages

.PP
\fBParameters\fP
.RS 4
\fIoption\fP Option message (e\&.g\&. "-rpcuser=<user>") 
.br
\fImessage\fP Option description (e\&.g\&. "Username for JSON-RPC connections") 
.RE
.PP
\fBReturns\fP
.RS 4
the formatted string 
.RE
.PP

.SS "bool HelpRequested (const \fBArgsManager\fP & args)"

.PP
\fBReturns\fP
.RS 4
true if help has been requested via a command-line arg 
.RE
.PP

.SS "\fBKeyInfo\fP InterpretKey (std::string key)"
Parse "name", "section\&.name", "noname", "section\&.noname" settings keys\&.

.PP
\fBNote\fP
.RS 4
Where an option was negated can be later checked using the IsArgNegated() method\&. One use case for this is to have a way to disable options that are not normally boolean (e\&.g\&. using -nodebuglogfile to request that debug log output is not sent to any file at all)\&. 
.RE
.PP

.SS "std::optional< \fBcommon::SettingsValue\fP > InterpretValue (const \fBKeyInfo\fP & key, const std::string * value, unsigned int flags, std::string & error)"
Interpret settings value based on registered flags\&.

.PP
\fBParameters\fP
.RS 4
\fIkey\fP key information to know if key was negated 
.br
\fIvalue\fP string value of setting to be parsed 
.br
\fIflags\fP \fBArgsManager\fP registered argument flags 
.br
\fIerror\fP Error description if settings value is not valid
.RE
.PP
\fBReturns\fP
.RS 4
parsed settings value if it is valid, otherwise nullopt accompanied by a descriptive error string 
.RE
.PP

.SS "std::optional< bool > SettingToBool (const \fBcommon::SettingsValue\fP & value)"

.SS "bool SettingToBool (const \fBcommon::SettingsValue\fP & value, bool fDefault)"

.SS "std::optional< int64_t > SettingToInt (const \fBcommon::SettingsValue\fP & value)"

.SS "int64_t SettingToInt (const \fBcommon::SettingsValue\fP & value, int64_t nDefault)"

.SS "std::optional< std::string > SettingToString (const \fBcommon::SettingsValue\fP & value)"

.SS "std::string SettingToString (const \fBcommon::SettingsValue\fP & value, const std::string & strDefault)"

.SS "void SetupHelpOptions (\fBArgsManager\fP & args)"
Add help options to the args manager 
.SH "Variable Documentation"
.PP 
.SS "const char* const BITCOIN_CONF_FILENAME = 'bitcoin\&.conf'"

.SS "const char* const BITCOIN_SETTINGS_FILENAME = 'settings\&.json'"

.SS "\fBArgsManager\fP gArgs"

.SS "const std::vector<std::string> TEST_OPTIONS_DOC"
\fBInitial value:\fP
.nf
{
    "addrman (use deterministic addrman)",
    "reindex_after_failure_noninteractive_yes (When asked for a reindex after failure interactively, simulate as\-if answered with 'yes')",
    "bip94 (enforce BIP94 consensus rules)",
}
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
