.TH "ArgsManager::Arg" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArgsManager::Arg
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <args\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBm_help_param\fP"
.br
.ti -1c
.RI "std::string \fBm_help_text\fP"
.br
.ti -1c
.RI "unsigned int \fBm_flags\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned int m_flags"

.SS "std::string m_help_param"

.SS "std::string m_help_text"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
