.TH "ArgsManager::Command" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArgsManager::Command
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <args\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBcommand\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBargs\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "std::vector<std::string> args"
If command is non-empty: Any args that followed it If command is empty: The unregistered command and any args that followed it 
.SS "std::string command"
The command (if one has been registered with AddCommand), or empty 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
