.TH "ArgsMergeTestingSetup" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArgsMergeTestingSetup
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBasicTestingSetup\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAction\fP { \fBNONE\fP, \fBSET\fP, \fBNEGATE\fP, \fBSECTION_SET\fP, \fBSECTION_NEGATE\fP }"
.br
.ti -1c
.RI "using \fBActionList\fP = \fBAction\fP[\fBMAX_ACTIONS\fP]"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Fn> void \fBForEachMergeSetup\fP (Fn &&fn)"
.br
.RI "Enumerate all possible test configurations\&. "
.ti -1c
.RI "std::vector< std::string > \fBGetValues\fP (const \fBActionList\fP &actions, const std::string &section, const std::string &\fBname\fP, const std::string &value_prefix)"
.br
.RI "Translate actions into a list of <key>=

.PP
setting strings\&. "
.in -1c

Public Member Functions inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "void \fBSeedRandomForTest\fP (\fBSeedRand\fP seed)"
.br
.ti -1c
.RI "\fBBasicTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~BasicTestingSetup\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBMAX_ACTIONS\fP = 3"
.br
.in -1c
.SS "Additional Inherited Members"


Data Fields inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "\fButil::SignalInterrupt\fP \fBm_interrupt\fP"
.br
.ti -1c
.RI "\fBnode::NodeContext\fP \fBm_node\fP"
.br
.ti -1c
.RI "\fBFastRandomContext\fP \fBm_rng\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_root\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_lock\fP"
.br
.ti -1c
.RI "bool \fBm_has_custom_datadir\fP {false}"
.br
.ti -1c
.RI "\fBArgsManager\fP \fBm_args\fP"
.br
.RI "Test-specific arguments and settings\&. "
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBActionList\fP = \fBAction\fP[\fBMAX_ACTIONS\fP]"

.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBAction\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINONE \fP
.TP
\f(BISET \fP
.TP
\f(BINEGATE \fP
.TP
\f(BISECTION_SET \fP
.TP
\f(BISECTION_NEGATE \fP
.SH "Member Function Documentation"
.PP 
.SS "template<typename Fn> void ForEachMergeSetup (Fn && fn)\fR [inline]\fP"

.PP
Enumerate all possible test configurations\&. 
.SS "std::vector< std::string > GetValues (const \fBActionList\fP & actions, const std::string & section, const std::string & name, const std::string & value_prefix)\fR [inline]\fP"

.PP
Translate actions into a list of <key>=

.PP
setting strings\&. 
.SH "Field Documentation"
.PP 
.SS "int MAX_ACTIONS = 3\fR [static]\fP, \fR [constexpr]\fP"
Max number of actions to sequence together\&. Can decrease this when debugging to make test results easier to understand\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
