.TH "AskPassphraseDialog" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AskPassphraseDialog
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <askpassphrasedialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBEncrypt\fP, \fBUnlock\fP, \fBChangePass\fP, \fBUnlockMigration\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAskPassphraseDialog\fP (\fBMode\fP mode, QWidget *parent, \fBSecureString\fP *passphrase_out=nullptr)"
.br
.ti -1c
.RI "\fB~AskPassphraseDialog\fP ()"
.br
.ti -1c
.RI "void \fBaccept\fP () override"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBWalletModel\fP *model)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBevent\fP (QEvent *event) override"
.br
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *object, QEvent *\fBevent\fP) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Multifunctional dialog to ask for passphrases\&. Used for encryption, unlocking, and changing the passphrase\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIEncrypt \fP
Ask passphrase twice and encrypt 
.TP
\f(BIUnlock \fP
Ask passphrase and unlock 
.TP
\f(BIChangePass \fP
Ask old passphrase + new passphrase twice 
.TP
\f(BIUnlockMigration \fP
Ask passphrase for unlocking during migration 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAskPassphraseDialog\fP (\fBMode\fP mode, QWidget * parent, \fBSecureString\fP * passphrase_out = \fRnullptr\fP)\fR [explicit]\fP"

.SS "~\fBAskPassphraseDialog\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void accept ()\fR [override]\fP"

.SS "bool event (QEvent * event)\fR [override]\fP, \fR [protected]\fP"

.SS "bool eventFilter (QObject * object, QEvent * event)\fR [override]\fP, \fR [protected]\fP"

.SS "void setModel (\fBWalletModel\fP * model)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
