.TH "src/util/asmap.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/asmap.h
.SH SYNOPSIS
.br
.PP
\fR#include <util/fs\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBInterpret\fP (const std::vector< bool > &asmap, const std::vector< bool > &ip)"
.br
.ti -1c
.RI "bool \fBSanityCheckASMap\fP (const std::vector< bool > &asmap, int bits)"
.br
.ti -1c
.RI "std::vector< bool > \fBDecodeAsmap\fP (\fBfs::path\fP path)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::vector< bool > DecodeAsmap (\fBfs::path\fP path)"
Read asmap from provided binary file 
.SS "uint32_t Interpret (const std::vector< bool > & asmap, const std::vector< bool > & ip)"

.SS "bool SanityCheckASMap (const std::vector< bool > & asmap, int bits)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
