.TH "AssumeutxoHash" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AssumeutxoHash
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <chainparams\&.h>\fP
.PP
Inherits \fBBaseHash< uint256 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssumeutxoHash\fP (const \fBuint256\fP &hash)"
.br
.in -1c

Public Member Functions inherited from \fBBaseHash< uint256 >\fP
.in +1c
.ti -1c
.RI "\fBBaseHash\fP ()"
.br
.ti -1c
.RI "unsigned char * \fBbegin\fP ()"
.br
.ti -1c
.RI "unsigned char * \fBend\fP ()"
.br
.ti -1c
.RI "\fBoperator std::vector< unsigned char >\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBBaseHash\fP< \fBuint256\fP > &other) const noexcept"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBBaseHash\fP< \fBuint256\fP > &other) const noexcept"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBBaseHash< uint256 >\fP
.in +1c
.ti -1c
.RI "\fBuint256\fP \fBm_hash\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAssumeutxoHash\fP (const \fBuint256\fP & hash)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
