.TH "BanTableModel" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BanTableModel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bantablemodel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBColumnIndex\fP { \fBAddress\fP = 0, \fBBantime\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBanTableModel\fP (\fBinterfaces::Node\fP &\fBnode\fP, QObject *parent)"
.br
.ti -1c
.RI "\fB~BanTableModel\fP ()"
.br
.ti -1c
.RI "void \fBstartAutoRefresh\fP ()"
.br
.ti -1c
.RI "void \fBstopAutoRefresh\fP ()"
.br
.in -1c
.SS "Methods overridden from QAbstractTableModel"

.in +1c
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const override"
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const override"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &\fBindex\fP, int role) const override"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const override"
.br
.ti -1c
.RI "QModelIndex \fBindex\fP (int row, int column, const QModelIndex &parent) const override"
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &\fBindex\fP) const override"
.br
.ti -1c
.RI "void \fBsort\fP (int column, Qt::SortOrder order) override"
.br
.ti -1c
.RI "bool \fBshouldShow\fP ()"
.br
.ti -1c
.RI "bool \fBunban\fP (const QModelIndex &\fBindex\fP)"
.br
.ti -1c
.RI "void \fBrefresh\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Qt model providing information about banned peers, similar to the "getpeerinfo" RPC call\&. Used by the rpc console UI\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBColumnIndex\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIAddress \fP
.TP
\f(BIBantime \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBanTableModel\fP (\fBinterfaces::Node\fP & node, QObject * parent)\fR [explicit]\fP"

.SS "~\fBBanTableModel\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int columnCount (const QModelIndex & parent) const\fR [override]\fP"

.SS "QVariant data (const QModelIndex & index, int role) const\fR [override]\fP"

.SS "Qt::ItemFlags flags (const QModelIndex & index) const\fR [override]\fP"

.SS "QVariant headerData (int section, Qt::Orientation orientation, int role) const\fR [override]\fP"

.SS "QModelIndex index (int row, int column, const QModelIndex & parent) const\fR [override]\fP"

.SS "void refresh ()\fR [slot]\fP"

.SS "int rowCount (const QModelIndex & parent) const\fR [override]\fP"

.SS "bool shouldShow ()"

.SS "void sort (int column, Qt::SortOrder order)\fR [override]\fP"

.SS "void startAutoRefresh ()"

.SS "void stopAutoRefresh ()"

.SS "bool unban (const QModelIndex & index)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
