.TH "src/test/base58_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/base58_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/data/base58_encode_decode\&.json\&.h>\fP
.br
\fR#include <base58\&.h>\fP
.br
\fR#include <test/util/json\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/vector\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (base58_EncodeBase58)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (base58_DecodeBase58)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (base58_DecodeBase58 )"

.SS "BOOST_AUTO_TEST_CASE (base58_EncodeBase58 )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
