.TH "BaseHash< HashType >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseHash< HashType >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hash_type\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseHash\fP ()"
.br
.ti -1c
.RI "\fBBaseHash\fP (const HashType &in)"
.br
.ti -1c
.RI "unsigned char * \fBbegin\fP ()"
.br
.ti -1c
.RI "const unsigned char * \fBbegin\fP () const"
.br
.ti -1c
.RI "unsigned char * \fBend\fP ()"
.br
.ti -1c
.RI "const unsigned char * \fBend\fP () const"
.br
.ti -1c
.RI "\fBoperator std::vector< unsigned char >\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBBaseHash\fP< HashType > &other) const noexcept"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBBaseHash\fP< HashType > &other) const noexcept"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP ()"
.br
.ti -1c
.RI "const unsigned char * \fBdata\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "HashType \fBm_hash\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename HashType> \fBBaseHash\fP ()\fR [inline]\fP"

.SS "template<typename HashType> \fBBaseHash\fP (const HashType & in)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename HashType> unsigned char * begin ()\fR [inline]\fP"

.SS "template<typename HashType> const unsigned char * begin () const\fR [inline]\fP"

.SS "template<typename HashType> unsigned char * data ()\fR [inline]\fP"

.SS "template<typename HashType> const unsigned char * data () const\fR [inline]\fP"

.SS "template<typename HashType> unsigned char * end ()\fR [inline]\fP"

.SS "template<typename HashType> const unsigned char * end () const\fR [inline]\fP"

.SS "template<typename HashType> operator std::vector< unsigned char > () const\fR [inline]\fP"

.SS "template<typename HashType> bool operator< (const \fBBaseHash\fP< HashType > & other) const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<typename HashType> bool operator== (const \fBBaseHash\fP< HashType > & other) const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<typename HashType> size_t size () const\fR [inline]\fP"

.SS "template<typename HashType> std::string ToString () const\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "template<typename HashType> HashType m_hash\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
