.TH "src/test/fuzz/base_encode_decode.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/base_encode_decode.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <base58\&.h>\fP
.br
\fR#include <psbt\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <ranges>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFUZZ_TARGET\fP (base58_encode_decode)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (base58check_encode_decode)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (base32_encode_decode)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (base64_encode_decode)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (psbt_base64_decode)"
.br
.ti -1c
.RI "std::string_view \fBTrimStringView\fP (std::string_view str, std::string_view pattern=' \\f\\n\\r\\t\\v')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (base32_encode_decode )"

.SS "FUZZ_TARGET (base58_encode_decode )"

.SS "FUZZ_TARGET (base58check_encode_decode )"

.SS "FUZZ_TARGET (base64_encode_decode )"

.SS "FUZZ_TARGET (psbt_base64_decode )"

.SS "std::string_view TrimStringView (std::string_view str, std::string_view pattern = \fR' \\f\\n\\r\\t\\v'\fP)\fR [inline]\fP, \fR [nodiscard]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
