.TH "BaseRequestHandler" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseRequestHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAddrinfoRequestHandler\fP, \fBDefaultRequestHandler\fP, \fBGenerateToAddressRequestHandler\fP, \fBGetinfoRequestHandler\fP, and \fBNetinfoRequestHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~BaseRequestHandler\fP ()=default"
.br
.ti -1c
.RI "virtual \fBUniValue\fP \fBPrepareRequest\fP (const std::string &method, const std::vector< std::string > &\fBargs\fP)=0"
.br
.ti -1c
.RI "virtual \fBUniValue\fP \fBProcessReply\fP (const \fBUniValue\fP &batch_in)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handle the conversion from a command-line to a JSON-RPC request, as well as converting back to a JSON object that can be shown as result\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBBaseRequestHandler\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBUniValue\fP PrepareRequest (const std::string & method, const std::vector< std::string > & args)\fR [pure virtual]\fP"

.PP
Implemented in \fBAddrinfoRequestHandler\fP, \fBDefaultRequestHandler\fP, \fBGenerateToAddressRequestHandler\fP, \fBGetinfoRequestHandler\fP, and \fBNetinfoRequestHandler\fP\&.
.SS "virtual \fBUniValue\fP ProcessReply (const \fBUniValue\fP & batch_in)\fR [pure virtual]\fP"

.PP
Implemented in \fBAddrinfoRequestHandler\fP, \fBDefaultRequestHandler\fP, \fBGenerateToAddressRequestHandler\fP, \fBGetinfoRequestHandler\fP, and \fBNetinfoRequestHandler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
