.TH "BaseIndex::DB" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseIndex::DB
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <base\&.h>\fP
.PP
Inherits \fBCDBWrapper\fP\&.
.PP
Inherited by \fBTxIndex::DB\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDB\fP (const \fBfs::path\fP &path, size_t n_cache_size, bool f_memory=false, bool f_wipe=false, bool f_obfuscate=false)"
.br
.ti -1c
.RI "\fBCBlockLocator\fP \fBReadBestBlock\fP () const"
.br
.ti -1c
.RI "void \fBWriteBestBlock\fP (\fBCDBBatch\fP &batch, const \fBCBlockLocator\fP &locator)"
.br
.RI "Write block locator of the chain that the index is in sync with\&. "
.in -1c

Public Member Functions inherited from \fBCDBWrapper\fP
.in +1c
.ti -1c
.RI "\fBCDBWrapper\fP (const \fBDBParams\fP &params)"
.br
.ti -1c
.RI "\fB~CDBWrapper\fP ()"
.br
.ti -1c
.RI "\fBCDBWrapper\fP (const \fBCDBWrapper\fP &)=delete"
.br
.ti -1c
.RI "\fBCDBWrapper\fP & \fBoperator=\fP (const \fBCDBWrapper\fP &)=delete"
.br
.ti -1c
.RI "template<typename K, typename V> bool \fBRead\fP (const K &key, V &value) const"
.br
.ti -1c
.RI "template<typename K, typename V> void \fBWrite\fP (const K &key, const V &value, bool fSync=false)"
.br
.ti -1c
.RI "template<typename K> bool \fBExists\fP (const K &key) const"
.br
.ti -1c
.RI "template<typename K> void \fBErase\fP (const K &key, bool fSync=false)"
.br
.ti -1c
.RI "void \fBWriteBatch\fP (\fBCDBBatch\fP &batch, bool fSync=false)"
.br
.ti -1c
.RI "size_t \fBDynamicMemoryUsage\fP () const"
.br
.ti -1c
.RI "\fBCDBIterator\fP * \fBNewIterator\fP ()"
.br
.ti -1c
.RI "bool \fBIsEmpty\fP ()"
.br
.ti -1c
.RI "template<typename K> size_t \fBEstimateSize\fP (const K &key_begin, const K &key_end) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The database stores a block locator of the chain the database is synced to so that the index can efficiently determine the point it last stopped at\&. A locator is used instead of a simple hash of the chain tip because blocks and block index entries may not be flushed to disk until after this database is updated\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBDB\fP (const \fBfs::path\fP & path, size_t n_cache_size, bool f_memory = \fRfalse\fP, bool f_wipe = \fRfalse\fP, bool f_obfuscate = \fRfalse\fP)"

.SH "Member Function Documentation"
.PP 
.SS "\fBCBlockLocator\fP ReadBestBlock () const"
Read block locator of the chain that the index is in sync with\&. Note, the returned locator will be empty if no record exists\&. 
.SS "void WriteBestBlock (\fBCDBBatch\fP & batch, const \fBCBlockLocator\fP & locator)"

.PP
Write block locator of the chain that the index is in sync with\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
