.TH "Base" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Base \- (Un)serialize a number as raw byte or 2 hexadecimal chars\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDerived\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBase\fP ()"
.br
.ti -1c
.RI "\fBBase\fP (uint8_t data)"
.br
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBm_base_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
(Un)serialize a number as raw byte or 2 hexadecimal chars\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBase\fP ()\fR [inline]\fP"

.SS "\fBBase\fP (uint8_t data)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream> void Serialize (Stream & s) const\fR [inline]\fP"

.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "uint8_t m_base_data"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
