.TH "BasicByte" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicByte
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <span\&.h>\fP
.SH "Concept definition"
.PP 

.nf
template<typename B>
concept BasicByte =  requires { UCharCast(std::span<B>{}\&.data()); }
.PP
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
