.TH "BasicTestingSetup" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicTestingSetup
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <setup_common\&.h>\fP
.PP
Inherited by \fBArgsMergeTestingSetup\fP, \fBBlockVersionTest\fP, \fBCacheTest\fP, \fBChainMergeTestingSetup\fP, \fBChainTestingSetup\fP, \fBEnvTestingSetup\fP, \fBEraseParallelTest\fP, \fBEraseTest\fP, \fBFlushTest\fP, \fBGenerationsTest\fP, \fBHitRateTest\fP, \fBInitTestSetup\fP, \fBLogSetup\fP, \fBMergeTestingSetup\fP, \fBPCPTestingSetup\fP, \fBScriptTest\fP, \fBSigHashTest\fP, \fBUpdateTest\fP, \fBBloomTest\fP, \fBCryptoTest\fP, and \fBInitWalletDirTestingSetup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSeedRandomForTest\fP (\fBSeedRand\fP seed)"
.br
.ti -1c
.RI "\fBBasicTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~BasicTestingSetup\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButil::SignalInterrupt\fP \fBm_interrupt\fP"
.br
.ti -1c
.RI "\fBnode::NodeContext\fP \fBm_node\fP"
.br
.ti -1c
.RI "\fBFastRandomContext\fP \fBm_rng\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_root\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_lock\fP"
.br
.ti -1c
.RI "bool \fBm_has_custom_datadir\fP {false}"
.br
.ti -1c
.RI "\fBArgsManager\fP \fBm_args\fP"
.br
.RI "Test-specific arguments and settings\&. "
.in -1c
.SH "Detailed Description"
.PP 
Basic testing setup\&. This just configures logging, data dir and chain parameters\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBasicTestingSetup\fP (const \fBChainType\fP chainType = \fR\fBChainType::MAIN\fP\fP, \fBTestOpts\fP opts = \fR{}\fP)\fR [explicit]\fP"

.SS "~\fBBasicTestingSetup\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void SeedRandomForTest (\fBSeedRand\fP seed)\fR [inline]\fP"
Seed the global RNG state and m_rng for testing and log the seed value\&. This affects all randomness, except \fBGetStrongRandBytes()\fP\&. 
.SH "Field Documentation"
.PP 
.SS "\fBArgsManager\fP m_args"

.PP
Test-specific arguments and settings\&. This member is intended to be the primary source of settings for code being tested by unit tests\&. It exists to make tests more self-contained and reduce reliance on global state\&.

.PP
Usage guidelines:
.IP "1." 4
Prefer using m_args where possible in test code\&.
.IP "2." 4
If m_args is not accessible, use m_node\&.args as a fallback\&.
.IP "3." 4
Avoid direct references to gArgs in test code\&.
.PP

.PP
Note: Currently, m_node\&.args points to gArgs for backwards compatibility\&. In the future, it will point to m_args to further isolate test environments\&.

.PP
\fBSee also\fP
.RS 4
https://github.com/bitcoin/bitcoin/issues/25055 \fBfor\fP additional context\&. 
.RE
.PP

.SS "bool m_has_custom_datadir {false}"

.SS "\fButil::SignalInterrupt\fP m_interrupt"

.SS "\fBnode::NodeContext\fP m_node"

.SS "\fBfs::path\fP m_path_lock"

.SS "\fBfs::path\fP m_path_root"

.SS "\fBFastRandomContext\fP m_rng"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
