.TH "src/util/batchpriority.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/batchpriority.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <logging\&.h>\fP
.br
\fR#include <util/syserror\&.h>\fP
.br
\fR#include <sched\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBScheduleBatchPriority\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ScheduleBatchPriority ()"
On platforms that support it, tell the kernel the calling thread is CPU-intensive and non-interactive\&. See SCHED_BATCH in sched(7) for details\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
