.TH "Logger" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <logging\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBufferedLog\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLogPrintStr\fP (std::string_view str, \fBSourceLocation\fP &&source_loc, \fBBCLog::LogFlags\fP category, \fBBCLog::Level\fP level, bool should_ratelimit) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "bool \fBEnabled\fP () const \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "std::list< std::function< void(conststd::string &)> >::iterator \fBPushBackCallback\fP (std::function< void(const std::string &)> fun) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "void \fBDeleteCallback\fP (std::list< std::function< void(const std::string &)> >::iterator it) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "size_t \fBNumConnections\fP ()"
.br
.ti -1c
.RI "bool \fBStartLogging\fP () \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "void \fBDisconnectTestLogger\fP () \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "void \fBSetRateLimiting\fP (std::shared_ptr< \fBLogRateLimiter\fP > limiter) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "void \fBDisableLogging\fP () \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "void \fBShrinkDebugFile\fP ()"
.br
.ti -1c
.RI "std::unordered_map< \fBLogFlags\fP, \fBLevel\fP > \fBCategoryLevels\fP () const \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "void \fBSetCategoryLogLevel\fP (const std::unordered_map< \fBLogFlags\fP, \fBLevel\fP > &levels) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "void \fBAddCategoryLogLevel\fP (\fBLogFlags\fP category, \fBLevel\fP level)"
.br
.ti -1c
.RI "bool \fBSetCategoryLogLevel\fP (std::string_view category_str, std::string_view level_str) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "\fBLevel\fP \fBLogLevel\fP () const"
.br
.ti -1c
.RI "void \fBSetLogLevel\fP (\fBLevel\fP level)"
.br
.ti -1c
.RI "bool \fBSetLogLevel\fP (std::string_view level)"
.br
.ti -1c
.RI "\fBCategoryMask\fP \fBGetCategoryMask\fP () const"
.br
.ti -1c
.RI "void \fBEnableCategory\fP (\fBLogFlags\fP flag)"
.br
.ti -1c
.RI "bool \fBEnableCategory\fP (std::string_view str)"
.br
.ti -1c
.RI "void \fBDisableCategory\fP (\fBLogFlags\fP flag)"
.br
.ti -1c
.RI "bool \fBDisableCategory\fP (std::string_view str)"
.br
.ti -1c
.RI "bool \fBWillLogCategory\fP (\fBLogFlags\fP category) const"
.br
.ti -1c
.RI "bool \fBWillLogCategoryLevel\fP (\fBLogFlags\fP category, \fBLevel\fP level) const \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_cs)"
.br
.ti -1c
.RI "std::vector< \fBLogCategory\fP > \fBLogCategoriesList\fP () const"
.br
.ti -1c
.RI "std::string \fBLogCategoriesString\fP () const"
.br
.ti -1c
.RI "std::string \fBLogLevelsString\fP () const"
.br
.RI "Returns a string with all user-selectable log levels\&. "
.ti -1c
.RI "bool \fBDefaultShrinkDebugFile\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBLogLevelToStr\fP (\fBBCLog::Level\fP level)"
.br
.RI "Returns the string representation of a log level\&. "
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBm_print_to_console\fP = false"
.br
.ti -1c
.RI "bool \fBm_print_to_file\fP = false"
.br
.ti -1c
.RI "bool \fBm_log_timestamps\fP = DEFAULT_LOGTIMESTAMPS"
.br
.ti -1c
.RI "bool \fBm_log_time_micros\fP = DEFAULT_LOGTIMEMICROS"
.br
.ti -1c
.RI "bool \fBm_log_threadnames\fP = DEFAULT_LOGTHREADNAMES"
.br
.ti -1c
.RI "bool \fBm_log_sourcelocations\fP = DEFAULT_LOGSOURCELOCATIONS"
.br
.ti -1c
.RI "bool \fBm_always_print_category_level\fP = DEFAULT_LOGLEVELALWAYS"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_file_path\fP"
.br
.ti -1c
.RI "std::atomic< bool > \fBm_reopen_file\fP {false}"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AddCategoryLogLevel (\fBLogFlags\fP category, \fBLevel\fP level)\fR [inline]\fP"

.SS "std::unordered_map< \fBLogFlags\fP, \fBLevel\fP > CategoryLevels () const\fR [inline]\fP"

.SS "bool DefaultShrinkDebugFile () const"

.SS "void DeleteCallback (std::list< std::function< void(const std::string &)> >::iterator it)\fR [inline]\fP"
Delete a connection 
.SS "void DisableCategory (\fBBCLog::LogFlags\fP flag)"

.SS "bool DisableCategory (std::string_view str)"

.SS "void DisableLogging ()"
Disable logging This offers a slight speedup and slightly smaller memory usage compared to leaving the logging system in its default state\&. Mostly intended for libbitcoin-kernel apps that don't want any logging\&. Should be used instead of \fBStartLogging()\fP\&. 
.SS "void DisconnectTestLogger ()"
Only for testing 
.SS "void EnableCategory (\fBBCLog::LogFlags\fP flag)"

.SS "bool EnableCategory (std::string_view str)"

.SS "bool Enabled () const\fR [inline]\fP"
Returns whether logs will be written to any output 
.SS "\fBCategoryMask\fP GetCategoryMask () const\fR [inline]\fP"

.SS "std::vector< \fBLogCategory\fP > LogCategoriesList () const"
Returns a vector of the log categories in alphabetical order\&. 
.SS "std::string LogCategoriesString () const\fR [inline]\fP"
Returns a string with the log categories in alphabetical order\&. 
.SS "\fBLevel\fP LogLevel () const\fR [inline]\fP"

.SS "std::string LogLevelsString () const"

.PP
Returns a string with all user-selectable log levels\&. 
.SS "std::string LogLevelToStr (\fBBCLog::Level\fP level)\fR [static]\fP"

.PP
Returns the string representation of a log level\&. 
.SS "void LogPrintStr (std::string_view str, \fBSourceLocation\fP && source_loc, \fBBCLog::LogFlags\fP category, \fBBCLog::Level\fP level, bool should_ratelimit)"
Send a string to the log output 
.SS "size_t \fBNumConnections\fP ()\fR [inline]\fP"

.SS "std::list< std::function< void(conststd::string &)> >::iterator PushBackCallback (std::function< void(const std::string &)> fun)\fR [inline]\fP"
Connect a slot to the print signal and return the connection 
.SS "void SetCategoryLogLevel (const std::unordered_map< \fBLogFlags\fP, \fBLevel\fP > & levels)\fR [inline]\fP"

.SS "bool SetCategoryLogLevel (std::string_view category_str, std::string_view level_str)"

.SS "void SetLogLevel (\fBLevel\fP level)\fR [inline]\fP"

.SS "bool SetLogLevel (std::string_view level)"

.SS "void SetRateLimiting (std::shared_ptr< \fBLogRateLimiter\fP > limiter)\fR [inline]\fP"

.SS "void ShrinkDebugFile ()"

.SS "bool StartLogging ()"
Start logging (and flush all buffered messages) 
.SS "bool WillLogCategory (\fBBCLog::LogFlags\fP category) const"

.SS "bool WillLogCategoryLevel (\fBBCLog::LogFlags\fP category, \fBBCLog::Level\fP level) const"

.SH "Field Documentation"
.PP 
.SS "bool m_always_print_category_level = DEFAULT_LOGLEVELALWAYS"

.SS "\fBfs::path\fP m_file_path"

.SS "bool m_log_sourcelocations = DEFAULT_LOGSOURCELOCATIONS"

.SS "bool m_log_threadnames = DEFAULT_LOGTHREADNAMES"

.SS "bool m_log_time_micros = DEFAULT_LOGTIMEMICROS"

.SS "bool m_log_timestamps = DEFAULT_LOGTIMESTAMPS"

.SS "bool m_print_to_console = false"

.SS "bool m_print_to_file = false"

.SS "std::atomic<bool> m_reopen_file {false}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
