.TH "src/bech32.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bech32.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBDecodeResult\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbech32\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBEncoding\fP { \fBINVALID\fP, \fBBECH32\fP, \fBBECH32M\fP }"
.br
.ti -1c
.RI "enum \fBCharLimit\fP : size_t { \fBBECH32\fP = 90 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBEncode\fP (\fBEncoding\fP encoding, const std::string &hrp, const std::vector< uint8_t > &values)"
.br
.ti -1c
.RI "\fBDecodeResult\fP \fBDecode\fP (const std::string &str, \fBCharLimit\fP limit)"
.br
.ti -1c
.RI "std::pair< std::string, std::vector< int > > \fBLocateErrors\fP (const std::string &str, \fBCharLimit\fP limit)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
