.TH "bech32" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bech32
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBDecodeResult\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBEncoding\fP { \fBINVALID\fP, \fBBECH32\fP, \fBBECH32M\fP }"
.br
.ti -1c
.RI "enum \fBCharLimit\fP : size_t { \fBBECH32\fP = 90 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBEncode\fP (\fBEncoding\fP encoding, const std::string &hrp, const data &values)"
.br
.ti -1c
.RI "\fBDecodeResult\fP \fBDecode\fP (const std::string &str, \fBCharLimit\fP limit)"
.br
.ti -1c
.RI "std::pair< std::string, std::vector< int > > \fBLocateErrors\fP (const std::string &str, \fBCharLimit\fP limit)"
.br
.ti -1c
.RI "std::string \fBEncode\fP (\fBEncoding\fP encoding, const std::string &hrp, const std::vector< uint8_t > &values)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCharLimit\fP : size_t"
Character limits for Bech32(m) encoded strings\&. Character limits are how we provide error location guarantees\&. These values should never exceed 2^31 - 1 (max value for a 32-bit int), since there are places where we may need to convert the CharLimit::VALUE to an int\&. In practice, this should never happen since this \fBCharLimit\fP applies to an address encoding and we would never encode an address with such a massive value 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIBECH32 \fP
BIP173/350 imposed character limit for Bech32(m) encoded addresses\&. This guarantees finding up to 4 errors\&. 
.SS "enum class \fBEncoding\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIINVALID \fP
Failed decoding\&. 
.TP
\f(BIBECH32 \fP
Bech32 encoding as defined in BIP173\&. 
.TP
\f(BIBECH32M \fP
Bech32m encoding as defined in BIP350\&. 
.SH "Function Documentation"
.PP 
.SS "\fBDecodeResult\fP Decode (const std::string & str, \fBCharLimit\fP limit)"
Decode a Bech32 or Bech32m string\&. 
.SS "std::string Encode (\fBEncoding\fP encoding, const std::string & hrp, const data & values)"
Encode a Bech32 or Bech32m string\&. 
.SS "std::string Encode (\fBEncoding\fP encoding, const std::string & hrp, const std::vector< uint8_t > & values)"
Encode a Bech32 or Bech32m string\&. If hrp contains uppercase characters, this will cause an assertion error\&. \fBEncoding\fP must be one of BECH32 or BECH32M\&. 
.SS "std::pair< std::string, std::vector< int > > LocateErrors (const std::string & str, \fBCharLimit\fP limit)"
Find index of an incorrect character in a Bech32 string\&.

.PP
Return the positions of errors in a Bech32 string\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
