.TH "bench_schnorrsig_data" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bench_schnorrsig_data
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bench_impl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsecp256k1_context\fP * \fBctx\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "const \fBsecp256k1_keypair\fP ** \fBkeypairs\fP"
.br
.ti -1c
.RI "const unsigned char ** \fBpk\fP"
.br
.ti -1c
.RI "const unsigned char ** \fBsigs\fP"
.br
.ti -1c
.RI "const unsigned char ** \fBmsgs\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsecp256k1_context\fP* ctx"

.SS "const \fBsecp256k1_keypair\fP** keypairs"

.SS "const unsigned char** msgs"

.SS "int n"

.SS "const unsigned char** pk"

.SS "const unsigned char** sigs"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
