.TH "bench_data" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bench_data
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsecp256k1_context\fP * \fBctx\fP"
.br
.ti -1c
.RI "unsigned char \fBmsg\fP [32]"
.br
.ti -1c
.RI "unsigned char \fBkey\fP [32]"
.br
.ti -1c
.RI "unsigned char \fBsig\fP [72]"
.br
.ti -1c
.RI "size_t \fBsiglen\fP"
.br
.ti -1c
.RI "unsigned char \fBpubkey\fP [33]"
.br
.ti -1c
.RI "size_t \fBpubkeylen\fP"
.br
.ti -1c
.RI "\fBsecp256k1_scratch_space\fP * \fBscratch\fP"
.br
.ti -1c
.RI "\fBsecp256k1_scalar\fP * \fBscalars\fP"
.br
.ti -1c
.RI "\fBsecp256k1_ge\fP * \fBpubkeys\fP"
.br
.ti -1c
.RI "\fBsecp256k1_gej\fP * \fBpubkeys_gej\fP"
.br
.ti -1c
.RI "\fBsecp256k1_scalar\fP * \fBseckeys\fP"
.br
.ti -1c
.RI "\fBsecp256k1_gej\fP * \fBexpected_output\fP"
.br
.ti -1c
.RI "\fBsecp256k1_ecmult_multi_func\fP \fBecmult_multi\fP"
.br
.ti -1c
.RI "size_t \fBcount\fP"
.br
.ti -1c
.RI "int \fBincludes_g\fP"
.br
.ti -1c
.RI "size_t \fBoffset1\fP"
.br
.ti -1c
.RI "size_t \fBoffset2\fP"
.br
.ti -1c
.RI "\fBsecp256k1_gej\fP * \fBoutput\fP"
.br
.ti -1c
.RI "\fBsecp256k1_fe\fP * \fBoutput_xonly\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t count"

.SS "\fBsecp256k1_context\fP * ctx"

.SS "\fBsecp256k1_ecmult_multi_func\fP ecmult_multi"

.SS "\fBsecp256k1_gej\fP* expected_output"

.SS "int includes_g"

.SS "unsigned char key[32]"

.SS "unsigned char msg[32]"

.SS "size_t offset1"

.SS "size_t offset2"

.SS "\fBsecp256k1_gej\fP* output"

.SS "\fBsecp256k1_fe\fP* output_xonly"

.SS "unsigned char pubkey[33]"

.SS "size_t pubkeylen"

.SS "\fBsecp256k1_ge\fP* pubkeys"

.SS "\fBsecp256k1_gej\fP* pubkeys_gej"

.SS "\fBsecp256k1_scalar\fP* scalars"

.SS "\fBsecp256k1_scratch_space\fP* scratch"

.SS "\fBsecp256k1_scalar\fP* seckeys"

.SS "unsigned char sig[72]"

.SS "size_t siglen"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
