.TH "bilingual_str" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bilingual_str
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <translation\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbilingual_str\fP & \fBoperator+=\fP (const \fBbilingual_str\fP &rhs)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBoriginal\fP"
.br
.ti -1c
.RI "std::string \fBtranslated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Bilingual messages:
.IP "\(bu" 2
in GUI: user's native language + untranslated (i\&.e\&. English)
.IP "\(bu" 2
in log and stderr: untranslated only 
.PP

.SH "Member Function Documentation"
.PP 
.SS "void clear ()\fR [inline]\fP"

.SS "bool empty () const\fR [inline]\fP"

.SS "\fBbilingual_str\fP & operator+= (const \fBbilingual_str\fP & rhs)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::string original"

.SS "std::string translated"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
