.TH "BIP9GBTStatus::Info" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BIP9GBTStatus::Info
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <versionbits\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBbit\fP"
.br
.ti -1c
.RI "uint32_t \fBmask\fP"
.br
.ti -1c
.RI "bool \fBgbt_optional_rule\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int bit"

.SS "bool gbt_optional_rule"

.SS "uint32_t mask"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
