.TH "BIP9GBTStatus" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BIP9GBTStatus
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <versionbits\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBInfo\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::map< std::string, const \fBInfo\fP, std::less<> > \fBsignalling\fP"
.br
.ti -1c
.RI "std::map< std::string, const \fBInfo\fP, std::less<> > \fBlocked_in\fP"
.br
.ti -1c
.RI "std::map< std::string, const \fBInfo\fP, std::less<> > \fBactive\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "std::map<std::string, const \fBInfo\fP, std::less<> > active"

.SS "std::map<std::string, const \fBInfo\fP, std::less<> > locked_in"

.SS "std::map<std::string, const \fBInfo\fP, std::less<> > signalling"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
