.TH "BIP9Info" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BIP9Info
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <versionbits\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsince\fP {0}"
.br
.ti -1c
.RI "std::string \fBcurrent_state\fP {}"
.br
.ti -1c
.RI "std::string \fBnext_state\fP {}"
.br
.ti -1c
.RI "std::optional< \fBBIP9Stats\fP > \fBstats\fP"
.br
.ti -1c
.RI "std::vector< bool > \fBsignalling_blocks\fP"
.br
.ti -1c
.RI "std::optional< int > \fBactive_since\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Detailed status of an enabled BIP9 deployment 
.SH "Field Documentation"
.PP 
.SS "std::optional<int> active_since"
Height at which the deployment is active, if known\&. May be in the future\&. 
.SS "std::string current_state {}"
String representing the current state 
.SS "std::string next_state {}"
String representing the next block's state 
.SS "std::vector<bool> signalling_blocks"
Which blocks signalled; empty if signalling is not applicable 
.SS "int since {0}"
Height at which current_state started 
.SS "std::optional<\fBBIP9Stats\fP> stats"
For states where signalling is applicable, information about the signalling 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
