.TH "BitcoinApplication" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitcoinApplication
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoin\&.h>\fP
.PP
Inherits QApplication\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBinitializeResult\fP (bool success, \fBinterfaces::BlockAndHeaderTipInfo\fP tip_info)"
.br
.ti -1c
.RI "void \fBrequestShutdown\fP ()"
.br
.RI "Request core shutdown\&. "
.ti -1c
.RI "void \fBhandleRunawayException\fP (const QString &message)"
.br
.RI "Handle runaway exceptions\&. Shows a message box with the problem and quits the program\&. "
.ti -1c
.RI "void \fBhandleNonFatalException\fP (const QString &message)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBrequestedInitialize\fP ()"
.br
.ti -1c
.RI "void \fBrequestedShutdown\fP ()"
.br
.ti -1c
.RI "void \fBwindowShown\fP (\fBBitcoinGUI\fP *window)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitcoinApplication\fP ()"
.br
.ti -1c
.RI "\fB~BitcoinApplication\fP ()"
.br
.ti -1c
.RI "void \fBparameterSetup\fP ()"
.br
.RI "parameter interaction/setup based on rules "
.ti -1c
.RI "bool \fBcreateOptionsModel\fP (bool resetSettings)"
.br
.RI "Create options model\&. "
.ti -1c
.RI "void \fBInitPruneSetting\fP (int64_t prune_MiB)"
.br
.RI "Initialize prune setting\&. "
.ti -1c
.RI "void \fBcreateWindow\fP (const \fBNetworkStyle\fP *networkStyle)"
.br
.RI "Create main window\&. "
.ti -1c
.RI "void \fBcreateSplashScreen\fP (const \fBNetworkStyle\fP *networkStyle)"
.br
.RI "Create splash screen\&. "
.ti -1c
.RI "void \fBcreateNode\fP (\fBinterfaces::Init\fP &\fBinit\fP)"
.br
.RI "Create or spawn node\&. "
.ti -1c
.RI "bool \fBbaseInitialize\fP ()"
.br
.RI "Basic initialization, before starting initialization/shutdown thread\&. Return true on success\&. "
.ti -1c
.RI "void \fBrequestInitialize\fP ()"
.br
.RI "Request core initialization\&. "
.ti -1c
.RI "WId \fBgetMainWinId\fP () const"
.br
.RI "Get window identifier of QMainWindow (\fBBitcoinGUI\fP)\&. "
.ti -1c
.RI "void \fBsetupPlatformStyle\fP ()"
.br
.RI "Setup platform style\&. "
.ti -1c
.RI "\fBinterfaces::Node\fP & \fBnode\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBevent\fP (QEvent *e) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main Bitcoin application object 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBitcoinApplication\fP ()\fR [explicit]\fP"

.SS "~\fBBitcoinApplication\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "bool baseInitialize ()"

.PP
Basic initialization, before starting initialization/shutdown thread\&. Return true on success\&. 
.SS "void createNode (\fBinterfaces::Init\fP & init)"

.PP
Create or spawn node\&. 
.SS "bool createOptionsModel (bool resetSettings)\fR [nodiscard]\fP"

.PP
Create options model\&. 
.SS "void createSplashScreen (const \fBNetworkStyle\fP * networkStyle)"

.PP
Create splash screen\&. 
.SS "void createWindow (const \fBNetworkStyle\fP * networkStyle)"

.PP
Create main window\&. 
.SS "bool event (QEvent * e)\fR [override]\fP, \fR [protected]\fP"

.SS "WId getMainWinId () const"

.PP
Get window identifier of QMainWindow (\fBBitcoinGUI\fP)\&. 
.SS "void handleNonFatalException (const QString & message)\fR [slot]\fP"
A helper function that shows a message box with details about a non-fatal exception\&. 
.SS "void handleRunawayException (const QString & message)\fR [slot]\fP"

.PP
Handle runaway exceptions\&. Shows a message box with the problem and quits the program\&. 
.SS "void initializeResult (bool success, \fBinterfaces::BlockAndHeaderTipInfo\fP tip_info)\fR [slot]\fP"

.SS "void InitPruneSetting (int64_t prune_MiB)"

.PP
Initialize prune setting\&. 
.SS "\fBinterfaces::Node\fP & node () const\fR [inline]\fP"

.SS "void parameterSetup ()"

.PP
parameter interaction/setup based on rules 
.SS "void requestedInitialize ()\fR [signal]\fP"

.SS "void requestedShutdown ()\fR [signal]\fP"

.SS "void requestInitialize ()"

.PP
Request core initialization\&. 
.SS "void requestShutdown ()\fR [slot]\fP"

.PP
Request core shutdown\&. 
.SS "void setupPlatformStyle ()"

.PP
Setup platform style\&. 
.SS "void windowShown (\fBBitcoinGUI\fP * window)\fR [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
