.TH "src/init/bitcoin-wallet.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/init/bitcoin-wallet.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <interfaces/init\&.h>\fP
.br
\fR#include <memory>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinterfaces\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBInit\fP > \fBMakeWalletInit\fP (int argc, char *argv[], int &\fBexit_status\fP)"
.br
.RI "Return implementation of \fBInit\fP interface for the wallet process\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
