.TH "BitcoinAddressCheckValidator" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitcoinAddressCheckValidator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinaddressvalidator\&.h>\fP
.PP
Inherits QValidator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitcoinAddressCheckValidator\fP (QObject *parent)"
.br
.ti -1c
.RI "\fBState\fP \fBvalidate\fP (QString &input, int &pos) const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Bitcoin address widget validator, checks for a valid bitcoin address\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBitcoinAddressCheckValidator\fP (QObject * parent)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QValidator::State validate (QString & input, int & pos) const\fR [override]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
