.TH "BitcoinAmountField" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitcoinAmountField
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinamountfield\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBvalueChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitcoinAmountField\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBvalue\fP (bool *value=nullptr) const"
.br
.ti -1c
.RI "void \fBsetValue\fP (const \fBCAmount\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBSetAllowEmpty\fP (bool allow)"
.br
.ti -1c
.RI "void \fBSetMinValue\fP (const \fBCAmount\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBSetMaxValue\fP (const \fBCAmount\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBsetSingleStep\fP (const \fBCAmount\fP &step)"
.br
.ti -1c
.RI "void \fBsetReadOnly\fP (bool fReadOnly)"
.br
.ti -1c
.RI "void \fBsetValid\fP (bool valid)"
.br
.ti -1c
.RI "bool \fBvalidate\fP ()"
.br
.ti -1c
.RI "void \fBsetDisplayUnit\fP (\fBBitcoinUnit\fP new_unit)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBsetEnabled\fP (bool fEnabled)"
.br
.ti -1c
.RI "QWidget * \fBsetupTabChain\fP (QWidget *prev)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *object, QEvent *event) override"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qint64 \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Widget for entering bitcoin amounts\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBitcoinAmountField\fP (QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void clear ()"
Make field empty and ready for new input\&. 
.SS "bool eventFilter (QObject * object, QEvent * event)\fR [override]\fP, \fR [protected]\fP"
Intercept focus-in event and ',' key presses 
.SS "void SetAllowEmpty (bool allow)"
If allow empty is set to false the field will be set to the minimum allowed value if left empty\&. 
.SS "void setDisplayUnit (\fBBitcoinUnit\fP new_unit)"
Change unit used to display amount\&. 
.SS "void setEnabled (bool fEnabled)"
Enable/Disable\&. 
.SS "void SetMaxValue (const \fBCAmount\fP & value)"
Set the maximum value in satoshis 
.SS "void SetMinValue (const \fBCAmount\fP & value)"
Set the minimum value in satoshis 
.SS "void setReadOnly (bool fReadOnly)"
Make read-only 
.SS "void setSingleStep (const \fBCAmount\fP & step)"
Set single step in satoshis 
.SS "QWidget * setupTabChain (QWidget * prev)"
Qt messes up the tab chain by default in some cases (issue https://bugreports.qt-project.org/browse/QTBUG-10907), in these cases we have to set it up manually\&. 
.SS "void setValid (bool valid)"
Mark current value as invalid in UI\&. 
.SS "void setValue (const \fBCAmount\fP & value)"

.SS "bool validate ()"
Perform input validation, mark field as invalid if entered value is not valid\&. 
.SS "\fBCAmount\fP value (bool * value = \fRnullptr\fP) const"

.SS "void valueChanged ()\fR [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "qint64 value\fR [read]\fP, \fR [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
