.TH "src/kernel/bitcoinkernel_wrapper.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kernel/bitcoinkernel_wrapper.h
.SH SYNOPSIS
.br
.PP
\fR#include <kernel/bitcoinkernel\&.h>\fP
.br
\fR#include <array>\fP
.br
\fR#include <exception>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <span>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include <type_traits>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBis_bitmask_enum< T >\fP"
.br
.ti -1c
.RI "struct \fBis_bitmask_enum< ScriptVerificationFlags >\fP"
.br
.ti -1c
.RI "class \fBIterator< Collection, ValueType >\fP"
.br
.ti -1c
.RI "class \fBRange< Container, SizeFunc, GetFunc >\fP"
.br
.ti -1c
.RI "class \fBView< CType >\fP"
.br
.ti -1c
.RI "class \fBHandle< CType, CopyFunc, DestroyFunc >\fP"
.br
.ti -1c
.RI "class \fBUniqueHandle< CType, DestroyFunc >\fP"
.br
.ti -1c
.RI "struct \fBUniqueHandle< CType, DestroyFunc >::Deleter\fP"
.br
.ti -1c
.RI "class \fBScriptPubkeyApi< Derived >\fP"
.br
.ti -1c
.RI "class \fBScriptPubkeyView\fP"
.br
.ti -1c
.RI "class \fBScriptPubkey\fP"
.br
.ti -1c
.RI "class \fBTransactionOutputApi< Derived >\fP"
.br
.ti -1c
.RI "class \fBTransactionOutputView\fP"
.br
.ti -1c
.RI "class \fBTransactionOutput\fP"
.br
.ti -1c
.RI "class \fBTxidApi< Derived >\fP"
.br
.ti -1c
.RI "class \fBTxidView\fP"
.br
.ti -1c
.RI "class \fBTxid\fP"
.br
.ti -1c
.RI "class \fBOutPointApi< Derived >\fP"
.br
.ti -1c
.RI "class \fBOutPointView\fP"
.br
.ti -1c
.RI "class \fBOutPoint\fP"
.br
.ti -1c
.RI "class \fBTransactionInputApi< Derived >\fP"
.br
.ti -1c
.RI "class \fBTransactionInputView\fP"
.br
.ti -1c
.RI "class \fBTransactionInput\fP"
.br
.ti -1c
.RI "class \fBTransactionApi< Derived >\fP"
.br
.ti -1c
.RI "class \fBTransactionView\fP"
.br
.ti -1c
.RI "class \fBTransaction\fP"
.br
.ti -1c
.RI "class \fBBlockHashApi< Derived >\fP"
.br
.ti -1c
.RI "class \fBBlockHashView\fP"
.br
.ti -1c
.RI "class \fBBlockHash\fP"
.br
.ti -1c
.RI "class \fBBlock\fP"
.br
.ti -1c
.RI "class \fBLogger< T >\fP"
.br
.ti -1c
.RI "class \fBBlockTreeEntry\fP"
.br
.ti -1c
.RI "class \fBKernelNotifications\fP"
.br
.ti -1c
.RI "class \fBBlockValidationState\fP"
.br
.ti -1c
.RI "class \fBValidationInterface\fP"
.br
.ti -1c
.RI "class \fBChainParams\fP"
.br
.ti -1c
.RI "class \fBContextOptions\fP"
.br
.ti -1c
.RI "class \fBContext\fP"
.br
.ti -1c
.RI "class \fBChainstateManagerOptions\fP"
.br
.ti -1c
.RI "class \fBChainView\fP"
.br
.ti -1c
.RI "class \fBCoinApi< Derived >\fP"
.br
.ti -1c
.RI "class \fBCoinView\fP"
.br
.ti -1c
.RI "class \fBCoin\fP"
.br
.ti -1c
.RI "class \fBTransactionSpentOutputsApi< Derived >\fP"
.br
.ti -1c
.RI "class \fBTransactionSpentOutputsView\fP"
.br
.ti -1c
.RI "class \fBTransactionSpentOutputs\fP"
.br
.ti -1c
.RI "class \fBBlockSpentOutputs\fP"
.br
.ti -1c
.RI "class \fBChainMan\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbtck\fP"
.br
.in -1c
.SS "Concepts"

.in +1c
.ti -1c
.RI "concept \fBbtck::BitmaskEnum\fP"
.br
.ti -1c
.RI "concept \fBbtck::IndexedContainer\fP"
.br
.ti -1c
.RI "concept \fBbtck::Log\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAKE_RANGE_METHOD\fP(method_name,  ContainerType,  SizeFunc,  GetFunc,  container_expr)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBLogCategory\fP : btck_LogCategory { \fBALL\fP = btck_LogCategory_ALL, \fBBENCH\fP = btck_LogCategory_BENCH, \fBBLOCKSTORAGE\fP = btck_LogCategory_BLOCKSTORAGE, \fBCOINDB\fP = btck_LogCategory_COINDB, \fBLEVELDB\fP = btck_LogCategory_LEVELDB, \fBMEMPOOL\fP = btck_LogCategory_MEMPOOL, \fBPRUNE\fP = btck_LogCategory_PRUNE, \fBRAND\fP = btck_LogCategory_RAND, \fBREINDEX\fP = btck_LogCategory_REINDEX, \fBVALIDATION\fP = btck_LogCategory_VALIDATION, \fBKERNEL\fP = btck_LogCategory_KERNEL }"
.br
.ti -1c
.RI "enum class \fBLogLevel\fP : btck_LogLevel { \fBTRACE_LEVEL\fP = btck_LogLevel_TRACE, \fBDEBUG_LEVEL\fP = btck_LogLevel_DEBUG, \fBINFO_LEVEL\fP = btck_LogLevel_INFO }"
.br
.ti -1c
.RI "enum class \fBChainType\fP : btck_ChainType { \fBMAINNET\fP = btck_ChainType_MAINNET, \fBTESTNET\fP = btck_ChainType_TESTNET, \fBTESTNET_4\fP = btck_ChainType_TESTNET_4, \fBSIGNET\fP = btck_ChainType_SIGNET, \fBREGTEST\fP = btck_ChainType_REGTEST }"
.br
.ti -1c
.RI "enum class \fBSynchronizationState\fP : btck_SynchronizationState { \fBINIT_REINDEX\fP = btck_SynchronizationState_INIT_REINDEX, \fBINIT_DOWNLOAD\fP = btck_SynchronizationState_INIT_DOWNLOAD, \fBPOST_INIT\fP = btck_SynchronizationState_POST_INIT }"
.br
.ti -1c
.RI "enum class \fBWarning\fP : btck_Warning { \fBUNKNOWN_NEW_RULES_ACTIVATED\fP = btck_Warning_UNKNOWN_NEW_RULES_ACTIVATED, \fBLARGE_WORK_INVALID_CHAIN\fP = btck_Warning_LARGE_WORK_INVALID_CHAIN }"
.br
.ti -1c
.RI "enum class \fBValidationMode\fP : btck_ValidationMode { \fBVALID\fP = btck_ValidationMode_VALID, \fBINVALID\fP = btck_ValidationMode_INVALID, \fBINTERNAL_ERROR\fP = btck_ValidationMode_INTERNAL_ERROR }"
.br
.ti -1c
.RI "enum class \fBBlockValidationResult\fP : btck_BlockValidationResult { \fBUNSET\fP = btck_BlockValidationResult_UNSET, \fBCONSENSUS\fP = btck_BlockValidationResult_CONSENSUS, \fBCACHED_INVALID\fP = btck_BlockValidationResult_CACHED_INVALID, \fBINVALID_HEADER\fP = btck_BlockValidationResult_INVALID_HEADER, \fBMUTATED\fP = btck_BlockValidationResult_MUTATED, \fBMISSING_PREV\fP = btck_BlockValidationResult_MISSING_PREV, \fBINVALID_PREV\fP = btck_BlockValidationResult_INVALID_PREV, \fBTIME_FUTURE\fP = btck_BlockValidationResult_TIME_FUTURE, \fBHEADER_LOW_WORK\fP = btck_BlockValidationResult_HEADER_LOW_WORK }"
.br
.ti -1c
.RI "enum class \fBScriptVerifyStatus\fP : btck_ScriptVerifyStatus { \fBOK\fP = btck_ScriptVerifyStatus_OK, \fBERROR_INVALID_FLAGS_COMBINATION\fP = btck_ScriptVerifyStatus_ERROR_INVALID_FLAGS_COMBINATION, \fBERROR_SPENT_OUTPUTS_REQUIRED\fP = btck_ScriptVerifyStatus_ERROR_SPENT_OUTPUTS_REQUIRED }"
.br
.ti -1c
.RI "enum class \fBScriptVerificationFlags\fP : btck_ScriptVerificationFlags { \fBNONE\fP = btck_ScriptVerificationFlags_NONE, \fBP2SH\fP = btck_ScriptVerificationFlags_P2SH, \fBDERSIG\fP = btck_ScriptVerificationFlags_DERSIG, \fBNULLDUMMY\fP = btck_ScriptVerificationFlags_NULLDUMMY, \fBCHECKLOCKTIMEVERIFY\fP = btck_ScriptVerificationFlags_CHECKLOCKTIMEVERIFY, \fBCHECKSEQUENCEVERIFY\fP = btck_ScriptVerificationFlags_CHECKSEQUENCEVERIFY, \fBWITNESS\fP = btck_ScriptVerificationFlags_WITNESS, \fBTAPROOT\fP = btck_ScriptVerificationFlags_TAPROOT, \fBALL\fP = btck_ScriptVerificationFlags_ALL }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<BitmaskEnum T> constexpr \fBT\fP \fBoperator|\fP (\fBT\fP lhs, \fBT\fP rhs)"
.br
.ti -1c
.RI "template<BitmaskEnum T> constexpr \fBT\fP \fBoperator&\fP (\fBT\fP lhs, \fBT\fP rhs)"
.br
.ti -1c
.RI "template<BitmaskEnum T> constexpr \fBT\fP \fBoperator^\fP (\fBT\fP lhs, \fBT\fP rhs)"
.br
.ti -1c
.RI "template<BitmaskEnum T> constexpr \fBT\fP \fBoperator~\fP (\fBT\fP value)"
.br
.ti -1c
.RI "template<BitmaskEnum T> constexpr \fBT\fP & \fBoperator|=\fP (\fBT\fP &lhs, \fBT\fP rhs)"
.br
.ti -1c
.RI "template<BitmaskEnum T> constexpr \fBT\fP & \fBoperator&=\fP (\fBT\fP &lhs, \fBT\fP rhs)"
.br
.ti -1c
.RI "template<BitmaskEnum T> constexpr \fBT\fP & \fBoperator^=\fP (\fBT\fP &lhs, \fBT\fP rhs)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP \fBcheck\fP (\fBT\fP ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::vector< std::byte > \fBwrite_bytes\fP (const \fBT\fP *object, int(*to_bytes)(const \fBT\fP *, \fBbtck_WriteBytes\fP, void *))"
.br
.ti -1c
.RI "void \fBlogging_disable\fP ()"
.br
.ti -1c
.RI "void \fBlogging_set_options\fP (const \fBbtck_LoggingOptions\fP &logging_options)"
.br
.ti -1c
.RI "void \fBlogging_set_level_category\fP (\fBLogCategory\fP\fBLogCategory\fP category, \fBLogLevel\fP level)"
.br
.ti -1c
.RI "void \fBlogging_enable_category\fP (\fBLogCategory\fP\fBLogCategory\fP category)"
.br
.ti -1c
.RI "void \fBlogging_disable_category\fP (\fBLogCategory\fP\fBLogCategory\fP category)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAKE_RANGE_METHOD( method_name,  ContainerType,  SizeFunc,  GetFunc,  container_expr)"
\fBValue:\fP
.nf
    auto method_name() const & { \\
        return Range<ContainerType, SizeFunc, GetFunc>{container_expr}; \\
    } \\
    auto method_name() const && = delete;
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
