.TH "bitset_detail" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bitset_detail
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIntBitSet\fP"
.br
.ti -1c
.RI "class \fBMultiIntBitSet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename I> unsigned constexpr \fBPopCount\fP (I v)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename I> unsigned constexpr PopCount (I v)\fR [inline]\fP, \fR [constexpr]\fP"
Count the number of bits set in an unsigned integer type\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
