.TH "BitStreamWriter< OStream >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitStreamWriter< OStream >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <streams\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitStreamWriter\fP (OStream &ostream)"
.br
.ti -1c
.RI "\fB~BitStreamWriter\fP ()"
.br
.ti -1c
.RI "void \fBWrite\fP (uint64_t data, int nbits)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename OStream> \fBBitStreamWriter\fP (OStream & ostream)\fR [inline]\fP, \fR [explicit]\fP"

.SS "template<typename OStream> ~\fBBitStreamWriter\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename OStream> void Flush ()\fR [inline]\fP"
Flush any unwritten bits to the output stream, padding with 0's to the next byte boundary\&. 
.SS "template<typename OStream> void Write (uint64_t data, int nbits)\fR [inline]\fP"
Write the nbits least significant bits of a 64-bit int to the output stream\&. Data is buffered until it completes an octet\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
