.TH "src/node/blockmanager_args.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/blockmanager_args.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/blockmanager_args\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <node/blockstorage\&.h>\fP
.br
\fR#include <node/database_args\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <util/result\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <cstdint>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fButil::Result\fP< void > \fBApplyArgsManOptions\fP (const \fBArgsManager\fP &\fBargs\fP, \fBBlockManager::Options\fP &opts)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
