.TH "src/test/blockencodings_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/blockencodings_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <blockencodings\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <consensus/merkle\&.h>\fP
.br
\fR#include <pow\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/txmempool\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTestHeaderAndShortIDs\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (SimpleRoundTripTest)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (NonCoinbasePreforwardRTTest)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (SufficientPreforwardRTTest)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (EmptyBlockRoundTripTest)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (ReceiveWithExtraTransactions)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (TransactionsRequestSerializationTest)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (TransactionsRequestDeserializationMaxTest)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (TransactionsRequestDeserializationOverflowTest)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::vector< std::pair< \fBWtxid\fP, \fBCTransactionRef\fP > > \fBempty_extra_txn\fP"
.br
.ti -1c
.RI "constexpr long \fBSHARED_TX_OFFSET\fP {3}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (EmptyBlockRoundTripTest )"

.SS "BOOST_AUTO_TEST_CASE (NonCoinbasePreforwardRTTest )"

.SS "BOOST_AUTO_TEST_CASE (ReceiveWithExtraTransactions )"

.SS "BOOST_AUTO_TEST_CASE (SimpleRoundTripTest )"

.SS "BOOST_AUTO_TEST_CASE (SufficientPreforwardRTTest )"

.SS "BOOST_AUTO_TEST_CASE (TransactionsRequestDeserializationMaxTest )"

.SS "BOOST_AUTO_TEST_CASE (TransactionsRequestDeserializationOverflowTest )"

.SS "BOOST_AUTO_TEST_CASE (TransactionsRequestSerializationTest )"

.SH "Variable Documentation"
.PP 
.SS "const std::vector<std::pair<\fBWtxid\fP, \fBCTransactionRef\fP> > empty_extra_txn"

.SS "long SHARED_TX_OFFSET {3}\fR [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
