.TH "src/primitives/block.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/primitives/block.h
.SH SYNOPSIS
.br
.PP
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCBlockHeader\fP"
.br
.ti -1c
.RI "class \fBCBlock\fP"
.br
.ti -1c
.RI "struct \fBCBlockLocator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
