.TH "src/test/util/blockfilter.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/util/blockfilter.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/util/blockfilter\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <node/blockstorage\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <undo\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBComputeFilter\fP (\fBBlockFilterType\fP filter_type, const \fBCBlockIndex\fP &block_index, \fBBlockFilter\fP &filter, const \fBBlockManager\fP &blockman)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool ComputeFilter (\fBBlockFilterType\fP filter_type, const \fBCBlockIndex\fP & block_index, \fBBlockFilter\fP & filter, const \fBBlockManager\fP & blockman)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
