.TH "src/policy/fees/block_policy_estimator.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/policy/fees/block_policy_estimator.h
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <policy/feerate\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <threadsafety\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <validationinterface\&.h>\fP
.br
\fR#include <array>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <map>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <set>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEstimatorBucket\fP"
.br
.ti -1c
.RI "struct \fBEstimationResult\fP"
.br
.ti -1c
.RI "struct \fBFeeCalculation\fP"
.br
.ti -1c
.RI "class \fBCBlockPolicyEstimator\fP"
.br
.ti -1c
.RI "class \fBFeeFilterRounder\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBFeeEstimateHorizon\fP { \fBSHORT_HALFLIFE\fP, \fBMED_HALFLIFE\fP, \fBLONG_HALFLIFE\fP }"
.br
.ti -1c
.RI "enum class \fBFeeReason\fP { \fBNONE\fP, \fBHALF_ESTIMATE\fP, \fBFULL_ESTIMATE\fP, \fBDOUBLE_ESTIMATE\fP, \fBCONSERVATIVE\fP, \fBMEMPOOL_MIN\fP, \fBPAYTXFEE\fP, \fBFALLBACK\fP, \fBREQUIRED\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBStringForFeeEstimateHorizon\fP (\fBFeeEstimateHorizon\fP horizon)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBFeeEstimateHorizon\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BISHORT_HALFLIFE \fP
.TP
\f(BIMED_HALFLIFE \fP
.TP
\f(BILONG_HALFLIFE \fP
.SS "enum class \fBFeeReason\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINONE \fP
.TP
\f(BIHALF_ESTIMATE \fP
.TP
\f(BIFULL_ESTIMATE \fP
.TP
\f(BIDOUBLE_ESTIMATE \fP
.TP
\f(BICONSERVATIVE \fP
.TP
\f(BIMEMPOOL_MIN \fP
.TP
\f(BIPAYTXFEE \fP
.TP
\f(BIFALLBACK \fP
.TP
\f(BIREQUIRED \fP
.SH "Function Documentation"
.PP 
.SS "std::string StringForFeeEstimateHorizon (\fBFeeEstimateHorizon\fP horizon)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
