.TH "src/index/blockfilterindex.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/index/blockfilterindex.h
.SH SYNOPSIS
.br
.PP
\fR#include <attributes\&.h>\fP
.br
\fR#include <flatfile\&.h>\fP
.br
\fR#include <index/base\&.h>\fP
.br
\fR#include <interfaces/chain\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/hasher\&.h>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBlockFilterIndex\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBlockFilterIndex\fP * \fBGetBlockFilterIndex\fP (\fBBlockFilterType\fP filter_type)"
.br
.ti -1c
.RI "void \fBForEachBlockFilterIndex\fP (std::function< void(\fBBlockFilterIndex\fP &)> fn)"
.br
.ti -1c
.RI "bool \fBInitBlockFilterIndex\fP (std::function< std::unique_ptr< \fBinterfaces::Chain\fP >()> make_chain, \fBBlockFilterType\fP filter_type, size_t n_cache_size, bool f_memory=false, bool f_wipe=false)"
.br
.ti -1c
.RI "bool \fBDestroyBlockFilterIndex\fP (\fBBlockFilterType\fP filter_type)"
.br
.ti -1c
.RI "void \fBDestroyAllBlockFilterIndexes\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void DestroyAllBlockFilterIndexes ()"
Destroy all open block filter indexes\&. 
.SS "bool DestroyBlockFilterIndex (\fBBlockFilterType\fP filter_type)"
Destroy the block filter index with the given type\&. Returns false if no such index exists\&. This just releases the allocated memory and closes the database connection, it does not delete the index data\&. 
.SS "void ForEachBlockFilterIndex (std::function< void(\fBBlockFilterIndex\fP &)> fn)"
Iterate over all running block filter indexes, invoking fn on each\&. 
.SS "\fBBlockFilterIndex\fP * GetBlockFilterIndex (\fBBlockFilterType\fP filter_type)"
Get a block filter index by type\&. Returns nullptr if index has not been initialized or was already destroyed\&. 
.SS "bool InitBlockFilterIndex (std::function< std::unique_ptr< \fBinterfaces::Chain\fP >()> make_chain, \fBBlockFilterType\fP filter_type, size_t n_cache_size, bool f_memory = \fRfalse\fP, bool f_wipe = \fRfalse\fP)"
Initialize a block filter index for the given type if one does not already exist\&. Returns true if a new index is created and false if one has already been initialized\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
