.TH "BlockTemplate" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockTemplate \- Block template interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mining\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~BlockTemplate\fP ()=default"
.br
.ti -1c
.RI "virtual \fBCBlockHeader\fP \fBgetBlockHeader\fP ()=0"
.br
.ti -1c
.RI "virtual \fBCBlock\fP \fBgetBlock\fP ()=0"
.br
.ti -1c
.RI "virtual std::vector< \fBCAmount\fP > \fBgetTxFees\fP ()=0"
.br
.ti -1c
.RI "virtual std::vector< int64_t > \fBgetTxSigops\fP ()=0"
.br
.ti -1c
.RI "virtual \fBCTransactionRef\fP \fBgetCoinbaseTx\fP ()=0"
.br
.ti -1c
.RI "virtual std::vector< unsigned char > \fBgetCoinbaseCommitment\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBgetWitnessCommitmentIndex\fP ()=0"
.br
.ti -1c
.RI "virtual std::vector< \fBuint256\fP > \fBgetCoinbaseMerklePath\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBsubmitSolution\fP (uint32_t version, uint32_t timestamp, uint32_t \fBnonce\fP, \fBCTransactionRef\fP coinbase)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBBlockTemplate\fP > \fBwaitNext\fP (const \fBnode::BlockWaitOptions\fP options={})=0"
.br
.ti -1c
.RI "virtual void \fBinterruptWait\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Block template interface\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBBlockTemplate\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBCBlock\fP getBlock ()\fR [pure virtual]\fP"

.SS "virtual \fBCBlockHeader\fP getBlockHeader ()\fR [pure virtual]\fP"

.SS "virtual std::vector< unsigned char > getCoinbaseCommitment ()\fR [pure virtual]\fP"

.SS "virtual std::vector< \fBuint256\fP > getCoinbaseMerklePath ()\fR [pure virtual]\fP"
Compute merkle path to the coinbase transaction

.PP
\fBReturns\fP
.RS 4
merkle path ordered from the deepest 
.RE
.PP

.SS "virtual \fBCTransactionRef\fP getCoinbaseTx ()\fR [pure virtual]\fP"

.SS "virtual std::vector< \fBCAmount\fP > getTxFees ()\fR [pure virtual]\fP"

.SS "virtual std::vector< int64_t > getTxSigops ()\fR [pure virtual]\fP"

.SS "virtual int getWitnessCommitmentIndex ()\fR [pure virtual]\fP"

.SS "virtual void interruptWait ()\fR [pure virtual]\fP"
Interrupts the current wait for the next block template\&. 
.SS "virtual bool submitSolution (uint32_t version, uint32_t timestamp, uint32_t nonce, \fBCTransactionRef\fP coinbase)\fR [pure virtual]\fP"
Construct and broadcast the block\&. Modifies the template in place, updating the fields listed below as well as the merkle root\&.

.PP
\fBParameters\fP
.RS 4
\fIversion\fP version block header field 
.br
\fItimestamp\fP time block header field (unix timestamp) 
.br
\fInonce\fP nonce block header field 
.br
\fIcoinbase\fP complete coinbase transaction (including witness)
.RE
.PP
\fBNote\fP
.RS 4
unlike the submitblock RPC, this method does NOT add the coinbase witness automatically\&.
.RE
.PP
\fBReturns\fP
.RS 4
if the block was processed, does not necessarily indicate validity\&.
.RE
.PP
\fBNote\fP
.RS 4
Returns true if the block is already known, which can happen if the solved block is constructed and broadcast by multiple nodes (e\&.g\&. both the miner who constructed the template and the pool)\&. 
.RE
.PP

.SS "virtual std::unique_ptr< \fBBlockTemplate\fP > waitNext (const \fBnode::BlockWaitOptions\fP options = \fR{}\fP)\fR [pure virtual]\fP"
Waits for fees in the next block to rise, a new tip or the timeout\&.

.PP
\fBParameters\fP
.RS 4
\fIoptions\fP Control the timeout (default forever) and by how much total fees for the next block should rise (default infinite)\&.
.RE
.PP
\fBReturns\fP
.RS 4
a new \fBBlockTemplate\fP or nothing if the timeout occurs\&.
.RE
.PP
On testnet this will additionally return a template with difficulty 1 if the tip is more than 20 minutes old\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
