.TH "src/index/blockfilterindex.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/index/blockfilterindex.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <index/blockfilterindex\&.h>\fP
.br
\fR#include <blockfilter\&.h>\fP
.br
\fR#include <chain\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <dbwrapper\&.h>\fP
.br
\fR#include <flatfile\&.h>\fP
.br
\fR#include <hash\&.h>\fP
.br
\fR#include <index/base\&.h>\fP
.br
\fR#include <interfaces/chain\&.h>\fP
.br
\fR#include <interfaces/types\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/hasher\&.h>\fP
.br
\fR#include <util/syserror\&.h>\fP
.br
\fR#include <cerrno>\fP
.br
\fR#include <exception>\fP
.br
\fR#include <ios>\fP
.br
\fR#include <map>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <span>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <string>\fP
.br
\fR#include <tuple>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBlockFilterIndex\fP * \fBGetBlockFilterIndex\fP (\fBBlockFilterType\fP filter_type)"
.br
.ti -1c
.RI "void \fBForEachBlockFilterIndex\fP (std::function< void(\fBBlockFilterIndex\fP &)> fn)"
.br
.ti -1c
.RI "bool \fBInitBlockFilterIndex\fP (std::function< std::unique_ptr< \fBinterfaces::Chain\fP >()> make_chain, \fBBlockFilterType\fP filter_type, size_t n_cache_size, bool f_memory, bool f_wipe)"
.br
.ti -1c
.RI "bool \fBDestroyBlockFilterIndex\fP (\fBBlockFilterType\fP filter_type)"
.br
.ti -1c
.RI "void \fBDestroyAllBlockFilterIndexes\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr uint8_t \fBDB_BLOCK_HASH\fP {'s'}"
.br
.ti -1c
.RI "constexpr uint8_t \fBDB_BLOCK_HEIGHT\fP {'t'}"
.br
.ti -1c
.RI "constexpr uint8_t \fBDB_FILTER_POS\fP {'P'}"
.br
.ti -1c
.RI "constexpr unsigned int \fBMAX_FLTR_FILE_SIZE\fP = 0x1000000"
.br
.ti -1c
.RI "constexpr unsigned int \fBFLTR_FILE_CHUNK_SIZE\fP = 0x100000"
.br
.ti -1c
.RI "constexpr size_t \fBCF_HEADERS_CACHE_MAX_SZ\fP {2000}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void DestroyAllBlockFilterIndexes ()"
Destroy all open block filter indexes\&. 
.SS "bool DestroyBlockFilterIndex (\fBBlockFilterType\fP filter_type)"
Destroy the block filter index with the given type\&. Returns false if no such index exists\&. This just releases the allocated memory and closes the database connection, it does not delete the index data\&. 
.SS "void ForEachBlockFilterIndex (std::function< void(\fBBlockFilterIndex\fP &)> fn)"
Iterate over all running block filter indexes, invoking fn on each\&. 
.SS "\fBBlockFilterIndex\fP * GetBlockFilterIndex (\fBBlockFilterType\fP filter_type)"
Get a block filter index by type\&. Returns nullptr if index has not been initialized or was already destroyed\&. 
.SS "bool InitBlockFilterIndex (std::function< std::unique_ptr< \fBinterfaces::Chain\fP >()> make_chain, \fBBlockFilterType\fP filter_type, size_t n_cache_size, bool f_memory = \fRfalse\fP, bool f_wipe = \fRfalse\fP)"
Initialize a block filter index for the given type if one does not already exist\&. Returns true if a new index is created and false if one has already been initialized\&. 
.SH "Variable Documentation"
.PP 
.SS "size_t CF_HEADERS_CACHE_MAX_SZ {2000}\fR [constexpr]\fP"
Maximum size of the cfheaders cache We have a limit to prevent a bug in filling this cache potentially turning into an OOM\&. At 2000 entries, this cache is big enough for a 2,000,000 length block chain, which we should be enough until ~2047\&. 
.SS "uint8_t DB_BLOCK_HASH {'s'}\fR [constexpr]\fP"

.SS "uint8_t DB_BLOCK_HEIGHT {'t'}\fR [constexpr]\fP"

.SS "uint8_t DB_FILTER_POS {'P'}\fR [constexpr]\fP"

.SS "unsigned int FLTR_FILE_CHUNK_SIZE = 0x100000\fR [constexpr]\fP"
The pre-allocation chunk size for fltr?????\&.dat files 
.SS "unsigned int MAX_FLTR_FILE_SIZE = 0x1000000\fR [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
