.TH "src/test/blockfilter_index_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/blockfilter_index_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <addresstype\&.h>\fP
.br
\fR#include <blockfilter\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <consensus/merkle\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <index/blockfilterindex\&.h>\fP
.br
\fR#include <interfaces/chain\&.h>\fP
.br
\fR#include <node/miner\&.h>\fP
.br
\fR#include <pow\&.h>\fP
.br
\fR#include <test/util/blockfilter\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <future>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBuildChainTestingSetup\fP"
.br
.ti -1c
.RI "class \fBIndexReorgCrash\fP"
.br
.ti -1c
.RI "struct \fBCBlockTemplate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (blockfilter_index_initial_sync, \fBBuildChainTestingSetup\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (blockfilter_index_init_destroy, \fBBasicTestingSetup\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (index_reorg_crash, \fBBuildChainTestingSetup\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_FIXTURE_TEST_CASE (blockfilter_index_init_destroy , \fBBasicTestingSetup\fP )"

.SS "BOOST_FIXTURE_TEST_CASE (blockfilter_index_initial_sync , \fBBuildChainTestingSetup\fP )"

.SS "BOOST_FIXTURE_TEST_CASE (index_reorg_crash , \fBBuildChainTestingSetup\fP )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
