.TH "src/test/blockmanager_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/blockmanager_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <chain\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <clientversion\&.h>\fP
.br
\fR#include <node/blockstorage\&.h>\fP
.br
\fR#include <node/context\&.h>\fP
.br
\fR#include <node/kernel_notifications\&.h>\fP
.br
\fR#include <script/solver\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <test/util/logging\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCBlockFileInfo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (blockmanager_find_block_pos)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (blockmanager_scan_unlink_already_pruned_files, \fBTestChain100Setup\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (blockmanager_block_data_availability, \fBTestChain100Setup\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (blockmanager_block_data_part, \fBTestChain100Setup\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (blockmanager_block_data_part_error, \fBTestChain100Setup\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (blockmanager_readblock_hash_mismatch, \fBTestingSetup\fP)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (blockmanager_flush_block_file)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (blockmanager_find_block_pos )"

.SS "BOOST_AUTO_TEST_CASE (blockmanager_flush_block_file )"

.SS "BOOST_FIXTURE_TEST_CASE (blockmanager_block_data_availability , \fBTestChain100Setup\fP )"

.SS "BOOST_FIXTURE_TEST_CASE (blockmanager_block_data_part , \fBTestChain100Setup\fP )"

.SS "BOOST_FIXTURE_TEST_CASE (blockmanager_block_data_part_error , \fBTestChain100Setup\fP )"

.SS "BOOST_FIXTURE_TEST_CASE (blockmanager_readblock_hash_mismatch , \fBTestingSetup\fP )"

.SS "BOOST_FIXTURE_TEST_CASE (blockmanager_scan_unlink_already_pruned_files , \fBTestChain100Setup\fP )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
