.TH "BlockFilter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockFilter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <blockfilter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockFilter\fP ()=default"
.br
.ti -1c
.RI "\fBBlockFilter\fP (\fBBlockFilterType\fP filter_type, const \fBuint256\fP &block_hash, std::vector< unsigned char > filter, bool skip_decode_check)"
.br
.RI "Reconstruct a \fBBlockFilter\fP from parts\&. "
.ti -1c
.RI "\fBBlockFilter\fP (\fBBlockFilterType\fP filter_type, const \fBCBlock\fP &block, const \fBCBlockUndo\fP &block_undo)"
.br
.RI "Construct a new \fBBlockFilter\fP of the specified type from a block\&. "
.ti -1c
.RI "\fBBlockFilterType\fP \fBGetFilterType\fP () const"
.br
.ti -1c
.RI "const \fBuint256\fP & \fBGetBlockHash\fP () const \fBLIFETIMEBOUND\fP"
.br
.ti -1c
.RI "const \fBGCSFilter\fP & \fBGetFilter\fP () const \fBLIFETIMEBOUND\fP"
.br
.ti -1c
.RI "const std::vector< unsigned char > & \fBGetEncodedFilter\fP () const \fBLIFETIMEBOUND\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP () const"
.br
.RI "Compute the filter hash\&. "
.ti -1c
.RI "\fBuint256\fP \fBComputeHeader\fP (const \fBuint256\fP &prev_header) const"
.br
.RI "Compute the filter header given the previous one\&. "
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Complete block filter struct as defined in BIP 157\&. Serialization matches payload of "cfilter" messages\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBlockFilter\fP ()\fR [default]\fP"

.SS "\fBBlockFilter\fP (\fBBlockFilterType\fP filter_type, const \fBuint256\fP & block_hash, std::vector< unsigned char > filter, bool skip_decode_check)"

.PP
Reconstruct a \fBBlockFilter\fP from parts\&. 
.SS "\fBBlockFilter\fP (\fBBlockFilterType\fP filter_type, const \fBCBlock\fP & block, const \fBCBlockUndo\fP & block_undo)"

.PP
Construct a new \fBBlockFilter\fP of the specified type from a block\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBuint256\fP ComputeHeader (const \fBuint256\fP & prev_header) const"

.PP
Compute the filter header given the previous one\&. 
.SS "const \fBuint256\fP & GetBlockHash () const\fR [inline]\fP"

.SS "const std::vector< unsigned char > & GetEncodedFilter () const\fR [inline]\fP"

.SS "const \fBGCSFilter\fP & GetFilter () const\fR [inline]\fP"

.SS "\fBBlockFilterType\fP GetFilterType () const\fR [inline]\fP"

.SS "\fBuint256\fP GetHash () const"

.PP
Compute the filter hash\&. 
.SS "template<typename Stream> void Serialize (Stream & s) const\fR [inline]\fP"

.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
