.TH "BlockTransactions" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockTransactions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <blockencodings\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockTransactions\fP ()=default"
.br
.ti -1c
.RI "\fBBlockTransactions\fP (const \fBBlockTransactionsRequest\fP &req)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBBlockTransactions\fP, obj)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBblockhash\fP"
.br
.ti -1c
.RI "std::vector< \fBCTransactionRef\fP > \fBtxn\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBlockTransactions\fP ()\fR [default]\fP"

.SS "\fBBlockTransactions\fP (const \fBBlockTransactionsRequest\fP & req)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "SERIALIZE_METHODS (\fBBlockTransactions\fP , obj )\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP blockhash"

.SS "std::vector<\fBCTransactionRef\fP> txn"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
