.TH "src/test/bloom_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/bloom_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/bloom\&.h>\fP
.br
\fR#include <clientversion\&.h>\fP
.br
\fR#include <common/system\&.h>\fP
.br
\fR#include <key\&.h>\fP
.br
\fR#include <key_io\&.h>\fP
.br
\fR#include <merkleblock\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBloomTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbloom_tests\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (bloom_create_insert_serialize)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (bloom_create_insert_serialize_with_tweak)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (bloom_create_insert_key)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (bloom_match)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (merkle_block_1)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (merkle_block_2)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (merkle_block_2_with_update_none)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (merkle_block_3_and_serialize)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (merkle_block_4)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (merkle_block_4_test_p2pubkey_only)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (merkle_block_4_test_update_none)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rolling_bloom)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (bloom_create_insert_key )"

.SS "BOOST_AUTO_TEST_CASE (bloom_create_insert_serialize )"

.SS "BOOST_AUTO_TEST_CASE (bloom_create_insert_serialize_with_tweak )"

.SS "BOOST_AUTO_TEST_CASE (bloom_match )"

.SS "BOOST_AUTO_TEST_CASE (merkle_block_1 )"

.SS "BOOST_AUTO_TEST_CASE (merkle_block_2 )"

.SS "BOOST_AUTO_TEST_CASE (merkle_block_2_with_update_none )"

.SS "BOOST_AUTO_TEST_CASE (merkle_block_3_and_serialize )"

.SS "BOOST_AUTO_TEST_CASE (merkle_block_4 )"

.SS "BOOST_AUTO_TEST_CASE (merkle_block_4_test_p2pubkey_only )"

.SS "BOOST_AUTO_TEST_CASE (merkle_block_4_test_update_none )"

.SS "BOOST_AUTO_TEST_CASE (rolling_bloom )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
