.TH "src/common/bloom.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/common/bloom.h
.SH SYNOPSIS
.br
.PP
\fR#include <serialize\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCBloomFilter\fP"
.br
.ti -1c
.RI "class \fBCRollingBloomFilter\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBbloomflags\fP { \fBBLOOM_UPDATE_NONE\fP = 0, \fBBLOOM_UPDATE_ALL\fP = 1, \fBBLOOM_UPDATE_P2PUBKEY_ONLY\fP = 2, \fBBLOOM_UPDATE_MASK\fP = 3 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBbloomflags\fP"
First two bits of nFlags control how much IsRelevantAndUpdate actually updates The remaining bits are reserved 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIBLOOM_UPDATE_NONE \fP
.TP
\f(BIBLOOM_UPDATE_ALL \fP
.TP
\f(BIBLOOM_UPDATE_P2PUBKEY_ONLY \fP
.TP
\f(BIBLOOM_UPDATE_MASK \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
