.TH "src/leveldb/util/bloom_test.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/util/bloom_test.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'leveldb/filter_policy\&.h'\fP
.br
\fR#include 'util/coding\&.h'\fP
.br
\fR#include 'util/logging\&.h'\fP
.br
\fR#include 'util/testharness\&.h'\fP
.br
\fR#include 'util/testutil\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBloomTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBBloomTest\fP, EmptyFilter)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBBloomTest\fP, Small)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBBloomTest\fP, VaryingLengths)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
