.TH "TransactionSpentOutputsView" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionSpentOutputsView
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBView< btck_TransactionSpentOutputs >\fP, and \fBTransactionSpentOutputsApi< TransactionSpentOutputsView >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionSpentOutputsView\fP (const \fBbtck_TransactionSpentOutputs\fP *ptr)"
.br
.in -1c

Public Member Functions inherited from \fBView< btck_TransactionSpentOutputs >\fP
.in +1c
.ti -1c
.RI "\fBView\fP (const \fBbtck_TransactionSpentOutputs\fP *ptr)"
.br
.ti -1c
.RI "const \fBbtck_TransactionSpentOutputs\fP * \fBget\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBTransactionSpentOutputsApi< TransactionSpentOutputsView >\fP
.in +1c
.ti -1c
.RI "size_t \fBCount\fP () const"
.br
.ti -1c
.RI "\fBCoinView\fP \fBGetCoin\fP (size_t index) const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBView< btck_TransactionSpentOutputs >\fP
.in +1c
.ti -1c
.RI "const \fBbtck_TransactionSpentOutputs\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TransactionSpentOutputsView (const \fBbtck_TransactionSpentOutputs\fP * ptr)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
