.TH "Txid" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Txid
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBHandle< btck_Txid, btck_txid_copy, btck_txid_destroy >\fP, and \fBTxidApi< Txid >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTxid\fP (const \fBTxidView\fP &view)"
.br
.in -1c

Public Member Functions inherited from \fBHandle< btck_Txid, btck_txid_copy, btck_txid_destroy >\fP
.in +1c
.ti -1c
.RI "\fBHandle\fP (\fBbtck_Txid\fP *ptr)"
.br
.ti -1c
.RI "\fBHandle\fP & \fBoperator=\fP (const \fBHandle\fP &other)"
.br
.ti -1c
.RI "\fB~Handle\fP ()"
.br
.ti -1c
.RI "\fBbtck_Txid\fP * \fBget\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBTxidApi< Txid >\fP
.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const TxidApi &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const TxidApi &other) const"
.br
.ti -1c
.RI "std::array< std::byte, 32 > \fBToBytes\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBHandle< btck_Txid, btck_txid_copy, btck_txid_destroy >\fP
.in +1c
.ti -1c
.RI "\fBbtck_Txid\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Txid (const \fBTxidView\fP & view)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
