.TH "ChainParams" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChainParams
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBHandle< btck_ChainParameters, btck_chain_parameters_copy, btck_chain_parameters_destroy >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChainParams\fP (\fBChainType\fP chain_type)"
.br
.in -1c

Public Member Functions inherited from \fBHandle< btck_ChainParameters, btck_chain_parameters_copy, btck_chain_parameters_destroy >\fP
.in +1c
.ti -1c
.RI "\fBHandle\fP (\fBbtck_ChainParameters\fP *ptr)"
.br
.ti -1c
.RI "\fBHandle\fP & \fBoperator=\fP (const \fBHandle\fP &other)"
.br
.ti -1c
.RI "\fB~Handle\fP ()"
.br
.ti -1c
.RI "\fBbtck_ChainParameters\fP * \fBget\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBHandle< btck_ChainParameters, btck_chain_parameters_copy, btck_chain_parameters_destroy >\fP
.in +1c
.ti -1c
.RI "\fBbtck_ChainParameters\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChainParams (\fBChainType\fP chain_type)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
