.TH "BlockHashApi< Derived >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockHashApi< Derived >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBDerived\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBDerived\fP &other) const"
.br
.ti -1c
.RI "std::array< std::byte, 32 > \fBToBytes\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBDerived\fP> bool operator!= (const \fBDerived\fP & other) const\fR [inline]\fP"

.SS "template<typename \fBDerived\fP> bool operator== (const \fBDerived\fP & other) const\fR [inline]\fP"

.SS "template<typename \fBDerived\fP> std::array< std::byte, 32 > ToBytes () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
