.TH "Context" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Context
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBHandle< btck_Context, btck_context_copy, btck_context_destroy >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContext\fP (\fBContextOptions\fP &opts)"
.br
.ti -1c
.RI "\fBContext\fP ()"
.br
.ti -1c
.RI "bool \fBinterrupt\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBHandle< btck_Context, btck_context_copy, btck_context_destroy >\fP
.in +1c
.ti -1c
.RI "\fBHandle\fP (\fBbtck_Context\fP *ptr)"
.br
.ti -1c
.RI "\fBHandle\fP & \fBoperator=\fP (const \fBHandle\fP &other)"
.br
.ti -1c
.RI "\fB~Handle\fP ()"
.br
.ti -1c
.RI "\fBbtck_Context\fP * \fBget\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBHandle< btck_Context, btck_context_copy, btck_context_destroy >\fP
.in +1c
.ti -1c
.RI "\fBbtck_Context\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Context (\fBContextOptions\fP & opts)\fR [inline]\fP"

.SS "Context ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool interrupt ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
