.TH "BlockTreeEntry" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockTreeEntry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBView< btck_BlockTreeEntry >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockTreeEntry\fP (const \fBbtck_BlockTreeEntry\fP *entry)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBBlockTreeEntry\fP &other) const"
.br
.ti -1c
.RI "std::optional< \fBBlockTreeEntry\fP > \fBGetPrevious\fP () const"
.br
.ti -1c
.RI "int32_t \fBGetHeight\fP () const"
.br
.ti -1c
.RI "\fBBlockHashView\fP \fBGetHash\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBView< btck_BlockTreeEntry >\fP
.in +1c
.ti -1c
.RI "\fBView\fP (const \fBbtck_BlockTreeEntry\fP *ptr)"
.br
.ti -1c
.RI "const \fBbtck_BlockTreeEntry\fP * \fBget\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBView< btck_BlockTreeEntry >\fP
.in +1c
.ti -1c
.RI "const \fBbtck_BlockTreeEntry\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockTreeEntry (const \fBbtck_BlockTreeEntry\fP * entry)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBBlockHashView\fP GetHash () const\fR [inline]\fP"

.SS "int32_t GetHeight () const\fR [inline]\fP"

.SS "std::optional< \fBBlockTreeEntry\fP > GetPrevious () const\fR [inline]\fP"

.SS "bool operator== (const \fBBlockTreeEntry\fP & other) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
