.TH "ChainstateManagerOptions" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChainstateManagerOptions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBUniqueHandle< btck_ChainstateManagerOptions, btck_chainstate_manager_options_destroy >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChainstateManagerOptions\fP (const \fBContext\fP &context, std::string_view data_dir, std::string_view blocks_dir)"
.br
.ti -1c
.RI "void \fBSetWorkerThreads\fP (int worker_threads)"
.br
.ti -1c
.RI "bool \fBSetWipeDbs\fP (bool wipe_block_tree, bool wipe_chainstate)"
.br
.ti -1c
.RI "void \fBUpdateBlockTreeDbInMemory\fP (bool block_tree_db_in_memory)"
.br
.ti -1c
.RI "void \fBUpdateChainstateDbInMemory\fP (bool chainstate_db_in_memory)"
.br
.in -1c

Public Member Functions inherited from \fBUniqueHandle< btck_ChainstateManagerOptions, btck_chainstate_manager_options_destroy >\fP
.in +1c
.ti -1c
.RI "\fBUniqueHandle\fP (\fBbtck_ChainstateManagerOptions\fP *ptr)"
.br
.ti -1c
.RI "\fBbtck_ChainstateManagerOptions\fP * \fBget\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBUniqueHandle< btck_ChainstateManagerOptions, btck_chainstate_manager_options_destroy >\fP
.in +1c
.ti -1c
.RI "std::unique_ptr< \fBbtck_ChainstateManagerOptions\fP, Deleter > \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChainstateManagerOptions (const \fBContext\fP & context, std::string_view data_dir, std::string_view blocks_dir)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool SetWipeDbs (bool wipe_block_tree, bool wipe_chainstate)\fR [inline]\fP"

.SS "void SetWorkerThreads (int worker_threads)\fR [inline]\fP"

.SS "void UpdateBlockTreeDbInMemory (bool block_tree_db_in_memory)\fR [inline]\fP"

.SS "void UpdateChainstateDbInMemory (bool chainstate_db_in_memory)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
