.TH "KernelNotifications" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KernelNotifications
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherited by \fBTestKernelNotifications\fP, and \fBTestKernelNotifications\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~KernelNotifications\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBBlockTipHandler\fP (\fBSynchronizationState\fP state, \fBBlockTreeEntry\fP entry, double verification_progress)"
.br
.ti -1c
.RI "virtual void \fBHeaderTipHandler\fP (\fBSynchronizationState\fP state, int64_t height, int64_t timestamp, bool presync)"
.br
.ti -1c
.RI "virtual void \fBProgressHandler\fP (std::string_view title, int progress_percent, bool resume_possible)"
.br
.ti -1c
.RI "virtual void \fBWarningSetHandler\fP (\fBWarning\fP warning, std::string_view message)"
.br
.ti -1c
.RI "virtual void \fBWarningUnsetHandler\fP (\fBWarning\fP warning)"
.br
.ti -1c
.RI "virtual void \fBFlushErrorHandler\fP (std::string_view error)"
.br
.ti -1c
.RI "virtual void \fBFatalErrorHandler\fP (std::string_view error)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBKernelNotifications\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void BlockTipHandler (\fBSynchronizationState\fP state, \fBBlockTreeEntry\fP entry, double verification_progress)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBTestKernelNotifications\fP\&.
.SS "virtual void FatalErrorHandler (std::string_view error)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBTestKernelNotifications\fP, and \fBTestKernelNotifications\fP\&.
.SS "virtual void FlushErrorHandler (std::string_view error)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBTestKernelNotifications\fP, and \fBTestKernelNotifications\fP\&.
.SS "virtual void HeaderTipHandler (\fBSynchronizationState\fP state, int64_t height, int64_t timestamp, bool presync)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBTestKernelNotifications\fP\&.
.SS "virtual void ProgressHandler (std::string_view title, int progress_percent, bool resume_possible)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBTestKernelNotifications\fP\&.
.SS "virtual void WarningSetHandler (\fBWarning\fP warning, std::string_view message)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBTestKernelNotifications\fP, and \fBTestKernelNotifications\fP\&.
.SS "virtual void WarningUnsetHandler (\fBWarning\fP warning)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBTestKernelNotifications\fP, and \fBTestKernelNotifications\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
