.TH "TransactionView" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionView
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBView< btck_Transaction >\fP, and \fBTransactionApi< TransactionView >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionView\fP (const \fBbtck_Transaction\fP *ptr)"
.br
.in -1c

Public Member Functions inherited from \fBView< btck_Transaction >\fP
.in +1c
.ti -1c
.RI "\fBView\fP (const \fBbtck_Transaction\fP *ptr)"
.br
.ti -1c
.RI "const \fBbtck_Transaction\fP * \fBget\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBTransactionApi< TransactionView >\fP
.in +1c
.ti -1c
.RI "size_t \fBCountOutputs\fP () const"
.br
.ti -1c
.RI "size_t \fBCountInputs\fP () const"
.br
.ti -1c
.RI "\fBTransactionOutputView\fP \fBGetOutput\fP (size_t index) const"
.br
.ti -1c
.RI "\fBTransactionInputView\fP \fBGetInput\fP (size_t index) const"
.br
.ti -1c
.RI "\fBTxidView\fP \fBTxid\fP () const"
.br
.ti -1c
.RI "std::vector< std::byte > \fBToBytes\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBView< btck_Transaction >\fP
.in +1c
.ti -1c
.RI "const \fBbtck_Transaction\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTransactionView\fP (const \fBbtck_Transaction\fP * ptr)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
