.TH "btck_NotificationInterfaceCallbacks" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
btck_NotificationInterfaceCallbacks
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "\fBbtck_DestroyCallback\fP \fBuser_data_destroy\fP"
.br
.RI "Frees the provided user data structure\&. "
.ti -1c
.RI "\fBbtck_NotifyBlockTip\fP \fBblock_tip\fP"
.br
.RI "The chain's tip was updated to the provided block entry\&. "
.ti -1c
.RI "\fBbtck_NotifyHeaderTip\fP \fBheader_tip\fP"
.br
.RI "A new best block header was added\&. "
.ti -1c
.RI "\fBbtck_NotifyProgress\fP \fBprogress\fP"
.br
.RI "Reports on current block synchronization progress\&. "
.ti -1c
.RI "\fBbtck_NotifyWarningSet\fP \fBwarning_set\fP"
.br
.RI "A warning issued by the kernel library during validation\&. "
.ti -1c
.RI "\fBbtck_NotifyWarningUnset\fP \fBwarning_unset\fP"
.br
.RI "A previous condition leading to the issuance of a warning is no longer given\&. "
.ti -1c
.RI "\fBbtck_NotifyFlushError\fP \fBflush_error\fP"
.br
.RI "An error encountered when flushing data to disk\&. "
.ti -1c
.RI "\fBbtck_NotifyFatalError\fP \fBfatal_error\fP"
.br
.RI "An unrecoverable system error encountered by the library\&. "
.in -1c
.SH "Detailed Description"
.PP 
A struct for holding the kernel notification callbacks\&. The user data pointer may be used to point to user-defined structures to make processing the notifications easier\&.

.PP
If user_data_destroy is provided, the kernel will automatically call this callback to clean up user_data when the notification interface object is destroyed\&. If user_data_destroy is NULL, it is the user's responsibility to ensure that the user_data outlives the kernel objects\&. \fBNotifications\fP can occur even as kernel objects are deleted, so care has to be taken to ensure safe unwinding\&. 
.SH "Field Documentation"
.PP 
.SS "\fBbtck_NotifyBlockTip\fP block_tip"

.PP
The chain's tip was updated to the provided block entry\&. 
.SS "\fBbtck_NotifyFatalError\fP fatal_error"

.PP
An unrecoverable system error encountered by the library\&. 
.SS "\fBbtck_NotifyFlushError\fP flush_error"

.PP
An error encountered when flushing data to disk\&. 
.SS "\fBbtck_NotifyHeaderTip\fP header_tip"

.PP
A new best block header was added\&. 
.SS "\fBbtck_NotifyProgress\fP progress"

.PP
Reports on current block synchronization progress\&. 
.SS "void* user_data"
Holds a user-defined opaque structure that is passed to the notification callbacks\&. If user_data_destroy is also defined ownership of the user_data is passed to the created context options and subsequently context\&. 
.SS "\fBbtck_DestroyCallback\fP user_data_destroy"

.PP
Frees the provided user data structure\&. 
.SS "\fBbtck_NotifyWarningSet\fP warning_set"

.PP
A warning issued by the kernel library during validation\&. 
.SS "\fBbtck_NotifyWarningUnset\fP warning_unset"

.PP
A previous condition leading to the issuance of a warning is no longer given\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
