.TH "BlockHashView" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockHashView
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBView< btck_BlockHash >\fP, and \fBBlockHashApi< BlockHashView >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockHashView\fP (const \fBbtck_BlockHash\fP *ptr)"
.br
.in -1c

Public Member Functions inherited from \fBView< btck_BlockHash >\fP
.in +1c
.ti -1c
.RI "\fBView\fP (const \fBbtck_BlockHash\fP *ptr)"
.br
.ti -1c
.RI "const \fBbtck_BlockHash\fP * \fBget\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBBlockHashApi< BlockHashView >\fP
.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBBlockHashView\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBBlockHashView\fP &other) const"
.br
.ti -1c
.RI "std::array< std::byte, 32 > \fBToBytes\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBView< btck_BlockHash >\fP
.in +1c
.ti -1c
.RI "const \fBbtck_BlockHash\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockHashView (const \fBbtck_BlockHash\fP * ptr)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
