.TH "TxidView" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxidView
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBView< btck_Txid >\fP, and \fBTxidApi< TxidView >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTxidView\fP (const \fBbtck_Txid\fP *ptr)"
.br
.in -1c

Public Member Functions inherited from \fBView< btck_Txid >\fP
.in +1c
.ti -1c
.RI "\fBView\fP (const \fBbtck_Txid\fP *ptr)"
.br
.ti -1c
.RI "const \fBbtck_Txid\fP * \fBget\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBTxidApi< TxidView >\fP
.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const TxidApi &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const TxidApi &other) const"
.br
.ti -1c
.RI "std::array< std::byte, 32 > \fBToBytes\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBView< btck_Txid >\fP
.in +1c
.ti -1c
.RI "const \fBbtck_Txid\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TxidView (const \fBbtck_Txid\fP * ptr)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
