.TH "Block" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Block
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBHandle< btck_Block, btck_block_copy, btck_block_destroy >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlock\fP (const std::span< const std::byte > raw_block)"
.br
.ti -1c
.RI "\fBBlock\fP (\fBbtck_Block\fP *block)"
.br
.ti -1c
.RI "size_t \fBCountTransactions\fP () const"
.br
.ti -1c
.RI "\fBTransactionView\fP \fBGetTransaction\fP (size_t index) const"
.br
.ti -1c
.RI "\fBBlockHash\fP \fBGetHash\fP () const"
.br
.ti -1c
.RI "std::vector< std::byte > \fBToBytes\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBHandle< btck_Block, btck_block_copy, btck_block_destroy >\fP
.in +1c
.ti -1c
.RI "\fBHandle\fP (\fBbtck_Block\fP *ptr)"
.br
.ti -1c
.RI "\fBHandle\fP & \fBoperator=\fP (const \fBHandle\fP &other)"
.br
.ti -1c
.RI "\fB~Handle\fP ()"
.br
.ti -1c
.RI "\fBbtck_Block\fP * \fBget\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBHandle< btck_Block, btck_block_copy, btck_block_destroy >\fP
.in +1c
.ti -1c
.RI "\fBbtck_Block\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Block (const std::span< const std::byte > raw_block)\fR [inline]\fP"

.SS "Block (\fBbtck_Block\fP * block)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "size_t CountTransactions () const\fR [inline]\fP"

.SS "\fBBlockHash\fP GetHash () const\fR [inline]\fP"

.SS "\fBTransactionView\fP GetTransaction (size_t index) const\fR [inline]\fP"

.SS "std::vector< std::byte > ToBytes () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
