.TH "ScriptPubkeyView" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScriptPubkeyView
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBView< btck_ScriptPubkey >\fP, and \fBScriptPubkeyApi< ScriptPubkeyView >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScriptPubkeyView\fP (const \fBbtck_ScriptPubkey\fP *ptr)"
.br
.in -1c

Public Member Functions inherited from \fBView< btck_ScriptPubkey >\fP
.in +1c
.ti -1c
.RI "\fBView\fP (const \fBbtck_ScriptPubkey\fP *ptr)"
.br
.ti -1c
.RI "const \fBbtck_ScriptPubkey\fP * \fBget\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBScriptPubkeyApi< ScriptPubkeyView >\fP
.in +1c
.ti -1c
.RI "bool \fBVerify\fP (int64_t amount, const \fBTransaction\fP &tx_to, std::span< const \fBTransactionOutput\fP > spent_outputs, unsigned int input_index, \fBScriptVerificationFlags\fP \fBflags\fP, \fBScriptVerifyStatus\fP &status) const"
.br
.ti -1c
.RI "std::vector< std::byte > \fBToBytes\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBView< btck_ScriptPubkey >\fP
.in +1c
.ti -1c
.RI "const \fBbtck_ScriptPubkey\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ScriptPubkeyView (const \fBbtck_ScriptPubkey\fP * ptr)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
