.TH "btck_LoggingOptions" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
btck_LoggingOptions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlog_timestamps\fP"
.br
.RI "Prepend a timestamp to log messages\&. "
.ti -1c
.RI "int \fBlog_time_micros\fP"
.br
.RI "Log timestamps in microsecond precision\&. "
.ti -1c
.RI "int \fBlog_threadnames\fP"
.br
.RI "Prepend the name of the thread to log messages\&. "
.ti -1c
.RI "int \fBlog_sourcelocations\fP"
.br
.RI "Prepend the source location to log messages\&. "
.ti -1c
.RI "int \fBalways_print_category_levels\fP"
.br
.RI "Prepend the log category and level to log messages\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBOptions\fP controlling the format of log messages\&.

.PP
Set fields as non-zero to indicate true\&. 
.SH "Field Documentation"
.PP 
.SS "int always_print_category_levels"

.PP
Prepend the log category and level to log messages\&. 
.SS "int log_sourcelocations"

.PP
Prepend the source location to log messages\&. 
.SS "int log_threadnames"

.PP
Prepend the name of the thread to log messages\&. 
.SS "int log_time_micros"

.PP
Log timestamps in microsecond precision\&. 
.SS "int log_timestamps"

.PP
Prepend a timestamp to log messages\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
