.TH "OutPoint" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutPoint
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBHandle< btck_TransactionOutPoint, btck_transaction_out_point_copy, btck_transaction_out_point_destroy >\fP, and \fBOutPointApi< OutPoint >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOutPoint\fP (const \fBOutPointView\fP &view)"
.br
.in -1c

Public Member Functions inherited from \fBHandle< btck_TransactionOutPoint, btck_transaction_out_point_copy, btck_transaction_out_point_destroy >\fP
.in +1c
.ti -1c
.RI "\fBHandle\fP (\fBbtck_TransactionOutPoint\fP *ptr)"
.br
.ti -1c
.RI "\fBHandle\fP & \fBoperator=\fP (const \fBHandle\fP &other)"
.br
.ti -1c
.RI "\fB~Handle\fP ()"
.br
.ti -1c
.RI "\fBbtck_TransactionOutPoint\fP * \fBget\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBOutPointApi< OutPoint >\fP
.in +1c
.ti -1c
.RI "uint32_t \fBindex\fP () const"
.br
.ti -1c
.RI "\fBTxidView\fP \fBTxid\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBHandle< btck_TransactionOutPoint, btck_transaction_out_point_copy, btck_transaction_out_point_destroy >\fP
.in +1c
.ti -1c
.RI "\fBbtck_TransactionOutPoint\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OutPoint (const \fBOutPointView\fP & view)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
