.TH "TransactionOutput" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionOutput
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBHandle< btck_TransactionOutput, btck_transaction_output_copy, btck_transaction_output_destroy >\fP, and \fBTransactionOutputApi< TransactionOutput >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionOutput\fP (const \fBScriptPubkey\fP &script_pubkey, int64_t amount)"
.br
.ti -1c
.RI "\fBTransactionOutput\fP (const \fBTransactionOutputView\fP &view)"
.br
.in -1c

Public Member Functions inherited from \fBHandle< btck_TransactionOutput, btck_transaction_output_copy, btck_transaction_output_destroy >\fP
.in +1c
.ti -1c
.RI "\fBHandle\fP (\fBbtck_TransactionOutput\fP *ptr)"
.br
.ti -1c
.RI "\fBHandle\fP & \fBoperator=\fP (const \fBHandle\fP &other)"
.br
.ti -1c
.RI "\fB~Handle\fP ()"
.br
.ti -1c
.RI "\fBbtck_TransactionOutput\fP * \fBget\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBTransactionOutputApi< TransactionOutput >\fP
.in +1c
.ti -1c
.RI "int64_t \fBAmount\fP () const"
.br
.ti -1c
.RI "\fBScriptPubkeyView\fP \fBGetScriptPubkey\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBHandle< btck_TransactionOutput, btck_transaction_output_copy, btck_transaction_output_destroy >\fP
.in +1c
.ti -1c
.RI "\fBbtck_TransactionOutput\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TransactionOutput (const \fBScriptPubkey\fP & script_pubkey, int64_t amount)\fR [inline]\fP, \fR [explicit]\fP"

.SS "TransactionOutput (const \fBTransactionOutputView\fP & view)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
