.TH "Handle< CType, CopyFunc, DestroyFunc >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Handle< CType, CopyFunc, DestroyFunc >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHandle\fP (CType *ptr)"
.br
.ti -1c
.RI "\fBHandle\fP (const Handle &other)"
.br
.ti -1c
.RI "\fBHandle\fP & \fBoperator=\fP (const \fBHandle\fP &other)"
.br
.ti -1c
.RI "\fBHandle\fP (Handle &&other) noexcept"
.br
.ti -1c
.RI "\fBHandle\fP & \fBoperator=\fP (\fBHandle\fP &&other) noexcept"
.br
.ti -1c
.RI "template<typename ViewType> 
.br
requires std::derived_from<ViewType, \fBView\fP<CType>>\fBHandle\fP (const ViewType &view)"
.br
.ti -1c
.RI "\fB~Handle\fP ()"
.br
.ti -1c
.RI "CType * \fBget\fP ()"
.br
.ti -1c
.RI "const CType * \fBget\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "CType * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CType, CType *(*)(const CType *) CopyFunc, void(*)(CType *) DestroyFunc> Handle (CType * ptr)\fR [inline]\fP, \fR [explicit]\fP"

.SS "template<typename CType, CType *(*)(const CType *) CopyFunc, void(*)(CType *) DestroyFunc> Handle (const Handle< CType, CopyFunc, DestroyFunc > & other)\fR [inline]\fP"

.SS "template<typename CType, CType *(*)(const CType *) CopyFunc, void(*)(CType *) DestroyFunc> Handle (Handle< CType, CopyFunc, DestroyFunc > && other)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<typename CType, CType *(*)(const CType *) CopyFunc, void(*)(CType *) DestroyFunc> template<typename ViewType> 
.br
requires std::derived_from<ViewType, \fBView\fP<CType>>Handle (const ViewType & view)\fR [inline]\fP"

.SS "template<typename CType, CType *(*)(const CType *) CopyFunc, void(*)(CType *) DestroyFunc> ~\fBHandle\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename CType, CType *(*)(const CType *) CopyFunc, void(*)(CType *) DestroyFunc> CType * get ()\fR [inline]\fP"

.SS "template<typename CType, CType *(*)(const CType *) CopyFunc, void(*)(CType *) DestroyFunc> const CType * get () const\fR [inline]\fP"

.SS "template<typename CType, CType *(*)(const CType *) CopyFunc, void(*)(CType *) DestroyFunc> \fBHandle\fP & operator= (const \fBHandle\fP< CType, CopyFunc, DestroyFunc > & other)\fR [inline]\fP"

.SS "template<typename CType, CType *(*)(const CType *) CopyFunc, void(*)(CType *) DestroyFunc> \fBHandle\fP & operator= (\fBHandle\fP< CType, CopyFunc, DestroyFunc > && other)\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Field Documentation"
.PP 
.SS "template<typename CType, CType *(*)(const CType *) CopyFunc, void(*)(CType *) DestroyFunc> CType* m_ptr\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
