.TH "Coin" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coin
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBHandle< btck_Coin, btck_coin_copy, btck_coin_destroy >\fP, and \fBCoinApi< Coin >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoin\fP (\fBbtck_Coin\fP *coin)"
.br
.ti -1c
.RI "\fBCoin\fP (const \fBCoinView\fP &view)"
.br
.in -1c

Public Member Functions inherited from \fBHandle< btck_Coin, btck_coin_copy, btck_coin_destroy >\fP
.in +1c
.ti -1c
.RI "\fBHandle\fP (\fBbtck_Coin\fP *ptr)"
.br
.ti -1c
.RI "\fBHandle\fP & \fBoperator=\fP (const \fBHandle\fP &other)"
.br
.ti -1c
.RI "\fB~Handle\fP ()"
.br
.ti -1c
.RI "\fBbtck_Coin\fP * \fBget\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBCoinApi< Coin >\fP
.in +1c
.ti -1c
.RI "uint32_t \fBGetConfirmationHeight\fP () const"
.br
.ti -1c
.RI "bool \fBIsCoinbase\fP () const"
.br
.ti -1c
.RI "\fBTransactionOutputView\fP \fBGetOutput\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBHandle< btck_Coin, btck_coin_copy, btck_coin_destroy >\fP
.in +1c
.ti -1c
.RI "\fBbtck_Coin\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCoin\fP (\fBbtck_Coin\fP * coin)\fR [inline]\fP"

.SS "\fBCoin\fP (const \fBCoinView\fP & view)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
