.TH "OutPointApi< Derived >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutPointApi< Derived >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBindex\fP () const"
.br
.ti -1c
.RI "\fBTxidView\fP \fBTxid\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBDerived\fP> uint32_t index () const\fR [inline]\fP"

.SS "template<typename \fBDerived\fP> \fBTxidView\fP Txid () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
