.TH "TransactionOutputView" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionOutputView
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.PP
Inherits \fBView< btck_TransactionOutput >\fP, and \fBTransactionOutputApi< TransactionOutputView >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionOutputView\fP (const \fBbtck_TransactionOutput\fP *ptr)"
.br
.in -1c

Public Member Functions inherited from \fBView< btck_TransactionOutput >\fP
.in +1c
.ti -1c
.RI "\fBView\fP (const \fBbtck_TransactionOutput\fP *ptr)"
.br
.ti -1c
.RI "const \fBbtck_TransactionOutput\fP * \fBget\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBTransactionOutputApi< TransactionOutputView >\fP
.in +1c
.ti -1c
.RI "int64_t \fBAmount\fP () const"
.br
.ti -1c
.RI "\fBScriptPubkeyView\fP \fBGetScriptPubkey\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBView< btck_TransactionOutput >\fP
.in +1c
.ti -1c
.RI "const \fBbtck_TransactionOutput\fP * \fBm_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TransactionOutputView (const \fBbtck_TransactionOutput\fP * ptr)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
