.TH "Range< Container, SizeFunc, GetFunc >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Range< Container, SizeFunc, GetFunc >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bitcoinkernel_wrapper\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_type\fP = std::invoke_result_t<decltype(GetFunc), const Container&, size_t>"
.br
.ti -1c
.RI "using \fBdifference_type\fP = std::ptrdiff_t"
.br
.ti -1c
.RI "using \fBiterator\fP = \fBIterator\fP<\fBRange\fP, \fBvalue_type\fP>"
.br
.ti -1c
.RI "using \fBconst_iterator\fP = \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRange\fP (const Container &container)"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP () const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBcbegin\fP () const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBcend\fP () const"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "\fBvalue_type\fP \fBoperator[]\fP (size_t index) const"
.br
.ti -1c
.RI "\fBvalue_type\fP \fBat\fP (size_t index) const"
.br
.ti -1c
.RI "\fBvalue_type\fP \fBfront\fP () const"
.br
.ti -1c
.RI "\fBvalue_type\fP \fBback\fP () const"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename Container, auto SizeFunc, auto GetFunc> using \fBconst_iterator\fP = \fBiterator\fP"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> using \fBdifference_type\fP = std::ptrdiff_t"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> using \fBiterator\fP = \fBIterator\fP<\fBRange\fP, \fBvalue_type\fP>"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> using \fBvalue_type\fP = std::invoke_result_t<decltype(GetFunc), const Container&, size_t>"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Container, auto SizeFunc, auto GetFunc> \fBRange\fP (const Container & container)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Container, auto SizeFunc, auto GetFunc> \fBvalue_type\fP at (size_t index) const\fR [inline]\fP"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> \fBvalue_type\fP back () const\fR [inline]\fP"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> \fBiterator\fP begin () const\fR [inline]\fP"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> \fBconst_iterator\fP cbegin () const\fR [inline]\fP"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> \fBconst_iterator\fP cend () const\fR [inline]\fP"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> bool empty () const\fR [inline]\fP"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> \fBiterator\fP end () const\fR [inline]\fP"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> \fBvalue_type\fP front () const\fR [inline]\fP"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> \fBvalue_type\fP operator[] (size_t index) const\fR [inline]\fP"

.SS "template<typename Container, auto SizeFunc, auto GetFunc> size_t size () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
