.TH "ByteType" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ByteType
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <common\&.h>\fP
.SH "Concept definition"
.PP 

.nf
template<typename B>
concept ByteType =  std::same_as<B, unsigned char> || std::same_as<B, std::byte>
.PP
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
