.TH "src/util/byte_units.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/byte_units.h
.SH SYNOPSIS
.br
.PP
\fR#include <util/overflow\&.h>\fP
.br
\fR#include <stdexcept>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr size_t \fBoperator''_MiB\fP (unsigned long long mebibytes)"
.br
.RI "Overflow-safe conversion of MiB to bytes\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t operator''_MiB (unsigned long long mebibytes)\fR [constexpr]\fP"

.PP
Overflow-safe conversion of MiB to bytes\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
