.TH "ByteVectorHash" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ByteVectorHash
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bytevectorhash\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBByteVectorHash\fP ()"
.br
.ti -1c
.RI "size_t \fBoperator()\fP (const std::vector< unsigned char > &input) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of Hash named requirement for types that internally store a byte array\&. This may be used as the hash function in std::unordered_set or std::unordered_map over such types\&. Internally, this uses a random instance of SipHash-2-4\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBByteVectorHash\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "size_t operator() (const std::vector< unsigned char > & input) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
