.TH "src/compat/byteswap.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/compat/byteswap.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBSWAP_CONSTEXPR\fP   constexpr"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint16_t \fBinternal_bswap_16\fP (uint16_t x)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint32_t \fBinternal_bswap_32\fP (uint32_t x)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint64_t \fBinternal_bswap_64\fP (uint64_t x)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BSWAP_CONSTEXPR   constexpr"

.SH "Function Documentation"
.PP 
.SS "\fBBSWAP_CONSTEXPR\fP uint16_t internal_bswap_16 (uint16_t x)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint32_t internal_bswap_32 (uint32_t x)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint64_t internal_bswap_64 (uint64_t x)\fR [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
