.TH "src/leveldb/db/c.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/db/c.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'leveldb/c\&.h'\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include 'leveldb/cache\&.h'\fP
.br
\fR#include 'leveldb/comparator\&.h'\fP
.br
\fR#include 'leveldb/db\&.h'\fP
.br
\fR#include 'leveldb/env\&.h'\fP
.br
\fR#include 'leveldb/filter_policy\&.h'\fP
.br
\fR#include 'leveldb/iterator\&.h'\fP
.br
\fR#include 'leveldb/options\&.h'\fP
.br
\fR#include 'leveldb/status\&.h'\fP
.br
\fR#include 'leveldb/write_batch\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBleveldb_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_iterator_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_writebatch_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_snapshot_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_readoptions_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_writeoptions_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_options_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_cache_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_seqfile_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_randomfile_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_writablefile_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_logger_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_filelock_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_comparator_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_filterpolicy_t\fP"
.br
.ti -1c
.RI "struct \fBleveldb_env_t\fP"
.br
.ti -1c
.RI "class \fBCache\fP"
.br
.ti -1c
.RI "class \fBComparator\fP"
.br
.ti -1c
.RI "class \fBDB\fP"
.br
.ti -1c
.RI "class \fBEnv\fP"
.br
.ti -1c
.RI "class \fBFileLock\fP"
.br
.ti -1c
.RI "class \fBFilterPolicy\fP"
.br
.ti -1c
.RI "class \fBIterator\fP"
.br
.ti -1c
.RI "class \fBLogger\fP"
.br
.ti -1c
.RI "struct \fBOptions\fP"
.br
.ti -1c
.RI "class \fBRandomAccessFile\fP"
.br
.ti -1c
.RI "struct \fBRange\fP"
.br
.ti -1c
.RI "struct \fBReadOptions\fP"
.br
.ti -1c
.RI "class \fBSequentialFile\fP"
.br
.ti -1c
.RI "class \fBSlice\fP"
.br
.ti -1c
.RI "class \fBSnapshot\fP"
.br
.ti -1c
.RI "class \fBStatus\fP"
.br
.ti -1c
.RI "class \fBWritableFile\fP"
.br
.ti -1c
.RI "class \fBWriteBatch\fP"
.br
.ti -1c
.RI "struct \fBWriteOptions\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCompressionType\fP "
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBleveldb_t\fP * \fBleveldb_open\fP (const \fBleveldb_options_t\fP *options, const char *\fBname\fP, char **errptr)"
.br
.ti -1c
.RI "void \fBleveldb_close\fP (\fBleveldb_t\fP *db)"
.br
.ti -1c
.RI "void \fBleveldb_put\fP (\fBleveldb_t\fP *db, const \fBleveldb_writeoptions_t\fP *options, const char *key, size_t keylen, const char *val, size_t vallen, char **errptr)"
.br
.ti -1c
.RI "void \fBleveldb_delete\fP (\fBleveldb_t\fP *db, const \fBleveldb_writeoptions_t\fP *options, const char *key, size_t keylen, char **errptr)"
.br
.ti -1c
.RI "void \fBleveldb_write\fP (\fBleveldb_t\fP *db, const \fBleveldb_writeoptions_t\fP *options, \fBleveldb_writebatch_t\fP *batch, char **errptr)"
.br
.ti -1c
.RI "char * \fBleveldb_get\fP (\fBleveldb_t\fP *db, const \fBleveldb_readoptions_t\fP *options, const char *key, size_t keylen, size_t *vallen, char **errptr)"
.br
.ti -1c
.RI "\fBleveldb_iterator_t\fP * \fBleveldb_create_iterator\fP (\fBleveldb_t\fP *db, const \fBleveldb_readoptions_t\fP *options)"
.br
.ti -1c
.RI "const \fBleveldb_snapshot_t\fP * \fBleveldb_create_snapshot\fP (\fBleveldb_t\fP *db)"
.br
.ti -1c
.RI "void \fBleveldb_release_snapshot\fP (\fBleveldb_t\fP *db, const \fBleveldb_snapshot_t\fP *snapshot)"
.br
.ti -1c
.RI "char * \fBleveldb_property_value\fP (\fBleveldb_t\fP *db, const char *propname)"
.br
.ti -1c
.RI "void \fBleveldb_approximate_sizes\fP (\fBleveldb_t\fP *db, int num_ranges, const char *const *range_start_key, const size_t *range_start_key_len, const char *const *range_limit_key, const size_t *range_limit_key_len, uint64_t *sizes)"
.br
.ti -1c
.RI "void \fBleveldb_compact_range\fP (\fBleveldb_t\fP *db, const char *start_key, size_t start_key_len, const char *limit_key, size_t limit_key_len)"
.br
.ti -1c
.RI "void \fBleveldb_destroy_db\fP (const \fBleveldb_options_t\fP *options, const char *\fBname\fP, char **errptr)"
.br
.ti -1c
.RI "void \fBleveldb_repair_db\fP (const \fBleveldb_options_t\fP *options, const char *\fBname\fP, char **errptr)"
.br
.ti -1c
.RI "void \fBleveldb_iter_destroy\fP (\fBleveldb_iterator_t\fP *iter)"
.br
.ti -1c
.RI "uint8_t \fBleveldb_iter_valid\fP (const \fBleveldb_iterator_t\fP *iter)"
.br
.ti -1c
.RI "void \fBleveldb_iter_seek_to_first\fP (\fBleveldb_iterator_t\fP *iter)"
.br
.ti -1c
.RI "void \fBleveldb_iter_seek_to_last\fP (\fBleveldb_iterator_t\fP *iter)"
.br
.ti -1c
.RI "void \fBleveldb_iter_seek\fP (\fBleveldb_iterator_t\fP *iter, const char *k, size_t klen)"
.br
.ti -1c
.RI "void \fBleveldb_iter_next\fP (\fBleveldb_iterator_t\fP *iter)"
.br
.ti -1c
.RI "void \fBleveldb_iter_prev\fP (\fBleveldb_iterator_t\fP *iter)"
.br
.ti -1c
.RI "const char * \fBleveldb_iter_key\fP (const \fBleveldb_iterator_t\fP *iter, size_t *klen)"
.br
.ti -1c
.RI "const char * \fBleveldb_iter_value\fP (const \fBleveldb_iterator_t\fP *iter, size_t *vlen)"
.br
.ti -1c
.RI "void \fBleveldb_iter_get_error\fP (const \fBleveldb_iterator_t\fP *iter, char **errptr)"
.br
.ti -1c
.RI "\fBleveldb_writebatch_t\fP * \fBleveldb_writebatch_create\fP ()"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_destroy\fP (\fBleveldb_writebatch_t\fP *b)"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_clear\fP (\fBleveldb_writebatch_t\fP *b)"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_put\fP (\fBleveldb_writebatch_t\fP *b, const char *key, size_t klen, const char *val, size_t vlen)"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_delete\fP (\fBleveldb_writebatch_t\fP *b, const char *key, size_t klen)"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_iterate\fP (const \fBleveldb_writebatch_t\fP *b, void *state, void(*put)(void *, const char *k, size_t klen, const char *v, size_t vlen), void(*deleted)(void *, const char *k, size_t klen))"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_append\fP (\fBleveldb_writebatch_t\fP *destination, const \fBleveldb_writebatch_t\fP *source)"
.br
.ti -1c
.RI "\fBleveldb_options_t\fP * \fBleveldb_options_create\fP ()"
.br
.ti -1c
.RI "void \fBleveldb_options_destroy\fP (\fBleveldb_options_t\fP *options)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_comparator\fP (\fBleveldb_options_t\fP *opt, \fBleveldb_comparator_t\fP *cmp)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_filter_policy\fP (\fBleveldb_options_t\fP *opt, \fBleveldb_filterpolicy_t\fP *policy)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_create_if_missing\fP (\fBleveldb_options_t\fP *opt, uint8_t v)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_error_if_exists\fP (\fBleveldb_options_t\fP *opt, uint8_t v)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_paranoid_checks\fP (\fBleveldb_options_t\fP *opt, uint8_t v)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_env\fP (\fBleveldb_options_t\fP *opt, \fBleveldb_env_t\fP *env)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_info_log\fP (\fBleveldb_options_t\fP *opt, \fBleveldb_logger_t\fP *l)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_write_buffer_size\fP (\fBleveldb_options_t\fP *opt, size_t s)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_max_open_files\fP (\fBleveldb_options_t\fP *opt, int n)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_cache\fP (\fBleveldb_options_t\fP *opt, \fBleveldb_cache_t\fP *c)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_block_size\fP (\fBleveldb_options_t\fP *opt, size_t s)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_block_restart_interval\fP (\fBleveldb_options_t\fP *opt, int n)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_max_file_size\fP (\fBleveldb_options_t\fP *opt, size_t s)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_compression\fP (\fBleveldb_options_t\fP *opt, int t)"
.br
.ti -1c
.RI "\fBleveldb_comparator_t\fP * \fBleveldb_comparator_create\fP (void *state, void(*destructor)(void *), int(*compare)(void *, const char *a, size_t alen, const char *b, size_t blen), const char *(*\fBname\fP)(void *))"
.br
.ti -1c
.RI "void \fBleveldb_comparator_destroy\fP (\fBleveldb_comparator_t\fP *cmp)"
.br
.ti -1c
.RI "\fBleveldb_filterpolicy_t\fP * \fBleveldb_filterpolicy_create\fP (void *state, void(*destructor)(void *), char *(*create_filter)(void *, const char *const *key_array, const size_t *key_length_array, int num_keys, size_t *filter_length), uint8_t(*key_may_match)(void *, const char *key, size_t length, const char *filter, size_t filter_length), const char *(*\fBname\fP)(void *))"
.br
.ti -1c
.RI "void \fBleveldb_filterpolicy_destroy\fP (\fBleveldb_filterpolicy_t\fP *filter)"
.br
.ti -1c
.RI "\fBleveldb_filterpolicy_t\fP * \fBleveldb_filterpolicy_create_bloom\fP (int bits_per_key)"
.br
.ti -1c
.RI "\fBleveldb_readoptions_t\fP * \fBleveldb_readoptions_create\fP ()"
.br
.ti -1c
.RI "void \fBleveldb_readoptions_destroy\fP (\fBleveldb_readoptions_t\fP *opt)"
.br
.ti -1c
.RI "void \fBleveldb_readoptions_set_verify_checksums\fP (\fBleveldb_readoptions_t\fP *opt, uint8_t v)"
.br
.ti -1c
.RI "void \fBleveldb_readoptions_set_fill_cache\fP (\fBleveldb_readoptions_t\fP *opt, uint8_t v)"
.br
.ti -1c
.RI "void \fBleveldb_readoptions_set_snapshot\fP (\fBleveldb_readoptions_t\fP *opt, const \fBleveldb_snapshot_t\fP *snap)"
.br
.ti -1c
.RI "\fBleveldb_writeoptions_t\fP * \fBleveldb_writeoptions_create\fP ()"
.br
.ti -1c
.RI "void \fBleveldb_writeoptions_destroy\fP (\fBleveldb_writeoptions_t\fP *opt)"
.br
.ti -1c
.RI "void \fBleveldb_writeoptions_set_sync\fP (\fBleveldb_writeoptions_t\fP *opt, uint8_t v)"
.br
.ti -1c
.RI "\fBleveldb_cache_t\fP * \fBleveldb_cache_create_lru\fP (size_t capacity)"
.br
.ti -1c
.RI "void \fBleveldb_cache_destroy\fP (\fBleveldb_cache_t\fP *cache)"
.br
.ti -1c
.RI "\fBleveldb_env_t\fP * \fBleveldb_create_default_env\fP ()"
.br
.ti -1c
.RI "void \fBleveldb_env_destroy\fP (\fBleveldb_env_t\fP *env)"
.br
.ti -1c
.RI "char * \fBleveldb_env_get_test_directory\fP (\fBleveldb_env_t\fP *env)"
.br
.ti -1c
.RI "void \fBleveldb_free\fP (void *ptr)"
.br
.ti -1c
.RI "int \fBleveldb_major_version\fP ()"
.br
.ti -1c
.RI "int \fBleveldb_minor_version\fP ()"
.br
.ti -1c
.RI "\fBLEVELDB_EXPORT\fP const \fBFilterPolicy\fP * \fBNewBloomFilterPolicy\fP (int bits_per_key)"
.br
.ti -1c
.RI "\fBLEVELDB_EXPORT\fP \fBCache\fP * \fBNewLRUCache\fP (size_t capacity)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCompressionType\fP"

.SH "Function Documentation"
.PP 
.SS "void leveldb_approximate_sizes (\fBleveldb_t\fP * db, int num_ranges, const char *const * range_start_key, const size_t * range_start_key_len, const char *const * range_limit_key, const size_t * range_limit_key_len, uint64_t * sizes)"

.SS "\fBleveldb_cache_t\fP * leveldb_cache_create_lru (size_t capacity)"

.SS "void leveldb_cache_destroy (\fBleveldb_cache_t\fP * cache)"

.SS "void leveldb_close (\fBleveldb_t\fP * db)"

.SS "void leveldb_compact_range (\fBleveldb_t\fP * db, const char * start_key, size_t start_key_len, const char * limit_key, size_t limit_key_len)"

.SS "\fBleveldb_comparator_t\fP * leveldb_comparator_create (void * state, void(* destructor )(void *), int(* compare )(void *, const char *a, size_t alen, const char *b, size_t blen), const char *(* name )(void *))"

.SS "void leveldb_comparator_destroy (\fBleveldb_comparator_t\fP * cmp)"

.SS "\fBleveldb_env_t\fP * leveldb_create_default_env (void )"

.SS "\fBleveldb_iterator_t\fP * leveldb_create_iterator (\fBleveldb_t\fP * db, const \fBleveldb_readoptions_t\fP * options)"

.SS "const \fBleveldb_snapshot_t\fP * leveldb_create_snapshot (\fBleveldb_t\fP * db)"

.SS "void leveldb_delete (\fBleveldb_t\fP * db, const \fBleveldb_writeoptions_t\fP * options, const char * key, size_t keylen, char ** errptr)"

.SS "void leveldb_destroy_db (const \fBleveldb_options_t\fP * options, const char * name, char ** errptr)"

.SS "void leveldb_env_destroy (\fBleveldb_env_t\fP * env)"

.SS "char * leveldb_env_get_test_directory (\fBleveldb_env_t\fP * env)"

.SS "\fBleveldb_filterpolicy_t\fP * leveldb_filterpolicy_create (void * state, void(* destructor )(void *), char *(* create_filter )(void *, const char *const *key_array, const size_t *key_length_array, int num_keys, size_t *filter_length), uint8_t(* key_may_match )(void *, const char *key, size_t length, const char *filter, size_t filter_length), const char *(* name )(void *))"

.SS "\fBleveldb_filterpolicy_t\fP * leveldb_filterpolicy_create_bloom (int bits_per_key)"

.SS "void leveldb_filterpolicy_destroy (\fBleveldb_filterpolicy_t\fP * filter)"

.SS "void leveldb_free (void * ptr)"

.SS "char * leveldb_get (\fBleveldb_t\fP * db, const \fBleveldb_readoptions_t\fP * options, const char * key, size_t keylen, size_t * vallen, char ** errptr)"

.SS "void leveldb_iter_destroy (\fBleveldb_iterator_t\fP * iter)"

.SS "void leveldb_iter_get_error (const \fBleveldb_iterator_t\fP * iter, char ** errptr)"

.SS "const char * leveldb_iter_key (const \fBleveldb_iterator_t\fP * iter, size_t * klen)"

.SS "void leveldb_iter_next (\fBleveldb_iterator_t\fP * iter)"

.SS "void leveldb_iter_prev (\fBleveldb_iterator_t\fP * iter)"

.SS "void leveldb_iter_seek (\fBleveldb_iterator_t\fP * iter, const char * k, size_t klen)"

.SS "void leveldb_iter_seek_to_first (\fBleveldb_iterator_t\fP * iter)"

.SS "void leveldb_iter_seek_to_last (\fBleveldb_iterator_t\fP * iter)"

.SS "uint8_t leveldb_iter_valid (const \fBleveldb_iterator_t\fP * iter)"

.SS "const char * leveldb_iter_value (const \fBleveldb_iterator_t\fP * iter, size_t * vlen)"

.SS "int leveldb_major_version (void )"

.SS "int leveldb_minor_version (void )"

.SS "\fBleveldb_t\fP * leveldb_open (const \fBleveldb_options_t\fP * options, const char * name, char ** errptr)"

.SS "\fBleveldb_options_t\fP * leveldb_options_create (void )"

.SS "void leveldb_options_destroy (\fBleveldb_options_t\fP * options)"

.SS "void leveldb_options_set_block_restart_interval (\fBleveldb_options_t\fP * opt, int n)"

.SS "void leveldb_options_set_block_size (\fBleveldb_options_t\fP * opt, size_t s)"

.SS "void leveldb_options_set_cache (\fBleveldb_options_t\fP * opt, \fBleveldb_cache_t\fP * c)"

.SS "void leveldb_options_set_comparator (\fBleveldb_options_t\fP * opt, \fBleveldb_comparator_t\fP * cmp)"

.SS "void leveldb_options_set_compression (\fBleveldb_options_t\fP * opt, int t)"

.SS "void leveldb_options_set_create_if_missing (\fBleveldb_options_t\fP * opt, uint8_t v)"

.SS "void leveldb_options_set_env (\fBleveldb_options_t\fP * opt, \fBleveldb_env_t\fP * env)"

.SS "void leveldb_options_set_error_if_exists (\fBleveldb_options_t\fP * opt, uint8_t v)"

.SS "void leveldb_options_set_filter_policy (\fBleveldb_options_t\fP * opt, \fBleveldb_filterpolicy_t\fP * policy)"

.SS "void leveldb_options_set_info_log (\fBleveldb_options_t\fP * opt, \fBleveldb_logger_t\fP * l)"

.SS "void leveldb_options_set_max_file_size (\fBleveldb_options_t\fP * opt, size_t s)"

.SS "void leveldb_options_set_max_open_files (\fBleveldb_options_t\fP * opt, int n)"

.SS "void leveldb_options_set_paranoid_checks (\fBleveldb_options_t\fP * opt, uint8_t v)"

.SS "void leveldb_options_set_write_buffer_size (\fBleveldb_options_t\fP * opt, size_t s)"

.SS "char * leveldb_property_value (\fBleveldb_t\fP * db, const char * propname)"

.SS "void leveldb_put (\fBleveldb_t\fP * db, const \fBleveldb_writeoptions_t\fP * options, const char * key, size_t keylen, const char * val, size_t vallen, char ** errptr)"

.SS "\fBleveldb_readoptions_t\fP * leveldb_readoptions_create (void )"

.SS "void leveldb_readoptions_destroy (\fBleveldb_readoptions_t\fP * opt)"

.SS "void leveldb_readoptions_set_fill_cache (\fBleveldb_readoptions_t\fP * opt, uint8_t v)"

.SS "void leveldb_readoptions_set_snapshot (\fBleveldb_readoptions_t\fP * opt, const \fBleveldb_snapshot_t\fP * snap)"

.SS "void leveldb_readoptions_set_verify_checksums (\fBleveldb_readoptions_t\fP * opt, uint8_t v)"

.SS "void leveldb_release_snapshot (\fBleveldb_t\fP * db, const \fBleveldb_snapshot_t\fP * snapshot)"

.SS "void leveldb_repair_db (const \fBleveldb_options_t\fP * options, const char * name, char ** errptr)"

.SS "void leveldb_write (\fBleveldb_t\fP * db, const \fBleveldb_writeoptions_t\fP * options, \fBleveldb_writebatch_t\fP * batch, char ** errptr)"

.SS "void leveldb_writebatch_append (\fBleveldb_writebatch_t\fP * destination, const \fBleveldb_writebatch_t\fP * source)"

.SS "void leveldb_writebatch_clear (\fBleveldb_writebatch_t\fP * b)"

.SS "\fBleveldb_writebatch_t\fP * leveldb_writebatch_create (void )"

.SS "void leveldb_writebatch_delete (\fBleveldb_writebatch_t\fP * b, const char * key, size_t klen)"

.SS "void leveldb_writebatch_destroy (\fBleveldb_writebatch_t\fP * b)"

.SS "void leveldb_writebatch_iterate (const \fBleveldb_writebatch_t\fP * b, void * state, void(* put )(void *, const char *k, size_t klen, const char *v, size_t vlen), void(* deleted )(void *, const char *k, size_t klen))"

.SS "void leveldb_writebatch_put (\fBleveldb_writebatch_t\fP * b, const char * key, size_t klen, const char * val, size_t vlen)"

.SS "\fBleveldb_writeoptions_t\fP * leveldb_writeoptions_create (void )"

.SS "void leveldb_writeoptions_destroy (\fBleveldb_writeoptions_t\fP * opt)"

.SS "void leveldb_writeoptions_set_sync (\fBleveldb_writeoptions_t\fP * opt, uint8_t v)"

.SS "const \fBFilterPolicy\fP * NewBloomFilterPolicy (int bits_per_key)"

.SS "\fBCache\fP * NewLRUCache (size_t capacity)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
