.TH "src/init Directory Reference" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/init Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbitcoin\-gui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbitcoin\-node\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbitcoin\-qt\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbitcoin\-wallet\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbitcoind\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcommon\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcommon\&.h\fP"
.br
.RI "Common init functions shared by bitcoin-node, bitcoin-wallet, etc\&. "
.in -1c
