.TH "src/crc32c/src Directory Reference" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crc32c/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcrc32c\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_arm64\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_arm64\&.h\fP"
.br
.ti -1c
.RI "file \fBcrc32c_arm64_check\&.h\fP"
.br
.ti -1c
.RI "file \fBcrc32c_arm64_unittest\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_benchmark\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_capi_unittest\&.c\fP"
.br
.ti -1c
.RI "file \fBcrc32c_extend_unittests\&.h\fP"
.br
.ti -1c
.RI "file \fBcrc32c_internal\&.h\fP"
.br
.ti -1c
.RI "file \fBcrc32c_portable\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_portable_unittest\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_prefetch\&.h\fP"
.br
.ti -1c
.RI "file \fBcrc32c_prefetch_unittest\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_read_le\&.h\fP"
.br
.ti -1c
.RI "file \fBcrc32c_read_le_unittest\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_round_up\&.h\fP"
.br
.ti -1c
.RI "file \fBcrc32c_round_up_unittest\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_sse42\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_sse42\&.h\fP"
.br
.ti -1c
.RI "file \fBcrc32c_sse42_check\&.h\fP"
.br
.ti -1c
.RI "file \fBcrc32c_sse42_unittest\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_test_main\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32c_unittest\&.cc\fP"
.br
.in -1c
