.TH "src/test/util Directory Reference" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/util Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBblockfilter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBblockfilter\&.h\fP"
.br
.ti -1c
.RI "file \fBchainstate\&.h\fP"
.br
.ti -1c
.RI "file \fBcluster_linearize\&.h\fP"
.br
.ti -1c
.RI "file \fBcoins\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcoins\&.h\fP"
.br
.ti -1c
.RI "file \fBcoverage\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcoverage\&.h\fP"
.br
.ti -1c
.RI "file \fBjson\&.cpp\fP"
.br
.ti -1c
.RI "file \fBjson\&.h\fP"
.br
.ti -1c
.RI "file \fBlogging\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogging\&.h\fP"
.br
.ti -1c
.RI "file \fBmining\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmining\&.h\fP"
.br
.ti -1c
.RI "file \fBnet\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnet\&.h\fP"
.br
.ti -1c
.RI "file \fBpoolresourcetester\&.h\fP"
.br
.ti -1c
.RI "file \fBrandom\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrandom\&.h\fP"
.br
.ti -1c
.RI "file \fBscript\&.cpp\fP"
.br
.ti -1c
.RI "file \fBscript\&.h\fP"
.br
.ti -1c
.RI "file \fBsetup_common\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsetup_common\&.h\fP"
.br
.ti -1c
.RI "file \fBstr\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstr\&.h\fP"
.br
.ti -1c
.RI "file \fBtime\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtime\&.h\fP"
.br
.ti -1c
.RI "file \fBtransaction_utils\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtransaction_utils\&.h\fP"
.br
.ti -1c
.RI "file \fBtxmempool\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtxmempool\&.h\fP"
.br
.ti -1c
.RI "file \fBvalidation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvalidation\&.h\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Test library"
.PP
This contains files for the test library, which is used by the test binaries (unit tests, benchmarks, fuzzers, gui tests)\&.

.PP
Generally, the files in this folder should be well-separated modules\&. New code should be added to existing modules or (when in doubt) a new module should be created\&.

.PP
The utilities in here are compiled into a library, which does not hold any state\&. However, the main file \fRsetup_common\fP defines the common test setup for all test binaries\&. The test binaries will handle the global state when they instantiate the \fR\fBBasicTestingSetup\fP\fP (or one of its derived classes)\&. 
