.TH "src/interfaces Directory Reference" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/interfaces Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBchain\&.h\fP"
.br
.ti -1c
.RI "file \fBecho\&.h\fP"
.br
.ti -1c
.RI "file \fBhandler\&.h\fP"
.br
.ti -1c
.RI "file \fBinit\&.h\fP"
.br
.ti -1c
.RI "file \fBipc\&.h\fP"
.br
.ti -1c
.RI "file \fBmining\&.h\fP"
.br
.ti -1c
.RI "file \fBnode\&.h\fP"
.br
.ti -1c
.RI "file \fBtypes\&.h\fP"
.br
.ti -1c
.RI "file \fBwallet\&.h\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Internal c++ interfaces"
.PP
The following interfaces are defined here:

.PP
.IP "\(bu" 2
\fR\fRChain\fP\fP — used by wallet to access blockchain and mempool state\&. Added in \fR#14437\fP, \fR#14711\fP, \fR#15288\fP, and \fR#10973\fP\&.
.IP "\(bu" 2
\fR\fRChainClient\fP\fP — used by node to start & stop \fR\fBChain\fP\fP clients\&. Added in \fR#14437\fP\&.
.IP "\(bu" 2
\fR\fRNode\fP\fP — used by GUI to start & stop bitcoin node\&. Added in \fR#10244\fP\&.
.IP "\(bu" 2
\fR\fRWallet\fP\fP — used by GUI to access wallets\&. Added in \fR#10244\fP\&.
.IP "\(bu" 2
\fR\fRHandler\fP\fP — returned by \fRhandleEvent\fP methods on interfaces above and used to manage lifetimes of event handlers\&.
.IP "\(bu" 2
\fR\fRInit\fP\fP — used by multiprocess code to access interfaces above on startup\&. Added in \fR#19160\fP\&.
.IP "\(bu" 2
\fR\fRIpc\fP\fP — used by multiprocess code to access \fR\fBInit\fP\fP interface across processes\&. Added in \fR#19160\fP\&.
.PP

.PP
The interfaces above define boundaries between major components of bitcoin code (node, wallet, and gui), making it possible for them to run in \fBdifferent processes\fP, and be tested, developed, and understood independently\&. These interfaces are not currently designed to be stable or to be used externally\&. 
