.TH "src/kernel Directory Reference" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kernel Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbitcoinkernel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbitcoinkernel\&.h\fP"
.br
.ti -1c
.RI "file \fBbitcoinkernel_wrapper\&.h\fP"
.br
.ti -1c
.RI "file \fBblockmanager_opts\&.h\fP"
.br
.ti -1c
.RI "file \fBcaches\&.h\fP"
.br
.ti -1c
.RI "file \fBchain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBchain\&.h\fP"
.br
.ti -1c
.RI "file \fBchainparams\&.cpp\fP"
.br
.ti -1c
.RI "file \fBchainparams\&.h\fP"
.br
.ti -1c
.RI "file \fBchainstatemanager_opts\&.h\fP"
.br
.ti -1c
.RI "file \fBchecks\&.cpp\fP"
.br
.ti -1c
.RI "file \fBchecks\&.h\fP"
.br
.ti -1c
.RI "file \fBcoinstats\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcoinstats\&.h\fP"
.br
.ti -1c
.RI "file \fBcontext\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcontext\&.h\fP"
.br
.ti -1c
.RI "file \fBcs_main\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcs_main\&.h\fP"
.br
.ti -1c
.RI "file \fBdisconnected_transactions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdisconnected_transactions\&.h\fP"
.br
.ti -1c
.RI "file \fBmempool_entry\&.h\fP"
.br
.ti -1c
.RI "file \fBmempool_limits\&.h\fP"
.br
.ti -1c
.RI "file \fBmempool_options\&.h\fP"
.br
.ti -1c
.RI "file \fBmempool_removal_reason\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmempool_removal_reason\&.h\fP"
.br
.ti -1c
.RI "file \fBmessagestartchars\&.h\fP"
.br
.ti -1c
.RI "file \fBnotifications_interface\&.h\fP"
.br
.ti -1c
.RI "file \fBtypes\&.h\fP"
.br
.ti -1c
.RI "file \fBwarning\&.h\fP"
.br
.in -1c
