.TH "src/test/data Directory Reference" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/data Directory Reference
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This directory contains data-driven tests for various aspects of Bitcoin\&.
.SH "License"
.PP
The data files in this directory are distributed under the MIT software license, see the accompanying file COPYING or https://www.opensource.org/licenses/mit-license.php\&. 
