.TH "src/ipc/libmultiprocess/ci Directory Reference" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc/libmultiprocess/ci Directory Reference
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "CI quick-reference"
.PP
All CI is just bash and nix\&.

.PP
.IP "\(bu" 2
\fBWorkflow\fP:
.IP "  \(bu" 4
\fR\&.github/workflows/ci\&.yml\fP – lists the jobs (\fRdefault\fP, \fRllvm\fP, …)\&.
.PP

.IP "\(bu" 2
\fBScripts\fP:
.IP "  \(bu" 4
\fRci/scripts/run\&.sh\fP – spins up the Nix shell then calls…
.IP "  \(bu" 4
\fRci/scripts/ci\&.sh\fP – …to configure, build, and test\&.
.PP

.IP "\(bu" 2
\fBConfiguration\fP:
.IP "  \(bu" 4
\fRci/configs/*\&.sh\fP – defines flags for each job\&.
.IP "  \(bu" 4
\fRshell\&.nix\fP – defines build environment (compilers, tools, libraries)\&.
.PP

.IP "\(bu" 2
\fBBuild directories\fP:
.IP "  \(bu" 4
\fRbuild-*/\fP – separate build directories (like \fRbuild-default\fP, \fRbuild-llvm\fP) will be created for each job\&.
.PP

.PP

.PP
To run jobs locally:

.PP
.PP
.nf
CI_CONFIG=ci/configs/default\&.bash  ci/scripts/run\&.sh
CI_CONFIG=ci/configs/llvm\&.bash     ci/scripts/run\&.sh
CI_CONFIG=ci/configs/gnu32\&.bash    ci/scripts/run\&.sh
CI_CONFIG=ci/configs/sanitize\&.bash ci/scripts/run\&.sh
CI_CONFIG=ci/configs/olddeps\&.bash  ci/scripts/run\&.sh
.fi
.PP

.PP
By default CI jobs will reuse their build directories\&. \fRCI_CLEAN=1\fP can be specified to delete them before running instead\&. 
