.TH "src/ipc Directory Reference" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcapnp\fP"
.br
.ti -1c
.RI "directory \fBlibmultiprocess\fP"
.br
.ti -1c
.RI "directory \fBtest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcontext\&.h\fP"
.br
.ti -1c
.RI "file \fBexception\&.h\fP"
.br
.ti -1c
.RI "file \fBinterfaces\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprocess\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprocess\&.h\fP"
.br
.ti -1c
.RI "file \fBprotocol\&.h\fP"
.br
.in -1c
