.TH "src/support/allocators Directory Reference" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/support/allocators Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpool\&.h\fP"
.br
.ti -1c
.RI "file \fBsecure\&.h\fP"
.br
.ti -1c
.RI "file \fBzeroafterfree\&.h\fP"
.br
.in -1c
