.TH "src/leveldb/util/cache_test.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/util/cache_test.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'leveldb/cache\&.h'\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'util/coding\&.h'\fP
.br
\fR#include 'util/testharness\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCacheTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBCacheTest\fP, HitAndMiss)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCacheTest\fP, Erase)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCacheTest\fP, EntriesArePinned)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCacheTest\fP, EvictionPolicy)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCacheTest\fP, UseExceedsCacheSize)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCacheTest\fP, HeavyEntries)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCacheTest\fP, NewId)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCacheTest\fP, Prune)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCacheTest\fP, ZeroSizeCache)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
