.TH "src/leveldb/include/leveldb/cache.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/include/leveldb/cache.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include 'leveldb/export\&.h'\fP
.br
\fR#include 'leveldb/slice\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCache\fP"
.br
.ti -1c
.RI "struct \fBCache::Handle\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLEVELDB_EXPORT\fP \fBCache\fP * \fBNewLRUCache\fP (size_t capacity)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class \fBLEVELDB_EXPORT\fP \fBCache\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
