.TH "CachingTransactionSignatureChecker" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachingTransactionSignatureChecker
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sigcache\&.h>\fP
.PP
Inherits \fBGenericTransactionSignatureChecker< CTransaction >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCachingTransactionSignatureChecker\fP (const \fBCTransaction\fP *txToIn, unsigned int nInIn, const \fBCAmount\fP &amountIn, bool storeIn, \fBSignatureCache\fP &signature_cache, \fBPrecomputedTransactionData\fP &txdataIn)"
.br
.ti -1c
.RI "bool \fBVerifyECDSASignature\fP (const std::vector< unsigned char > &vchSig, const \fBCPubKey\fP &vchPubKey, const \fBuint256\fP &sighash) const override"
.br
.ti -1c
.RI "bool \fBVerifySchnorrSignature\fP (std::span< const unsigned char > sig, const \fBXOnlyPubKey\fP &pubkey, const \fBuint256\fP &sighash) const override"
.br
.in -1c

Public Member Functions inherited from \fBGenericTransactionSignatureChecker< CTransaction >\fP
.in +1c
.ti -1c
.RI "\fBGenericTransactionSignatureChecker\fP (const \fBCTransaction\fP *txToIn, unsigned int nInIn, const \fBCAmount\fP &amountIn, \fBMissingDataBehavior\fP mdb)"
.br
.ti -1c
.RI "\fBGenericTransactionSignatureChecker\fP (const \fBCTransaction\fP *txToIn, unsigned int nInIn, const \fBCAmount\fP &amountIn, const \fBPrecomputedTransactionData\fP &txdataIn, \fBMissingDataBehavior\fP mdb)"
.br
.ti -1c
.RI "bool \fBCheckECDSASignature\fP (const std::vector< unsigned char > &scriptSig, const std::vector< unsigned char > &vchPubKey, const \fBCScript\fP &scriptCode, \fBSigVersion\fP sigversion) const override"
.br
.ti -1c
.RI "bool \fBCheckSchnorrSignature\fP (std::span< const unsigned char > sig, std::span< const unsigned char > pubkey, \fBSigVersion\fP sigversion, \fBScriptExecutionData\fP &execdata, \fBScriptError\fP *serror=nullptr) const override"
.br
.ti -1c
.RI "bool \fBCheckLockTime\fP (const \fBCScriptNum\fP &nLockTime) const override"
.br
.ti -1c
.RI "bool \fBCheckSequence\fP (const \fBCScriptNum\fP &nSequence) const override"
.br
.in -1c

Public Member Functions inherited from \fBBaseSignatureChecker\fP
.in +1c
.ti -1c
.RI "virtual \fB~BaseSignatureChecker\fP ()=default"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCachingTransactionSignatureChecker\fP (const \fBCTransaction\fP * txToIn, unsigned int nInIn, const \fBCAmount\fP & amountIn, bool storeIn, \fBSignatureCache\fP & signature_cache, \fBPrecomputedTransactionData\fP & txdataIn)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool VerifyECDSASignature (const std::vector< unsigned char > & vchSig, const \fBCPubKey\fP & vchPubKey, const \fBuint256\fP & sighash) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBGenericTransactionSignatureChecker< CTransaction >\fP\&.
.SS "bool VerifySchnorrSignature (std::span< const unsigned char > sig, const \fBXOnlyPubKey\fP & pubkey, const \fBuint256\fP & sighash) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBGenericTransactionSignatureChecker< CTransaction >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
