.TH "src/test/caches_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/caches_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/caches\&.h>\fP
.br
\fR#include <util/byte_units\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (oversized_dbcache_warning)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (oversized_dbcache_warning )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
