.TH "CAddress" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAddress
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <protocol\&.h>\fP
.PP
Inherits \fBCService\fP\&.
.PP
Inherited by \fBAddrInfo\fP\&.
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSerParams\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBFormat\fP { \fBDisk\fP, \fBNetwork\fP }"
.br
.in -1c

Public Types inherited from \fBCNetAddr\fP
.in +1c
.ti -1c
.RI "enum class \fBEncoding\fP { \fBV1\fP, \fBV2\fP }"
.br
.ti -1c
.RI "enum \fBBIP155Network\fP : uint8_t { \fBIPV4\fP = 1, \fBIPV6\fP = 2, \fBTORV2\fP = 3, \fBTORV3\fP = 4, \fBI2P\fP = 5, \fBCJDNS\fP = 6 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCAddress\fP ()"
.br
.ti -1c
.RI "\fBCAddress\fP (\fBCService\fP ipIn, \fBServiceFlags\fP nServicesIn)"
.br
.ti -1c
.RI "\fBCAddress\fP (\fBCService\fP ipIn, \fBServiceFlags\fP nServicesIn, \fBNodeSeconds\fP time)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCAddress\fP, obj)"
.br
.in -1c

Public Member Functions inherited from \fBCService\fP
.in +1c
.ti -1c
.RI "\fBCService\fP ()"
.br
.ti -1c
.RI "\fBCService\fP (const \fBCNetAddr\fP &ip, uint16_t \fBport\fP)"
.br
.ti -1c
.RI "\fBCService\fP (const struct in_addr &ipv4Addr, uint16_t \fBport\fP)"
.br
.ti -1c
.RI "\fBCService\fP (const struct sockaddr_in &addr)"
.br
.ti -1c
.RI "uint16_t \fBGetPort\fP () const"
.br
.ti -1c
.RI "bool \fBGetSockAddr\fP (struct sockaddr *paddr, socklen_t *addrlen) const"
.br
.ti -1c
.RI "bool \fBSetSockAddr\fP (const struct sockaddr *paddr, socklen_t addrlen)"
.br
.ti -1c
.RI "sa_family_t \fBGetSAFamily\fP () const"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBGetKey\fP () const"
.br
.ti -1c
.RI "std::string \fBToStringAddrPort\fP () const"
.br
.ti -1c
.RI "\fBCService\fP (const struct in6_addr &ipv6Addr, uint16_t \fBport\fP)"
.br
.ti -1c
.RI "\fBCService\fP (const struct sockaddr_in6 &addr)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCService\fP, obj)"
.br
.in -1c

Public Member Functions inherited from \fBCNetAddr\fP
.in +1c
.ti -1c
.RI "\fBCNetAddr\fP ()"
.br
.ti -1c
.RI "\fBCNetAddr\fP (const struct in_addr &ipv4Addr)"
.br
.ti -1c
.RI "void \fBSetIP\fP (const \fBCNetAddr\fP &ip)"
.br
.ti -1c
.RI "void \fBSetLegacyIPv6\fP (std::span< const uint8_t > ipv6)"
.br
.ti -1c
.RI "bool \fBSetInternal\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "bool \fBSetSpecial\fP (std::string_view addr)"
.br
.ti -1c
.RI "bool \fBIsBindAny\fP () const"
.br
.ti -1c
.RI "bool \fBIsIPv4\fP () const"
.br
.ti -1c
.RI "bool \fBIsIPv6\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC1918\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC2544\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC6598\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC5737\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC3849\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC3927\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC3964\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC4193\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC4380\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC4843\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC7343\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC4862\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC6052\fP () const"
.br
.ti -1c
.RI "bool \fBIsRFC6145\fP () const"
.br
.ti -1c
.RI "bool \fBIsHeNet\fP () const"
.br
.ti -1c
.RI "bool \fBIsTor\fP () const"
.br
.ti -1c
.RI "bool \fBIsI2P\fP () const"
.br
.ti -1c
.RI "bool \fBIsCJDNS\fP () const"
.br
.ti -1c
.RI "bool \fBHasCJDNSPrefix\fP () const"
.br
.ti -1c
.RI "bool \fBIsLocal\fP () const"
.br
.ti -1c
.RI "bool \fBIsRoutable\fP () const"
.br
.ti -1c
.RI "bool \fBIsInternal\fP () const"
.br
.ti -1c
.RI "bool \fBIsValid\fP () const"
.br
.ti -1c
.RI "bool \fBIsPrivacyNet\fP () const"
.br
.ti -1c
.RI "bool \fBIsAddrV1Compatible\fP () const"
.br
.ti -1c
.RI "enum \fBNetwork\fP \fBGetNetwork\fP () const"
.br
.ti -1c
.RI "std::string \fBToStringAddr\fP () const"
.br
.ti -1c
.RI "bool \fBGetInAddr\fP (struct in_addr *pipv4Addr) const"
.br
.ti -1c
.RI "\fBNetwork\fP \fBGetNetClass\fP () const"
.br
.ti -1c
.RI "uint32_t \fBGetLinkedIPv4\fP () const"
.br
.RI "For IPv4, mapped IPv4, SIIT translated IPv4, Teredo, 6to4 tunneled addresses, return the relevant IPv4 address as a uint32\&. "
.ti -1c
.RI "bool \fBHasLinkedIPv4\fP () const"
.br
.RI "Whether this address has a linked IPv4 address (see \fBGetLinkedIPv4()\fP)\&. "
.ti -1c
.RI "std::vector< unsigned char > \fBGetAddrBytes\fP () const"
.br
.ti -1c
.RI "int \fBGetReachabilityFrom\fP (const \fBCNetAddr\fP &paddrPartner) const"
.br
.ti -1c
.RI "\fBCNetAddr\fP (const struct in6_addr &pipv6Addr, const uint32_t scope=0)"
.br
.ti -1c
.RI "bool \fBGetIn6Addr\fP (struct in6_addr *pipv6Addr) const"
.br
.ti -1c
.RI "bool \fBIsRelayable\fP () const"
.br
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBNodeSeconds\fP \fBnTime\fP {TIME_INIT}"
.br
.RI "Always included in serialization\&. The behavior is unspecified if the value is not representable as uint32_t\&. "
.ti -1c
.RI "\fBServiceFlags\fP \fBnServices\fP {\fBNODE_NONE\fP}"
.br
.RI "Serialized as uint64_t in V1, and as CompactSize in V2\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV1_NETWORK\fP {{\fBCNetAddr::Encoding::V1\fP}, \fBFormat::Network\fP}"
.br
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV2_NETWORK\fP {{\fBCNetAddr::Encoding::V2\fP}, \fBFormat::Network\fP}"
.br
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV1_DISK\fP {{\fBCNetAddr::Encoding::V1\fP}, \fBFormat::Disk\fP}"
.br
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV2_DISK\fP {{\fBCNetAddr::Encoding::V2\fP}, \fBFormat::Disk\fP}"
.br
.in -1c

Static Public Attributes inherited from \fBCNetAddr\fP
.in +1c
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV1\fP {\fBEncoding::V1\fP}"
.br
.ti -1c
.RI "static constexpr \fBSerParams\fP \fBV2\fP {\fBEncoding::V2\fP}"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCAddress\fP &a, const \fBCAddress\fP &b)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBCService\fP
.in +1c
.ti -1c
.RI "uint16_t \fBport\fP"
.br
.in -1c

Protected Attributes inherited from \fBCNetAddr\fP
.in +1c
.ti -1c
.RI "\fBprevector\fP< ADDR_IPV6_SIZE, uint8_t > \fBm_addr\fP {ADDR_IPV6_SIZE, 0x0}"
.br
.ti -1c
.RI "\fBNetwork\fP \fBm_net\fP {\fBNET_IPV6\fP}"
.br
.ti -1c
.RI "uint32_t \fBm_scope_id\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBCService\fP with information about it as peer 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBFormat\fP\fBFormat\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIDisk \fP
.TP
\f(BINetwork \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCAddress\fP ()\fR [inline]\fP"

.SS "\fBCAddress\fP (\fBCService\fP ipIn, \fBServiceFlags\fP nServicesIn)\fR [inline]\fP"

.SS "\fBCAddress\fP (\fBCService\fP ipIn, \fBServiceFlags\fP nServicesIn, \fBNodeSeconds\fP time)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "SERIALIZE_METHODS (\fBCAddress\fP , obj )\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "bool operator== (const \fBCAddress\fP & a, const \fBCAddress\fP & b)\fR [friend]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBServiceFlags\fP nServices {\fBNODE_NONE\fP}"

.PP
Serialized as uint64_t in V1, and as CompactSize in V2\&. 
.SS "\fBNodeSeconds\fP nTime {TIME_INIT}"

.PP
Always included in serialization\&. The behavior is unspecified if the value is not representable as uint32_t\&. 
.SS "\fBSerParams\fP V1_DISK {{\fBCNetAddr::Encoding::V1\fP}, \fBFormat::Disk\fP}\fR [static]\fP, \fR [constexpr]\fP"

.SS "\fBSerParams\fP V1_NETWORK {{\fBCNetAddr::Encoding::V1\fP}, \fBFormat::Network\fP}\fR [static]\fP, \fR [constexpr]\fP"

.SS "\fBSerParams\fP V2_DISK {{\fBCNetAddr::Encoding::V2\fP}, \fBFormat::Disk\fP}\fR [static]\fP, \fR [constexpr]\fP"

.SS "\fBSerParams\fP V2_NETWORK {{\fBCNetAddr::Encoding::V2\fP}, \fBFormat::Network\fP}\fR [static]\fP, \fR [constexpr]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
