.TH "CAddress::SerParams" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAddress::SerParams
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <protocol\&.h>\fP
.PP
Inherits \fBCNetAddr::SerParams\fP\&.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBFormat\fP\fBFormat\fP \fBfmt\fP"
.br
.in -1c

Data Fields inherited from \fBCNetAddr::SerParams\fP
.in +1c
.ti -1c
.RI "const \fBEncoding\fP \fBenc\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const \fBFormat\fP\fBFormat\fP fmt"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
