.TH "Calculator" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calculator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <calculator\&.h>\fP
.PP
Inherited by \fBCalculatorImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Calculator\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBsolveEquation\fP (const std::string &eqn)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBCalculator\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void solveEquation (const std::string & eqn)\fR [pure virtual]\fP"

.PP
Implemented in \fBCalculatorImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
