.TH "CAppNapInhibitor::CAppNapImpl" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAppNapInhibitor::CAppNapImpl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~CAppNapImpl\fP ()"
.br
.ti -1c
.RI "void \fBdisableAppNap\fP ()"
.br
.ti -1c
.RI "void \fBenableAppNap\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "~\fBCAppNapImpl\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void disableAppNap ()\fR [inline]\fP"

.SS "void enableAppNap ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
