.TH "CBitcoinLevelDBLogger" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBitcoinLevelDBLogger
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLogger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLogv\fP (const char *format, va_list ap) override"
.br
.in -1c

Public Member Functions inherited from \fBLogger\fP
.in +1c
.ti -1c
.RI "\fBLogger\fP ()=default"
.br
.ti -1c
.RI "\fBLogger\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "\fBLogger\fP & \fBoperator=\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "virtual \fB~Logger\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Logv (const char * format, va_list ap)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBLogger\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
