.TH "CBlockIndex" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBlockIndex
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <chain\&.h>\fP
.PP
Inherited by \fBCDiskBlockIndex\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int nFile \fBGUARDED_BY\fP (\fB::cs_main\fP)"
.br
.RI "Which # file this block is stored in (blk?????\&.dat)\&. "
.ti -1c
.RI "unsigned int nDataPos \fBGUARDED_BY\fP (\fB::cs_main\fP)"
.br
.RI "Byte offset within blk?????\&.dat where this block's data is stored\&. "
.ti -1c
.RI "unsigned int nUndoPos \fBGUARDED_BY\fP (\fB::cs_main\fP)"
.br
.RI "Byte offset within rev?????\&.dat where this block's undo data is stored\&. "
.ti -1c
.RI "uint32_t nStatus \fBGUARDED_BY\fP (\fB::cs_main\fP)"
.br
.ti -1c
.RI "\fBCBlockIndex\fP (const \fBCBlockHeader\fP &block)"
.br
.ti -1c
.RI "\fBFlatFilePos\fP \fBGetBlockPos\fP () const \fBEXCLUSIVE_LOCKS_REQUIRED\fP("
.br
.ti -1c
.RI "\fBFlatFilePos\fP \fBGetUndoPos\fP () const \fBEXCLUSIVE_LOCKS_REQUIRED\fP("
.br
.ti -1c
.RI "\fBCBlockHeader\fP \fBGetBlockHeader\fP () const"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetBlockHash\fP () const"
.br
.ti -1c
.RI "bool \fBHaveNumChainTxs\fP () const"
.br
.ti -1c
.RI "\fBNodeSeconds\fP \fBTime\fP () const"
.br
.ti -1c
.RI "int64_t \fBGetBlockTime\fP () const"
.br
.ti -1c
.RI "int64_t \fBGetBlockTimeMax\fP () const"
.br
.ti -1c
.RI "int64_t \fBGetMedianTimePast\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "bool \fBIsValid\fP (enum \fBBlockStatus\fP nUpTo) const \fBEXCLUSIVE_LOCKS_REQUIRED\fP("
.br
.RI "Check whether this block index entry is valid up to the passed validity level\&. "
.ti -1c
.RI "bool \fBRaiseValidity\fP (enum \fBBlockStatus\fP nUpTo) \fBEXCLUSIVE_LOCKS_REQUIRED\fP("
.br
.ti -1c
.RI "void \fBBuildSkip\fP ()"
.br
.RI "Build the skiplist pointer for this entry\&. "
.ti -1c
.RI "\fBCBlockIndex\fP * \fBGetAncestor\fP (int height)"
.br
.RI "Efficiently find an ancestor of this block\&. "
.ti -1c
.RI "const \fBCBlockIndex\fP * \fBGetAncestor\fP (int height) const"
.br
.ti -1c
.RI "\fBCBlockIndex\fP ()=default"
.br
.ti -1c
.RI "\fB~CBlockIndex\fP ()=default"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBuint256\fP * \fBphashBlock\fP {nullptr}"
.br
.RI "pointer to the hash of the block, if any\&. Memory is owned by this \fBCBlockIndex\fP "
.ti -1c
.RI "\fBCBlockIndex\fP * \fBpprev\fP {nullptr}"
.br
.RI "pointer to the index of the predecessor of this block "
.ti -1c
.RI "\fBCBlockIndex\fP * \fBpskip\fP {nullptr}"
.br
.RI "pointer to the index of some further predecessor of this block "
.ti -1c
.RI "int \fBnHeight\fP {0}"
.br
.RI "height of the entry in the chain\&. The genesis block has height 0 "
.ti -1c
.RI "\fBarith_uint256\fP \fBnChainWork\fP {}"
.br
.RI "(memory only) Total amount of work (expected number of hashes) in the chain up to and including this block "
.ti -1c
.RI "unsigned int \fBnTx\fP {0}"
.br
.ti -1c
.RI "uint64_t \fBm_chain_tx_count\fP {0}"
.br
.ti -1c
.RI "int32_t \fBnVersion\fP {0}"
.br
.RI "block header "
.ti -1c
.RI "\fBuint256\fP \fBhashMerkleRoot\fP {}"
.br
.ti -1c
.RI "uint32_t \fBnTime\fP {0}"
.br
.ti -1c
.RI "uint32_t \fBnBits\fP {0}"
.br
.ti -1c
.RI "uint32_t \fBnNonce\fP {0}"
.br
.ti -1c
.RI "int32_t \fBnSequenceId\fP {SEQ_ID_INIT_FROM_DISK}"
.br
.ti -1c
.RI "unsigned int \fBnTimeMax\fP {0}"
.br
.RI "(memory only) Maximum nTime in the chain up to and including this block\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBnMedianTimeSpan\fP = 11"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCBlockIndex\fP (const \fBCBlockIndex\fP &)=default"
.br
.ti -1c
.RI "\fBCBlockIndex\fP & \fBoperator=\fP (const \fBCBlockIndex\fP &)=delete"
.br
.ti -1c
.RI "\fBCBlockIndex\fP (\fBCBlockIndex\fP &&)=delete"
.br
.ti -1c
.RI "\fBCBlockIndex\fP & \fBoperator=\fP (\fBCBlockIndex\fP &&)=delete"
.br
.in -1c
.SH "Detailed Description"
.PP 
The block chain is a tree shaped structure starting with the genesis block at the root, with each block potentially having multiple candidates to be the next block\&. A blockindex may have multiple pprev pointing to it, but at most one of them can be part of the currently active branch\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCBlockIndex\fP (const \fBCBlockHeader\fP & block)\fR [inline]\fP, \fR [explicit]\fP"

.SS "\fBCBlockIndex\fP ()\fR [default]\fP"

.SS "~\fBCBlockIndex\fP ()\fR [default]\fP"

.SS "\fBCBlockIndex\fP (const \fBCBlockIndex\fP & )\fR [protected]\fP, \fR [default]\fP"
\fBCBlockIndex\fP should not allow public copy construction because equality comparison via pointer is very common throughout the codebase, making use of copy a footgun\&. Also, use of copies do not have the benefit of simplifying lifetime considerations due to attributes like pprev and pskip, which are at risk of becoming dangling pointers in a copied instance\&.

.PP
We declare these protected instead of simply deleting them so that \fBCDiskBlockIndex\fP can reuse copy construction\&. 
.SS "\fBCBlockIndex\fP (\fBCBlockIndex\fP && )\fR [protected]\fP, \fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void BuildSkip ()"

.PP
Build the skiplist pointer for this entry\&. 
.SS "\fBCBlockIndex\fP * GetAncestor (int height)"

.PP
Efficiently find an ancestor of this block\&. 
.SS "const \fBCBlockIndex\fP * GetAncestor (int height) const"

.SS "\fBuint256\fP GetBlockHash () const\fR [inline]\fP"

.SS "\fBCBlockHeader\fP GetBlockHeader () const\fR [inline]\fP"

.SS "\fBFlatFilePos\fP GetBlockPos () const\fR [inline]\fP"

.SS "int64_t GetBlockTime () const\fR [inline]\fP"

.SS "int64_t GetBlockTimeMax () const\fR [inline]\fP"

.SS "int64_t GetMedianTimePast () const\fR [inline]\fP"

.SS "\fBFlatFilePos\fP GetUndoPos () const\fR [inline]\fP"

.SS "uint32_t nStatus GUARDED_BY (\fB::cs_main\fP )\fR [inline]\fP"
Verification status of this block\&. See enum \fBBlockStatus\fP

.PP
Note: this value is modified to show BLOCK_OPT_WITNESS during UTXO snapshot load to avoid a spurious startup failure requiring -reindex\&. 
.PP
\fBSee also\fP
.RS 4
NeedsRedownload 

.PP
ActivateSnapshot 
.RE
.PP

.SS "unsigned int nUndoPos GUARDED_BY (\fB::cs_main\fP )\fR [inline]\fP"

.PP
Byte offset within rev?????\&.dat where this block's undo data is stored\&. 
.SS "unsigned int nDataPos GUARDED_BY (\fB::cs_main\fP )\fR [inline]\fP"

.PP
Byte offset within blk?????\&.dat where this block's data is stored\&. 
.SS "int nFile GUARDED_BY (\fB::cs_main\fP )\fR [inline]\fP"

.PP
Which # file this block is stored in (blk?????\&.dat)\&. 
.SS "bool HaveNumChainTxs () const\fR [inline]\fP"
Check whether this block and all previous blocks back to the genesis block or an assumeutxo snapshot block have reached VALID_TRANSACTIONS and had transactions downloaded (and stored to disk) at some point\&.

.PP
Does not imply the transactions are consensus-valid (ConnectTip might fail) Does not imply the transactions are still stored on disk\&. (IsBlockPruned might return true)

.PP
Note that this will be true for the snapshot base block, if one is loaded, since its m_chain_tx_count value will have been set manually based on the related \fBAssumeutxoData\fP entry\&. 
.SS "bool IsValid (enum \fBBlockStatus\fP nUpTo) const\fR [inline]\fP"

.PP
Check whether this block index entry is valid up to the passed validity level\&. 
.SS "\fBCBlockIndex\fP & operator= (\fBCBlockIndex\fP && )\fR [protected]\fP, \fR [delete]\fP"

.SS "\fBCBlockIndex\fP & operator= (const \fBCBlockIndex\fP & )\fR [protected]\fP, \fR [delete]\fP"

.SS "bool RaiseValidity (enum \fBBlockStatus\fP nUpTo)\fR [inline]\fP"
Raise the validity level of this block index entry\&. Returns true if the validity was changed\&. 
.SS "\fBNodeSeconds\fP Time () const\fR [inline]\fP"

.SS "std::string ToString () const"

.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP hashMerkleRoot {}"

.SS "uint64_t m_chain_tx_count {0}"
(memory only) Number of transactions in the chain up to and including this block\&. This value will be non-zero if this block and all previous blocks back to the genesis block or an assumeutxo snapshot block have reached the VALID_TRANSACTIONS level\&. 
.SS "uint32_t nBits {0}"

.SS "\fBarith_uint256\fP nChainWork {}"

.PP
(memory only) Total amount of work (expected number of hashes) in the chain up to and including this block 
.SS "int nHeight {0}"

.PP
height of the entry in the chain\&. The genesis block has height 0 
.SS "int nMedianTimeSpan = 11\fR [static]\fP, \fR [constexpr]\fP"

.SS "uint32_t nNonce {0}"

.SS "int32_t nSequenceId {SEQ_ID_INIT_FROM_DISK}"
(memory only) Sequential id assigned to distinguish order in which blocks are received\&. Initialized to SEQ_ID_INIT_FROM_DISK{1} when loading blocks from disk, except for blocks belonging to the best chain which overwrite it to SEQ_ID_BEST_CHAIN_FROM_DISK{0}\&. 
.SS "uint32_t nTime {0}"

.SS "unsigned int nTimeMax {0}"

.PP
(memory only) Maximum nTime in the chain up to and including this block\&. 
.SS "unsigned int nTx {0}"
Number of transactions in this block\&. This will be nonzero if the block reached the VALID_TRANSACTIONS level, and zero otherwise\&. Note: in a potential headers-first mode, this number cannot be relied upon 
.SS "int32_t nVersion {0}"

.PP
block header 
.SS "const \fBuint256\fP* phashBlock {nullptr}"

.PP
pointer to the hash of the block, if any\&. Memory is owned by this \fBCBlockIndex\fP 
.SS "\fBCBlockIndex\fP* pprev {nullptr}"

.PP
pointer to the index of the predecessor of this block 
.SS "\fBCBlockIndex\fP* pskip {nullptr}"

.PP
pointer to the index of some further predecessor of this block 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
