.TH "CBlockLocator" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBlockLocator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <block\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCBlockLocator\fP ()=default"
.br
.ti -1c
.RI "\fBCBlockLocator\fP (std::vector< \fBuint256\fP > &&have)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCBlockLocator\fP, obj)"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "bool \fBIsNull\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< \fBuint256\fP > \fBvHave\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBDUMMY_VERSION\fP = 70016"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes a place in the block chain to another node such that if the other node doesn't have the same branch, it can find a recent common trunk\&. The further back it is, the further before the fork it may be\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCBlockLocator\fP ()\fR [default]\fP"

.SS "\fBCBlockLocator\fP (std::vector< \fBuint256\fP > && have)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool IsNull () const\fR [inline]\fP"

.SS "SERIALIZE_METHODS (\fBCBlockLocator\fP , obj )\fR [inline]\fP"

.SS "void SetNull ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "int DUMMY_VERSION = 70016\fR [static]\fP, \fR [constexpr]\fP"
Historically \fBCBlockLocator\fP's version field has been written to network streams as the negotiated protocol version and to disk streams as the client version, but the value has never been used\&.

.PP
Hard-code to the highest protocol version ever written to a network stream\&. SerParams can be used if the field requires any meaning in the future, 
.SS "std::vector<\fBuint256\fP> vHave"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
