.TH "CCoinsViewDB" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCoinsViewDB
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <txdb\&.h>\fP
.PP
Inherits \fBCCoinsView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCCoinsViewDB\fP (\fBDBParams\fP db_params, \fBCoinsViewOptions\fP options)"
.br
.ti -1c
.RI "std::optional< \fBCoin\fP > \fBGetCoin\fP (const \fBCOutPoint\fP &outpoint) const override"
.br
.RI "Retrieve the \fBCoin\fP (unspent transaction output) for a given outpoint\&. "
.ti -1c
.RI "bool \fBHaveCoin\fP (const \fBCOutPoint\fP &outpoint) const override"
.br
.RI "Just check whether a given outpoint is unspent\&. "
.ti -1c
.RI "\fBuint256\fP \fBGetBestBlock\fP () const override"
.br
.RI "Retrieve the block hash whose state this \fBCCoinsView\fP currently represents\&. "
.ti -1c
.RI "std::vector< \fBuint256\fP > \fBGetHeadBlocks\fP () const override"
.br
.ti -1c
.RI "bool \fBBatchWrite\fP (\fBCoinsViewCacheCursor\fP &cursor, const \fBuint256\fP &hashBlock) override"
.br
.ti -1c
.RI "std::unique_ptr< \fBCCoinsViewCursor\fP > \fBCursor\fP () const override"
.br
.RI "Get a cursor to iterate over the whole state\&. "
.ti -1c
.RI "bool \fBNeedsUpgrade\fP ()"
.br
.RI "Whether an unsupported database format is used\&. "
.ti -1c
.RI "size_t \fBEstimateSize\fP () const override"
.br
.RI "Estimate database size (0 if not implemented)\&. "
.ti -1c
.RI "void \fBResizeCache\fP (size_t new_cache_size) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(\fBcs_main\fP)"
.br
.RI "Dynamically alter the underlying leveldb cache size\&. "
.in -1c

Public Member Functions inherited from \fBCCoinsView\fP
.in +1c
.ti -1c
.RI "virtual \fB~CCoinsView\fP ()=default"
.br
.RI "As we use CCoinsViews polymorphically, have a virtual destructor\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBDBParams\fP \fBm_db_params\fP"
.br
.ti -1c
.RI "\fBCoinsViewOptions\fP \fBm_options\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBCDBWrapper\fP > \fBm_db\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCCoinsView\fP backed by the coin database (chainstate/) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCCoinsViewDB\fP (\fBDBParams\fP db_params, \fBCoinsViewOptions\fP options)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool BatchWrite (\fBCoinsViewCacheCursor\fP & cursor, const \fBuint256\fP & hashBlock)\fR [override]\fP, \fR [virtual]\fP"
Do a bulk modification (multiple \fBCoin\fP changes + BestBlock change)\&. The passed cursor is used to iterate through the coins\&. 
.PP
Reimplemented from \fBCCoinsView\fP\&.
.SS "std::unique_ptr< \fBCCoinsViewCursor\fP > Cursor () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Get a cursor to iterate over the whole state\&. 
.PP
Reimplemented from \fBCCoinsView\fP\&.
.SS "size_t EstimateSize () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Estimate database size (0 if not implemented)\&. 
.PP
Reimplemented from \fBCCoinsView\fP\&.
.SS "\fBuint256\fP GetBestBlock () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Retrieve the block hash whose state this \fBCCoinsView\fP currently represents\&. 
.PP
Reimplemented from \fBCCoinsView\fP\&.
.SS "std::optional< \fBCoin\fP > GetCoin (const \fBCOutPoint\fP & outpoint) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Retrieve the \fBCoin\fP (unspent transaction output) for a given outpoint\&. 
.PP
Reimplemented from \fBCCoinsView\fP\&.
.SS "std::vector< \fBuint256\fP > GetHeadBlocks () const\fR [override]\fP, \fR [virtual]\fP"
Retrieve the range of blocks that may have been only partially written\&. If the database is in a consistent state, the result is the empty vector\&. Otherwise, a two-element vector is returned consisting of the new and the old block hash, in that order\&. 
.PP
Reimplemented from \fBCCoinsView\fP\&.
.SS "bool HaveCoin (const \fBCOutPoint\fP & outpoint) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Just check whether a given outpoint is unspent\&. 
.PP
Reimplemented from \fBCCoinsView\fP\&.
.SS "bool NeedsUpgrade ()"

.PP
Whether an unsupported database format is used\&. 
.SS "void ResizeCache (size_t new_cache_size)"

.PP
Dynamically alter the underlying leveldb cache size\&. 
.SH "Field Documentation"
.PP 
.SS "std::unique_ptr<\fBCDBWrapper\fP> m_db\fR [protected]\fP"

.SS "\fBDBParams\fP m_db_params\fR [protected]\fP"

.SS "\fBCoinsViewOptions\fP m_options\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
