.TH "CCombinedBan" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCombinedBan
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bantablemodel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCSubNet\fP \fBsubnet\fP"
.br
.ti -1c
.RI "\fBCBanEntry\fP \fBbanEntry\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBCBanEntry\fP banEntry"

.SS "\fBCSubNet\fP subnet"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
