.TH "CDBIterator" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDBIterator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <dbwrapper\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBIteratorImpl\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCDBIterator\fP (const \fBCDBWrapper\fP &_parent, std::unique_ptr< \fBIteratorImpl\fP > _piter)"
.br
.ti -1c
.RI "\fB~CDBIterator\fP ()"
.br
.ti -1c
.RI "bool \fBValid\fP () const"
.br
.ti -1c
.RI "void \fBSeekToFirst\fP ()"
.br
.ti -1c
.RI "template<typename K> void \fBSeek\fP (const K &key)"
.br
.ti -1c
.RI "void \fBNext\fP ()"
.br
.ti -1c
.RI "template<typename K> bool \fBGetKey\fP (K &key)"
.br
.ti -1c
.RI "template<typename V> bool \fBGetValue\fP (V &value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCDBIterator\fP (const \fBCDBWrapper\fP & _parent, std::unique_ptr< \fBIteratorImpl\fP > _piter)"

.PP
\fBParameters\fP
.RS 4
\fI_parent\fP Parent \fBCDBWrapper\fP instance\&. 
.br
\fI_piter\fP The original leveldb iterator\&. 
.RE
.PP

.SS "~\fBCDBIterator\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename K> bool GetKey (K & key)\fR [inline]\fP"

.SS "template<typename V> bool GetValue (V & value)\fR [inline]\fP"

.SS "void Next ()"

.SS "template<typename K> void Seek (const K & key)\fR [inline]\fP"

.SS "void SeekToFirst ()"

.SS "bool Valid () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
