.TH "CDBIterator::IteratorImpl" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDBIterator::IteratorImpl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIteratorImpl\fP (\fBleveldb::Iterator\fP *_iter)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const std::unique_ptr< \fBleveldb::Iterator\fP > \fBiter\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IteratorImpl (\fBleveldb::Iterator\fP * _iter)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Field Documentation"
.PP 
.SS "const std::unique_ptr<\fBleveldb::Iterator\fP> iter"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
