.TH "CDiskTxPos" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDiskTxPos
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <disktxpos\&.h>\fP
.PP
Inherits \fBFlatFilePos\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCDiskTxPos\fP, obj)"
.br
.ti -1c
.RI "\fBCDiskTxPos\fP (const \fBFlatFilePos\fP &blockIn, uint32_t nTxOffsetIn)"
.br
.ti -1c
.RI "\fBCDiskTxPos\fP ()=default"
.br
.in -1c

Public Member Functions inherited from \fBFlatFilePos\fP
.in +1c
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBFlatFilePos\fP, obj)"
.br
.ti -1c
.RI "\fBFlatFilePos\fP ()=default"
.br
.ti -1c
.RI "\fBFlatFilePos\fP (int32_t nFileIn, uint32_t nPosIn)"
.br
.ti -1c
.RI "bool \fBIsNull\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBnTxOffset\fP {0}"
.br
.in -1c

Data Fields inherited from \fBFlatFilePos\fP
.in +1c
.ti -1c
.RI "int32_t \fBnFile\fP {\-1}"
.br
.ti -1c
.RI "uint32_t \fBnPos\fP {0}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCDiskTxPos\fP (const \fBFlatFilePos\fP & blockIn, uint32_t nTxOffsetIn)\fR [inline]\fP"

.SS "\fBCDiskTxPos\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "SERIALIZE_METHODS (\fBCDiskTxPos\fP , obj )\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "uint32_t nTxOffset {0}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
