.TH "CExtKey" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CExtKey
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <key\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCExtKey\fP ()=default"
.br
.ti -1c
.RI "\fBCExtKey\fP (const \fBCExtPubKey\fP &xpub, const \fBCKey\fP &key_in)"
.br
.ti -1c
.RI "void \fBEncode\fP (unsigned char code[\fBBIP32_EXTKEY_SIZE\fP]) const"
.br
.ti -1c
.RI "void \fBDecode\fP (const unsigned char code[\fBBIP32_EXTKEY_SIZE\fP])"
.br
.ti -1c
.RI "bool \fBDerive\fP (\fBCExtKey\fP &out, unsigned int \fBnChild\fP) const"
.br
.ti -1c
.RI "\fBCExtPubKey\fP \fBNeuter\fP () const"
.br
.ti -1c
.RI "void \fBSetSeed\fP (std::span< const std::byte > seed)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBnDepth\fP"
.br
.ti -1c
.RI "unsigned char \fBvchFingerprint\fP [4]"
.br
.ti -1c
.RI "unsigned int \fBnChild\fP"
.br
.ti -1c
.RI "\fBChainCode\fP \fBchaincode\fP"
.br
.ti -1c
.RI "\fBCKey\fP \fBkey\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCExtKey\fP &a, const \fBCExtKey\fP &b)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCExtKey\fP ()\fR [default]\fP"

.SS "\fBCExtKey\fP (const \fBCExtPubKey\fP & xpub, const \fBCKey\fP & key_in)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Decode (const unsigned char code[BIP32_EXTKEY_SIZE])"

.SS "bool Derive (\fBCExtKey\fP & out, unsigned int nChild) const\fR [nodiscard]\fP"

.SS "void Encode (unsigned char code[BIP32_EXTKEY_SIZE]) const"

.SS "\fBCExtPubKey\fP Neuter () const"

.SS "void SetSeed (std::span< const std::byte > seed)"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "bool operator== (const \fBCExtKey\fP & a, const \fBCExtKey\fP & b)\fR [friend]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBChainCode\fP chaincode"

.SS "\fBCKey\fP key"

.SS "unsigned int nChild"

.SS "unsigned char nDepth"

.SS "unsigned char vchFingerprint[4]"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
