.TH "CFeeRate" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFeeRate
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <feerate\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCFeeRate\fP ()=default"
.br
.ti -1c
.RI "template<std::integral I> \fBCFeeRate\fP (const I m_feerate_kvb)"
.br
.ti -1c
.RI "\fBCFeeRate\fP (const \fBCAmount\fP &nFeePaid, int32_t virtual_bytes)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetFee\fP (int32_t virtual_bytes) const"
.br
.ti -1c
.RI "\fBFeePerVSize\fP \fBGetFeePerVSize\fP () const"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetFeePerK\fP () const"
.br
.ti -1c
.RI "\fBCFeeRate\fP & \fBoperator+=\fP (const \fBCFeeRate\fP &a)"
.br
.ti -1c
.RI "std::string \fBToString\fP (const \fBFeeEstimateMode\fP &fee_estimate_mode=\fBFeeEstimateMode::BTC_KVB\fP) const"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCFeeRate\fP, obj)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::weak_ordering \fBoperator<=>\fP (const \fBCFeeRate\fP &a, const \fBCFeeRate\fP &b) noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCFeeRate\fP &a, const \fBCFeeRate\fP &b) noexcept"
.br
.ti -1c
.RI "\fBCFeeRate\fP \fBoperator*\fP (const \fBCFeeRate\fP &f, int a)"
.br
.ti -1c
.RI "\fBCFeeRate\fP \fBoperator*\fP (int a, const \fBCFeeRate\fP &f)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fee rate in satoshis per virtualbyte: \fBCAmount\fP / vB the feerate is represented internally as \fBFeeFrac\fP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCFeeRate\fP ()\fR [default]\fP"
Fee rate of 0 satoshis per 0 vB 
.SS "template<std::integral I> \fBCFeeRate\fP (const I m_feerate_kvb)\fR [inline]\fP, \fR [explicit]\fP"

.SS "\fBCFeeRate\fP (const \fBCAmount\fP & nFeePaid, int32_t virtual_bytes)"
Construct a fee rate from a fee in satoshis and a vsize in vB\&.

.PP
Passing any virtual_bytes less than or equal to 0 will result in 0 fee rate per 0 size\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBCAmount\fP GetFee (int32_t virtual_bytes) const"
Return the fee in satoshis for the given vsize in vbytes\&. If the calculated fee would have fractional satoshis, then the returned fee will always be rounded up to the nearest satoshi\&. 
.SS "\fBCAmount\fP GetFeePerK () const\fR [inline]\fP"
Return the fee in satoshis for a vsize of 1000 vbytes 
.SS "\fBFeePerVSize\fP GetFeePerVSize () const\fR [inline]\fP"

.SS "\fBCFeeRate\fP & operator+= (const \fBCFeeRate\fP & a)\fR [inline]\fP"

.SS "SERIALIZE_METHODS (\fBCFeeRate\fP , obj )\fR [inline]\fP"

.SS "std::string ToString (const \fBFeeEstimateMode\fP & fee_estimate_mode = \fR\fBFeeEstimateMode::BTC_KVB\fP\fP) const"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBCFeeRate\fP operator* (const \fBCFeeRate\fP & f, int a)\fR [friend]\fP"

.SS "\fBCFeeRate\fP operator* (int a, const \fBCFeeRate\fP & f)\fR [friend]\fP"

.SS "std::weak_ordering operator<=> (const \fBCFeeRate\fP & a, const \fBCFeeRate\fP & b)\fR [friend]\fP"

.SS "bool operator== (const \fBCFeeRate\fP & a, const \fBCFeeRate\fP & b)\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
