.TH "src/crypto/chacha20poly1305.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crypto/chacha20poly1305.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <span>\fP
.br
\fR#include <crypto/chacha20\&.h>\fP
.br
\fR#include <crypto/poly1305\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAEADChaCha20Poly1305\fP"
.br
.ti -1c
.RI "class \fBFSChaCha20Poly1305\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
