.TH "src/crypto/chacha20.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crypto/chacha20.h
.SH SYNOPSIS
.br
.PP
\fR#include <array>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <iterator>\fP
.br
\fR#include <span>\fP
.br
\fR#include <utility>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBChaCha20Aligned\fP"
.br
.ti -1c
.RI "class \fBChaCha20\fP"
.br
.ti -1c
.RI "class \fBFSChaCha20\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
