.TH "Chain::NotifyOptions" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Chain::NotifyOptions \- \fBOptions\fP specifying which chain notifications are required\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <chain\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBconnect_undo_data\fP = false"
.br
.RI "Include undo data with block connected notifications\&. "
.ti -1c
.RI "bool \fBdisconnect_data\fP = false"
.br
.RI "Include block data with block disconnected notifications\&. "
.ti -1c
.RI "bool \fBdisconnect_undo_data\fP = false"
.br
.RI "Include undo data with block disconnected notifications\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBOptions\fP specifying which chain notifications are required\&. 
.SH "Field Documentation"
.PP 
.SS "bool connect_undo_data = false"

.PP
Include undo data with block connected notifications\&. 
.SS "bool disconnect_data = false"

.PP
Include block data with block disconnected notifications\&. 
.SS "bool disconnect_undo_data = false"

.PP
Include undo data with block disconnected notifications\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
