.TH "ChainTxData" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChainTxData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <chainparams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int64_t \fBnTime\fP"
.br
.RI "UNIX timestamp of last known number of transactions\&. "
.ti -1c
.RI "uint64_t \fBtx_count\fP"
.br
.RI "total number of transactions between genesis and that timestamp "
.ti -1c
.RI "double \fBdTxRate\fP"
.br
.RI "estimated number of transactions per second after that timestamp "
.in -1c
.SH "Detailed Description"
.PP 
Holds various statistics on transactions within a chain\&. Used to estimate verification progress during chain sync\&.

.PP
See also: \fBCChainParams::TxData\fP, GuessVerificationProgress\&. 
.SH "Field Documentation"
.PP 
.SS "double dTxRate"

.PP
estimated number of transactions per second after that timestamp 
.SS "int64_t nTime"

.PP
UNIX timestamp of last known number of transactions\&. 
.SS "uint64_t tx_count"

.PP
total number of transactions between genesis and that timestamp 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
