.TH "src/test/util/chainstate.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/util/chainstate.h
.SH SYNOPSIS
.br
.PP
\fR#include <clientversion\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <node/context\&.h>\fP
.br
\fR#include <node/utxo_snapshot\&.h>\fP
.br
\fR#include <rpc/blockchain\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const auto \fBNoMalleation\fP = [](\fBAutoFile\fP& file, \fBnode::SnapshotMetadata\fP& meta){}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const auto NoMalleation = [](\fBAutoFile\fP& file, \fBnode::SnapshotMetadata\fP& meta){}"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
