.TH "src/chainparamsbase.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/chainparamsbase.h
.SH SYNOPSIS
.br
.PP
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCBaseChainParams\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLIST_CHAIN_NAMES\fP   'main, test, testnet4, signet, regtest'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBCBaseChainParams\fP > \fBCreateBaseChainParams\fP (const \fBChainType\fP chain)"
.br
.ti -1c
.RI "void \fBSetupChainParamsBaseOptions\fP (\fBArgsManager\fP &argsman)"
.br
.ti -1c
.RI "const \fBCBaseChainParams\fP & \fBBaseParams\fP ()"
.br
.ti -1c
.RI "void \fBSelectBaseParams\fP (const \fBChainType\fP chain)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LIST_CHAIN_NAMES   'main, test, testnet4, signet, regtest'"
List of possible chain / network names 
.SH "Function Documentation"
.PP 
.SS "const \fBCBaseChainParams\fP & BaseParams ()"
Return the currently selected parameters\&. This won't change after app startup, except for unit tests\&. 
.SS "std::unique_ptr< \fBCBaseChainParams\fP > CreateBaseChainParams (const \fBChainType\fP chain)"
Creates and returns a std::unique_ptr<CBaseChainParams> of the chosen chain\&.

.PP
Port numbers for incoming Tor connections (8334, 18334, 38334, 48334, 18445) have been chosen arbitrarily to keep ranges of used ports tight\&. 
.SS "void SelectBaseParams (const \fBChainType\fP chain)"
Sets the params returned by \fBParams()\fP to those for the given chain\&. 
.SS "void SetupChainParamsBaseOptions (\fBArgsManager\fP & argsman)"
Set the arguments for chainparams 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
