.TH "src/kernel/chain.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kernel/chain.h
.SH SYNOPSIS
.br
.PP
\fR#include <attributes\&.h>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBlockInfo\fP"
.br
.RI "Block data sent with blockConnected, blockDisconnected notifications\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinterfaces\fP"
.br
.ti -1c
.RI "namespace \fBkernel\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBinterfaces::BlockInfo\fP \fBMakeBlockInfo\fP (const \fBCBlockIndex\fP *block_index, const \fBCBlock\fP *data=nullptr)"
.br
.RI "Return data from block index\&. "
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBChainstateRole\fP &role)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
