.TH "ChainstateRole" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChainstateRole \- Information about chainstate that notifications are sent from\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBvalidated\fP {true}"
.br
.ti -1c
.RI "bool \fBhistorical\fP {false}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information about chainstate that notifications are sent from\&. 
.SH "Field Documentation"
.PP 
.SS "bool historical {false}"
Whether this is a historical chainstate downloading old blocks to validate an assumeutxo snapshot, not syncing to the network tip\&. 
.SS "bool validated {true}"
Whether this is a notification from a chainstate that's been fully validated starting from the genesis block\&. False if it is from an assumeutxo snapshot chainstate that has not been validated yet\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
