.TH "CharNotInt8" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharNotInt8
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <serialize\&.h>\fP
.SH "Concept definition"
.PP 

.nf
template<class T>
concept CharNotInt8 =  std::same_as<T, char> && !std::same_as<T, int8_t>
.PP
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
