.TH "src/secp256k1/src/checkmem.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/checkmem.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSECP256K1_CHECKMEM_NOOP\fP(p,  len)"
.br
.ti -1c
.RI "#define \fBSECP256K1_CHECKMEM_MSAN_DEFINE\fP(p,  len)"
.br
.ti -1c
.RI "#define \fBSECP256K1_CHECKMEM_ENABLED\fP   0"
.br
.ti -1c
.RI "#define \fBSECP256K1_CHECKMEM_UNDEFINE\fP(p,  len)"
.br
.ti -1c
.RI "#define \fBSECP256K1_CHECKMEM_DEFINE\fP(p,  len)"
.br
.ti -1c
.RI "#define \fBSECP256K1_CHECKMEM_CHECK\fP(p,  len)"
.br
.ti -1c
.RI "#define \fBSECP256K1_CHECKMEM_RUNNING\fP()"
.br
.ti -1c
.RI "#define \fBSECP256K1_CHECKMEM_CHECK_VERIFY\fP(p,  len)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SECP256K1_CHECKMEM_CHECK( p,  len)"
\fBValue:\fP
.nf
SECP256K1_CHECKMEM_NOOP((p), (len))
.PP
.fi

.SS "#define SECP256K1_CHECKMEM_CHECK_VERIFY( p,  len)"
\fBValue:\fP
.nf
SECP256K1_CHECKMEM_NOOP((p), (len))
.PP
.fi

.SS "#define SECP256K1_CHECKMEM_DEFINE( p,  len)"
\fBValue:\fP
.nf
SECP256K1_CHECKMEM_NOOP((p), (len))
.PP
.fi

.SS "#define SECP256K1_CHECKMEM_ENABLED   0"

.SS "#define SECP256K1_CHECKMEM_MSAN_DEFINE( p,  len)"
\fBValue:\fP
.nf
SECP256K1_CHECKMEM_NOOP((p), (len))
.PP
.fi

.SS "#define SECP256K1_CHECKMEM_NOOP( p,  len)"
\fBValue:\fP
.nf
do { (void)(p); (void)(len); } while(0)
.PP
.fi

.SS "#define SECP256K1_CHECKMEM_RUNNING()"
\fBValue:\fP
.nf
(0)
.PP
.fi

.SS "#define SECP256K1_CHECKMEM_UNDEFINE( p,  len)"
\fBValue:\fP
.nf
SECP256K1_CHECKMEM_NOOP((p), (len))
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
