.TH "src/test/checkqueue_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/checkqueue_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <checkqueue\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <condition_variable>\fP
.br
\fR#include <mutex>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <unordered_set>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBNoLockLoggingTestingSetup\fP"
.br
.ti -1c
.RI "struct \fBCheckQueueTest\fP"
.br
.ti -1c
.RI "struct \fBFakeCheck\fP"
.br
.ti -1c
.RI "struct \fBFakeCheckCheckCompletion\fP"
.br
.ti -1c
.RI "struct \fBFixedCheck\fP"
.br
.ti -1c
.RI "struct \fBUniqueCheck\fP"
.br
.ti -1c
.RI "struct \fBMemoryCheck\fP"
.br
.ti -1c
.RI "struct \fBFrozenCleanupCheck\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBCCheckQueue\fP< \fBFakeCheckCheckCompletion\fP > \fBCorrect_Queue\fP"
.br
.ti -1c
.RI "typedef \fBCCheckQueue\fP< \fBFakeCheck\fP > \fBStandard_Queue\fP"
.br
.ti -1c
.RI "typedef \fBCCheckQueue\fP< \fBFixedCheck\fP > \fBFixed_Queue\fP"
.br
.ti -1c
.RI "typedef \fBCCheckQueue\fP< \fBUniqueCheck\fP > \fBUnique_Queue\fP"
.br
.ti -1c
.RI "typedef \fBCCheckQueue\fP< \fBMemoryCheck\fP > \fBMemory_Queue\fP"
.br
.ti -1c
.RI "typedef \fBCCheckQueue\fP< \fBFrozenCleanupCheck\fP > \fBFrozenCleanup_Queue\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_CheckQueue_Correct_Zero)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_CheckQueue_Correct_One)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_CheckQueue_Correct_Max)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_CheckQueue_Correct_Random)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_CheckQueue_Catches_Failure)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_CheckQueue_Recovers_From_Failure)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_CheckQueue_UniqueCheck)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_CheckQueue_Memory)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_CheckQueue_FrozenCleanup)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_CheckQueueControl_Locks)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBCCheckQueue\fP<\fBFakeCheckCheckCompletion\fP> \fBCorrect_Queue\fP"

.SS "typedef \fBCCheckQueue\fP<\fBFixedCheck\fP> \fBFixed_Queue\fP"

.SS "typedef \fBCCheckQueue\fP<\fBFrozenCleanupCheck\fP> \fBFrozenCleanup_Queue\fP"

.SS "typedef \fBCCheckQueue\fP<\fBMemoryCheck\fP> \fBMemory_Queue\fP"

.SS "typedef \fBCCheckQueue\fP<\fBFakeCheck\fP> \fBStandard_Queue\fP"

.SS "typedef \fBCCheckQueue\fP<\fBUniqueCheck\fP> \fBUnique_Queue\fP"

.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (test_CheckQueue_Catches_Failure )"
Test that distinct failing checks are caught 
.SS "BOOST_AUTO_TEST_CASE (test_CheckQueue_Correct_Max )"
Test that MAX check is correct 
.SS "BOOST_AUTO_TEST_CASE (test_CheckQueue_Correct_One )"
Test that 1 check is correct 
.SS "BOOST_AUTO_TEST_CASE (test_CheckQueue_Correct_Random )"
Test that random numbers of checks are correct 
.SS "BOOST_AUTO_TEST_CASE (test_CheckQueue_Correct_Zero )"
Test that 0 checks is correct 
.SS "BOOST_AUTO_TEST_CASE (test_CheckQueue_FrozenCleanup )"

.SS "BOOST_AUTO_TEST_CASE (test_CheckQueue_Memory )"

.SS "BOOST_AUTO_TEST_CASE (test_CheckQueue_Recovers_From_Failure )"

.SS "BOOST_AUTO_TEST_CASE (test_CheckQueue_UniqueCheck )"

.SS "BOOST_AUTO_TEST_CASE (test_CheckQueueControl_Locks )"
Test that \fBCCheckQueueControl\fP is threadsafe 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
