.TH "src/util/check.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/check.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <util/check\&.h>\fP
.br
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <clientversion\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <cstdio>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <source_location>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBStrFormatInternalBug\fP (std::string_view msg, const std::source_location &loc)"
.br
.ti -1c
.RI "void \fBassertion_fail\fP (const std::source_location &loc, std::string_view assertion)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBg_detail_test_only_CheckFailuresAreExceptionsNotAborts\fP {false}"
.br
.ti -1c
.RI "std::atomic< bool > \fBg_enable_dynamic_fuzz_determinism\fP {false}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void assertion_fail (const std::source_location & loc, std::string_view assertion)"
Internal helper 
.SS "std::string StrFormatInternalBug (std::string_view msg, const std::source_location & loc)"

.SH "Variable Documentation"
.PP 
.SS "bool g_detail_test_only_CheckFailuresAreExceptionsNotAborts {false}"

.SS "std::atomic<bool> g_enable_dynamic_fuzz_determinism {false}"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
