.TH "src/test/fuzz/util/check_globals.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/util/check_globals.h
.SH SYNOPSIS
.br
.PP
\fR#include <atomic>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBCheckGlobals\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::atomic< bool > \fBg_used_system_time\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::atomic<bool> g_used_system_time\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
