.TH "CHKDF_HMAC_SHA256_L32" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CHKDF_HMAC_SHA256_L32
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hkdf_sha256_32\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCHKDF_HMAC_SHA256_L32\fP (const unsigned char *ikm, size_t ikmlen, const std::string &salt)"
.br
.ti -1c
.RI "void \fBExpand32\fP (const std::string &info, unsigned char hash[OUTPUT_SIZE])"
.br
.in -1c
.SH "Detailed Description"
.PP 
A rfc5869 HKDF implementation with HMAC_SHA256 and fixed key output length of 32 bytes (L=32) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCHKDF_HMAC_SHA256_L32\fP (const unsigned char * ikm, size_t ikmlen, const std::string & salt)"

.SH "Member Function Documentation"
.PP 
.SS "void Expand32 (const std::string & info, unsigned char hash[OUTPUT_SIZE])"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
