.TH "CInv" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CInv
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <protocol\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCInv\fP ()"
.br
.ti -1c
.RI "\fBCInv\fP (uint32_t typeIn, const \fBuint256\fP &hashIn)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCInv\fP, obj)"
.br
.ti -1c
.RI "std::string \fBGetMessageType\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "bool \fBIsMsgTx\fP () const"
.br
.ti -1c
.RI "bool \fBIsMsgBlk\fP () const"
.br
.ti -1c
.RI "bool \fBIsMsgWtx\fP () const"
.br
.ti -1c
.RI "bool \fBIsMsgFilteredBlk\fP () const"
.br
.ti -1c
.RI "bool \fBIsMsgCmpctBlk\fP () const"
.br
.ti -1c
.RI "bool \fBIsMsgWitnessBlk\fP () const"
.br
.ti -1c
.RI "bool \fBIsGenTxMsg\fP () const"
.br
.ti -1c
.RI "bool \fBIsGenBlkMsg\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBhash\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCInv\fP &a, const \fBCInv\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
inv message data 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCInv\fP ()"

.SS "\fBCInv\fP (uint32_t typeIn, const \fBuint256\fP & hashIn)"

.SH "Member Function Documentation"
.PP 
.SS "std::string GetMessageType () const"

.SS "bool IsGenBlkMsg () const\fR [inline]\fP"

.SS "bool IsGenTxMsg () const\fR [inline]\fP"

.SS "bool IsMsgBlk () const\fR [inline]\fP"

.SS "bool IsMsgCmpctBlk () const\fR [inline]\fP"

.SS "bool IsMsgFilteredBlk () const\fR [inline]\fP"

.SS "bool IsMsgTx () const\fR [inline]\fP"

.SS "bool IsMsgWitnessBlk () const\fR [inline]\fP"

.SS "bool IsMsgWtx () const\fR [inline]\fP"

.SS "SERIALIZE_METHODS (\fBCInv\fP , obj )\fR [inline]\fP"

.SS "std::string ToString () const"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "bool operator< (const \fBCInv\fP & a, const \fBCInv\fP & b)\fR [friend]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP hash"

.SS "uint32_t type"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
