.TH "src/support/cleanse.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/support/cleanse.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstdlib>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmemory_cleanse\fP (void *ptr, size_t len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void memory_cleanse (void * ptr, size_t len)"
Secure overwrite a buffer (possibly containing secret data) with zero-bytes\&. The write operation will not be optimized out by the compiler\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
