.TH "src/clientversion.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/clientversion.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <clientversion\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <bitcoin\-build\-info\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUILD_DESC\fP   'v' CLIENT_VERSION_STRING"
.br
.ti -1c
.RI "#define \fBBUILD_SUFFIX\fP   '\-unk'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const std::string \fBUA_NAME\fP ('Satoshi')"
.br
.ti -1c
.RI "std::string \fBFormatFullVersion\fP ()"
.br
.ti -1c
.RI "std::string \fBFormatSubVersion\fP (const std::string &\fBname\fP, int nClientVersion, const std::vector< std::string > &comments)"
.br
.ti -1c
.RI "std::string \fBCopyrightHolders\fP (const std::string &strPrefix)"
.br
.ti -1c
.RI "std::string \fBLicenseInfo\fP ()"
.br
.ti -1c
.RI "template<typename C, typename \fBS\fP, typename UnaryOp> auto \fBJoin\fP (const C &container, const \fBS\fP &separator, UnaryOp unary_op)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUILD_DESC   'v' CLIENT_VERSION_STRING"

.SS "#define BUILD_SUFFIX   '\-unk'"

.SH "Function Documentation"
.PP 
.SS "std::string CopyrightHolders (const std::string & strPrefix)"

.SS "std::string FormatFullVersion ()"

.SS "std::string FormatSubVersion (const std::string & name, int nClientVersion, const std::vector< std::string > & comments)"
\fBFormat\fP the subversion field according to BIP 14 spec (https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki) 
.SS "template<typename C, typename \fBS\fP, typename UnaryOp> auto Join (const C & container, const \fBS\fP & separator, UnaryOp unary_op)"
Join all container items\&. Typically used to concatenate strings but accepts containers with elements of any type\&.

.PP
\fBParameters\fP
.RS 4
\fIcontainer\fP The items to join 
.br
\fIseparator\fP The separator 
.br
\fIunary_op\fP Apply this operator to each item 
.RE
.PP

.SS "std::string LicenseInfo ()"
Returns licensing information (for -version) 
.SS "const std::string UA_NAME ('Satoshi' )"
Name of client reported in the 'version' message\&. Report the same name for both bitcoind and bitcoin-qt, to make it harder for attackers to target servers or GUI users specifically\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
