.TH "src/minisketch/src/fields/clmul_common_impl.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/minisketch/src/fields/clmul_common_impl.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <immintrin\&.h>\fP
.br
\fR#include '\&.\&./int_utils\&.h'\fP
.br
\fR#include '\&.\&./lintrans\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNO_SANITIZE_MEMORY\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NO_SANITIZE_MEMORY"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
