.TH "src/test/fuzz/cluster_linearize.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/cluster_linearize.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <cluster_linearize\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/util/cluster_linearize\&.h>\fP
.br
\fR#include <util/bitset\&.h>\fP
.br
\fR#include <util/feefrac\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_depgraph_sim)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_depgraph_serialization)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_components)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_make_connected)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_chunking)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_simple_finder)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_simple_linearize)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_sfl)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_linearize)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_postlinearize)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_postlinearize_tree)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_postlinearize_moved_leaf)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (clusterlin_fix_linearization)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (clusterlin_chunking )"

.SS "FUZZ_TARGET (clusterlin_components )"

.SS "FUZZ_TARGET (clusterlin_depgraph_serialization )"

.SS "FUZZ_TARGET (clusterlin_depgraph_sim )"
Real \fBDepGraph\fP being tested\&.

.PP
Simulated \fBDepGraph\fP (sim[i] is std::nullopt if position i does not exist; otherwise, sim[i]->first is its individual feerate, and sim[i]->second is its set of ancestors\&.

.PP
The number of non-nullopt position in sim\&.

.PP
Read a valid index of a transaction from the provider\&.

.PP
Read a valid subset of the transactions from the provider\&.

.PP
Read any set of transactions from the provider (including unused positions)\&.

.PP
Propagate ancestor information in sim\&.

.PP
Compare the state of transaction i in the simulation with the real one\&.
.SS "FUZZ_TARGET (clusterlin_fix_linearization )"

.SS "FUZZ_TARGET (clusterlin_linearize )"

.SS "FUZZ_TARGET (clusterlin_make_connected )"

.SS "FUZZ_TARGET (clusterlin_postlinearize )"

.SS "FUZZ_TARGET (clusterlin_postlinearize_moved_leaf )"

.SS "FUZZ_TARGET (clusterlin_postlinearize_tree )"

.SS "FUZZ_TARGET (clusterlin_sfl )"
Whether to make the depgraph connected\&.

.PP
Whether to load some input linearization into the state\&.

.PP
Whether that input linearization is topological\&.
.SS "FUZZ_TARGET (clusterlin_simple_finder )"

.SS "FUZZ_TARGET (clusterlin_simple_linearize )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
