.TH "CMainParams" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMainParams
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCChainParams\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMainParams\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBCChainParams\fP
.in +1c
.ti -1c
.RI "const \fBConsensus::Params\fP & \fBGetConsensus\fP () const"
.br
.ti -1c
.RI "const \fBMessageStartChars\fP & \fBMessageStart\fP () const"
.br
.ti -1c
.RI "uint16_t \fBGetDefaultPort\fP () const"
.br
.ti -1c
.RI "std::vector< int > \fBGetAvailableSnapshotHeights\fP () const"
.br
.ti -1c
.RI "const \fBCBlock\fP & \fBGenesisBlock\fP () const"
.br
.ti -1c
.RI "bool \fBDefaultConsistencyChecks\fP () const"
.br
.ti -1c
.RI "bool \fBIsTestChain\fP () const"
.br
.ti -1c
.RI "bool \fBIsMockableChain\fP () const"
.br
.ti -1c
.RI "uint64_t \fBPruneAfterHeight\fP () const"
.br
.ti -1c
.RI "uint64_t \fBAssumedBlockchainSize\fP () const"
.br
.ti -1c
.RI "uint64_t \fBAssumedChainStateSize\fP () const"
.br
.ti -1c
.RI "bool \fBMineBlocksOnDemand\fP () const"
.br
.ti -1c
.RI "std::string \fBGetChainTypeString\fP () const"
.br
.ti -1c
.RI "\fBChainType\fP \fBGetChainType\fP () const"
.br
.ti -1c
.RI "const std::vector< std::string > & \fBDNSSeeds\fP () const"
.br
.ti -1c
.RI "const std::vector< unsigned char > & \fBBase58Prefix\fP (\fBBase58Type\fP type) const"
.br
.ti -1c
.RI "const std::string & \fBBech32HRP\fP () const"
.br
.ti -1c
.RI "const std::vector< uint8_t > & \fBFixedSeeds\fP () const"
.br
.ti -1c
.RI "const \fBHeadersSyncParams\fP & \fBHeadersSync\fP () const"
.br
.ti -1c
.RI "std::optional< \fBAssumeutxoData\fP > \fBAssumeutxoForHeight\fP (int height) const"
.br
.ti -1c
.RI "std::optional< \fBAssumeutxoData\fP > \fBAssumeutxoForBlockhash\fP (const \fBuint256\fP &blockhash) const"
.br
.ti -1c
.RI "const \fBChainTxData\fP & \fBTxData\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBCChainParams\fP
.in +1c
.ti -1c
.RI "enum \fBBase58Type\fP { \fBPUBKEY_ADDRESS\fP, \fBSCRIPT_ADDRESS\fP, \fBSECRET_KEY\fP, \fBEXT_PUBLIC_KEY\fP, \fBEXT_SECRET_KEY\fP, \fBMAX_BASE58_TYPES\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBCChainParams\fP
.in +1c
.ti -1c
.RI "static std::unique_ptr< const \fBCChainParams\fP > \fBRegTest\fP (const \fBRegTestOptions\fP &options)"
.br
.ti -1c
.RI "static std::unique_ptr< const \fBCChainParams\fP > \fBSigNet\fP (const \fBSigNetOptions\fP &options)"
.br
.ti -1c
.RI "static std::unique_ptr< const \fBCChainParams\fP > \fBMain\fP ()"
.br
.ti -1c
.RI "static std::unique_ptr< const \fBCChainParams\fP > \fBTestNet\fP ()"
.br
.ti -1c
.RI "static std::unique_ptr< const \fBCChainParams\fP > \fBTestNet4\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBCChainParams\fP
.in +1c
.ti -1c
.RI "\fBCChainParams\fP ()=default"
.br
.in -1c

Protected Attributes inherited from \fBCChainParams\fP
.in +1c
.ti -1c
.RI "\fBConsensus::Params\fP \fBconsensus\fP"
.br
.ti -1c
.RI "\fBMessageStartChars\fP \fBpchMessageStart\fP"
.br
.ti -1c
.RI "uint16_t \fBnDefaultPort\fP"
.br
.ti -1c
.RI "uint64_t \fBnPruneAfterHeight\fP"
.br
.ti -1c
.RI "uint64_t \fBm_assumed_blockchain_size\fP"
.br
.ti -1c
.RI "uint64_t \fBm_assumed_chain_state_size\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBvSeeds\fP"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBbase58Prefixes\fP [\fBMAX_BASE58_TYPES\fP]"
.br
.ti -1c
.RI "std::string \fBbech32_hrp\fP"
.br
.ti -1c
.RI "\fBChainType\fP \fBm_chain_type\fP"
.br
.ti -1c
.RI "\fBCBlock\fP \fBgenesis\fP"
.br
.ti -1c
.RI "std::vector< uint8_t > \fBvFixedSeeds\fP"
.br
.ti -1c
.RI "bool \fBfDefaultConsistencyChecks\fP"
.br
.ti -1c
.RI "bool \fBm_is_mockable_chain\fP"
.br
.ti -1c
.RI "std::vector< \fBAssumeutxoData\fP > \fBm_assumeutxo_data\fP"
.br
.ti -1c
.RI "\fBChainTxData\fP \fBchainTxData\fP"
.br
.ti -1c
.RI "\fBHeadersSyncParams\fP \fBm_headers_sync_params\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main network on which people trade goods and services\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCMainParams\fP ()\fR [inline]\fP"
The message start string is designed to be unlikely to occur in normal data\&. The characters are rarely used upper ASCII, not valid as UTF-8, and produce a large 32-bit integer with any alignment\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
