.TH "CMessageHeader" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMessageHeader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <protocol\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMessageHeader\fP ()=default"
.br
.ti -1c
.RI "\fBCMessageHeader\fP (const \fBMessageStartChars\fP &pchMessageStartIn, const char *msg_type, unsigned int nMessageSizeIn)"
.br
.ti -1c
.RI "std::string \fBGetMessageType\fP () const"
.br
.ti -1c
.RI "bool \fBIsMessageTypeValid\fP () const"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCMessageHeader\fP, obj)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMessageStartChars\fP \fBpchMessageStart\fP {}"
.br
.ti -1c
.RI "char \fBm_msg_type\fP [\fBMESSAGE_TYPE_SIZE\fP] {}"
.br
.ti -1c
.RI "uint32_t \fBnMessageSize\fP {std::numeric_limits<uint32_t>::max()}"
.br
.ti -1c
.RI "uint8_t \fBpchChecksum\fP [\fBCHECKSUM_SIZE\fP] {}"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr size_t \fBMESSAGE_TYPE_SIZE\fP = 12"
.br
.ti -1c
.RI "static constexpr size_t \fBMESSAGE_SIZE_SIZE\fP = 4"
.br
.ti -1c
.RI "static constexpr size_t \fBCHECKSUM_SIZE\fP = 4"
.br
.ti -1c
.RI "static constexpr size_t \fBMESSAGE_SIZE_OFFSET\fP = std::tuple_size_v<\fBMessageStartChars\fP> + \fBMESSAGE_TYPE_SIZE\fP"
.br
.ti -1c
.RI "static constexpr size_t \fBCHECKSUM_OFFSET\fP = \fBMESSAGE_SIZE_OFFSET\fP + \fBMESSAGE_SIZE_SIZE\fP"
.br
.ti -1c
.RI "static constexpr size_t \fBHEADER_SIZE\fP = std::tuple_size_v<\fBMessageStartChars\fP> + \fBMESSAGE_TYPE_SIZE\fP + \fBMESSAGE_SIZE_SIZE\fP + \fBCHECKSUM_SIZE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Message header\&. (4) message start\&. (12) message type\&. (4) size\&. (4) checksum\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCMessageHeader\fP ()\fR [explicit]\fP, \fR [default]\fP"

.SS "\fBCMessageHeader\fP (const \fBMessageStartChars\fP & pchMessageStartIn, const char * msg_type, unsigned int nMessageSizeIn)"
Construct a P2P message header from message-start characters, a message type and the size of the message\&. 
.PP
\fBNote\fP
.RS 4
Passing in a \fRmsg_type\fP longer than MESSAGE_TYPE_SIZE will result in a run-time assertion error\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string GetMessageType () const"

.SS "bool IsMessageTypeValid () const"

.SS "SERIALIZE_METHODS (\fBCMessageHeader\fP , obj )\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "size_t CHECKSUM_OFFSET = \fBMESSAGE_SIZE_OFFSET\fP + \fBMESSAGE_SIZE_SIZE\fP\fR [static]\fP, \fR [constexpr]\fP"

.SS "size_t CHECKSUM_SIZE = 4\fR [static]\fP, \fR [constexpr]\fP"

.SS "size_t HEADER_SIZE = std::tuple_size_v<\fBMessageStartChars\fP> + \fBMESSAGE_TYPE_SIZE\fP + \fBMESSAGE_SIZE_SIZE\fP + \fBCHECKSUM_SIZE\fP\fR [static]\fP, \fR [constexpr]\fP"

.SS "char m_msg_type[\fBMESSAGE_TYPE_SIZE\fP] {}"

.SS "size_t MESSAGE_SIZE_OFFSET = std::tuple_size_v<\fBMessageStartChars\fP> + \fBMESSAGE_TYPE_SIZE\fP\fR [static]\fP, \fR [constexpr]\fP"

.SS "size_t MESSAGE_SIZE_SIZE = 4\fR [static]\fP, \fR [constexpr]\fP"

.SS "size_t MESSAGE_TYPE_SIZE = 12\fR [static]\fP, \fR [constexpr]\fP"

.SS "uint32_t nMessageSize {std::numeric_limits<uint32_t>::max()}"

.SS "uint8_t pchChecksum[\fBCHECKSUM_SIZE\fP] {}"

.SS "\fBMessageStartChars\fP pchMessageStart {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
