.TH "CMutableTransaction" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMutableTransaction
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transaction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMutableTransaction\fP ()"
.br
.ti -1c
.RI "\fBCMutableTransaction\fP (const \fBCTransaction\fP &tx)"
.br
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.ti -1c
.RI "template<typename Stream> \fBCMutableTransaction\fP (\fBdeserialize_type\fP, const \fBTransactionSerParams\fP &params, Stream &s)"
.br
.ti -1c
.RI "template<typename Stream> \fBCMutableTransaction\fP (\fBdeserialize_type\fP, Stream &s)"
.br
.ti -1c
.RI "\fBTxid\fP \fBGetHash\fP () const"
.br
.ti -1c
.RI "bool \fBHasWitness\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< \fBCTxIn\fP > \fBvin\fP"
.br
.ti -1c
.RI "std::vector< \fBCTxOut\fP > \fBvout\fP"
.br
.ti -1c
.RI "uint32_t \fBversion\fP"
.br
.ti -1c
.RI "uint32_t \fBnLockTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A mutable version of \fBCTransaction\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCMutableTransaction\fP ()\fR [explicit]\fP"

.SS "\fBCMutableTransaction\fP (const \fBCTransaction\fP & tx)\fR [explicit]\fP"

.SS "template<typename Stream> \fBCMutableTransaction\fP (\fBdeserialize_type\fP , const \fBTransactionSerParams\fP & params, Stream & s)\fR [inline]\fP"

.SS "template<typename Stream> \fBCMutableTransaction\fP (\fBdeserialize_type\fP , Stream & s)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBTxid\fP GetHash () const"
Compute the hash of this \fBCMutableTransaction\fP\&. This is computed on the fly, as opposed to \fBGetHash()\fP in \fBCTransaction\fP, which uses a cached result\&. 
.SS "bool HasWitness () const\fR [inline]\fP"

.SS "template<typename Stream> void Serialize (Stream & s) const\fR [inline]\fP"

.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "uint32_t nLockTime"

.SS "uint32_t version"

.SS "std::vector<\fBCTxIn\fP> vin"

.SS "std::vector<\fBCTxOut\fP> vout"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
