.TH "CNetAddr::SerParams" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CNetAddr::SerParams
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <netaddress\&.h>\fP
.PP
Inherited by \fBCAddress::SerParams\fP\&.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBEncoding\fP \fBenc\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const \fBEncoding\fP enc"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
