.TH "CNetMessage" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CNetMessage
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <net\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCNetMessage\fP (\fBDataStream\fP &&recv_in)"
.br
.ti -1c
.RI "\fBCNetMessage\fP (\fBCNetMessage\fP &&)=default"
.br
.ti -1c
.RI "\fBCNetMessage\fP (const \fBCNetMessage\fP &)=delete"
.br
.ti -1c
.RI "\fBCNetMessage\fP & \fBoperator=\fP (\fBCNetMessage\fP &&)=default"
.br
.ti -1c
.RI "\fBCNetMessage\fP & \fBoperator=\fP (const \fBCNetMessage\fP &)=delete"
.br
.ti -1c
.RI "size_t \fBGetMemoryUsage\fP () const noexcept"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDataStream\fP \fBm_recv\fP"
.br
.RI "received message data "
.ti -1c
.RI "std::chrono::microseconds \fBm_time\fP {0}"
.br
.RI "time of message receipt "
.ti -1c
.RI "uint32_t \fBm_message_size\fP {0}"
.br
.RI "size of the payload "
.ti -1c
.RI "uint32_t \fBm_raw_message_size\fP {0}"
.br
.RI "used wire size of the message (including header/checksum) "
.ti -1c
.RI "std::string \fBm_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTransport\fP protocol agnostic message container\&. Ideally it should only contain receive time, payload, type and size\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCNetMessage\fP (\fBDataStream\fP && recv_in)\fR [inline]\fP, \fR [explicit]\fP"

.SS "\fBCNetMessage\fP (\fBCNetMessage\fP && )\fR [default]\fP"

.SS "\fBCNetMessage\fP (const \fBCNetMessage\fP & )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "size_t GetMemoryUsage () const\fR [noexcept]\fP"
Compute total memory usage of this object (own memory + any dynamic memory)\&. 
.SS "\fBCNetMessage\fP & operator= (\fBCNetMessage\fP && )\fR [default]\fP"

.SS "\fBCNetMessage\fP & operator= (const \fBCNetMessage\fP & )\fR [delete]\fP"

.SH "Field Documentation"
.PP 
.SS "uint32_t m_message_size {0}"

.PP
size of the payload 
.SS "uint32_t m_raw_message_size {0}"

.PP
used wire size of the message (including header/checksum) 
.SS "\fBDataStream\fP m_recv"

.PP
received message data 
.SS "std::chrono::microseconds m_time {0}"

.PP
time of message receipt 
.SS "std::string m_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
