.TH "src/leveldb/util/coding_test.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/util/coding_test.cc
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include 'util/coding\&.h'\fP
.br
\fR#include 'util/testharness\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCoding\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBCoding\fP, Fixed32)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCoding\fP, Fixed64)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCoding\fP, EncodingOutput)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCoding\fP, Varint32)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCoding\fP, Varint64)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCoding\fP, Varint32Overflow)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCoding\fP, Varint32Truncation)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCoding\fP, Varint64Overflow)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCoding\fP, Varint64Truncation)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCoding\fP, Strings)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
