.TH "src/qt/coincontroltreewidget.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/coincontroltreewidget.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/coincontroltreewidget\&.h>\fP
.br
\fR#include <qt/coincontroldialog\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
