.TH "src/qt/coincontroldialog.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/coincontroldialog.h
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <QAbstractButton>\fP
.br
\fR#include <QAction>\fP
.br
\fR#include <QDialog>\fP
.br
\fR#include <QList>\fP
.br
\fR#include <QMenu>\fP
.br
\fR#include <QPoint>\fP
.br
\fR#include <QString>\fP
.br
\fR#include <QTreeWidgetItem>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCCoinControlWidgetItem\fP"
.br
.ti -1c
.RI "class \fBCoinControlDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBASYMP_UTF8\fP   '\\xE2\\x89\\x88'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASYMP_UTF8   '\\xE2\\x89\\x88'"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
