.TH "CoinControlDialog" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoinControlDialog
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <coincontroldialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoinControlDialog\fP (\fBwallet::CCoinControl\fP &coin_control, \fBWalletModel\fP *model, const \fBPlatformStyle\fP *platformStyle, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~CoinControlDialog\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBupdateLabels\fP (\fBwallet::CCoinControl\fP &m_coin_control, \fBWalletModel\fP *, QDialog *)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static QList< \fBCAmount\fP > \fBpayAmounts\fP"
.br
.ti -1c
.RI "static bool \fBfSubtractFeeFromAmount\fP = false"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeEvent\fP (QEvent *e) override"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCCoinControlWidgetItem\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCoinControlDialog\fP (\fBwallet::CCoinControl\fP & coin_control, \fBWalletModel\fP * model, const \fBPlatformStyle\fP * platformStyle, QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SS "~\fBCoinControlDialog\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void changeEvent (QEvent * e)\fR [override]\fP, \fR [protected]\fP"

.SS "void updateLabels (\fBwallet::CCoinControl\fP & m_coin_control, \fBWalletModel\fP * model, QDialog * dialog)\fR [static]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBCCoinControlWidgetItem\fP\fR [friend]\fP"

.SH "Field Documentation"
.PP 
.SS "bool fSubtractFeeFromAmount = false\fR [static]\fP"

.SS "QList< \fBCAmount\fP > payAmounts\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
