.TH "src/test/fuzz/coins_view.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/coins_view.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <coins\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <consensus/tx_check\&.h>\fP
.br
\fR#include <consensus/tx_verify\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <script/interpreter\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <txdb\&.h>\fP
.br
\fR#include <util/hasher\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <limits>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <string>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_coins_view\fP ()"
.br
.ti -1c
.RI "void \fBTestCoinsView\fP (\fBFuzzedDataProvider\fP &fuzzed_data_provider, \fBCCoinsView\fP &backend_coins_view, bool is_db)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (coins_view,\&.\fBinit\fP=\fBinitialize_coins_view\fP)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (coins_view_db,\&.\fBinit\fP=\fBinitialize_coins_view\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (coins_view , \&. init = \fR\fBinitialize_coins_view\fP\fP)"

.SS "FUZZ_TARGET (coins_view_db , \&. init = \fR\fBinitialize_coins_view\fP\fP)"

.SS "void initialize_coins_view ()"

.SS "void TestCoinsView (\fBFuzzedDataProvider\fP & fuzzed_data_provider, \fBCCoinsView\fP & backend_coins_view, bool is_db)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
