.TH "src/kernel/coinstats.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kernel/coinstats.h
.SH SYNOPSIS
.br
.PP
\fR#include <arith_uint256\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <crypto/muhash\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <optional>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBCCoinsStats\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnode\fP"
.br
.ti -1c
.RI "namespace \fBkernel\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCoinStatsHashType\fP { \fBHASH_SERIALIZED\fP, \fBMUHASH\fP, \fBNONE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBGetBogoSize\fP (const \fBCScript\fP &script_pub_key)"
.br
.ti -1c
.RI "void \fBApplyCoinHash\fP (\fBMuHash3072\fP &muhash, const \fBCOutPoint\fP &outpoint, const \fBCoin\fP &coin)"
.br
.ti -1c
.RI "void \fBRemoveCoinHash\fP (\fBMuHash3072\fP &muhash, const \fBCOutPoint\fP &outpoint, const \fBCoin\fP &coin)"
.br
.ti -1c
.RI "std::optional< \fBCCoinsStats\fP > \fBComputeUTXOStats\fP (\fBCoinStatsHashType\fP hash_type, \fBCCoinsView\fP *view, \fBnode::BlockManager\fP &blockman, const std::function< void()> &interruption_point)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
