.TH "src/node/coin.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/coin.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/coin\&.h>\fP
.br
\fR#include <node/context\&.h>\fP
.br
\fR#include <txmempool\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFindCoins\fP (const \fBNodeContext\fP &\fBnode\fP, std::map< \fBCOutPoint\fP, \fBCoin\fP > &coins)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
