.TH "CoinEligibilityFilter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoinEligibilityFilter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <coinselection\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoinEligibilityFilter\fP ()=delete"
.br
.ti -1c
.RI "\fBCoinEligibilityFilter\fP (int \fBconf_mine\fP, int \fBconf_theirs\fP, uint64_t \fBmax_ancestors\fP)"
.br
.ti -1c
.RI "\fBCoinEligibilityFilter\fP (int \fBconf_mine\fP, int \fBconf_theirs\fP, uint64_t \fBmax_ancestors\fP, uint64_t \fBmax_descendants\fP)"
.br
.ti -1c
.RI "\fBCoinEligibilityFilter\fP (int \fBconf_mine\fP, int \fBconf_theirs\fP, uint64_t \fBmax_ancestors\fP, uint64_t \fBmax_descendants\fP, bool include_partial)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCoinEligibilityFilter\fP &other) const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const int \fBconf_mine\fP"
.br
.ti -1c
.RI "const int \fBconf_theirs\fP"
.br
.ti -1c
.RI "const uint64_t \fBmax_ancestors\fP"
.br
.ti -1c
.RI "const uint64_t \fBmax_descendants\fP"
.br
.ti -1c
.RI "const bool \fBm_include_partial_groups\fP {false}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parameters for filtering which OutputGroups we may use in coin selection\&. We start by being very selective and requiring multiple confirmations and then get more permissive if we cannot fund the transaction\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCoinEligibilityFilter\fP ()\fR [delete]\fP"

.SS "\fBCoinEligibilityFilter\fP (int conf_mine, int conf_theirs, uint64_t max_ancestors)\fR [inline]\fP"

.SS "\fBCoinEligibilityFilter\fP (int conf_mine, int conf_theirs, uint64_t max_ancestors, uint64_t max_descendants)\fR [inline]\fP"

.SS "\fBCoinEligibilityFilter\fP (int conf_mine, int conf_theirs, uint64_t max_ancestors, uint64_t max_descendants, bool include_partial)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool operator< (const \fBCoinEligibilityFilter\fP & other) const\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "const int conf_mine"
Minimum number of confirmations for outputs that we sent to ourselves\&. We may use unconfirmed UTXOs sent from ourselves, e\&.g\&. change outputs\&. 
.SS "const int conf_theirs"
Minimum number of confirmations for outputs received from a different wallet\&. 
.SS "const bool m_include_partial_groups {false}"
When avoid_reuse=true and there are full groups (OUTPUT_GROUP_MAX_ENTRIES), whether or not to use any partial groups\&. 
.SS "const uint64_t max_ancestors"
Maximum number of unconfirmed ancestors aggregated across all UTXOs in an \fBOutputGroup\fP\&. 
.SS "const uint64_t max_descendants"
Maximum number of descendants that a single UTXO in the \fBOutputGroup\fP may have\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
