.TH "src/test/coinscachepair_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/coinscachepair_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <coins\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <list>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::list< \fBCoinsCachePair\fP > \fBCreatePairs\fP (\fBCoinsCachePair\fP &sentinel)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (linked_list_iteration)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (linked_list_iterate_erase)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (linked_list_random_deletion)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (linked_list_set_state)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (linked_list_iterate_erase )"

.SS "BOOST_AUTO_TEST_CASE (linked_list_iteration )"

.SS "BOOST_AUTO_TEST_CASE (linked_list_random_deletion )"

.SS "BOOST_AUTO_TEST_CASE (linked_list_set_state )"

.SS "std::list< \fBCoinsCachePair\fP > CreatePairs (\fBCoinsCachePair\fP & sentinel)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
