.TH "CoinsViewOptions" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoinsViewOptions \- User-controlled performance and debug options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <txdb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBbatch_write_bytes\fP {DEFAULT_DB_CACHE_BATCH}"
.br
.RI "Maximum database write batch size in bytes\&. "
.ti -1c
.RI "int \fBsimulate_crash_ratio\fP {0}"
.br
.RI "If non-zero, randomly exit when the database is flushed with (1/ratio) probability\&. "
.in -1c
.SH "Detailed Description"
.PP 
User-controlled performance and debug options\&. 
.SH "Field Documentation"
.PP 
.SS "size_t batch_write_bytes {DEFAULT_DB_CACHE_BATCH}"

.PP
Maximum database write batch size in bytes\&. 
.SS "int simulate_crash_ratio {0}"

.PP
If non-zero, randomly exit when the database is flushed with (1/ratio) probability\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
