.TH "Coin" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coin
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <coins\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoin\fP (\fBCTxOut\fP &&outIn, int nHeightIn, bool fCoinBaseIn)"
.br
.RI "construct a \fBCoin\fP from a \fBCTxOut\fP and height/coinbase information\&. "
.ti -1c
.RI "\fBCoin\fP (const \fBCTxOut\fP &outIn, int nHeightIn, bool fCoinBaseIn)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "\fBCoin\fP ()"
.br
.RI "empty constructor "
.ti -1c
.RI "bool \fBIsCoinBase\fP () const"
.br
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.ti -1c
.RI "bool \fBIsSpent\fP () const"
.br
.ti -1c
.RI "size_t \fBDynamicMemoryUsage\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCTxOut\fP \fBout\fP"
.br
.RI "unspent transaction output "
.ti -1c
.RI "unsigned int \fBfCoinBase\fP: 1"
.br
.RI "whether containing transaction was a coinbase "
.ti -1c
.RI "uint32_t \fBnHeight\fP: 31"
.br
.RI "at which height this containing transaction was included in the active block chain "
.in -1c
.SH "Detailed Description"
.PP 
A UTXO entry\&.

.PP
Serialized format:
.IP "\(bu" 2
VARINT((coinbase ? 1 : 0) | (height << 1))
.IP "\(bu" 2
the non-spent \fBCTxOut\fP (via \fBTxOutCompression\fP) 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCoin\fP (\fBCTxOut\fP && outIn, int nHeightIn, bool fCoinBaseIn)\fR [inline]\fP"

.PP
construct a \fBCoin\fP from a \fBCTxOut\fP and height/coinbase information\&. 
.SS "\fBCoin\fP (const \fBCTxOut\fP & outIn, int nHeightIn, bool fCoinBaseIn)\fR [inline]\fP"

.SS "\fBCoin\fP ()\fR [inline]\fP"

.PP
empty constructor 
.SH "Member Function Documentation"
.PP 
.SS "void Clear ()\fR [inline]\fP"

.SS "size_t DynamicMemoryUsage () const\fR [inline]\fP"

.SS "bool IsCoinBase () const\fR [inline]\fP"

.SS "bool IsSpent () const\fR [inline]\fP"
Either this coin never existed (see e\&.g\&. coinEmpty in coins\&.cpp), or it did exist and has been spent\&. 
.SS "template<typename Stream> void Serialize (Stream & s) const\fR [inline]\fP"

.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "unsigned int fCoinBase"

.PP
whether containing transaction was a coinbase 
.SS "uint32_t nHeight"

.PP
at which height this containing transaction was included in the active block chain 
.SS "\fBCTxOut\fP out"

.PP
unspent transaction output 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
