.TH "SettingsSpan" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SettingsSpan
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <settings\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSettingsSpan\fP ()=default"
.br
.ti -1c
.RI "\fBSettingsSpan\fP (const \fBSettingsValue\fP &value) noexcept"
.br
.ti -1c
.RI "\fBSettingsSpan\fP (const \fBSettingsValue\fP *\fBdata\fP, size_t \fBsize\fP) noexcept"
.br
.ti -1c
.RI "\fBSettingsSpan\fP (const std::vector< \fBSettingsValue\fP > &vec) noexcept"
.br
.ti -1c
.RI "const \fBSettingsValue\fP * \fBbegin\fP () const"
.br
.RI "Pointer to first non-negated value\&. "
.ti -1c
.RI "const \fBSettingsValue\fP * \fBend\fP () const"
.br
.RI "Pointer to end of values\&. "
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.RI "True if there are any non-negated values\&. "
.ti -1c
.RI "bool \fBlast_negated\fP () const"
.br
.RI "True if the last value is negated\&. "
.ti -1c
.RI "size_t \fBnegated\fP () const"
.br
.RI "Number of negated values\&. "
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBSettingsValue\fP * \fBdata\fP = nullptr"
.br
.ti -1c
.RI "size_t \fBsize\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Accessor for list of settings that skips negated values when iterated over\&. The last boolean \fRfalse\fP value in the list and all earlier values are considered negated\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SettingsSpan ()\fR [explicit]\fP, \fR [default]\fP"

.SS "SettingsSpan (const \fBSettingsValue\fP & value)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "SettingsSpan (const \fBSettingsValue\fP * data, size_t size)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "SettingsSpan (const std::vector< \fBSettingsValue\fP > & vec)\fR [explicit]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBSettingsValue\fP * begin () const"

.PP
Pointer to first non-negated value\&. 
.SS "bool empty () const"

.PP
True if there are any non-negated values\&. 
.SS "const \fBSettingsValue\fP * end () const"

.PP
Pointer to end of values\&. 
.SS "bool last_negated () const"

.PP
True if the last value is negated\&. 
.SS "size_t negated () const"

.PP
Number of negated values\&. 
.SH "Field Documentation"
.PP 
.SS "const \fBSettingsValue\fP* data = nullptr"

.SS "size_t size = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
