.TH "Settings" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Settings
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <settings\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::map< std::string, \fBSettingsValue\fP > \fBforced_settings\fP"
.br
.RI "Map of setting name to forced setting value\&. "
.ti -1c
.RI "std::map< std::string, std::vector< \fBSettingsValue\fP > > \fBcommand_line_options\fP"
.br
.RI "Map of setting name to list of command line values\&. "
.ti -1c
.RI "std::map< std::string, \fBSettingsValue\fP > \fBrw_settings\fP"
.br
.RI "Map of setting name to read-write file setting value\&. "
.ti -1c
.RI "std::map< std::string, std::map< std::string, std::vector< \fBSettingsValue\fP > > > \fBro_config\fP"
.br
.RI "Map of config section name and setting name to list of config file values\&. "
.in -1c
.SH "Detailed Description"
.PP 
Stored settings\&. This struct combines settings from the command line, a read-only configuration file, and a read-write runtime settings file\&. 
.SH "Field Documentation"
.PP 
.SS "std::map<std::string, std::vector<\fBSettingsValue\fP> > command_line_options"

.PP
Map of setting name to list of command line values\&. 
.SS "std::map<std::string, \fBSettingsValue\fP> forced_settings"

.PP
Map of setting name to forced setting value\&. 
.SS "std::map<std::string, std::map<std::string, std::vector<\fBSettingsValue\fP> > > ro_config"

.PP
Map of config section name and setting name to list of config file values\&. 
.SS "std::map<std::string, \fBSettingsValue\fP> rw_settings"

.PP
Map of setting name to read-write file setting value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
