.TH "ConfigError" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigError
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <init\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBConfigStatus\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBmessage\fP {}"
.br
.ti -1c
.RI "std::vector< std::string > \fBdetails\fP {}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "std::vector<std::string> details {}"

.SS "\fBbilingual_str\fP message {}"

.SS "\fBConfigStatus\fP status"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
