.TH "src/test/common_url_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/common_url_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/url\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (encode_decode_test)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (decode_malformed_test)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (decode_lowercase_hex_test)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (decode_internal_nulls_test)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (decode_internal_nulls_test )"

.SS "BOOST_AUTO_TEST_CASE (decode_lowercase_hex_test )"

.SS "BOOST_AUTO_TEST_CASE (decode_malformed_test )"

.SS "BOOST_AUTO_TEST_CASE (encode_decode_test )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
