.TH "src/init/common.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/init/common.h \- Common init functions shared by bitcoin-node, bitcoin-wallet, etc\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <util/result\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAddLoggingArgs\fP (\fBArgsManager\fP &argsman)"
.br
.ti -1c
.RI "void \fBSetLoggingOptions\fP (const \fBArgsManager\fP &\fBargs\fP)"
.br
.ti -1c
.RI "\fButil::Result\fP< void > \fBSetLoggingCategories\fP (const \fBArgsManager\fP &\fBargs\fP)"
.br
.ti -1c
.RI "\fButil::Result\fP< void > \fBSetLoggingLevel\fP (const \fBArgsManager\fP &\fBargs\fP)"
.br
.ti -1c
.RI "bool \fBStartLogging\fP (const \fBArgsManager\fP &\fBargs\fP)"
.br
.ti -1c
.RI "void \fBLogPackageVersion\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Common init functions shared by bitcoin-node, bitcoin-wallet, etc\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
