.TH "src/compat/compat.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/compat/compat.h
.SH SYNOPSIS
.br
.PP
\fR#include <arpa/inet\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <net/if\&.h>\fP
.br
\fR#include <netdb\&.h>\fP
.br
\fR#include <netinet/in\&.h>\fP
.br
\fR#include <netinet/tcp\&.h>\fP
.br
\fR#include <sys/mman\&.h>\fP
.br
\fR#include <sys/select\&.h>\fP
.br
\fR#include <sys/socket\&.h>\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <cerrno>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWSAGetLastError\fP()"
.br
.ti -1c
.RI "#define \fBWSAEINVAL\fP   EINVAL"
.br
.ti -1c
.RI "#define \fBWSAEWOULDBLOCK\fP   EWOULDBLOCK"
.br
.ti -1c
.RI "#define \fBWSAEAGAIN\fP   EAGAIN"
.br
.ti -1c
.RI "#define \fBWSAEMSGSIZE\fP   EMSGSIZE"
.br
.ti -1c
.RI "#define \fBWSAEINTR\fP   EINTR"
.br
.ti -1c
.RI "#define \fBWSAEINPROGRESS\fP   EINPROGRESS"
.br
.ti -1c
.RI "#define \fBWSAEADDRINUSE\fP   EADDRINUSE"
.br
.ti -1c
.RI "#define \fBINVALID_SOCKET\fP   (\fBSOCKET\fP)(~0)"
.br
.ti -1c
.RI "#define \fBSOCKET_ERROR\fP   \-1"
.br
.ti -1c
.RI "#define \fBMAX_PATH\fP   1024"
.br
.ti -1c
.RI "#define \fBMAIN_FUNCTION\fP   int \fBmain\fP(int argc, char* argv[])"
.br
.ti -1c
.RI "#define \fBMSG_NOSIGNAL\fP   0"
.br
.ti -1c
.RI "#define \fBMSG_DONTWAIT\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBSOCKET\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INVALID_SOCKET   (\fBSOCKET\fP)(~0)"

.SS "#define MAIN_FUNCTION   int \fBmain\fP(int argc, char* argv[])"

.SS "#define MAX_PATH   1024"

.SS "#define MSG_DONTWAIT   0"

.SS "#define MSG_NOSIGNAL   0"

.SS "#define SOCKET_ERROR   \-1"

.SS "#define WSAEADDRINUSE   EADDRINUSE"

.SS "#define WSAEAGAIN   EAGAIN"

.SS "#define WSAEINPROGRESS   EINPROGRESS"

.SS "#define WSAEINTR   EINTR"

.SS "#define WSAEINVAL   EINVAL"

.SS "#define WSAEMSGSIZE   EMSGSIZE"

.SS "#define WSAEWOULDBLOCK   EWOULDBLOCK"

.SS "#define WSAGetLastError()"
\fBValue:\fP
.nf
errno
.PP
.fi

.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned int \fBSOCKET\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
