.TH "CompactSizeFormatter< RangeCheck >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompactSizeFormatter< RangeCheck >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <serialize\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream, typename I> void \fBUnser\fP (Stream &s, I &v)"
.br
.ti -1c
.RI "template<typename Stream, typename I> void \fBSer\fP (Stream &s, I v)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool RangeCheck>
.br
struct CompactSizeFormatter< RangeCheck >"Formatter for integers in CompactSize format\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<bool RangeCheck> template<typename Stream, typename I> void Ser (Stream & s, I v)\fR [inline]\fP"

.SS "template<bool RangeCheck> template<typename Stream, typename I> void Unser (Stream & s, I & v)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
