.TH "src/compressor.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/compressor.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <compressor\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBCompressScript\fP (const \fBCScript\fP &\fBscript\fP, \fBCompressedScript\fP &out)"
.br
.ti -1c
.RI "unsigned int \fBGetSpecialScriptSize\fP (unsigned int nSize)"
.br
.ti -1c
.RI "bool \fBDecompressScript\fP (\fBCScript\fP &\fBscript\fP, unsigned int nSize, const \fBCompressedScript\fP &in)"
.br
.ti -1c
.RI "uint64_t \fBCompressAmount\fP (uint64_t n)"
.br
.ti -1c
.RI "uint64_t \fBDecompressAmount\fP (uint64_t x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint64_t CompressAmount (uint64_t nAmount)"
Compress amount\&.

.PP
nAmount is of type uint64_t and thus cannot be negative\&. If you're passing in a \fBCAmount\fP (int64_t), make sure to properly handle the case where the amount is negative before calling CompressAmount(\&.\&.\&.)\&.

.PP
\fBPrecondition\fP
.RS 4
Function defined only for 0 <= nAmount <= MAX_MONEY\&. 
.RE
.PP

.SS "bool CompressScript (const \fBCScript\fP & script, \fBCompressedScript\fP & out)"

.SS "uint64_t DecompressAmount (uint64_t x)"

.SS "bool DecompressScript (\fBCScript\fP & script, unsigned int nSize, const \fBCompressedScript\fP & in)"

.SS "unsigned int GetSpecialScriptSize (unsigned int nSize)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
