.TH "src/leveldb/util/comparator.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/util/comparator.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'leveldb/comparator\&.h'\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br
\fR#include <type_traits>\fP
.br
\fR#include 'leveldb/slice\&.h'\fP
.br
\fR#include 'util/logging\&.h'\fP
.br
\fR#include 'util/no_destructor\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLEVELDB_EXPORT\fP const \fBComparator\fP * \fBBytewiseComparator\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
