.TH "src/compressor.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/compressor.h
.SH SYNOPSIS
.br
.PP
\fR#include <prevector\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBScriptCompression\fP"
.br
.ti -1c
.RI "struct \fBAmountCompression\fP"
.br
.ti -1c
.RI "struct \fBTxOutCompression\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBCompressedScript\fP = \fBprevector\fP<33, unsigned char>"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBCompressScript\fP (const \fBCScript\fP &\fBscript\fP, \fBCompressedScript\fP &out)"
.br
.ti -1c
.RI "unsigned int \fBGetSpecialScriptSize\fP (unsigned int nSize)"
.br
.ti -1c
.RI "bool \fBDecompressScript\fP (\fBCScript\fP &\fBscript\fP, unsigned int nSize, const \fBCompressedScript\fP &in)"
.br
.ti -1c
.RI "uint64_t \fBCompressAmount\fP (uint64_t nAmount)"
.br
.ti -1c
.RI "uint64_t \fBDecompressAmount\fP (uint64_t nAmount)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBCompressedScript\fP = \fBprevector\fP<33, unsigned char>"
This saves us from making many heap allocations when serializing and deserializing compressed scripts\&.

.PP
This prevector size is determined by the largest \&.resize() in the CompressScript function\&. The largest compressed script format is a compressed public key, which is 33 bytes\&. 
.SH "Function Documentation"
.PP 
.SS "uint64_t CompressAmount (uint64_t nAmount)"
Compress amount\&.

.PP
nAmount is of type uint64_t and thus cannot be negative\&. If you're passing in a \fBCAmount\fP (int64_t), make sure to properly handle the case where the amount is negative before calling CompressAmount(\&.\&.\&.)\&.

.PP
\fBPrecondition\fP
.RS 4
Function defined only for 0 <= nAmount <= MAX_MONEY\&. 
.RE
.PP

.SS "bool CompressScript (const \fBCScript\fP & script, \fBCompressedScript\fP & out)"

.SS "uint64_t DecompressAmount (uint64_t nAmount)"

.SS "bool DecompressScript (\fBCScript\fP & script, unsigned int nSize, const \fBCompressedScript\fP & in)"

.SS "unsigned int GetSpecialScriptSize (unsigned int nSize)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
