.TH "CompareBlocksByHeight" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompareBlocksByHeight
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCBlockIndex\fP *a, const \fBCBlockIndex\fP *b) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Comparison function for sorting the getchaintips heads\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool operator() (const \fBCBlockIndex\fP * a, const \fBCBlockIndex\fP * b) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
