.TH "src/test/compress_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/compress_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <compressor\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUM_MULTIPLES_UNIT\fP   100000"
.br
.ti -1c
.RI "#define \fBNUM_MULTIPLES_CENT\fP   10000"
.br
.ti -1c
.RI "#define \fBNUM_MULTIPLES_1BTC\fP   10000"
.br
.ti -1c
.RI "#define \fBNUM_MULTIPLES_50BTC\fP   420000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (compress_amounts)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (compress_script_to_ckey_id)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (compress_script_to_cscript_id)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (compress_script_to_compressed_pubkey_id)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (compress_script_to_uncompressed_pubkey_id)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (compress_p2pk_scripts_not_on_curve)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NUM_MULTIPLES_1BTC   10000"

.SS "#define NUM_MULTIPLES_50BTC   420000"

.SS "#define NUM_MULTIPLES_CENT   10000"

.SS "#define NUM_MULTIPLES_UNIT   100000"

.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (compress_amounts )"

.SS "BOOST_AUTO_TEST_CASE (compress_p2pk_scripts_not_on_curve )"

.SS "BOOST_AUTO_TEST_CASE (compress_script_to_ckey_id )"

.SS "BOOST_AUTO_TEST_CASE (compress_script_to_compressed_pubkey_id )"

.SS "BOOST_AUTO_TEST_CASE (compress_script_to_cscript_id )"

.SS "BOOST_AUTO_TEST_CASE (compress_script_to_uncompressed_pubkey_id )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
