.TH "Params" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Params
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <params\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::chrono::seconds \fBPowTargetSpacing\fP () const"
.br
.ti -1c
.RI "int64_t \fBDifficultyAdjustmentInterval\fP () const"
.br
.ti -1c
.RI "int \fBDeploymentHeight\fP (\fBBuriedDeployment\fP dep) const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBhashGenesisBlock\fP"
.br
.ti -1c
.RI "int \fBnSubsidyHalvingInterval\fP"
.br
.ti -1c
.RI "std::map< \fBuint256\fP, \fBscript_verify_flags\fP > \fBscript_flag_exceptions\fP"
.br
.ti -1c
.RI "int \fBBIP34Height\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBBIP34Hash\fP"
.br
.ti -1c
.RI "int \fBBIP65Height\fP"
.br
.ti -1c
.RI "int \fBBIP66Height\fP"
.br
.ti -1c
.RI "int \fBCSVHeight\fP"
.br
.ti -1c
.RI "int \fBSegwitHeight\fP"
.br
.ti -1c
.RI "int \fBMinBIP9WarningHeight\fP"
.br
.ti -1c
.RI "std::array< \fBBIP9Deployment\fP, \fBMAX_VERSION_BITS_DEPLOYMENTS\fP > \fBvDeployments\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBpowLimit\fP"
.br
.ti -1c
.RI "bool \fBfPowAllowMinDifficultyBlocks\fP"
.br
.ti -1c
.RI "bool \fBenforce_BIP94\fP"
.br
.ti -1c
.RI "bool \fBfPowNoRetargeting\fP"
.br
.ti -1c
.RI "int64_t \fBnPowTargetSpacing\fP"
.br
.ti -1c
.RI "int64_t \fBnPowTargetTimespan\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBnMinimumChainWork\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBdefaultAssumeValid\fP"
.br
.ti -1c
.RI "bool \fBsignet_blocks\fP {false}"
.br
.ti -1c
.RI "std::vector< uint8_t > \fBsignet_challenge\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parameters that influence chain consensus\&. 
.SH "Member Function Documentation"
.PP 
.SS "int DeploymentHeight (\fBBuriedDeployment\fP dep) const\fR [inline]\fP"

.SS "int64_t DifficultyAdjustmentInterval () const\fR [inline]\fP"

.SS "std::chrono::seconds PowTargetSpacing () const\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP BIP34Hash"

.SS "int BIP34Height"
Block height and hash at which BIP34 becomes active 
.SS "int BIP65Height"
Block height at which BIP65 becomes active 
.SS "int BIP66Height"
Block height at which BIP66 becomes active 
.SS "int CSVHeight"
Block height at which CSV (BIP68, BIP112 and BIP113) becomes active 
.SS "\fBuint256\fP defaultAssumeValid"
By default assume that the signatures in ancestors of this block are valid 
.SS "bool enforce_BIP94"
Enforce BIP94 timewarp attack mitigation\&. On testnet4 this also enforces the block storm mitigation\&. 
.SS "bool fPowAllowMinDifficultyBlocks"

.SS "bool fPowNoRetargeting"

.SS "\fBuint256\fP hashGenesisBlock"

.SS "int MinBIP9WarningHeight"
Don't warn about unknown BIP 9 activations below this height\&. This prevents us from warning about the CSV and segwit activations\&. 
.SS "\fBuint256\fP nMinimumChainWork"
The best chain should have at least this much work 
.SS "int64_t nPowTargetSpacing"

.SS "int64_t nPowTargetTimespan"

.SS "int nSubsidyHalvingInterval"

.SS "\fBuint256\fP powLimit"
Proof of work parameters 
.SS "std::map<\fBuint256\fP, \fBscript_verify_flags\fP> script_flag_exceptions"
Hashes of blocks that
.IP "\(bu" 2
are known to be consensus valid, and
.IP "\(bu" 2
buried in the chain, and
.IP "\(bu" 2
fail if the default script verify flags are applied\&. 
.PP

.SS "int SegwitHeight"
Block height at which Segwit (BIP141, BIP143 and BIP147) becomes active\&. Note that segwit v0 script rules are enforced on all blocks except the BIP 16 exception blocks\&. 
.SS "bool signet_blocks {false}"
If true, witness commitments contain a payload equal to a Bitcoin Script solution to the signet challenge\&. See BIP325\&. 
.SS "std::vector<uint8_t> signet_challenge"

.SS "std::array<\fBBIP9Deployment\fP,\fBMAX_VERSION_BITS_DEPLOYMENTS\fP> vDeployments"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
