.TH "CountingSemaphoreGrant< LeastMaxValue >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CountingSemaphoreGrant< LeastMaxValue >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <semaphore_grant\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAcquire\fP () noexcept"
.br
.ti -1c
.RI "void \fBRelease\fP () noexcept"
.br
.ti -1c
.RI "bool \fBTryAcquire\fP () noexcept"
.br
.ti -1c
.RI "\fBCountingSemaphoreGrant\fP (const \fBCountingSemaphoreGrant\fP &)=delete"
.br
.ti -1c
.RI "\fBCountingSemaphoreGrant\fP & \fBoperator=\fP (const \fBCountingSemaphoreGrant\fP &)=delete"
.br
.ti -1c
.RI "\fBCountingSemaphoreGrant\fP (\fBCountingSemaphoreGrant\fP &&other) noexcept"
.br
.ti -1c
.RI "\fBCountingSemaphoreGrant\fP & \fBoperator=\fP (\fBCountingSemaphoreGrant\fP &&other) noexcept"
.br
.ti -1c
.RI "\fBCountingSemaphoreGrant\fP () noexcept"
.br
.ti -1c
.RI "\fBCountingSemaphoreGrant\fP (std::counting_semaphore< LeastMaxValue > &sema, bool fTry=false) noexcept"
.br
.ti -1c
.RI "\fB~CountingSemaphoreGrant\fP ()"
.br
.ti -1c
.RI "\fBoperator bool\fP () const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()>
.br
class CountingSemaphoreGrant< LeastMaxValue >"RAII-style semaphore lock 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> \fBCountingSemaphoreGrant\fP (const \fBCountingSemaphoreGrant\fP< LeastMaxValue > & )\fR [delete]\fP"

.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> \fBCountingSemaphoreGrant\fP (\fBCountingSemaphoreGrant\fP< LeastMaxValue > && other)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> \fBCountingSemaphoreGrant\fP ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> \fBCountingSemaphoreGrant\fP (std::counting_semaphore< LeastMaxValue > & sema, bool fTry = \fRfalse\fP)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> ~\fBCountingSemaphoreGrant\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> void Acquire ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> operator bool () const\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> \fBCountingSemaphoreGrant\fP & operator= (const \fBCountingSemaphoreGrant\fP< LeastMaxValue > & )\fR [delete]\fP"

.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> \fBCountingSemaphoreGrant\fP & operator= (\fBCountingSemaphoreGrant\fP< LeastMaxValue > && other)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> void Release ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<std::ptrdiff_t LeastMaxValue = std::counting_semaphore<>::max()> bool TryAcquire ()\fR [inline]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
