.TH "COutPoint" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COutPoint
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transaction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCOutPoint\fP ()"
.br
.ti -1c
.RI "\fBCOutPoint\fP (const \fBTxid\fP &hashIn, uint32_t nIn)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCOutPoint\fP, obj)"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "bool \fBIsNull\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTxid\fP \fBhash\fP"
.br
.ti -1c
.RI "uint32_t \fBn\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr uint32_t \fBNULL_INDEX\fP = std::numeric_limits<uint32_t>::max()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCOutPoint\fP &a, const \fBCOutPoint\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCOutPoint\fP &a, const \fBCOutPoint\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An outpoint - a combination of a transaction hash and an index n into its vout 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCOutPoint\fP ()\fR [inline]\fP"

.SS "\fBCOutPoint\fP (const \fBTxid\fP & hashIn, uint32_t nIn)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool IsNull () const\fR [inline]\fP"

.SS "SERIALIZE_METHODS (\fBCOutPoint\fP , obj )\fR [inline]\fP"

.SS "void SetNull ()\fR [inline]\fP"

.SS "std::string ToString () const"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "bool operator< (const \fBCOutPoint\fP & a, const \fBCOutPoint\fP & b)\fR [friend]\fP"

.SS "bool operator== (const \fBCOutPoint\fP & a, const \fBCOutPoint\fP & b)\fR [friend]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBTxid\fP hash"

.SS "uint32_t n"

.SS "uint32_t NULL_INDEX = std::numeric_limits<uint32_t>::max()\fR [static]\fP, \fR [constexpr]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
