.TH "COutput" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COutput
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <coinselection\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCOutput\fP (const \fBCOutPoint\fP &\fBoutpoint\fP, const \fBCTxOut\fP &\fBtxout\fP, int \fBdepth\fP, int \fBinput_bytes\fP, bool \fBsolvable\fP, bool \fBsafe\fP, int64_t \fBtime\fP, bool \fBfrom_me\fP, const std::optional< \fBCFeeRate\fP > feerate=std::nullopt)"
.br
.ti -1c
.RI "\fBCOutput\fP (const \fBCOutPoint\fP &\fBoutpoint\fP, const \fBCTxOut\fP &\fBtxout\fP, int \fBdepth\fP, int \fBinput_bytes\fP, bool \fBsolvable\fP, bool \fBsafe\fP, int64_t \fBtime\fP, bool \fBfrom_me\fP, const \fBCAmount\fP fees)"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCOutput\fP &rhs) const"
.br
.ti -1c
.RI "void \fBApplyBumpFee\fP (\fBCAmount\fP bump_fee)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetFee\fP () const"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetEffectiveValue\fP () const"
.br
.ti -1c
.RI "bool \fBHasEffectiveValue\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCOutPoint\fP \fBoutpoint\fP"
.br
.ti -1c
.RI "\fBCTxOut\fP \fBtxout\fP"
.br
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "int \fBinput_bytes\fP"
.br
.ti -1c
.RI "bool \fBsolvable\fP"
.br
.ti -1c
.RI "bool \fBsafe\fP"
.br
.ti -1c
.RI "int64_t \fBtime\fP"
.br
.ti -1c
.RI "bool \fBfrom_me\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBlong_term_fee\fP {0}"
.br
.ti -1c
.RI "\fBCAmount\fP \fBancestor_bump_fees\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
A UTXO under consideration for use in funding a new transaction\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCOutput\fP (const \fBCOutPoint\fP & outpoint, const \fBCTxOut\fP & txout, int depth, int input_bytes, bool solvable, bool safe, int64_t time, bool from_me, const std::optional< \fBCFeeRate\fP > feerate = \fRstd::nullopt\fP)\fR [inline]\fP"

.SS "\fBCOutput\fP (const \fBCOutPoint\fP & outpoint, const \fBCTxOut\fP & txout, int depth, int input_bytes, bool solvable, bool safe, int64_t time, bool from_me, const \fBCAmount\fP fees)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ApplyBumpFee (\fBCAmount\fP bump_fee)\fR [inline]\fP"

.SS "\fBCAmount\fP GetEffectiveValue () const\fR [inline]\fP"

.SS "\fBCAmount\fP GetFee () const\fR [inline]\fP"

.SS "bool HasEffectiveValue () const\fR [inline]\fP"

.SS "bool operator< (const \fBCOutput\fP & rhs) const\fR [inline]\fP"

.SS "std::string ToString () const"

.SH "Field Documentation"
.PP 
.SS "\fBCAmount\fP ancestor_bump_fees {0}"
The fee necessary to bump this UTXO's ancestor transactions to the target feerate 
.SS "int depth"
Depth in block chain\&. If > 0: the tx is on chain and has this many confirmations\&. If = 0: the tx is waiting confirmation\&. If < 0: a conflicting tx is on chain and has this many confirmations\&. 
.SS "bool from_me"
Whether the transaction containing this output is sent from the owning wallet 
.SS "int input_bytes"
Pre-computed estimated size of this output as a fully-signed input in a transaction\&. Can be -1 if it could not be calculated 
.SS "\fBCAmount\fP long_term_fee {0}"
The fee required to spend this output at the consolidation feerate\&. 
.SS "\fBCOutPoint\fP outpoint"
The outpoint identifying this UTXO 
.SS "bool safe"
Whether this output is considered safe to spend\&. Unconfirmed transactions from outside keys and unconfirmed replacement transactions are considered unsafe and will not be used to fund new spending transactions\&. 
.SS "bool solvable"
Whether we know how to spend this output, ignoring the lack of keys 
.SS "int64_t time"
The time of the transaction containing this output as determined by \fBCWalletTx::nTimeSmart\fP 
.SS "\fBCTxOut\fP txout"
The output itself 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
