.TH "src/test/util/coverage.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/util/coverage.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/util/coverage\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBResetCoverageCounters\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ResetCoverageCounters ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
