.TH "src/crc32c/src/crc32c_round_up_unittest.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crc32c/src/crc32c_round_up_unittest.cc
.SH SYNOPSIS
.br
.PP
\fR#include '\&./crc32c_round_up\&.h'\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include 'gtest/gtest\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcrc32c\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (CRC32CRoundUpTest, RoundUpUintptr)"
.br
.ti -1c
.RI "\fBTEST\fP (CRC32CRoundUpTest, RoundUpPointer)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
