.TH "src/crc32c/src/crc32c_round_up.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crc32c/src/crc32c_round_up.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcrc32c\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<int N> constexpr uintptr_t \fBRoundUp\fP (uintptr_t pointer)"
.br
.ti -1c
.RI "template<int N> constexpr const uint8_t * \fBRoundUp\fP (const uint8_t *pointer)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
