.TH "src/crc32c/src/crc32c_sse42_unittest.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crc32c/src/crc32c_sse42_unittest.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'gtest/gtest\&.h'\fP
.br
\fR#include '\&./crc32c_extend_unittests\&.h'\fP
.br
\fR#include '\&./crc32c_sse42\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcrc32c\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
