.TH "CRC32CBenchmark" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC32CBenchmark
.SH SYNOPSIS
.br
.PP
.PP
Inherits Fixture\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP (const benchmark::State &state) override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBblock_data_\fP"
.br
.ti -1c
.RI "const uint8_t * \fBblock_buffer_\fP"
.br
.ti -1c
.RI "size_t \fBblock_size_\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SetUp (const benchmark::State & state)\fR [inline]\fP, \fR [override]\fP"

.SH "Field Documentation"
.PP 
.SS "const uint8_t* block_buffer_\fR [protected]\fP"

.SS "std::string block_data_\fR [protected]\fP"

.SS "size_t block_size_\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
