.TH "src/leveldb/util/crc32c.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/util/crc32c.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'util/crc32c\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include 'port/port\&.h'\fP
.br
\fR#include 'util/coding\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.ti -1c
.RI "namespace \fBleveldb::crc32c\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTEP1\fP"
.br
.ti -1c
.RI "#define \fBSTEP4\fP(s)"
.br
.ti -1c
.RI "#define \fBSTEP16\fP"
.br
.ti -1c
.RI "#define \fBSTEP4W\fP(w)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBExtend\fP (uint32_t crc, const char *data, size_t n)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STEP1"
\fBValue:\fP
.nf
  do {                                     \\
    int c = (l & 0xff) ^ *p++;             \\
    l = kByteExtensionTable[c] ^ (l >> 8); \\
  } while (0)
.PP
.fi

.SS "#define STEP16"
\fBValue:\fP
.nf
  do {         \\
    STEP4(0);  \\
    STEP4(1);  \\
    STEP4(2);  \\
    STEP4(3);  \\
    p += 16;   \\
  } while (0)
.PP
.fi

.SS "#define STEP4( s)"
\fBValue:\fP
.nf
  do {                                                                         \\
    crc##s = ReadUint32LE(p + s * 4) ^ kStrideExtensionTable3[crc##s & 0xff] ^ \\
             kStrideExtensionTable2[(crc##s >> 8) & 0xff] ^                    \\
             kStrideExtensionTable1[(crc##s >> 16) & 0xff] ^                   \\
             kStrideExtensionTable0[crc##s >> 24];                             \\
  } while (0)
.PP
.fi

.SS "#define STEP4W( w)"
\fBValue:\fP
.nf
  do {                                              \\
    w ^= l;                                         \\
    for (size_t i = 0; i < 4; ++i) {                \\
      w = (w >> 8) ^ kByteExtensionTable[w & 0xff]; \\
    }                                               \\
    l = w;                                          \\
  } while (0)
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
