.TH "src/crc32c/src/crc32c_extend_unittests.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crc32c/src/crc32c_extend_unittests.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include 'gtest/gtest\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBExtendTest< TestTraits >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcrc32c\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTYPED_TEST_SUITE_P\fP (\fBExtendTest\fP)"
.br
.ti -1c
.RI "\fBTYPED_TEST_P\fP (\fBExtendTest\fP, StandardResults)"
.br
.ti -1c
.RI "\fBTYPED_TEST_P\fP (\fBExtendTest\fP, HelloWorld)"
.br
.ti -1c
.RI "\fBTYPED_TEST_P\fP (\fBExtendTest\fP, BufferSlicing)"
.br
.ti -1c
.RI "\fBTYPED_TEST_P\fP (\fBExtendTest\fP, LargeBufferSlicing)"
.br
.ti -1c
.RI "\fBREGISTER_TYPED_TEST_SUITE_P\fP (\fBExtendTest\fP, StandardResults, HelloWorld, BufferSlicing, LargeBufferSlicing)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
