.TH "crc32c" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crc32c
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBExtendTest\fP"
.br
.ti -1c
.RI "struct \fBPortableTestTraits\fP"
.br
.ti -1c
.RI "struct \fBApiTestTraits\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBExtend\fP (uint32_t crc, const uint8_t *data, size_t count)"
.br
.ti -1c
.RI "uint32_t \fBcrc32c_extend\fP (uint32_t crc, const uint8_t *data, size_t count)"
.br
.ti -1c
.RI "uint32_t \fBcrc32c_value\fP (const uint8_t *data, size_t count)"
.br
.ti -1c
.RI "\fBTYPED_TEST_SUITE_P\fP (\fBExtendTest\fP)"
.br
.ti -1c
.RI "\fBTYPED_TEST_P\fP (\fBExtendTest\fP, StandardResults)"
.br
.ti -1c
.RI "\fBTYPED_TEST_P\fP (\fBExtendTest\fP, HelloWorld)"
.br
.ti -1c
.RI "\fBTYPED_TEST_P\fP (\fBExtendTest\fP, BufferSlicing)"
.br
.ti -1c
.RI "\fBTYPED_TEST_P\fP (\fBExtendTest\fP, LargeBufferSlicing)"
.br
.ti -1c
.RI "\fBREGISTER_TYPED_TEST_SUITE_P\fP (\fBExtendTest\fP, StandardResults, HelloWorld, BufferSlicing, LargeBufferSlicing)"
.br
.ti -1c
.RI "uint32_t \fBExtendPortable\fP (uint32_t crc, const uint8_t *data, size_t count)"
.br
.ti -1c
.RI "\fBINSTANTIATE_TYPED_TEST_SUITE_P\fP (Portable, \fBExtendTest\fP, \fBPortableTestTraits\fP)"
.br
.ti -1c
.RI "void \fBRequestPrefetch\fP (const uint8_t *address)"
.br
.ti -1c
.RI "uint32_t \fBReadUint32LE\fP (const uint8_t *buffer)"
.br
.ti -1c
.RI "uint64_t \fBReadUint64LE\fP (const uint8_t *buffer)"
.br
.ti -1c
.RI "\fBTEST\fP (Crc32CReadLETest, \fBReadUint32LE\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (Crc32CReadLETest, \fBReadUint64LE\fP)"
.br
.ti -1c
.RI "template<int N> constexpr uintptr_t \fBRoundUp\fP (uintptr_t pointer)"
.br
.ti -1c
.RI "template<int N> constexpr const uint8_t * \fBRoundUp\fP (const uint8_t *pointer)"
.br
.ti -1c
.RI "\fBTEST\fP (CRC32CRoundUpTest, RoundUpUintptr)"
.br
.ti -1c
.RI "\fBTEST\fP (CRC32CRoundUpTest, RoundUpPointer)"
.br
.ti -1c
.RI "\fBINSTANTIATE_TYPED_TEST_SUITE_P\fP (Api, \fBExtendTest\fP, \fBApiTestTraits\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t crc32c_extend (uint32_t crc, const uint8_t * data, size_t count)"

.SS "uint32_t crc32c_value (const uint8_t * data, size_t count)"

.SS "uint32_t Extend (uint32_t crc, const uint8_t * data, size_t count)"

.SS "uint32_t ExtendPortable (uint32_t crc, const uint8_t * data, size_t count)"

.SS "INSTANTIATE_TYPED_TEST_SUITE_P (Api , \fBExtendTest\fP , \fBApiTestTraits\fP )"

.SS "INSTANTIATE_TYPED_TEST_SUITE_P (Portable , \fBExtendTest\fP , \fBPortableTestTraits\fP )"

.SS "uint32_t ReadUint32LE (const uint8_t * buffer)\fR [inline]\fP"

.SS "uint64_t ReadUint64LE (const uint8_t * buffer)\fR [inline]\fP"

.SS "REGISTER_TYPED_TEST_SUITE_P (\fBExtendTest\fP , StandardResults , HelloWorld , BufferSlicing , LargeBufferSlicing )"

.SS "void RequestPrefetch (const uint8_t * address)\fR [inline]\fP"

.SS "template<int N> const uint8_t * RoundUp (const uint8_t * pointer)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<int N> uintptr_t RoundUp (uintptr_t pointer)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "TEST (Crc32CReadLETest , \fBReadUint32LE\fP )"

.SS "TEST (Crc32CReadLETest , \fBReadUint64LE\fP )"

.SS "TEST (CRC32CRoundUpTest , RoundUpPointer )"

.SS "TEST (CRC32CRoundUpTest , RoundUpUintptr )"

.SS "TYPED_TEST_P (\fBExtendTest\fP , BufferSlicing )"

.SS "TYPED_TEST_P (\fBExtendTest\fP , HelloWorld )"

.SS "TYPED_TEST_P (\fBExtendTest\fP , LargeBufferSlicing )"

.SS "TYPED_TEST_P (\fBExtendTest\fP , StandardResults )"

.SS "TYPED_TEST_SUITE_P (\fBExtendTest\fP )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
