.TH "src/crc32c/src/crc32c_arm64.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crc32c/src/crc32c_arm64.cc
.SH SYNOPSIS
.br
.PP
\fR#include '\&./crc32c_arm64\&.h'\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include '\&./crc32c_internal\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
