.TH "src/crc32c/src/crc32c_prefetch.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crc32c/src/crc32c_prefetch.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcrc32c\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBRequestPrefetch\fP (const uint8_t *address)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
