.TH "CreateWalletDialog" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateWalletDialog
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <createwalletdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreateWalletDialog\fP (QWidget *parent)"
.br
.ti -1c
.RI "virtual \fB~CreateWalletDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetSigners\fP (const std::vector< std::unique_ptr< \fBinterfaces::ExternalSigner\fP > > &signers)"
.br
.ti -1c
.RI "QString \fBwalletName\fP () const"
.br
.ti -1c
.RI "bool \fBisEncryptWalletChecked\fP () const"
.br
.ti -1c
.RI "bool \fBisDisablePrivateKeysChecked\fP () const"
.br
.ti -1c
.RI "bool \fBisMakeBlankWalletChecked\fP () const"
.br
.ti -1c
.RI "bool \fBisExternalSignerChecked\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dialog for creating wallets 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCreateWalletDialog\fP (QWidget * parent)\fR [explicit]\fP"

.SS "~\fBCreateWalletDialog\fP ()\fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool isDisablePrivateKeysChecked () const"

.SS "bool isEncryptWalletChecked () const"

.SS "bool isExternalSignerChecked () const"

.SS "bool isMakeBlankWalletChecked () const"

.SS "void setSigners (const std::vector< std::unique_ptr< \fBinterfaces::ExternalSigner\fP > > & signers)"

.SS "QString walletName () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
