.TH "CRPCCommand" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRPCCommand
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <server\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBActor\fP = std::function<bool(const \fBJSONRPCRequest\fP& request, \fBUniValue\fP& result, bool last_handler)>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCRPCCommand\fP (std::string \fBcategory\fP, std::string \fBname\fP, \fBActor\fP \fBactor\fP, std::vector< std::pair< std::string, bool > > \fBargs\fP, intptr_t \fBunique_id\fP)"
.br
.RI "Constructor taking \fBActor\fP callback supporting multiple handlers\&. "
.ti -1c
.RI "\fBCRPCCommand\fP (std::string \fBcategory\fP, \fBRpcMethodFnType\fP fn)"
.br
.RI "Simplified constructor taking plain \fBRpcMethodFnType\fP function pointer\&. "
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBcategory\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "\fBActor\fP \fBactor\fP"
.br
.ti -1c
.RI "std::vector< std::pair< std::string, bool > > \fBargNames\fP"
.br
.ti -1c
.RI "intptr_t \fBunique_id\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBActor\fP = std::function<bool(const \fBJSONRPCRequest\fP& request, \fBUniValue\fP& result, bool last_handler)>"
RPC method handler reading request and assigning result\&. Should return true if request is fully handled, false if it should be passed on to subsequent handlers\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCRPCCommand\fP (std::string category, std::string name, \fBActor\fP actor, std::vector< std::pair< std::string, bool > > args, intptr_t unique_id)\fR [inline]\fP"

.PP
Constructor taking \fBActor\fP callback supporting multiple handlers\&. 
.SS "\fBCRPCCommand\fP (std::string category, \fBRpcMethodFnType\fP fn)\fR [inline]\fP"

.PP
Simplified constructor taking plain \fBRpcMethodFnType\fP function pointer\&. 
.SH "Field Documentation"
.PP 
.SS "\fBActor\fP actor"

.SS "std::vector<std::pair<std::string, bool> > argNames"
List of method arguments and whether they are named-only\&. Incoming RPC requests contain a "params" field that can either be an array containing unnamed arguments or an object containing named arguments\&. The "argNames" vector is used in the latter case to transform the params object into an array\&. Each argument in "argNames" gets mapped to a unique position in the array, based on the order it is listed, unless the argument is a named-only argument with argNames[x]\&.second set to true\&. Named-only arguments are combined into a JSON object that is appended after other arguments, see transformNamedArguments for details\&. 
.SS "std::string category"

.SS "std::string name"

.SS "intptr_t unique_id"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
