.TH "src/wallet/crypter.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/crypter.h
.SH SYNOPSIS
.br
.PP
\fR#include <serialize\&.h>\fP
.br
\fR#include <support/allocators/secure\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCMasterKey\fP"
.br
.ti -1c
.RI "class \fBCCrypter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.ti -1c
.RI "namespace \fBwallet::wallet_crypto_tests\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< unsigned char, \fBsecure_allocator\fP< unsigned char > > \fBCKeyingMaterial\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBEncryptSecret\fP (const \fBCKeyingMaterial\fP &vMasterKey, const \fBCKeyingMaterial\fP &vchPlaintext, const \fBuint256\fP &nIV, std::vector< unsigned char > &vchCiphertext)"
.br
.ti -1c
.RI "bool \fBDecryptSecret\fP (const \fBCKeyingMaterial\fP &master_key, const std::span< const unsigned char > ciphertext, const \fBuint256\fP &iv, \fBCKeyingMaterial\fP &plaintext)"
.br
.ti -1c
.RI "bool \fBDecryptKey\fP (const \fBCKeyingMaterial\fP &master_key, const std::span< const unsigned char > crypted_secret, const \fBCPubKey\fP &pub_key, \fBCKey\fP &key)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned int \fBWALLET_CRYPTO_KEY_SIZE\fP = 32"
.br
.ti -1c
.RI "const unsigned int \fBWALLET_CRYPTO_SALT_SIZE\fP = 8"
.br
.ti -1c
.RI "const unsigned int \fBWALLET_CRYPTO_IV_SIZE\fP = 16"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
