.TH "CScriptNum" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CScriptNum
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <script\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCScriptNum\fP (const int64_t &n)"
.br
.ti -1c
.RI "\fBCScriptNum\fP (const std::vector< unsigned char > &vch, bool fRequireMinimal, const size_t nMaxNumSize=\fBnDefaultMaxNumSize\fP)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const int64_t &rhs) const"
.br
.ti -1c
.RI "auto \fBoperator<=>\fP (const int64_t &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCScriptNum\fP &rhs) const"
.br
.ti -1c
.RI "auto \fBoperator<=>\fP (const \fBCScriptNum\fP &rhs) const"
.br
.ti -1c
.RI "\fBCScriptNum\fP \fBoperator+\fP (const int64_t &rhs) const"
.br
.ti -1c
.RI "\fBCScriptNum\fP \fBoperator\-\fP (const int64_t &rhs) const"
.br
.ti -1c
.RI "\fBCScriptNum\fP \fBoperator+\fP (const \fBCScriptNum\fP &rhs) const"
.br
.ti -1c
.RI "\fBCScriptNum\fP \fBoperator\-\fP (const \fBCScriptNum\fP &rhs) const"
.br
.ti -1c
.RI "\fBCScriptNum\fP & \fBoperator+=\fP (const \fBCScriptNum\fP &rhs)"
.br
.ti -1c
.RI "\fBCScriptNum\fP & \fBoperator\-=\fP (const \fBCScriptNum\fP &rhs)"
.br
.ti -1c
.RI "\fBCScriptNum\fP \fBoperator&\fP (const int64_t &rhs) const"
.br
.ti -1c
.RI "\fBCScriptNum\fP \fBoperator&\fP (const \fBCScriptNum\fP &rhs) const"
.br
.ti -1c
.RI "\fBCScriptNum\fP & \fBoperator&=\fP (const \fBCScriptNum\fP &rhs)"
.br
.ti -1c
.RI "\fBCScriptNum\fP \fBoperator\-\fP () const"
.br
.ti -1c
.RI "\fBCScriptNum\fP & \fBoperator=\fP (const int64_t &rhs)"
.br
.ti -1c
.RI "\fBCScriptNum\fP & \fBoperator+=\fP (const int64_t &rhs)"
.br
.ti -1c
.RI "\fBCScriptNum\fP & \fBoperator\-=\fP (const int64_t &rhs)"
.br
.ti -1c
.RI "\fBCScriptNum\fP & \fBoperator&=\fP (const int64_t &rhs)"
.br
.ti -1c
.RI "int \fBgetint\fP () const"
.br
.ti -1c
.RI "int64_t \fBGetInt64\fP () const"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBgetvch\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::vector< unsigned char > \fBserialize\fP (const int64_t &value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const size_t \fBnDefaultMaxNumSize\fP = 4"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCScriptNum\fP (const int64_t & n)\fR [inline]\fP, \fR [explicit]\fP"
Numeric opcodes (OP_1ADD, etc) are restricted to operating on 4-byte integers\&. The semantics are subtle, though: operands must be in the range [-2^31 +1\&.\&.\&.2^31 -1], but results may overflow (and are valid as long as they are not used in a subsequent numeric operation)\&. \fBCScriptNum\fP enforces those semantics by storing results as an int64 and allowing out-of-range values to be returned as a vector of bytes but throwing an exception if arithmetic is done or the result is interpreted as an integer\&. 
.SS "\fBCScriptNum\fP (const std::vector< unsigned char > & vch, bool fRequireMinimal, const size_t nMaxNumSize = \fR\fBnDefaultMaxNumSize\fP\fP)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int getint () const\fR [inline]\fP"

.SS "int64_t GetInt64 () const\fR [inline]\fP"

.SS "std::vector< unsigned char > getvch () const\fR [inline]\fP"

.SS "\fBCScriptNum\fP operator& (const \fBCScriptNum\fP & rhs) const\fR [inline]\fP"

.SS "\fBCScriptNum\fP operator& (const int64_t & rhs) const\fR [inline]\fP"

.SS "\fBCScriptNum\fP & operator&= (const \fBCScriptNum\fP & rhs)\fR [inline]\fP"

.SS "\fBCScriptNum\fP & operator&= (const int64_t & rhs)\fR [inline]\fP"

.SS "\fBCScriptNum\fP operator+ (const \fBCScriptNum\fP & rhs) const\fR [inline]\fP"

.SS "\fBCScriptNum\fP operator+ (const int64_t & rhs) const\fR [inline]\fP"

.SS "\fBCScriptNum\fP & operator+= (const \fBCScriptNum\fP & rhs)\fR [inline]\fP"

.SS "\fBCScriptNum\fP & operator+= (const int64_t & rhs)\fR [inline]\fP"

.SS "\fBCScriptNum\fP operator\- () const\fR [inline]\fP"

.SS "\fBCScriptNum\fP operator\- (const \fBCScriptNum\fP & rhs) const\fR [inline]\fP"

.SS "\fBCScriptNum\fP operator\- (const int64_t & rhs) const\fR [inline]\fP"

.SS "\fBCScriptNum\fP & operator\-= (const \fBCScriptNum\fP & rhs)\fR [inline]\fP"

.SS "\fBCScriptNum\fP & operator\-= (const int64_t & rhs)\fR [inline]\fP"

.SS "auto operator<=> (const \fBCScriptNum\fP & rhs) const\fR [inline]\fP"

.SS "auto operator<=> (const int64_t & rhs) const\fR [inline]\fP"

.SS "\fBCScriptNum\fP & operator= (const int64_t & rhs)\fR [inline]\fP"

.SS "bool operator== (const \fBCScriptNum\fP & rhs) const\fR [inline]\fP"

.SS "bool operator== (const int64_t & rhs) const\fR [inline]\fP"

.SS "std::vector< unsigned char > serialize (const int64_t & value)\fR [inline]\fP, \fR [static]\fP"

.SH "Field Documentation"
.PP 
.SS "const size_t nDefaultMaxNumSize = 4\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
