.TH "CScriptWitness" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CScriptWitness
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <script\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCScriptWitness\fP ()=default"
.br
.ti -1c
.RI "bool \fBIsNull\fP () const"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< std::vector< unsigned char > > \fBstack\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCScriptWitness\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool IsNull () const\fR [inline]\fP"

.SS "void SetNull ()\fR [inline]\fP"

.SS "std::string ToString () const"

.SH "Field Documentation"
.PP 
.SS "std::vector<std::vector<unsigned char> > stack"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
