.TH "CSerializeMethodsTestMany" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSerializeMethodsTestMany
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCSerializeMethodsTestSingle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCSerializeMethodsTestMany\fP, obj)"
.br
.ti -1c
.RI "\fBCSerializeMethodsTestSingle\fP ()=default"
.br
.ti -1c
.RI "\fBCSerializeMethodsTestSingle\fP (int intvalin, bool boolvalin, std::string stringvalin, const uint8_t *charstrvalin, const \fBCTransactionRef\fP &txvalin)"
.br
.in -1c

Public Member Functions inherited from \fBCSerializeMethodsTestSingle\fP
.in +1c
.ti -1c
.RI "\fBCSerializeMethodsTestSingle\fP ()=default"
.br
.ti -1c
.RI "\fBCSerializeMethodsTestSingle\fP (int intvalin, bool boolvalin, std::string stringvalin, const uint8_t *charstrvalin, const \fBCTransactionRef\fP &txvalin)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCSerializeMethodsTestSingle\fP, obj)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCSerializeMethodsTestSingle\fP &rhs) const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBCSerializeMethodsTestSingle\fP
.in +1c
.ti -1c
.RI "int \fBintval\fP"
.br
.ti -1c
.RI "bool \fBboolval\fP"
.br
.ti -1c
.RI "std::string \fBstringval\fP"
.br
.ti -1c
.RI "char \fBcharstrval\fP [16]"
.br
.ti -1c
.RI "\fBCTransactionRef\fP \fBtxval\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBCSerializeMethodsTestSingle\fP ()\fR [default]\fP"

.SS "\fBCSerializeMethodsTestSingle\fP (int intvalin, bool boolvalin, std::string stringvalin, const uint8_t * charstrvalin, const \fBCTransactionRef\fP & txvalin)\fR [inline]\fP"

.SS "SERIALIZE_METHODS (\fBCSerializeMethodsTestMany\fP , obj )\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
