.TH "CSHA256" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSHA256
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sha256\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSHA256\fP ()"
.br
.ti -1c
.RI "\fBCSHA256\fP & \fBWrite\fP (const unsigned char *data, size_t len)"
.br
.ti -1c
.RI "void \fBFinalize\fP (unsigned char hash[\fBOUTPUT_SIZE\fP])"
.br
.ti -1c
.RI "\fBCSHA256\fP & \fBReset\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const size_t \fBOUTPUT_SIZE\fP = 32"
.br
.in -1c
.SH "Detailed Description"
.PP 
A hasher class for SHA-256\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCSHA256\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void Finalize (unsigned char hash[OUTPUT_SIZE])"

.SS "\fBCSHA256\fP & Reset ()"

.SS "\fBCSHA256\fP & Write (const unsigned char * data, size_t len)"

.SH "Field Documentation"
.PP 
.SS "const size_t OUTPUT_SIZE = 32\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
