.TH "CThreadInterrupt" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CThreadInterrupt
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <threadinterrupt\&.h>\fP
.PP
Inherited by \fBFuzzedThreadInterrupt\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBClock\fP = std::chrono::steady_clock"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCThreadInterrupt\fP ()"
.br
.ti -1c
.RI "virtual \fB~CThreadInterrupt\fP ()=default"
.br
.ti -1c
.RI "virtual bool \fBinterrupted\fP () const"
.br
.RI "Return true if \fR\fBoperator()()\fP\fP has been called\&. "
.ti -1c
.RI "virtual \fBoperator bool\fP () const"
.br
.RI "An alias for \fR\fBinterrupted()\fP\fP\&. "
.ti -1c
.RI "virtual void \fBoperator()\fP () \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!mut)"
.br
.RI "Interrupt any sleeps\&. After this \fR\fBinterrupted()\fP\fP will return \fRtrue\fP\&. "
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.RI "Reset to an non-interrupted state\&. "
.ti -1c
.RI "virtual bool \fBsleep_for\fP (Clock::duration rel_time) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!mut)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A helper class for interruptible sleeps\&. Calling operator() will interrupt any current sleep, and after that point operator bool() will return true until reset\&.

.PP
This class should not be used in a signal handler\&. It uses thread synchronization primitives that are not safe to use with signals\&. If sending an interrupt from a signal handler is necessary, the \fBSignalInterrupt\fP class can be used instead\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBClock\fP = std::chrono::steady_clock"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCThreadInterrupt\fP ()"

.SS "virtual ~\fBCThreadInterrupt\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool interrupted () const\fR [virtual]\fP"

.PP
Return true if \fR\fBoperator()()\fP\fP has been called\&. 
.PP
Reimplemented in \fBFuzzedThreadInterrupt\fP\&.
.SS "operator bool () const\fR [explicit]\fP, \fR [virtual]\fP"

.PP
An alias for \fR\fBinterrupted()\fP\fP\&. 
.SS "void operator() ()\fR [virtual]\fP"

.PP
Interrupt any sleeps\&. After this \fR\fBinterrupted()\fP\fP will return \fRtrue\fP\&. 
.SS "void reset ()\fR [virtual]\fP"

.PP
Reset to an non-interrupted state\&. 
.SS "bool sleep_for (Clock::duration rel_time)\fR [virtual]\fP"
Sleep for the given duration\&. 
.PP
\fBReturn values\fP
.RS 4
\fItrue\fP The time passed\&. 
.br
\fIfalse\fP The sleep was interrupted\&. 
.RE
.PP

.PP
Reimplemented in \fBFuzzedThreadInterrupt\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
