.TH "CTxMemPool::ChangeSet" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTxMemPool::ChangeSet
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <txmempool\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBTxHandle\fP = \fBCTxMemPool::txiter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChangeSet\fP (\fBCTxMemPool\fP *pool)"
.br
.ti -1c
.RI "\fB~ChangeSet\fP () \fBEXCLUSIVE_LOCKS_REQUIRED\fP(m_pool \-> \fBcs\fP)"
.br
.ti -1c
.RI "\fBChangeSet\fP (const ChangeSet &)=delete"
.br
.ti -1c
.RI "\fBChangeSet\fP & \fBoperator=\fP (const \fBChangeSet\fP &)=delete"
.br
.ti -1c
.RI "\fBTxHandle\fP \fBStageAddition\fP (const \fBCTransactionRef\fP &tx, const \fBCAmount\fP \fBfee\fP, int64_t time, unsigned int entry_height, uint64_t entry_sequence, bool spends_coinbase, int64_t sigops_cost, \fBLockPoints\fP \fBlp\fP)"
.br
.ti -1c
.RI "void \fBStageRemoval\fP (\fBCTxMemPool::txiter\fP \fBit\fP)"
.br
.ti -1c
.RI "const \fBCTxMemPool::setEntries\fP & \fBGetRemovals\fP () const"
.br
.ti -1c
.RI "bool \fBCheckMemPoolPolicyLimits\fP ()"
.br
.ti -1c
.RI "\fBCTxMemPool::setEntries\fP \fBCalculateMemPoolAncestors\fP (\fBTxHandle\fP tx)"
.br
.ti -1c
.RI "std::vector< \fBCTransactionRef\fP > \fBGetAddedTxns\fP () const"
.br
.ti -1c
.RI "\fButil::Result\fP< std::pair< std::vector< \fBFeeFrac\fP >, std::vector< \fBFeeFrac\fP > > > \fBCalculateChunksForRBF\fP ()"
.br
.ti -1c
.RI "size_t \fBGetTxCount\fP () const"
.br
.ti -1c
.RI "const \fBCTransaction\fP & \fBGetAddedTxn\fP (size_t index) const"
.br
.ti -1c
.RI "void \fBApply\fP () \fBEXCLUSIVE_LOCKS_REQUIRED\fP(\fBcs_main\fP)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCTxMemPool\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBTxHandle\fP = \fBCTxMemPool::txiter\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChangeSet (\fBCTxMemPool\fP * pool)\fR [inline]\fP, \fR [explicit]\fP"

.SS "~\fBChangeSet\fP ()\->\fBcs\fP)\fR [inline]\fP"

.SS "ChangeSet (const ChangeSet & )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Apply ()"

.SS "\fButil::Result\fP< std::pair< std::vector< \fBFeeFrac\fP >, std::vector< \fBFeeFrac\fP > > > CalculateChunksForRBF ()"
Calculate the sorted chunks for the old and new mempool relating to the clusters that would be affected by a potential replacement transaction\&.

.PP
\fBReturns\fP
.RS 4
old and new diagram pair respectively, or an error string if the conflicts don't match a calculable topology 
.RE
.PP

.SS "\fBCTxMemPool::setEntries\fP CalculateMemPoolAncestors (\fBTxHandle\fP tx)\fR [inline]\fP"

.SS "bool CheckMemPoolPolicyLimits ()"
Check if any cluster limits are exceeded\&. Returns true if pass, false if fail\&. 
.SS "const \fBCTransaction\fP & GetAddedTxn (size_t index) const\fR [inline]\fP"

.SS "std::vector< \fBCTransactionRef\fP > GetAddedTxns () const\fR [inline]\fP"

.SS "const \fBCTxMemPool::setEntries\fP & GetRemovals () const\fR [inline]\fP"

.SS "size_t GetTxCount () const\fR [inline]\fP"

.SS "\fBChangeSet\fP & operator= (const \fBChangeSet\fP & )\fR [delete]\fP"

.SS "\fBCTxMemPool::ChangeSet::TxHandle\fP StageAddition (const \fBCTransactionRef\fP & tx, const \fBCAmount\fP fee, int64_t time, unsigned int entry_height, uint64_t entry_sequence, bool spends_coinbase, int64_t sigops_cost, \fBLockPoints\fP lp)"

.SS "void StageRemoval (\fBCTxMemPool::txiter\fP it)"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBCTxMemPool\fP\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
