.TH "CValidationInterface" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CValidationInterface
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <validationinterface\&.h>\fP
.PP
Inherited by \fBBaseIndex\fP, \fBBlockValidationStateCatcher\fP, \fBCBlockPolicyEstimator\fP, \fBCZMQNotificationInterface\fP, \fBPeerManager\fP, \fBTestInterface\fP, \fBTestSubscriber\fP, \fBTestSubscriberNoop\fP, and \fBsubmitblock_StateCatcher\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB~CValidationInterface\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBUpdatedBlockTip\fP (const \fBCBlockIndex\fP *pindexNew, const \fBCBlockIndex\fP *pindexFork, bool fInitialDownload)"
.br
.ti -1c
.RI "virtual void \fBActiveTipChange\fP (const \fBCBlockIndex\fP &new_tip, bool is_ibd)"
.br
.ti -1c
.RI "virtual void \fBTransactionAddedToMempool\fP (const \fBNewMempoolTransactionInfo\fP &tx, uint64_t mempool_sequence)"
.br
.ti -1c
.RI "virtual void \fBTransactionRemovedFromMempool\fP (const \fBCTransactionRef\fP &tx, \fBMemPoolRemovalReason\fP reason, uint64_t mempool_sequence)"
.br
.ti -1c
.RI "virtual void \fBMempoolTransactionsRemovedForBlock\fP (const std::vector< \fBRemovedMempoolTransactionInfo\fP > &txs_removed_for_block, unsigned int nBlockHeight)"
.br
.ti -1c
.RI "virtual void \fBBlockConnected\fP (const \fBkernel::ChainstateRole\fP &role, const std::shared_ptr< const \fBCBlock\fP > &block, const \fBCBlockIndex\fP *pindex)"
.br
.ti -1c
.RI "virtual void \fBBlockDisconnected\fP (const std::shared_ptr< const \fBCBlock\fP > &block, const \fBCBlockIndex\fP *pindex)"
.br
.ti -1c
.RI "virtual void \fBChainStateFlushed\fP (const \fBkernel::ChainstateRole\fP &role, const \fBCBlockLocator\fP &locator)"
.br
.ti -1c
.RI "virtual void \fBBlockChecked\fP (const std::shared_ptr< const \fBCBlock\fP > &, const \fBBlockValidationState\fP &)"
.br
.ti -1c
.RI "virtual void \fBNewPoWValidBlock\fP (const \fBCBlockIndex\fP *pindex, const std::shared_ptr< const \fBCBlock\fP > &block)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBValidationSignals\fP"
.br
.ti -1c
.RI "class \fBValidationInterfaceTest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implement this to subscribe to events generated in validation and mempool

.PP
Each \fBCValidationInterface()\fP subscriber will receive event callbacks in the order in which the events were generated by validation and mempool\&. Furthermore, each ValidationInterface() subscriber may assume that callbacks effectively run in a single thread with single-threaded memory consistency\&. That is, for a given ValidationInterface() instantiation, each callback will complete before the next one is invoked\&. This means, for example when a block is connected that the \fBUpdatedBlockTip()\fP callback may depend on an operation performed in the \fBBlockConnected()\fP callback without worrying about explicit synchronization\&. No ordering should be assumed across ValidationInterface() subscribers\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "~\fBCValidationInterface\fP ()\fR [protected]\fP, \fR [default]\fP"
Protected destructor so that instances can only be deleted by derived classes\&. If that restriction is no longer desired, this should be made public and virtual\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual void ActiveTipChange (const \fBCBlockIndex\fP & new_tip, bool is_ibd)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"
Notifies listeners any time the block chain tip changes, synchronously\&. 
.SS "virtual void BlockChecked (const std::shared_ptr< const \fBCBlock\fP > & , const \fBBlockValidationState\fP & )\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"
Notifies listeners of a block validation result\&. If the provided \fBBlockValidationState\fP IsValid, the provided block is guaranteed to be the current best block at the time the callback was generated (not necessarily now)\&. 
.PP
Reimplemented in \fBBlockValidationStateCatcher\fP, \fBsubmitblock_StateCatcher\fP, \fBTestInterface\fP, and \fBTestSubscriberNoop\fP\&.
.SS "virtual void BlockConnected (const \fBkernel::ChainstateRole\fP & role, const std::shared_ptr< const \fBCBlock\fP > & block, const \fBCBlockIndex\fP * pindex)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"
Notifies listeners of a block being connected\&.

.PP
Called on a background thread\&. 
.PP
Reimplemented in \fBBaseIndex\fP, \fBCZMQNotificationInterface\fP, and \fBTestSubscriber\fP\&.
.SS "virtual void BlockDisconnected (const std::shared_ptr< const \fBCBlock\fP > & block, const \fBCBlockIndex\fP * pindex)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"
Notifies listeners of a block being disconnected Provides the block that was disconnected\&.

.PP
Called on a background thread\&. Only called for the active chainstate, since background chainstates should never disconnect blocks\&. 
.PP
Reimplemented in \fBCZMQNotificationInterface\fP, and \fBTestSubscriber\fP\&.
.SS "virtual void ChainStateFlushed (const \fBkernel::ChainstateRole\fP & role, const \fBCBlockLocator\fP & locator)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"
Notifies listeners of the new active block chain on-disk\&.

.PP
Prior to this callback, any updates are not guaranteed to persist on disk (ie clients need to handle shutdown/restart safety by being able to understand when some updates were lost due to unclean shutdown)\&.

.PP
When this callback is invoked, the validation changes done by any prior callback are guaranteed to exist on disk and survive a restart, including an unclean shutdown\&.

.PP
Provides a locator describing the best chain, which is likely useful for storing current state on disk in client DBs\&.

.PP
Called on a background thread\&. 
.PP
Reimplemented in \fBBaseIndex\fP\&.
.SS "virtual void MempoolTransactionsRemovedForBlock (const std::vector< \fBRemovedMempoolTransactionInfo\fP > & txs_removed_for_block, unsigned int nBlockHeight)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCBlockPolicyEstimator\fP\&.
.SS "virtual void NewPoWValidBlock (const \fBCBlockIndex\fP * pindex, const std::shared_ptr< const \fBCBlock\fP > & block)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"
Notifies listeners that a block which builds directly on our current tip has been received and connected to the headers tree, though not validated yet\&. 
.SS "virtual void TransactionAddedToMempool (const \fBNewMempoolTransactionInfo\fP & tx, uint64_t mempool_sequence)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"
Notifies listeners of a transaction having been added to mempool\&.

.PP
Called on a background thread\&. 
.PP
Reimplemented in \fBCBlockPolicyEstimator\fP, and \fBCZMQNotificationInterface\fP\&.
.SS "virtual void TransactionRemovedFromMempool (const \fBCTransactionRef\fP & tx, \fBMemPoolRemovalReason\fP reason, uint64_t mempool_sequence)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"
Notifies listeners of a transaction leaving mempool\&.

.PP
This notification fires for transactions that are removed from the mempool for the following reasons:

.PP
.IP "\(bu" 2
EXPIRY (expired from mempool after -mempoolexpiry hours)
.IP "\(bu" 2
SIZELIMIT (removed in size limiting if the mempool exceeds -maxmempool megabytes)
.IP "\(bu" 2
REORG (removed during a reorg)
.IP "\(bu" 2
CONFLICT (removed because it conflicts with in-block transaction)
.IP "\(bu" 2
REPLACED (removed due to RBF replacement)
.PP

.PP
This does not fire for transactions that are removed from the mempool because they have been included in a block\&. Any client that is interested in transactions removed from the mempool for inclusion in a block can learn about those transactions from the MempoolTransactionsRemovedForBlock notification\&.

.PP
Transactions that are removed from the mempool because they conflict with a transaction in the new block will have TransactionRemovedFromMempool events fired \fIbefore\fP the BlockConnected event is fired\&. If multiple blocks are connected in one step, then the ordering could be:

.PP
.IP "\(bu" 2
TransactionRemovedFromMempool(tx1 from block A)
.IP "\(bu" 2
TransactionRemovedFromMempool(tx2 from block A)
.IP "\(bu" 2
TransactionRemovedFromMempool(tx1 from block B)
.IP "\(bu" 2
TransactionRemovedFromMempool(tx2 from block B)
.IP "\(bu" 2
BlockConnected(A)
.IP "\(bu" 2
BlockConnected(B)
.PP

.PP
Called on a background thread\&. 
.PP
Reimplemented in \fBCBlockPolicyEstimator\fP, and \fBCZMQNotificationInterface\fP\&.
.SS "virtual void UpdatedBlockTip (const \fBCBlockIndex\fP * pindexNew, const \fBCBlockIndex\fP * pindexFork, bool fInitialDownload)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"
Notifies listeners when the block chain tip advances\&.

.PP
When multiple blocks are connected at once, UpdatedBlockTip will be called on the final tip but may not be called on every intermediate tip\&. If the latter behavior is desired, subscribe to \fBBlockConnected()\fP instead\&.

.PP
Called on a background thread\&. Only called for the active chainstate\&. 
.PP
Reimplemented in \fBCZMQNotificationInterface\fP, and \fBTestSubscriber\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBValidationInterfaceTest\fP\fR [friend]\fP"

.SS "friend class \fBValidationSignals\fP\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
