.TH "CVerifyDB" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CVerifyDB
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <validation\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCVerifyDB\fP (\fBkernel::Notifications\fP &notifications)"
.br
.ti -1c
.RI "\fB~CVerifyDB\fP ()"
.br
.ti -1c
.RI "\fBVerifyDBResult\fP \fBVerifyDB\fP (\fBChainstate\fP &chainstate, const \fBConsensus::Params\fP &consensus_params, \fBCCoinsView\fP &coinsview, int nCheckLevel, int nCheckDepth) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(\fBcs_main\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
RAII wrapper for VerifyDB: Verify consistency of the block and coin databases 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCVerifyDB\fP (\fBkernel::Notifications\fP & notifications)\fR [explicit]\fP"

.SS "~\fBCVerifyDB\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBVerifyDBResult\fP VerifyDB (\fBChainstate\fP & chainstate, const \fBConsensus::Params\fP & consensus_params, \fBCCoinsView\fP & coinsview, int nCheckLevel, int nCheckDepth)\fR [nodiscard]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
