.TH "CWallet::ScanResult" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CWallet::ScanResult
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wallet\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBSUCCESS\fP, \fBFAILURE\fP, \fBUSER_ABORT\fP }"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum wallet::CWallet::ScanResult:: { \&.\&.\&. }  \fBstatus\fP = \fBSUCCESS\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBlast_scanned_block\fP"
.br
.ti -1c
.RI "std::optional< int > \fBlast_scanned_height\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBlast_failed_block\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BISUCCESS \fP
.TP
\f(BIFAILURE \fP
.TP
\f(BIUSER_ABORT \fP
.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP last_failed_block"
Height of the most recent block that could not be scanned due to read errors or pruning\&. Will be set if status is FAILURE, unset if status is SUCCESS, and may or may not be set if status is USER_ABORT\&. 
.SS "\fBuint256\fP last_scanned_block"
Hash and height of most recent block that was successfully scanned\&. Unset if no blocks were scanned due to read errors or the chain being empty\&. 
.SS "std::optional<int> last_scanned_height"

.SS "enum  { \&.\&.\&. }  status"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
