.TH "CWallet::AddrBookFilter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CWallet::AddrBookFilter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wallet\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::optional< std::string > \fBm_op_label\fP {std::nullopt}"
.br
.ti -1c
.RI "bool \fBignore_change\fP {true}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool ignore_change {true}"

.SS "std::optional<std::string> m_op_label {std::nullopt}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
