.TH "src/wallet/db.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/db.h
.SH SYNOPSIS
.br
.PP
\fR#include <clientversion\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <support/allocators/secure\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBytePrefix\fP"
.br
.ti -1c
.RI "class \fBDatabaseCursor\fP"
.br
.ti -1c
.RI "class \fBDatabaseBatch\fP"
.br
.ti -1c
.RI "class \fBWalletDatabase\fP"
.br
.ti -1c
.RI "struct \fBDatabaseOptions\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBDatabaseFormat\fP { \fBSQLITE\fP, \fBBERKELEY_RO\fP }"
.br
.ti -1c
.RI "enum class \fBDatabaseStatus\fP { \fBSUCCESS\fP, \fBFAILED_BAD_PATH\fP, \fBFAILED_BAD_FORMAT\fP, \fBFAILED_LEGACY_DISABLED\fP, \fBFAILED_ALREADY_LOADED\fP, \fBFAILED_ALREADY_EXISTS\fP, \fBFAILED_NOT_FOUND\fP, \fBFAILED_CREATE\fP, \fBFAILED_LOAD\fP, \fBFAILED_VERIFY\fP, \fBFAILED_ENCRYPT\fP, \fBFAILED_INVALID_BACKUP_FILE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (\fBBytePrefix\fP a, std::span< const std::byte > b)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (std::span< const std::byte > a, \fBBytePrefix\fP b)"
.br
.ti -1c
.RI "std::vector< std::pair< \fBfs::path\fP, std::string > > \fBListDatabases\fP (const \fBfs::path\fP &wallet_dir)"
.br
.ti -1c
.RI "void \fBReadDatabaseArgs\fP (const \fBArgsManager\fP &\fBargs\fP, \fBDatabaseOptions\fP &options)"
.br
.ti -1c
.RI "std::unique_ptr< \fBWalletDatabase\fP > \fBMakeDatabase\fP (const \fBfs::path\fP &path, const \fBDatabaseOptions\fP &options, \fBDatabaseStatus\fP &status, \fBbilingual_str\fP &error)"
.br
.ti -1c
.RI "\fBfs::path\fP \fBBDBDataFile\fP (const \fBfs::path\fP &wallet_path)"
.br
.ti -1c
.RI "\fBfs::path\fP \fBSQLiteDataFile\fP (const \fBfs::path\fP &path)"
.br
.ti -1c
.RI "bool \fBIsBDBFile\fP (const \fBfs::path\fP &path)"
.br
.ti -1c
.RI "bool \fBIsSQLiteFile\fP (const \fBfs::path\fP &path)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
