.TH "DBOptions" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DBOptions \- User-controlled performance and debug options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <dbwrapper\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBforce_compact\fP = false"
.br
.RI "Compact database on startup\&. "
.in -1c
.SH "Detailed Description"
.PP 
User-controlled performance and debug options\&. 
.SH "Field Documentation"
.PP 
.SS "bool force_compact = false"

.PP
Compact database on startup\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
