.TH "src/test/dbwrapper_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/dbwrapper_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <dbwrapper\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <ranges>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBStringContentsSerializer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (dbwrapper)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (dbwrapper_basic_data)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (dbwrapper_batch)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (dbwrapper_iterator)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (existing_data_no_obfuscate)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (existing_data_reindex)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (iterator_ordering)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (iterator_string_ordering)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (unicodepath)"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::string \fBToString\fP (const \fBT\fP &t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (dbwrapper )"

.SS "BOOST_AUTO_TEST_CASE (dbwrapper_basic_data )"

.SS "BOOST_AUTO_TEST_CASE (dbwrapper_batch )"

.SS "BOOST_AUTO_TEST_CASE (dbwrapper_iterator )"

.SS "BOOST_AUTO_TEST_CASE (existing_data_no_obfuscate )"

.SS "BOOST_AUTO_TEST_CASE (existing_data_reindex )"

.SS "BOOST_AUTO_TEST_CASE (iterator_ordering )"

.SS "BOOST_AUTO_TEST_CASE (iterator_string_ordering )"

.SS "BOOST_AUTO_TEST_CASE (unicodepath )"

.SS "template<typename \fBT\fP> std::string ToString (const \fBT\fP & t)"
Locale-independent version of std::to_string 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
