.TH "src/dbwrapper.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dbwrapper.h
.SH SYNOPSIS
.br
.PP
\fR#include <attributes\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <exception>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBDBOptions\fP"
.br
.RI "User-controlled performance and debug options\&. "
.ti -1c
.RI "struct \fBDBParams\fP"
.br
.RI "Application-specific storage settings\&. "
.ti -1c
.RI "class \fBdbwrapper_error\fP"
.br
.ti -1c
.RI "class \fBCDBBatch\fP"
.br
.ti -1c
.RI "class \fBCDBIterator\fP"
.br
.ti -1c
.RI "class \fBCDBWrapper\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdbwrapper_private\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBObfuscation\fP & \fBGetObfuscation\fP (const \fBCDBWrapper\fP &w)"
.br
.ti -1c
.RI "bool \fBDestroyDB\fP (const std::string &path_str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool DestroyDB (const std::string & path_str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
