.TH "dbwrapper_private" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbwrapper_private
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBObfuscation\fP & \fBGetObfuscation\fP (const \fBCDBWrapper\fP &w)"
.br
.in -1c
.SH "Detailed Description"
.PP 
These should be considered an implementation detail of the specific database\&. 
.SH "Function Documentation"
.PP 
.SS "const \fBObfuscation\fP & GetObfuscation (const \fBCDBWrapper\fP & )"
Work around circular dependency, as well as for testing in dbwrapper_tests\&. Database obfuscation should be considered an implementation detail of the specific database\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
