.TH "DebugLogHelper" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DebugLogHelper
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <logging\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBMatchFn\fP = std::function<bool(const std::string* line)>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDebugLogHelper\fP (std::string message, \fBMatchFn\fP match=[](const std::string *){ return true;})"
.br
.ti -1c
.RI "\fBDebugLogHelper\fP (const \fBDebugLogHelper\fP &)=delete"
.br
.ti -1c
.RI "\fBDebugLogHelper\fP & \fBoperator=\fP (const \fBDebugLogHelper\fP &)=delete"
.br
.ti -1c
.RI "\fB~DebugLogHelper\fP ()"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBMatchFn\fP = std::function<bool(const std::string* line)>"
Custom match checking function\&.

.PP
Invoked with pointers to lines containing matching strings, and with null if check_found() is called without any successful match\&.

.PP
Can return true to enable default \fBDebugLogHelper\fP behavior of: (1) ending search after first successful match, and (2) raising an error in check_found if no match was found Can return false to do the opposite in either case\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBDebugLogHelper\fP (std::string message, \fBMatchFn\fP match = \fR[](const std::string*){ return true; }\fP)\fR [explicit]\fP"

.SS "\fBDebugLogHelper\fP (const \fBDebugLogHelper\fP & )\fR [delete]\fP"

.SS "~\fBDebugLogHelper\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBDebugLogHelper\fP & operator= (const \fBDebugLogHelper\fP & )\fR [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
