.TH "DefaultFormatter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefaultFormatter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <serialize\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream, typename \fBT\fP> static void \fBSer\fP (Stream &s, const \fBT\fP &t)"
.br
.ti -1c
.RI "template<typename Stream, typename \fBT\fP> static void \fBUnser\fP (Stream &s, \fBT\fP &t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Default formatter\&. Serializes objects as themselves\&.

.PP
The vector/prevector serialization code passes this to \fBVectorFormatter\fP to enable reusing that logic\&. It shouldn't be needed elsewhere\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream, typename \fBT\fP> void Ser (Stream & s, const \fBT\fP & t)\fR [inline]\fP, \fR [static]\fP"

.SS "template<typename Stream, typename \fBT\fP> void Unser (Stream & s, \fBT\fP & t)\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
