.TH "DeferringSignatureChecker" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeferringSignatureChecker
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <interpreter\&.h>\fP
.PP
Inherits \fBBaseSignatureChecker\fP\&.
.PP
Inherited by \fBSignatureWeightChecker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeferringSignatureChecker\fP (const \fBBaseSignatureChecker\fP &checker)"
.br
.ti -1c
.RI "bool \fBCheckECDSASignature\fP (const std::vector< unsigned char > &scriptSig, const std::vector< unsigned char > &vchPubKey, const \fBCScript\fP &scriptCode, \fBSigVersion\fP sigversion) const override"
.br
.ti -1c
.RI "bool \fBCheckSchnorrSignature\fP (std::span< const unsigned char > sig, std::span< const unsigned char > pubkey, \fBSigVersion\fP sigversion, \fBScriptExecutionData\fP &execdata, \fBScriptError\fP *serror=nullptr) const override"
.br
.ti -1c
.RI "bool \fBCheckLockTime\fP (const \fBCScriptNum\fP &nLockTime) const override"
.br
.ti -1c
.RI "bool \fBCheckSequence\fP (const \fBCScriptNum\fP &nSequence) const override"
.br
.in -1c

Public Member Functions inherited from \fBBaseSignatureChecker\fP
.in +1c
.ti -1c
.RI "virtual \fB~BaseSignatureChecker\fP ()=default"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBBaseSignatureChecker\fP & \fBm_checker\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBDeferringSignatureChecker\fP (const \fBBaseSignatureChecker\fP & checker)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool CheckECDSASignature (const std::vector< unsigned char > & scriptSig, const std::vector< unsigned char > & vchPubKey, const \fBCScript\fP & scriptCode, \fBSigVersion\fP sigversion) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBBaseSignatureChecker\fP\&.
.PP
Reimplemented in \fBSignatureWeightChecker\fP\&.
.SS "bool CheckLockTime (const \fBCScriptNum\fP & nLockTime) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBBaseSignatureChecker\fP\&.
.SS "bool CheckSchnorrSignature (std::span< const unsigned char > sig, std::span< const unsigned char > pubkey, \fBSigVersion\fP sigversion, \fBScriptExecutionData\fP & execdata, \fBScriptError\fP * serror = \fRnullptr\fP) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBBaseSignatureChecker\fP\&.
.SS "bool CheckSequence (const \fBCScriptNum\fP & nSequence) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBBaseSignatureChecker\fP\&.
.SH "Field Documentation"
.PP 
.SS "const \fBBaseSignatureChecker\fP& m_checker\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
