.TH "src/deploymentinfo.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/deploymentinfo.h
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/params\&.h>\fP
.br
\fR#include <array>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBVBDeploymentInfo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBDeploymentName\fP (\fBConsensus::BuriedDeployment\fP dep)"
.br
.ti -1c
.RI "std::string \fBDeploymentName\fP (\fBConsensus::DeploymentPos\fP pos)"
.br
.ti -1c
.RI "std::optional< \fBConsensus::BuriedDeployment\fP > \fBGetBuriedDeployment\fP (const std::string_view deployment_name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::array< \fBVBDeploymentInfo\fP, \fBConsensus::MAX_VERSION_BITS_DEPLOYMENTS\fP > \fBVersionBitsDeploymentInfo\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string DeploymentName (\fBConsensus::BuriedDeployment\fP dep)"

.SS "std::string DeploymentName (\fBConsensus::DeploymentPos\fP pos)\fR [inline]\fP"

.SS "std::optional< \fBConsensus::BuriedDeployment\fP > GetBuriedDeployment (const std::string_view deployment_name)"

.SH "Variable Documentation"
.PP 
.SS "const std::array<\fBVBDeploymentInfo\fP,\fBConsensus::MAX_VERSION_BITS_DEPLOYMENTS\fP> VersionBitsDeploymentInfo\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
