.TH "DereferencingComparator< T >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DereferencingComparator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <indirectmap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP a, const \fBT\fP b) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class \fBT\fP> bool operator() (const \fBT\fP a, const \fBT\fP b) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
