.TH "DescriptorCache" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DescriptorCache
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <descriptor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCacheParentExtPubKey\fP (uint32_t key_exp_pos, const \fBCExtPubKey\fP &xpub)"
.br
.ti -1c
.RI "bool \fBGetCachedParentExtPubKey\fP (uint32_t key_exp_pos, \fBCExtPubKey\fP &xpub) const"
.br
.ti -1c
.RI "void \fBCacheDerivedExtPubKey\fP (uint32_t key_exp_pos, uint32_t der_index, const \fBCExtPubKey\fP &xpub)"
.br
.ti -1c
.RI "bool \fBGetCachedDerivedExtPubKey\fP (uint32_t key_exp_pos, uint32_t der_index, \fBCExtPubKey\fP &xpub) const"
.br
.ti -1c
.RI "void \fBCacheLastHardenedExtPubKey\fP (uint32_t key_exp_pos, const \fBCExtPubKey\fP &xpub)"
.br
.ti -1c
.RI "bool \fBGetCachedLastHardenedExtPubKey\fP (uint32_t key_exp_pos, \fBCExtPubKey\fP &xpub) const"
.br
.ti -1c
.RI "\fBExtPubKeyMap\fP \fBGetCachedParentExtPubKeys\fP () const"
.br
.ti -1c
.RI "std::unordered_map< uint32_t, \fBExtPubKeyMap\fP > \fBGetCachedDerivedExtPubKeys\fP () const"
.br
.ti -1c
.RI "\fBExtPubKeyMap\fP \fBGetCachedLastHardenedExtPubKeys\fP () const"
.br
.ti -1c
.RI "\fBDescriptorCache\fP \fBMergeAndDiff\fP (const \fBDescriptorCache\fP &other)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCache\fP for single descriptor's derived extended pubkeys 
.SH "Member Function Documentation"
.PP 
.SS "void CacheDerivedExtPubKey (uint32_t key_exp_pos, uint32_t der_index, const \fBCExtPubKey\fP & xpub)"
\fBCache\fP an xpub derived at an index

.PP
\fBParameters\fP
.RS 4
\fIkey_exp_pos\fP Position of the key expression within the descriptor 
.br
\fIder_index\fP Derivation index of the xpub 
.br
\fIxpub\fP The \fBCExtPubKey\fP to cache 
.RE
.PP

.SS "void CacheLastHardenedExtPubKey (uint32_t key_exp_pos, const \fBCExtPubKey\fP & xpub)"
\fBCache\fP a last hardened xpub

.PP
\fBParameters\fP
.RS 4
\fIkey_exp_pos\fP Position of the key expression within the descriptor 
.br
\fIxpub\fP The \fBCExtPubKey\fP to cache 
.RE
.PP

.SS "void CacheParentExtPubKey (uint32_t key_exp_pos, const \fBCExtPubKey\fP & xpub)"
\fBCache\fP a parent xpub

.PP
\fBParameters\fP
.RS 4
\fIkey_exp_pos\fP Position of the key expression within the descriptor 
.br
\fIxpub\fP The \fBCExtPubKey\fP to cache 
.RE
.PP

.SS "bool GetCachedDerivedExtPubKey (uint32_t key_exp_pos, uint32_t der_index, \fBCExtPubKey\fP & xpub) const"
Retrieve a cached xpub derived at an index

.PP
\fBParameters\fP
.RS 4
\fIkey_exp_pos\fP Position of the key expression within the descriptor 
.br
\fIder_index\fP Derivation index of the xpub 
.br
\fIxpub\fP The \fBCExtPubKey\fP to get from cache 
.RE
.PP

.SS "std::unordered_map< uint32_t, \fBExtPubKeyMap\fP > GetCachedDerivedExtPubKeys () const"
Retrieve all cached derived xpubs 
.SS "bool GetCachedLastHardenedExtPubKey (uint32_t key_exp_pos, \fBCExtPubKey\fP & xpub) const"
Retrieve a cached last hardened xpub

.PP
\fBParameters\fP
.RS 4
\fIkey_exp_pos\fP Position of the key expression within the descriptor 
.br
\fIxpub\fP The \fBCExtPubKey\fP to get from cache 
.RE
.PP

.SS "\fBExtPubKeyMap\fP GetCachedLastHardenedExtPubKeys () const"
Retrieve all cached last hardened xpubs 
.SS "bool GetCachedParentExtPubKey (uint32_t key_exp_pos, \fBCExtPubKey\fP & xpub) const"
Retrieve a cached parent xpub

.PP
\fBParameters\fP
.RS 4
\fIkey_exp_pos\fP Position of the key expression within the descriptor 
.br
\fIxpub\fP The \fBCExtPubKey\fP to get from cache 
.RE
.PP

.SS "\fBExtPubKeyMap\fP GetCachedParentExtPubKeys () const"
Retrieve all cached parent xpubs 
.SS "\fBDescriptorCache\fP MergeAndDiff (const \fBDescriptorCache\fP & other)"
Combine another \fBDescriptorCache\fP into this one\&. Returns a cache containing the items from the other cache unknown to current cache 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
