.TH "deserialize_type" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deserialize_type
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <serialize\&.h>\fP
.SH "Detailed Description"
.PP 
Dummy data type to identify deserializing constructors\&.

.PP
By convention, a constructor of a type T with signature

.PP
template <typename Stream> T::T(deserialize_type, Stream& s)

.PP
is a deserializing constructor, which builds the type by deserializing it from s\&. If T contains const fields, this is likely the only way to do so\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
