.TH "src/dummywallet.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dummywallet.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/args\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <walletinitinterface\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDummyWalletInit\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinterfaces\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBWalletLoader\fP > \fBMakeWalletLoader\fP (\fBChain\fP &chain, \fBArgsManager\fP &\fBargs\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBWalletInitInterface\fP & \fBg_wallet_init_interface\fP = \fBDummyWalletInit\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBWalletInitInterface\fP& g_wallet_init_interface = \fBDummyWalletInit\fP()"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
