.TH "DummyWalletInit" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DummyWalletInit
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWalletInitInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBHasWalletSupport\fP () const override"
.br
.ti -1c
.RI "void \fBAddWalletOptions\fP (\fBArgsManager\fP &argsman) const override"
.br
.ti -1c
.RI "bool \fBParameterInteraction\fP () const override"
.br
.ti -1c
.RI "void \fBConstruct\fP (\fBnode::NodeContext\fP &\fBnode\fP) const override"
.br
.in -1c

Public Member Functions inherited from \fBWalletInitInterface\fP
.in +1c
.ti -1c
.RI "virtual \fB~WalletInitInterface\fP ()=default"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AddWalletOptions (\fBArgsManager\fP & argsman) const\fR [override]\fP, \fR [virtual]\fP"
Get wallet help string 
.PP
Implements \fBWalletInitInterface\fP\&.
.SS "void Construct (\fBnode::NodeContext\fP & node) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Add wallets that should be opened to list of chain clients\&. 
.PP
Implements \fBWalletInitInterface\fP\&.
.SS "bool HasWalletSupport () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Is the wallet component enabled 
.PP
Implements \fBWalletInitInterface\fP\&.
.SS "bool ParameterInteraction () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Check wallet parameter interaction 
.PP
Implements \fBWalletInitInterface\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
