.TH "DummyTorControlConnection" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DummyTorControlConnection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTorControlConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDummyTorControlConnection\fP ()"
.br
.ti -1c
.RI "bool \fBConnect\fP (const std::string &, const \fBConnectionCB\fP &, const \fBConnectionCB\fP &)"
.br
.ti -1c
.RI "void \fBDisconnect\fP ()"
.br
.ti -1c
.RI "bool \fBCommand\fP (const std::string &, const \fBReplyHandlerCB\fP &)"
.br
.in -1c

Public Member Functions inherited from \fBTorControlConnection\fP
.in +1c
.ti -1c
.RI "\fBTorControlConnection\fP (struct event_base *base)"
.br
.ti -1c
.RI "\fB~TorControlConnection\fP ()"
.br
.ti -1c
.RI "bool \fBConnect\fP (const std::string &tor_control_center, const \fBConnectionCB\fP &connected, const \fBConnectionCB\fP &disconnected)"
.br
.ti -1c
.RI "void \fBDisconnect\fP ()"
.br
.ti -1c
.RI "bool \fBCommand\fP (const std::string &\fBcmd\fP, const \fBReplyHandlerCB\fP &reply_handler)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBTorControlConnection\fP
.in +1c
.ti -1c
.RI "typedef std::function< void(\fBTorControlConnection\fP &)> \fBConnectionCB\fP"
.br
.ti -1c
.RI "typedef std::function< void(\fBTorControlConnection\fP &, const \fBTorControlReply\fP &)> \fBReplyHandlerCB\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBDummyTorControlConnection\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool Command (const std::string & , const \fBReplyHandlerCB\fP & )\fR [inline]\fP"

.SS "bool Connect (const std::string & , const \fBConnectionCB\fP & , const \fBConnectionCB\fP & )\fR [inline]\fP"

.SS "void Disconnect ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
