.TH "DynSock::Pipes" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynSock::Pipes
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <net\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPipe\fP \fBrecv\fP"
.br
.ti -1c
.RI "\fBPipe\fP \fBsend\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBPipe\fP recv"

.SS "\fBPipe\fP send"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
