.TH "ecmult_multi_data" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecmult_multi_data
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsecp256k1_scalar\fP * \fBsc\fP"
.br
.ti -1c
.RI "\fBsecp256k1_ge\fP * \fBpt\fP"
.br
.ti -1c
.RI "\fBsecp256k1_scalar\fP \fBsc\fP [2]"
.br
.ti -1c
.RI "\fBsecp256k1_ge\fP \fBpt\fP [2]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsecp256k1_ge\fP* pt"

.SS "\fBsecp256k1_ge\fP pt[2]"

.SS "\fBsecp256k1_scalar\fP* sc"

.SS "\fBsecp256k1_scalar\fP sc[2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
