.TH "EditAddressDialog" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditAddressDialog
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <editaddressdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBNewSendingAddress\fP, \fBEditReceivingAddress\fP, \fBEditSendingAddress\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBaccept\fP () override"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditAddressDialog\fP (\fBMode\fP mode, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~EditAddressDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBAddressTableModel\fP *model)"
.br
.ti -1c
.RI "void \fBloadRow\fP (int row)"
.br
.ti -1c
.RI "QString \fBgetAddress\fP () const"
.br
.ti -1c
.RI "void \fBsetAddress\fP (const QString &address)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dialog for editing an address and associated information\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINewSendingAddress \fP
.TP
\f(BIEditReceivingAddress \fP
.TP
\f(BIEditSendingAddress \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEditAddressDialog\fP (\fBMode\fP mode, QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SS "~\fBEditAddressDialog\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void accept ()\fR [override]\fP, \fR [slot]\fP"

.SS "QString getAddress () const"

.SS "void loadRow (int row)"

.SS "void setAddress (const QString & address)"

.SS "void setModel (\fBAddressTableModel\fP * model)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
