.TH "ElapseSteady" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElapseSteady
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <time\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElapseSteady\fP ()"
.br
.ti -1c
.RI "void \fBoperator()\fP (std::chrono::milliseconds d)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "MockableSteadyClock::mock_time_point::duration \fBt\fP {\fBMockableSteadyClock::INITIAL_MOCK_TIME\fP}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBElapseSteady\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void operator() (std::chrono::milliseconds d)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "MockableSteadyClock::mock_time_point::duration t {\fBMockableSteadyClock::INITIAL_MOCK_TIME\fP}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
