.TH "ellswift_xdh_test" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ellswift_xdh_test
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tests_impl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBpriv_ours\fP [32]"
.br
.ti -1c
.RI "unsigned char \fBellswift_ours\fP [64]"
.br
.ti -1c
.RI "unsigned char \fBellswift_theirs\fP [64]"
.br
.ti -1c
.RI "int \fBinitiating\fP"
.br
.ti -1c
.RI "unsigned char \fBshared_secret\fP [32]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char ellswift_ours[64]"

.SS "unsigned char ellswift_theirs[64]"

.SS "int initiating"

.SS "unsigned char priv_ours[32]"

.SS "unsigned char shared_secret[32]"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
