.TH "ellswift_xswiftec_inv_test" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ellswift_xswiftec_inv_test
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tests_impl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBenc_bitmap\fP"
.br
.ti -1c
.RI "\fBsecp256k1_fe\fP \fBu\fP"
.br
.ti -1c
.RI "\fBsecp256k1_fe\fP \fBx\fP"
.br
.ti -1c
.RI "\fBsecp256k1_fe\fP \fBencs\fP [8]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int enc_bitmap"

.SS "\fBsecp256k1_fe\fP encs[8]"

.SS "\fBsecp256k1_fe\fP u"

.SS "\fBsecp256k1_fe\fP x"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
