.TH "src/compat/endian.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/compat/endian.h
.SH SYNOPSIS
.br
.PP
\fR#include <compat/byteswap\&.h>\fP
.br
\fR#include <bit>\fP
.br
\fR#include <cstdint>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint16_t \fBhtobe16_internal\fP (uint16_t host_16bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint16_t \fBhtole16_internal\fP (uint16_t host_16bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint16_t \fBbe16toh_internal\fP (uint16_t big_endian_16bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint16_t \fBle16toh_internal\fP (uint16_t little_endian_16bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint32_t \fBhtobe32_internal\fP (uint32_t host_32bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint32_t \fBhtole32_internal\fP (uint32_t host_32bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint32_t \fBbe32toh_internal\fP (uint32_t big_endian_32bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint32_t \fBle32toh_internal\fP (uint32_t little_endian_32bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint64_t \fBhtobe64_internal\fP (uint64_t host_64bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint64_t \fBhtole64_internal\fP (uint64_t host_64bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint64_t \fBbe64toh_internal\fP (uint64_t big_endian_64bits)"
.br
.ti -1c
.RI "\fBBSWAP_CONSTEXPR\fP uint64_t \fBle64toh_internal\fP (uint64_t little_endian_64bits)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBBSWAP_CONSTEXPR\fP uint16_t be16toh_internal (uint16_t big_endian_16bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint32_t be32toh_internal (uint32_t big_endian_32bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint64_t be64toh_internal (uint64_t big_endian_64bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint16_t htobe16_internal (uint16_t host_16bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint32_t htobe32_internal (uint32_t host_32bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint64_t htobe64_internal (uint64_t host_64bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint16_t htole16_internal (uint16_t host_16bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint32_t htole32_internal (uint32_t host_32bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint64_t htole64_internal (uint64_t host_64bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint16_t le16toh_internal (uint16_t little_endian_16bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint32_t le32toh_internal (uint32_t little_endian_32bits)\fR [inline]\fP"

.SS "\fBBSWAP_CONSTEXPR\fP uint64_t le64toh_internal (uint64_t little_endian_64bits)\fR [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
