.TH "Epoch::Guard" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Epoch::Guard
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <epochguard\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGuard\fP (\fBEpoch\fP &epoch) \fBEXCLUSIVE_LOCK_FUNCTION\fP(epoch)"
.br
.ti -1c
.RI "\fB~Guard\fP () \fBUNLOCK_FUNCTION\fP()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Guard (\fBEpoch\fP & epoch)\fR [inline]\fP, \fR [explicit]\fP"

.SS "~\fBGuard\fP ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
