.TH "Epoch::Marker" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Epoch::Marker
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <epochguard\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarker\fP ()=default"
.br
.ti -1c
.RI "\fBMarker\fP (const Marker &)=default"
.br
.ti -1c
.RI "\fBMarker\fP (Marker &&)=default"
.br
.ti -1c
.RI "\fBMarker\fP & \fBoperator=\fP (\fBMarker\fP &&)=default"
.br
.ti -1c
.RI "\fB~Marker\fP ()=default"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBEpoch\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Marker ()\fR [default]\fP"

.SS "Marker (const Marker & )\fR [default]\fP"

.SS "Marker (Marker && )\fR [default]\fP"

.SS "~\fBMarker\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBMarker\fP & operator= (\fBMarker\fP && )\fR [default]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBEpoch\fP\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
