.TH "src/util/epochguard.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/epochguard.h
.SH SYNOPSIS
.br
.PP
\fR#include <threadsafety\&.h>\fP
.br
\fR#include <util/macros\&.h>\fP
.br
\fR#include <cassert>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBEpoch\fP"
.br
.ti -1c
.RI "class \fBEpoch::Marker\fP"
.br
.ti -1c
.RI "class \fBEpoch::Guard\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWITH_FRESH_EPOCH\fP(epoch)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define WITH_FRESH_EPOCH( epoch)"
\fBValue:\fP
.nf
const Epoch::Guard UNIQUE_NAME(epoch_guard_)(epoch)
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
