.TH "EraseParallelTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EraseParallelTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBasicTestingSetup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \fBCache\fP> void \fBtest_cache_erase_parallel\fP (size_t megabytes)"
.br
.in -1c

Public Member Functions inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "void \fBSeedRandomForTest\fP (\fBSeedRand\fP seed)"
.br
.ti -1c
.RI "\fBBasicTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~BasicTestingSetup\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Data Fields inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "\fButil::SignalInterrupt\fP \fBm_interrupt\fP"
.br
.ti -1c
.RI "\fBnode::NodeContext\fP \fBm_node\fP"
.br
.ti -1c
.RI "\fBFastRandomContext\fP \fBm_rng\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_root\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_lock\fP"
.br
.ti -1c
.RI "bool \fBm_has_custom_datadir\fP {false}"
.br
.ti -1c
.RI "\fBArgsManager\fP \fBm_args\fP"
.br
.RI "Test-specific arguments and settings\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBCache\fP> void test_cache_erase_parallel (size_t megabytes)\fR [inline]\fP"
We make a copy of the hashes because future optimizations of the cuckoocache may overwrite the inserted element, so the test is "future proofed"\&.

.PP
Grab lock to make sure we release inserts

.PP
Insert the first half

.PP
Spin up 3 threads to run contains with erase\&.

.PP
Erase the first quarter

.PP
Each thread is emplaced with x copy-by-value

.PP
Wait for all threads to finish

.PP
Grab lock to make sure we observe erases

.PP
Insert the second half

.PP
elements that we marked erased but that are still there

.PP
elements that we did not erase but are older

.PP
elements that were most recently inserted

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
