.TH "EstimatorBucket" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EstimatorBucket
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <block_policy_estimator\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBstart\fP = \-1"
.br
.ti -1c
.RI "double \fBend\fP = \-1"
.br
.ti -1c
.RI "double \fBwithinTarget\fP = 0"
.br
.ti -1c
.RI "double \fBtotalConfirmed\fP = 0"
.br
.ti -1c
.RI "double \fBinMempool\fP = 0"
.br
.ti -1c
.RI "double \fBleftMempool\fP = 0"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double end = \-1"

.SS "double inMempool = 0"

.SS "double leftMempool = 0"

.SS "double start = \-1"

.SS "double totalConfirmed = 0"

.SS "double withinTarget = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
