.TH "EstimationResult" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EstimationResult
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <block_policy_estimator\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEstimatorBucket\fP \fBpass\fP"
.br
.ti -1c
.RI "\fBEstimatorBucket\fP \fBfail\fP"
.br
.ti -1c
.RI "double \fBdecay\fP = 0"
.br
.ti -1c
.RI "unsigned int \fBscale\fP = 0"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double decay = 0"

.SS "\fBEstimatorBucket\fP fail"

.SS "\fBEstimatorBucket\fP pass"

.SS "unsigned int scale = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
