.TH "src/ipc/libmultiprocess/example/example.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc/libmultiprocess/example/example.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <init\&.capnp\&.h>\fP
.br
\fR#include <init\&.capnp\&.proxy\&.h>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <filesystem>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <future>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <kj/async\&.h>\fP
.br
\fR#include <kj/common\&.h>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <mp/proxy\-io\&.h>\fP
.br
\fR#include <mp/util\&.h>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <string>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <tuple>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
