.TH "src/minisketch/doc/example.c" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/minisketch/doc/example.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <assert\&.h>\fP
.br
\fR#include '\&.\&./include/minisketch\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
