.TH "src/wallet/external_signer_scriptpubkeyman.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/external_signer_scriptpubkeyman.h
.SH SYNOPSIS
.br
.PP
\fR#include <wallet/scriptpubkeyman\&.h>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <util/result\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBExternalSignerScriptPubKeyMan\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
