.TH "src/rpc/external_signer.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rpc/external_signer.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <common/system\&.h>\fP
.br
\fR#include <external_signer\&.h>\fP
.br
\fR#include <rpc/protocol\&.h>\fP
.br
\fR#include <rpc/server\&.h>\fP
.br
\fR#include <rpc/util\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
