.TH "ExternalSigner" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSigner
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <external_signer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalSigner\fP (const std::string &\fBcommand\fP, const std::string chain, const std::string &fingerprint, const std::string \fBname\fP)"
.br
.ti -1c
.RI "\fBUniValue\fP \fBDisplayAddress\fP (const std::string &descriptor) const"
.br
.ti -1c
.RI "\fBUniValue\fP \fBGetDescriptors\fP (const int account)"
.br
.ti -1c
.RI "bool \fBSignTransaction\fP (\fBPartiallySignedTransaction\fP &psbt, std::string &error)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBEnumerate\fP (const std::string &\fBcommand\fP, std::vector< \fBExternalSigner\fP > &signers, const std::string chain)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBm_fingerprint\fP"
.br
.RI "Master key fingerprint of the signer\&. "
.ti -1c
.RI "std::string \fBm_name\fP"
.br
.RI "Name of signer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Enables interaction with an external signing device or service, such as a hardware wallet\&. See doc/external-signer\&.md 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBExternalSigner\fP (const std::string & command, const std::string chain, const std::string & fingerprint, const std::string name)"

.PP
\fBParameters\fP
.RS 4
\fIcommand\fP the command which handles interaction with the external signer 
.br
\fIfingerprint\fP master key fingerprint of the signer 
.br
\fIchain\fP "main", "test", "regtest" or "signet" 
.br
\fIname\fP device name 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBUniValue\fP DisplayAddress (const std::string & descriptor) const"
Display address on the device\&. Calls \fR<\fBcommand\fP> displayaddress --desc <descriptor>\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIdescriptor\fP \fBDescriptor\fP specifying which address to display\&. Must include a public key or xpub, as well as key origin\&. 
.RE
.PP

.SS "bool Enumerate (const std::string & command, std::vector< \fBExternalSigner\fP > & signers, const std::string chain)\fR [static]\fP"
Obtain a list of signers\&. Calls \fR<\fBcommand\fP> enumerate\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP the command which handles interaction with the external signer 
.br
\fIsigners\fP vector to which new signers (with a unique master key fingerprint) are added 
.br
\fIchain\fP "main", "test", "regtest" or "signet" 
.RE
.PP
\fBReturns\fP
.RS 4
success 
.RE
.PP

.SS "\fBUniValue\fP GetDescriptors (const int account)"
Get receive and change \fBDescriptor(s)\fP from device for a given account\&. Calls \fR<\fBcommand\fP> getdescriptors --account <account>\fP 
.PP
\fBParameters\fP
.RS 4
\fIaccount\fP which BIP32 account to use (e\&.g\&. \fRm/44'/0'/account'\fP) 
.RE
.PP
\fBReturns\fP
.RS 4
see doc/external-signer\&.md 
.RE
.PP

.SS "bool SignTransaction (\fBPartiallySignedTransaction\fP & psbt, std::string & error)"
Sign \fBPartiallySignedTransaction\fP on the device\&. Calls \fR<\fBcommand\fP> signtransaction\fP and passes the PSBT via stdin\&. 
.PP
\fBParameters\fP
.RS 4
\fIpsbt\fP \fBPartiallySignedTransaction\fP to be signed 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "std::string m_fingerprint"

.PP
Master key fingerprint of the signer\&. 
.SS "std::string m_name"

.PP
Name of signer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
