.TH "src/wallet/feebumper.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/feebumper.h
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/consensus\&.h>\fP
.br
\fR#include <script/interpreter\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSignatureWeights\fP"
.br
.ti -1c
.RI "class \fBSignatureWeightChecker\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.ti -1c
.RI "namespace \fBwallet::feebumper\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBResult\fP { \fBOK\fP, \fBINVALID_ADDRESS_OR_KEY\fP, \fBINVALID_REQUEST\fP, \fBINVALID_PARAMETER\fP, \fBWALLET_ERROR\fP, \fBMISC_ERROR\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBTransactionCanBeBumped\fP (const \fBCWallet\fP &\fBwallet\fP, const \fBTxid\fP &txid)"
.br
.RI "Return whether transaction can be bumped\&. "
.ti -1c
.RI "\fBResult\fP \fBCreateRateBumpTransaction\fP (\fBCWallet\fP &\fBwallet\fP, const \fBTxid\fP &txid, const \fBCCoinControl\fP &coin_control, std::vector< \fBbilingual_str\fP > &errors, \fBCAmount\fP &old_fee, \fBCAmount\fP &new_fee, \fBCMutableTransaction\fP &mtx, bool require_mine, const std::vector< \fBCTxOut\fP > &outputs, std::optional< uint32_t > original_change_index)"
.br
.ti -1c
.RI "bool \fBSignTransaction\fP (\fBCWallet\fP &\fBwallet\fP, \fBCMutableTransaction\fP &mtx)"
.br
.ti -1c
.RI "\fBResult\fP \fBCommitTransaction\fP (\fBCWallet\fP &\fBwallet\fP, const \fBTxid\fP &txid, \fBCMutableTransaction\fP &&mtx, std::vector< \fBbilingual_str\fP > &errors, \fBTxid\fP &bumped_txid)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
