.TH "src/wallet/feebumper.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/feebumper.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/system\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <interfaces/chain\&.h>\fP
.br
\fR#include <policy/fees/block_policy_estimator\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <util/moneystr\&.h>\fP
.br
\fR#include <util/rbf\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <wallet/coincontrol\&.h>\fP
.br
\fR#include <wallet/feebumper\&.h>\fP
.br
\fR#include <wallet/fees\&.h>\fP
.br
\fR#include <wallet/receive\&.h>\fP
.br
\fR#include <wallet/spend\&.h>\fP
.br
\fR#include <wallet/wallet\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.ti -1c
.RI "namespace \fBwallet::feebumper\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBTransactionCanBeBumped\fP (const \fBCWallet\fP &\fBwallet\fP, const \fBTxid\fP &txid)"
.br
.RI "Return whether transaction can be bumped\&. "
.ti -1c
.RI "\fBResult\fP \fBCreateRateBumpTransaction\fP (\fBCWallet\fP &\fBwallet\fP, const \fBTxid\fP &txid, const \fBCCoinControl\fP &coin_control, std::vector< \fBbilingual_str\fP > &errors, \fBCAmount\fP &old_fee, \fBCAmount\fP &new_fee, \fBCMutableTransaction\fP &mtx, bool require_mine, const std::vector< \fBCTxOut\fP > &outputs, std::optional< uint32_t > original_change_index)"
.br
.ti -1c
.RI "bool \fBSignTransaction\fP (\fBCWallet\fP &\fBwallet\fP, \fBCMutableTransaction\fP &mtx)"
.br
.ti -1c
.RI "\fBResult\fP \fBCommitTransaction\fP (\fBCWallet\fP &\fBwallet\fP, const \fBTxid\fP &txid, \fBCMutableTransaction\fP &&mtx, std::vector< \fBbilingual_str\fP > &errors, \fBTxid\fP &bumped_txid)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
