.TH "FeeCalculation" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FeeCalculation
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <block_policy_estimator\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEstimationResult\fP \fBest\fP"
.br
.ti -1c
.RI "\fBFeeReason\fP \fBreason\fP = \fBFeeReason::NONE\fP"
.br
.ti -1c
.RI "int \fBdesiredTarget\fP = 0"
.br
.ti -1c
.RI "int \fBreturnedTarget\fP = 0"
.br
.ti -1c
.RI "unsigned int \fBbest_height\fP {0}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned int best_height {0}"

.SS "int desiredTarget = 0"

.SS "\fBEstimationResult\fP est"

.SS "\fBFeeReason\fP reason = \fBFeeReason::NONE\fP"

.SS "int returnedTarget = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
