.TH "src/policy/feerate.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/policy/feerate.h
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <util/feefrac\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br
\fR#include <type_traits>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCFeeRate\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBFeeEstimateMode\fP { \fBUNSET\fP, \fBECONOMICAL\fP, \fBCONSERVATIVE\fP, \fBBTC_KVB\fP, \fBSAT_VB\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBCURRENCY_UNIT\fP = 'BTC'"
.br
.ti -1c
.RI "const std::string \fBCURRENCY_ATOM\fP = 'sat'"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBFeeEstimateMode\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIUNSET \fP
Use default settings based on other criteria\&. 
.TP
\f(BIECONOMICAL \fP
Force estimateSmartFee to use non-conservative estimates\&. 
.TP
\f(BICONSERVATIVE \fP
Force estimateSmartFee to use conservative estimates\&. 
.TP
\f(BIBTC_KVB \fP
Use BTC/kvB fee rate unit\&. 
.TP
\f(BISAT_VB \fP
Use sat/vB fee rate unit\&. 
.SH "Variable Documentation"
.PP 
.SS "const std::string CURRENCY_ATOM = 'sat'"

.SS "const std::string CURRENCY_UNIT = 'BTC'"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
