.TH "src/wallet/fees.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/fees.h
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/amount\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCAmount\fP \fBGetRequiredFee\fP (const \fBCWallet\fP &\fBwallet\fP, unsigned int nTxBytes)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetMinimumFee\fP (const \fBCWallet\fP &\fBwallet\fP, unsigned int nTxBytes, const \fBCCoinControl\fP &coin_control, \fBFeeCalculation\fP *feeCalc)"
.br
.ti -1c
.RI "\fBCFeeRate\fP \fBGetRequiredFeeRate\fP (const \fBCWallet\fP &\fBwallet\fP)"
.br
.ti -1c
.RI "\fBCFeeRate\fP \fBGetMinimumFeeRate\fP (const \fBCWallet\fP &\fBwallet\fP, const \fBCCoinControl\fP &coin_control, \fBFeeCalculation\fP *feeCalc)"
.br
.ti -1c
.RI "\fBCFeeRate\fP \fBGetDiscardRate\fP (const \fBCWallet\fP &\fBwallet\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
