.TH "src/leveldb/include/leveldb/filter_policy.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/include/leveldb/filter_policy.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include 'leveldb/export\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFilterPolicy\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLEVELDB_EXPORT\fP const \fBFilterPolicy\fP * \fBNewBloomFilterPolicy\fP (int bits_per_key)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
