.TH "src/flatfile.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/flatfile.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBFlatFilePos\fP"
.br
.ti -1c
.RI "class \fBFlatFileSeq\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
