.TH "FlatFilePos" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatFilePos
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <flatfile\&.h>\fP
.PP
Inherited by \fBCDiskTxPos\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBFlatFilePos\fP, obj)"
.br
.ti -1c
.RI "\fBFlatFilePos\fP ()=default"
.br
.ti -1c
.RI "\fBFlatFilePos\fP (int32_t nFileIn, uint32_t nPosIn)"
.br
.ti -1c
.RI "bool \fBIsNull\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBnFile\fP {\-1}"
.br
.ti -1c
.RI "uint32_t \fBnPos\fP {0}"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBFlatFilePos\fP &a, const \fBFlatFilePos\fP &b)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFlatFilePos\fP ()\fR [default]\fP"

.SS "\fBFlatFilePos\fP (int32_t nFileIn, uint32_t nPosIn)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool IsNull () const\fR [inline]\fP"

.SS "SERIALIZE_METHODS (\fBFlatFilePos\fP , obj )\fR [inline]\fP"

.SS "std::string ToString () const"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "bool operator== (const \fBFlatFilePos\fP & a, const \fBFlatFilePos\fP & b)\fR [friend]\fP"

.SH "Field Documentation"
.PP 
.SS "int32_t nFile {\-1}"

.SS "uint32_t nPos {0}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
