.TH "src/test/flatfile_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/flatfile_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <clientversion\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <flatfile\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (flatfile_filename)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (flatfile_open)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (flatfile_allocate)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (flatfile_flush)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (flatfile_allocate )"

.SS "BOOST_AUTO_TEST_CASE (flatfile_filename )"

.SS "BOOST_AUTO_TEST_CASE (flatfile_flush )"

.SS "BOOST_AUTO_TEST_CASE (flatfile_open )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
