.TH "src/ipc/libmultiprocess/test/mp/test/foo.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc/libmultiprocess/test/mp/test/foo.h
.SH SYNOPSIS
.br
.PP
\fR#include <cassert>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <map>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <string>\fP
.br
\fR#include <set>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBFooStruct\fP"
.br
.ti -1c
.RI "struct \fBFooCustom\fP"
.br
.ti -1c
.RI "struct \fBFooEmpty\fP"
.br
.ti -1c
.RI "struct \fBFooMessage\fP"
.br
.ti -1c
.RI "struct \fBFooMutable\fP"
.br
.ti -1c
.RI "class \fBFooCallback\fP"
.br
.ti -1c
.RI "class \fBExtendedCallback\fP"
.br
.ti -1c
.RI "class \fBFooImplementation\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmp\fP"
.br
.RI "Functions to serialize / deserialize common bitcoin types\&. "
.ti -1c
.RI "namespace \fBmp::test\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBFooEnum\fP : uint8_t { \fBONE\fP = 1, \fBTWO\fP = 2 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
