.TH "FooImplementation" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FooImplementation
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ipc_test\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBadd\fP (int a, int b)"
.br
.ti -1c
.RI "\fBCOutPoint\fP \fBpassOutPoint\fP (\fBCOutPoint\fP o)"
.br
.ti -1c
.RI "\fBUniValue\fP \fBpassUniValue\fP (\fBUniValue\fP v)"
.br
.ti -1c
.RI "\fBCTransactionRef\fP \fBpassTransaction\fP (\fBCTransactionRef\fP t)"
.br
.ti -1c
.RI "std::vector< char > \fBpassVectorChar\fP (std::vector< char > v)"
.br
.ti -1c
.RI "\fBBlockValidationState\fP \fBpassBlockState\fP (\fBBlockValidationState\fP s)"
.br
.ti -1c
.RI "\fBCScript\fP \fBpassScript\fP (\fBCScript\fP s)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int add (int a, int b)\fR [inline]\fP"

.SS "\fBBlockValidationState\fP passBlockState (\fBBlockValidationState\fP s)\fR [inline]\fP"

.SS "\fBCOutPoint\fP passOutPoint (\fBCOutPoint\fP o)\fR [inline]\fP"

.SS "\fBCScript\fP passScript (\fBCScript\fP s)\fR [inline]\fP"

.SS "\fBCTransactionRef\fP passTransaction (\fBCTransactionRef\fP t)\fR [inline]\fP"

.SS "\fBUniValue\fP passUniValue (\fBUniValue\fP v)\fR [inline]\fP"

.SS "std::vector< char > passVectorChar (std::vector< char > v)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
