.TH "src/leveldb/table/format.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/table/format.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'leveldb/slice\&.h'\fP
.br
\fR#include 'leveldb/status\&.h'\fP
.br
\fR#include 'leveldb/table_builder\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBlockHandle\fP"
.br
.ti -1c
.RI "class \fBFooter\fP"
.br
.ti -1c
.RI "struct \fBBlockContents\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBStatus\fP \fBReadBlock\fP (\fBRandomAccessFile\fP *file, const \fBReadOptions\fP &options, const \fBBlockHandle\fP &handle, \fBBlockContents\fP *result)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
