.TH "FoundBlock" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FoundBlock
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <chain\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFoundBlock\fP & \fBhash\fP (\fBuint256\fP &hash)"
.br
.ti -1c
.RI "\fBFoundBlock\fP & \fBheight\fP (int &height)"
.br
.ti -1c
.RI "\fBFoundBlock\fP & \fBtime\fP (int64_t &time)"
.br
.ti -1c
.RI "\fBFoundBlock\fP & \fBmaxTime\fP (int64_t &max_time)"
.br
.ti -1c
.RI "\fBFoundBlock\fP & \fBmtpTime\fP (int64_t &mtp_time)"
.br
.ti -1c
.RI "\fBFoundBlock\fP & \fBinActiveChain\fP (bool &in_active_chain)"
.br
.RI "Return whether block is in the active (most-work) chain\&. "
.ti -1c
.RI "\fBFoundBlock\fP & \fBlocator\fP (\fBCBlockLocator\fP &locator)"
.br
.RI "Return locator if block is in the active chain\&. "
.ti -1c
.RI "\fBFoundBlock\fP & \fBnextBlock\fP (const \fBFoundBlock\fP &next_block)"
.br
.RI "Return next block in the active chain if current block is in the active chain\&. "
.ti -1c
.RI "\fBFoundBlock\fP & \fBdata\fP (\fBCBlock\fP &data)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint256\fP * \fBm_hash\fP = nullptr"
.br
.ti -1c
.RI "int * \fBm_height\fP = nullptr"
.br
.ti -1c
.RI "int64_t * \fBm_time\fP = nullptr"
.br
.ti -1c
.RI "int64_t * \fBm_max_time\fP = nullptr"
.br
.ti -1c
.RI "int64_t * \fBm_mtp_time\fP = nullptr"
.br
.ti -1c
.RI "bool * \fBm_in_active_chain\fP = nullptr"
.br
.ti -1c
.RI "\fBCBlockLocator\fP * \fBm_locator\fP = nullptr"
.br
.ti -1c
.RI "const \fBFoundBlock\fP * \fBm_next_block\fP = nullptr"
.br
.ti -1c
.RI "\fBCBlock\fP * \fBm_data\fP = nullptr"
.br
.ti -1c
.RI "bool \fBfound\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper for findBlock to selectively return pieces of block data\&. If block is found, data will be returned by setting specified output variables\&. If block is not found, output variables will keep their previous values\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBFoundBlock\fP & data (\fBCBlock\fP & data)\fR [inline]\fP"
Read block data from disk\&. If the block exists but doesn't have data (for example due to pruning), the \fBCBlock\fP variable will be set to null\&. 
.SS "\fBFoundBlock\fP & hash (\fBuint256\fP & hash)\fR [inline]\fP"

.SS "\fBFoundBlock\fP & height (int & height)\fR [inline]\fP"

.SS "\fBFoundBlock\fP & inActiveChain (bool & in_active_chain)\fR [inline]\fP"

.PP
Return whether block is in the active (most-work) chain\&. 
.SS "\fBFoundBlock\fP & locator (\fBCBlockLocator\fP & locator)\fR [inline]\fP"

.PP
Return locator if block is in the active chain\&. 
.SS "\fBFoundBlock\fP & maxTime (int64_t & max_time)\fR [inline]\fP"

.SS "\fBFoundBlock\fP & mtpTime (int64_t & mtp_time)\fR [inline]\fP"

.SS "\fBFoundBlock\fP & nextBlock (const \fBFoundBlock\fP & next_block)\fR [inline]\fP"

.PP
Return next block in the active chain if current block is in the active chain\&. 
.SS "\fBFoundBlock\fP & time (int64_t & time)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "bool found = false\fR [mutable]\fP"

.SS "\fBCBlock\fP* m_data = nullptr"

.SS "\fBuint256\fP* m_hash = nullptr"

.SS "int* m_height = nullptr"

.SS "bool* m_in_active_chain = nullptr"

.SS "\fBCBlockLocator\fP* m_locator = nullptr"

.SS "int64_t* m_max_time = nullptr"

.SS "int64_t* m_mtp_time = nullptr"

.SS "const \fBFoundBlock\fP* m_next_block = nullptr"

.SS "int64_t* m_time = nullptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
