.TH "FreespaceChecker::PathQuery" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FreespaceChecker::PathQuery
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <freespacechecker\&.h>\fP
.PP
Inherited by \fBIntro\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual QString \fBgetPathToCheck\fP ()=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual QString getPathToCheck ()\fR [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
