.TH "FreespaceChecker" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FreespaceChecker
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <freespacechecker\&.h>\fP
.PP
Inherits QObject\&.
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPathQuery\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBStatus\fP { \fBST_OK\fP, \fBST_ERROR\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBcheck\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBreply\fP (int status, const QString &message, quint64 available)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFreespaceChecker\fP (\fBPathQuery\fP *intro)"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBStatus\fP\fBStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIST_OK \fP
.TP
\f(BIST_ERROR \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFreespaceChecker\fP (\fBPathQuery\fP * intro)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void check ()\fR [slot]\fP"

.SS "void reply (int status, const QString & message, quint64 available)\fR [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
