.TH "src/qt/freespacechecker.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/freespacechecker.h
.SH SYNOPSIS
.br
.PP
\fR#include <QObject>\fP
.br
\fR#include <QString>\fP
.br
\fR#include <QtGlobal>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFreespaceChecker\fP"
.br
.ti -1c
.RI "class \fBFreespaceChecker::PathQuery\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
