.TH "src/test/fs_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fs_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/fs_helpers\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <ios>\fP
.br
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (fsbridge_pathtostring)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (fsbridge_stem)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (fsbridge_fstream)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rename)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (fsbridge_fstream )"

.SS "BOOST_AUTO_TEST_CASE (fsbridge_pathtostring )"

.SS "BOOST_AUTO_TEST_CASE (fsbridge_stem )"

.SS "BOOST_AUTO_TEST_CASE (rename )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
