.TH "FileLock" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileLock
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fs\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileLock\fP ()=delete"
.br
.ti -1c
.RI "\fBFileLock\fP (const \fBFileLock\fP &)=delete"
.br
.ti -1c
.RI "\fBFileLock\fP (\fBFileLock\fP &&)=delete"
.br
.ti -1c
.RI "\fBFileLock\fP (const \fBfs::path\fP &file)"
.br
.ti -1c
.RI "\fB~FileLock\fP ()"
.br
.ti -1c
.RI "bool \fBTryLock\fP ()"
.br
.ti -1c
.RI "std::string \fBGetReason\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFileLock\fP ()\fR [delete]\fP"

.SS "\fBFileLock\fP (const \fBFileLock\fP & )\fR [delete]\fP"

.SS "\fBFileLock\fP (\fBFileLock\fP && )\fR [delete]\fP"

.SS "\fBFileLock\fP (const \fBfs::path\fP & file)\fR [explicit]\fP"

.SS "~\fBFileLock\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "std::string GetReason ()\fR [inline]\fP"

.SS "bool TryLock ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
