.TH "FSChaCha20Poly1305" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSChaCha20Poly1305
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <chacha20poly1305\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFSChaCha20Poly1305\fP (const \fBFSChaCha20Poly1305\fP &)=delete"
.br
.ti -1c
.RI "\fBFSChaCha20Poly1305\fP (\fBFSChaCha20Poly1305\fP &&)=delete"
.br
.ti -1c
.RI "\fBFSChaCha20Poly1305\fP & \fBoperator=\fP (const \fBFSChaCha20Poly1305\fP &)=delete"
.br
.ti -1c
.RI "\fBFSChaCha20Poly1305\fP & \fBoperator=\fP (\fBFSChaCha20Poly1305\fP &&)=delete"
.br
.ti -1c
.RI "\fBFSChaCha20Poly1305\fP (std::span< const std::byte > key, uint32_t rekey_interval) noexcept"
.br
.ti -1c
.RI "void \fBEncrypt\fP (std::span< const std::byte > plain, std::span< const std::byte > aad, std::span< std::byte > cipher) noexcept"
.br
.ti -1c
.RI "void \fBEncrypt\fP (std::span< const std::byte > plain1, std::span< const std::byte > plain2, std::span< const std::byte > aad, std::span< std::byte > cipher) noexcept"
.br
.ti -1c
.RI "bool \fBDecrypt\fP (std::span< const std::byte > cipher, std::span< const std::byte > aad, std::span< std::byte > plain) noexcept"
.br
.ti -1c
.RI "bool \fBDecrypt\fP (std::span< const std::byte > cipher, std::span< const std::byte > aad, std::span< std::byte > plain1, std::span< std::byte > plain2) noexcept"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr auto \fBKEYLEN\fP = \fBAEADChaCha20Poly1305::KEYLEN\fP"
.br
.ti -1c
.RI "static constexpr auto \fBEXPANSION\fP = \fBAEADChaCha20Poly1305::EXPANSION\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Forward-secure wrapper around \fBAEADChaCha20Poly1305\fP\&.

.PP
This implements an AEAD which automatically increments the nonce on every encryption or decryption, and cycles keys after a predetermined number of encryptions or decryptions\&.

.PP
See BIP324 for details\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFSChaCha20Poly1305\fP (const \fBFSChaCha20Poly1305\fP & )\fR [delete]\fP"

.SS "\fBFSChaCha20Poly1305\fP (\fBFSChaCha20Poly1305\fP && )\fR [delete]\fP"

.SS "\fBFSChaCha20Poly1305\fP (std::span< const std::byte > key, uint32_t rekey_interval)\fR [inline]\fP, \fR [noexcept]\fP"
Construct an \fBFSChaCha20Poly1305\fP cipher that rekeys every rekey_interval operations\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool Decrypt (std::span< const std::byte > cipher, std::span< const std::byte > aad, std::span< std::byte > plain)\fR [inline]\fP, \fR [noexcept]\fP"
Decrypt a message with a specified aad\&. Returns true if valid\&.

.PP
Requires cipher\&.size() = plain\&.size() + EXPANSION\&. 
.SS "bool Decrypt (std::span< const std::byte > cipher, std::span< const std::byte > aad, std::span< std::byte > plain1, std::span< std::byte > plain2)\fR [noexcept]\fP"
Decrypt a message with a specified aad and split the result\&. Returns true if valid\&.

.PP
Requires cipher\&.size() = plain1\&.size() + plain2\&.size() + EXPANSION\&. 
.SS "void Encrypt (std::span< const std::byte > plain, std::span< const std::byte > aad, std::span< std::byte > cipher)\fR [inline]\fP, \fR [noexcept]\fP"
Encrypt a message with a specified aad\&.

.PP
Requires cipher\&.size() = plain\&.size() + EXPANSION\&. 
.SS "void Encrypt (std::span< const std::byte > plain1, std::span< const std::byte > plain2, std::span< const std::byte > aad, std::span< std::byte > cipher)\fR [noexcept]\fP"
Encrypt a message (given split into plain1 + plain2) with a specified aad\&.

.PP
Requires cipher\&.size() = plain\&.size() + EXPANSION\&. 
.SS "\fBFSChaCha20Poly1305\fP & operator= (const \fBFSChaCha20Poly1305\fP & )\fR [delete]\fP"

.SS "\fBFSChaCha20Poly1305\fP & operator= (\fBFSChaCha20Poly1305\fP && )\fR [delete]\fP"

.SH "Field Documentation"
.PP 
.SS "auto EXPANSION = \fBAEADChaCha20Poly1305::EXPANSION\fP\fR [static]\fP, \fR [constexpr]\fP"
Expansion when encrypting\&. 
.SS "auto KEYLEN = \fBAEADChaCha20Poly1305::KEYLEN\fP\fR [static]\fP, \fR [constexpr]\fP"
Length of keys expected by the constructor\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
