.TH "src/test/fuzz/fuzz.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/fuzz.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <netaddress\&.h>\fP
.br
\fR#include <netbase\&.h>\fP
.br
\fR#include <test/fuzz/util/check_globals\&.h>\fP
.br
\fR#include <test/util/coverage\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/sock\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <csignal>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdio>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <exception>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <map>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <random>\fP
.br
\fR#include <string>\fP
.br
\fR#include <tuple>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBFuzzTarget\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "auto & \fBFuzzTargets\fP ()"
.br
.ti -1c
.RI "void \fBFuzzFrameworkRegisterTarget\fP (std::string_view \fBname\fP, \fBTypeTestOneInput\fP target, \fBFuzzTargetOptions\fP opts)"
.br
.ti -1c
.RI "int \fBLLVMFuzzerTestOneInput\fP (const uint8_t *data, size_t size)"
.br
.ti -1c
.RI "int \fBLLVMFuzzerInitialize\fP (int *argc, char ***argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::function< void(const std::string &)> \fBG_TEST_LOG_FUN\fP {}"
.br
.ti -1c
.RI "const std::function< std::vector< const char * >()> \fBG_TEST_COMMAND_LINE_ARGUMENTS\fP"
.br
.ti -1c
.RI "const std::function< std::string()> \fBG_TEST_GET_FULL_NAME\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void FuzzFrameworkRegisterTarget (std::string_view name, \fBTypeTestOneInput\fP target, \fBFuzzTargetOptions\fP opts)"

.SS "auto & FuzzTargets ()"

.SS "int LLVMFuzzerInitialize (int * argc, char *** argv)"

.SS "int LLVMFuzzerTestOneInput (const uint8_t * data, size_t size)"

.SH "Variable Documentation"
.PP 
.SS "const std::function<std::vector<const char*>()> G_TEST_COMMAND_LINE_ARGUMENTS"
\fBInitial value:\fP
.nf
= []() {
    return g_args;
}
.PP
.fi
Retrieve the command line arguments\&. 
.SS "const std::function<std::string()> G_TEST_GET_FULL_NAME"
\fBInitial value:\fP
.nf
{[]{
    return std::string{g_fuzz_target};
}}
.PP
.fi
Retrieve the unit test name\&. 
.SS "const std::function<void(const std::string&)> G_TEST_LOG_FUN {}"
This is connected to the logger\&. Can be used to redirect logs to any other log 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
