.TH "FuzzTargetOptions" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuzzTargetOptions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fuzz\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::function< void()> \fBinit\fP {[] {}}"
.br
.ti -1c
.RI "bool \fBhidden\fP {false}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool hidden {false}"

.SS "std::function<void()> init {[] {}}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
