.TH "FuzzedDataProvider" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuzzedDataProvider
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FuzzedDataProvider\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFuzzedDataProvider\fP (const uint8_t *data, size_t size)"
.br
.ti -1c
.RI "\fB~FuzzedDataProvider\fP ()=default"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::vector< \fBT\fP > \fBConsumeBytes\fP (size_t num_bytes)"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::vector< \fBT\fP > \fBConsumeBytesWithTerminator\fP (size_t num_bytes, \fBT\fP terminator=0)"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::vector< \fBT\fP > \fBConsumeRemainingBytes\fP ()"
.br
.ti -1c
.RI "std::string \fBConsumeBytesAsString\fP (size_t num_bytes)"
.br
.ti -1c
.RI "std::string \fBConsumeRandomLengthString\fP (size_t max_length)"
.br
.ti -1c
.RI "std::string \fBConsumeRandomLengthString\fP ()"
.br
.ti -1c
.RI "std::string \fBConsumeRemainingBytesAsString\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP \fBConsumeIntegral\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP \fBConsumeIntegralInRange\fP (\fBT\fP min, \fBT\fP max)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP \fBConsumeFloatingPoint\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP \fBConsumeFloatingPointInRange\fP (\fBT\fP min, \fBT\fP max)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP \fBConsumeProbability\fP ()"
.br
.ti -1c
.RI "bool \fBConsumeBool\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP \fBConsumeEnum\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP, size_t size> \fBT\fP \fBPickValueInArray\fP (const \fBT\fP(&array)[size])"
.br
.ti -1c
.RI "template<typename \fBT\fP, size_t size> \fBT\fP \fBPickValueInArray\fP (const std::array< \fBT\fP, size > &array)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP \fBPickValueInArray\fP (std::initializer_list< const \fBT\fP > list)"
.br
.ti -1c
.RI "size_t \fBConsumeData\fP (void *destination, size_t num_bytes)"
.br
.ti -1c
.RI "size_t \fBremaining_bytes\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFuzzedDataProvider\fP (const uint8_t * data, size_t size)\fR [inline]\fP"

.SS "~\fBFuzzedDataProvider\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ConsumeBool ()\fR [inline]\fP"

.SS "template<typename \fBT\fP> std::vector< \fBT\fP > ConsumeBytes (size_t num_bytes)"

.SS "std::string ConsumeBytesAsString (size_t num_bytes)\fR [inline]\fP"

.SS "template<typename \fBT\fP> std::vector< \fBT\fP > ConsumeBytesWithTerminator (size_t num_bytes, \fBT\fP terminator = \fR0\fP)"

.SS "size_t ConsumeData (void * destination, size_t num_bytes)\fR [inline]\fP"

.SS "template<typename \fBT\fP> \fBT\fP ConsumeEnum ()"

.SS "template<typename \fBT\fP> \fBT\fP ConsumeFloatingPoint ()"

.SS "template<typename \fBT\fP> \fBT\fP ConsumeFloatingPointInRange (\fBT\fP min, \fBT\fP max)"

.SS "template<typename \fBT\fP> \fBT\fP ConsumeIntegral ()"

.SS "template<typename \fBT\fP> \fBT\fP ConsumeIntegralInRange (\fBT\fP min, \fBT\fP max)"

.SS "template<typename \fBT\fP> \fBT\fP ConsumeProbability ()"

.SS "std::string ConsumeRandomLengthString ()\fR [inline]\fP"

.SS "std::string ConsumeRandomLengthString (size_t max_length)\fR [inline]\fP"

.SS "template<typename \fBT\fP> std::vector< \fBT\fP > ConsumeRemainingBytes ()"

.SS "std::string ConsumeRemainingBytesAsString ()\fR [inline]\fP"

.SS "template<typename \fBT\fP, size_t size> \fBT\fP PickValueInArray (const std::array< \fBT\fP, size > & array)"

.SS "template<typename \fBT\fP, size_t size> \fBT\fP PickValueInArray (const \fBT\fP(&) array[size])"

.SS "template<typename \fBT\fP> \fBT\fP PickValueInArray (std::initializer_list< const \fBT\fP > list)"

.SS "size_t remaining_bytes ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
