.TH "src/bench/gcs_filter.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bench/gcs_filter.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bench/bench\&.h>\fP
.br
\fR#include <blockfilter\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBENCHMARK\fP (GCSBlockFilterGetHash, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.ti -1c
.RI "\fBBENCHMARK\fP (GCSFilterConstruct, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.ti -1c
.RI "\fBBENCHMARK\fP (GCSFilterDecode, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.ti -1c
.RI "\fBBENCHMARK\fP (GCSFilterDecodeSkipCheck, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.ti -1c
.RI "\fBBENCHMARK\fP (GCSFilterMatch, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BENCHMARK (GCSBlockFilterGetHash , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SS "BENCHMARK (GCSFilterConstruct , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SS "BENCHMARK (GCSFilterDecode , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SS "BENCHMARK (GCSFilterDecodeSkipCheck , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SS "BENCHMARK (GCSFilterMatch , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
