.TH "GCSFilter::Params" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GCSFilter::Params
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <blockfilter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParams\fP (uint64_t siphash_k0=0, uint64_t siphash_k1=0, uint8_t P=0, uint32_t M=1)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBm_siphash_k0\fP"
.br
.ti -1c
.RI "uint64_t \fBm_siphash_k1\fP"
.br
.ti -1c
.RI "uint8_t \fBm_P\fP"
.br
.RI "Golomb-Rice coding parameter\&. "
.ti -1c
.RI "uint32_t \fBm_M\fP"
.br
.RI "Inverse false positive rate\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Params (uint64_t siphash_k0 = \fR0\fP, uint64_t siphash_k1 = \fR0\fP, uint8_t P = \fR0\fP, uint32_t M = \fR1\fP)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "uint32_t m_M"

.PP
Inverse false positive rate\&. 
.SS "uint8_t m_P"

.PP
Golomb-Rice coding parameter\&. 
.SS "uint64_t m_siphash_k0"

.SS "uint64_t m_siphash_k1"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
