.TH "src/minisketch/src/fields/generic_5bytes.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/minisketch/src/fields/generic_5bytes.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./fielddefines\&.h'\fP
.br
\fR#include 'generic_common_impl\&.h'\fP
.br
\fR#include '\&.\&./lintrans\&.h'\fP
.br
\fR#include '\&.\&./sketch_impl\&.h'\fP
.br
\fR#include '\&.\&./sketch\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSketch\fP * \fBConstructGeneric5Bytes\fP (int bits, int implementation)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBSketch\fP * ConstructGeneric5Bytes (int bits, int implementation)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
