.TH "src/test/getarg_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/getarg_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/args\&.h>\fP
.br
\fR#include <common/settings\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <limits>\fP
.br
\fR#include <string>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBResetArgs\fP (\fBArgsManager\fP &local_args, const std::string &strArg)"
.br
.ti -1c
.RI "void \fBSetupArgs\fP (\fBArgsManager\fP &local_args, const std::vector< std::pair< std::string, unsigned int > > &\fBargs\fP)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (setting_args)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (boolarg)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (stringarg)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (intarg)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (patharg)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (doubledash)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (boolargno)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (logargs)"
.br
.ti -1c
.RI "std::vector< std::string > \fBSplitString\fP (std::string_view str, char sep)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (boolarg )"

.SS "BOOST_AUTO_TEST_CASE (boolargno )"

.SS "BOOST_AUTO_TEST_CASE (doubledash )"

.SS "BOOST_AUTO_TEST_CASE (intarg )"

.SS "BOOST_AUTO_TEST_CASE (logargs )"

.SS "BOOST_AUTO_TEST_CASE (patharg )"

.SS "BOOST_AUTO_TEST_CASE (setting_args )"

.SS "BOOST_AUTO_TEST_CASE (stringarg )"

.SS "void ResetArgs (\fBArgsManager\fP & local_args, const std::string & strArg)"

.SS "void SetupArgs (\fBArgsManager\fP & local_args, const std::vector< std::pair< std::string, unsigned int > > & args)"

.SS "std::vector< std::string > SplitString (std::string_view str, char sep)\fR [inline]\fP, \fR [nodiscard]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
