.TH "src/util/golombrice.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/golombrice.h
.SH SYNOPSIS
.br
.PP
\fR#include <util/fastrange\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <cstdint>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename OStream> void \fBGolombRiceEncode\fP (\fBBitStreamWriter\fP< OStream > &bitwriter, uint8_t P, uint64_t x)"
.br
.ti -1c
.RI "template<typename IStream> uint64_t \fBGolombRiceDecode\fP (\fBBitStreamReader\fP< IStream > &bitreader, uint8_t P)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename IStream> uint64_t GolombRiceDecode (\fBBitStreamReader\fP< IStream > & bitreader, uint8_t P)"

.SS "template<typename OStream> void GolombRiceEncode (\fBBitStreamWriter\fP< OStream > & bitwriter, uint8_t P, uint64_t x)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
