.TH "src/qt/guiconstants.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/guiconstants.h
.SH SYNOPSIS
.br
.PP
\fR#include <chrono>\fP
.br
\fR#include <cstdint>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTYLE_INVALID\fP   'border: 3px solid #FF8080'"
.br
.ti -1c
.RI "#define \fBCOLOR_UNCONFIRMED\fP   QColor(128, 128, 128)"
.br
.ti -1c
.RI "#define \fBCOLOR_NEGATIVE\fP   QColor(255, 0, 0)"
.br
.ti -1c
.RI "#define \fBCOLOR_BAREADDRESS\fP   QColor(140, 140, 140)"
.br
.ti -1c
.RI "#define \fBCOLOR_TX_STATUS_DANGER\fP   QColor(200, 100, 100)"
.br
.ti -1c
.RI "#define \fBCOLOR_BLACK\fP   QColor(0, 0, 0)"
.br
.ti -1c
.RI "#define \fBSPINNER_FRAMES\fP   36"
.br
.ti -1c
.RI "#define \fBQAPP_ORG_NAME\fP   'Bitcoin'"
.br
.ti -1c
.RI "#define \fBQAPP_ORG_DOMAIN\fP   'bitcoin\&.org'"
.br
.ti -1c
.RI "#define \fBQAPP_APP_NAME_DEFAULT\fP   'Bitcoin\-Qt'"
.br
.ti -1c
.RI "#define \fBQAPP_APP_NAME_TESTNET\fP   'Bitcoin\-Qt\-testnet'"
.br
.ti -1c
.RI "#define \fBQAPP_APP_NAME_TESTNET4\fP   'Bitcoin\-Qt\-testnet4'"
.br
.ti -1c
.RI "#define \fBQAPP_APP_NAME_SIGNET\fP   'Bitcoin\-Qt\-signet'"
.br
.ti -1c
.RI "#define \fBQAPP_APP_NAME_REGTEST\fP   'Bitcoin\-Qt\-regtest'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COLOR_BAREADDRESS   QColor(140, 140, 140)"

.SS "#define COLOR_BLACK   QColor(0, 0, 0)"

.SS "#define COLOR_NEGATIVE   QColor(255, 0, 0)"

.SS "#define COLOR_TX_STATUS_DANGER   QColor(200, 100, 100)"

.SS "#define COLOR_UNCONFIRMED   QColor(128, 128, 128)"

.SS "#define QAPP_APP_NAME_DEFAULT   'Bitcoin\-Qt'"

.SS "#define QAPP_APP_NAME_REGTEST   'Bitcoin\-Qt\-regtest'"

.SS "#define QAPP_APP_NAME_SIGNET   'Bitcoin\-Qt\-signet'"

.SS "#define QAPP_APP_NAME_TESTNET   'Bitcoin\-Qt\-testnet'"

.SS "#define QAPP_APP_NAME_TESTNET4   'Bitcoin\-Qt\-testnet4'"

.SS "#define QAPP_ORG_DOMAIN   'bitcoin\&.org'"

.SS "#define QAPP_ORG_NAME   'Bitcoin'"

.SS "#define SPINNER_FRAMES   36"

.SS "#define STYLE_INVALID   'border: 3px solid #FF8080'"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
