.TH "GUIUtil" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUIUtil
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBToolTipToRichTextFilter\fP"
.br
.ti -1c
.RI "class \fBThemedLabel\fP"
.br
.ti -1c
.RI "class \fBClickableLabel\fP"
.br
.ti -1c
.RI "class \fBClickableProgressBar\fP"
.br
.ti -1c
.RI "class \fBItemDelegate\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBClickableProgressBar\fP \fBProgressBar\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBdateTimeStr\fP (const QDateTime &date)"
.br
.ti -1c
.RI "QString \fBdateTimeStr\fP (qint64 nTime)"
.br
.ti -1c
.RI "QFont \fBfixedPitchFont\fP (bool use_embedded_font)"
.br
.ti -1c
.RI "void \fBsetupAddressWidget\fP (\fBQValidatedLineEdit\fP *widget, QWidget *parent)"
.br
.ti -1c
.RI "void \fBAddButtonShortcut\fP (QAbstractButton *button, const QKeySequence &shortcut)"
.br
.ti -1c
.RI "bool \fBparseBitcoinURI\fP (const QUrl &uri, \fBSendCoinsRecipient\fP *out)"
.br
.ti -1c
.RI "bool \fBparseBitcoinURI\fP (QString uri, \fBSendCoinsRecipient\fP *out)"
.br
.ti -1c
.RI "QString \fBformatBitcoinURI\fP (const \fBSendCoinsRecipient\fP &info)"
.br
.ti -1c
.RI "bool \fBisDust\fP (\fBinterfaces::Node\fP &\fBnode\fP, const QString &address, const \fBCAmount\fP &amount)"
.br
.ti -1c
.RI "QString \fBHtmlEscape\fP (const QString &str, bool fMultiLine)"
.br
.ti -1c
.RI "QString \fBHtmlEscape\fP (const std::string &str, bool fMultiLine)"
.br
.ti -1c
.RI "void \fBcopyEntryData\fP (const QAbstractItemView *view, int column, int role)"
.br
.ti -1c
.RI "QList< QModelIndex > \fBgetEntryData\fP (const QAbstractItemView *view, int column)"
.br
.ti -1c
.RI "bool \fBhasEntryData\fP (const QAbstractItemView *view, int column, int role)"
.br
.ti -1c
.RI "void \fBLoadFont\fP (const QString &file_name)"
.br
.ti -1c
.RI "QString \fBgetDefaultDataDirectory\fP ()"
.br
.ti -1c
.RI "QString \fBExtractFirstSuffixFromFilter\fP (const QString &filter)"
.br
.ti -1c
.RI "QString \fBgetSaveFileName\fP (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedSuffixOut)"
.br
.ti -1c
.RI "QString \fBgetOpenFileName\fP (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedSuffixOut)"
.br
.ti -1c
.RI "Qt::ConnectionType \fBblockingGUIThreadConnection\fP ()"
.br
.ti -1c
.RI "bool \fBcheckPoint\fP (const QPoint &p, const QWidget *w)"
.br
.ti -1c
.RI "bool \fBisObscured\fP (QWidget *w)"
.br
.ti -1c
.RI "void \fBbringToFront\fP (QWidget *w)"
.br
.ti -1c
.RI "void \fBhandleCloseWindowShortcut\fP (QWidget *w)"
.br
.ti -1c
.RI "void \fBopenDebugLogfile\fP ()"
.br
.ti -1c
.RI "bool \fBopenBitcoinConf\fP ()"
.br
.ti -1c
.RI "bool \fBGetStartOnSystemStartup\fP ()"
.br
.ti -1c
.RI "bool \fBSetStartOnSystemStartup\fP (bool fAutoStart)"
.br
.ti -1c
.RI "void \fBsetClipboard\fP (const QString &str)"
.br
.ti -1c
.RI "\fBfs::path\fP \fBQStringToPath\fP (const QString &path)"
.br
.ti -1c
.RI "QString \fBPathToQString\fP (const \fBfs::path\fP &path)"
.br
.ti -1c
.RI "QString \fBNetworkToQString\fP (\fBNetwork\fP net)"
.br
.ti -1c
.RI "QString \fBConnectionTypeToQString\fP (\fBConnectionType\fP conn_type, bool prepend_direction)"
.br
.ti -1c
.RI "QString \fBformatDurationStr\fP (std::chrono::seconds dur)"
.br
.ti -1c
.RI "QString \fBFormatPeerAge\fP (std::chrono::seconds time_connected)"
.br
.ti -1c
.RI "QString \fBformatServicesStr\fP (quint64 mask)"
.br
.ti -1c
.RI "QString \fBformatPingTime\fP (std::chrono::microseconds ping_time)"
.br
.ti -1c
.RI "QString \fBformatTimeOffset\fP (int64_t time_offset)"
.br
.ti -1c
.RI "QString \fBformatNiceTimeOffset\fP (qint64 secs)"
.br
.ti -1c
.RI "QString \fBformatBytes\fP (uint64_t bytes)"
.br
.ti -1c
.RI "qreal \fBcalculateIdealFontSize\fP (int width, const QString &text, QFont font, qreal minPointSize, qreal font_size)"
.br
.ti -1c
.RI "void \fBPolishProgressDialog\fP (QProgressDialog *dialog)"
.br
.ti -1c
.RI "int \fBTextWidth\fP (const QFontMetrics &fm, const QString &text)"
.br
.ti -1c
.RI "void \fBLogQtInfo\fP ()"
.br
.ti -1c
.RI "void \fBPopupMenu\fP (QMenu *menu, const QPoint &point, QAction *at_action)"
.br
.ti -1c
.RI "QDateTime \fBStartOfDay\fP (const QDate &date)"
.br
.ti -1c
.RI "bool \fBHasPixmap\fP (const QLabel *label)"
.br
.ti -1c
.RI "QString \fBMakeHtmlLink\fP (const QString &source, const QString &link)"
.br
.ti -1c
.RI "void \fBPrintSlotException\fP (const std::exception *exception, const QObject *sender, const QObject *receiver)"
.br
.ti -1c
.RI "void \fBShowModalDialogAsynchronously\fP (QDialog *dialog)"
.br
.ti -1c
.RI "QString \fBWalletDisplayName\fP (const QString &\fBname\fP)"
.br
.ti -1c
.RI "QString \fBWalletDisplayName\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "template<typename Sender, typename Signal, typename Receiver, typename Slot> auto \fBExceptionSafeConnect\fP (Sender sender, Signal signal, Receiver receiver, Slot method, Qt::ConnectionType type=Qt::AutoConnection)"
.br
.ti -1c
.RI "bool \fBIsEscapeOrBack\fP (int key)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr auto \fBdialog_flags\fP = Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowCloseButtonHint"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility functions used by the Bitcoin Qt UI\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBClickableProgressBar\fP \fBProgressBar\fP"

.SH "Function Documentation"
.PP 
.SS "void AddButtonShortcut (QAbstractButton * button, const QKeySequence & shortcut)"
Connects an additional shortcut to a QAbstractButton\&. Works around the one shortcut limitation of the button's shortcut property\&. 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP QAbstractButton to assign shortcut to 
.br
\fIshortcut\fP QKeySequence to use as shortcut 
.RE
.PP

.SS "Qt::ConnectionType blockingGUIThreadConnection ()"
Get connection type to call object slot in GUI thread with invokeMethod\&. The call will be blocking\&.

.PP
\fBReturns\fP
.RS 4
If called from the GUI thread, return a Qt::DirectConnection\&. If called from another thread, return a Qt::BlockingQueuedConnection\&. 
.RE
.PP

.SS "void bringToFront (QWidget * w)"

.SS "qreal calculateIdealFontSize (int width, const QString & text, QFont font, qreal minPointSize, qreal font_size)"

.SS "bool checkPoint (const QPoint & p, const QWidget * w)"

.SS "QString ConnectionTypeToQString (\fBConnectionType\fP conn_type, bool prepend_direction)"
Convert enum \fBConnectionType\fP to QString 
.SS "void copyEntryData (const QAbstractItemView * view, int column, int role = \fRQt::EditRole\fP)"
Copy a field of the currently selected entry of a view to the clipboard\&. Does nothing if nothing is selected\&. 
.PP
\fBParameters\fP
.RS 4
\fIcolumn\fP Data column to extract from the model 
.br
\fIrole\fP Data role to extract from the model 
.RE
.PP
\fBSee also\fP
.RS 4
TransactionView::copyLabel, TransactionView::copyAmount, TransactionView::copyAddress 
.RE
.PP

.SS "QString dateTimeStr (const QDateTime & date)"

.SS "QString dateTimeStr (qint64 nTime)"

.SS "template<typename Sender, typename Signal, typename Receiver, typename Slot> auto ExceptionSafeConnect (Sender sender, Signal signal, Receiver receiver, Slot method, Qt::ConnectionType type = \fRQt::AutoConnection\fP)"
A drop-in replacement of QObject::connect function (see: https://doc.qt.io/qt-5/qobject.html#connect-3), that guaranties that all exceptions are handled within the slot\&.

.PP
NOTE: This function is incompatible with Qt private signals\&. 
.SS "QString ExtractFirstSuffixFromFilter (const QString & filter)"
Extract first suffix from filter pattern "Description (*\&.foo)" or "Description (*\&.foo *\&.bar \&.\&.\&.)\&.@param [in] filter Filter specification such as "Comma Separated Files (*\&.csv)" 
.PP
\fBReturns\fP
.RS 4
QString 
.RE
.PP

.SS "QFont fixedPitchFont (bool use_embedded_font)"

.SS "QString formatBitcoinURI (const \fBSendCoinsRecipient\fP & info)"

.SS "QString formatBytes (uint64_t bytes)"

.SS "QString formatDurationStr (std::chrono::seconds dur)"
Convert seconds into a QString with days, hours, mins, secs 
.SS "QString formatNiceTimeOffset (qint64 secs)"

.SS "QString FormatPeerAge (std::chrono::seconds time_connected)"
Convert peer connection time to a QString denominated in the most relevant unit\&. 
.SS "QString formatPingTime (std::chrono::microseconds ping_time)"
\fBFormat\fP a \fBCNodeStats\&.m_last_ping_time\fP into a user-readable string or display N/A, if 0 
.SS "QString formatServicesStr (quint64 mask)"
\fBFormat\fP CNodeStats\&.nServices bitmask into a user-readable string 
.SS "QString formatTimeOffset (int64_t time_offset)"
\fBFormat\fP a \fBCNodeStateStats\&.time_offset\fP into a user-readable string 
.SS "QString getDefaultDataDirectory ()"
Determine default data directory for operating system\&. 
.SS "QList< QModelIndex > getEntryData (const QAbstractItemView * view, int column)"
Return a field of the currently selected entry as a QString\&. Does nothing if nothing is selected\&. 
.PP
\fBParameters\fP
.RS 4
\fIcolumn\fP Data column to extract from the model 
.RE
.PP
\fBSee also\fP
.RS 4
TransactionView::copyLabel, TransactionView::copyAmount, TransactionView::copyAddress 
.RE
.PP

.SS "QString getOpenFileName (QWidget * parent, const QString & caption, const QString & dir, const QString & filter, QString * selectedSuffixOut)"
Get open filename, convenience wrapper for QFileDialog::getOpenFileName\&.

.PP
\fBParameters\fP
.RS 4
\fIparent\fP Parent window (or 0) 
.br
\fIcaption\fP Window caption (or empty, for default) 
.br
\fIdir\fP Starting directory (or empty, to default to documents directory) 
.br
\fIfilter\fP Filter specification such as "Comma Separated Files (*\&.csv)" 
.br
\fIselectedSuffixOut\fP Pointer to return the suffix (file type) that was selected (or 0)\&. Can be useful when choosing the save file format based on suffix\&. 
.RE
.PP

.SS "QString getSaveFileName (QWidget * parent, const QString & caption, const QString & dir, const QString & filter, QString * selectedSuffixOut)"
Get save filename, mimics QFileDialog::getSaveFileName, except that it appends a default suffix when no suffix is provided by the user\&.

.PP
\fBParameters\fP
.RS 4
\fIparent\fP Parent window (or 0) 
.br
\fIcaption\fP Window caption (or empty, for default) 
.br
\fIdir\fP Starting directory (or empty, to default to documents directory) 
.br
\fIfilter\fP Filter specification such as "Comma Separated Files (*\&.csv)" 
.br
\fIselectedSuffixOut\fP Pointer to return the suffix (file type) that was selected (or 0)\&. Can be useful when choosing the save file format based on suffix\&. 
.RE
.PP

.SS "bool GetStartOnSystemStartup ()"

.SS "void handleCloseWindowShortcut (QWidget * w)"

.SS "bool hasEntryData (const QAbstractItemView * view, int column, int role)"
Returns true if the specified field of the currently selected view entry is not empty\&. 
.PP
\fBParameters\fP
.RS 4
\fIcolumn\fP Data column to extract from the model 
.br
\fIrole\fP Data role to extract from the model 
.RE
.PP
\fBSee also\fP
.RS 4
TransactionView::contextualMenu 
.RE
.PP

.SS "bool HasPixmap (const QLabel * label)"
Returns true if pixmap has been set\&.

.PP
QPixmap* QLabel::pixmap() is deprecated since Qt 5\&.15\&. 
.SS "QString HtmlEscape (const QString & str, bool fMultiLine)"

.SS "QString HtmlEscape (const std::string & str, bool fMultiLine)"

.SS "bool isDust (\fBinterfaces::Node\fP & node, const QString & address, const \fBCAmount\fP & amount)"

.SS "bool IsEscapeOrBack (int key)\fR [inline]\fP"

.SS "bool isObscured (QWidget * w)"

.SS "void LoadFont (const QString & file_name)"
Loads the font from the file specified by file_name, aborts if it fails\&. 
.SS "void LogQtInfo ()"
Writes to debug\&.log short info about the used Qt and the host system\&. 
.SS "QString MakeHtmlLink (const QString & source, const QString & link)"
Replaces a plain text link with an HTML tagged one\&. 
.SS "QString NetworkToQString (\fBNetwork\fP net)"
Convert enum \fBNetwork\fP to QString 
.SS "bool openBitcoinConf ()"

.SS "void openDebugLogfile ()"

.SS "bool parseBitcoinURI (const QUrl & uri, \fBSendCoinsRecipient\fP * out)"

.SS "bool parseBitcoinURI (QString uri, \fBSendCoinsRecipient\fP * out)"

.SS "QString PathToQString (const \fBfs::path\fP & path)"
Convert OS specific boost path to QString through UTF-8 
.SS "void PolishProgressDialog (QProgressDialog * dialog)"

.SS "void PopupMenu (QMenu * menu, const QPoint & point, QAction * at_action = \fRnullptr\fP)"
Call QMenu::popup() only on supported QT_QPA_PLATFORM\&. 
.SS "void PrintSlotException (const std::exception * exception, const QObject * sender, const QObject * receiver)"

.SS "\fBfs::path\fP QStringToPath (const QString & path)"
Qt event filter that intercepts QEvent::FocusOut events for QLabel objects, and resets their `textInteractionFlags' property to get rid of the visible cursor\&.

.PP
This is a temporary fix of QTBUG-59514\&. */ class LabelOutOfFocusEventFilter : public QObject { Q_OBJECT

.PP
public: explicit LabelOutOfFocusEventFilter(QObject* parent); bool eventFilter(QObject* watched, QEvent* event) override; };

.PP
bool \fBGetStartOnSystemStartup()\fP; bool \fBSetStartOnSystemStartup(bool fAutoStart)\fP;

.PP
/** Convert QString to OS specific boost path through UTF-8 
.SS "void setClipboard (const QString & str)"

.SS "bool SetStartOnSystemStartup (bool fAutoStart)"

.SS "void setupAddressWidget (\fBQValidatedLineEdit\fP * widget, QWidget * parent)"

.SS "void ShowModalDialogAsynchronously (QDialog * dialog)"
Shows a QDialog instance asynchronously, and deletes it on close\&. 
.SS "QDateTime StartOfDay (const QDate & date)"
Returns the start-moment of the day in local time\&.

.PP
QDateTime::QDateTime(const QDate& date) is deprecated since Qt 5\&.15\&. QDate::startOfDay() was introduced in Qt 5\&.14\&. 
.SS "int TextWidth (const QFontMetrics & fm, const QString & text)"
Returns the distance in pixels appropriate for drawing a subsequent character after text\&.

.PP
In Qt 5\&.12 and before the QFontMetrics::width() is used and it is deprecated since Qt 5\&.13\&. In Qt 5\&.11 the QFontMetrics::horizontalAdvance() was introduced\&. 
.SS "QString WalletDisplayName (const QString & name)"

.SS "QString WalletDisplayName (const std::string & name)"

.SH "Variable Documentation"
.PP 
.SS "auto dialog_flags = Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowCloseButtonHint\fR [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
