.TH "ClickableProgressBar" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClickableProgressBar
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <guiutil\&.h>\fP
.PP
Inherits QProgressBar\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBclicked\fP (const QPoint &point)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBmouseReleaseEvent\fP (QMouseEvent *event) override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void clicked (const QPoint & point)\fR [signal]\fP"
Emitted when the progressbar is clicked\&. The relative mouse coordinates of the click are passed to the signal\&. 
.SS "void mouseReleaseEvent (QMouseEvent * event)\fR [override]\fP, \fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
