.TH "HashWriter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashWriter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hash\&.h>\fP
.PP
Inherited by \fBHashVerifier< Source >\fP, and \fBHashedSourceWriter< Source >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBwrite\fP (std::span< const std::byte > src)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetSHA256\fP ()"
.br
.ti -1c
.RI "uint64_t \fBGetCheapHash\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBHashWriter\fP & \fBoperator<<\fP (const \fBT\fP &obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A writer stream (for serialization) that computes a 256-bit hash\&. 
.SH "Member Function Documentation"
.PP 
.SS "uint64_t GetCheapHash ()\fR [inline]\fP"
Returns the first 64 bits from the resulting hash\&. 
.SS "\fBuint256\fP GetHash ()\fR [inline]\fP"
Compute the double-SHA256 hash of all data written to this object\&.

.PP
Invalidates this object\&. 
.SS "\fBuint256\fP GetSHA256 ()\fR [inline]\fP"
Compute the SHA256 hash of all data written to this object\&.

.PP
Invalidates this object\&. 
.SS "template<typename \fBT\fP> \fBHashWriter\fP & operator<< (const \fBT\fP & obj)\fR [inline]\fP"

.SS "void write (std::span< const std::byte > src)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
