.TH "HashVerifier< Source >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashVerifier< Source >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hash\&.h>\fP
.PP
Inherits \fBHashWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHashVerifier\fP (Source &source \fBLIFETIMEBOUND\fP)"
.br
.ti -1c
.RI "void \fBread\fP (std::span< std::byte > dst)"
.br
.ti -1c
.RI "void \fBignore\fP (size_t num_bytes)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBHashVerifier\fP< Source > & \fBoperator>>\fP (\fBT\fP &&obj)"
.br
.in -1c

Public Member Functions inherited from \fBHashWriter\fP
.in +1c
.ti -1c
.RI "void \fBwrite\fP (std::span< const std::byte > src)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetSHA256\fP ()"
.br
.ti -1c
.RI "uint64_t \fBGetCheapHash\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBHashWriter\fP & \fBoperator<<\fP (const \fBT\fP &obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Source>
.br
class HashVerifier< Source >"Reads data from an underlying stream, while hashing the read data\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Source> \fBHashVerifier\fP (Source &source LIFETIMEBOUND)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Source> void ignore (size_t num_bytes)\fR [inline]\fP"

.SS "template<typename Source> template<typename \fBT\fP> \fBHashVerifier\fP< Source > & operator>> (\fBT\fP && obj)\fR [inline]\fP"

.SS "template<typename Source> void read (std::span< std::byte > dst)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
