.TH "src/secp256k1/src/hash_impl.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/hash_impl.h
.SH SYNOPSIS
.br
.PP
\fR#include 'hash\&.h'\fP
.br
\fR#include 'util\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCh\fP(x,  y,  z)"
.br
.ti -1c
.RI "#define \fBMaj\fP(x,  y,  z)"
.br
.ti -1c
.RI "#define \fBSigma0\fP(x)"
.br
.ti -1c
.RI "#define \fBSigma1\fP(x)"
.br
.ti -1c
.RI "#define \fBsigma0\fP(x)"
.br
.ti -1c
.RI "#define \fBsigma1\fP(x)"
.br
.ti -1c
.RI "#define \fBRound\fP(a,  b,  c,  d,  e,  f,  g,  h,  k,  w)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define Ch( x,  y,  z)"
\fBValue:\fP
.nf
((z) ^ ((x) & ((y) ^ (z))))
.PP
.fi

.SS "#define Maj( x,  y,  z)"
\fBValue:\fP
.nf
(((x) & (y)) | ((z) & ((x) | (y))))
.PP
.fi

.SS "#define Round( a,  b,  c,  d,  e,  f,  g,  h,  k,  w)"
\fBValue:\fP
.nf
    do { \\
    uint32_t t1 = (h) + Sigma1(e) + Ch((e), (f), (g)) + (k) + (w); \\
    uint32_t t2 = Sigma0(a) + Maj((a), (b), (c)); \\
    (d) += t1; \\
    (h) = t1 + t2; \\
} while(0)
.PP
.fi

.SS "#define Sigma0( x)"
\fBValue:\fP
.nf
(((x) >> 2 | (x) << 30) ^ ((x) >> 13 | (x) << 19) ^ ((x) >> 22 | (x) << 10))
.PP
.fi

.SS "#define sigma0( x)"
\fBValue:\fP
.nf
(((x) >> 7 | (x) << 25) ^ ((x) >> 18 | (x) << 14) ^ ((x) >> 3))
.PP
.fi

.SS "#define Sigma1( x)"
\fBValue:\fP
.nf
(((x) >> 6 | (x) << 26) ^ ((x) >> 11 | (x) << 21) ^ ((x) >> 25 | (x) << 7))
.PP
.fi

.SS "#define sigma1( x)"
\fBValue:\fP
.nf
(((x) >> 17 | (x) << 15) ^ ((x) >> 19 | (x) << 13) ^ ((x) >> 10))
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
