.TH "src/hash.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hash.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <hash\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br
\fR#include <crypto/common\&.h>\fP
.br
\fR#include <crypto/hmac_sha512\&.h>\fP
.br
\fR#include <bit>\fP
.br
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBMurmurHash3\fP (unsigned int nHashSeed, std::span< const unsigned char > vDataToHash)"
.br
.ti -1c
.RI "void \fBBIP32Hash\fP (const \fBChainCode\fP &chainCode, unsigned int nChild, unsigned char header, const unsigned char data[32], unsigned char output[64])"
.br
.ti -1c
.RI "\fBuint256\fP \fBSHA256Uint256\fP (const \fBuint256\fP &input)"
.br
.ti -1c
.RI "\fBHashWriter\fP \fBTaggedHash\fP (const std::string &tag)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void BIP32Hash (const \fBChainCode\fP & chainCode, unsigned int nChild, unsigned char header, const unsigned char data[32], unsigned char output[64])"

.SS "unsigned int MurmurHash3 (unsigned int nHashSeed, std::span< const unsigned char > vDataToHash)"

.SS "\fBuint256\fP SHA256Uint256 (const \fBuint256\fP & input)\fR [nodiscard]\fP"
Single-SHA256 a 32-byte input (represented as \fBuint256\fP)\&. 
.SS "\fBHashWriter\fP TaggedHash (const std::string & tag)"
Return a \fBHashWriter\fP primed for tagged hashes (as specified in BIP 340)\&.

.PP
The returned object will have SHA256(tag) written to it twice (= 64 bytes)\&. A tagged hash can be computed by feeding the message into this object, and then calling \fBHashWriter::GetSHA256()\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
