.TH "HashedSourceWriter< Source >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashedSourceWriter< Source >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hash\&.h>\fP
.PP
Inherits \fBHashWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHashedSourceWriter\fP (Source &source \fBLIFETIMEBOUND\fP)"
.br
.ti -1c
.RI "void \fBwrite\fP (std::span< const std::byte > src)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBHashedSourceWriter\fP & \fBoperator<<\fP (const \fBT\fP &obj)"
.br
.in -1c

Public Member Functions inherited from \fBHashWriter\fP
.in +1c
.ti -1c
.RI "void \fBwrite\fP (std::span< const std::byte > src)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetSHA256\fP ()"
.br
.ti -1c
.RI "uint64_t \fBGetCheapHash\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBHashWriter\fP & \fBoperator<<\fP (const \fBT\fP &obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Source>
.br
class HashedSourceWriter< Source >"Writes data to an underlying source stream, while hashing the written data\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Source> \fBHashedSourceWriter\fP (Source &source LIFETIMEBOUND)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Source> template<typename \fBT\fP> \fBHashedSourceWriter\fP & operator<< (const \fBT\fP & obj)\fR [inline]\fP"

.SS "template<typename Source> void write (std::span< const std::byte > src)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
