.TH "HasJSON" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HasJSON
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHasJSON\fP (std::string json)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBUniValue\fP &value) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHasJSON\fP (std::string json)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool operator() (const \fBUniValue\fP & value) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
