.TH "HasReason" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HasReason
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <setup_common\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHasReason\fP (std::string_view reason)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (std::string_view s) const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const std::exception &e) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
BOOST_CHECK_EXCEPTION predicates to check the specific validation error\&. Use as BOOST_CHECK_EXCEPTION(code that throws, exception type, \fBHasReason\fP("foo")); 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHasReason\fP (std::string_view reason)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool operator() (const std::exception & e) const\fR [inline]\fP"

.SS "bool operator() (std::string_view s) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
