.TH "src/headerssync.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/headerssync.h
.SH SYNOPSIS
.br
.PP
\fR#include <arith_uint256\&.h>\fP
.br
\fR#include <chain\&.h>\fP
.br
\fR#include <consensus/params\&.h>\fP
.br
\fR#include <net\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/bitdeque\&.h>\fP
.br
\fR#include <util/hasher\&.h>\fP
.br
\fR#include <deque>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBCompressedHeader\fP"
.br
.ti -1c
.RI "class \fBHeadersSyncState\fP"
.br
.ti -1c
.RI "struct \fBHeadersSyncState::ProcessingResult\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
