.TH "HeadersSyncState::ProcessingResult" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeadersSyncState::ProcessingResult
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <headerssync\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< \fBCBlockHeader\fP > \fBpow_validated_headers\fP"
.br
.ti -1c
.RI "bool \fBsuccess\fP {false}"
.br
.ti -1c
.RI "bool \fBrequest_more\fP {false}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Result data structure for ProcessNextHeaders\&. 
.SH "Field Documentation"
.PP 
.SS "std::vector<\fBCBlockHeader\fP> pow_validated_headers"

.SS "bool request_more {false}"

.SS "bool success {false}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
