.TH "HelpMessageDialog" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelpMessageDialog
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <utilitydialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHelpMessageDialog\fP (QWidget *parent, bool about)"
.br
.ti -1c
.RI "\fB~HelpMessageDialog\fP ()"
.br
.ti -1c
.RI "void \fBprintToConsole\fP ()"
.br
.ti -1c
.RI "void \fBshowOrPrint\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
"Help message" dialog box 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHelpMessageDialog\fP (QWidget * parent, bool about)\fR [explicit]\fP"
"Help message" or "About" dialog box HTML-format the license message from the core
.SS "~\fBHelpMessageDialog\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void printToConsole ()"

.SS "void showOrPrint ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
