.TH "HelpResult" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelpResult
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.PP
Inherits runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHelpResult\fP (const std::string &msg)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHelpResult\fP (const std::string & msg)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
