.TH "HitRateTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HitRateTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBasicTestingSetup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \fBCache\fP> double \fBtest_cache\fP (size_t megabytes, double load)"
.br
.in -1c

Public Member Functions inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "void \fBSeedRandomForTest\fP (\fBSeedRand\fP seed)"
.br
.ti -1c
.RI "\fBBasicTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~BasicTestingSetup\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBnormalize_hit_rate\fP (double hits, double load)"
.br
.in -1c
.SS "Additional Inherited Members"


Data Fields inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "\fButil::SignalInterrupt\fP \fBm_interrupt\fP"
.br
.ti -1c
.RI "\fBnode::NodeContext\fP \fBm_node\fP"
.br
.ti -1c
.RI "\fBFastRandomContext\fP \fBm_rng\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_root\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_lock\fP"
.br
.ti -1c
.RI "bool \fBm_has_custom_datadir\fP {false}"
.br
.ti -1c
.RI "\fBArgsManager\fP \fBm_args\fP"
.br
.RI "Test-specific arguments and settings\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "double normalize_hit_rate (double hits, double load)\fR [inline]\fP, \fR [static]\fP"
The normalized hit rate for a given load\&.

.PP
The semantics are a little confusing, so please see the below explanation\&.

.PP
Examples:

.PP
.IP "1." 4
at load 0\&.5, we expect a perfect hit rate, so we multiply by 1\&.0
.IP "2." 4
at load 2\&.0, we expect to see half the entries, so a perfect hit rate would be 0\&.5\&. Therefore, if we see a hit rate of 0\&.4, 0\&.4*2\&.0 = 0\&.8 is the normalized hit rate\&.
.PP

.PP
This is basically the right semantics, but has a bit of a glitch depending on how you measure around load 1\&.0 as after load 1\&.0 your normalized hit rate becomes effectively perfect, ignoring freshness\&. 
.SS "template<typename \fBCache\fP> double test_cache (size_t megabytes, double load)\fR [inline]\fP"
This helper returns the hit rate when megabytes*load worth of entries are inserted into a megabytes sized cache We make a copy of the hashes because future optimizations of the cuckoocache may overwrite the inserted element, so the test is "future proofed"\&.

.PP
Do the insert

.PP
Count the hits

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
