.TH "HTTPClosure" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HTTPClosure
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <httpserver\&.h>\fP
.PP
Inherited by \fBHTTPWorkItem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBoperator()\fP ()=0"
.br
.ti -1c
.RI "virtual \fB~HTTPClosure\fP ()=default"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event handler closure\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBHTTPClosure\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void operator() ()\fR [pure virtual]\fP"

.PP
Implemented in \fBHTTPWorkItem\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
