.TH "src/httprpc.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/httprpc.h
.SH SYNOPSIS
.br
.PP
\fR#include <any>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBStartHTTPRPC\fP (const std::any &context)"
.br
.ti -1c
.RI "void \fBInterruptHTTPRPC\fP ()"
.br
.ti -1c
.RI "void \fBStopHTTPRPC\fP ()"
.br
.ti -1c
.RI "void \fBStartREST\fP (const std::any &context)"
.br
.ti -1c
.RI "void \fBInterruptREST\fP ()"
.br
.ti -1c
.RI "void \fBStopREST\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void InterruptHTTPRPC ()"
Interrupt HTTP RPC subsystem\&. 
.SS "void InterruptREST ()"
Interrupt RPC REST subsystem\&. 
.SS "bool StartHTTPRPC (const std::any & context)"
Start HTTP RPC subsystem\&. Precondition; HTTP and RPC has been started\&. 
.SS "void StartREST (const std::any & context)"
Start HTTP REST subsystem\&. Precondition; HTTP and RPC has been started\&. 
.SS "void StopHTTPRPC ()"
Stop HTTP RPC subsystem\&. Precondition; HTTP and RPC has been stopped\&. 
.SS "void StopREST ()"
Stop HTTP REST subsystem\&. Precondition; HTTP and RPC has been stopped\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
