.TH "src/test/fuzz/http_request.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/http_request.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <httpserver\&.h>\fP
.br
\fR#include <netaddress\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <util/signalinterrupt\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <event2/buffer\&.h>\fP
.br
\fR#include <event2/event\&.h>\fP
.br
\fR#include <event2/http\&.h>\fP
.br
\fR#include <event2/http_struct\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBevhttp_parse_firstline_\fP (struct evhttp_request *, struct evbuffer *)"
.br
.ti -1c
.RI "int \fBevhttp_parse_headers_\fP (struct evhttp_request *, struct evbuffer *)"
.br
.ti -1c
.RI "std::string \fBRequestMethodString\fP (\fBHTTPRequest::RequestMethod\fP m)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (http_request)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int evhttp_parse_firstline_ (struct evhttp_request * , struct evbuffer * )"

.SS "int evhttp_parse_headers_ (struct evhttp_request * , struct evbuffer * )"

.SS "FUZZ_TARGET (http_request )"

.SS "std::string RequestMethodString (\fBHTTPRequest::RequestMethod\fP m)"
HTTP request method as string - use for logging only 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
