.TH "HTTPWorkItem" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HTTPWorkItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHTTPClosure\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHTTPWorkItem\fP (std::unique_ptr< \fBHTTPRequest\fP > _req, const std::string &_path, const \fBHTTPRequestHandler\fP &_func)"
.br
.ti -1c
.RI "void \fBoperator()\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBHTTPClosure\fP
.in +1c
.ti -1c
.RI "virtual \fB~HTTPClosure\fP ()=default"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBHTTPRequest\fP > \fBreq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
HTTP request work item 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHTTPWorkItem\fP (std::unique_ptr< \fBHTTPRequest\fP > _req, const std::string & _path, const \fBHTTPRequestHandler\fP & _func)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void operator() ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBHTTPClosure\fP\&.
.SH "Field Documentation"
.PP 
.SS "std::unique_ptr<\fBHTTPRequest\fP> req"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
