.TH "src/httprpc.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/httprpc.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <httprpc\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <crypto/hmac_sha256\&.h>\fP
.br
\fR#include <httpserver\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <netaddress\&.h>\fP
.br
\fR#include <rpc/protocol\&.h>\fP
.br
\fR#include <rpc/server\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/fs_helpers\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <walletinitinterface\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <iterator>\fP
.br
\fR#include <map>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <set>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBStartHTTPRPC\fP (const std::any &context)"
.br
.ti -1c
.RI "void \fBInterruptHTTPRPC\fP ()"
.br
.ti -1c
.RI "void \fBStopHTTPRPC\fP ()"
.br
.ti -1c
.RI "std::vector< std::string > \fBSplitString\fP (std::string_view str, char sep)"
.br
.ti -1c
.RI "std::string_view \fBTrimStringView\fP (std::string_view str, std::string_view pattern=' \\f\\n\\r\\t\\v')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void InterruptHTTPRPC ()"
Interrupt HTTP RPC subsystem\&. 
.SS "std::vector< std::string > SplitString (std::string_view str, char sep)\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "bool StartHTTPRPC (const std::any & context)"
Start HTTP RPC subsystem\&. Precondition; HTTP and RPC has been started\&. 
.SS "void StopHTTPRPC ()"
Stop HTTP RPC subsystem\&. Precondition; HTTP and RPC has been stopped\&. 
.SS "std::string_view TrimStringView (std::string_view str, std::string_view pattern = \fR' \\f\\n\\r\\t\\v'\fP)\fR [inline]\fP, \fR [nodiscard]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
