.TH "src/test/fuzz/i2p.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/i2p.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/args\&.h>\fP
.br
\fR#include <i2p\&.h>\fP
.br
\fR#include <netaddress\&.h>\fP
.br
\fR#include <netbase\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <test/fuzz/util/net\&.h>\fP
.br
\fR#include <test/fuzz/util/threadinterrupt\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/fs_helpers\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_i2p\fP ()"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (\fBi2p\fP,\&.\fBinit\fP=\fBinitialize_i2p\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (\fBi2p\fP , \&. init = \fR\fBinitialize_i2p\fP\fP)"

.SS "void initialize_i2p ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
