.TH "Connection" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Connection
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <i2p\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBSock\fP > \fBsock\fP"
.br
.ti -1c
.RI "\fBCService\fP \fBme\fP"
.br
.ti -1c
.RI "\fBCService\fP \fBpeer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An established connection with another peer\&. 
.SH "Field Documentation"
.PP 
.SS "\fBCService\fP me"
Our I2P address\&. 
.SS "\fBCService\fP peer"
The peer's I2P address\&. 
.SS "std::unique_ptr<\fBSock\fP> sock"
Connected socket\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
