.TH "IndexSummary" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexSummary
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <base\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "bool \fBsynced\fP {false}"
.br
.ti -1c
.RI "int \fBbest_block_height\fP {0}"
.br
.ti -1c
.RI "\fBuint256\fP \fBbest_block_hash\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP best_block_hash"

.SS "int best_block_height {0}"

.SS "std::string name"

.SS "bool synced {false}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
