.TH "indirectmap< K, T >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
indirectmap< K, T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <indirectmap\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef base::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef base::const_iterator \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef base::size_type \fBsize_type\fP"
.br
.ti -1c
.RI "typedef base::value_type \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::pair< \fBiterator\fP, bool > \fBinsert\fP (const \fBvalue_type\fP &value)"
.br
.ti -1c
.RI "\fBiterator\fP \fBfind\fP (const K &key)"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBfind\fP (const K &key) const"
.br
.ti -1c
.RI "\fBiterator\fP \fBlower_bound\fP (const K &key)"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBlower_bound\fP (const K &key) const"
.br
.ti -1c
.RI "\fBsize_type\fP \fBerase\fP (const K &key)"
.br
.ti -1c
.RI "\fBsize_type\fP \fBcount\fP (const K &key) const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "\fBsize_type\fP \fBsize\fP () const"
.br
.ti -1c
.RI "\fBsize_type\fP \fBmax_size\fP () const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBend\fP () const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBcbegin\fP () const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBcend\fP () const"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<class K, class \fBT\fP> typedef base::const_iterator \fBconst_iterator\fP"

.SS "template<class K, class \fBT\fP> typedef base::iterator \fBiterator\fP"

.SS "template<class K, class \fBT\fP> typedef base::size_type \fBsize_type\fP"

.SS "template<class K, class \fBT\fP> typedef base::value_type \fBvalue_type\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class K, class \fBT\fP> \fBiterator\fP begin ()\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBconst_iterator\fP begin () const\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBconst_iterator\fP cbegin () const\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBconst_iterator\fP cend () const\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> void clear ()\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBsize_type\fP count (const K & key) const\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> bool empty () const\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBiterator\fP end ()\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBconst_iterator\fP end () const\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBsize_type\fP erase (const K & key)\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBiterator\fP find (const K & key)\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBconst_iterator\fP find (const K & key) const\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> std::pair< \fBiterator\fP, bool > insert (const \fBvalue_type\fP & value)\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBiterator\fP lower_bound (const K & key)\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBconst_iterator\fP lower_bound (const K & key) const\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBsize_type\fP max_size () const\fR [inline]\fP"

.SS "template<class K, class \fBT\fP> \fBsize_type\fP size () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
