.TH "src/ipc/libmultiprocess/example/init.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc/libmultiprocess/example/init.h
.SH SYNOPSIS
.br
.PP
\fR#include <calculator\&.h>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <printer\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBInit\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
