.TH "InitExecutor" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InitExecutor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <initexecutor\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "void \fBshutdown\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBinitializeResult\fP (bool success, \fBinterfaces::BlockAndHeaderTipInfo\fP tip_info)"
.br
.ti -1c
.RI "void \fBshutdownResult\fP ()"
.br
.ti -1c
.RI "void \fBrunawayException\fP (const QString &message)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInitExecutor\fP (\fBinterfaces::Node\fP &\fBnode\fP)"
.br
.ti -1c
.RI "\fB~InitExecutor\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class encapsulating Bitcoin Core startup and shutdown\&. Allows running startup and shutdown in a different thread from the UI thread\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBInitExecutor\fP (\fBinterfaces::Node\fP & node)\fR [explicit]\fP"

.SS "~\fBInitExecutor\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void initialize ()\fR [slot]\fP"

.SS "void initializeResult (bool success, \fBinterfaces::BlockAndHeaderTipInfo\fP tip_info)\fR [signal]\fP"

.SS "void runawayException (const QString & message)\fR [signal]\fP"

.SS "void shutdown ()\fR [slot]\fP"

.SS "void shutdownResult ()\fR [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
