.TH "InitImpl" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InitImpl
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBInit\fP, and \fBInit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBCalculator\fP > \fBmakeCalculator\fP (std::unique_ptr< \fBPrinter\fP > printer) override"
.br
.ti -1c
.RI "std::unique_ptr< \fBPrinter\fP > \fBmakePrinter\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBInit\fP
.in +1c
.ti -1c
.RI "virtual \fB~Init\fP ()=default"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::unique_ptr< \fBCalculator\fP > makeCalculator (std::unique_ptr< \fBPrinter\fP > printer)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBInit\fP\&.
.SS "std::unique_ptr< \fBPrinter\fP > makePrinter ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBInit\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
