.TH "InsecureRandomContext" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InsecureRandomContext
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <random\&.h>\fP
.PP
Inherits \fBRandomMixin< InsecureRandomContext >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBInsecureRandomContext\fP (uint64_t seedval) noexcept"
.br
.ti -1c
.RI "constexpr void \fBReseed\fP (uint64_t seedval) noexcept"
.br
.ti -1c
.RI "constexpr uint64_t \fBrand64\fP () noexcept"
.br
.in -1c

Public Member Functions inherited from \fBRandomMixin< InsecureRandomContext >\fP
.in +1c
.ti -1c
.RI "constexpr \fBRandomMixin\fP () noexcept=default"
.br
.ti -1c
.RI "\fBRandomMixin\fP & \fBoperator=\fP (const \fBRandomMixin\fP &)=delete"
.br
.ti -1c
.RI "uint64_t \fBrandbits\fP (int bits) noexcept"
.br
.ti -1c
.RI "I \fBrandrange\fP (I range) noexcept"
.br
.ti -1c
.RI "void \fBfillrand\fP (std::span< std::byte > span) noexcept"
.br
.ti -1c
.RI "I \fBrand\fP () noexcept"
.br
.ti -1c
.RI "std::vector< \fBB\fP > \fBrandbytes\fP (size_t len) noexcept"
.br
.ti -1c
.RI "uint32_t \fBrand32\fP () noexcept"
.br
.ti -1c
.RI "\fBuint256\fP \fBrand256\fP () noexcept"
.br
.ti -1c
.RI "bool \fBrandbool\fP () noexcept"
.br
.ti -1c
.RI "Tp \fBrand_uniform_delay\fP (const Tp &time, typename Tp::duration range) noexcept"
.br
.ti -1c
.RI "Chrono::duration \fBrand_uniform_duration\fP (typename Chrono::duration range) noexcept"
.br
.ti -1c
.RI "std::chrono::microseconds \fBrand_exp_duration\fP (std::chrono::microseconds mean) noexcept"
.br
.ti -1c
.RI "uint64_t \fBoperator()\fP () noexcept"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBRandomMixin< InsecureRandomContext >\fP
.in +1c
.ti -1c
.RI "typedef uint64_t \fBresult_type\fP"
.br
.in -1c

Static Public Member Functions inherited from \fBRandomMixin< InsecureRandomContext >\fP
.in +1c
.ti -1c
.RI "static constexpr uint64_t \fBmin\fP () noexcept"
.br
.ti -1c
.RI "static constexpr uint64_t \fBmax\fP () noexcept"
.br
.in -1c

Protected Member Functions inherited from \fBRandomMixin< InsecureRandomContext >\fP
.in +1c
.ti -1c
.RI "constexpr void \fBFlushCache\fP () noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
xoroshiro128++ PRNG\&. Extremely fast, not appropriate for cryptographic purposes\&.

.PP
Memory footprint is very small, period is 2^128 - 1\&. This class is not thread-safe\&.

.PP
Reference implementation available at https://prng.di.unimi.it/xoroshiro128plusplus.c See https://prng.di.unimi.it/ 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBInsecureRandomContext\fP (uint64_t seedval)\fR [inline]\fP, \fR [explicit]\fP, \fR [constexpr]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "uint64_t rand64 ()\fR [inline]\fP, \fR [constexpr]\fP, \fR [noexcept]\fP"

.SS "void Reseed (uint64_t seedval)\fR [inline]\fP, \fR [constexpr]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
