.TH "src/util/insert.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/insert.h
.SH SYNOPSIS
.br
.PP
\fR#include <set>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButil\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Tdst, typename Tsrc> void \fBinsert\fP (Tdst &dst, const Tsrc &src)"
.br
.RI "Simplification of std insertion\&. "
.ti -1c
.RI "template<typename TsetT, typename Tsrc> void \fBinsert\fP (std::set< TsetT > &dst, const Tsrc &src)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
