.TH "src/secp256k1/src/int128_native.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/int128_native.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include 'util\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint128_t \fBsecp256k1_uint128\fP"
.br
.ti -1c
.RI "typedef int128_t \fBsecp256k1_int128\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int128_t \fBsecp256k1_int128\fP"

.SS "typedef uint128_t secp256k1_uint128"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
