.TH "src/secp256k1/src/int128_struct.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/int128_struct.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include 'util\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsecp256k1_uint128\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBsecp256k1_uint128\fP \fBsecp256k1_int128\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBsecp256k1_uint128\fP \fBsecp256k1_int128\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
