.TH "src/minisketch/src/int_utils.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/minisketch/src/int_utils.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <limits>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <type_traits>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBitWriter\fP"
.br
.ti -1c
.RI "class \fBBitReader\fP"
.br
.ti -1c
.RI "class \fBBitsInt< I, BITS >\fP"
.br
.ti -1c
.RI "struct \fBLFSR< F, MOD >\fP"
.br
.ti -1c
.RI "struct \fBGFMulHelper< I, N, L, F, 0 >\fP"
.br
.ti -1c
.RI "struct \fBGFMulHelper< I, N, L, F, K >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBSipHash\fP (uint64_t k0, uint64_t k1, uint64_t data)"
.br
.ti -1c
.RI "template<int BITS, typename I> constexpr I \fBMask\fP ()"
.br
.ti -1c
.RI "template<typename I, int N, typename L, typename F> constexpr I \fBGFMul\fP (const I &a, const I &b)"
.br
.ti -1c
.RI "template<typename I, typename F, int BITS, uint32_t MOD> I \fBInvExtGCD\fP (I x)"
.br
.ti -1c
.RI "template<typename I, typename F, int BITS, I(*)(I, I) MUL, I(*)(I) SQR, I(*)(I) SQR2, I(*)(I) SQR4, I(*)(I) SQR8, I(*)(I) SQR16> I \fBInvLadder\fP (I x1)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename I, int N, typename L, typename F> I GFMul (const I & a, const I & b)\fR [inline]\fP, \fR [constexpr]\fP"
Compute the carry-less multiplication of a and b, with N bits, using L as \fBLFSR\fP type\&. 
.SS "template<typename I, typename F, int BITS, uint32_t MOD> I InvExtGCD (I x)\fR [inline]\fP"
Compute the inverse of x using an extgcd algorithm\&. 
.SS "template<typename I, typename F, int BITS, I(*)(I, I) MUL, I(*)(I) SQR, I(*)(I) SQR2, I(*)(I) SQR4, I(*)(I) SQR8, I(*)(I) SQR16> I InvLadder (I x1)\fR [inline]\fP"
Compute the inverse of x1 using an exponentiation ladder\&.

.PP
The \fRMUL\fP argument is a multiplication function, \fRSQR\fP is a squaring function, and the \fRSQRi\fP arguments compute x**(2**i)\&. 
.SS "template<int BITS, typename I> I Mask ()\fR [inline]\fP, \fR [constexpr]\fP"
Return a value of type I with its \fRbits\fP lowest bits set (bits must be > 0)\&. 
.SS "uint64_t SipHash (uint64_t k0, uint64_t k1, uint64_t data)\fR [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
