.TH "src/node/interface_ui.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/interface_ui.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/interface_ui\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <boost/signals2/optional_last_value\&.hpp>\fP
.br
\fR#include <boost/signals2/signal\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBUISignals\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADD_SIGNALS_IMPL_WRAPPER\fP(signal_name)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (ThreadSafeMessageBox)"
.br
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (ThreadSafeQuestion)"
.br
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (InitMessage)"
.br
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (InitWallet)"
.br
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (NotifyNumConnectionsChanged)"
.br
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (NotifyNetworkActiveChanged)"
.br
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (NotifyAlertChanged)"
.br
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (ShowProgress)"
.br
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (NotifyBlockTip)"
.br
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (NotifyHeaderTip)"
.br
.ti -1c
.RI "\fBADD_SIGNALS_IMPL_WRAPPER\fP (BannedListChanged)"
.br
.ti -1c
.RI "bool \fBInitError\fP (const \fBbilingual_str\fP &str)"
.br
.ti -1c
.RI "bool \fBInitError\fP (const \fBbilingual_str\fP &str, const std::vector< std::string > &details)"
.br
.ti -1c
.RI "void \fBInitWarning\fP (const \fBbilingual_str\fP &str)"
.br
.ti -1c
.RI "std::string \fBMakeUnorderedList\fP (const std::vector< std::string > &items)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCClientUIInterface\fP \fBuiInterface\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADD_SIGNALS_IMPL_WRAPPER( signal_name)"
\fBValue:\fP
.nf
    boost::signals2::connection CClientUIInterface::signal_name##_connect(std::function<signal_name##Sig> fn) \\
    {                                                                                                         \\
        return g_ui_signals\&.signal_name\&.connect(fn);                                                          \\
    }
.PP
.fi

.SH "Function Documentation"
.PP 
.SS "ADD_SIGNALS_IMPL_WRAPPER (BannedListChanged )"

.SS "ADD_SIGNALS_IMPL_WRAPPER (InitMessage )"

.SS "ADD_SIGNALS_IMPL_WRAPPER (InitWallet )"

.SS "ADD_SIGNALS_IMPL_WRAPPER (NotifyAlertChanged )"

.SS "ADD_SIGNALS_IMPL_WRAPPER (NotifyBlockTip )"

.SS "ADD_SIGNALS_IMPL_WRAPPER (NotifyHeaderTip )"

.SS "ADD_SIGNALS_IMPL_WRAPPER (NotifyNetworkActiveChanged )"

.SS "ADD_SIGNALS_IMPL_WRAPPER (NotifyNumConnectionsChanged )"

.SS "ADD_SIGNALS_IMPL_WRAPPER (ShowProgress )"

.SS "ADD_SIGNALS_IMPL_WRAPPER (ThreadSafeMessageBox )"

.SS "ADD_SIGNALS_IMPL_WRAPPER (ThreadSafeQuestion )"

.SS "bool InitError (const \fBbilingual_str\fP & str)"
Show error message 
.SS "bool InitError (const \fBbilingual_str\fP & str, const std::vector< std::string > & details)"

.SS "void InitWarning (const \fBbilingual_str\fP & str)"
Show warning message 
.SS "std::string MakeUnorderedList (const std::vector< std::string > & items)\fR [inline]\fP"
Create an unordered multi-line list of items\&. 
.SH "Variable Documentation"
.PP 
.SS "\fBCClientUIInterface\fP uiInterface"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
