.TH "BlockRef" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockRef \- Hash/height pair to help track and identify blocks\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBhash\fP"
.br
.ti -1c
.RI "int \fBheight\fP = \-1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Hash/height pair to help track and identify blocks\&. 
.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP hash"

.SS "int height = \-1"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
