.TH "src/test/fuzz/integer.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/integer.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <arith_uint256\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <common/system\&.h>\fP
.br
\fR#include <compressor\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <consensus/merkle\&.h>\fP
.br
\fR#include <core_io\&.h>\fP
.br
\fR#include <crypto/common\&.h>\fP
.br
\fR#include <crypto/siphash\&.h>\fP
.br
\fR#include <key_io\&.h>\fP
.br
\fR#include <memusage\&.h>\fP
.br
\fR#include <netbase\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <policy/settings\&.h>\fP
.br
\fR#include <pow\&.h>\fP
.br
\fR#include <protocol\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/moneystr\&.h>\fP
.br
\fR#include <util/overflow\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <limits>\fP
.br
\fR#include <set>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_integer\fP ()"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (integer,\&.\fBinit\fP=\fBinitialize_integer\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::string \fBToString\fP (const \fBT\fP &t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (integer , \&. init = \fR\fBinitialize_integer\fP\fP)"

.SS "void initialize_integer ()"

.SS "template<typename \fBT\fP> std::string ToString (const \fBT\fP & t)"
Locale-independent version of std::to_string 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
