.TH "ExternalSigner" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSigner \- External signer interface used by the GUI\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <node\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ExternalSigner\fP ()=default"
.br
.ti -1c
.RI "virtual std::string \fBgetName\fP ()=0"
.br
.RI "Get signer display name\&. "
.in -1c
.SH "Detailed Description"
.PP 
External signer interface used by the GUI\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBExternalSigner\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::string getName ()\fR [pure virtual]\fP"

.PP
Get signer display name\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
