.TH "interfaces" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interfaces
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFoundBlock\fP"
.br
.ti -1c
.RI "class \fBChain\fP"
.br
.ti -1c
.RI "class \fBChainClient\fP"
.br
.ti -1c
.RI "class \fBEcho\fP"
.br
.RI "Simple string echoing interface for testing\&. "
.ti -1c
.RI "class \fBHandler\fP"
.br
.ti -1c
.RI "class \fBInit\fP"
.br
.ti -1c
.RI "class \fBIpc\fP"
.br
.ti -1c
.RI "class \fBBlockTemplate\fP"
.br
.RI "Block template interface\&. "
.ti -1c
.RI "class \fBMining\fP"
.br
.ti -1c
.RI "struct \fBBlockAndHeaderTipInfo\fP"
.br
.RI "Block and header tip information\&. "
.ti -1c
.RI "class \fBExternalSigner\fP"
.br
.RI "External signer interface used by the GUI\&. "
.ti -1c
.RI "class \fBNode\fP"
.br
.RI "Top-level interface for a bitcoin node (bitcoind process)\&. "
.ti -1c
.RI "struct \fBBlockTip\fP"
.br
.RI "Block tip (could be a header or not, depends on the subscribed signal)\&. "
.ti -1c
.RI "struct \fBBlockRef\fP"
.br
.RI "Hash/height pair to help track and identify blocks\&. "
.ti -1c
.RI "class \fBWallet\fP"
.br
.RI "Interface for accessing a wallet\&. "
.ti -1c
.RI "class \fBWalletLoader\fP"
.br
.ti -1c
.RI "struct \fBWalletAddress\fP"
.br
.RI "Information about one wallet address\&. "
.ti -1c
.RI "struct \fBWalletBalances\fP"
.br
.RI "Collection of wallet balances\&. "
.ti -1c
.RI "struct \fBWalletTx\fP"
.br
.ti -1c
.RI "struct \fBWalletTxStatus\fP"
.br
.RI "Updated transaction status\&. "
.ti -1c
.RI "struct \fBWalletTxOut\fP"
.br
.RI "\fBWallet\fP transaction output\&. "
.ti -1c
.RI "struct \fBWalletMigrationResult\fP"
.br
.RI "Migrated wallet info\&. "
.ti -1c
.RI "struct \fBBlockInfo\fP"
.br
.RI "Block data sent with blockConnected, blockDisconnected notifications\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBSettingsUpdate\fP = std::function<std::optional<\fBinterfaces::SettingsAction\fP>(\fBcommon::SettingsValue\fP&)>"
.br
.ti -1c
.RI "using \fBWalletOrderForm\fP = std::vector<std::pair<std::string, std::string>>"
.br
.ti -1c
.RI "using \fBWalletValueMap\fP = std::map<std::string, std::string>"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBSettingsAction\fP { \fBWRITE\fP, \fBSKIP_WRITE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBHandler\fP > \fBMakeCleanupHandler\fP (std::function< void()> cleanup)"
.br
.RI "Return handler wrapping a cleanup function\&. "
.ti -1c
.RI "std::unique_ptr< \fBHandler\fP > \fBMakeSignalHandler\fP (boost::signals2::connection connection)"
.br
.RI "Return handler wrapping a boost signal connection\&. "
.ti -1c
.RI "std::unique_ptr< \fBEcho\fP > \fBMakeEcho\fP ()"
.br
.RI "Return implementation of \fBEcho\fP interface\&. "
.ti -1c
.RI "std::unique_ptr< \fBWalletLoader\fP > \fBMakeWalletLoader\fP (\fBChain\fP &chain, \fBArgsManager\fP &\fBargs\fP)"
.br
.ti -1c
.RI "std::unique_ptr< \fBInit\fP > \fBMakeGuiInit\fP (int argc, char *argv[])"
.br
.RI "Return implementation of \fBInit\fP interface for the gui process\&. "
.ti -1c
.RI "std::unique_ptr< \fBInit\fP > \fBMakeNodeInit\fP (\fBnode::NodeContext\fP &\fBnode\fP, int argc, char *argv[], int &\fBexit_status\fP)"
.br
.ti -1c
.RI "std::unique_ptr< \fBInit\fP > \fBMakeWalletInit\fP (int argc, char *argv[], int &\fBexit_status\fP)"
.br
.RI "Return implementation of \fBInit\fP interface for the wallet process\&. "
.ti -1c
.RI "std::unique_ptr< \fBChain\fP > \fBMakeChain\fP (\fBnode::NodeContext\fP &\fBnode\fP)"
.br
.RI "Return implementation of \fBChain\fP interface\&. "
.ti -1c
.RI "std::unique_ptr< \fBIpc\fP > \fBMakeIpc\fP (const char *exe_name, const char *process_argv0, \fBInit\fP &\fBinit\fP)"
.br
.RI "Return implementation of \fBIpc\fP interface\&. "
.ti -1c
.RI "std::unique_ptr< \fBMining\fP > \fBMakeMining\fP (\fBnode::NodeContext\fP &\fBnode\fP)"
.br
.RI "Return implementation of \fBMining\fP interface\&. "
.ti -1c
.RI "std::unique_ptr< \fBNode\fP > \fBMakeNode\fP (\fBnode::NodeContext\fP &context)"
.br
.RI "Return implementation of \fBNode\fP interface\&. "
.ti -1c
.RI "std::unique_ptr< \fBWallet\fP > \fBMakeWallet\fP (\fBwallet::WalletContext\fP &context, const std::shared_ptr< \fBwallet::CWallet\fP > &\fBwallet\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBSettingsUpdate\fP = std::function<std::optional<\fBinterfaces::SettingsAction\fP>(\fBcommon::SettingsValue\fP&)>"

.SS "using \fBWalletOrderForm\fP = std::vector<std::pair<std::string, std::string>>"

.SS "using \fBWalletValueMap\fP = std::map<std::string, std::string>"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBSettingsAction\fP\fR [strong]\fP"
The action to be taken after updating a settings value\&. WRITE indicates that the updated value must be written to disk, while SKIP_WRITE indicates that the change will be kept in memory-only without persisting it\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIWRITE \fP
.TP
\f(BISKIP_WRITE \fP
.SH "Function Documentation"
.PP 
.SS "std::unique_ptr< \fBChain\fP > MakeChain (\fBnode::NodeContext\fP & node)"

.PP
Return implementation of \fBChain\fP interface\&. 
.SS "std::unique_ptr< \fBHandler\fP > MakeCleanupHandler (std::function< void()> cleanup)"

.PP
Return handler wrapping a cleanup function\&. 
.SS "std::unique_ptr< \fBEcho\fP > MakeEcho ()"

.PP
Return implementation of \fBEcho\fP interface\&. 
.SS "std::unique_ptr< \fBInit\fP > MakeGuiInit (int argc, char * argv[])"

.PP
Return implementation of \fBInit\fP interface for the gui process\&. 
.SS "std::unique_ptr< \fBIpc\fP > MakeIpc (const char * exe_name, const char * process_argv0, \fBInit\fP & init)"

.PP
Return implementation of \fBIpc\fP interface\&. 
.SS "std::unique_ptr< \fBMining\fP > MakeMining (\fBnode::NodeContext\fP & node)"

.PP
Return implementation of \fBMining\fP interface\&. 
.SS "std::unique_ptr< \fBNode\fP > MakeNode (\fBnode::NodeContext\fP & context)"

.PP
Return implementation of \fBNode\fP interface\&. 
.SS "std::unique_ptr< \fBInit\fP > MakeNodeInit (\fBnode::NodeContext\fP & node, int argc, char * argv[], int & exit_status)"
Return implementation of \fBInit\fP interface for the node process\&. If the argv indicates that this is a child process spawned to handle requests from a parent process, this blocks and handles requests, then returns null and a status code to exit with\&. If this returns non-null, the caller can start up normally and use the \fBInit\fP object to spawn and connect to other processes while it is running\&. 
.SS "std::unique_ptr< \fBHandler\fP > MakeSignalHandler (boost::signals2::connection connection)"

.PP
Return handler wrapping a boost signal connection\&. 
.SS "std::unique_ptr< \fBWallet\fP > MakeWallet (\fBwallet::WalletContext\fP & context, const std::shared_ptr< \fBwallet::CWallet\fP > & wallet)"
Return implementation of \fBWallet\fP interface\&. This function is defined in \fBdummywallet\&.cpp\fP and throws if the wallet component is not compiled\&. 
.SS "std::unique_ptr< \fBInit\fP > MakeWalletInit (int argc, char * argv[], int & exit_status)"

.PP
Return implementation of \fBInit\fP interface for the wallet process\&. 
.SS "std::unique_ptr< \fBWalletLoader\fP > MakeWalletLoader (\fBChain\fP & chain, \fBArgsManager\fP & args)"
Return implementation of \fBChainClient\fP interface for a wallet loader\&. This function will be undefined in builds where ENABLE_WALLET is false\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
