.TH "Echo" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Echo \- Simple string echoing interface for testing\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <echo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Echo\fP ()=default"
.br
.ti -1c
.RI "virtual std::string \fBecho\fP (const std::string &echo)=0"
.br
.RI "\fBEcho\fP provided string\&. "
.in -1c
.SH "Detailed Description"
.PP 
Simple string echoing interface for testing\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBEcho\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::string echo (const std::string & echo)\fR [pure virtual]\fP"

.PP
\fBEcho\fP provided string\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
