.TH "ChainClient" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChainClient
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <chain\&.h>\fP
.PP
Inherited by \fBWalletLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ChainClient\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBregisterRpcs\fP ()=0"
.br
.RI "Register rpcs\&. "
.ti -1c
.RI "virtual bool \fBverify\fP ()=0"
.br
.RI "Check for errors before loading\&. "
.ti -1c
.RI "virtual bool \fBload\fP ()=0"
.br
.RI "Load saved state\&. "
.ti -1c
.RI "virtual void \fBstart\fP (\fBCScheduler\fP &scheduler)=0"
.br
.RI "Start client execution and provide a scheduler\&. "
.ti -1c
.RI "virtual void \fBstop\fP ()=0"
.br
.RI "Shut down client\&. "
.ti -1c
.RI "virtual void \fBsetMockTime\fP (int64_t time)=0"
.br
.RI "Set mock time\&. "
.ti -1c
.RI "virtual void \fBschedulerMockForward\fP (std::chrono::seconds delta_seconds)=0"
.br
.RI "Mock the scheduler to fast forward in time\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface to let node manage chain clients (wallets, or maybe tools for monitoring and analysis in the future)\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBChainClient\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool load ()\fR [pure virtual]\fP"

.PP
Load saved state\&. 
.SS "virtual void registerRpcs ()\fR [pure virtual]\fP"

.PP
Register rpcs\&. 
.SS "virtual void schedulerMockForward (std::chrono::seconds delta_seconds)\fR [pure virtual]\fP"

.PP
Mock the scheduler to fast forward in time\&. 
.SS "virtual void setMockTime (int64_t time)\fR [pure virtual]\fP"

.PP
Set mock time\&. 
.SS "virtual void start (\fBCScheduler\fP & scheduler)\fR [pure virtual]\fP"

.PP
Start client execution and provide a scheduler\&. 
.SS "virtual void stop ()\fR [pure virtual]\fP"

.PP
Shut down client\&. 
.SS "virtual bool verify ()\fR [pure virtual]\fP"

.PP
Check for errors before loading\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
