.TH "Mining" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mining
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mining\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Mining\fP ()=default"
.br
.ti -1c
.RI "virtual bool \fBisTestChain\fP ()=0"
.br
.RI "If this chain is exclusively used for testing\&. "
.ti -1c
.RI "virtual bool \fBisInitialBlockDownload\fP ()=0"
.br
.RI "Returns whether IBD is still in progress\&. "
.ti -1c
.RI "virtual std::optional< \fBBlockRef\fP > \fBgetTip\fP ()=0"
.br
.RI "Returns the hash and height for the tip of this chain\&. "
.ti -1c
.RI "virtual std::optional< \fBBlockRef\fP > \fBwaitTipChanged\fP (\fBuint256\fP current_tip, \fBMillisecondsDouble\fP timeout=MillisecondsDouble::max())=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBBlockTemplate\fP > \fBcreateNewBlock\fP (const \fBnode::BlockCreateOptions\fP &options={})=0"
.br
.ti -1c
.RI "virtual bool \fBcheckBlock\fP (const \fBCBlock\fP &block, const \fBnode::BlockCheckOptions\fP &options, std::string &reason, std::string &debug)=0"
.br
.ti -1c
.RI "virtual \fBnode::NodeContext\fP * \fBcontext\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface giving clients (RPC, Stratum v2 Template Provider in the future) ability to create block templates\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBMining\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool checkBlock (const \fBCBlock\fP & block, const \fBnode::BlockCheckOptions\fP & options, std::string & reason, std::string & debug)\fR [pure virtual]\fP"
Checks if a given block is valid\&.

.PP
\fBParameters\fP
.RS 4
\fIblock\fP the block to check 
.br
\fIoptions\fP verification options: the proof-of-work check can be skipped in order to verify a template generated by external software\&. 
.br
\fIreason\fP failure reason (BIP22) 
.br
\fIdebug\fP more detailed rejection reason 
.RE
.PP
\fBReturns\fP
.RS 4
whether the block is valid
.RE
.PP
For signets the challenge verification is skipped when check_pow is false\&. 
.SS "virtual \fBnode::NodeContext\fP * context ()\fR [inline]\fP, \fR [virtual]\fP"
Get internal node context\&. Useful for RPC and testing, but not accessible across processes\&. 
.SS "virtual std::unique_ptr< \fBBlockTemplate\fP > createNewBlock (const \fBnode::BlockCreateOptions\fP & options = \fR{}\fP)\fR [pure virtual]\fP"
Construct a new block template\&.

.PP
During node initialization, this will wait until the tip is connected\&.

.PP
\fBParameters\fP
.RS 4
\fIoptions\fP options for creating the block 
.RE
.PP
\fBReturn values\fP
.RS 4
\fI\fBBlockTemplate\fP\fP a block template\&. 
.br
\fIstd::nullptr\fP if the node is shut down\&. 
.RE
.PP

.SS "virtual std::optional< \fBBlockRef\fP > getTip ()\fR [pure virtual]\fP"

.PP
Returns the hash and height for the tip of this chain\&. 
.SS "virtual bool isInitialBlockDownload ()\fR [pure virtual]\fP"

.PP
Returns whether IBD is still in progress\&. 
.SS "virtual bool isTestChain ()\fR [pure virtual]\fP"

.PP
If this chain is exclusively used for testing\&. 
.SS "virtual std::optional< \fBBlockRef\fP > waitTipChanged (\fBuint256\fP current_tip, \fBMillisecondsDouble\fP timeout = \fRMillisecondsDouble::max()\fP)\fR [pure virtual]\fP"
Waits for the connected tip to change\&. During node initialization, this will wait until the tip is connected (regardless of \fRtimeout\fP)\&.

.PP
\fBParameters\fP
.RS 4
\fIcurrent_tip\fP block hash of the current chain tip\&. Function waits for the chain tip to differ from this\&. 
.br
\fItimeout\fP how long to wait for a new tip (default is forever)
.RE
.PP
\fBReturn values\fP
.RS 4
\fI\fBBlockRef\fP\fP hash and height of the current chain tip after this call\&. 
.br
\fIstd::nullopt\fP if the node is shut down\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
