.TH "src/wallet/interfaces.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/interfaces.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <interfaces/wallet\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <interfaces/chain\&.h>\fP
.br
\fR#include <interfaces/handler\&.h>\fP
.br
\fR#include <node/types\&.h>\fP
.br
\fR#include <policy/fees/block_policy_estimator\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <rpc/server\&.h>\fP
.br
\fR#include <scheduler\&.h>\fP
.br
\fR#include <support/allocators/secure\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <util/ui_change_type\&.h>\fP
.br
\fR#include <wallet/coincontrol\&.h>\fP
.br
\fR#include <wallet/context\&.h>\fP
.br
\fR#include <wallet/feebumper\&.h>\fP
.br
\fR#include <wallet/fees\&.h>\fP
.br
\fR#include <wallet/load\&.h>\fP
.br
\fR#include <wallet/receive\&.h>\fP
.br
\fR#include <wallet/rpc/wallet\&.h>\fP
.br
\fR#include <wallet/spend\&.h>\fP
.br
\fR#include <wallet/wallet\&.h>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <string>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWallet\fP"
.br
.RI "Interface for accessing a wallet\&. "
.ti -1c
.RI "struct \fBWalletAddress\fP"
.br
.RI "Information about one wallet address\&. "
.ti -1c
.RI "struct \fBWalletBalances\fP"
.br
.RI "Collection of wallet balances\&. "
.ti -1c
.RI "struct \fBWalletMigrationResult\fP"
.br
.RI "Migrated wallet info\&. "
.ti -1c
.RI "struct \fBWalletTx\fP"
.br
.ti -1c
.RI "struct \fBWalletTxOut\fP"
.br
.RI "\fBWallet\fP transaction output\&. "
.ti -1c
.RI "struct \fBWalletTxStatus\fP"
.br
.RI "Updated transaction status\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.ti -1c
.RI "namespace \fBinterfaces\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBWalletOrderForm\fP"
.br
.ti -1c
.RI "using \fBWalletValueMap\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBPSBTError\fP "
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBWallet\fP > \fBMakeWallet\fP (\fBwallet::WalletContext\fP &context, const std::shared_ptr< \fBwallet::CWallet\fP > &\fBwallet\fP)"
.br
.ti -1c
.RI "std::unique_ptr< \fBWalletLoader\fP > \fBMakeWalletLoader\fP (\fBChain\fP &chain, \fBArgsManager\fP &\fBargs\fP)"
.br
.ti -1c
.RI "std::unique_ptr< \fBHandler\fP > \fBMakeSignalHandler\fP (boost::signals2::connection connection)"
.br
.RI "Return handler wrapping a boost signal connection\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBWalletOrderForm\fP"

.SS "using \fBWalletValueMap\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBPSBTError\fP\fR [strong]\fP"

.SH "Function Documentation"
.PP 
.SS "std::unique_ptr< \fBHandler\fP > MakeSignalHandler (boost::signals2::connection connection)"

.PP
Return handler wrapping a boost signal connection\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
