.TH "Chain::Notifications" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Chain::Notifications \- \fBChain\fP notifications\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <chain\&.h>\fP
.PP
Inherited by \fBCWallet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Notifications\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBtransactionAddedToMempool\fP (const \fBCTransactionRef\fP &tx)"
.br
.ti -1c
.RI "virtual void \fBtransactionRemovedFromMempool\fP (const \fBCTransactionRef\fP &tx, \fBMemPoolRemovalReason\fP reason)"
.br
.ti -1c
.RI "virtual void \fBblockConnected\fP (const \fBkernel::ChainstateRole\fP &role, const \fBBlockInfo\fP &block)"
.br
.ti -1c
.RI "virtual void \fBblockDisconnected\fP (const \fBBlockInfo\fP &block)"
.br
.ti -1c
.RI "virtual void \fBupdatedBlockTip\fP ()"
.br
.ti -1c
.RI "virtual void \fBchainStateFlushed\fP (const \fBkernel::ChainstateRole\fP &role, const \fBCBlockLocator\fP &locator)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBChain\fP notifications\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBNotifications\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void blockConnected (const \fBkernel::ChainstateRole\fP & role, const \fBBlockInfo\fP & block)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCWallet\fP, and \fBCWallet\fP\&.
.SS "virtual void blockDisconnected (const \fBBlockInfo\fP & block)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCWallet\fP, and \fBCWallet\fP\&.
.SS "virtual void chainStateFlushed (const \fBkernel::ChainstateRole\fP & role, const \fBCBlockLocator\fP & locator)\fR [inline]\fP, \fR [virtual]\fP"

.SS "virtual void transactionAddedToMempool (const \fBCTransactionRef\fP & tx)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCWallet\fP, and \fBCWallet\fP\&.
.SS "virtual void transactionRemovedFromMempool (const \fBCTransactionRef\fP & tx, \fBMemPoolRemovalReason\fP reason)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCWallet\fP, and \fBCWallet\fP\&.
.SS "virtual void updatedBlockTip ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCWallet\fP, and \fBCWallet\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
