.TH "Node" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node \- Top-level interface for a bitcoin node (bitcoind process)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <node\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBNodesStats\fP = std::vector<std::tuple<\fBCNodeStats\fP, bool, \fBCNodeStateStats\fP>>"
.br
.RI "Get stats for connected nodes\&. "
.ti -1c
.RI "using \fBInitMessageFn\fP = std::function<void(const std::string& message)>"
.br
.RI "Register handler for init messages\&. "
.ti -1c
.RI "using \fBMessageBoxFn\fP"
.br
.RI "Register handler for message box messages\&. "
.ti -1c
.RI "using \fBQuestionFn\fP"
.br
.RI "Register handler for question messages\&. "
.ti -1c
.RI "using \fBShowProgressFn\fP = std::function<void(const std::string& title, int progress, bool resume_possible)>"
.br
.RI "Register handler for progress messages\&. "
.ti -1c
.RI "using \fBInitWalletFn\fP = std::function<void()>"
.br
.RI "Register handler for wallet loader constructed messages\&. "
.ti -1c
.RI "using \fBNotifyNumConnectionsChangedFn\fP = std::function<void(int new_num_connections)>"
.br
.RI "Register handler for number of connections changed messages\&. "
.ti -1c
.RI "using \fBNotifyNetworkActiveChangedFn\fP = std::function<void(bool network_active)>"
.br
.RI "Register handler for network active messages\&. "
.ti -1c
.RI "using \fBNotifyAlertChangedFn\fP = std::function<void()>"
.br
.RI "Register handler for notify alert messages\&. "
.ti -1c
.RI "using \fBBannedListChangedFn\fP = std::function<void()>"
.br
.RI "Register handler for ban list messages\&. "
.ti -1c
.RI "using \fBNotifyBlockTipFn\fP"
.br
.RI "Register handler for block tip messages\&. "
.ti -1c
.RI "using \fBNotifyHeaderTipFn\fP"
.br
.RI "Register handler for header tip messages\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Node\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBinitLogging\fP ()=0"
.br
.RI "\fBInit\fP logging\&. "
.ti -1c
.RI "virtual void \fBinitParameterInteraction\fP ()=0"
.br
.RI "\fBInit\fP parameter interaction\&. "
.ti -1c
.RI "virtual \fBbilingual_str\fP \fBgetWarnings\fP ()=0"
.br
.RI "Get warnings\&. "
.ti -1c
.RI "virtual int \fBgetExitStatus\fP ()=0"
.br
.RI "Get exit status\&. "
.ti -1c
.RI "virtual \fBBCLog::CategoryMask\fP \fBgetLogCategories\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBbaseInitialize\fP ()=0"
.br
.RI "Initialize app dependencies\&. "
.ti -1c
.RI "virtual bool \fBappInitMain\fP (\fBinterfaces::BlockAndHeaderTipInfo\fP *tip_info=nullptr)=0"
.br
.RI "Start node\&. "
.ti -1c
.RI "virtual void \fBappShutdown\fP ()=0"
.br
.RI "Stop node\&. "
.ti -1c
.RI "virtual void \fBstartShutdown\fP ()=0"
.br
.RI "Start shutdown\&. "
.ti -1c
.RI "virtual bool \fBshutdownRequested\fP ()=0"
.br
.RI "Return whether shutdown was requested\&. "
.ti -1c
.RI "virtual bool \fBisSettingIgnored\fP (const std::string &\fBname\fP)=0"
.br
.ti -1c
.RI "virtual \fBcommon::SettingsValue\fP \fBgetPersistentSetting\fP (const std::string &\fBname\fP)=0"
.br
.RI "Return setting value from <datadir>/settings\&.json or bitcoin\&.conf\&. "
.ti -1c
.RI "virtual void \fBupdateRwSetting\fP (const std::string &\fBname\fP, const \fBcommon::SettingsValue\fP &value)=0"
.br
.RI "Update a setting in <datadir>/settings\&.json\&. "
.ti -1c
.RI "virtual void \fBforceSetting\fP (const std::string &\fBname\fP, const \fBcommon::SettingsValue\fP &value)=0"
.br
.ti -1c
.RI "virtual void \fBresetSettings\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBmapPort\fP (bool enable)=0"
.br
.RI "Map port\&. "
.ti -1c
.RI "virtual bool \fBgetProxy\fP (\fBNetwork\fP net, \fBProxy\fP &proxy_info)=0"
.br
.RI "Get proxy\&. "
.ti -1c
.RI "virtual size_t \fBgetNodeCount\fP (\fBConnectionDirection\fP \fBflags\fP)=0"
.br
.RI "Get number of connections\&. "
.ti -1c
.RI "virtual bool \fBgetNodesStats\fP (\fBNodesStats\fP &stats)=0"
.br
.ti -1c
.RI "virtual bool \fBgetBanned\fP (\fBbanmap_t\fP &banmap)=0"
.br
.RI "Get ban map entries\&. "
.ti -1c
.RI "virtual bool \fBban\fP (const \fBCNetAddr\fP &net_addr, int64_t ban_time_offset)=0"
.br
.RI "Ban node\&. "
.ti -1c
.RI "virtual bool \fBunban\fP (const \fBCSubNet\fP &ip)=0"
.br
.RI "Unban node\&. "
.ti -1c
.RI "virtual bool \fBdisconnectByAddress\fP (const \fBCNetAddr\fP &net_addr)=0"
.br
.RI "Disconnect node by address\&. "
.ti -1c
.RI "virtual bool \fBdisconnectById\fP (\fBNodeId\fP id)=0"
.br
.RI "Disconnect node by id\&. "
.ti -1c
.RI "virtual std::vector< std::unique_ptr< \fBExternalSigner\fP > > \fBlistExternalSigners\fP ()=0"
.br
.RI "Return list of external signers (attached devices which can sign transactions)\&. "
.ti -1c
.RI "virtual int64_t \fBgetTotalBytesRecv\fP ()=0"
.br
.RI "Get total bytes recv\&. "
.ti -1c
.RI "virtual int64_t \fBgetTotalBytesSent\fP ()=0"
.br
.RI "Get total bytes sent\&. "
.ti -1c
.RI "virtual size_t \fBgetMempoolSize\fP ()=0"
.br
.RI "Get mempool size\&. "
.ti -1c
.RI "virtual size_t \fBgetMempoolDynamicUsage\fP ()=0"
.br
.RI "Get mempool dynamic usage\&. "
.ti -1c
.RI "virtual size_t \fBgetMempoolMaxUsage\fP ()=0"
.br
.RI "Get mempool maximum memory usage\&. "
.ti -1c
.RI "virtual bool \fBgetHeaderTip\fP (int &height, int64_t &block_time)=0"
.br
.RI "Get header tip height and time\&. "
.ti -1c
.RI "virtual int \fBgetNumBlocks\fP ()=0"
.br
.RI "Get num blocks\&. "
.ti -1c
.RI "virtual std::map< \fBCNetAddr\fP, \fBLocalServiceInfo\fP > \fBgetNetLocalAddresses\fP ()=0"
.br
.RI "Get network local addresses\&. "
.ti -1c
.RI "virtual \fBuint256\fP \fBgetBestBlockHash\fP ()=0"
.br
.RI "Get best block hash\&. "
.ti -1c
.RI "virtual int64_t \fBgetLastBlockTime\fP ()=0"
.br
.RI "Get last block time\&. "
.ti -1c
.RI "virtual double \fBgetVerificationProgress\fP ()=0"
.br
.RI "Get verification progress\&. "
.ti -1c
.RI "virtual bool \fBisInitialBlockDownload\fP ()=0"
.br
.RI "Is initial block download\&. "
.ti -1c
.RI "virtual bool \fBisLoadingBlocks\fP ()=0"
.br
.RI "Is loading blocks\&. "
.ti -1c
.RI "virtual void \fBsetNetworkActive\fP (bool active)=0"
.br
.RI "Set network active\&. "
.ti -1c
.RI "virtual bool \fBgetNetworkActive\fP ()=0"
.br
.RI "Get network active\&. "
.ti -1c
.RI "virtual \fBCFeeRate\fP \fBgetDustRelayFee\fP ()=0"
.br
.RI "Get dust relay fee\&. "
.ti -1c
.RI "virtual \fBUniValue\fP \fBexecuteRpc\fP (const std::string &\fBcommand\fP, const \fBUniValue\fP &params, const std::string &uri)=0"
.br
.RI "Execute rpc command\&. "
.ti -1c
.RI "virtual std::vector< std::string > \fBlistRpcCommands\fP ()=0"
.br
.RI "List rpc commands\&. "
.ti -1c
.RI "virtual std::optional< \fBCoin\fP > \fBgetUnspentOutput\fP (const \fBCOutPoint\fP &output)=0"
.br
.RI "Get unspent output associated with a transaction\&. "
.ti -1c
.RI "virtual \fBnode::TransactionError\fP \fBbroadcastTransaction\fP (\fBCTransactionRef\fP tx, \fBCAmount\fP max_tx_fee, std::string &err_string)=0"
.br
.RI "Broadcast transaction\&. "
.ti -1c
.RI "virtual \fBWalletLoader\fP & \fBwalletLoader\fP ()=0"
.br
.RI "Get wallet loader\&. "
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleInitMessage\fP (\fBInitMessageFn\fP fn)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleMessageBox\fP (\fBMessageBoxFn\fP fn)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleQuestion\fP (\fBQuestionFn\fP fn)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleShowProgress\fP (\fBShowProgressFn\fP fn)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleInitWallet\fP (\fBInitWalletFn\fP fn)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleNotifyNumConnectionsChanged\fP (\fBNotifyNumConnectionsChangedFn\fP fn)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleNotifyNetworkActiveChanged\fP (\fBNotifyNetworkActiveChangedFn\fP fn)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleNotifyAlertChanged\fP (\fBNotifyAlertChangedFn\fP fn)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleBannedListChanged\fP (\fBBannedListChangedFn\fP fn)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleNotifyBlockTip\fP (\fBNotifyBlockTipFn\fP fn)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBHandler\fP > \fBhandleNotifyHeaderTip\fP (\fBNotifyHeaderTipFn\fP fn)=0"
.br
.ti -1c
.RI "virtual \fBnode::NodeContext\fP * \fBcontext\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetContext\fP (\fBnode::NodeContext\fP *\fBcontext\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Top-level interface for a bitcoin node (bitcoind process)\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBBannedListChangedFn\fP = std::function<void()>"

.PP
Register handler for ban list messages\&. 
.SS "using \fBInitMessageFn\fP = std::function<void(const std::string& message)>"

.PP
Register handler for init messages\&. 
.SS "using \fBInitWalletFn\fP = std::function<void()>"

.PP
Register handler for wallet loader constructed messages\&. 
.SS "using \fBMessageBoxFn\fP"
\fBInitial value:\fP
.nf

        std::function<bool(const bilingual_str& message, const std::string& caption, unsigned int style)>
.PP
.fi

.PP
Register handler for message box messages\&. 
.SS "using \fBNodesStats\fP = std::vector<std::tuple<\fBCNodeStats\fP, bool, \fBCNodeStateStats\fP>>"

.PP
Get stats for connected nodes\&. 
.SS "using \fBNotifyAlertChangedFn\fP = std::function<void()>"

.PP
Register handler for notify alert messages\&. 
.SS "using \fBNotifyBlockTipFn\fP"
\fBInitial value:\fP
.nf

        std::function<void(SynchronizationState, interfaces::BlockTip tip, double verification_progress)>
.PP
.fi

.PP
Register handler for block tip messages\&. 
.SS "using \fBNotifyHeaderTipFn\fP"
\fBInitial value:\fP
.nf

        std::function<void(SynchronizationState, interfaces::BlockTip tip, bool presync)>
.PP
.fi

.PP
Register handler for header tip messages\&. 
.SS "using \fBNotifyNetworkActiveChangedFn\fP = std::function<void(bool network_active)>"

.PP
Register handler for network active messages\&. 
.SS "using \fBNotifyNumConnectionsChangedFn\fP = std::function<void(int new_num_connections)>"

.PP
Register handler for number of connections changed messages\&. 
.SS "using \fBQuestionFn\fP"
\fBInitial value:\fP
.nf
 std::function<bool(const bilingual_str& message,
        const std::string& non_interactive_message,
        const std::string& caption,
        unsigned int style)>
.PP
.fi

.PP
Register handler for question messages\&. 
.SS "using \fBShowProgressFn\fP = std::function<void(const std::string& title, int progress, bool resume_possible)>"

.PP
Register handler for progress messages\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBNode\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool appInitMain (\fBinterfaces::BlockAndHeaderTipInfo\fP * tip_info = \fRnullptr\fP)\fR [pure virtual]\fP"

.PP
Start node\&. 
.SS "virtual void appShutdown ()\fR [pure virtual]\fP"

.PP
Stop node\&. 
.SS "virtual bool ban (const \fBCNetAddr\fP & net_addr, int64_t ban_time_offset)\fR [pure virtual]\fP"

.PP
Ban node\&. 
.SS "virtual bool baseInitialize ()\fR [pure virtual]\fP"

.PP
Initialize app dependencies\&. 
.SS "virtual \fBnode::TransactionError\fP broadcastTransaction (\fBCTransactionRef\fP tx, \fBCAmount\fP max_tx_fee, std::string & err_string)\fR [pure virtual]\fP"

.PP
Broadcast transaction\&. 
.SS "virtual \fBnode::NodeContext\fP * context ()\fR [inline]\fP, \fR [virtual]\fP"
Get and set internal node context\&. Useful for testing, but not accessible across processes\&. 
.SS "virtual bool disconnectByAddress (const \fBCNetAddr\fP & net_addr)\fR [pure virtual]\fP"

.PP
Disconnect node by address\&. 
.SS "virtual bool disconnectById (\fBNodeId\fP id)\fR [pure virtual]\fP"

.PP
Disconnect node by id\&. 
.SS "virtual \fBUniValue\fP executeRpc (const std::string & command, const \fBUniValue\fP & params, const std::string & uri)\fR [pure virtual]\fP"

.PP
Execute rpc command\&. 
.SS "virtual void forceSetting (const std::string & name, const \fBcommon::SettingsValue\fP & value)\fR [pure virtual]\fP"
Force a setting value to be applied, overriding any other configuration source, but not being persisted\&. 
.SS "virtual bool getBanned (\fBbanmap_t\fP & banmap)\fR [pure virtual]\fP"

.PP
Get ban map entries\&. 
.SS "virtual \fBuint256\fP getBestBlockHash ()\fR [pure virtual]\fP"

.PP
Get best block hash\&. 
.SS "virtual \fBCFeeRate\fP getDustRelayFee ()\fR [pure virtual]\fP"

.PP
Get dust relay fee\&. 
.SS "virtual int getExitStatus ()\fR [pure virtual]\fP"

.PP
Get exit status\&. 
.SS "virtual bool getHeaderTip (int & height, int64_t & block_time)\fR [pure virtual]\fP"

.PP
Get header tip height and time\&. 
.SS "virtual int64_t getLastBlockTime ()\fR [pure virtual]\fP"

.PP
Get last block time\&. 
.SS "virtual \fBBCLog::CategoryMask\fP getLogCategories ()\fR [pure virtual]\fP"

.SS "virtual size_t getMempoolDynamicUsage ()\fR [pure virtual]\fP"

.PP
Get mempool dynamic usage\&. 
.SS "virtual size_t getMempoolMaxUsage ()\fR [pure virtual]\fP"

.PP
Get mempool maximum memory usage\&. 
.SS "virtual size_t getMempoolSize ()\fR [pure virtual]\fP"

.PP
Get mempool size\&. 
.SS "virtual std::map< \fBCNetAddr\fP, \fBLocalServiceInfo\fP > getNetLocalAddresses ()\fR [pure virtual]\fP"

.PP
Get network local addresses\&. 
.SS "virtual bool getNetworkActive ()\fR [pure virtual]\fP"

.PP
Get network active\&. 
.SS "virtual size_t getNodeCount (\fBConnectionDirection\fP flags)\fR [pure virtual]\fP"

.PP
Get number of connections\&. 
.SS "virtual bool getNodesStats (\fBNodesStats\fP & stats)\fR [pure virtual]\fP"

.SS "virtual int getNumBlocks ()\fR [pure virtual]\fP"

.PP
Get num blocks\&. 
.SS "virtual \fBcommon::SettingsValue\fP getPersistentSetting (const std::string & name)\fR [pure virtual]\fP"

.PP
Return setting value from <datadir>/settings\&.json or bitcoin\&.conf\&. 
.SS "virtual bool getProxy (\fBNetwork\fP net, \fBProxy\fP & proxy_info)\fR [pure virtual]\fP"

.PP
Get proxy\&. 
.SS "virtual int64_t getTotalBytesRecv ()\fR [pure virtual]\fP"

.PP
Get total bytes recv\&. 
.SS "virtual int64_t getTotalBytesSent ()\fR [pure virtual]\fP"

.PP
Get total bytes sent\&. 
.SS "virtual std::optional< \fBCoin\fP > getUnspentOutput (const \fBCOutPoint\fP & output)\fR [pure virtual]\fP"

.PP
Get unspent output associated with a transaction\&. 
.SS "virtual double getVerificationProgress ()\fR [pure virtual]\fP"

.PP
Get verification progress\&. 
.SS "virtual \fBbilingual_str\fP getWarnings ()\fR [pure virtual]\fP"

.PP
Get warnings\&. 
.SS "virtual std::unique_ptr< \fBHandler\fP > handleBannedListChanged (\fBBannedListChangedFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual std::unique_ptr< \fBHandler\fP > handleInitMessage (\fBInitMessageFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual std::unique_ptr< \fBHandler\fP > handleInitWallet (\fBInitWalletFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual std::unique_ptr< \fBHandler\fP > handleMessageBox (\fBMessageBoxFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual std::unique_ptr< \fBHandler\fP > handleNotifyAlertChanged (\fBNotifyAlertChangedFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual std::unique_ptr< \fBHandler\fP > handleNotifyBlockTip (\fBNotifyBlockTipFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual std::unique_ptr< \fBHandler\fP > handleNotifyHeaderTip (\fBNotifyHeaderTipFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual std::unique_ptr< \fBHandler\fP > handleNotifyNetworkActiveChanged (\fBNotifyNetworkActiveChangedFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual std::unique_ptr< \fBHandler\fP > handleNotifyNumConnectionsChanged (\fBNotifyNumConnectionsChangedFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual std::unique_ptr< \fBHandler\fP > handleQuestion (\fBQuestionFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual std::unique_ptr< \fBHandler\fP > handleShowProgress (\fBShowProgressFn\fP fn)\fR [pure virtual]\fP"

.SS "virtual void initLogging ()\fR [pure virtual]\fP"

.PP
\fBInit\fP logging\&. 
.SS "virtual void initParameterInteraction ()\fR [pure virtual]\fP"

.PP
\fBInit\fP parameter interaction\&. 
.SS "virtual bool isInitialBlockDownload ()\fR [pure virtual]\fP"

.PP
Is initial block download\&. 
.SS "virtual bool isLoadingBlocks ()\fR [pure virtual]\fP"

.PP
Is loading blocks\&. 
.SS "virtual bool isSettingIgnored (const std::string & name)\fR [pure virtual]\fP"
Return whether a particular setting in <datadir>/settings\&.json is or would be ignored because it is also specified in the command line\&. 
.SS "virtual std::vector< std::unique_ptr< \fBExternalSigner\fP > > listExternalSigners ()\fR [pure virtual]\fP"

.PP
Return list of external signers (attached devices which can sign transactions)\&. 
.SS "virtual std::vector< std::string > listRpcCommands ()\fR [pure virtual]\fP"

.PP
List rpc commands\&. 
.SS "virtual void mapPort (bool enable)\fR [pure virtual]\fP"

.PP
Map port\&. 
.SS "virtual void resetSettings ()\fR [pure virtual]\fP"
Clear all settings in <datadir>/settings\&.json and store a backup of previous settings in <datadir>/settings\&.json\&.bak\&. 
.SS "virtual void setContext (\fBnode::NodeContext\fP * context)\fR [inline]\fP, \fR [virtual]\fP"

.SS "virtual void setNetworkActive (bool active)\fR [pure virtual]\fP"

.PP
Set network active\&. 
.SS "virtual bool shutdownRequested ()\fR [pure virtual]\fP"

.PP
Return whether shutdown was requested\&. 
.SS "virtual void startShutdown ()\fR [pure virtual]\fP"

.PP
Start shutdown\&. 
.SS "virtual bool unban (const \fBCSubNet\fP & ip)\fR [pure virtual]\fP"

.PP
Unban node\&. 
.SS "virtual void updateRwSetting (const std::string & name, const \fBcommon::SettingsValue\fP & value)\fR [pure virtual]\fP"

.PP
Update a setting in <datadir>/settings\&.json\&. 
.SS "virtual \fBWalletLoader\fP & walletLoader ()\fR [pure virtual]\fP"

.PP
Get wallet loader\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
