.TH "InvalidAddrManVersionError" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvalidAddrManVersionError
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <addrman\&.h>\fP
.PP
Inherits failure\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInvalidAddrManVersionError\fP (std::string msg)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBInvalidAddrManVersionError\fP (std::string msg)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
