.TH "src/ipc/test/ipc_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc/test/ipc_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <ipc/process\&.h>\fP
.br
\fR#include <ipc/test/ipc_test\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (ipc_tests)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (parse_address_test)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (ipc_tests )"

.SS "BOOST_AUTO_TEST_CASE (parse_address_test )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
