.TH "ipc::capnp::Deserializable" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipc::capnp::Deserializable
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <common\-types\&.h>\fP
.SH "Concept definition"
.PP 

.nf
template<typename T>
concept ipc::capnp::Deserializable =  std::is_constructible_v<T, ::deserialize_type, ::DataStream&>
.PP
.fi
.SH "Detailed Description"
.PP 
Detect if type has a \fBdeserialize_type\fP constructor, which is used to deserialize types like \fBCTransaction\fP that can't be unserialized into existing objects because they are immutable\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
