.TH "Process" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Process
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <process\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Process\fP ()=default"
.br
.ti -1c
.RI "virtual int \fBspawn\fP (const std::string &new_exe_name, const \fBfs::path\fP &argv0_path, int &pid)=0"
.br
.ti -1c
.RI "virtual int \fBwaitSpawned\fP (int pid)=0"
.br
.RI "Wait for spawned process to exit and return its exit code\&. "
.ti -1c
.RI "virtual bool \fBcheckSpawned\fP (int argc, char *argv[], int &fd)=0"
.br
.ti -1c
.RI "virtual int \fBconnect\fP (const \fBfs::path\fP &data_dir, const std::string &dest_exe_name, std::string &address)=0"
.br
.RI "Canonicalize and connect to address, returning socket descriptor\&. "
.ti -1c
.RI "virtual int \fBbind\fP (const \fBfs::path\fP &data_dir, const std::string &exe_name, std::string &address)=0"
.br
.RI "Create listening socket, bind and canonicalize address, and return socket descriptor\&. "
.in -1c
.SH "Detailed Description"
.PP 
IPC process interface for spawning bitcoin processes and serving requests in processes that have been spawned\&.

.PP
There will be different implementations of this interface depending on the platform (e\&.g\&. unix, windows)\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBProcess\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual int bind (const \fBfs::path\fP & data_dir, const std::string & exe_name, std::string & address)\fR [pure virtual]\fP"

.PP
Create listening socket, bind and canonicalize address, and return socket descriptor\&. 
.SS "virtual bool checkSpawned (int argc, char * argv[], int & fd)\fR [pure virtual]\fP"
Parse command line and determine if current process is a spawned child process\&. If so, return true and a file descriptor for communicating with the parent process\&. 
.SS "virtual int connect (const \fBfs::path\fP & data_dir, const std::string & dest_exe_name, std::string & address)\fR [pure virtual]\fP"

.PP
Canonicalize and connect to address, returning socket descriptor\&. 
.SS "virtual int spawn (const std::string & new_exe_name, const \fBfs::path\fP & argv0_path, int & pid)\fR [pure virtual]\fP"
Spawn process and return socket file descriptor for communicating with it\&. 
.SS "virtual int waitSpawned (int pid)\fR [pure virtual]\fP"

.PP
Wait for spawned process to exit and return its exit code\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
