.TH "src/ipc/test/ipc_test.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc/test/ipc_test.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <interfaces/init\&.h>\fP
.br
\fR#include <ipc/capnp/protocol\&.h>\fP
.br
\fR#include <ipc/process\&.h>\fP
.br
\fR#include <ipc/protocol\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <mp/proxy\-types\&.h>\fP
.br
\fR#include <ipc/test/ipc_test\&.capnp\&.h>\fP
.br
\fR#include <ipc/test/ipc_test\&.capnp\&.proxy\&.h>\fP
.br
\fR#include <ipc/test/ipc_test\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <future>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <kj/common\&.h>\fP
.br
\fR#include <kj/memory\&.h>\fP
.br
\fR#include <kj/test\&.h>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTestInit\fP"
.br
.RI "Remote init class\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBIpcPipeTest\fP ()"
.br
.ti -1c
.RI "void \fBIpcSocketPairTest\fP ()"
.br
.RI "Test \fBipc::Protocol\fP connect() and serve() methods connecting over a socketpair\&. "
.ti -1c
.RI "void \fBIpcSocketTest\fP (const \fBfs::path\fP &datadir)"
.br
.RI "Test \fBipc::Process\fP bind() and connect() methods connecting over a unix socket\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void IpcPipeTest ()"
Unit test that tests execution of IPC calls without actually creating a separate process\&. This test is primarily intended to verify behavior of type conversion code that converts C++ objects to Cap'n Proto messages and vice versa\&.

.PP
The test creates a thread which creates a \fBFooImplementation\fP object (defined in \fBipc_test\&.h\fP) and a two-way pipe accepting IPC requests which call methods on the object through FooInterface (defined in ipc_test\&.capnp)\&. 
.SS "void IpcSocketPairTest ()"

.PP
Test \fBipc::Protocol\fP connect() and serve() methods connecting over a socketpair\&. 
.SS "void IpcSocketTest (const \fBfs::path\fP & datadir)"

.PP
Test \fBipc::Process\fP bind() and connect() methods connecting over a unix socket\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
