.TH "src/leveldb/table/iterator_wrapper.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/table/iterator_wrapper.h
.SH SYNOPSIS
.br
.PP
\fR#include 'leveldb/iterator\&.h'\fP
.br
\fR#include 'leveldb/slice\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIteratorWrapper\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
