.TH "Iterator" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Iterator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <iterator\&.h>\fP
.PP
Inherited by \fBBlock::Iter\fP, \fBKeyConvertingIterator\fP, \fBMemTableIterator\fP, and \fBVersion::LevelFileNumIterator\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBCleanupFunction\fP = void (*)(void* arg1, void* arg2)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP (const \fBIterator\fP &)=delete"
.br
.ti -1c
.RI "\fBIterator\fP & \fBoperator=\fP (const \fBIterator\fP &)=delete"
.br
.ti -1c
.RI "virtual \fB~Iterator\fP ()"
.br
.ti -1c
.RI "virtual bool \fBValid\fP () const=0"
.br
.ti -1c
.RI "virtual void \fBSeekToFirst\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBSeekToLast\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBSeek\fP (const \fBSlice\fP &target)=0"
.br
.ti -1c
.RI "virtual void \fBNext\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBPrev\fP ()=0"
.br
.ti -1c
.RI "virtual \fBSlice\fP \fBkey\fP () const=0"
.br
.ti -1c
.RI "virtual \fBSlice\fP \fBvalue\fP () const=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBstatus\fP () const=0"
.br
.ti -1c
.RI "void \fBRegisterCleanup\fP (\fBCleanupFunction\fP function, void *arg1, void *arg2)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBCleanupFunction\fP = void (*)(void* arg1, void* arg2)"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBIterator\fP ()"

.SS "\fBIterator\fP (const \fBIterator\fP & )\fR [delete]\fP"

.SS "~\fBIterator\fP ()\fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBSlice\fP key () const\fR [pure virtual]\fP"

.SS "virtual void Next ()\fR [pure virtual]\fP"

.SS "\fBIterator\fP & operator= (const \fBIterator\fP & )\fR [delete]\fP"

.SS "virtual void Prev ()\fR [pure virtual]\fP"

.SS "void RegisterCleanup (\fBCleanupFunction\fP function, void * arg1, void * arg2)"

.SS "virtual void Seek (const \fBSlice\fP & target)\fR [pure virtual]\fP"

.SS "virtual void SeekToFirst ()\fR [pure virtual]\fP"

.SS "virtual void SeekToLast ()\fR [pure virtual]\fP"

.SS "virtual \fBStatus\fP status () const\fR [pure virtual]\fP"

.SS "virtual bool Valid () const\fR [pure virtual]\fP"

.SS "virtual \fBSlice\fP value () const\fR [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
