.TH "JSONRPCRequest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSONRPCRequest
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <request\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBEXECUTE\fP, \fBGET_HELP\fP, \fBGET_ARGS\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparse\fP (const \fBUniValue\fP &valRequest)"
.br
.ti -1c
.RI "bool \fBIsNotification\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::optional< \fBUniValue\fP > \fBid\fP = \fBUniValue::VNULL\fP"
.br
.ti -1c
.RI "std::string \fBstrMethod\fP"
.br
.ti -1c
.RI "\fBUniValue\fP \fBparams\fP"
.br
.ti -1c
.RI "enum \fBJSONRPCRequest::Mode\fP \fBmode\fP = \fBEXECUTE\fP"
.br
.ti -1c
.RI "std::string \fBURI\fP"
.br
.ti -1c
.RI "std::string \fBauthUser\fP"
.br
.ti -1c
.RI "std::string \fBpeerAddr\fP"
.br
.ti -1c
.RI "std::any \fBcontext\fP"
.br
.ti -1c
.RI "\fBJSONRPCVersion\fP \fBm_json_version\fP = \fBJSONRPCVersion::V1_LEGACY\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIEXECUTE \fP
.TP
\f(BIGET_HELP \fP
.TP
\f(BIGET_ARGS \fP
.SH "Member Function Documentation"
.PP 
.SS "bool IsNotification () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "void parse (const \fBUniValue\fP & valRequest)"

.SH "Field Documentation"
.PP 
.SS "std::string authUser"

.SS "std::any context"

.SS "std::optional<\fBUniValue\fP> id = \fBUniValue::VNULL\fP"

.SS "\fBJSONRPCVersion\fP m_json_version = \fBJSONRPCVersion::V1_LEGACY\fP"

.SS "enum \fBJSONRPCRequest::Mode\fP mode = \fBEXECUTE\fP"

.SS "\fBUniValue\fP params"

.SS "std::string peerAddr"

.SS "std::string strMethod"

.SS "std::string URI"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
