.TH "JSONUTF8StringFilter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSONUTF8StringFilter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <univalue_utffilter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJSONUTF8StringFilter\fP (std::string &s)"
.br
.ti -1c
.RI "void \fBpush_back\fP (unsigned char ch)"
.br
.ti -1c
.RI "void \fBpush_back_u\fP (unsigned int codepoint_)"
.br
.ti -1c
.RI "bool \fBfinalize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filter that generates and validates UTF-8, as well as collates UTF-16 surrogate pairs as specified in RFC4627\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBJSONUTF8StringFilter\fP (std::string & s)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool finalize ()\fR [inline]\fP"

.SS "void push_back (unsigned char ch)\fR [inline]\fP"

.SS "void push_back_u (unsigned int codepoint_)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
