.TH "Interrupted" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interrupted \- Result type for use with std::variant to indicate that an operation should be interrupted\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <notifications_interface\&.h>\fP
.SH "Detailed Description"
.PP 
Result type for use with std::variant to indicate that an operation should be interrupted\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
