.TH "Context" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Context
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <context\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContext\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBContext\fP struct holding the kernel library's logically global state, and passed to external libbitcoin_kernel functions which need access to this state\&. The kernel library API is a work in progress, so state organization and member list will evolve over time\&.

.PP
\fBState\fP stored directly in this struct should be simple\&. More complex state should be stored to std::unique_ptr members pointing to opaque types\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Context ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
