.TH "src/node/kernel_notifications.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/kernel_notifications.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/kernel_notifications\&.h>\fP
.br
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <chain\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <common/system\&.h>\fP
.br
\fR#include <kernel/context\&.h>\fP
.br
\fR#include <kernel/warning\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <node/abort\&.h>\fP
.br
\fR#include <node/interface_ui\&.h>\fP
.br
\fR#include <node/warnings\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/signalinterrupt\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br
\fR#include <thread>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBReadNotificationArgs\fP (const \fBArgsManager\fP &\fBargs\fP, \fBKernelNotifications\fP &notifications)"
.br
.ti -1c
.RI "void \fBReplaceAll\fP (std::string &in_out, const std::string &search, const std::string &substitute)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ReplaceAll (std::string & in_out, const std::string & search, const std::string & substitute)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
