.TH "BlockManagerOpts" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockManagerOpts
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <blockmanager_opts\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBCChainParams\fP & \fBchainparams\fP"
.br
.ti -1c
.RI "bool \fBuse_xor\fP {DEFAULT_XOR_BLOCKSDIR}"
.br
.ti -1c
.RI "uint64_t \fBprune_target\fP {0}"
.br
.ti -1c
.RI "bool \fBfast_prune\fP {false}"
.br
.ti -1c
.RI "const \fBfs::path\fP \fBblocks_dir\fP"
.br
.ti -1c
.RI "\fBNotifications\fP & \fBnotifications\fP"
.br
.ti -1c
.RI "\fBDBParams\fP \fBblock_tree_db_params\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An options struct for \fR\fBBlockManager\fP\fP, more ergonomically referred to as \fR\fBBlockManager::Options\fP\fP due to the using-declaration in \fR\fBBlockManager\fP\fP\&. 
.SH "Field Documentation"
.PP 
.SS "\fBDBParams\fP block_tree_db_params"

.SS "const \fBfs::path\fP blocks_dir"

.SS "const \fBCChainParams\fP& chainparams"

.SS "bool fast_prune {false}"

.SS "\fBNotifications\fP& notifications"

.SS "uint64_t prune_target {0}"

.SS "bool use_xor {DEFAULT_XOR_BLOCKSDIR}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
