.TH "Notifications" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Notifications
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <notifications_interface\&.h>\fP
.PP
Inherited by \fBKernelNotifications\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Notifications\fP ()=default"
.br
.ti -1c
.RI "virtual \fBInterruptResult\fP \fBblockTip\fP (\fBSynchronizationState\fP state, const \fBCBlockIndex\fP &index, double verification_progress)"
.br
.ti -1c
.RI "virtual void \fBheaderTip\fP (\fBSynchronizationState\fP state, int64_t height, int64_t timestamp, bool presync)"
.br
.ti -1c
.RI "virtual void \fBprogress\fP (const \fBbilingual_str\fP &title, int progress_percent, bool resume_possible)"
.br
.ti -1c
.RI "virtual void \fBwarningSet\fP (\fBWarning\fP id, const \fBbilingual_str\fP &message)"
.br
.ti -1c
.RI "virtual void \fBwarningUnset\fP (\fBWarning\fP id)"
.br
.ti -1c
.RI "virtual void \fBflushError\fP (const \fBbilingual_str\fP &message)"
.br
.ti -1c
.RI "virtual void \fBfatalError\fP (const \fBbilingual_str\fP &message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A base class defining functions for notifying about certain kernel events\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBNotifications\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBInterruptResult\fP blockTip (\fBSynchronizationState\fP state, const \fBCBlockIndex\fP & index, double verification_progress)\fR [inline]\fP, \fR [nodiscard]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBKernelNotifications\fP, and \fBKernelNotifications\fP\&.
.SS "virtual void fatalError (const \fBbilingual_str\fP & message)\fR [inline]\fP, \fR [virtual]\fP"
The fatal error notification is sent to notify the user when an error occurs in kernel code that can't be recovered from\&. After this notification is sent, whatever function triggered the error should also return an error code or raise an exception\&. Applications can choose to handle the fatal error notification by logging the error, or notifying the user, or triggering an early shutdown as a precaution against causing more errors\&. 
.PP
Reimplemented in \fBKernelNotifications\fP, and \fBKernelNotifications\fP\&.
.SS "virtual void flushError (const \fBbilingual_str\fP & message)\fR [inline]\fP, \fR [virtual]\fP"
The flush error notification is sent to notify the user that an error occurred while flushing block data to disk\&. Kernel code may ignore flush errors that don't affect the immediate operation it is trying to perform\&. Applications can choose to handle the flush error notification by logging the error, or notifying the user, or triggering an early shutdown as a precaution against causing more errors\&. 
.PP
Reimplemented in \fBKernelNotifications\fP, and \fBKernelNotifications\fP\&.
.SS "virtual void headerTip (\fBSynchronizationState\fP state, int64_t height, int64_t timestamp, bool presync)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBKernelNotifications\fP, and \fBKernelNotifications\fP\&.
.SS "virtual void progress (const \fBbilingual_str\fP & title, int progress_percent, bool resume_possible)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBKernelNotifications\fP, and \fBKernelNotifications\fP\&.
.SS "virtual void warningSet (\fBWarning\fP id, const \fBbilingual_str\fP & message)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBKernelNotifications\fP, and \fBKernelNotifications\fP\&.
.SS "virtual void warningUnset (\fBWarning\fP id)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBKernelNotifications\fP, and \fBKernelNotifications\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
