.TH "src/test/fuzz/key.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/key.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <chainparams\&.h>\fP
.br
\fR#include <key\&.h>\fP
.br
\fR#include <key_io\&.h>\fP
.br
\fR#include <outputtype\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <rpc/util\&.h>\fP
.br
\fR#include <script/keyorigin\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <script/sign\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br
\fR#include <script/solver\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <array>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <numeric>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_key\fP ()"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (key,\&.\fBinit\fP=\fBinitialize_key\fP)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (ellswift_roundtrip,\&.\fBinit\fP=\fBinitialize_key\fP)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (bip324_ecdh,\&.\fBinit\fP=\fBinitialize_key\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (bip324_ecdh , \&. init = \fR\fBinitialize_key\fP\fP)"

.SS "FUZZ_TARGET (ellswift_roundtrip , \&. init = \fR\fBinitialize_key\fP\fP)"

.SS "FUZZ_TARGET (key , \&. init = \fR\fBinitialize_key\fP\fP)"

.SS "void initialize_key ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
