.TH "src/key.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/key.h
.SH SYNOPSIS
.br
.PP
\fR#include <musig\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <support/allocators/secure\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCKey\fP"
.br
.ti -1c
.RI "struct \fBCExtKey\fP"
.br
.ti -1c
.RI "class \fBKeyPair\fP"
.br
.ti -1c
.RI "class \fBECC_Context\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< unsigned char, \fBsecure_allocator\fP< unsigned char > > \fBCPrivKey\fP"
.br
.ti -1c
.RI "using \fBECDHSecret\fP = std::array<std::byte, ECDH_SECRET_SIZE>"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCKey\fP \fBGenerateRandomKey\fP (bool compressed=true) noexcept"
.br
.ti -1c
.RI "bool \fBECC_InitSanityCheck\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<unsigned char, \fBsecure_allocator\fP<unsigned char> > \fBCPrivKey\fP"
\fBCPrivKey\fP is a serialized private key, with all parameters included (SIZE bytes) 
.SS "using \fBECDHSecret\fP = std::array<std::byte, ECDH_SECRET_SIZE>"

.SH "Function Documentation"
.PP 
.SS "bool ECC_InitSanityCheck ()"
Check that required EC support is available at runtime\&. 
.SS "\fBCKey\fP GenerateRandomKey (bool compressed = \fRtrue\fP)\fR [noexcept]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
