.TH "src/key_io.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/key_io.h
.SH SYNOPSIS
.br
.PP
\fR#include <addresstype\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <key\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCKey\fP \fBDecodeSecret\fP (const std::string &str)"
.br
.ti -1c
.RI "std::string \fBEncodeSecret\fP (const \fBCKey\fP &key)"
.br
.ti -1c
.RI "\fBCExtKey\fP \fBDecodeExtKey\fP (const std::string &str)"
.br
.ti -1c
.RI "std::string \fBEncodeExtKey\fP (const \fBCExtKey\fP &extkey)"
.br
.ti -1c
.RI "\fBCExtPubKey\fP \fBDecodeExtPubKey\fP (const std::string &str)"
.br
.ti -1c
.RI "std::string \fBEncodeExtPubKey\fP (const \fBCExtPubKey\fP &extpubkey)"
.br
.ti -1c
.RI "std::string \fBEncodeDestination\fP (const \fBCTxDestination\fP &dest)"
.br
.ti -1c
.RI "\fBCTxDestination\fP \fBDecodeDestination\fP (const std::string &str)"
.br
.ti -1c
.RI "\fBCTxDestination\fP \fBDecodeDestination\fP (const std::string &str, std::string &error_msg, std::vector< int > *error_locations=nullptr)"
.br
.ti -1c
.RI "bool \fBIsValidDestinationString\fP (const std::string &str)"
.br
.ti -1c
.RI "bool \fBIsValidDestinationString\fP (const std::string &str, const \fBCChainParams\fP &params)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCTxDestination\fP DecodeDestination (const std::string & str)"

.SS "\fBCTxDestination\fP DecodeDestination (const std::string & str, std::string & error_msg, std::vector< int > * error_locations = \fRnullptr\fP)"

.SS "\fBCExtKey\fP DecodeExtKey (const std::string & str)"

.SS "\fBCExtPubKey\fP DecodeExtPubKey (const std::string & str)"

.SS "\fBCKey\fP DecodeSecret (const std::string & str)"

.SS "std::string EncodeDestination (const \fBCTxDestination\fP & dest)"

.SS "std::string EncodeExtKey (const \fBCExtKey\fP & extkey)"

.SS "std::string EncodeExtPubKey (const \fBCExtPubKey\fP & extpubkey)"

.SS "std::string EncodeSecret (const \fBCKey\fP & key)"

.SS "bool IsValidDestinationString (const std::string & str)"

.SS "bool IsValidDestinationString (const std::string & str, const \fBCChainParams\fP & params)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
