.TH "KeyOriginInfo" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyOriginInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <keyorigin\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBKeyOriginInfo\fP, obj)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBfingerprint\fP [4]"
.br
.RI "First 32 bits of the Hash160 of the public key at the root of the path\&. "
.ti -1c
.RI "std::vector< uint32_t > \fBpath\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBKeyOriginInfo\fP &a, const \fBKeyOriginInfo\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBKeyOriginInfo\fP &a, const \fBKeyOriginInfo\fP &b)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void clear ()\fR [inline]\fP"

.SS "SERIALIZE_METHODS (\fBKeyOriginInfo\fP , obj )\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "bool operator< (const \fBKeyOriginInfo\fP & a, const \fBKeyOriginInfo\fP & b)\fR [friend]\fP"

.SS "bool operator== (const \fBKeyOriginInfo\fP & a, const \fBKeyOriginInfo\fP & b)\fR [friend]\fP"

.SH "Field Documentation"
.PP 
.SS "unsigned char fingerprint[4]"

.PP
First 32 bits of the Hash160 of the public key at the root of the path\&. 
.SS "std::vector<uint32_t> path"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
