.TH "KeyPair" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyPair
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <key\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyPair\fP () noexcept=default"
.br
.ti -1c
.RI "\fBKeyPair\fP (\fBKeyPair\fP &&) noexcept=default"
.br
.ti -1c
.RI "\fBKeyPair\fP & \fBoperator=\fP (\fBKeyPair\fP &&) noexcept=default"
.br
.ti -1c
.RI "\fBKeyPair\fP & \fBoperator=\fP (const \fBKeyPair\fP &other)"
.br
.ti -1c
.RI "\fBKeyPair\fP (const \fBKeyPair\fP &other)"
.br
.ti -1c
.RI "bool \fBSignSchnorr\fP (const \fBuint256\fP &hash, std::span< unsigned char > sig, const \fBuint256\fP &aux) const"
.br
.ti -1c
.RI "bool \fBIsValid\fP () const"
.br
.RI "Check whether this keypair is valid\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBKeyPair\fP \fBCKey::ComputeKeyPair\fP (const \fBuint256\fP *merkle_root) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBKeyPair\fP

.PP
Wraps a \fR\fBsecp256k1_keypair\fP\fP type, an opaque data structure for holding a secret and public key\&. This is intended for BIP340 keys and allows us to easily determine if the secret key needs to be negated by checking the parity of the public key\&. This class primarily intended for passing secret keys to libsecp256k1 functions expecting a \fR\fBsecp256k1_keypair\fP\fP\&. For all other cases, \fBCKey\fP should be preferred\&.

.PP
A \fBKeyPair\fP can be created from a \fBCKey\fP with an optional merkle_root tweak (per BIP342)\&. See \fBCKey::ComputeKeyPair\fP for more details\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBKeyPair\fP ()\fR [default]\fP, \fR [noexcept]\fP"

.SS "\fBKeyPair\fP (\fBKeyPair\fP && )\fR [default]\fP, \fR [noexcept]\fP"

.SS "\fBKeyPair\fP (const \fBKeyPair\fP & other)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool IsValid () const\fR [inline]\fP"

.PP
Check whether this keypair is valid\&. 
.SS "\fBKeyPair\fP & operator= (const \fBKeyPair\fP & other)\fR [inline]\fP"

.SS "\fBKeyPair\fP & operator= (\fBKeyPair\fP && )\fR [default]\fP, \fR [noexcept]\fP"

.SS "bool SignSchnorr (const \fBuint256\fP & hash, std::span< unsigned char > sig, const \fBuint256\fP & aux) const\fR [nodiscard]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBKeyPair\fP \fBCKey::ComputeKeyPair\fP (const \fBuint256\fP * merkle_root) const\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
