.TH "Version" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Version
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <version_set\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBGetStats\fP"
.br
.ti -1c
.RI "class \fBLevelFileNumIterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddIterators\fP (const \fBReadOptions\fP &, std::vector< \fBIterator\fP * > *iters)"
.br
.ti -1c
.RI "\fBStatus\fP \fBGet\fP (const \fBReadOptions\fP &, const \fBLookupKey\fP &key, std::string *val, \fBGetStats\fP *stats)"
.br
.ti -1c
.RI "bool \fBUpdateStats\fP (const \fBGetStats\fP &stats)"
.br
.ti -1c
.RI "bool \fBRecordReadSample\fP (\fBSlice\fP key)"
.br
.ti -1c
.RI "void \fBRef\fP ()"
.br
.ti -1c
.RI "void \fBUnref\fP ()"
.br
.ti -1c
.RI "void \fBGetOverlappingInputs\fP (int level, const \fBInternalKey\fP *begin, const \fBInternalKey\fP *end, std::vector< \fBFileMetaData\fP * > *inputs)"
.br
.ti -1c
.RI "bool \fBOverlapInLevel\fP (int level, const \fBSlice\fP *smallest_user_key, const \fBSlice\fP *largest_user_key)"
.br
.ti -1c
.RI "int \fBPickLevelForMemTableOutput\fP (const \fBSlice\fP &smallest_user_key, const \fBSlice\fP &largest_user_key)"
.br
.ti -1c
.RI "int \fBNumFiles\fP (int level) const"
.br
.ti -1c
.RI "std::string \fBDebugString\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCompaction\fP"
.br
.ti -1c
.RI "class \fBVersionSet\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AddIterators (const \fBReadOptions\fP & options, std::vector< \fBIterator\fP * > * iters)"

.SS "std::string DebugString () const"

.SS "\fBStatus\fP Get (const \fBReadOptions\fP & options, const \fBLookupKey\fP & key, std::string * val, \fBGetStats\fP * stats)"

.SS "void GetOverlappingInputs (int level, const \fBInternalKey\fP * begin, const \fBInternalKey\fP * end, std::vector< \fBFileMetaData\fP * > * inputs)"

.SS "int NumFiles (int level) const\fR [inline]\fP"

.SS "bool OverlapInLevel (int level, const \fBSlice\fP * smallest_user_key, const \fBSlice\fP * largest_user_key)"

.SS "int PickLevelForMemTableOutput (const \fBSlice\fP & smallest_user_key, const \fBSlice\fP & largest_user_key)"

.SS "bool RecordReadSample (\fBSlice\fP key)"

.SS "void Ref ()"

.SS "void Unref ()"

.SS "bool UpdateStats (const \fBGetStats\fP & stats)"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class Compaction\fR [friend]\fP"

.SS "friend class VersionSet\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
