.TH "WriteBatch::Handler" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WriteBatch::Handler
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <write_batch\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Handler\fP ()"
.br
.ti -1c
.RI "virtual void \fBPut\fP (const \fBSlice\fP &key, const \fBSlice\fP &value)=0"
.br
.ti -1c
.RI "virtual void \fBDelete\fP (const \fBSlice\fP &key)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "~\fBHandler\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Delete (const \fBSlice\fP & key)\fR [pure virtual]\fP"

.SS "virtual void Put (const \fBSlice\fP & key, const \fBSlice\fP & value)\fR [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
