.TH "Block::Iter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Block::Iter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIter\fP (const \fBComparator\fP *comparator, const char *data, uint32_t restarts, uint32_t num_restarts)"
.br
.ti -1c
.RI "bool \fBValid\fP () const override"
.br
.ti -1c
.RI "\fBStatus\fP \fBstatus\fP () const override"
.br
.ti -1c
.RI "\fBSlice\fP \fBkey\fP () const override"
.br
.ti -1c
.RI "\fBSlice\fP \fBvalue\fP () const override"
.br
.ti -1c
.RI "void \fBNext\fP () override"
.br
.ti -1c
.RI "void \fBPrev\fP () override"
.br
.ti -1c
.RI "void \fBSeek\fP (const \fBSlice\fP &target) override"
.br
.ti -1c
.RI "void \fBSeekToFirst\fP () override"
.br
.ti -1c
.RI "void \fBSeekToLast\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBIterator\fP
.in +1c
.ti -1c
.RI "\fBIterator\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP (const \fBIterator\fP &)=delete"
.br
.ti -1c
.RI "\fBIterator\fP & \fBoperator=\fP (const \fBIterator\fP &)=delete"
.br
.ti -1c
.RI "virtual \fB~Iterator\fP ()"
.br
.ti -1c
.RI "void \fBRegisterCleanup\fP (\fBCleanupFunction\fP function, void *arg1, void *arg2)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBIterator\fP
.in +1c
.ti -1c
.RI "using \fBCleanupFunction\fP = void (*)(void* arg1, void* arg2)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Iter (const \fBComparator\fP * comparator, const char * data, uint32_t restarts, uint32_t num_restarts)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBSlice\fP key () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBIterator\fP\&.
.SS "void Next ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBIterator\fP\&.
.SS "void Prev ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBIterator\fP\&.
.SS "void Seek (const \fBSlice\fP & target)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBIterator\fP\&.
.SS "void SeekToFirst ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBIterator\fP\&.
.SS "void SeekToLast ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBIterator\fP\&.
.SS "\fBStatus\fP status () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBIterator\fP\&.
.SS "bool Valid () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBIterator\fP\&.
.SS "\fBSlice\fP value () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBIterator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
