.TH "LevelDBContext" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelDBContext
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBleveldb::Env\fP * \fBpenv\fP"
.br
.RI "custom environment this database is using (may be nullptr in case of default environment) "
.ti -1c
.RI "\fBleveldb::Options\fP \fBoptions\fP"
.br
.RI "database options used "
.ti -1c
.RI "\fBleveldb::ReadOptions\fP \fBreadoptions\fP"
.br
.RI "options used when reading from the database "
.ti -1c
.RI "\fBleveldb::ReadOptions\fP \fBiteroptions\fP"
.br
.RI "options used when iterating over values of the database "
.ti -1c
.RI "\fBleveldb::WriteOptions\fP \fBwriteoptions\fP"
.br
.RI "options used when writing to the database "
.ti -1c
.RI "\fBleveldb::WriteOptions\fP \fBsyncoptions\fP"
.br
.RI "options used when sync writing to the database "
.ti -1c
.RI "\fBleveldb::DB\fP * \fBpdb\fP"
.br
.RI "the database itself "
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBleveldb::ReadOptions\fP iteroptions"

.PP
options used when iterating over values of the database 
.SS "\fBleveldb::Options\fP options"

.PP
database options used 
.SS "\fBleveldb::DB\fP* pdb"

.PP
the database itself 
.SS "\fBleveldb::Env\fP* penv"

.PP
custom environment this database is using (may be nullptr in case of default environment) 
.SS "\fBleveldb::ReadOptions\fP readoptions"

.PP
options used when reading from the database 
.SS "\fBleveldb::WriteOptions\fP syncoptions"

.PP
options used when sync writing to the database 
.SS "\fBleveldb::WriteOptions\fP writeoptions"

.PP
options used when writing to the database 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
