.TH "ErrorEnv" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorEnv
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testutil\&.h>\fP
.PP
Inherits \fBEnvWrapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrorEnv\fP ()"
.br
.ti -1c
.RI "\fB~ErrorEnv\fP () override"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewWritableFile\fP (const std::string &fname, \fBWritableFile\fP **result) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewAppendableFile\fP (const std::string &fname, \fBWritableFile\fP **result) override"
.br
.in -1c

Public Member Functions inherited from \fBEnvWrapper\fP
.in +1c
.ti -1c
.RI "\fBEnvWrapper\fP (\fBEnv\fP *t)"
.br
.ti -1c
.RI "virtual \fB~EnvWrapper\fP ()"
.br
.ti -1c
.RI "\fBEnv\fP * \fBtarget\fP () const"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewSequentialFile\fP (const std::string &f, \fBSequentialFile\fP **r) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewRandomAccessFile\fP (const std::string &f, \fBRandomAccessFile\fP **r) override"
.br
.ti -1c
.RI "bool \fBFileExists\fP (const std::string &f) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBGetChildren\fP (const std::string &dir, std::vector< std::string > *r) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBDeleteFile\fP (const std::string &f) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBCreateDir\fP (const std::string &d) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBDeleteDir\fP (const std::string &d) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBGetFileSize\fP (const std::string &f, uint64_t *s) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBRenameFile\fP (const std::string &s, const std::string &t) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBLockFile\fP (const std::string &f, \fBFileLock\fP **l) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBUnlockFile\fP (\fBFileLock\fP *l) override"
.br
.ti -1c
.RI "void \fBSchedule\fP (void(*f)(void *), void *a) override"
.br
.ti -1c
.RI "void \fBStartThread\fP (void(*f)(void *), void *a) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBGetTestDirectory\fP (std::string *path) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewLogger\fP (const std::string &fname, \fBLogger\fP **result) override"
.br
.ti -1c
.RI "uint64_t \fBNowMicros\fP () override"
.br
.ti -1c
.RI "void \fBSleepForMicroseconds\fP (int micros) override"
.br
.in -1c

Public Member Functions inherited from \fBEnv\fP
.in +1c
.ti -1c
.RI "\fBEnv\fP ()=default"
.br
.ti -1c
.RI "\fBEnv\fP (const \fBEnv\fP &)=delete"
.br
.ti -1c
.RI "\fBEnv\fP & \fBoperator=\fP (const \fBEnv\fP &)=delete"
.br
.ti -1c
.RI "virtual \fB~Env\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBwritable_file_error_\fP"
.br
.ti -1c
.RI "int \fBnum_writable_file_errors_\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEnv\fP
.in +1c
.ti -1c
.RI "static \fBEnv\fP * \fBDefault\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ErrorEnv ()\fR [inline]\fP"

.SS "~\fBErrorEnv\fP ()\fR [inline]\fP, \fR [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBStatus\fP NewAppendableFile (const std::string & fname, \fBWritableFile\fP ** result)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBEnvWrapper\fP\&.
.SS "\fBStatus\fP NewWritableFile (const std::string & fname, \fBWritableFile\fP ** result)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBEnvWrapper\fP\&.
.SH "Field Documentation"
.PP 
.SS "int num_writable_file_errors_"

.SS "bool writable_file_error_"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
