.TH "CacheTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CacheTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCacheTest\fP ()"
.br
.ti -1c
.RI "\fB~CacheTest\fP ()"
.br
.ti -1c
.RI "int \fBLookup\fP (int key)"
.br
.ti -1c
.RI "void \fBInsert\fP (int key, int value, int charge=1)"
.br
.ti -1c
.RI "\fBCache::Handle\fP * \fBInsertAndReturnHandle\fP (int key, int value, int charge=1)"
.br
.ti -1c
.RI "void \fBErase\fP (int key)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBDeleter\fP (const \fBSlice\fP &key, void *v)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< int > \fBdeleted_keys_\fP"
.br
.ti -1c
.RI "std::vector< int > \fBdeleted_values_\fP"
.br
.ti -1c
.RI "\fBCache\fP * \fBcache_\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBkCacheSize\fP = 1000"
.br
.ti -1c
.RI "static \fBCacheTest\fP * \fBcurrent_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCacheTest\fP ()\fR [inline]\fP"

.SS "~\fBCacheTest\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Deleter (const \fBSlice\fP & key, void * v)\fR [inline]\fP, \fR [static]\fP"

.SS "void Erase (int key)\fR [inline]\fP"

.SS "void Insert (int key, int value, int charge = \fR1\fP)\fR [inline]\fP"

.SS "\fBCache::Handle\fP * InsertAndReturnHandle (int key, int value, int charge = \fR1\fP)\fR [inline]\fP"

.SS "int Lookup (int key)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBCache\fP* cache_"

.SS "\fBCacheTest\fP * current_\fR [static]\fP"

.SS "std::vector<int> deleted_keys_"

.SS "std::vector<int> deleted_values_"

.SS "const int kCacheSize = 1000\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
