.TH "Table::Rep" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Table::Rep
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Rep\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBOptions\fP \fBoptions\fP"
.br
.ti -1c
.RI "\fBStatus\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBRandomAccessFile\fP * \fBfile\fP"
.br
.ti -1c
.RI "uint64_t \fBcache_id\fP"
.br
.ti -1c
.RI "\fBFilterBlockReader\fP * \fBfilter\fP"
.br
.ti -1c
.RI "const char * \fBfilter_data\fP"
.br
.ti -1c
.RI "\fBBlockHandle\fP \fBmetaindex_handle\fP"
.br
.ti -1c
.RI "\fBBlock\fP * \fBindex_block\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "~\fBRep\fP ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "uint64_t cache_id"

.SS "\fBRandomAccessFile\fP* file"

.SS "\fBFilterBlockReader\fP* filter"

.SS "const char* filter_data"

.SS "\fBBlock\fP* index_block"

.SS "\fBBlockHandle\fP metaindex_handle"

.SS "\fBOptions\fP options"

.SS "\fBStatus\fP status"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
