.TH "Footer" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Footer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <format\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBkEncodedLength\fP = 2 * BlockHandle::kMaxEncodedLength + 8 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFooter\fP ()=default"
.br
.ti -1c
.RI "const \fBBlockHandle\fP & \fBmetaindex_handle\fP () const"
.br
.ti -1c
.RI "void \fBset_metaindex_handle\fP (const \fBBlockHandle\fP &h)"
.br
.ti -1c
.RI "const \fBBlockHandle\fP & \fBindex_handle\fP () const"
.br
.ti -1c
.RI "void \fBset_index_handle\fP (const \fBBlockHandle\fP &h)"
.br
.ti -1c
.RI "void \fBEncodeTo\fP (std::string *dst) const"
.br
.ti -1c
.RI "\fBStatus\fP \fBDecodeFrom\fP (\fBSlice\fP *input)"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIkEncodedLength \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Footer ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBStatus\fP DecodeFrom (\fBSlice\fP * input)"

.SS "void EncodeTo (std::string * dst) const"

.SS "const \fBBlockHandle\fP & index_handle () const\fR [inline]\fP"

.SS "const \fBBlockHandle\fP & metaindex_handle () const\fR [inline]\fP"

.SS "void set_index_handle (const \fBBlockHandle\fP & h)\fR [inline]\fP"

.SS "void set_metaindex_handle (const \fBBlockHandle\fP & h)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
