.TH "EnvWindowsTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnvWindowsTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnvWindowsTest\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetFileLimits\fP (int mmap_limit)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEnv\fP * \fBenv_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EnvWindowsTest ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void SetFileLimits (int mmap_limit)\fR [inline]\fP, \fR [static]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBEnv\fP* env_"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
