.TH "MemTable" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemTable
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <memtable\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemTable\fP (const \fBInternalKeyComparator\fP &comparator)"
.br
.ti -1c
.RI "\fBMemTable\fP (const MemTable &)=delete"
.br
.ti -1c
.RI "\fBMemTable\fP & \fBoperator=\fP (const \fBMemTable\fP &)=delete"
.br
.ti -1c
.RI "void \fBRef\fP ()"
.br
.ti -1c
.RI "void \fBUnref\fP ()"
.br
.ti -1c
.RI "size_t \fBApproximateMemoryUsage\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP * \fBNewIterator\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBSequenceNumber\fP seq, \fBValueType\fP type, const \fBSlice\fP &key, const \fBSlice\fP &value)"
.br
.ti -1c
.RI "bool \fBGet\fP (const \fBLookupKey\fP &key, std::string *value, \fBStatus\fP *s)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMemTableIterator\fP"
.br
.ti -1c
.RI "class \fBMemTableBackwardIterator\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MemTable (const \fBInternalKeyComparator\fP & comparator)\fR [explicit]\fP"

.SS "MemTable (const MemTable & )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Add (\fBSequenceNumber\fP seq, \fBValueType\fP type, const \fBSlice\fP & key, const \fBSlice\fP & value)"

.SS "size_t ApproximateMemoryUsage ()"

.SS "bool Get (const \fBLookupKey\fP & key, std::string * value, \fBStatus\fP * s)"

.SS "\fBIterator\fP * NewIterator ()"

.SS "\fBMemTable\fP & operator= (const \fBMemTable\fP & )\fR [delete]\fP"

.SS "void Ref ()\fR [inline]\fP"

.SS "void Unref ()\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class MemTableBackwardIterator\fR [friend]\fP"

.SS "friend class MemTableIterator\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
