.TH "RecoveryTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecoveryTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRecoveryTest\fP ()"
.br
.ti -1c
.RI "\fB~RecoveryTest\fP ()"
.br
.ti -1c
.RI "\fBDBImpl\fP * \fBdbfull\fP () const"
.br
.ti -1c
.RI "\fBEnv\fP * \fBenv\fP () const"
.br
.ti -1c
.RI "bool \fBCanAppend\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "\fBStatus\fP \fBOpenWithStatus\fP (\fBOptions\fP *options=nullptr)"
.br
.ti -1c
.RI "void \fBOpen\fP (\fBOptions\fP *options=nullptr)"
.br
.ti -1c
.RI "\fBStatus\fP \fBPut\fP (const std::string &k, const std::string &v)"
.br
.ti -1c
.RI "std::string \fBGet\fP (const std::string &k, const \fBSnapshot\fP *snapshot=nullptr)"
.br
.ti -1c
.RI "std::string \fBManifestFileName\fP ()"
.br
.ti -1c
.RI "std::string \fBLogName\fP (uint64_t number)"
.br
.ti -1c
.RI "size_t \fBDeleteLogFiles\fP ()"
.br
.ti -1c
.RI "void \fBDeleteManifestFile\fP ()"
.br
.ti -1c
.RI "uint64_t \fBFirstLogFile\fP ()"
.br
.ti -1c
.RI "std::vector< uint64_t > \fBGetFiles\fP (\fBFileType\fP t)"
.br
.ti -1c
.RI "int \fBNumLogs\fP ()"
.br
.ti -1c
.RI "int \fBNumTables\fP ()"
.br
.ti -1c
.RI "uint64_t \fBFileSize\fP (const std::string &fname)"
.br
.ti -1c
.RI "void \fBCompactMemTable\fP ()"
.br
.ti -1c
.RI "void \fBMakeLogFile\fP (uint64_t lognum, \fBSequenceNumber\fP seq, \fBSlice\fP key, \fBSlice\fP val)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RecoveryTest ()\fR [inline]\fP"

.SS "~\fBRecoveryTest\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool CanAppend ()\fR [inline]\fP"

.SS "void Close ()\fR [inline]\fP"

.SS "void CompactMemTable ()\fR [inline]\fP"

.SS "\fBDBImpl\fP * dbfull () const\fR [inline]\fP"

.SS "size_t DeleteLogFiles ()\fR [inline]\fP"

.SS "void DeleteManifestFile ()\fR [inline]\fP"

.SS "\fBEnv\fP * env () const\fR [inline]\fP"

.SS "uint64_t FileSize (const std::string & fname)\fR [inline]\fP"

.SS "uint64_t FirstLogFile ()\fR [inline]\fP"

.SS "std::string Get (const std::string & k, const \fBSnapshot\fP * snapshot = \fRnullptr\fP)\fR [inline]\fP"

.SS "std::vector< uint64_t > GetFiles (\fBFileType\fP t)\fR [inline]\fP"

.SS "std::string LogName (uint64_t number)\fR [inline]\fP"

.SS "void MakeLogFile (uint64_t lognum, \fBSequenceNumber\fP seq, \fBSlice\fP key, \fBSlice\fP val)\fR [inline]\fP"

.SS "std::string ManifestFileName ()\fR [inline]\fP"

.SS "int NumLogs ()\fR [inline]\fP"

.SS "int NumTables ()\fR [inline]\fP"

.SS "void Open (\fBOptions\fP * options = \fRnullptr\fP)\fR [inline]\fP"

.SS "\fBStatus\fP OpenWithStatus (\fBOptions\fP * options = \fRnullptr\fP)\fR [inline]\fP"

.SS "\fBStatus\fP Put (const std::string & k, const std::string & v)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
