.TH "WritableFile" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WritableFile
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <env\&.h>\fP
.PP
Inherited by \fBStringSink\fP, and \fBTestWritableFile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWritableFile\fP ()=default"
.br
.ti -1c
.RI "\fBWritableFile\fP (const \fBWritableFile\fP &)=delete"
.br
.ti -1c
.RI "\fBWritableFile\fP & \fBoperator=\fP (const \fBWritableFile\fP &)=delete"
.br
.ti -1c
.RI "virtual \fB~WritableFile\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBAppend\fP (const \fBSlice\fP &data)=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBClose\fP ()=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBFlush\fP ()=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBSync\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBGetName\fP () const =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBWritableFile\fP ()\fR [default]\fP"

.SS "\fBWritableFile\fP (const \fBWritableFile\fP & )\fR [delete]\fP"

.SS "~\fBWritableFile\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBStatus\fP Append (const \fBSlice\fP & data)\fR [pure virtual]\fP"

.PP
Implemented in \fBStringSink\fP, and \fBTestWritableFile\fP\&.
.SS "virtual \fBStatus\fP Close ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringSink\fP, and \fBTestWritableFile\fP\&.
.SS "virtual \fBStatus\fP Flush ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringSink\fP, and \fBTestWritableFile\fP\&.
.SS "virtual std::string GetName () const\fR [pure virtual]\fP"

.PP
Implemented in \fBStringSink\fP, and \fBTestWritableFile\fP\&.
.SS "\fBWritableFile\fP & operator= (const \fBWritableFile\fP & )\fR [delete]\fP"

.SS "virtual \fBStatus\fP Sync ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringSink\fP, and \fBTestWritableFile\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
