.TH "leveldb::log" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::log
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBReader\fP"
.br
.ti -1c
.RI "class \fBLogTest\fP"
.br
.ti -1c
.RI "class \fBWriter\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBRecordType\fP { \fBkZeroType\fP = 0, \fBkFullType\fP = 1, \fBkFirstType\fP = 2, \fBkMiddleType\fP = 3, \fBkLastType\fP = 4 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, Empty)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadWrite)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ManyBlocks)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, Fragmentation)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, MarginalTrailer)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, MarginalTrailer2)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ShortTrailer)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, AlignedEof)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, OpenForAppend)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, RandomRead)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadError)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, BadRecordType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, TruncatedTrailingRecordIsIgnored)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, BadLength)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, BadLengthAtEndIsIgnored)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ChecksumMismatch)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, UnexpectedMiddleType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, UnexpectedLastType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, UnexpectedFullType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, UnexpectedFirstType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, MissingLastIsIgnored)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, PartialLastIsIgnored)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, SkipIntoMultiRecord)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ErrorJoinsRecords)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadStart)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadSecondOneOff)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadSecondTenThousand)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadSecondStart)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadThirdOneOff)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadThirdStart)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadFourthOneOff)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadFourthFirstBlockTrailer)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadFourthMiddleBlock)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadFourthLastBlock)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadFourthStart)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadInitialOffsetIntoBlockPadding)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadEnd)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadPastEnd)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBRecordType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIkZeroType \fP
.TP
\f(BIkFullType \fP
.TP
\f(BIkFirstType \fP
.TP
\f(BIkMiddleType \fP
.TP
\f(BIkLastType \fP
.SH "Function Documentation"
.PP 
.SS "TEST (\fBLogTest\fP , AlignedEof )"

.SS "TEST (\fBLogTest\fP , BadLength )"

.SS "TEST (\fBLogTest\fP , BadLengthAtEndIsIgnored )"

.SS "TEST (\fBLogTest\fP , BadRecordType )"

.SS "TEST (\fBLogTest\fP , ChecksumMismatch )"

.SS "TEST (\fBLogTest\fP , Empty )"

.SS "TEST (\fBLogTest\fP , ErrorJoinsRecords )"

.SS "TEST (\fBLogTest\fP , Fragmentation )"

.SS "TEST (\fBLogTest\fP , ManyBlocks )"

.SS "TEST (\fBLogTest\fP , MarginalTrailer )"

.SS "TEST (\fBLogTest\fP , MarginalTrailer2 )"

.SS "TEST (\fBLogTest\fP , MissingLastIsIgnored )"

.SS "TEST (\fBLogTest\fP , OpenForAppend )"

.SS "TEST (\fBLogTest\fP , PartialLastIsIgnored )"

.SS "TEST (\fBLogTest\fP , RandomRead )"

.SS "TEST (\fBLogTest\fP , ReadEnd )"

.SS "TEST (\fBLogTest\fP , ReadError )"

.SS "TEST (\fBLogTest\fP , ReadFourthFirstBlockTrailer )"

.SS "TEST (\fBLogTest\fP , ReadFourthLastBlock )"

.SS "TEST (\fBLogTest\fP , ReadFourthMiddleBlock )"

.SS "TEST (\fBLogTest\fP , ReadFourthOneOff )"

.SS "TEST (\fBLogTest\fP , ReadFourthStart )"

.SS "TEST (\fBLogTest\fP , ReadInitialOffsetIntoBlockPadding )"

.SS "TEST (\fBLogTest\fP , ReadPastEnd )"

.SS "TEST (\fBLogTest\fP , ReadSecondOneOff )"

.SS "TEST (\fBLogTest\fP , ReadSecondStart )"

.SS "TEST (\fBLogTest\fP , ReadSecondTenThousand )"

.SS "TEST (\fBLogTest\fP , ReadStart )"

.SS "TEST (\fBLogTest\fP , ReadThirdOneOff )"

.SS "TEST (\fBLogTest\fP , ReadThirdStart )"

.SS "TEST (\fBLogTest\fP , ReadWrite )"

.SS "TEST (\fBLogTest\fP , ShortTrailer )"

.SS "TEST (\fBLogTest\fP , SkipIntoMultiRecord )"

.SS "TEST (\fBLogTest\fP , TruncatedTrailingRecordIsIgnored )"

.SS "TEST (\fBLogTest\fP , UnexpectedFirstType )"

.SS "TEST (\fBLogTest\fP , UnexpectedFullType )"

.SS "TEST (\fBLogTest\fP , UnexpectedLastType )"

.SS "TEST (\fBLogTest\fP , UnexpectedMiddleType )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
