.TH "WindowsLogger" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsLogger
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <windows_logger\&.h>\fP
.PP
Inherits \fBLogger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindowsLogger\fP (std::FILE *fp)"
.br
.ti -1c
.RI "\fB~WindowsLogger\fP () override"
.br
.ti -1c
.RI "void \fBLogv\fP (const char *format, va_list arguments) override"
.br
.in -1c

Public Member Functions inherited from \fBLogger\fP
.in +1c
.ti -1c
.RI "\fBLogger\fP ()=default"
.br
.ti -1c
.RI "\fBLogger\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "\fBLogger\fP & \fBoperator=\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "virtual \fB~Logger\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WindowsLogger (std::FILE * fp)\fR [inline]\fP, \fR [explicit]\fP"

.SS "~\fBWindowsLogger\fP ()\fR [inline]\fP, \fR [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Logv (const char * format, va_list arguments)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBLogger\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
