.TH "Slice" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Slice
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <slice\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSlice\fP ()"
.br
.ti -1c
.RI "\fBSlice\fP (const char *d, size_t n)"
.br
.ti -1c
.RI "\fBSlice\fP (const std::string &s)"
.br
.ti -1c
.RI "\fBSlice\fP (const char *s)"
.br
.ti -1c
.RI "\fBSlice\fP (const \fBSlice\fP &)=default"
.br
.ti -1c
.RI "\fBSlice\fP & \fBoperator=\fP (const \fBSlice\fP &)=default"
.br
.ti -1c
.RI "const char * \fBdata\fP () const"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "const char * \fBbegin\fP () const"
.br
.ti -1c
.RI "const char * \fBend\fP () const"
.br
.ti -1c
.RI "char \fBoperator[]\fP (size_t n) const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBremove_prefix\fP (size_t n)"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "int \fBcompare\fP (const \fBSlice\fP &b) const"
.br
.ti -1c
.RI "bool \fBstarts_with\fP (const \fBSlice\fP &x) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSlice\fP ()\fR [inline]\fP"

.SS "\fBSlice\fP (const char * d, size_t n)\fR [inline]\fP"

.SS "\fBSlice\fP (const std::string & s)\fR [inline]\fP"

.SS "\fBSlice\fP (const char * s)\fR [inline]\fP"

.SS "\fBSlice\fP (const \fBSlice\fP & )\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const char * begin () const\fR [inline]\fP"

.SS "void clear ()\fR [inline]\fP"

.SS "int compare (const \fBSlice\fP & b) const\fR [inline]\fP"

.SS "const char * data () const\fR [inline]\fP"

.SS "bool empty () const\fR [inline]\fP"

.SS "const char * end () const\fR [inline]\fP"

.SS "\fBSlice\fP & operator= (const \fBSlice\fP & )\fR [default]\fP"

.SS "char operator[] (size_t n) const\fR [inline]\fP"

.SS "void remove_prefix (size_t n)\fR [inline]\fP"

.SS "size_t size () const\fR [inline]\fP"

.SS "bool starts_with (const \fBSlice\fP & x) const\fR [inline]\fP"

.SS "std::string ToString () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
