.TH "ReadOptions" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadOptions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <options\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReadOptions\fP ()=default"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBverify_checksums\fP = false"
.br
.ti -1c
.RI "bool \fBfill_cache\fP = true"
.br
.ti -1c
.RI "const \fBSnapshot\fP * \fBsnapshot\fP = nullptr"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBReadOptions\fP ()\fR [default]\fP"

.SH "Field Documentation"
.PP 
.SS "bool fill_cache = true"

.SS "const \fBSnapshot\fP* snapshot = nullptr"

.SS "bool verify_checksums = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
