.TH "ConcurrentTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConcurrentTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConcurrentTest\fP ()"
.br
.ti -1c
.RI "void \fBWriteStep\fP (\fBRandom\fP *rnd)"
.br
.ti -1c
.RI "void \fBReadStep\fP (\fBRandom\fP *rnd)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConcurrentTest ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ReadStep (\fBRandom\fP * rnd)\fR [inline]\fP"

.SS "void WriteStep (\fBRandom\fP * rnd)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
