.TH "IteratorWrapper" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IteratorWrapper
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <iterator_wrapper\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIteratorWrapper\fP ()"
.br
.ti -1c
.RI "\fBIteratorWrapper\fP (\fBIterator\fP *\fBiter\fP)"
.br
.ti -1c
.RI "\fB~IteratorWrapper\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP * \fBiter\fP () const"
.br
.ti -1c
.RI "void \fBSet\fP (\fBIterator\fP *\fBiter\fP)"
.br
.ti -1c
.RI "bool \fBValid\fP () const"
.br
.ti -1c
.RI "\fBSlice\fP \fBkey\fP () const"
.br
.ti -1c
.RI "\fBSlice\fP \fBvalue\fP () const"
.br
.ti -1c
.RI "\fBStatus\fP \fBstatus\fP () const"
.br
.ti -1c
.RI "void \fBNext\fP ()"
.br
.ti -1c
.RI "void \fBPrev\fP ()"
.br
.ti -1c
.RI "void \fBSeek\fP (const \fBSlice\fP &k)"
.br
.ti -1c
.RI "void \fBSeekToFirst\fP ()"
.br
.ti -1c
.RI "void \fBSeekToLast\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IteratorWrapper ()\fR [inline]\fP"

.SS "IteratorWrapper (\fBIterator\fP * iter)\fR [inline]\fP, \fR [explicit]\fP"

.SS "~\fBIteratorWrapper\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBIterator\fP * iter () const\fR [inline]\fP"

.SS "\fBSlice\fP key () const\fR [inline]\fP"

.SS "void Next ()\fR [inline]\fP"

.SS "void Prev ()\fR [inline]\fP"

.SS "void Seek (const \fBSlice\fP & k)\fR [inline]\fP"

.SS "void SeekToFirst ()\fR [inline]\fP"

.SS "void SeekToLast ()\fR [inline]\fP"

.SS "void Set (\fBIterator\fP * iter)\fR [inline]\fP"

.SS "\fBStatus\fP status () const\fR [inline]\fP"

.SS "bool Valid () const\fR [inline]\fP"

.SS "\fBSlice\fP value () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
