.TH "VersionSet::Builder" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VersionSet::Builder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuilder\fP (\fBVersionSet\fP *vset, \fBVersion\fP *base)"
.br
.ti -1c
.RI "\fB~Builder\fP ()"
.br
.ti -1c
.RI "void \fBApply\fP (\fBVersionEdit\fP *edit)"
.br
.ti -1c
.RI "void \fBSaveTo\fP (\fBVersion\fP *v)"
.br
.ti -1c
.RI "void \fBMaybeAddFile\fP (\fBVersion\fP *v, int level, \fBFileMetaData\fP *f)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Builder (\fBVersionSet\fP * vset, \fBVersion\fP * base)\fR [inline]\fP"

.SS "~\fBBuilder\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Apply (\fBVersionEdit\fP * edit)\fR [inline]\fP"

.SS "void MaybeAddFile (\fBVersion\fP * v, int level, \fBFileMetaData\fP * f)\fR [inline]\fP"

.SS "void SaveTo (\fBVersion\fP * v)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
