.TH "AddBoundaryInputsTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddBoundaryInputsTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddBoundaryInputsTest\fP ()"
.br
.ti -1c
.RI "\fB~AddBoundaryInputsTest\fP ()"
.br
.ti -1c
.RI "\fBFileMetaData\fP * \fBCreateFileMetaData\fP (uint64_t number, \fBInternalKey\fP smallest, \fBInternalKey\fP largest)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< \fBFileMetaData\fP * > \fBlevel_files_\fP"
.br
.ti -1c
.RI "std::vector< \fBFileMetaData\fP * > \fBcompaction_files_\fP"
.br
.ti -1c
.RI "std::vector< \fBFileMetaData\fP * > \fBall_files_\fP"
.br
.ti -1c
.RI "\fBInternalKeyComparator\fP \fBicmp_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddBoundaryInputsTest ()\fR [inline]\fP"

.SS "~\fBAddBoundaryInputsTest\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBFileMetaData\fP * CreateFileMetaData (uint64_t number, \fBInternalKey\fP smallest, \fBInternalKey\fP largest)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::vector<\fBFileMetaData\fP*> all_files_"

.SS "std::vector<\fBFileMetaData\fP*> compaction_files_"

.SS "\fBInternalKeyComparator\fP icmp_"

.SS "std::vector<\fBFileMetaData\fP*> level_files_"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
