.TH "SnapshotImpl" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SnapshotImpl
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <snapshot\&.h>\fP
.PP
Inherits \fBSnapshot\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSnapshotImpl\fP (\fBSequenceNumber\fP \fBsequence_number\fP)"
.br
.ti -1c
.RI "\fBSequenceNumber\fP \fBsequence_number\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSnapshotList\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBSnapshot\fP
.in +1c
.ti -1c
.RI "virtual \fB~Snapshot\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SnapshotImpl (\fBSequenceNumber\fP sequence_number)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBSequenceNumber\fP sequence_number () const\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class SnapshotList\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
