.TH "ModelDB::ModelSnapshot" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelDB::ModelSnapshot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSnapshot\fP\&.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKVMap\fP \fBmap_\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBSnapshot\fP
.in +1c
.ti -1c
.RI "virtual \fB~Snapshot\fP ()"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBKVMap\fP map_"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
