.TH "BloomTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BloomTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBloomTest\fP ()"
.br
.ti -1c
.RI "\fB~BloomTest\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (const \fBSlice\fP &s)"
.br
.ti -1c
.RI "void \fBBuild\fP ()"
.br
.ti -1c
.RI "size_t \fBFilterSize\fP () const"
.br
.ti -1c
.RI "void \fBDumpFilter\fP ()"
.br
.ti -1c
.RI "bool \fBMatches\fP (const \fBSlice\fP &s)"
.br
.ti -1c
.RI "double \fBFalsePositiveRate\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BloomTest ()\fR [inline]\fP"

.SS "~\fBBloomTest\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Add (const \fBSlice\fP & s)\fR [inline]\fP"

.SS "void Build ()\fR [inline]\fP"

.SS "void DumpFilter ()\fR [inline]\fP"

.SS "double FalsePositiveRate ()\fR [inline]\fP"

.SS "size_t FilterSize () const\fR [inline]\fP"

.SS "bool Matches (const \fBSlice\fP & s)\fR [inline]\fP"

.SS "void Reset ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
