.TH "leveldb_comparator_t" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb_comparator_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComparator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~leveldb_comparator_t\fP () override"
.br
.ti -1c
.RI "int \fBCompare\fP (const \fBSlice\fP &a, const \fBSlice\fP &b) const override"
.br
.ti -1c
.RI "const char * \fBName\fP () const override"
.br
.ti -1c
.RI "void \fBFindShortestSeparator\fP (std::string *, const \fBSlice\fP &) const override"
.br
.ti -1c
.RI "void \fBFindShortSuccessor\fP (std::string *key) const override"
.br
.in -1c

Public Member Functions inherited from \fBComparator\fP
.in +1c
.ti -1c
.RI "int \fBoperator()\fP (const \fBKey\fP &a, const \fBKey\fP &b) const"
.br
.ti -1c
.RI "virtual \fB~Comparator\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBstate_\fP"
.br
.ti -1c
.RI "void(* \fBdestructor_\fP )(void *)"
.br
.ti -1c
.RI "int(* \fBcompare_\fP )(void *, const char *a, size_t alen, const char *b, size_t blen)"
.br
.ti -1c
.RI "const char *(* \fBname_\fP )(void *)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "~\fBleveldb_comparator_t\fP ()\fR [inline]\fP, \fR [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int Compare (const \fBSlice\fP & a, const \fBSlice\fP & b) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBComparator\fP\&.
.SS "void FindShortestSeparator (std::string * , const \fBSlice\fP & ) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBComparator\fP\&.
.SS "void FindShortSuccessor (std::string * key) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBComparator\fP\&.
.SS "const char * Name () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBComparator\fP\&.
.SH "Field Documentation"
.PP 
.SS "int(* compare_) (void *, const char *a, size_t alen, const char *b, size_t blen)"

.SS "void(* destructor_) (void *)"

.SS "const char *(* name_) (void *)"

.SS "void* state_"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
