.TH "WriteBatchInternal" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WriteBatchInternal
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <write_batch_internal\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBCount\fP (const \fBWriteBatch\fP *batch)"
.br
.ti -1c
.RI "static void \fBSetCount\fP (\fBWriteBatch\fP *batch, int n)"
.br
.ti -1c
.RI "static \fBSequenceNumber\fP \fBSequence\fP (const \fBWriteBatch\fP *batch)"
.br
.ti -1c
.RI "static void \fBSetSequence\fP (\fBWriteBatch\fP *batch, \fBSequenceNumber\fP seq)"
.br
.ti -1c
.RI "static \fBSlice\fP \fBContents\fP (const \fBWriteBatch\fP *batch)"
.br
.ti -1c
.RI "static size_t \fBByteSize\fP (const \fBWriteBatch\fP *batch)"
.br
.ti -1c
.RI "static void \fBSetContents\fP (\fBWriteBatch\fP *batch, const \fBSlice\fP &contents)"
.br
.ti -1c
.RI "static \fBStatus\fP \fBInsertInto\fP (const \fBWriteBatch\fP *batch, \fBMemTable\fP *memtable)"
.br
.ti -1c
.RI "static void \fBAppend\fP (\fBWriteBatch\fP *dst, const \fBWriteBatch\fP *src)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Append (\fBWriteBatch\fP * dst, const \fBWriteBatch\fP * src)\fR [static]\fP"

.SS "size_t ByteSize (const \fBWriteBatch\fP * batch)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBSlice\fP Contents (const \fBWriteBatch\fP * batch)\fR [inline]\fP, \fR [static]\fP"

.SS "int Count (const \fBWriteBatch\fP * batch)\fR [static]\fP"

.SS "\fBStatus\fP InsertInto (const \fBWriteBatch\fP * batch, \fBMemTable\fP * memtable)\fR [static]\fP"

.SS "\fBSequenceNumber\fP Sequence (const \fBWriteBatch\fP * batch)\fR [static]\fP"

.SS "void SetContents (\fBWriteBatch\fP * batch, const \fBSlice\fP & contents)\fR [static]\fP"

.SS "void SetCount (\fBWriteBatch\fP * batch, int n)\fR [static]\fP"

.SS "void SetSequence (\fBWriteBatch\fP * batch, \fBSequenceNumber\fP seq)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
