.TH "Random" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Random
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <random\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandom\fP (uint32_t s)"
.br
.ti -1c
.RI "uint32_t \fBNext\fP ()"
.br
.ti -1c
.RI "uint32_t \fBUniform\fP (int n)"
.br
.ti -1c
.RI "bool \fBOneIn\fP (int n)"
.br
.ti -1c
.RI "uint32_t \fBSkewed\fP (int max_log)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Random (uint32_t s)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "uint32_t Next ()\fR [inline]\fP"

.SS "bool OneIn (int n)\fR [inline]\fP"

.SS "uint32_t Skewed (int max_log)\fR [inline]\fP"

.SS "uint32_t Uniform (int n)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
