.TH "BlockBuilder" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <block_builder\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockBuilder\fP (const \fBOptions\fP *options)"
.br
.ti -1c
.RI "\fBBlockBuilder\fP (const BlockBuilder &)=delete"
.br
.ti -1c
.RI "\fBBlockBuilder\fP & \fBoperator=\fP (const \fBBlockBuilder\fP &)=delete"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (const \fBSlice\fP &key, const \fBSlice\fP &value)"
.br
.ti -1c
.RI "\fBSlice\fP \fBFinish\fP ()"
.br
.ti -1c
.RI "size_t \fBCurrentSizeEstimate\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockBuilder (const \fBOptions\fP * options)\fR [explicit]\fP"

.SS "BlockBuilder (const BlockBuilder & )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Add (const \fBSlice\fP & key, const \fBSlice\fP & value)"

.SS "size_t CurrentSizeEstimate () const"

.SS "bool empty () const\fR [inline]\fP"

.SS "\fBSlice\fP Finish ()"

.SS "\fBBlockBuilder\fP & operator= (const \fBBlockBuilder\fP & )\fR [delete]\fP"

.SS "void Reset ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
