.TH "FileMetaData" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileMetaData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <version_edit\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileMetaData\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBrefs\fP"
.br
.ti -1c
.RI "int \fBallowed_seeks\fP"
.br
.ti -1c
.RI "uint64_t \fBnumber\fP"
.br
.ti -1c
.RI "uint64_t \fBfile_size\fP"
.br
.ti -1c
.RI "\fBInternalKey\fP \fBsmallest\fP"
.br
.ti -1c
.RI "\fBInternalKey\fP \fBlargest\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileMetaData ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "int allowed_seeks"

.SS "uint64_t file_size"

.SS "\fBInternalKey\fP largest"

.SS "uint64_t number"

.SS "int refs"

.SS "\fBInternalKey\fP smallest"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
