.TH "MutexLock" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MutexLock
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mutexlock\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutexLock\fP (\fBport::Mutex\fP *mu) \fBEXCLUSIVE_LOCK_FUNCTION\fP(mu)"
.br
.ti -1c
.RI "\fB~MutexLock\fP () \fBUNLOCK_FUNCTION\fP()"
.br
.ti -1c
.RI "\fBMutexLock\fP (const MutexLock &)=delete"
.br
.ti -1c
.RI "\fBMutexLock\fP & \fBoperator=\fP (const \fBMutexLock\fP &)=delete"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MutexLock (\fBport::Mutex\fP * mu)\fR [inline]\fP, \fR [explicit]\fP"

.SS "~\fBMutexLock\fP ()\fR [inline]\fP"

.SS "MutexLock (const MutexLock & )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBMutexLock\fP & operator= (const \fBMutexLock\fP & )\fR [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
