.TH "Tester" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tester
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testharness\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTester\fP (const char *f, int l)"
.br
.ti -1c
.RI "\fB~Tester\fP ()"
.br
.ti -1c
.RI "\fBTester\fP & \fBIs\fP (bool b, const char *msg)"
.br
.ti -1c
.RI "\fBTester\fP & \fBIsOk\fP (const \fBStatus\fP &s)"
.br
.ti -1c
.RI "template<class V> \fBTester\fP & \fBoperator<<\fP (const V &value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Tester (const char * f, int l)\fR [inline]\fP"

.SS "~\fBTester\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBTester\fP & Is (bool b, const char * msg)\fR [inline]\fP"

.SS "\fBTester\fP & IsOk (const \fBStatus\fP & s)\fR [inline]\fP"

.SS "template<class V> \fBTester\fP & operator<< (const V & value)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
