.TH "FileLock" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileLock
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <env\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileLock\fP ()=default"
.br
.ti -1c
.RI "\fBFileLock\fP (const \fBFileLock\fP &)=delete"
.br
.ti -1c
.RI "\fBFileLock\fP & \fBoperator=\fP (const \fBFileLock\fP &)=delete"
.br
.ti -1c
.RI "virtual \fB~FileLock\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFileLock\fP ()\fR [default]\fP"

.SS "\fBFileLock\fP (const \fBFileLock\fP & )\fR [delete]\fP"

.SS "~\fBFileLock\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBFileLock\fP & operator= (const \fBFileLock\fP & )\fR [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
