.TH "FaultInjectionTestEnv" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaultInjectionTestEnv
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEnvWrapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFaultInjectionTestEnv\fP ()"
.br
.ti -1c
.RI "\fB~FaultInjectionTestEnv\fP () override=default"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewWritableFile\fP (const std::string &fname, \fBWritableFile\fP **result) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewAppendableFile\fP (const std::string &fname, \fBWritableFile\fP **result) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBDeleteFile\fP (const std::string &f) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBRenameFile\fP (const std::string &s, const std::string &t) override"
.br
.ti -1c
.RI "void \fBWritableFileClosed\fP (const FileState &state)"
.br
.ti -1c
.RI "\fBStatus\fP \fBDropUnsyncedFileData\fP ()"
.br
.ti -1c
.RI "\fBStatus\fP \fBDeleteFilesCreatedAfterLastDirSync\fP ()"
.br
.ti -1c
.RI "void \fBDirWasSynced\fP ()"
.br
.ti -1c
.RI "bool \fBIsFileCreatedSinceLastDirSync\fP (const std::string &filename)"
.br
.ti -1c
.RI "void \fBResetState\fP ()"
.br
.ti -1c
.RI "void \fBUntrackFile\fP (const std::string &f)"
.br
.ti -1c
.RI "bool \fBIsFilesystemActive\fP () \fBLOCKS_EXCLUDED\fP(mutex_)"
.br
.ti -1c
.RI "void \fBSetFilesystemActive\fP (bool active) \fBLOCKS_EXCLUDED\fP(mutex_)"
.br
.in -1c

Public Member Functions inherited from \fBEnvWrapper\fP
.in +1c
.ti -1c
.RI "\fBEnvWrapper\fP (\fBEnv\fP *t)"
.br
.ti -1c
.RI "virtual \fB~EnvWrapper\fP ()"
.br
.ti -1c
.RI "\fBEnv\fP * \fBtarget\fP () const"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewSequentialFile\fP (const std::string &f, \fBSequentialFile\fP **r) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewRandomAccessFile\fP (const std::string &f, \fBRandomAccessFile\fP **r) override"
.br
.ti -1c
.RI "bool \fBFileExists\fP (const std::string &f) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBGetChildren\fP (const std::string &dir, std::vector< std::string > *r) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBCreateDir\fP (const std::string &d) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBDeleteDir\fP (const std::string &d) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBGetFileSize\fP (const std::string &f, uint64_t *s) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBLockFile\fP (const std::string &f, \fBFileLock\fP **l) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBUnlockFile\fP (\fBFileLock\fP *l) override"
.br
.ti -1c
.RI "void \fBSchedule\fP (void(*f)(void *), void *a) override"
.br
.ti -1c
.RI "void \fBStartThread\fP (void(*f)(void *), void *a) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBGetTestDirectory\fP (std::string *path) override"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewLogger\fP (const std::string &fname, \fBLogger\fP **result) override"
.br
.ti -1c
.RI "uint64_t \fBNowMicros\fP () override"
.br
.ti -1c
.RI "void \fBSleepForMicroseconds\fP (int micros) override"
.br
.in -1c

Public Member Functions inherited from \fBEnv\fP
.in +1c
.ti -1c
.RI "\fBEnv\fP ()=default"
.br
.ti -1c
.RI "\fBEnv\fP (const \fBEnv\fP &)=delete"
.br
.ti -1c
.RI "\fBEnv\fP & \fBoperator=\fP (const \fBEnv\fP &)=delete"
.br
.ti -1c
.RI "virtual \fB~Env\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEnv\fP
.in +1c
.ti -1c
.RI "static \fBEnv\fP * \fBDefault\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FaultInjectionTestEnv ()\fR [inline]\fP"

.SS "~\fBFaultInjectionTestEnv\fP ()\fR [override]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBStatus\fP DeleteFile (const std::string & f)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBEnvWrapper\fP\&.
.SS "\fBStatus\fP DeleteFilesCreatedAfterLastDirSync ()"

.SS "void DirWasSynced ()"

.SS "\fBStatus\fP DropUnsyncedFileData ()"

.SS "bool IsFileCreatedSinceLastDirSync (const std::string & filename)"

.SS "bool IsFilesystemActive ()\fR [inline]\fP"

.SS "\fBStatus\fP NewAppendableFile (const std::string & fname, \fBWritableFile\fP ** result)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBEnvWrapper\fP\&.
.SS "\fBStatus\fP NewWritableFile (const std::string & fname, \fBWritableFile\fP ** result)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBEnvWrapper\fP\&.
.SS "\fBStatus\fP RenameFile (const std::string & s, const std::string & t)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBEnvWrapper\fP\&.
.SS "void ResetState ()"

.SS "void SetFilesystemActive (bool active)\fR [inline]\fP"

.SS "void UntrackFile (const std::string & f)"

.SS "void WritableFileClosed (const FileState & state)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
