.TH "Arena" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arena
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <arena\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArena\fP ()"
.br
.ti -1c
.RI "\fBArena\fP (const \fBArena\fP &)=delete"
.br
.ti -1c
.RI "\fBArena\fP & \fBoperator=\fP (const \fBArena\fP &)=delete"
.br
.ti -1c
.RI "\fB~Arena\fP ()"
.br
.ti -1c
.RI "char * \fBAllocate\fP (size_t bytes)"
.br
.ti -1c
.RI "char * \fBAllocateAligned\fP (size_t bytes)"
.br
.ti -1c
.RI "size_t \fBMemoryUsage\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBArena\fP ()"

.SS "\fBArena\fP (const \fBArena\fP & )\fR [delete]\fP"

.SS "~\fBArena\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "char * Allocate (size_t bytes)\fR [inline]\fP"

.SS "char * AllocateAligned (size_t bytes)"

.SS "size_t MemoryUsage () const\fR [inline]\fP"

.SS "\fBArena\fP & operator= (const \fBArena\fP & )\fR [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
