.TH "BlockHandle" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockHandle
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <format\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBkMaxEncodedLength\fP = 10 + 10 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockHandle\fP ()"
.br
.ti -1c
.RI "uint64_t \fBoffset\fP () const"
.br
.ti -1c
.RI "void \fBset_offset\fP (uint64_t \fBoffset\fP)"
.br
.ti -1c
.RI "uint64_t \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBset_size\fP (uint64_t \fBsize\fP)"
.br
.ti -1c
.RI "void \fBEncodeTo\fP (std::string *dst) const"
.br
.ti -1c
.RI "\fBStatus\fP \fBDecodeFrom\fP (\fBSlice\fP *input)"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIkMaxEncodedLength \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockHandle ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBStatus\fP DecodeFrom (\fBSlice\fP * input)"

.SS "void EncodeTo (std::string * dst) const"

.SS "uint64_t offset () const\fR [inline]\fP"

.SS "void set_offset (uint64_t offset)\fR [inline]\fP"

.SS "void set_size (uint64_t size)\fR [inline]\fP"

.SS "uint64_t size () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
