.TH "LookupKey" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LookupKey
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <dbformat\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLookupKey\fP (const \fBSlice\fP &\fBuser_key\fP, \fBSequenceNumber\fP \fBsequence\fP)"
.br
.ti -1c
.RI "\fBLookupKey\fP (const LookupKey &)=delete"
.br
.ti -1c
.RI "\fBLookupKey\fP & \fBoperator=\fP (const \fBLookupKey\fP &)=delete"
.br
.ti -1c
.RI "\fB~LookupKey\fP ()"
.br
.ti -1c
.RI "\fBSlice\fP \fBmemtable_key\fP () const"
.br
.ti -1c
.RI "\fBSlice\fP \fBinternal_key\fP () const"
.br
.ti -1c
.RI "\fBSlice\fP \fBuser_key\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LookupKey (const \fBSlice\fP & user_key, \fBSequenceNumber\fP sequence)"

.SS "LookupKey (const LookupKey & )\fR [delete]\fP"

.SS "~\fBLookupKey\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBSlice\fP internal_key () const\fR [inline]\fP"

.SS "\fBSlice\fP memtable_key () const\fR [inline]\fP"

.SS "\fBLookupKey\fP & operator= (const \fBLookupKey\fP & )\fR [delete]\fP"

.SS "\fBSlice\fP user_key () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
