.TH "WriteOptions" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WriteOptions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <options\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWriteOptions\fP ()=default"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBsync\fP = false"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBWriteOptions\fP ()\fR [default]\fP"

.SH "Field Documentation"
.PP 
.SS "bool sync = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
