.TH "SnapshotList" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SnapshotList
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <snapshot\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSnapshotList\fP ()"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "\fBSnapshotImpl\fP * \fBoldest\fP () const"
.br
.ti -1c
.RI "\fBSnapshotImpl\fP * \fBnewest\fP () const"
.br
.ti -1c
.RI "\fBSnapshotImpl\fP * \fBNew\fP (\fBSequenceNumber\fP sequence_number)"
.br
.ti -1c
.RI "void \fBDelete\fP (const \fBSnapshotImpl\fP *snapshot)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SnapshotList ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Delete (const \fBSnapshotImpl\fP * snapshot)\fR [inline]\fP"

.SS "bool empty () const\fR [inline]\fP"

.SS "\fBSnapshotImpl\fP * New (\fBSequenceNumber\fP sequence_number)\fR [inline]\fP"

.SS "\fBSnapshotImpl\fP * newest () const\fR [inline]\fP"

.SS "\fBSnapshotImpl\fP * oldest () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
