.TH "CorruptionTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CorruptionTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCorruptionTest\fP ()"
.br
.ti -1c
.RI "\fB~CorruptionTest\fP ()"
.br
.ti -1c
.RI "\fBStatus\fP \fBTryReopen\fP ()"
.br
.ti -1c
.RI "void \fBReopen\fP ()"
.br
.ti -1c
.RI "void \fBRepairDB\fP ()"
.br
.ti -1c
.RI "void \fBBuild\fP (int n)"
.br
.ti -1c
.RI "void \fBCheck\fP (int min_expected, int max_expected)"
.br
.ti -1c
.RI "void \fBCorrupt\fP (\fBFileType\fP filetype, int offset, int bytes_to_corrupt)"
.br
.ti -1c
.RI "int \fBProperty\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "\fBSlice\fP \fBKey\fP (int i, std::string *storage)"
.br
.ti -1c
.RI "\fBSlice\fP \fBValue\fP (int k, std::string *storage)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtest::ErrorEnv\fP \fBenv_\fP"
.br
.ti -1c
.RI "\fBOptions\fP \fBoptions_\fP"
.br
.ti -1c
.RI "\fBDB\fP * \fBdb_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CorruptionTest ()\fR [inline]\fP"

.SS "~\fBCorruptionTest\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Build (int n)\fR [inline]\fP"

.SS "void Check (int min_expected, int max_expected)\fR [inline]\fP"

.SS "void Corrupt (\fBFileType\fP filetype, int offset, int bytes_to_corrupt)\fR [inline]\fP"

.SS "\fBSlice\fP \fBKey\fP (int i, std::string * storage)\fR [inline]\fP"

.SS "int Property (const std::string & name)\fR [inline]\fP"

.SS "void Reopen ()\fR [inline]\fP"

.SS "void RepairDB ()\fR [inline]\fP"

.SS "\fBStatus\fP TryReopen ()\fR [inline]\fP"

.SS "\fBSlice\fP Value (int k, std::string * storage)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBDB\fP* db_"

.SS "\fBtest::ErrorEnv\fP env_"

.SS "\fBOptions\fP options_"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
