.TH "TableBuilder" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <table_builder\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBRep\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTableBuilder\fP (const \fBOptions\fP &options, \fBWritableFile\fP *file)"
.br
.ti -1c
.RI "\fBTableBuilder\fP (const TableBuilder &)=delete"
.br
.ti -1c
.RI "\fBTableBuilder\fP & \fBoperator=\fP (const \fBTableBuilder\fP &)=delete"
.br
.ti -1c
.RI "\fB~TableBuilder\fP ()"
.br
.ti -1c
.RI "\fBStatus\fP \fBChangeOptions\fP (const \fBOptions\fP &options)"
.br
.ti -1c
.RI "void \fBAdd\fP (const \fBSlice\fP &key, const \fBSlice\fP &value)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "\fBStatus\fP \fBstatus\fP () const"
.br
.ti -1c
.RI "\fBStatus\fP \fBFinish\fP ()"
.br
.ti -1c
.RI "void \fBAbandon\fP ()"
.br
.ti -1c
.RI "uint64_t \fBNumEntries\fP () const"
.br
.ti -1c
.RI "uint64_t \fBFileSize\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TableBuilder (const \fBOptions\fP & options, \fBWritableFile\fP * file)"

.SS "TableBuilder (const TableBuilder & )\fR [delete]\fP"

.SS "~\fBTableBuilder\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void Abandon ()"

.SS "void Add (const \fBSlice\fP & key, const \fBSlice\fP & value)"

.SS "\fBStatus\fP ChangeOptions (const \fBOptions\fP & options)"

.SS "uint64_t FileSize () const"

.SS "\fBStatus\fP Finish ()"

.SS "void Flush ()"

.SS "uint64_t NumEntries () const"

.SS "\fBTableBuilder\fP & operator= (const \fBTableBuilder\fP & )\fR [delete]\fP"

.SS "\fBStatus\fP status () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
