.TH "SkipList< Key, Comparator >::Iterator" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkipList< Key, Comparator >::Iterator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <skiplist\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP (const \fBSkipList\fP *list)"
.br
.ti -1c
.RI "bool \fBValid\fP () const"
.br
.ti -1c
.RI "const \fBKey\fP & \fBkey\fP () const"
.br
.ti -1c
.RI "void \fBNext\fP ()"
.br
.ti -1c
.RI "void \fBPrev\fP ()"
.br
.ti -1c
.RI "void \fBSeek\fP (const \fBKey\fP &target)"
.br
.ti -1c
.RI "void \fBSeekToFirst\fP ()"
.br
.ti -1c
.RI "void \fBSeekToLast\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBKey\fP, class \fBComparator\fP> \fBIterator\fP (const \fBSkipList\fP * list)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBKey\fP, class \fBComparator\fP> const \fBKey\fP & key () const\fR [inline]\fP"

.SS "template<typename \fBKey\fP, class \fBComparator\fP> void Next ()\fR [inline]\fP"

.SS "template<typename \fBKey\fP, class \fBComparator\fP> void Prev ()\fR [inline]\fP"

.SS "template<typename \fBKey\fP, class \fBComparator\fP> void Seek (const \fBKey\fP & target)\fR [inline]\fP"

.SS "template<typename \fBKey\fP, class \fBComparator\fP> void SeekToFirst ()\fR [inline]\fP"

.SS "template<typename \fBKey\fP, class \fBComparator\fP> void SeekToLast ()\fR [inline]\fP"

.SS "template<typename \fBKey\fP, class \fBComparator\fP> bool Valid () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
