.TH "Reader" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <log_reader\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBReporter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReader\fP (\fBSequentialFile\fP *file, \fBReporter\fP *reporter, bool checksum, uint64_t initial_offset)"
.br
.ti -1c
.RI "\fBReader\fP (const Reader &)=delete"
.br
.ti -1c
.RI "\fBReader\fP & \fBoperator=\fP (const \fBReader\fP &)=delete"
.br
.ti -1c
.RI "\fB~Reader\fP ()"
.br
.ti -1c
.RI "bool \fBReadRecord\fP (\fBSlice\fP *record, std::string *scratch)"
.br
.ti -1c
.RI "uint64_t \fBLastRecordOffset\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Reader (\fBSequentialFile\fP * file, \fBReporter\fP * reporter, bool checksum, uint64_t initial_offset)"

.SS "Reader (const Reader & )\fR [delete]\fP"

.SS "~\fBReader\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "uint64_t LastRecordOffset ()"

.SS "\fBReader\fP & operator= (const \fBReader\fP & )\fR [delete]\fP"

.SS "bool ReadRecord (\fBSlice\fP * record, std::string * scratch)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
