.TH "LinTrans< I, N >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinTrans< I, N >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lintrans\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinTrans\fP ()=default"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (I a, I b)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (I a, I b, I c)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (I a, I b, I c, I d)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (I a, I b, I c, I d, I e)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (I a, I b, I c, I d, I e, I f)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (I a, I b, I c, I d, I e, I f, I g)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (I a, I b, I c, I d, I e, I f, I g, I h)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (const I *p, \fBNum\fP< 2 >)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (const I *p, \fBNum\fP< 3 >)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (const I *p, \fBNum\fP< 4 >)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (const I *p, \fBNum\fP< 5 >)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (const I *p, \fBNum\fP< 6 >)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (const I *p, \fBNum\fP< 7 >)"
.br
.ti -1c
.RI "constexpr \fBLinTrans\fP (const I *p, \fBNum\fP< 8 >)"
.br
.ti -1c
.RI "template<I(*)(const I &) F> I \fBBuild\fP (\fBNum\fP< 1 >, I a)"
.br
.ti -1c
.RI "template<I(*)(const I &) F> I \fBBuild\fP (\fBNum\fP< 2 >, I a)"
.br
.ti -1c
.RI "template<I(*)(const I &) F> I \fBBuild\fP (\fBNum\fP< 3 >, I a)"
.br
.ti -1c
.RI "template<I(*)(const I &) F> I \fBBuild\fP (\fBNum\fP< 4 >, I a)"
.br
.ti -1c
.RI "template<I(*)(const I &) F> I \fBBuild\fP (\fBNum\fP< 5 >, I a)"
.br
.ti -1c
.RI "template<I(*)(const I &) F> I \fBBuild\fP (\fBNum\fP< 6 >, I a)"
.br
.ti -1c
.RI "template<typename O, int P> I constexpr \fBMap\fP (I a) const"
.br
.ti -1c
.RI "template<typename O, int P> I constexpr \fBTopMap\fP (I a) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename I, int N>
.br
class LinTrans< I, N >"A Linear N-bit transformation over the field I\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename I, int N> \fBLinTrans\fP ()\fR [default]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (I a, I b)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (I a, I b, I c)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (I a, I b, I c, I d)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (I a, I b, I c, I d, I e)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (I a, I b, I c, I d, I e, I f)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (I a, I b, I c, I d, I e, I f, I g)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (I a, I b, I c, I d, I e, I f, I g, I h)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (const I * p, \fBNum\fP< 2 > )\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (const I * p, \fBNum\fP< 3 > )\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (const I * p, \fBNum\fP< 4 > )\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (const I * p, \fBNum\fP< 5 > )\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (const I * p, \fBNum\fP< 6 > )\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (const I * p, \fBNum\fP< 7 > )\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBLinTrans\fP (const I * p, \fBNum\fP< 8 > )\fR [inline]\fP, \fR [constexpr]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename I, int N> template<I(*)(const I &) F> I Build (\fBNum\fP< 1 > , I a)\fR [inline]\fP"

.SS "template<typename I, int N> template<I(*)(const I &) F> I Build (\fBNum\fP< 2 > , I a)\fR [inline]\fP"

.SS "template<typename I, int N> template<I(*)(const I &) F> I Build (\fBNum\fP< 3 > , I a)\fR [inline]\fP"

.SS "template<typename I, int N> template<I(*)(const I &) F> I Build (\fBNum\fP< 4 > , I a)\fR [inline]\fP"

.SS "template<typename I, int N> template<I(*)(const I &) F> I Build (\fBNum\fP< 5 > , I a)\fR [inline]\fP"

.SS "template<typename I, int N> template<I(*)(const I &) F> I Build (\fBNum\fP< 6 > , I a)\fR [inline]\fP"

.SS "template<typename I, int N> template<typename O, int P> I constexpr Map (I a) const\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> template<typename O, int P> I constexpr TopMap (I a) const\fR [inline]\fP, \fR [constexpr]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
