.TH "src/wallet/load.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/load.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <wallet/load\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <interfaces/chain\&.h>\fP
.br
\fR#include <scheduler\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <wallet/context\&.h>\fP
.br
\fR#include <wallet/spend\&.h>\fP
.br
\fR#include <wallet/wallet\&.h>\fP
.br
\fR#include <wallet/walletdb\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <system_error>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBVerifyWallets\fP (\fBWalletContext\fP &context)"
.br
.RI "Responsible for reading and validating the -wallet arguments and verifying the wallet database\&. "
.ti -1c
.RI "bool \fBLoadWallets\fP (\fBWalletContext\fP &context)"
.br
.RI "Load wallet databases\&. "
.ti -1c
.RI "void \fBStartWallets\fP (\fBWalletContext\fP &context)"
.br
.RI "Complete startup of wallets\&. "
.ti -1c
.RI "void \fBUnloadWallets\fP (\fBWalletContext\fP &context)"
.br
.ti -1c
.RI "template<typename C, typename \fBS\fP, typename UnaryOp> auto \fBJoin\fP (const C &container, const \fBS\fP &separator, UnaryOp unary_op)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename C, typename \fBS\fP, typename UnaryOp> auto Join (const C & container, const \fBS\fP & separator, UnaryOp unary_op)"
Join all container items\&. Typically used to concatenate strings but accepts containers with elements of any type\&.

.PP
\fBParameters\fP
.RS 4
\fIcontainer\fP The items to join 
.br
\fIseparator\fP The separator 
.br
\fIunary_op\fP Apply this operator to each item 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
