.TH "LockedPageAllocator" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LockedPageAllocator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lockedpool\&.h>\fP
.PP
Inherited by \fBPosixLockedPageAllocator\fP, and \fBTestLockedPageAllocator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~LockedPageAllocator\fP ()=default"
.br
.ti -1c
.RI "virtual void * \fBAllocateLocked\fP (size_t len, bool *lockingSuccess)=0"
.br
.ti -1c
.RI "virtual void \fBFreeLocked\fP (void *addr, size_t len)=0"
.br
.ti -1c
.RI "virtual size_t \fBGetLimit\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
OS-dependent allocation and deallocation of locked/pinned memory pages\&. Abstract base class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBLockedPageAllocator\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void * AllocateLocked (size_t len, bool * lockingSuccess)\fR [pure virtual]\fP"
Allocate and lock memory pages\&. If len is not a multiple of the system page size, it is rounded up\&. Returns nullptr in case of allocation failure\&.

.PP
If locking the memory pages could not be accomplished it will still return the memory, however the lockingSuccess flag will be false\&. lockingSuccess is undefined if the allocation fails\&. 
.PP
Implemented in \fBPosixLockedPageAllocator\fP, and \fBTestLockedPageAllocator\fP\&.
.SS "virtual void FreeLocked (void * addr, size_t len)\fR [pure virtual]\fP"
Unlock and free memory pages\&. Clear the memory before unlocking\&. 
.PP
Implemented in \fBPosixLockedPageAllocator\fP, and \fBTestLockedPageAllocator\fP\&.
.SS "virtual size_t GetLimit ()\fR [pure virtual]\fP"
Get the total limit on the amount of memory that may be locked by this process, in bytes\&. Return size_t max if there is no limit or the limit is unknown\&. Return 0 if no memory can be locked at all\&. 
.PP
Implemented in \fBPosixLockedPageAllocator\fP, and \fBTestLockedPageAllocator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
