.TH "LockedPoolManager" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LockedPoolManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lockedpool\&.h>\fP
.PP
Inherits \fBLockedPool\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLockedPoolManager\fP & \fBInstance\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBLockedPool\fP
.in +1c
.ti -1c
.RI "typedef bool(* \fBLockingFailed_Callback\fP) ()"
.br
.in -1c

Public Member Functions inherited from \fBLockedPool\fP
.in +1c
.ti -1c
.RI "\fBLockedPool\fP (std::unique_ptr< \fBLockedPageAllocator\fP > allocator, \fBLockingFailed_Callback\fP lf_cb_in=nullptr)"
.br
.ti -1c
.RI "\fB~LockedPool\fP ()"
.br
.ti -1c
.RI "\fBLockedPool\fP (const \fBLockedPool\fP &other)=delete"
.br
.ti -1c
.RI "\fBLockedPool\fP & \fBoperator=\fP (const \fBLockedPool\fP &)=delete"
.br
.ti -1c
.RI "void * \fBalloc\fP (size_t size)"
.br
.ti -1c
.RI "void \fBfree\fP (void *ptr)"
.br
.ti -1c
.RI "\fBStats\fP \fBstats\fP () const"
.br
.in -1c

Static Public Attributes inherited from \fBLockedPool\fP
.in +1c
.ti -1c
.RI "static const size_t \fBARENA_SIZE\fP = 256*1024"
.br
.ti -1c
.RI "static const size_t \fBARENA_ALIGN\fP = 16"
.br
.in -1c
.SH "Detailed Description"
.PP 
Singleton class to keep track of locked (ie, non-swappable) memory, for use in std::allocator templates\&.

.PP
Some implementations of the STL allocate memory in some constructors (i\&.e\&., see MSVC's vector<T> implementation where it allocates 1 byte of memory in the allocator\&.) Due to the unpredictable order of static initializers, we have to make sure the \fBLockedPoolManager\fP instance exists before any other STL-based objects that use \fBsecure_allocator\fP are created\&. So instead of having \fBLockedPoolManager\fP also be static-initialized, it is created on demand\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBLockedPoolManager\fP & Instance ()\fR [inline]\fP, \fR [static]\fP"
Return the current instance, or create it once 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
