.TH "src/leveldb/db/log_reader.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/db/log_reader.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include 'db/log_format\&.h'\fP
.br
\fR#include 'leveldb/slice\&.h'\fP
.br
\fR#include 'leveldb/status\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBReader\fP"
.br
.ti -1c
.RI "class \fBReader::Reporter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.ti -1c
.RI "namespace \fBleveldb::log\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
