.TH "src/leveldb/db/log_test.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/db/log_test.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'db/log_reader\&.h'\fP
.br
\fR#include 'db/log_writer\&.h'\fP
.br
\fR#include 'leveldb/env\&.h'\fP
.br
\fR#include 'util/coding\&.h'\fP
.br
\fR#include 'util/crc32c\&.h'\fP
.br
\fR#include 'util/random\&.h'\fP
.br
\fR#include 'util/testharness\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBLogTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.ti -1c
.RI "namespace \fBleveldb::log\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, Empty)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadWrite)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ManyBlocks)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, Fragmentation)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, MarginalTrailer)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, MarginalTrailer2)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ShortTrailer)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, AlignedEof)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, OpenForAppend)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, RandomRead)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadError)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, BadRecordType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, TruncatedTrailingRecordIsIgnored)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, BadLength)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, BadLengthAtEndIsIgnored)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ChecksumMismatch)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, UnexpectedMiddleType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, UnexpectedLastType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, UnexpectedFullType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, UnexpectedFirstType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, MissingLastIsIgnored)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, PartialLastIsIgnored)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, SkipIntoMultiRecord)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ErrorJoinsRecords)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadStart)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadSecondOneOff)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadSecondTenThousand)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadSecondStart)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadThirdOneOff)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadThirdStart)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadFourthOneOff)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadFourthFirstBlockTrailer)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadFourthMiddleBlock)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadFourthLastBlock)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadFourthStart)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadInitialOffsetIntoBlockPadding)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadEnd)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogTest\fP, ReadPastEnd)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
