.TH "src/test/util/logging.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/util/logging.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/util/logging\&.h>\fP
.br
\fR#include <noui\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
