.TH "src/leveldb/util/logging_test.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/util/logging_test.cc
.SH SYNOPSIS
.br
.PP
\fR#include <limits>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'leveldb/slice\&.h'\fP
.br
\fR#include 'util/logging\&.h'\fP
.br
\fR#include 'util/testharness\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBLogging\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBLogging\fP, \fBNumberToString\fP)"
.br
.ti -1c
.RI "void \fBConsumeDecimalNumberRoundtripTest\fP (uint64_t number, const std::string &padding='')"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogging\fP, ConsumeDecimalNumberRoundtrip)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogging\fP, ConsumeDecimalNumberRoundtripWithPadding)"
.br
.ti -1c
.RI "void \fBConsumeDecimalNumberOverflowTest\fP (const std::string &input_string)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogging\fP, ConsumeDecimalNumberOverflow)"
.br
.ti -1c
.RI "void \fBConsumeDecimalNumberNoDigitsTest\fP (const std::string &input_string)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBLogging\fP, ConsumeDecimalNumberNoDigits)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
