.TH "src/test/util/logging.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/util/logging.h
.SH SYNOPSIS
.br
.PP
\fR#include <util/macros\&.h>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <list>\fP
.br
\fR#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDebugLogHelper\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBASSERT_DEBUG_LOG\fP(message)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASSERT_DEBUG_LOG( message)"
\fBValue:\fP
.nf
DebugLogHelper UNIQUE_NAME(debugloghelper)(message)
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
