.TH "LogSetup" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogSetup
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBasicTestingSetup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogSetup\fP ()"
.br
.ti -1c
.RI "\fB~LogSetup\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "void \fBSeedRandomForTest\fP (\fBSeedRand\fP seed)"
.br
.ti -1c
.RI "\fBBasicTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~BasicTestingSetup\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfs::path\fP \fBprev_log_path\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBtmp_log_path\fP"
.br
.ti -1c
.RI "bool \fBprev_reopen_file\fP"
.br
.ti -1c
.RI "bool \fBprev_print_to_file\fP"
.br
.ti -1c
.RI "bool \fBprev_log_timestamps\fP"
.br
.ti -1c
.RI "bool \fBprev_log_threadnames\fP"
.br
.ti -1c
.RI "bool \fBprev_log_sourcelocations\fP"
.br
.ti -1c
.RI "std::unordered_map< \fBBCLog::LogFlags\fP, \fBBCLog::Level\fP > \fBprev_category_levels\fP"
.br
.ti -1c
.RI "\fBBCLog::Level\fP \fBprev_log_level\fP"
.br
.ti -1c
.RI "\fBBCLog::CategoryMask\fP \fBprev_category_mask\fP"
.br
.in -1c

Data Fields inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "\fButil::SignalInterrupt\fP \fBm_interrupt\fP"
.br
.ti -1c
.RI "\fBnode::NodeContext\fP \fBm_node\fP"
.br
.ti -1c
.RI "\fBFastRandomContext\fP \fBm_rng\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_root\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_lock\fP"
.br
.ti -1c
.RI "bool \fBm_has_custom_datadir\fP {false}"
.br
.ti -1c
.RI "\fBArgsManager\fP \fBm_args\fP"
.br
.RI "Test-specific arguments and settings\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLogSetup\fP ()\fR [inline]\fP"

.SS "~\fBLogSetup\fP ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::unordered_map<\fBBCLog::LogFlags\fP, \fBBCLog::Level\fP> prev_category_levels"

.SS "\fBBCLog::CategoryMask\fP prev_category_mask"

.SS "\fBBCLog::Level\fP prev_log_level"

.SS "\fBfs::path\fP prev_log_path"

.SS "bool prev_log_sourcelocations"

.SS "bool prev_log_threadnames"

.SS "bool prev_log_timestamps"

.SS "bool prev_print_to_file"

.SS "bool prev_reopen_file"

.SS "\fBfs::path\fP tmp_log_path"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
