.TH "MacDockIconHandler" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MacDockIconHandler
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <macdockiconhandler\&.h>\fP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdockIconClicked\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMacDockIconHandler\fP * \fBinstance\fP ()"
.br
.ti -1c
.RI "static void \fBcleanup\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
macOS-specific Dock icon handler\&. 
.SH "Member Function Documentation"
.PP 
.SS "void cleanup ()\fR [static]\fP"

.SS "void dockIconClicked ()\fR [signal]\fP"

.SS "\fBMacDockIconHandler\fP * instance ()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
