.TH "src/qt/macnotificationhandler.mm" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/macnotificationhandler.mm
.SH SYNOPSIS
.br
.PP
\fR#include 'macnotificationhandler\&.h'\fP
.br
\fRimport <objc/runtime\&.h>\fP
.br
\fR#include <Cocoa/Cocoa\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
