.TH "src/qt/macos_appnap.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/macos_appnap.h
.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCAppNapInhibitor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
