.TH "md_src_2ipc_2libmultiprocess_2doc_2install" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_src_2ipc_2libmultiprocess_2doc_2install \- libmultiprocess Installation 
.PP


.PP
Installation currently requires Cap'n Proto 0\&.7 or higher:

.PP
.PP
.nf
apt install libcapnp\-dev capnproto
brew install capnp cmake
dnf install capnproto
.fi
.PP

.PP
Installation steps are:

.PP
.PP
.nf
mkdir build
cd build
cmake \&.\&.
make
make check # Optionally build and run tests
make install
.fi
.PP

.PP
To build with libmultiprocess in a CMake project can specify:

.PP
.PP
.nf
find_package(Libmultiprocess)
target_capnp_sources(mytarget ${CMAKE_CURRENT_SOURCE_DIR} myschema\&.capnp)
.fi
.PP

.PP
Which will locate the libmultiprocess cmake package, and call the \fRtarget_capnp_sources\fP function to generate C++ files and link them into a library or executable target\&. See \fRexample/CMakeLists\&.txt\fP for a complete example\&.

.PP
To build with libmultiprocess in a non-CMake project can use installed \fR<\fBprefix\fP>/include/mpgen\&.mk\fP Makefile rule to generate C++ files, and \fR<\fBprefix\fP>/lib/pkgconfig/libmultiprocess\&.pc\fP pkg-config definition to link against the runtime library\&.

.PP
For cross-compilation, it may be useful to build the runtime library and code generation binaries separately, which can be done with:

.PP
.PP
.nf
make install\-bin # install bin/mpgen and related files
make install\-lib # install lib/libmultiprocess\&.a and related files
.fi
.PP

.PP
It is also possible to import CMake targets separately with:

.PP
.PP
.nf
find_package(Libmultiprocess COMPONENTS Bin)
find_package(Libmultiprocess COMPONENTS Lib)
.fi
.PP
 
