.TH "md_src_2crc32c_2_c_o_n_t_r_i_b_u_t_i_n_g" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_src_2crc32c_2_c_o_n_t_r_i_b_u_t_i_n_g \- How to Contribute 
.PP


.PP
We'd love to accept your patches and contributions to this project\&. There are just a few small guidelines you need to follow\&.
.SH "Contributor License Agreement"
.PP
Contributions to this project must be accompanied by a Contributor License Agreement\&. You (or your employer) retain the copyright to your contribution, this simply gives us permission to use and redistribute your contributions as part of the project\&. Head over to https://cla.developers.google.com/ to see your current agreements on file or to sign a new one\&.

.PP
You generally only need to submit a CLA once, so if you've already submitted one (even if it was for a different project), you probably don't need to do it again\&.
.SH "Code reviews"
.PP
All submissions, including submissions by project members, require review\&. We use GitHub pull requests for this purpose\&. Consult \fRGitHub Help\fP for more information on using pull requests\&. 
