.TH "src/kernel/mempool_removal_reason.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kernel/mempool_removal_reason.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBMemPoolRemovalReason\fP { \fBEXPIRY\fP, \fBSIZELIMIT\fP, \fBREORG\fP, \fBBLOCK\fP, \fBCONFLICT\fP, \fBREPLACED\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBRemovalReasonToString\fP (const \fBMemPoolRemovalReason\fP &r) noexcept"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBMemPoolRemovalReason\fP\fR [strong]\fP"
Reason why a transaction was removed from the mempool, this is passed to the notification signal\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIEXPIRY \fP
Expired from mempool\&. 
.TP
\f(BISIZELIMIT \fP
Removed in size limiting\&. 
.TP
\f(BIREORG \fP
Removed for reorganization\&. 
.TP
\f(BIBLOCK \fP
Removed for block\&. 
.TP
\f(BICONFLICT \fP
Removed for conflict with in-block transaction\&. 
.TP
\f(BIREPLACED \fP
Removed for replacement\&. 
.SH "Function Documentation"
.PP 
.SS "std::string RemovalReasonToString (const \fBMemPoolRemovalReason\fP & r)\fR [noexcept]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
