.TH "src/bench/mempool_eviction.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bench/mempool_eviction.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bench/bench\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <kernel/cs_main\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <test/util/txmempool\&.h>\fP
.br
\fR#include <txmempool\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTryAddToMempool\fP (pool, \fBCTxMemPoolEntry\fP(\fBTxGraph::Ref\fP(), tx, nFee, nTime, \fBnHeight\fP, \fBsequence\fP, \fBspendsCoinbase\fP, \fBsigOpCost\fP, \fBlp\fP))"
.br
.ti -1c
.RI "\fBBENCHMARK\fP (MempoolEviction, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static void pool \fBcs\fP"
.br
.ti -1c
.RI "unsigned int \fBnHeight\fP = 1"
.br
.ti -1c
.RI "uint64_t \fBsequence\fP = 0"
.br
.ti -1c
.RI "bool \fBspendsCoinbase\fP = false"
.br
.ti -1c
.RI "unsigned int \fBsigOpCost\fP = 4"
.br
.ti -1c
.RI "\fBLockPoints\fP \fBlp\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BENCHMARK (MempoolEviction , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SS "TryAddToMempool (pool , \fBCTxMemPoolEntry\fP(\fBTxGraph::Ref\fP(), tx, nFee, nTime, \fBnHeight\fP, \fBsequence\fP, \fBspendsCoinbase\fP, \fBsigOpCost\fP, \fBlp\fP) )"

.SH "Variable Documentation"
.PP 
.SS "void pool cs"
\fBInitial value:\fP
.nf
{
    int64_t nTime = 0
.PP
.fi

.SS "\fBLockPoints\fP lp"

.SS "unsigned int nHeight = 1"

.SS "uint64_t sequence = 0"

.SS "unsigned int sigOpCost = 4"

.SS "bool spendsCoinbase = false"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
