.TH "src/node/mempool_args.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/mempool_args.h
.SH SYNOPSIS
.br
.PP
\fR#include <util/result\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBkernel\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fButil::Result\fP< void > \fBApplyArgsManOptions\fP (const \fBArgsManager\fP &argsman, const \fBCChainParams\fP &chainparams, \fBkernel::MemPoolOptions\fP &mempool_opts)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fButil::Result\fP< void > ApplyArgsManOptions (const \fBArgsManager\fP & argsman, const \fBCChainParams\fP & chainparams, \fBkernel::MemPoolOptions\fP & mempool_opts)\fR [nodiscard]\fP"
Overlay the options set in \fRargsman\fP on top of corresponding members in \fRmempool_opts\fP\&. Returns an error if one was encountered\&.

.PP
\fBParameters\fP
.RS 4
\fIargsman\fP The \fBArgsManager\fP in which to check set options\&. 
.br
\fImempool_opts\fP The \fBMemPoolOptions\fP to modify according to \fRargsman\fP\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
