.TH "src/kernel/mempool_entry.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kernel/mempool_entry.h
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <core_memusage\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <policy/settings\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <txgraph\&.h>\fP
.br
\fR#include <util/epochguard\&.h>\fP
.br
\fR#include <util/overflow\&.h>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <set>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBLockPoints\fP"
.br
.ti -1c
.RI "struct \fBCompareIteratorByHash\fP"
.br
.ti -1c
.RI "class \fBCTxMemPoolEntry\fP"
.br
.ti -1c
.RI "struct \fBTransactionInfo\fP"
.br
.ti -1c
.RI "struct \fBRemovedMempoolTransactionInfo\fP"
.br
.ti -1c
.RI "struct \fBNewMempoolTransactionInfo\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBCTxMemPoolEntryRef\fP = \fBCTxMemPoolEntry::CTxMemPoolEntryRef\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBCTxMemPoolEntryRef\fP = \fBCTxMemPoolEntry::CTxMemPoolEntryRef\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
