.TH "src/node/mempool_args.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/mempool_args.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/mempool_args\&.h>\fP
.br
\fR#include <kernel/mempool_limits\&.h>\fP
.br
\fR#include <kernel/mempool_options\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <common/messages\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <kernel/chainparams\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <policy/feerate\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <txgraph\&.h>\fP
.br
\fR#include <util/moneystr\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <memory>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBMemPoolLimits\fP"
.br
.ti -1c
.RI "struct \fBMemPoolOptions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fButil::Result\fP< void > \fBApplyArgsManOptions\fP (const \fBArgsManager\fP &argsman, const \fBCChainParams\fP &chainparams, \fBMemPoolOptions\fP &mempool_opts)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBAmountErrMsg\fP (const std::string &optname, const std::string &strValue)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBbilingual_str\fP AmountErrMsg (const std::string & optname, const std::string & strValue)"

.SS "\fButil::Result\fP< void > ApplyArgsManOptions (const \fBArgsManager\fP & argsman, const \fBCChainParams\fP & chainparams, \fBkernel::MemPoolOptions\fP & mempool_opts)\fR [nodiscard]\fP"
Overlay the options set in \fRargsman\fP on top of corresponding members in \fRmempool_opts\fP\&. Returns an error if one was encountered\&.

.PP
\fBParameters\fP
.RS 4
\fIargsman\fP The \fBArgsManager\fP in which to check set options\&. 
.br
\fImempool_opts\fP The \fBMemPoolOptions\fP to modify according to \fRargsman\fP\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
