.TH "src/leveldb/table/merger.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/table/merger.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'table/merger\&.h'\fP
.br
\fR#include 'leveldb/comparator\&.h'\fP
.br
\fR#include 'leveldb/iterator\&.h'\fP
.br
\fR#include 'table/iterator_wrapper\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP * \fBNewMergingIterator\fP (const \fBComparator\fP *comparator, \fBIterator\fP **children, int n)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
