.TH "src/merkleblock.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/merkleblock.h
.SH SYNOPSIS
.br
.PP
\fR#include <common/bloom\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <primitives/transaction_identifier\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <set>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCPartialMerkleTree\fP"
.br
.ti -1c
.RI "class \fBCMerkleBlock\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< unsigned char > \fBBitsToBytes\fP (const std::vector< bool > &bits)"
.br
.ti -1c
.RI "std::vector< bool > \fBBytesToBits\fP (const std::vector< unsigned char > &bytes)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::vector< unsigned char > BitsToBytes (const std::vector< bool > & bits)"

.SS "std::vector< bool > BytesToBits (const std::vector< unsigned char > & bytes)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
