.TH "src/common/messages.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/common/messages.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnode\fP"
.br
.ti -1c
.RI "namespace \fBcommon\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBFeeModeFromString\fP (std::string_view mode_string, \fBFeeEstimateMode\fP &fee_estimate_mode)"
.br
.ti -1c
.RI "std::string \fBStringForFeeReason\fP (\fBFeeReason\fP reason)"
.br
.ti -1c
.RI "std::string \fBFeeModes\fP (const std::string &delimiter)"
.br
.ti -1c
.RI "std::string \fBFeeModeInfo\fP (std::pair< std::string, \fBFeeEstimateMode\fP > &mode)"
.br
.ti -1c
.RI "std::string \fBFeeModesDetail\fP (std::string default_info)"
.br
.ti -1c
.RI "std::string \fBInvalidEstimateModeErrorMessage\fP ()"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBPSBTErrorString\fP (\fBPSBTError\fP err)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBTransactionErrorString\fP (const \fBTransactionError\fP err)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBResolveErrMsg\fP (const std::string &optname, const std::string &strBind)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBInvalidPortErrMsg\fP (const std::string &optname, const std::string &invalid_value)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBAmountHighWarn\fP (const std::string &optname)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBAmountErrMsg\fP (const std::string &optname, const std::string &strValue)"
.br
.in -1c
.SH "Detailed Description"
.PP 
is a home for simple string functions returning descriptive messages that are used in RPC and GUI interfaces or log messages, and are called in different parts of the codebase across node/wallet/gui boundaries\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
