.TH "src/common/messages.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/common/messages.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/messages\&.h>\fP
.br
\fR#include <common/types\&.h>\fP
.br
\fR#include <policy/fees/block_policy_estimator\&.h>\fP
.br
\fR#include <node/types\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <map>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcommon\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBTransactionError\fP "
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBStringForFeeReason\fP (\fBFeeReason\fP reason)"
.br
.ti -1c
.RI "const std::vector< std::pair< std::string, \fBFeeEstimateMode\fP > > & \fBFeeModeMap\fP ()"
.br
.ti -1c
.RI "std::string \fBFeeModeInfo\fP (const std::pair< std::string, \fBFeeEstimateMode\fP > &mode, std::string &default_info)"
.br
.ti -1c
.RI "std::string \fBFeeModesDetail\fP (std::string default_info)"
.br
.ti -1c
.RI "std::string \fBFeeModes\fP (const std::string &delimiter)"
.br
.ti -1c
.RI "std::string \fBInvalidEstimateModeErrorMessage\fP ()"
.br
.ti -1c
.RI "bool \fBFeeModeFromString\fP (std::string_view mode_string, \fBFeeEstimateMode\fP &fee_estimate_mode)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBPSBTErrorString\fP (\fBPSBTError\fP err)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBTransactionErrorString\fP (const \fBTransactionError\fP err)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBResolveErrMsg\fP (const std::string &optname, const std::string &strBind)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBInvalidPortErrMsg\fP (const std::string &optname, const std::string &invalid_value)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBAmountHighWarn\fP (const std::string &optname)"
.br
.ti -1c
.RI "\fBbilingual_str\fP \fBAmountErrMsg\fP (const std::string &optname, const std::string &strValue)"
.br
.ti -1c
.RI "template<typename C, typename \fBS\fP, typename UnaryOp> auto \fBJoin\fP (const C &container, const \fBS\fP &separator, UnaryOp unary_op)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBTransactionError\fP\fR [strong]\fP"

.SH "Function Documentation"
.PP 
.SS "template<typename C, typename \fBS\fP, typename UnaryOp> auto Join (const C & container, const \fBS\fP & separator, UnaryOp unary_op)"
Join all container items\&. Typically used to concatenate strings but accepts containers with elements of any type\&.

.PP
\fBParameters\fP
.RS 4
\fIcontainer\fP The items to join 
.br
\fIseparator\fP The separator 
.br
\fIunary_op\fP Apply this operator to each item 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
