.TH "src/wallet/migrate.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/migrate.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <compat/byteswap\&.h>\fP
.br
\fR#include <crypto/common\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <wallet/migrate\&.h>\fP
.br
\fR#include <array>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <variant>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMetaPage\fP"
.br
.ti -1c
.RI "class \fBRecordHeader\fP"
.br
.ti -1c
.RI "class \fBDataRecord\fP"
.br
.ti -1c
.RI "class \fBInternalRecord\fP"
.br
.ti -1c
.RI "class \fBOverflowRecord\fP"
.br
.ti -1c
.RI "class \fBPageHeader\fP"
.br
.ti -1c
.RI "class \fBRecordsPage\fP"
.br
.ti -1c
.RI "class \fBOverflowPage\fP"
.br
.ti -1c
.RI "class \fBInternalPage\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBPageType\fP : uint8_t { \fBBTREE_INTERNAL\fP = 3, \fBBTREE_LEAF\fP = 5, \fBOVERFLOW_DATA\fP = 7, \fBBTREE_META\fP = 9 }"
.br
.ti -1c
.RI "enum class \fBRecordType\fP : uint8_t { \fBKEYDATA\fP = 1, \fBOVERFLOW_DATA\fP = 3, \fBDELETE\fP = 0x80 }"
.br
.ti -1c
.RI "enum class \fBBTreeFlags\fP : uint32_t { \fBSUBDB\fP = 0x20 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBBerkeleyRODatabase\fP > \fBMakeBerkeleyRODatabase\fP (const \fBfs::path\fP &path, const \fBDatabaseOptions\fP &options, \fBDatabaseStatus\fP &status, \fBbilingual_str\fP &error)"
.br
.RI "Return object giving access to Berkeley Read Only database at specified path\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr uint32_t \fBBTREE_MAGIC\fP = 0x00053162"
.br
.ti -1c
.RI "constexpr uint32_t \fBBTREE_MAGIC_OE\fP = 0x62310500"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
