.TH "src/test/miner_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/miner_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <addresstype\&.h>\fP
.br
\fR#include <coins\&.h>\fP
.br
\fR#include <common/system\&.h>\fP
.br
\fR#include <consensus/consensus\&.h>\fP
.br
\fR#include <consensus/merkle\&.h>\fP
.br
\fR#include <consensus/tx_verify\&.h>\fP
.br
\fR#include <interfaces/mining\&.h>\fP
.br
\fR#include <node/miner\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/transaction_utils\&.h>\fP
.br
\fR#include <test/util/txmempool\&.h>\fP
.br
\fR#include <txmempool\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/feefrac\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <versionbits\&.h>\fP
.br
\fR#include <pow\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBMinerTestingSetup\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBminer_tests\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< \fBCTransactionRef\fP > \fBCreateBigSigOpsCluster\fP (const \fBCTransactionRef\fP &first_tx)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (CreateNewBlock_validity)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (CreateNewBlock_validity )"
Simple block creation, nothing special yet\&. If current_height is odd, block_template will have already been set at the end of the previous loop\&.
.SS "std::vector< \fBCTransactionRef\fP > CreateBigSigOpsCluster (const \fBCTransactionRef\fP & first_tx)"

.SH "Variable Documentation"
.PP 
.SS "unsigned int extranonce"

.SS "unsigned int nonce"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
