.TH "src/test/minisketch_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/minisketch_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <minisketch\&.h>\fP
.br
\fR#include <node/minisketchwrapper\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <utility>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (minisketch_test)"
.br
.ti -1c
.RI "Minisketch \fBMakeMinisketch32\fP (size_t capacity)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (minisketch_test )"

.SS "Minisketch MakeMinisketch32 (size_t capacity)"
\fBWrapper\fP around Minisketch::Minisketch(32, implementation, capacity)\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
