.TH "src/node/mini_miner.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/mini_miner.h
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <map>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <set>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMiniMinerMempoolEntry\fP"
.br
.ti -1c
.RI "struct \fBIteratorComparator\fP"
.br
.ti -1c
.RI "class \fBMiniMiner\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnode\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
