.TH "WitnessSize" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WitnessSize
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <miniscript\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWitnessSize\fP (\fBMaxInt\fP< uint32_t > in_sat, \fBMaxInt\fP< uint32_t > in_dsat)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMaxInt\fP< uint32_t > \fBsat\fP"
.br
.RI "Maximum witness size to satisfy;\&. "
.ti -1c
.RI "\fBMaxInt\fP< uint32_t > \fBdsat\fP"
.br
.RI "Maximum witness size to dissatisfy;\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WitnessSize (\fBMaxInt\fP< uint32_t > in_sat, \fBMaxInt\fP< uint32_t > in_dsat)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBMaxInt\fP<uint32_t> dsat"

.PP
Maximum witness size to dissatisfy;\&. 
.SS "\fBMaxInt\fP<uint32_t> sat"

.PP
Maximum witness size to satisfy;\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
