.TH "InputStack" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputStack \- An object representing a sequence of witness stack elements\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <miniscript\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputStack\fP ()=default"
.br
.RI "Construct an empty stack (valid)\&. "
.ti -1c
.RI "\fBInputStack\fP (std::vector< unsigned char > in)"
.br
.RI "Construct a valid single-element stack (with an element up to 75 bytes)\&. "
.ti -1c
.RI "\fBInputStack\fP & \fBSetAvailable\fP (\fBAvailability\fP avail)"
.br
.RI "Change availability\&. "
.ti -1c
.RI "\fBInputStack\fP & \fBSetWithSig\fP ()"
.br
.RI "Mark this input stack as having a signature\&. "
.ti -1c
.RI "\fBInputStack\fP & \fBSetNonCanon\fP ()"
.br
.RI "Mark this input stack as non-canonical (known to not be necessary in non-malleable satisfactions)\&. "
.ti -1c
.RI "\fBInputStack\fP & \fBSetMalleable\fP (bool x=true)"
.br
.RI "Mark this input stack as malleable\&. "
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBAvailability\fP \fBavailable\fP = \fBAvailability::YES\fP"
.br
.ti -1c
.RI "bool \fBhas_sig\fP = false"
.br
.RI "Whether this stack contains a digital signature\&. "
.ti -1c
.RI "bool \fBmalleable\fP = false"
.br
.RI "Whether this stack is malleable (can be turned into an equally valid other stack by a third party)\&. "
.ti -1c
.RI "bool \fBnon_canon\fP = false"
.br
.ti -1c
.RI "size_t \fBsize\fP = 0"
.br
.RI "Serialized witness size\&. "
.ti -1c
.RI "std::vector< std::vector< unsigned char > > \fBstack\fP"
.br
.RI "Data elements\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBInputStack\fP \fBoperator+\fP (\fBInputStack\fP a, \fBInputStack\fP b)"
.br
.RI "Concatenate two input stacks\&. "
.ti -1c
.RI "\fBInputStack\fP \fBoperator|\fP (\fBInputStack\fP a, \fBInputStack\fP b)"
.br
.RI "Choose between two potential input stacks\&. "
.in -1c
.SH "Detailed Description"
.PP 
An object representing a sequence of witness stack elements\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InputStack ()\fR [default]\fP"

.PP
Construct an empty stack (valid)\&. 
.SS "InputStack (std::vector< unsigned char > in)\fR [inline]\fP"

.PP
Construct a valid single-element stack (with an element up to 75 bytes)\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBInputStack\fP & SetAvailable (\fBAvailability\fP avail)"

.PP
Change availability\&. 
.SS "\fBInputStack\fP & SetMalleable (bool x = \fRtrue\fP)"

.PP
Mark this input stack as malleable\&. 
.SS "\fBInputStack\fP & SetNonCanon ()"

.PP
Mark this input stack as non-canonical (known to not be necessary in non-malleable satisfactions)\&. 
.SS "\fBInputStack\fP & SetWithSig ()"

.PP
Mark this input stack as having a signature\&. 
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBInputStack\fP operator+ (\fBInputStack\fP a, \fBInputStack\fP b)\fR [friend]\fP"

.PP
Concatenate two input stacks\&. 
.SS "\fBInputStack\fP operator| (\fBInputStack\fP a, \fBInputStack\fP b)\fR [friend]\fP"

.PP
Choose between two potential input stacks\&. 
.SH "Field Documentation"
.PP 
.SS "\fBAvailability\fP available = \fBAvailability::YES\fP"
Whether this stack is valid for its intended purpose (satisfaction or dissatisfaction of a \fBNode\fP)\&. The MAYBE value is used for size estimation, when keys/preimages may actually be unavailable, but may be available at signing time\&. This makes the \fBInputStack\fP structure and signing logic, filled with dummy signatures/preimages usable for witness size estimation\&. 
.SS "bool has_sig = false"

.PP
Whether this stack contains a digital signature\&. 
.SS "bool malleable = false"

.PP
Whether this stack is malleable (can be turned into an equally valid other stack by a third party)\&. 
.SS "bool non_canon = false"
Whether this stack is non-canonical (using a construction known to be unnecessary for satisfaction)\&. Note that this flag does not affect the satisfaction algorithm; it is only used for sanity checking\&. 
.SS "size_t size = 0"

.PP
Serialized witness size\&. 
.SS "std::vector<std::vector<unsigned char> > stack"

.PP
Data elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
