.TH "src/test/miniscript_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/miniscript_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <addresstype\&.h>\fP
.br
\fR#include <core_io\&.h>\fP
.br
\fR#include <hash\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <crypto/ripemd160\&.h>\fP
.br
\fR#include <crypto/sha256\&.h>\fP
.br
\fR#include <script/interpreter\&.h>\fP
.br
\fR#include <script/miniscript\&.h>\fP
.br
\fR#include <script/script_error\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (fixed_tests)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (fixed_tests )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
