.TH "MockedDescriptorConverter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MockedDescriptorConverter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <descriptor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIdIsCompPubKey\fP (uint8_t idx) const"
.br
.ti -1c
.RI "bool \fBIdIsUnCompPubKey\fP (uint8_t idx) const"
.br
.ti -1c
.RI "bool \fBIdIsXOnlyPubKey\fP (uint8_t idx) const"
.br
.ti -1c
.RI "bool \fBIdIsConstPrivKey\fP (uint8_t idx) const"
.br
.ti -1c
.RI "bool \fBIdIsXpub\fP (uint8_t idx) const"
.br
.ti -1c
.RI "bool \fBIdIsXprv\fP (uint8_t idx) const"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.RI "When initializing the target, populate the list of keys\&. "
.ti -1c
.RI "std::optional< uint8_t > \fBIdxFromHex\fP (std::string_view hex_characters) const"
.br
.RI "Parse an id in the keys vectors from a 2-characters hex string\&. "
.ti -1c
.RI "std::optional< std::string > \fBGetDescriptor\fP (std::string_view mocked_desc) const"
.br
.RI "Get an actual descriptor string from a descriptor string whose keys were mocked\&. "
.in -1c
.SH "Detailed Description"
.PP 
Converts a mocked descriptor string to a valid one\&. Every key in a mocked descriptor key is represented by 2 hex characters preceded by the '' character\&. We parse the two hex characters as an index in a list of pre-generated keys\&. This list contains keys of the various types accepted in descriptor keys expressions\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::optional< std::string > GetDescriptor (std::string_view mocked_desc) const"

.PP
Get an actual descriptor string from a descriptor string whose keys were mocked\&. 
.SS "bool IdIsCompPubKey (uint8_t idx) const\fR [inline]\fP"

.SS "bool IdIsConstPrivKey (uint8_t idx) const\fR [inline]\fP"

.SS "bool IdIsUnCompPubKey (uint8_t idx) const\fR [inline]\fP"

.SS "bool IdIsXOnlyPubKey (uint8_t idx) const\fR [inline]\fP"

.SS "bool IdIsXprv (uint8_t idx) const\fR [inline]\fP"

.SS "bool IdIsXpub (uint8_t idx) const\fR [inline]\fP"

.SS "std::optional< uint8_t > IdxFromHex (std::string_view hex_characters) const"

.PP
Parse an id in the keys vectors from a 2-characters hex string\&. 
.SS "void \fBInit\fP ()"

.PP
When initializing the target, populate the list of keys\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
