.TH "ModalOverlay" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModalOverlay
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <modaloverlay\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBtoggleVisibility\fP ()"
.br
.ti -1c
.RI "void \fBcloseClicked\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBtriggered\fP (bool hidden)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModalOverlay\fP (bool enable_wallet, QWidget *parent)"
.br
.ti -1c
.RI "\fB~ModalOverlay\fP ()"
.br
.ti -1c
.RI "void \fBtipUpdate\fP (int count, const QDateTime &blockDate, double nVerificationProgress)"
.br
.ti -1c
.RI "void \fBsetKnownBestHeight\fP (int count, const QDateTime &blockDate, bool presync)"
.br
.ti -1c
.RI "void \fBshowHide\fP (bool hide=false, bool userRequested=false)"
.br
.ti -1c
.RI "bool \fBisLayerVisible\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *obj, QEvent *ev) override"
.br
.ti -1c
.RI "bool \fBevent\fP (QEvent *ev) override"
.br
.RI "Tracks parent widget changes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Modal overlay to display information about the chain-sync state 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBModalOverlay\fP (bool enable_wallet, QWidget * parent)\fR [explicit]\fP"

.SS "~\fBModalOverlay\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void closeClicked ()\fR [slot]\fP"

.SS "bool event (QEvent * ev)\fR [override]\fP, \fR [protected]\fP"

.PP
Tracks parent widget changes\&. 
.SS "bool eventFilter (QObject * obj, QEvent * ev)\fR [override]\fP, \fR [protected]\fP"

.SS "bool isLayerVisible () const\fR [inline]\fP"

.SS "void setKnownBestHeight (int count, const QDateTime & blockDate, bool presync)"

.SS "void showHide (bool hide = \fRfalse\fP, bool userRequested = \fRfalse\fP)"

.SS "void tipUpdate (int count, const QDateTime & blockDate, double nVerificationProgress)"

.SS "void toggleVisibility ()\fR [slot]\fP"

.SS "void triggered (bool hidden)\fR [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
