.TH "src/secp256k1/src/modinv32.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/modinv32.h
.SH SYNOPSIS
.br
.PP
\fR#include 'util\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsecp256k1_modinv32_signed30\fP"
.br
.ti -1c
.RI "struct \fBsecp256k1_modinv32_modinfo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
