.TH "src/util/moneystr.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/moneystr.h
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBFormatMoney\fP (const \fBCAmount\fP n)"
.br
.ti -1c
.RI "std::optional< \fBCAmount\fP > \fBParseMoney\fP (const std::string &str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string FormatMoney (const \fBCAmount\fP n)"
Money parsing/formatting utilities\&. 
.SS "std::optional< \fBCAmount\fP > ParseMoney (const std::string & str)"
Parse an amount denoted in full coins\&. E\&.g\&. "0\&.0034" supplied on the command line\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
