.TH "src/util/moneystr.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/moneystr.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <util/moneystr\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <optional>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBFormatMoney\fP (const \fBCAmount\fP n)"
.br
.ti -1c
.RI "std::optional< \fBCAmount\fP > \fBParseMoney\fP (const std::string &money_string)"
.br
.ti -1c
.RI "bool \fBContainsNoNUL\fP (std::string_view str) noexcept"
.br
.ti -1c
.RI "std::string \fBTrimString\fP (std::string_view str, std::string_view pattern=' \\f\\n\\r\\t\\v')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool ContainsNoNUL (std::string_view str)\fR [inline]\fP, \fR [nodiscard]\fP, \fR [noexcept]\fP"
Check if a string does not contain any embedded NUL (\\0) characters 
.SS "std::string FormatMoney (const \fBCAmount\fP n)"
Money parsing/formatting utilities\&. 
.SS "std::optional< \fBCAmount\fP > ParseMoney (const std::string & str)"
Parse an amount denoted in full coins\&. E\&.g\&. "0\&.0034" supplied on the command line\&. 
.SS "std::string TrimString (std::string_view str, std::string_view pattern = \fR' \\f\\n\\r\\t\\v'\fP)\fR [inline]\fP, \fR [nodiscard]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
