.TH "_Require< SfinaeExpr, Result_ >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Require< SfinaeExpr, Result_ > \- SFINAE helper, see using \fBRequire\fP below\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBResult\fP = Result_"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename SfinaeExpr, typename Result_>
.br
struct mp::_Require< SfinaeExpr, Result_ >"SFINAE helper, see using \fBRequire\fP below\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename SfinaeExpr, typename Result_> using \fBResult\fP = Result_"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
