.TH "ClientException< Exception, Accessor >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientException< Exception, Accessor >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-types\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBuildParams\fP"
.br
.ti -1c
.RI "struct \fBReadResults\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
