.TH "ClientParam< Accessor, Types >::BuildParams" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientParam< Accessor, Types >::BuildParams
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-types\&.h>\fP
.PP
Inherits \fBIterateFieldsHelper< BuildParams, sizeof\&.\&.\&.(Types)>\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \fBParams\fP, typename ParamList> void \fBhandleField\fP (\fBClientInvokeContext\fP &invoke_context, \fBParams\fP &params, ParamList)"
.br
.ti -1c
.RI "\fBBuildParams\fP (\fBClientParam\fP *client_param)"
.br
.in -1c

Public Member Functions inherited from \fBIterateFieldsHelper< BuildParams, sizeof\&.\&.\&.(Types)>\fP
.in +1c
.ti -1c
.RI "void \fBhandleChain\fP (Arg1 &arg1, Arg2 &arg2, ParamList, NextFn &&next_fn, NextFnArgs &&\&.\&.\&. next_fn_args)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBClientParam\fP * \fBm_client_param\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBAccessor\fP, typename\&.\&.\&. Types> BuildParams (\fBClientParam\fP * client_param)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBAccessor\fP, typename\&.\&.\&. Types> template<typename \fBParams\fP, typename ParamList> void handleField (\fBClientInvokeContext\fP & invoke_context, \fBParams\fP & params, ParamList )\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "template<typename \fBAccessor\fP, typename\&.\&.\&. Types> \fBClientParam\fP* m_client_param"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
