.TH "ClientInvokeContext" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientInvokeContext
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-io\&.h>\fP
.PP
Inherits \fBInvokeContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClientInvokeContext\fP (\fBConnection\fP &conn, \fBThreadContext\fP &\fBthread_context\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBThreadContext\fP & \fBthread_context\fP"
.br
.in -1c

Data Fields inherited from \fBInvokeContext\fP
.in +1c
.ti -1c
.RI "\fBConnection\fP & \fBconnection\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ClientInvokeContext (\fBConnection\fP & conn, \fBThreadContext\fP & thread_context)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBThreadContext\fP& thread_context"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
