.TH "EventLoopRef" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventLoopRef
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventLoopRef\fP (\fBEventLoop\fP &loop, \fBLock\fP *lock=nullptr)"
.br
.ti -1c
.RI "\fBEventLoopRef\fP (EventLoopRef &&other) noexcept"
.br
.ti -1c
.RI "\fBEventLoopRef\fP (const EventLoopRef &)=delete"
.br
.ti -1c
.RI "\fBEventLoopRef\fP & \fBoperator=\fP (const \fBEventLoopRef\fP &)=delete"
.br
.ti -1c
.RI "\fBEventLoopRef\fP & \fBoperator=\fP (\fBEventLoopRef\fP &&)=delete"
.br
.ti -1c
.RI "\fB~EventLoopRef\fP ()"
.br
.ti -1c
.RI "\fBEventLoop\fP & \fBoperator*\fP () const"
.br
.ti -1c
.RI "\fBEventLoop\fP * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "void \fBreset\fP (bool relock=false)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEventLoop\fP * \fBm_loop\fP {nullptr}"
.br
.ti -1c
.RI "\fBLock\fP * \fBm_lock\fP {nullptr}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event loop smart pointer automatically managing m_num_clients\&. If a lock pointer argument is passed, the specified lock will be used, otherwise \fBEventLoop::m_mutex\fP will be locked when needed\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EventLoopRef (\fBEventLoop\fP & loop, \fBLock\fP * lock = \fRnullptr\fP)\fR [explicit]\fP"

.SS "EventLoopRef (EventLoopRef && other)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "EventLoopRef (const EventLoopRef & )\fR [delete]\fP"

.SS "~\fBEventLoopRef\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBEventLoop\fP & operator* () const\fR [inline]\fP"

.SS "\fBEventLoop\fP * operator\-> () const\fR [inline]\fP"

.SS "\fBEventLoopRef\fP & operator= (const \fBEventLoopRef\fP & )\fR [delete]\fP"

.SS "\fBEventLoopRef\fP & operator= (\fBEventLoopRef\fP && )\fR [delete]\fP"

.SS "void reset (bool relock = \fRfalse\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBLock\fP* m_lock {nullptr}"

.SS "\fBEventLoop\fP* m_loop {nullptr}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
