.TH "mp::IsByteSpan" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mp::IsByteSpan
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <type\-data\&.h>\fP
.SH "Concept definition"
.PP 

.nf
template<typename T>
concept mp::IsByteSpan = 
    IsSpanOf<T, std::byte> ||
    IsSpanOf<T, char> ||
    IsSpanOf<T, unsigned char> ||
    IsSpanOf<T, signed char>
.PP
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
