.TH "mp::IsSpanOf" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mp::IsSpanOf
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <type\-data\&.h>\fP
.SH "Concept definition"
.PP 

.nf
template<typename T, typename U>
concept mp::IsSpanOf = 
    std::convertible_to<T, std::span<const U>> &&
    std::constructible_from<T, const U*, const U*>
.PP
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
