.TH "IterateFieldsHelper< Derived, N >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IterateFieldsHelper< Derived, N >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Arg1, typename Arg2, typename ParamList, typename NextFn, typename\&.\&.\&. NextFnArgs> void \fBhandleChain\fP (Arg1 &arg1, Arg2 &arg2, ParamList, NextFn &&next_fn, NextFnArgs &&\&.\&.\&. next_fn_args)"
.br
.ti -1c
.RI "template<typename Arg1, typename Arg2, typename ParamList> void \fBhandleChain\fP (Arg1 &arg1, Arg2 &arg2, ParamList)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBDerived\fP, size_t N = 0> template<typename Arg1, typename Arg2, typename ParamList> void handleChain (Arg1 & arg1, Arg2 & arg2, ParamList )\fR [inline]\fP"

.SS "template<typename \fBDerived\fP, size_t N = 0> template<typename Arg1, typename Arg2, typename ParamList, typename NextFn, typename\&.\&.\&. NextFnArgs> void handleChain (Arg1 & arg1, Arg2 & arg2, ParamList , NextFn && next_fn, NextFnArgs &&\&.\&.\&. next_fn_args)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
