.TH "Lock" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lock
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLock\fP (\fBMutex\fP &m) \fBMP_ACQUIRE\fP(m)"
.br
.ti -1c
.RI "\fB~Lock\fP () \fBMP_RELEASE\fP()=default"
.br
.ti -1c
.RI "void \fBunlock\fP () \fBMP_RELEASE\fP()"
.br
.ti -1c
.RI "void \fBlock\fP () \fBMP_ACQUIRE\fP()"
.br
.ti -1c
.RI "void \fBassert_locked\fP (\fBMutex\fP &mutex) \fBMP_ASSERT_CAPABILITY\fP() \fBMP_ASSERT_CAPABILITY\fP(mutex)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::unique_lock< std::mutex > \fBm_lock\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Lock (\fBMutex\fP & m)\fR [inline]\fP, \fR [explicit]\fP"

.SS "~\fBLock\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void assert_locked (\fBMutex\fP & mutex)\fR [inline]\fP"

.SS "void lock ()\fR [inline]\fP"

.SS "void unlock ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::unique_lock<std::mutex> m_lock"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
