.TH "ListOutput<::capnp::List< T, kind > >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListOutput<::capnp::List< T, kind > >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-types\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBuilder\fP = typename ::capnp::List<\fBT\fP, kind>::Builder"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBListOutput\fP (\fBBuilder\fP &builder, size_t index)"
.br
.ti -1c
.RI "decltype(auto) \fBget\fP () const"
.br
.ti -1c
.RI "decltype(auto) \fBinit\fP () const"
.br
.ti -1c
.RI "template<typename \fBB\fP = Builder, typename Arg> decltype(auto) \fBset\fP (Arg &&arg) const"
.br
.ti -1c
.RI "template<typename \fBB\fP = Builder, typename Arg> decltype(auto) \fBinit\fP (Arg &&arg) const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBuilder\fP & \fBm_builder\fP"
.br
.ti -1c
.RI "size_t \fBm_index\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename \fBT\fP, ::capnp::Kind kind> using \fBBuilder\fP = typename ::capnp::List<\fBT\fP, kind>::Builder"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBT\fP, ::capnp::Kind kind> ListOutput (\fBBuilder\fP & builder, size_t index)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBT\fP, ::capnp::Kind kind> decltype(auto) get () const\fR [inline]\fP"

.SS "template<typename \fBT\fP, ::capnp::Kind kind> decltype(auto) init () const\fR [inline]\fP"

.SS "template<typename \fBT\fP, ::capnp::Kind kind> template<typename \fBB\fP = Builder, typename Arg> decltype(auto) init (Arg && arg) const\fR [inline]\fP"

.SS "template<typename \fBT\fP, ::capnp::Kind kind> template<typename \fBB\fP = Builder, typename Arg> decltype(auto) set (Arg && arg) const\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "template<typename \fBT\fP, ::capnp::Kind kind> \fBBuilder\fP& m_builder"

.SS "template<typename \fBT\fP, ::capnp::Kind kind> size_t m_index"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
