.TH "LogMessage" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogMessage
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-io\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.RI "Message to be logged\&. "
.ti -1c
.RI "\fBLog\fP \fBlevel\fP"
.br
.RI "The severity level of this message\&. "
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBLog\fP level"

.PP
The severity level of this message\&. 
.SS "std::string message"

.PP
Message to be logged\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
