.TH "LoggingErrorHandler" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoggingErrorHandler \- \fBHandler\fP for kj::TaskSet failed task events\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-io\&.h>\fP
.PP
Inherits ErrorHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoggingErrorHandler\fP (\fBEventLoop\fP &loop)"
.br
.ti -1c
.RI "void \fBtaskFailed\fP (kj::Exception &&exception) override"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEventLoop\fP & \fBm_loop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBHandler\fP for kj::TaskSet failed task events\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LoggingErrorHandler (\fBEventLoop\fP & loop)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void taskFailed (kj::Exception && exception)\fR [override]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBEventLoop\fP& m_loop"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
