.TH "Logger" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-io\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogger\fP (const \fBLogOptions\fP &options, \fBLog\fP log_level)"
.br
.ti -1c
.RI "\fBLogger\fP (\fBLogger\fP &&)=delete"
.br
.ti -1c
.RI "\fBLogger\fP & \fBoperator=\fP (\fBLogger\fP &&)=delete"
.br
.ti -1c
.RI "\fBLogger\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "\fBLogger\fP & \fBoperator=\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "\fB~Logger\fP () noexcept(false)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP> \fBLogger\fP & \fBoperator<<\fP (\fBLogger\fP &logger, \fBT\fP &&value)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBLogger\fP & \fBoperator<<\fP (\fBLogger\fP &&logger, \fBT\fP &&value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLogger\fP (const \fBLogOptions\fP & options, \fBLog\fP log_level)\fR [inline]\fP"

.SS "\fBLogger\fP (\fBLogger\fP && )\fR [delete]\fP"

.SS "\fBLogger\fP (const \fBLogger\fP & )\fR [delete]\fP"

.SS "~\fBLogger\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "operator bool () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "\fBLogger\fP & operator= (const \fBLogger\fP & )\fR [delete]\fP"

.SS "\fBLogger\fP & operator= (\fBLogger\fP && )\fR [delete]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "template<typename \fBT\fP> \fBLogger\fP & operator<< (\fBLogger\fP && logger, \fBT\fP && value)\fR [friend]\fP"

.SS "template<typename \fBT\fP> \fBLogger\fP & operator<< (\fBLogger\fP & logger, \fBT\fP && value)\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
