.TH "ProxyContext" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxyContext \- Context data associated with proxy client and server classes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProxyContext\fP (\fBConnection\fP *\fBconnection\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBConnection\fP * \fBconnection\fP"
.br
.ti -1c
.RI "\fBEventLoopRef\fP \fBloop\fP"
.br
.ti -1c
.RI "\fBCleanupList\fP \fBcleanup_fns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Context data associated with proxy client and server classes\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProxyContext (\fBConnection\fP * connection)"

.SH "Field Documentation"
.PP 
.SS "\fBCleanupList\fP cleanup_fns"

.SS "\fBConnection\fP* connection"

.SS "\fBEventLoopRef\fP loop"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
