.TH "ProxyServer< ThreadMap >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxyServer< ThreadMap >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <type\-threadmap\&.h>\fP
.PP
Inherits Server\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProxyServer\fP (\fBConnection\fP &connection)"
.br
.ti -1c
.RI "kj::Promise< void > \fBmakeThread\fP (MakeThreadContext context) override"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBConnection\fP & \fBm_connection\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProxyServer (\fBConnection\fP & connection)"

.SH "Member Function Documentation"
.PP 
.SS "kj::Promise< void > makeThread (MakeThreadContext context)\fR [override]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBConnection\fP& m_connection"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
