.TH "ProxyServerMethodTraits< MethodParams >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxyServerMethodTraits< MethodParams >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\&.h>\fP
.PP
Inherits \fBProxyMethodTraits< MethodParams, Enable >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBProxyMethodTraits< MethodParams, Enable >\fP
.in +1c
.ti -1c
.RI "using \fBParams\fP = \fBTypeList\fP<>"
.br
.ti -1c
.RI "using \fBResult\fP = void"
.br
.ti -1c
.RI "using \fBFields\fP = \fBParams\fP"
.br
.in -1c

Static Public Member Functions inherited from \fBProxyMethodTraits< MethodParams, Enable >\fP
.in +1c
.ti -1c
.RI "template<typename \fBServerContext\fP> static void \fBinvoke\fP (\fBServerContext\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MethodParams>
.br
struct mp::ProxyServerMethodTraits< MethodParams >"Customizable (through template specialization) traits class used in generated \fBProxyServer\fP implementations from proxy-codegen\&.cpp\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
