.TH "ProxyCallback< Fn >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxyCallback< Fn > \- \fBWrapper\fP around std::function for passing std::function objects between client and servers\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename Fn>
.br
class mp::ProxyCallback< Fn >"\fBWrapper\fP around std::function for passing std::function objects between client and servers\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
