.TH "ProxyClient< Thread >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxyClient< Thread >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-io\&.h>\fP
.PP
Inherits \fBProxyClientBase< Thread, ::capnp::Void >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProxyClient\fP (const ProxyClient &)=delete"
.br
.ti -1c
.RI "\fB~ProxyClient\fP ()"
.br
.ti -1c
.RI "\fBProxyClientBase\fP (typename Interface::Client client, \fBConnection\fP *connection, bool destroy_connection)"
.br
.in -1c

Public Member Functions inherited from \fBProxyClientBase< Thread, ::capnp::Void >\fP
.in +1c
.ti -1c
.RI "\fBProxyClientBase\fP (typename Interface::Client client, \fBConnection\fP *connection, bool destroy_connection)"
.br
.ti -1c
.RI "\fB~ProxyClientBase\fP () noexcept"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::optional< \fBCleanupIt\fP > \fBm_disconnect_cb\fP"
.br
.in -1c

Data Fields inherited from \fBProxyClientBase< Thread, ::capnp::Void >\fP
.in +1c
.ti -1c
.RI "Interface::Client \fBm_client\fP"
.br
.ti -1c
.RI "\fBProxyContext\fP \fBm_context\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBProxyClientBase< Thread, ::capnp::Void >\fP
.in +1c
.ti -1c
.RI "using \fBInterface\fP"
.br
.ti -1c
.RI "using \fBImpl\fP"
.br
.ti -1c
.RI "using \fBSub\fP"
.br
.ti -1c
.RI "using \fBSuper\fP"
.br
.in -1c

Static Public Member Functions inherited from \fBProxyClientBase< Thread, ::capnp::Void >\fP
.in +1c
.ti -1c
.RI "static void \fBconstruct\fP (\fBSuper\fP &)"
.br
.ti -1c
.RI "static void \fBdestroy\fP (\fBSuper\fP &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProxyClient (const ProxyClient< Thread > & )\fR [delete]\fP"

.SS "~\fBProxyClient\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "ProxyClientBase (typename Interface::Client client, \fBConnection\fP * connection, bool destroy_connection)"
Construct libmultiprocess client object wrapping Cap'n Proto client object with a reference to the associated \fBmp::Connection\fP object\&.

.PP
The destroy_connection option determines whether destroying this client object closes the connection\&. It is set to true for the ProxyClient<InitInterface> object returned by ConnectStream, to let IPC clients close the connection by freeing the object\&. It is false for other client objects so they can be destroyed without affecting the connection\&. 
.SH "Field Documentation"
.PP 
.SS "std::optional<\fBCleanupIt\fP> m_disconnect_cb"
Reference to callback function that is run if there is a sudden disconnect and the \fBConnection\fP object is destroyed before this \fBProxyClient<Thread>\fP object\&. The callback will destroy this object and remove its entry from the thread's request_threads or callback_threads map\&. It will also reset m_disconnect_cb so the destructor does not access it\&. In the normal case where there is no sudden disconnect, the destructor will unregister m_disconnect_cb so the callback is never run\&. Since this variable is accessed from multiple threads, accesses should be guarded with the associated \fBWaiter::m_mutex\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
