.TH "ProxyClientCustom< Interface, Impl >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxyClientCustom< Interface, Impl >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\&.h>\fP
.PP
Inherits \fBProxyClientBase< Interface, Impl >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBProxyClientBase< Interface, Impl >\fP
.in +1c
.ti -1c
.RI "using \fBInterface\fP"
.br
.ti -1c
.RI "using \fBImpl\fP"
.br
.ti -1c
.RI "using \fBSub\fP"
.br
.ti -1c
.RI "using \fBSuper\fP"
.br
.in -1c

Public Member Functions inherited from \fBProxyClientBase< Interface, Impl >\fP
.in +1c
.ti -1c
.RI "\fBProxyClientBase\fP (typename Interface::Client client, \fBConnection\fP *connection, bool destroy_connection)"
.br
.ti -1c
.RI "\fB~ProxyClientBase\fP () noexcept"
.br
.in -1c

Static Public Member Functions inherited from \fBProxyClientBase< Interface, Impl >\fP
.in +1c
.ti -1c
.RI "static void \fBconstruct\fP (\fBSuper\fP &)"
.br
.ti -1c
.RI "static void \fBdestroy\fP (\fBSuper\fP &)"
.br
.in -1c

Data Fields inherited from \fBProxyClientBase< Interface, Impl >\fP
.in +1c
.ti -1c
.RI "Interface::Client \fBm_client\fP"
.br
.ti -1c
.RI "\fBProxyContext\fP \fBm_context\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \fBInterface\fP, typename \fBImpl\fP>
.br
class mp::ProxyClientCustom< Interface, Impl >"Customizable (through template specialization) base class used in generated \fBProxyClient\fP implementations from proxy-codegen\&.cpp\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
