.TH "ProxyMethodTraits< MethodParams, Require< decltype(ProxyMethod< MethodParams >::impl)> >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxyMethodTraits< MethodParams, Require< decltype(ProxyMethod< MethodParams >::impl)> >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\&.h>\fP
.PP
Inherits \fBFunctionTraits< decltype(ProxyMethod< MethodParams >::impl)>\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBParams\fP"
.br
.ti -1c
.RI "using \fBResult\fP"
.br
.ti -1c
.RI "using \fBFields\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \fBServerContext\fP, typename\&.\&.\&. Args> static decltype(auto) \fBinvoke\fP (\fBServerContext\fP &server_context, Args &&\&.\&.\&. \fBargs\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MethodParams>
.br
struct mp::ProxyMethodTraits< MethodParams, Require< decltype(ProxyMethod< MethodParams >::impl)> >"Specialization of above for proxy methods that have a ProxyMethod<InterfaceName::MethodNameParams>::impl pointer-to-method constant defined by generated code\&. This includes all functions defined in the capnp interface except any construct() or destroy() methods, that are assumed not to correspond to real member functions in the C++ class, and will use the fallback traits definition above\&. The generated code this specialization relies on looks like:

.PP
struct \fBProxyMethod<InterfaceName::MethodNameParams>\fP { static constexpr auto impl = &ClassName::methodName; }; 
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBFields\fP"

.SS "using \fBParams\fP"

.SS "using \fBResult\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename MethodParams> template<typename \fBServerContext\fP, typename\&.\&.\&. Args> decltype(auto) invoke (\fBServerContext\fP & server_context, Args &&\&.\&.\&. args)\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
