.TH "ProxyCallback< std::function< Result(Args...)> >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxyCallback< std::function< Result(Args...)> > \- Specialization of above to separate Result and Arg types\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\&.h>\fP
.PP
Inherited by \fBProxyCallbackImpl< Result, Args >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual Result \fBcall\fP (Args &&\&.\&.\&. \fBargs\fP)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Result, typename\&.\&.\&. Args>
.br
class mp::ProxyCallback< std::function< Result(Args\&.\&.\&.)> >"Specialization of above to separate Result and Arg types\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename Result, typename\&.\&.\&. Args> virtual Result call (Args &&\&.\&.\&. args)\fR [pure virtual]\fP"

.PP
Implemented in \fBProxyCallbackImpl< Result, Args >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
