.TH "Priority< 0 >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Priority< 0 > \- Specialization of above (base case)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.SH "Detailed Description"
.PP 
Specialization of above (base case)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
