.TH "ServerCall" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerCall
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \fBServerContext\fP, typename\&.\&.\&. Args> decltype(auto) \fBinvoke\fP (\fBServerContext\fP &server_context, \fBTypeList\fP<>, Args &&\&.\&.\&. \fBargs\fP) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBServerContext\fP, typename\&.\&.\&. Args> decltype(auto) invoke (\fBServerContext\fP & server_context, \fBTypeList\fP<> , Args &&\&.\&.\&. args) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
