.TH "Split< index, List, _First, done >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Split< index, List, _First, done >
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<std::size_t index, typename List, typename _First = TypeList<>, bool done = index == 0>
.br
struct mp::Split< index, List, _First, done >"Type helper splitting a \fBTypeList\fP into two halves at position index\&.

.PP
Example: is_same<\fBTypeList<int, double>\fP, Split<2, TypeList<int, double, float, bool>>::First> is_same<\fBTypeList<float, bool>\fP, Split<2, TypeList<int, double, float, bool>>::Second> 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
