.TH "Split< index, TypeList< Type, _Second... >, TypeList< _First... >, false >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Split< index, TypeList< Type, _Second... >, TypeList< _First... >, false > \- Specialization of above (recursive case)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fB_Next\fP = \fBSplit\fP<index \- 1, \fBTypeList\fP<_Second\&.\&.\&.>, \fBTypeList\fP<_First\&.\&.\&., Type>>"
.br
.ti -1c
.RI "using \fBFirst\fP = typename _Next::First"
.br
.ti -1c
.RI "using \fBSecond\fP = typename _Next::Second"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<std::size_t index, typename Type, typename\&.\&.\&. _Second, typename\&.\&.\&. _First>
.br
struct mp::Split< index, TypeList< Type, _Second\&.\&.\&. >, TypeList< _First\&.\&.\&. >, false >"Specialization of above (recursive case)\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "template<std::size_t index, typename Type, typename\&.\&.\&. _Second, typename\&.\&.\&. _First> using \fB_Next\fP = \fBSplit\fP<index \- 1, \fBTypeList\fP<_Second\&.\&.\&.>, \fBTypeList\fP<_First\&.\&.\&., Type>>"

.SS "template<std::size_t index, typename Type, typename\&.\&.\&. _Second, typename\&.\&.\&. _First> using \fBFirst\fP = typename _Next::First"

.SS "template<std::size_t index, typename Type, typename\&.\&.\&. _Second, typename\&.\&.\&. _First> using \fBSecond\fP = typename _Next::Second"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
