.TH "ServerRet< Accessor, Parent >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerRet< Accessor, Parent >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <proxy\-types\&.h>\fP
.PP
Inherits Parent\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServerRet\fP (Parent parent)"
.br
.ti -1c
.RI "template<typename \fBServerContext\fP, typename\&.\&.\&. Args> void \fBinvoke\fP (\fBServerContext\fP &server_context, \fBTypeList\fP<>, Args &&\&.\&.\&. \fBargs\fP) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBAccessor\fP, typename Parent> ServerRet (Parent parent)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBAccessor\fP, typename Parent> template<typename \fBServerContext\fP, typename\&.\&.\&. Args> void invoke (\fBServerContext\fP & server_context, \fBTypeList\fP<> , Args &&\&.\&.\&. args) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
