.TH "TestSetup" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestSetup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestSetup\fP (bool client_owns_connection=true)"
.br
.ti -1c
.RI "\fB~TestSetup\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::function< void()> \fBserver_disconnect\fP"
.br
.ti -1c
.RI "std::function< void()> \fBclient_disconnect\fP"
.br
.ti -1c
.RI "std::promise< std::unique_ptr< \fBProxyClient\fP< messages::FooInterface > > > \fBclient_promise\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBProxyClient\fP< messages::FooInterface > > \fBclient\fP"
.br
.ti -1c
.RI "\fBProxyServer\fP< messages::FooInterface > * \fBserver\fP {nullptr}"
.br
.ti -1c
.RI "std::thread \fBthread\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test setup class creating a two way connection between a \fBProxyServer<FooInterface>\fP object and a \fBProxyClient<FooInterface>\fP\&.

.PP
Provides client_disconnect and server_disconnect lambdas that can be used to trigger disconnects and test handling of broken and closed connections\&.

.PP
Accepts a client_owns_connection option to test different \fBProxyClient\fP destroy_connection values and control whether destroying the \fBProxyClient\fP object destroys the client \fBConnection\fP object\&. Normally it makes sense for this to be true to simplify shutdown and avoid needing to call client_disconnect manually, but false allows testing more \fBProxyClient\fP behavior and the "IPC client method called after disconnect" code path\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TestSetup (bool client_owns_connection = \fRtrue\fP)\fR [inline]\fP"

.SS "~\fBTestSetup\fP ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::unique_ptr<\fBProxyClient\fP<messages::FooInterface> > client"

.SS "std::function<void()> client_disconnect"

.SS "std::promise<std::unique_ptr<\fBProxyClient\fP<messages::FooInterface> > > client_promise"

.SS "\fBProxyServer\fP<messages::FooInterface>* server {nullptr}"

.SS "std::function<void()> server_disconnect"

.SS "std::thread thread"
Thread variable should be after other struct members so the thread does not start until the other members are initialized\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
