.TH "UnlockGuard< Lock >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnlockGuard< Lock > \- Analog to std::lock_guard that unlocks instead of locks\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnlockGuard\fP (\fBLock\fP &lock)"
.br
.ti -1c
.RI "\fB~UnlockGuard\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBLock\fP & \fBm_lock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \fBLock\fP>
.br
struct mp::UnlockGuard< Lock >"Analog to std::lock_guard that unlocks instead of locks\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBLock\fP> UnlockGuard (\fBLock\fP & lock)\fR [inline]\fP"

.SS "template<typename \fBLock\fP> ~\fBUnlockGuard\fP ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "template<typename \fBLock\fP> \fBLock\fP& m_lock"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
