.TH "src/test/multisig_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/multisig_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <key\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <script/interpreter\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <script/script_error\&.h>\fP
.br
\fR#include <script/sign\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <test/util/transaction_utils\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (multisig_verify)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (multisig_IsStandard)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (multisig_Sign)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (multisig_IsStandard )"

.SS "BOOST_AUTO_TEST_CASE (multisig_Sign )"

.SS "BOOST_AUTO_TEST_CASE (multisig_verify )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
