.TH "musig_key_agg_error_test_case" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
musig_key_agg_error_test_case
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <vectors\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBkey_indices_len\fP"
.br
.ti -1c
.RI "size_t \fBkey_indices\fP [4]"
.br
.ti -1c
.RI "size_t \fBtweak_indices_len\fP"
.br
.ti -1c
.RI "size_t \fBtweak_indices\fP [1]"
.br
.ti -1c
.RI "int \fBis_xonly\fP [1]"
.br
.ti -1c
.RI "enum \fBMUSIG_ERROR\fP \fBerror\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "enum \fBMUSIG_ERROR\fP error"

.SS "int is_xonly[1]"

.SS "size_t key_indices[4]"

.SS "size_t key_indices_len"

.SS "size_t tweak_indices[1]"

.SS "size_t tweak_indices_len"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
