.TH "src/musig.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/musig.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <musig\&.h>\fP
.br
\fR#include <support/allocators/secure\&.h>\fP
.br
\fR#include <secp256k1_musig\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMuSig2SecNonceImpl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::optional< \fBCPubKey\fP > \fBMuSig2AggregatePubkeys\fP (const std::vector< \fBCPubKey\fP > &pubkeys, \fBsecp256k1_musig_keyagg_cache\fP &keyagg_cache, const std::optional< \fBCPubKey\fP > &expected_aggregate)"
.br
.ti -1c
.RI "std::optional< \fBCPubKey\fP > \fBMuSig2AggregatePubkeys\fP (const std::vector< \fBCPubKey\fP > &pubkeys)"
.br
.ti -1c
.RI "\fBCExtPubKey\fP \fBCreateMuSig2SyntheticXpub\fP (const \fBCPubKey\fP &pubkey)"
.br
.RI "Construct the BIP 328 synthetic xpub for a pubkey\&. "
.ti -1c
.RI "\fBuint256\fP \fBMuSig2SessionID\fP (const \fBCPubKey\fP &script_pubkey, const \fBCPubKey\fP &part_pubkey, const \fBuint256\fP &sighash)"
.br
.ti -1c
.RI "std::optional< std::vector< uint8_t > > \fBCreateMuSig2AggregateSig\fP (const std::vector< \fBCPubKey\fP > &part_pubkeys, const \fBCPubKey\fP &aggregate_pubkey, const std::vector< std::pair< \fBuint256\fP, bool > > &tweaks, const \fBuint256\fP &sighash, const std::map< \fBCPubKey\fP, std::vector< uint8_t > > &pubnonces, const std::map< \fBCPubKey\fP, \fBuint256\fP > &partial_sigs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr \fBuint256\fP \fBMUSIG_CHAINCODE\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::optional< std::vector< uint8_t > > CreateMuSig2AggregateSig (const std::vector< \fBCPubKey\fP > & part_pubkeys, const \fBCPubKey\fP & aggregate_pubkey, const std::vector< std::pair< \fBuint256\fP, bool > > & tweaks, const \fBuint256\fP & sighash, const std::map< \fBCPubKey\fP, std::vector< uint8_t > > & pubnonces, const std::map< \fBCPubKey\fP, \fBuint256\fP > & partial_sigs)"

.SS "\fBCExtPubKey\fP CreateMuSig2SyntheticXpub (const \fBCPubKey\fP & pubkey)"

.PP
Construct the BIP 328 synthetic xpub for a pubkey\&. 
.SS "std::optional< \fBCPubKey\fP > MuSig2AggregatePubkeys (const std::vector< \fBCPubKey\fP > & pubkeys)"

.SS "std::optional< \fBCPubKey\fP > MuSig2AggregatePubkeys (const std::vector< \fBCPubKey\fP > & pubkeys, \fBsecp256k1_musig_keyagg_cache\fP & keyagg_cache, const std::optional< \fBCPubKey\fP > & expected_aggregate)"
Compute the full aggregate pubkey from the given participant pubkeys in their current order\&. Outputs the \fBsecp256k1_musig_keyagg_cache\fP and validates that the computed aggregate pubkey matches an expected aggregate pubkey\&. This is necessary for most MuSig2 operations\&. 
.SS "\fBuint256\fP MuSig2SessionID (const \fBCPubKey\fP & script_pubkey, const \fBCPubKey\fP & part_pubkey, const \fBuint256\fP & sighash)"

.SH "Variable Documentation"
.PP 
.SS "\fBuint256\fP MUSIG_CHAINCODE\fR [constexpr]\fP"
\fBInitial value:\fP
.nf
{
    
    []() consteval { return uint256{"868087ca02a6f974c4598924c36b57762d32cb45717167e300622c7167e38965"_hex_u8}; }(),
}
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
