.TH "musig_nonce_agg_vector" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
musig_nonce_agg_vector
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <vectors\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBpnonces\fP [7][66]"
.br
.ti -1c
.RI "struct \fBmusig_nonce_agg_test_case\fP \fBvalid_case\fP [2]"
.br
.ti -1c
.RI "struct \fBmusig_nonce_agg_test_case\fP \fBerror_case\fP [3]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBmusig_nonce_agg_test_case\fP error_case[3]"

.SS "unsigned char pnonces[7][66]"

.SS "struct \fBmusig_nonce_agg_test_case\fP valid_case[2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
