.TH "musig_nonce_gen_test_case" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
musig_nonce_gen_test_case
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <vectors\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBrand_\fP [32]"
.br
.ti -1c
.RI "int \fBhas_sk\fP"
.br
.ti -1c
.RI "unsigned char \fBsk\fP [32]"
.br
.ti -1c
.RI "unsigned char \fBpk\fP [33]"
.br
.ti -1c
.RI "int \fBhas_aggpk\fP"
.br
.ti -1c
.RI "unsigned char \fBaggpk\fP [32]"
.br
.ti -1c
.RI "int \fBhas_msg\fP"
.br
.ti -1c
.RI "unsigned char \fBmsg\fP [32]"
.br
.ti -1c
.RI "int \fBhas_extra_in\fP"
.br
.ti -1c
.RI "unsigned char \fBextra_in\fP [32]"
.br
.ti -1c
.RI "unsigned char \fBexpected_secnonce\fP [97]"
.br
.ti -1c
.RI "unsigned char \fBexpected_pubnonce\fP [66]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char aggpk[32]"

.SS "unsigned char expected_pubnonce[66]"

.SS "unsigned char expected_secnonce[97]"

.SS "unsigned char extra_in[32]"

.SS "int has_aggpk"

.SS "int has_extra_in"

.SS "int has_msg"

.SS "int has_sk"

.SS "unsigned char msg[32]"

.SS "unsigned char pk[33]"

.SS "unsigned char rand_[32]"

.SS "unsigned char sk[32]"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
