.TH "musig_sig_agg_case" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
musig_sig_agg_case
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <vectors\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBkey_indices_len\fP"
.br
.ti -1c
.RI "size_t \fBkey_indices\fP [2]"
.br
.ti -1c
.RI "size_t \fBtweak_indices_len\fP"
.br
.ti -1c
.RI "size_t \fBtweak_indices\fP [3]"
.br
.ti -1c
.RI "int \fBis_xonly\fP [3]"
.br
.ti -1c
.RI "unsigned char \fBaggnonce\fP [66]"
.br
.ti -1c
.RI "size_t \fBpsig_indices_len\fP"
.br
.ti -1c
.RI "size_t \fBpsig_indices\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBexpected\fP [64]"
.br
.ti -1c
.RI "int \fBinvalid_sig_idx\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char aggnonce[66]"

.SS "unsigned char expected[64]"

.SS "int invalid_sig_idx"

.SS "int is_xonly[3]"

.SS "size_t key_indices[2]"

.SS "size_t key_indices_len"

.SS "size_t psig_indices[2]"

.SS "size_t psig_indices_len"

.SS "size_t tweak_indices[3]"

.SS "size_t tweak_indices_len"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
