.TH "musig_sig_agg_vector" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
musig_sig_agg_vector
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <vectors\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBpubkeys\fP [4][33]"
.br
.ti -1c
.RI "unsigned char \fBtweaks\fP [3][32]"
.br
.ti -1c
.RI "unsigned char \fBpsigs\fP [9][32]"
.br
.ti -1c
.RI "unsigned char \fBmsg\fP [32]"
.br
.ti -1c
.RI "struct \fBmusig_sig_agg_case\fP \fBvalid_case\fP [4]"
.br
.ti -1c
.RI "struct \fBmusig_sig_agg_case\fP \fBerror_case\fP [1]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBmusig_sig_agg_case\fP error_case[1]"

.SS "unsigned char msg[32]"

.SS "unsigned char psigs[9][32]"

.SS "unsigned char pubkeys[4][33]"

.SS "unsigned char tweaks[3][32]"

.SS "struct \fBmusig_sig_agg_case\fP valid_case[4]"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
