.TH "MuSig2SecNonceImpl" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MuSig2SecNonceImpl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMuSig2SecNonceImpl\fP ()"
.br
.ti -1c
.RI "\fBMuSig2SecNonceImpl\fP (const \fBMuSig2SecNonceImpl\fP &)=delete"
.br
.ti -1c
.RI "\fBMuSig2SecNonceImpl\fP & \fBoperator=\fP (const \fBMuSig2SecNonceImpl\fP &)=delete"
.br
.ti -1c
.RI "\fBsecp256k1_musig_secnonce\fP * \fBGet\fP () const"
.br
.ti -1c
.RI "void \fBInvalidate\fP ()"
.br
.ti -1c
.RI "bool \fBIsValid\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBMuSig2SecNonceImpl\fP ()\fR [inline]\fP"

.SS "\fBMuSig2SecNonceImpl\fP (const \fBMuSig2SecNonceImpl\fP & )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBsecp256k1_musig_secnonce\fP * Get () const\fR [inline]\fP"

.SS "void Invalidate ()\fR [inline]\fP"

.SS "bool IsValid ()\fR [inline]\fP"

.SS "\fBMuSig2SecNonceImpl\fP & operator= (const \fBMuSig2SecNonceImpl\fP & )\fR [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
