.TH "src/bench/nanobench.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bench/nanobench.h
.SH SYNOPSIS
.br
.PP
\fR#include <chrono>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <iosfwd>\fP
.br
\fR#include <string>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBPerfCountSet< T >\fP"
.br
.ti -1c
.RI "struct \fBConfig\fP"
.br
.ti -1c
.RI "class \fBResult\fP"
.br
.ti -1c
.RI "class \fBRng\fP"
.br
.ti -1c
.RI "class \fBBench\fP"
.br
.RI "Main entry point to nanobench's benchmarking facility\&. "
.ti -1c
.RI "class \fBIterationLogic\fP"
.br
.ti -1c
.RI "class \fBPerformanceCounters\fP"
.br
.ti -1c
.RI "class \fBBigO\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBankerl\fP"
.br
.ti -1c
.RI "namespace \fBankerl::nanobench\fP"
.br
.ti -1c
.RI "namespace \fBankerl::nanobench::templates\fP"
.br
.ti -1c
.RI "namespace \fBankerl::nanobench::detail\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_VERSION_MAJOR\fP   4"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_VERSION_MINOR\fP   3"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_VERSION_PATCH\fP   11"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH\fP(x)"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_CXX\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_CXX98\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_CXX11\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_CXX14\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_CXX17\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_NODISCARD\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_IGNORE_PADDED_PUSH\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_IGNORE_PADDED_POP\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_IGNORE_EFFCPP_PUSH\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_IGNORE_EFFCPP_POP\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_LOG\fP(x)"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_PERF_COUNTERS\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_NO_SANITIZE\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_NOINLINE\fP()"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_IS_TRIVIALLY_COPYABLE\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBANKERL_NANOBENCH_PRIVATE_NOEXCEPT_STRING_MOVE\fP()"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBClock\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrender\fP (char const *mustacheTemplate, \fBBench\fP const &bench, std::ostream &out)"
.br
.RI "Renders output from a mustache-like template and benchmark results\&. "
.ti -1c
.RI "void \fBrender\fP (std::string const &mustacheTemplate, \fBBench\fP const &bench, std::ostream &out)"
.br
.ti -1c
.RI "void \fBrender\fP (char const *mustacheTemplate, std::vector< \fBResult\fP > const &results, std::ostream &out)"
.br
.ti -1c
.RI "void \fBrender\fP (std::string const &mustacheTemplate, std::vector< \fBResult\fP > const &results, std::ostream &out)"
.br
.ti -1c
.RI "char const * \fBcsv\fP () noexcept"
.br
.RI "CSV data for the benchmark results\&. "
.ti -1c
.RI "char const * \fBhtmlBoxplot\fP () noexcept"
.br
.RI "HTML output that uses plotly to generate an interactive boxplot chart\&. See the tutorial for an example output\&. "
.ti -1c
.RI "char const * \fBpyperf\fP () noexcept"
.br
.RI "Output in pyperf compatible JSON format, which can be used for more analyzation\&. "
.ti -1c
.RI "char const * \fBjson\fP () noexcept"
.br
.RI "Template to generate JSON data\&. "
.ti -1c
.RI "template<typename Arg> void \fBdoNotOptimizeAway\fP (Arg &&arg)"
.br
.RI "Makes sure none of the given arguments are optimized away by the compiler\&. "
.ti -1c
.RI "template<typename \fBT\fP> void \fBdoNotOptimizeAway\fP (\fBT\fP const &val)"
.br
.ti -1c
.RI "template<typename \fBT\fP> void \fBdoNotOptimizeAway\fP (\fBT\fP &val)"
.br
.ti -1c
.RI "\fBPerformanceCounters\fP & \fBperformanceCounters\fP ()"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, \fBBigO\fP const &bigO)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, std::vector< \fBankerl::nanobench::BigO\fP > const &bigOs)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ANKERL_NANOBENCH( x)"
\fBValue:\fP
.nf
ANKERL_NANOBENCH_PRIVATE_##x()
.PP
.fi

.SS "#define ANKERL_NANOBENCH_IS_TRIVIALLY_COPYABLE( \&.\&.\&.)"
\fBValue:\fP
.nf
std::is_trivially_copyable<__VA_ARGS__>::value
.PP
.fi

.SS "#define ANKERL_NANOBENCH_LOG( x)"
\fBValue:\fP
.nf
        do {                        \\
        } while (0)
.PP
.fi

.SS "#define ANKERL_NANOBENCH_NO_SANITIZE( \&.\&.\&.)"

.SS "#define ANKERL_NANOBENCH_PRIVATE_CXX()"
\fBValue:\fP
.nf
__cplusplus
.PP
.fi

.SS "#define ANKERL_NANOBENCH_PRIVATE_CXX11()"
\fBValue:\fP
.nf
201103L
.PP
.fi

.SS "#define ANKERL_NANOBENCH_PRIVATE_CXX14()"
\fBValue:\fP
.nf
201402L
.PP
.fi

.SS "#define ANKERL_NANOBENCH_PRIVATE_CXX17()"
\fBValue:\fP
.nf
201703L
.PP
.fi

.SS "#define ANKERL_NANOBENCH_PRIVATE_CXX98()"
\fBValue:\fP
.nf
199711L
.PP
.fi

.SS "#define ANKERL_NANOBENCH_PRIVATE_IGNORE_EFFCPP_POP()"

.SS "#define ANKERL_NANOBENCH_PRIVATE_IGNORE_EFFCPP_PUSH()"

.SS "#define ANKERL_NANOBENCH_PRIVATE_IGNORE_PADDED_POP()"

.SS "#define ANKERL_NANOBENCH_PRIVATE_IGNORE_PADDED_PUSH()"

.SS "#define ANKERL_NANOBENCH_PRIVATE_NODISCARD()"

.SS "#define ANKERL_NANOBENCH_PRIVATE_NOEXCEPT_STRING_MOVE()"
\fBValue:\fP
.nf
std::is_nothrow_move_assignable<std::string>::value
.PP
.fi

.SS "#define ANKERL_NANOBENCH_PRIVATE_NOINLINE()"
\fBValue:\fP
.nf
__attribute__((noinline))
.PP
.fi

.SS "#define ANKERL_NANOBENCH_PRIVATE_PERF_COUNTERS()"
\fBValue:\fP
.nf
0
.PP
.fi

.SS "#define ANKERL_NANOBENCH_VERSION_MAJOR   4"

.SS "#define ANKERL_NANOBENCH_VERSION_MINOR   3"

.SS "#define ANKERL_NANOBENCH_VERSION_PATCH   11"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
