.TH "src/test/util/net.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/util/net.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/util/net\&.h>\fP
.br
\fR#include <net_processing\&.h>\fP
.br
\fR#include <netaddress\&.h>\fP
.br
\fR#include <netmessagemaker\&.h>\fP
.br
\fR#include <node/connection_types\&.h>\fP
.br
\fR#include <node/eviction\&.h>\fP
.br
\fR#include <protocol\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< \fBNodeEvictionCandidate\fP > \fBGetRandomNodeEvictionCandidates\fP (int n_candidates, \fBFastRandomContext\fP &random_context)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::vector< \fBNodeEvictionCandidate\fP > GetRandomNodeEvictionCandidates (int n_candidates, \fBFastRandomContext\fP & random_context)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
