.TH "src/test/net_peer_eviction_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/net_peer_eviction_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <netaddress\&.h>\fP
.br
\fR#include <net\&.h>\fP
.br
\fR#include <test/util/net\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <unordered_set>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBIsProtected\fP (int num_peers, std::function< void(\fBNodeEvictionCandidate\fP &)> candidate_setup_fn, const std::unordered_set< \fBNodeId\fP > &protected_peer_ids, const std::unordered_set< \fBNodeId\fP > &unprotected_peer_ids, \fBFastRandomContext\fP &random_context)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (peer_protection_test)"
.br
.ti -1c
.RI "bool \fBIsEvicted\fP (std::vector< \fBNodeEvictionCandidate\fP > candidates, const std::unordered_set< \fBNodeId\fP > &node_ids, \fBFastRandomContext\fP &random_context)"
.br
.ti -1c
.RI "bool \fBIsEvicted\fP (const int number_of_nodes, std::function< void(\fBNodeEvictionCandidate\fP &)> candidate_setup_fn, const std::unordered_set< \fBNodeId\fP > &node_ids, \fBFastRandomContext\fP &random_context)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (peer_eviction_test)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (peer_eviction_test )"

.SS "BOOST_AUTO_TEST_CASE (peer_protection_test )"

.SS "bool IsEvicted (const int number_of_nodes, std::function< void(\fBNodeEvictionCandidate\fP &)> candidate_setup_fn, const std::unordered_set< \fBNodeId\fP > & node_ids, \fBFastRandomContext\fP & random_context)"

.SS "bool IsEvicted (std::vector< \fBNodeEvictionCandidate\fP > candidates, const std::unordered_set< \fBNodeId\fP > & node_ids, \fBFastRandomContext\fP & random_context)"

.SS "bool IsProtected (int num_peers, std::function< void(\fBNodeEvictionCandidate\fP &)> candidate_setup_fn, const std::unordered_set< \fBNodeId\fP > & protected_peer_ids, const std::unordered_set< \fBNodeId\fP > & unprotected_peer_ids, \fBFastRandomContext\fP & random_context)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
