.TH "src/net_types.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/net_types.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br
\fR#include <map>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCBanEntry\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBbanmap_t\fP = std::map<\fBCSubNet\fP, \fBCBanEntry\fP>"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUniValue\fP \fBBanMapToJson\fP (const \fBbanmap_t\fP &bans)"
.br
.ti -1c
.RI "void \fBBanMapFromJson\fP (const \fBUniValue\fP &bans_json, \fBbanmap_t\fP &bans)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBbanmap_t\fP = std::map<\fBCSubNet\fP, \fBCBanEntry\fP>"

.SH "Function Documentation"
.PP 
.SS "void BanMapFromJson (const \fBUniValue\fP & bans_json, \fBbanmap_t\fP & bans)"
Convert a JSON array to a \fR\fBbanmap_t\fP\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIbans_json\fP JSON to convert, must be as returned by \fR\fBBanMapToJson()\fP\fP\&. 
.br
\fIbans\fP Bans list to create from the JSON\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIstd::runtime_error\fP if the JSON does not have the expected fields or they contain unparsable values\&. 
.RE
.PP

.SS "\fBUniValue\fP BanMapToJson (const \fBbanmap_t\fP & bans)"
Convert a \fR\fBbanmap_t\fP\fP object to a JSON array\&. 
.PP
\fBParameters\fP
.RS 4
\fIbans\fP Bans list to convert\&. 
.RE
.PP
\fBReturns\fP
.RS 4
a JSON array, similar to the one returned by the \fRlistbanned\fP RPC\&. Suitable for passing to \fR\fBBanMapFromJson()\fP\fP\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
