.TH "NetGroupManager" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetGroupManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <netgroup\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetGroupManager\fP (std::vector< bool > asmap)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetAsmapChecksum\fP () const"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBGetGroup\fP (const \fBCNetAddr\fP &address) const"
.br
.ti -1c
.RI "uint32_t \fBGetMappedAS\fP (const \fBCNetAddr\fP &address) const"
.br
.ti -1c
.RI "void \fBASMapHealthCheck\fP (const std::vector< \fBCNetAddr\fP > &clearnet_addrs) const"
.br
.ti -1c
.RI "bool \fBUsingASMap\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Netgroup manager 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNetGroupManager\fP (std::vector< bool > asmap)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ASMapHealthCheck (const std::vector< \fBCNetAddr\fP > & clearnet_addrs) const"
Analyze and log current health of ASMap based buckets\&. 
.SS "\fBuint256\fP GetAsmapChecksum () const"
Get a checksum identifying the asmap being used\&. 
.SS "std::vector< unsigned char > GetGroup (const \fBCNetAddr\fP & address) const"
Get the canonical identifier of the network group for address\&.

.PP
The groups are assigned in a way where it should be costly for an attacker to obtain addresses with many different group identifiers, even if it is cheap to obtain addresses with the same identifier\&.

.PP
\fBNote\fP
.RS 4
No two connections will be attempted to addresses with the same network group\&. 
.RE
.PP

.SS "uint32_t GetMappedAS (const \fBCNetAddr\fP & address) const"
Get the autonomous system on the BGP path to address\&.

.PP
The ip->AS mapping depends on how asmap is constructed\&. 
.SS "bool UsingASMap () const"
Indicates whether ASMap is being used for clearnet bucketing\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
