.TH "NetMsgType" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetMsgType
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr const char * \fBVERSION\fP {'version'}"
.br
.ti -1c
.RI "constexpr const char * \fBVERACK\fP {'verack'}"
.br
.ti -1c
.RI "constexpr const char * \fBADDR\fP {'addr'}"
.br
.ti -1c
.RI "constexpr const char * \fBADDRV2\fP {'addrv2'}"
.br
.ti -1c
.RI "constexpr const char * \fBSENDADDRV2\fP {'sendaddrv2'}"
.br
.ti -1c
.RI "constexpr const char * \fBINV\fP {'inv'}"
.br
.ti -1c
.RI "constexpr const char * \fBGETDATA\fP {'getdata'}"
.br
.ti -1c
.RI "constexpr const char * \fBMERKLEBLOCK\fP {'merkleblock'}"
.br
.ti -1c
.RI "constexpr const char * \fBGETBLOCKS\fP {'getblocks'}"
.br
.ti -1c
.RI "constexpr const char * \fBGETHEADERS\fP {'getheaders'}"
.br
.ti -1c
.RI "constexpr const char * \fBTX\fP {'tx'}"
.br
.ti -1c
.RI "constexpr const char * \fBHEADERS\fP {'headers'}"
.br
.ti -1c
.RI "constexpr const char * \fBBLOCK\fP {'block'}"
.br
.ti -1c
.RI "constexpr const char * \fBGETADDR\fP {'getaddr'}"
.br
.ti -1c
.RI "constexpr const char * \fBMEMPOOL\fP {'mempool'}"
.br
.ti -1c
.RI "constexpr const char * \fBPING\fP {'ping'}"
.br
.ti -1c
.RI "constexpr const char * \fBPONG\fP {'pong'}"
.br
.ti -1c
.RI "constexpr const char * \fBNOTFOUND\fP {'notfound'}"
.br
.ti -1c
.RI "constexpr const char * \fBFILTERLOAD\fP {'filterload'}"
.br
.ti -1c
.RI "constexpr const char * \fBFILTERADD\fP {'filteradd'}"
.br
.ti -1c
.RI "constexpr const char * \fBFILTERCLEAR\fP {'filterclear'}"
.br
.ti -1c
.RI "constexpr const char * \fBSENDHEADERS\fP {'sendheaders'}"
.br
.ti -1c
.RI "constexpr const char * \fBFEEFILTER\fP {'feefilter'}"
.br
.ti -1c
.RI "constexpr const char * \fBSENDCMPCT\fP {'sendcmpct'}"
.br
.ti -1c
.RI "constexpr const char * \fBCMPCTBLOCK\fP {'cmpctblock'}"
.br
.ti -1c
.RI "constexpr const char * \fBGETBLOCKTXN\fP {'getblocktxn'}"
.br
.ti -1c
.RI "constexpr const char * \fBBLOCKTXN\fP {'blocktxn'}"
.br
.ti -1c
.RI "constexpr const char * \fBGETCFILTERS\fP {'getcfilters'}"
.br
.ti -1c
.RI "constexpr const char * \fBCFILTER\fP {'cfilter'}"
.br
.ti -1c
.RI "constexpr const char * \fBGETCFHEADERS\fP {'getcfheaders'}"
.br
.ti -1c
.RI "constexpr const char * \fBCFHEADERS\fP {'cfheaders'}"
.br
.ti -1c
.RI "constexpr const char * \fBGETCFCHECKPT\fP {'getcfcheckpt'}"
.br
.ti -1c
.RI "constexpr const char * \fBCFCHECKPT\fP {'cfcheckpt'}"
.br
.ti -1c
.RI "constexpr const char * \fBWTXIDRELAY\fP {'wtxidrelay'}"
.br
.ti -1c
.RI "constexpr const char * \fBSENDTXRCNCL\fP {'sendtxrcncl'}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Bitcoin protocol message types\&. When adding new message types, don't forget to update ALL_NET_MESSAGE_TYPES below\&. 
.SH "Variable Documentation"
.PP 
.SS "const char* ADDR {'addr'}\fR [inline]\fP, \fR [constexpr]\fP"
The addr (IP address) message relays connection information for peers on the network\&. 
.SS "const char* ADDRV2 {'addrv2'}\fR [inline]\fP, \fR [constexpr]\fP"
The addrv2 message relays connection information for peers on the network just like the addr message, but is extended to allow gossiping of longer node addresses (see BIP155)\&. 
.SS "const char* BLOCK {'block'}\fR [inline]\fP, \fR [constexpr]\fP"
The block message transmits a single serialized block\&. 
.SS "const char* BLOCKTXN {'blocktxn'}\fR [inline]\fP, \fR [constexpr]\fP"
Contains a \fBBlockTransactions\fP\&. Sent in response to a "getblocktxn" message\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70014 as described by BIP 152 
.RE
.PP

.SS "const char* CFCHECKPT {'cfcheckpt'}\fR [inline]\fP, \fR [constexpr]\fP"
cfcheckpt is a response to a getcfcheckpt request containing a vector of evenly spaced filter headers for blocks on the requested chain\&. 
.SS "const char* CFHEADERS {'cfheaders'}\fR [inline]\fP, \fR [constexpr]\fP"
cfheaders is a response to a getcfheaders request containing a filter header and a vector of filter hashes for each subsequent block in the requested range\&. 
.SS "const char* CFILTER {'cfilter'}\fR [inline]\fP, \fR [constexpr]\fP"
cfilter is a response to a getcfilters request containing a single compact filter\&. 
.SS "const char* CMPCTBLOCK {'cmpctblock'}\fR [inline]\fP, \fR [constexpr]\fP"
Contains a \fBCBlockHeaderAndShortTxIDs\fP object - providing a header and list of "short txids"\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70014 as described by BIP 152 
.RE
.PP

.SS "const char* FEEFILTER {'feefilter'}\fR [inline]\fP, \fR [constexpr]\fP"
The feefilter message tells the receiving peer not to inv us any txs which do not meet the specified min fee rate\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70013 as described by BIP133 
.RE
.PP

.SS "const char* FILTERADD {'filteradd'}\fR [inline]\fP, \fR [constexpr]\fP"
The filteradd message tells the receiving peer to add a single element to a previously-set bloom filter, such as a new public key\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70001 as described by BIP37\&. Only available with service bit NODE_BLOOM since protocol version 70011 as described by BIP111\&. 
.RE
.PP

.SS "const char* FILTERCLEAR {'filterclear'}\fR [inline]\fP, \fR [constexpr]\fP"
The filterclear message tells the receiving peer to remove a previously-set bloom filter\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70001 as described by BIP37\&. Only available with service bit NODE_BLOOM since protocol version 70011 as described by BIP111\&. 
.RE
.PP

.SS "const char* FILTERLOAD {'filterload'}\fR [inline]\fP, \fR [constexpr]\fP"
The filterload message tells the receiving peer to filter all relayed transactions and requested merkle blocks through the provided filter\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70001 as described by BIP37\&. Only available with service bit NODE_BLOOM since protocol version 70011 as described by BIP111\&. 
.RE
.PP

.SS "const char* GETADDR {'getaddr'}\fR [inline]\fP, \fR [constexpr]\fP"
The getaddr message requests an addr message from the receiving node, preferably one with lots of IP addresses of other receiving nodes\&. 
.SS "const char* GETBLOCKS {'getblocks'}\fR [inline]\fP, \fR [constexpr]\fP"
The getblocks message requests an inv message that provides block header hashes starting from a particular point in the block chain\&. 
.SS "const char* GETBLOCKTXN {'getblocktxn'}\fR [inline]\fP, \fR [constexpr]\fP"
Contains a \fBBlockTransactionsRequest\fP Peer should respond with "blocktxn" message\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70014 as described by BIP 152 
.RE
.PP

.SS "const char* GETCFCHECKPT {'getcfcheckpt'}\fR [inline]\fP, \fR [constexpr]\fP"
getcfcheckpt requests evenly spaced compact filter headers, enabling parallelized download and validation of the headers between them\&. Only available with service bit NODE_COMPACT_FILTERS as described by BIP 157 & 158\&. 
.SS "const char* GETCFHEADERS {'getcfheaders'}\fR [inline]\fP, \fR [constexpr]\fP"
getcfheaders requests a compact filter header and the filter hashes for a range of blocks, which can then be used to reconstruct the filter headers for those blocks\&. Only available with service bit NODE_COMPACT_FILTERS as described by BIP 157 & 158\&. 
.SS "const char* GETCFILTERS {'getcfilters'}\fR [inline]\fP, \fR [constexpr]\fP"
getcfilters requests compact filters for a range of blocks\&. Only available with service bit NODE_COMPACT_FILTERS as described by BIP 157 & 158\&. 
.SS "const char* GETDATA {'getdata'}\fR [inline]\fP, \fR [constexpr]\fP"
The getdata message requests one or more data objects from another node\&. 
.SS "const char* GETHEADERS {'getheaders'}\fR [inline]\fP, \fR [constexpr]\fP"
The getheaders message requests a headers message that provides block headers starting from a particular point in the block chain\&. 
.PP
\fBSince\fP
.RS 4
protocol version 31800\&. 
.RE
.PP

.SS "const char* HEADERS {'headers'}\fR [inline]\fP, \fR [constexpr]\fP"
The headers message sends one or more block headers to a node which previously requested certain headers with a getheaders message\&. 
.PP
\fBSince\fP
.RS 4
protocol version 31800\&. 
.RE
.PP

.SS "const char* INV {'inv'}\fR [inline]\fP, \fR [constexpr]\fP"
The inv message (inventory message) transmits one or more inventories of objects known to the transmitting peer\&. 
.SS "const char* MEMPOOL {'mempool'}\fR [inline]\fP, \fR [constexpr]\fP"
The mempool message requests the TXIDs of transactions that the receiving node has verified as valid but which have not yet appeared in a block\&. 
.PP
\fBSince\fP
.RS 4
protocol version 60002 as described by BIP35\&. Only available with service bit NODE_BLOOM, see also BIP111\&. 
.RE
.PP

.SS "const char* MERKLEBLOCK {'merkleblock'}\fR [inline]\fP, \fR [constexpr]\fP"
The merkleblock message is a reply to a getdata message which requested a block using the inventory type MSG_MERKLEBLOCK\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70001 as described by BIP37\&. 
.RE
.PP

.SS "const char* NOTFOUND {'notfound'}\fR [inline]\fP, \fR [constexpr]\fP"
The notfound message is a reply to a getdata message which requested an object the receiving node does not have available for relay\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70001\&. 
.RE
.PP

.SS "const char* PING {'ping'}\fR [inline]\fP, \fR [constexpr]\fP"
The ping message is sent periodically to help confirm that the receiving peer is still connected\&. 
.SS "const char* PONG {'pong'}\fR [inline]\fP, \fR [constexpr]\fP"
The pong message replies to a ping message, proving to the pinging node that the ponging node is still alive\&. 
.PP
\fBSince\fP
.RS 4
protocol version 60001 as described by BIP31\&. 
.RE
.PP

.SS "const char* SENDADDRV2 {'sendaddrv2'}\fR [inline]\fP, \fR [constexpr]\fP"
The sendaddrv2 message signals support for receiving ADDRV2 messages (BIP155)\&. It also implies that its sender can encode as ADDRV2 and would send ADDRV2 instead of ADDR to a peer that has signaled ADDRV2 support by sending SENDADDRV2\&. 
.SS "const char* SENDCMPCT {'sendcmpct'}\fR [inline]\fP, \fR [constexpr]\fP"
Contains a 1-byte bool and 8-byte LE version number\&. Indicates that a node is willing to provide blocks via "cmpctblock" messages\&. May indicate that a node prefers to receive new block announcements via a "cmpctblock" message rather than an "inv", depending on message contents\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70014 as described by BIP 152 
.RE
.PP

.SS "const char* SENDHEADERS {'sendheaders'}\fR [inline]\fP, \fR [constexpr]\fP"
Indicates that a node prefers to receive new block announcements via a "headers" message rather than an "inv"\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70012 as described by BIP130\&. 
.RE
.PP

.SS "const char* SENDTXRCNCL {'sendtxrcncl'}\fR [inline]\fP, \fR [constexpr]\fP"
Contains a 4-byte version number and an 8-byte salt\&. The salt is used to compute short txids needed for efficient txreconciliation, as described by BIP 330\&. 
.SS "const char* TX {'tx'}\fR [inline]\fP, \fR [constexpr]\fP"
The tx message transmits a single transaction\&. 
.SS "const char* VERACK {'verack'}\fR [inline]\fP, \fR [constexpr]\fP"
The verack message acknowledges a previously-received version message, informing the connecting node that it can begin to send other messages\&. 
.SS "const char* VERSION {'version'}\fR [inline]\fP, \fR [constexpr]\fP"
The version message provides information about the transmitting node to the receiving node at the beginning of a connection\&. 
.SS "const char* WTXIDRELAY {'wtxidrelay'}\fR [inline]\fP, \fR [constexpr]\fP"
Indicates that a node prefers to relay transactions via wtxid, rather than txid\&. 
.PP
\fBSince\fP
.RS 4
protocol version 70016 as described by BIP 339\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
