.TH "NetPermissions" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetPermissions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <net_permissions\&.h>\fP
.PP
Inherited by \fBNetWhitebindPermissions\fP, and \fBNetWhitelistPermissions\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::vector< std::string > \fBToStrings\fP (\fBNetPermissionFlags\fP \fBflags\fP)"
.br
.ti -1c
.RI "static bool \fBHasFlag\fP (\fBNetPermissionFlags\fP \fBflags\fP, \fBNetPermissionFlags\fP f)"
.br
.ti -1c
.RI "static void \fBAddFlag\fP (\fBNetPermissionFlags\fP &\fBflags\fP, \fBNetPermissionFlags\fP f)"
.br
.ti -1c
.RI "static void \fBClearFlag\fP (\fBNetPermissionFlags\fP &\fBflags\fP, \fBNetPermissionFlags\fP f)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBNetPermissionFlags\fP \fBm_flags\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AddFlag (\fBNetPermissionFlags\fP & flags, \fBNetPermissionFlags\fP f)\fR [inline]\fP, \fR [static]\fP"

.SS "void ClearFlag (\fBNetPermissionFlags\fP & flags, \fBNetPermissionFlags\fP f)\fR [inline]\fP, \fR [static]\fP"
ClearFlag is only called with \fRf\fP == \fBNetPermissionFlags::Implicit\fP\&. If that should change in the future, be aware that ClearFlag should not be called with a subflag of a multiflag, e\&.g\&. \fBNetPermissionFlags::Relay\fP or \fBNetPermissionFlags::Download\fP, as that would leave \fR\fBflags\fP\fP in an invalid state corresponding to none of the existing flags\&. 
.SS "bool HasFlag (\fBNetPermissionFlags\fP flags, \fBNetPermissionFlags\fP f)\fR [inline]\fP, \fR [static]\fP"

.SS "std::vector< std::string > ToStrings (\fBNetPermissionFlags\fP flags)\fR [static]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBNetPermissionFlags\fP m_flags"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
