.TH "NetworkDisable" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetworkDisable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetworkDisable\fP (\fBCConnman\fP &connman)"
.br
.ti -1c
.RI "\fB~NetworkDisable\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
RAII class that disables the network in its constructor and enables it in its destructor\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNetworkDisable\fP (\fBCConnman\fP & connman)\fR [inline]\fP"

.SS "~\fBNetworkDisable\fP ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
