.TH "NetworkStyle" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetworkStyle
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <networkstyle\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const QString & \fBgetAppName\fP () const"
.br
.ti -1c
.RI "const QIcon & \fBgetAppIcon\fP () const"
.br
.ti -1c
.RI "const QIcon & \fBgetTrayAndWindowIcon\fP () const"
.br
.ti -1c
.RI "const QString & \fBgetTitleAddText\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBNetworkStyle\fP * \fBinstantiate\fP (const \fBChainType\fP \fBnetworkId\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "const QIcon & getAppIcon () const\fR [inline]\fP"

.SS "const QString & getAppName () const\fR [inline]\fP"

.SS "const QString & getTitleAddText () const\fR [inline]\fP"

.SS "const QIcon & getTrayAndWindowIcon () const\fR [inline]\fP"

.SS "const \fBNetworkStyle\fP * instantiate (const \fBChainType\fP networkId)\fR [static]\fP"
Get style associated with provided network id, or 0 if not known 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
