.TH "src/qt/networkstyle.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/networkstyle.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/networkstyle\&.h>\fP
.br
\fR#include <qt/guiconstants\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <QApplication>\fP
.br

.SH "Variable Documentation"
.PP 
.SS "const char* appName"

.SS "const int iconColorHueShift"

.SS "const int iconColorSaturationReduction"

.SS "const \fBChainType\fP networkId"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
