.TH "NewMempoolTransactionInfo" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewMempoolTransactionInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mempool_entry\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewMempoolTransactionInfo\fP (const \fBCTransactionRef\fP &tx, const \fBCAmount\fP &\fBfee\fP, const int64_t vsize, const unsigned int height, const bool mempool_limit_bypassed, const bool submitted_in_package, const bool chainstate_is_current, const bool has_no_mempool_parents)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTransactionInfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "const bool \fBm_mempool_limit_bypassed\fP"
.br
.ti -1c
.RI "const bool \fBm_submitted_in_package\fP"
.br
.ti -1c
.RI "const bool \fBm_chainstate_is_current\fP"
.br
.ti -1c
.RI "const bool \fBm_has_no_mempool_parents\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNewMempoolTransactionInfo\fP (const \fBCTransactionRef\fP & tx, const \fBCAmount\fP & fee, const int64_t vsize, const unsigned int height, const bool mempool_limit_bypassed, const bool submitted_in_package, const bool chainstate_is_current, const bool has_no_mempool_parents)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBTransactionInfo\fP info"

.SS "const bool m_chainstate_is_current"

.SS "const bool m_has_no_mempool_parents"

.SS "const bool m_mempool_limit_bypassed"

.SS "const bool m_submitted_in_package"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
