.TH "TxDownloadManagerImpl::PeerInfo" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxDownloadManagerImpl::PeerInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <txdownloadman_impl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPeerInfo\fP (const \fBTxDownloadConnectionInfo\fP &info)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBTxDownloadConnectionInfo\fP \fBm_connection_info\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PeerInfo (const \fBTxDownloadConnectionInfo\fP & info)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "const \fBTxDownloadConnectionInfo\fP m_connection_info"
Information relevant to scheduling tx requests\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
