.TH "CacheSizes" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CacheSizes
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <caches\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIndexCacheSizes\fP \fBindex\fP"
.br
.ti -1c
.RI "\fBkernel::CacheSizes\fP \fBkernel\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBIndexCacheSizes\fP index"

.SS "\fBkernel::CacheSizes\fP kernel"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
