.TH "PSBTInputAnalysis" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSBTInputAnalysis
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <psbt\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBhas_utxo\fP"
.br
.RI "Whether we have UTXO information for this input\&. "
.ti -1c
.RI "bool \fBis_final\fP"
.br
.RI "Whether the input has all required information including signatures\&. "
.ti -1c
.RI "\fBPSBTRole\fP \fBnext\fP"
.br
.RI "Which of the BIP 174 roles needs to handle this input next\&. "
.ti -1c
.RI "std::vector< \fBCKeyID\fP > \fBmissing_pubkeys\fP"
.br
.RI "Pubkeys whose BIP32 derivation path is missing\&. "
.ti -1c
.RI "std::vector< \fBCKeyID\fP > \fBmissing_sigs\fP"
.br
.RI "Pubkeys whose signatures are missing\&. "
.ti -1c
.RI "\fBuint160\fP \fBmissing_redeem_script\fP"
.br
.RI "Hash160 of redeem script, if missing\&. "
.ti -1c
.RI "\fBuint256\fP \fBmissing_witness_script\fP"
.br
.RI "SHA256 of witness script, if missing\&. "
.in -1c
.SH "Detailed Description"
.PP 
Holds an analysis of one input from a PSBT 
.SH "Field Documentation"
.PP 
.SS "bool has_utxo"

.PP
Whether we have UTXO information for this input\&. 
.SS "bool is_final"

.PP
Whether the input has all required information including signatures\&. 
.SS "std::vector<\fBCKeyID\fP> missing_pubkeys"

.PP
Pubkeys whose BIP32 derivation path is missing\&. 
.SS "\fBuint160\fP missing_redeem_script"

.PP
Hash160 of redeem script, if missing\&. 
.SS "std::vector<\fBCKeyID\fP> missing_sigs"

.PP
Pubkeys whose signatures are missing\&. 
.SS "\fBuint256\fP missing_witness_script"

.PP
SHA256 of witness script, if missing\&. 
.SS "\fBPSBTRole\fP next"

.PP
Which of the BIP 174 roles needs to handle this input next\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
