.TH "TxDownloadConnectionInfo" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxDownloadConnectionInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <txdownloadman\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const bool \fBm_preferred\fP"
.br
.ti -1c
.RI "const bool \fBm_relay_permissions\fP"
.br
.ti -1c
.RI "const bool \fBm_wtxid_relay\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const bool m_preferred"
Whether this peer is preferred for transaction download\&. 
.SS "const bool m_relay_permissions"
Whether this peer has Relay permissions\&. 
.SS "const bool m_wtxid_relay"
Whether this peer supports wtxid relay\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
