.TH "RejectedTxTodo" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RejectedTxTodo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <txdownloadman\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBm_should_add_extra_compact_tx\fP"
.br
.ti -1c
.RI "std::vector< \fBTxid\fP > \fBm_unique_parents\fP"
.br
.ti -1c
.RI "std::optional< \fBPackageToValidate\fP > \fBm_package_to_validate\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "std::optional<\fBPackageToValidate\fP> m_package_to_validate"

.SS "bool m_should_add_extra_compact_tx"

.SS "std::vector<\fBTxid\fP> m_unique_parents"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
