.TH "CBlockIndexWorkComparator" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBlockIndexWorkComparator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <blockstorage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCBlockIndex\fP *pa, const \fBCBlockIndex\fP *pb) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool operator() (const \fBCBlockIndex\fP * pa, const \fBCBlockIndex\fP * pb) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
