.TH "MiniMinerMempoolEntry" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MiniMinerMempoolEntry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mini_miner\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMiniMinerMempoolEntry\fP (const \fBCTransactionRef\fP &tx_in, int64_t vsize_self, int64_t vsize_ancestor, \fBCAmount\fP fee_self, \fBCAmount\fP fee_ancestor)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetModifiedFee\fP () const"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetModFeesWithAncestors\fP () const"
.br
.ti -1c
.RI "int64_t \fBGetTxSize\fP () const"
.br
.ti -1c
.RI "int64_t \fBGetSizeWithAncestors\fP () const"
.br
.ti -1c
.RI "const \fBCTransaction\fP & \fBGetTx\fP () const \fBLIFETIMEBOUND\fP"
.br
.ti -1c
.RI "void \fBUpdateAncestorState\fP (int64_t vsize_change, \fBCAmount\fP fee_change)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MiniMinerMempoolEntry (const \fBCTransactionRef\fP & tx_in, int64_t vsize_self, int64_t vsize_ancestor, \fBCAmount\fP fee_self, \fBCAmount\fP fee_ancestor)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBCAmount\fP GetModFeesWithAncestors () const\fR [inline]\fP"

.SS "\fBCAmount\fP GetModifiedFee () const\fR [inline]\fP"

.SS "int64_t GetSizeWithAncestors () const\fR [inline]\fP"

.SS "const \fBCTransaction\fP & GetTx () const\fR [inline]\fP"

.SS "int64_t GetTxSize () const\fR [inline]\fP"

.SS "void UpdateAncestorState (int64_t vsize_change, \fBCAmount\fP fee_change)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
