.TH "src/test/node_warnings_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/node_warnings_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/warnings\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (warnings)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (warnings )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
