.TH "NodeEvictionCandidate" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeEvictionCandidate
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <eviction\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBNodeId\fP \fBid\fP"
.br
.ti -1c
.RI "std::chrono::seconds \fBm_connected\fP"
.br
.ti -1c
.RI "std::chrono::microseconds \fBm_min_ping_time\fP"
.br
.ti -1c
.RI "std::chrono::seconds \fBm_last_block_time\fP"
.br
.ti -1c
.RI "std::chrono::seconds \fBm_last_tx_time\fP"
.br
.ti -1c
.RI "bool \fBfRelevantServices\fP"
.br
.ti -1c
.RI "bool \fBm_relay_txs\fP"
.br
.ti -1c
.RI "bool \fBfBloomFilter\fP"
.br
.ti -1c
.RI "uint64_t \fBnKeyedNetGroup\fP"
.br
.ti -1c
.RI "bool \fBprefer_evict\fP"
.br
.ti -1c
.RI "bool \fBm_is_local\fP"
.br
.ti -1c
.RI "\fBNetwork\fP \fBm_network\fP"
.br
.ti -1c
.RI "bool \fBm_noban\fP"
.br
.ti -1c
.RI "\fBConnectionType\fP \fBm_conn_type\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool fBloomFilter"

.SS "bool fRelevantServices"

.SS "\fBNodeId\fP id"

.SS "\fBConnectionType\fP m_conn_type"

.SS "std::chrono::seconds m_connected"

.SS "bool m_is_local"

.SS "std::chrono::seconds m_last_block_time"

.SS "std::chrono::seconds m_last_tx_time"

.SS "std::chrono::microseconds m_min_ping_time"

.SS "\fBNetwork\fP m_network"

.SS "bool m_noban"

.SS "bool m_relay_txs"

.SS "uint64_t nKeyedNetGroup"

.SS "bool prefer_evict"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
