.TH "BlockAssembler" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockAssembler
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <miner\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBOptions\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockAssembler\fP (\fBChainstate\fP &chainstate, const \fBCTxMemPool\fP *mempool, const \fBOptions\fP &options)"
.br
.ti -1c
.RI "std::unique_ptr< \fBCBlockTemplate\fP > \fBCreateNewBlock\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::optional< int64_t > \fBm_last_block_num_txs\fP {}"
.br
.ti -1c
.RI "static std::optional< int64_t > \fBm_last_block_weight\fP {}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generate a new block, without valid proof-of-work 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBlockAssembler\fP (\fBChainstate\fP & chainstate, const \fBCTxMemPool\fP * mempool, const \fBOptions\fP & options)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::unique_ptr< \fBCBlockTemplate\fP > CreateNewBlock ()"
Construct a new block template 
.SH "Field Documentation"
.PP 
.SS "std::optional<int64_t> m_last_block_num_txs {}\fR [inline]\fP, \fR [static]\fP"
The number of transactions in the last assembled block (excluding coinbase transaction) 
.SS "std::optional<int64_t> m_last_block_weight {}\fR [inline]\fP, \fR [static]\fP"
The weight of the last assembled block (including reserved weight for block header, txs count and coinbase tx) 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
