.TH "TxOrphanage::OrphanInfo" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxOrphanage::OrphanInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <txorphanage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrphanInfo\fP (\fBCTransactionRef\fP \fBtx\fP, std::set< \fBNodeId\fP > &&\fBannouncers\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCTransactionRef\fP \fBtx\fP"
.br
.ti -1c
.RI "std::set< \fBNodeId\fP > \fBannouncers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows providing orphan information externally 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OrphanInfo (\fBCTransactionRef\fP tx, std::set< \fBNodeId\fP > && announcers)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::set<\fBNodeId\fP> announcers"
Peers added with AddTx or AddAnnouncer\&. 
.SS "\fBCTransactionRef\fP tx"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
