.TH "BlockTreeDB" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockTreeDB
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <blockstorage\&.h>\fP
.PP
Inherits \fBCDBWrapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWriteBatchSync\fP (const std::vector< std::pair< int, const \fBCBlockFileInfo\fP * > > &fileInfo, int nLastFile, const std::vector< const \fBCBlockIndex\fP * > &blockinfo)"
.br
.ti -1c
.RI "bool \fBReadBlockFileInfo\fP (int nFile, \fBCBlockFileInfo\fP &info)"
.br
.ti -1c
.RI "bool \fBReadLastBlockFile\fP (int &nFile)"
.br
.ti -1c
.RI "void \fBWriteReindexing\fP (bool fReindexing)"
.br
.ti -1c
.RI "void \fBReadReindexing\fP (bool &fReindexing)"
.br
.ti -1c
.RI "void \fBWriteFlag\fP (const std::string &\fBname\fP, bool fValue)"
.br
.ti -1c
.RI "bool \fBReadFlag\fP (const std::string &\fBname\fP, bool &fValue)"
.br
.ti -1c
.RI "\fBCDBWrapper\fP (const \fBDBParams\fP &params)"
.br
.ti -1c
.RI "\fBCDBWrapper\fP (const \fBCDBWrapper\fP &)=delete"
.br
.in -1c

Public Member Functions inherited from \fBCDBWrapper\fP
.in +1c
.ti -1c
.RI "\fBCDBWrapper\fP (const \fBDBParams\fP &params)"
.br
.ti -1c
.RI "\fB~CDBWrapper\fP ()"
.br
.ti -1c
.RI "\fBCDBWrapper\fP (const \fBCDBWrapper\fP &)=delete"
.br
.ti -1c
.RI "\fBCDBWrapper\fP & \fBoperator=\fP (const \fBCDBWrapper\fP &)=delete"
.br
.ti -1c
.RI "template<typename K, typename V> bool \fBRead\fP (const K &key, V &value) const"
.br
.ti -1c
.RI "template<typename K, typename V> void \fBWrite\fP (const K &key, const V &value, bool fSync=false)"
.br
.ti -1c
.RI "template<typename K> bool \fBExists\fP (const K &key) const"
.br
.ti -1c
.RI "template<typename K> void \fBErase\fP (const K &key, bool fSync=false)"
.br
.ti -1c
.RI "void \fBWriteBatch\fP (\fBCDBBatch\fP &batch, bool fSync=false)"
.br
.ti -1c
.RI "size_t \fBDynamicMemoryUsage\fP () const"
.br
.ti -1c
.RI "\fBCDBIterator\fP * \fBNewIterator\fP ()"
.br
.ti -1c
.RI "bool \fBIsEmpty\fP ()"
.br
.ti -1c
.RI "template<typename K> size_t \fBEstimateSize\fP (const K &key_begin, const K &key_end) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Access to the block database (blocks/index/) 
.SH "Member Function Documentation"
.PP 
.SS "\fBCDBWrapper\fP (const \fBCDBWrapper\fP & )\fR [delete]\fP"

.SS "\fBCDBWrapper\fP (const \fBDBParams\fP & params)"

.SS "bool ReadBlockFileInfo (int nFile, \fBCBlockFileInfo\fP & info)"

.SS "bool ReadFlag (const std::string & name, bool & fValue)"

.SS "bool ReadLastBlockFile (int & nFile)"

.SS "void ReadReindexing (bool & fReindexing)"

.SS "void WriteBatchSync (const std::vector< std::pair< int, const \fBCBlockFileInfo\fP * > > & fileInfo, int nLastFile, const std::vector< const \fBCBlockIndex\fP * > & blockinfo)"

.SS "void WriteFlag (const std::string & name, bool fValue)"

.SS "void WriteReindexing (bool fReindexing)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
