.TH "IndexCacheSizes" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexCacheSizes
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <caches\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBtx_index\fP {0}"
.br
.ti -1c
.RI "size_t \fBfilter_index\fP {0}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t filter_index {0}"

.SS "size_t tx_index {0}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
