.TH "SnapshotMetadata" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SnapshotMetadata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <utxo_snapshot\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSnapshotMetadata\fP (const \fBMessageStartChars\fP network_magic)"
.br
.ti -1c
.RI "\fBSnapshotMetadata\fP (const \fBMessageStartChars\fP network_magic, const \fBuint256\fP &base_blockhash, uint64_t coins_count)"
.br
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBm_base_blockhash\fP"
.br
.ti -1c
.RI "uint64_t \fBm_coins_count\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Metadata describing a serialized version of a UTXO set from which an assumeutxo \fBChainstate\fP can be constructed\&. All metadata fields come from an untrusted file, so must be validated before being used\&. Thus, new fields should be added only if needed\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSnapshotMetadata\fP (const \fBMessageStartChars\fP network_magic)\fR [inline]\fP"

.SS "\fBSnapshotMetadata\fP (const \fBMessageStartChars\fP network_magic, const \fBuint256\fP & base_blockhash, uint64_t coins_count)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream> void Serialize (Stream & s) const\fR [inline]\fP"

.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP m_base_blockhash"
The hash of the block that reflects the tip of the chain for the UTXO set contained in this snapshot\&. 
.SS "uint64_t m_coins_count = 0"
The number of coins in the UTXO set contained in this snapshot\&. Used during snapshot load to estimate progress of UTXO set reconstruction\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
