.TH "src/test/node_init_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/node_init_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <init\&.h>\fP
.br
\fR#include <interfaces/init\&.h>\fP
.br
\fR#include <rpc/server\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBInitTestSetup\fP"
.br
.RI "Like \fBBasicTestingSetup\fP, but using regtest network instead of mainnet\&. "
.ti -1c
.RI "class \fBTestInit\fP"
.br
.RI "Remote init class\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (init_test)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (init_test )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
