.TH "BlockfileCursor" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockfileCursor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <blockstorage\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfile_num\fP {0}"
.br
.ti -1c
.RI "int \fBundo_height\fP {0}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int file_num {0}"

.SS "int undo_height {0}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
