.TH "NonFatalCheckError" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NonFatalCheckError
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <check\&.h>\fP
.PP
Inherits runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNonFatalCheckError\fP (std::string_view msg, const std::source_location &loc)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNonFatalCheckError\fP (std::string_view msg, const std::source_location & loc)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
