.TH "nontrivial_t" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nontrivial_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnontrivial_t\fP ()=default"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBnontrivial_t\fP, obj)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP {\-1}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBnontrivial_t\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "SERIALIZE_METHODS (\fBnontrivial_t\fP , obj )\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "int x {\-1}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
