.TH "src/qt/notificator.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/notificator.h
.SH SYNOPSIS
.br
.PP
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <QIcon>\fP
.br
\fR#include <QObject>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBNotificator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
