.TH "src/kernel/notifications_interface.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kernel/notifications_interface.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br
\fR#include <variant>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBInterrupted\fP"
.br
.RI "Result type for use with std::variant to indicate that an operation should be interrupted\&. "
.ti -1c
.RI "class \fBNotifications\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBkernel\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBInterruptResult\fP = std::variant<std::monostate, \fBInterrupted\fP>"
.br
.RI "Simple result type for functions that need to propagate an interrupt status and don't have other return values\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP> bool \fBIsInterrupted\fP (const \fBT\fP &result)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
