.TH "src/noui.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/noui.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <noui\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <node/interface_ui\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include <boost/signals2/connection\&.hpp>\fP
.br
\fR#include <boost/signals2/signal\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBnoui_ThreadSafeMessageBox\fP (const \fBbilingual_str\fP &message, const std::string &caption, unsigned int style)"
.br
.ti -1c
.RI "bool \fBnoui_ThreadSafeQuestion\fP (const \fBbilingual_str\fP &, const std::string &message, const std::string &caption, unsigned int style)"
.br
.ti -1c
.RI "void \fBnoui_InitMessage\fP (const std::string &message)"
.br
.ti -1c
.RI "void \fBnoui_connect\fP ()"
.br
.ti -1c
.RI "bool \fBnoui_ThreadSafeMessageBoxRedirect\fP (const \fBbilingual_str\fP &message, const std::string &caption, unsigned int style)"
.br
.ti -1c
.RI "bool \fBnoui_ThreadSafeQuestionRedirect\fP (const \fBbilingual_str\fP &, const std::string &message, const std::string &caption, unsigned int style)"
.br
.ti -1c
.RI "void \fBnoui_InitMessageRedirect\fP (const std::string &message)"
.br
.ti -1c
.RI "void \fBnoui_test_redirect\fP ()"
.br
.ti -1c
.RI "void \fBnoui_reconnect\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "boost::signals2::connection \fBnoui_ThreadSafeMessageBoxConn\fP"
.br
.ti -1c
.RI "boost::signals2::connection \fBnoui_ThreadSafeQuestionConn\fP"
.br
.ti -1c
.RI "boost::signals2::connection \fBnoui_InitMessageConn\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void noui_connect ()"
Connect all bitcoind signal handlers 
.SS "void noui_InitMessage (const std::string & message)"
Non-GUI handler, which only logs a message\&. 
.SS "void noui_InitMessageRedirect (const std::string & message)"

.SS "void noui_reconnect ()"
Reconnects the regular Non-GUI handlers after having used noui_test_redirect 
.SS "void noui_test_redirect ()"
Redirect all bitcoind signal handlers to LogInfo\&. Used to check or suppress output during test runs that produce expected errors 
.SS "bool noui_ThreadSafeMessageBox (const \fBbilingual_str\fP & message, const std::string & caption, unsigned int style)"
Non-GUI handler, which logs and prints messages\&. 
.SS "bool noui_ThreadSafeMessageBoxRedirect (const \fBbilingual_str\fP & message, const std::string & caption, unsigned int style)"

.SS "bool noui_ThreadSafeQuestion (const \fBbilingual_str\fP & , const std::string & message, const std::string & caption, unsigned int style)"
Non-GUI handler, which logs and prints questions\&. 
.SS "bool noui_ThreadSafeQuestionRedirect (const \fBbilingual_str\fP & , const std::string & message, const std::string & caption, unsigned int style)"

.SH "Variable Documentation"
.PP 
.SS "boost::signals2::connection noui_InitMessageConn"

.SS "boost::signals2::connection noui_ThreadSafeMessageBoxConn"
Store connections so we can disconnect them when suppressing output 
.SS "boost::signals2::connection noui_ThreadSafeQuestionConn"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
