.TH "src/noui.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/noui.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBnoui_ThreadSafeMessageBox\fP (const \fBbilingual_str\fP &message, const std::string &caption, unsigned int style)"
.br
.ti -1c
.RI "bool \fBnoui_ThreadSafeQuestion\fP (const \fBbilingual_str\fP &, const std::string &message, const std::string &caption, unsigned int style)"
.br
.ti -1c
.RI "void \fBnoui_InitMessage\fP (const std::string &message)"
.br
.ti -1c
.RI "void \fBnoui_connect\fP ()"
.br
.ti -1c
.RI "void \fBnoui_test_redirect\fP ()"
.br
.ti -1c
.RI "void \fBnoui_reconnect\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void noui_connect ()"
Connect all bitcoind signal handlers 
.SS "void noui_InitMessage (const std::string & message)"
Non-GUI handler, which only logs a message\&. 
.SS "void noui_reconnect ()"
Reconnects the regular Non-GUI handlers after having used noui_test_redirect 
.SS "void noui_test_redirect ()"
Redirect all bitcoind signal handlers to LogInfo\&. Used to check or suppress output during test runs that produce expected errors 
.SS "bool noui_ThreadSafeMessageBox (const \fBbilingual_str\fP & message, const std::string & caption, unsigned int style)"
Non-GUI handler, which logs and prints messages\&. 
.SS "bool noui_ThreadSafeQuestion (const \fBbilingual_str\fP & , const std::string & message, const std::string & caption, unsigned int style)"
Non-GUI handler, which logs and prints questions\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
