.TH "Num< N >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Num< N >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lintrans\&.h>\fP
.SH "Detailed Description"
.PP 

.SS "template<int N>
.br
struct Num< N >"A type to represent integers in the type system\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
