.TH "src/univalue/test/object.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/univalue/test/object.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <univalue\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <map>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include <vector>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBOOST_CHECK\fP(expr)"
.br
.ti -1c
.RI "#define \fBBOOST_CHECK_EQUAL\fP(v1,  v2)"
.br
.ti -1c
.RI "#define \fBBOOST_CHECK_THROW\fP(stmt,  excMatch)"
.br
.ti -1c
.RI "#define \fBBOOST_CHECK_NO_THROW\fP(stmt)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBunivalue_constructor\fP ()"
.br
.ti -1c
.RI "void \fBunivalue_push_throw\fP ()"
.br
.ti -1c
.RI "void \fBunivalue_typecheck\fP ()"
.br
.ti -1c
.RI "void \fBunivalue_set\fP ()"
.br
.ti -1c
.RI "void \fBunivalue_array\fP ()"
.br
.ti -1c
.RI "void \fBunivalue_object\fP ()"
.br
.ti -1c
.RI "void \fBunivalue_readwrite\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BOOST_CHECK( expr)"
\fBValue:\fP
.nf
assert(expr)
.PP
.fi

.SS "#define BOOST_CHECK_EQUAL( v1,  v2)"
\fBValue:\fP
.nf
assert((v1) == (v2))
.PP
.fi

.SS "#define BOOST_CHECK_NO_THROW( stmt)"
\fBValue:\fP
.nf
        { \\
        try { \\
            (stmt); \\
        } catch (\&.\&.\&.) { \\
            assert(0); \\
        } \\
    }
.PP
.fi

.SS "#define BOOST_CHECK_THROW( stmt,  excMatch)"
\fBValue:\fP
.nf
        { \\
        try { \\
            (stmt); \\
            assert(0 && "No exception caught"); \\
        } catch (excMatch&) { \\
        } catch (\&.\&.\&.) { \\
            assert(0 && "Wrong exception caught"); \\
        } \\
    }
.PP
.fi

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SS "void univalue_array ()"

.SS "void univalue_constructor ()"

.SS "void univalue_object ()"

.SS "void univalue_push_throw ()"

.SS "void univalue_readwrite ()"

.SS "void univalue_set ()"

.SS "void univalue_typecheck ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
