.TH "src/qt/openuridialog.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/openuridialog.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/openuridialog\&.h>\fP
.br
\fR#include <qt/forms/ui_openuridialog\&.h>\fP
.br
\fR#include <qt/guiutil\&.h>\fP
.br
\fR#include <qt/platformstyle\&.h>\fP
.br
\fR#include <qt/sendcoinsrecipient\&.h>\fP
.br
\fR#include <QAbstractButton>\fP
.br
\fR#include <QLineEdit>\fP
.br
\fR#include <QUrl>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
