.TH "src/qt/test/optiontests.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/test/optiontests.h
.SH SYNOPSIS
.br
.PP
\fR#include <common/settings\&.h>\fP
.br
\fR#include <qt/optionsmodel\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <QObject>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBOptionTests\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
