.TH "src/qt/optionsmodel.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/optionsmodel.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <qt/optionsmodel\&.h>\fP
.br
\fR#include <qt/bitcoinunits\&.h>\fP
.br
\fR#include <qt/guiconstants\&.h>\fP
.br
\fR#include <qt/guiutil\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <interfaces/node\&.h>\fP
.br
\fR#include <mapport\&.h>\fP
.br
\fR#include <net\&.h>\fP
.br
\fR#include <netbase\&.h>\fP
.br
\fR#include <node/caches\&.h>\fP
.br
\fR#include <node/chainstatemanager_args\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <wallet/wallet\&.h>\fP
.br
\fR#include <QDebug>\fP
.br
\fR#include <QLatin1Char>\fP
.br
\fR#include <QSettings>\fP
.br
\fR#include <QStringList>\fP
.br
\fR#include <QVariant>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBProxySetting\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBDEFAULT_GUI_PROXY_HOST\fP = '127\&.0\&.0\&.1'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* DEFAULT_GUI_PROXY_HOST = '127\&.0\&.0\&.1'"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
