.TH "OptionsModel" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionsModel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <optionsmodel\&.h>\fP
.PP
Inherits QAbstractListModel\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBOptionID\fP { \fBStartAtStartup\fP, \fBShowTrayIcon\fP, \fBMinimizeToTray\fP, \fBMapPortNatpmp\fP, \fBMinimizeOnClose\fP, \fBProxyUse\fP, \fBProxyIP\fP, \fBProxyPort\fP, \fBProxyUseTor\fP, \fBProxyIPTor\fP, \fBProxyPortTor\fP, \fBDisplayUnit\fP, \fBThirdPartyTxUrls\fP, \fBLanguage\fP, \fBFontForMoney\fP, \fBCoinControlFeatures\fP, \fBSubFeeFromAmount\fP, \fBThreadsScriptVerif\fP, \fBPrune\fP, \fBPruneSize\fP, \fBDatabaseCache\fP, \fBExternalSignerPath\fP, \fBSpendZeroConfChange\fP, \fBListen\fP, \fBServer\fP, \fBEnablePSBTControls\fP, \fBMaskValues\fP, \fBOptionIDRowCount\fP }"
.br
.ti -1c
.RI "enum class \fBFontChoiceAbstract\fP { \fBEmbeddedFont\fP, \fBBestSystemFont\fP }"
.br
.ti -1c
.RI "typedef std::variant< \fBFontChoiceAbstract\fP, QFont > \fBFontChoice\fP"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdisplayUnitChanged\fP (\fBBitcoinUnit\fP unit)"
.br
.ti -1c
.RI "void \fBcoinControlFeaturesChanged\fP (bool)"
.br
.ti -1c
.RI "void \fBshowTrayIconChanged\fP (bool)"
.br
.ti -1c
.RI "void \fBfontForMoneyChanged\fP (const QFont &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionsModel\fP (\fBinterfaces::Node\fP &\fBnode\fP, QObject *parent=nullptr)"
.br
.ti -1c
.RI "bool \fBInit\fP (\fBbilingual_str\fP &error)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent=QModelIndex()) const override"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role=Qt::DisplayRole) const override"
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override"
.br
.ti -1c
.RI "QVariant \fBgetOption\fP (\fBOptionID\fP option, const std::string &suffix='') const"
.br
.ti -1c
.RI "bool \fBsetOption\fP (\fBOptionID\fP option, const QVariant &value, const std::string &suffix='')"
.br
.ti -1c
.RI "void \fBsetDisplayUnit\fP (const QVariant &new_unit)"
.br
.ti -1c
.RI "bool \fBgetShowTrayIcon\fP () const"
.br
.ti -1c
.RI "bool \fBgetMinimizeToTray\fP () const"
.br
.ti -1c
.RI "bool \fBgetMinimizeOnClose\fP () const"
.br
.ti -1c
.RI "\fBBitcoinUnit\fP \fBgetDisplayUnit\fP () const"
.br
.ti -1c
.RI "QString \fBgetThirdPartyTxUrls\fP () const"
.br
.ti -1c
.RI "QFont \fBgetFontForMoney\fP () const"
.br
.ti -1c
.RI "bool \fBgetCoinControlFeatures\fP () const"
.br
.ti -1c
.RI "bool \fBgetSubFeeFromAmount\fP () const"
.br
.ti -1c
.RI "bool \fBgetEnablePSBTControls\fP () const"
.br
.ti -1c
.RI "const QString & \fBgetOverriddenByCommandLine\fP ()"
.br
.ti -1c
.RI "bool \fBhasSigner\fP ()"
.br
.ti -1c
.RI "void \fBSetPruneTargetGB\fP (int prune_target_gb)"
.br
.ti -1c
.RI "void \fBsetRestartRequired\fP (bool fRequired)"
.br
.ti -1c
.RI "bool \fBisRestartRequired\fP () const"
.br
.ti -1c
.RI "\fBinterfaces::Node\fP & \fBnode\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QFont \fBgetFontForChoice\fP (const \fBFontChoice\fP &fc)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBFontChoice\fP \fBUseBestSystemFont\fP {\fBFontChoiceAbstract::BestSystemFont\fP}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface from Qt to configuration data structure for Bitcoin client\&. To Qt, the options are presented as a list with the different options laid out vertically\&. This can be changed to a tree once the settings become sufficiently complex\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::variant<\fBFontChoiceAbstract\fP, QFont> \fBFontChoice\fP"

.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBFontChoiceAbstract\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIEmbeddedFont \fP
.TP
\f(BIBestSystemFont \fP
.SS "enum \fBOptionID\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIStartAtStartup \fP
.TP
\f(BIShowTrayIcon \fP
.TP
\f(BIMinimizeToTray \fP
.TP
\f(BIMapPortNatpmp \fP
.TP
\f(BIMinimizeOnClose \fP
.TP
\f(BIProxyUse \fP
.TP
\f(BIProxyIP \fP
.TP
\f(BIProxyPort \fP
.TP
\f(BIProxyUseTor \fP
.TP
\f(BIProxyIPTor \fP
.TP
\f(BIProxyPortTor \fP
.TP
\f(BIDisplayUnit \fP
.TP
\f(BIThirdPartyTxUrls \fP
.TP
\f(BILanguage \fP
.TP
\f(BIFontForMoney \fP
.TP
\f(BICoinControlFeatures \fP
.TP
\f(BISubFeeFromAmount \fP
.TP
\f(BIThreadsScriptVerif \fP
.TP
\f(BIPrune \fP
.TP
\f(BIPruneSize \fP
.TP
\f(BIDatabaseCache \fP
.TP
\f(BIExternalSignerPath \fP
.TP
\f(BISpendZeroConfChange \fP
.TP
\f(BIListen \fP
.TP
\f(BIServer \fP
.TP
\f(BIEnablePSBTControls \fP
.TP
\f(BIMaskValues \fP
.TP
\f(BIOptionIDRowCount \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBOptionsModel\fP (\fBinterfaces::Node\fP & node, QObject * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void coinControlFeaturesChanged (bool )\fR [signal]\fP"

.SS "QVariant data (const QModelIndex & index, int role = \fRQt::DisplayRole\fP) const\fR [override]\fP"

.SS "void displayUnitChanged (\fBBitcoinUnit\fP unit)\fR [signal]\fP"

.SS "void fontForMoneyChanged (const QFont & )\fR [signal]\fP"

.SS "bool getCoinControlFeatures () const\fR [inline]\fP"

.SS "\fBBitcoinUnit\fP getDisplayUnit () const\fR [inline]\fP"

.SS "bool getEnablePSBTControls () const\fR [inline]\fP"

.SS "QFont getFontForChoice (const \fBFontChoice\fP & fc)\fR [static]\fP"

.SS "QFont getFontForMoney () const"

.SS "bool getMinimizeOnClose () const\fR [inline]\fP"

.SS "bool getMinimizeToTray () const\fR [inline]\fP"

.SS "QVariant getOption (\fBOptionID\fP option, const std::string & suffix = \fR''\fP) const"

.SS "const QString & getOverriddenByCommandLine ()\fR [inline]\fP"

.SS "bool getShowTrayIcon () const\fR [inline]\fP"

.SS "bool getSubFeeFromAmount () const\fR [inline]\fP"

.SS "QString getThirdPartyTxUrls () const\fR [inline]\fP"

.SS "bool hasSigner ()"
Whether -signer was set or not 
.SS "bool \fBInit\fP (\fBbilingual_str\fP & error)"

.SS "bool isRestartRequired () const"

.SS "\fBinterfaces::Node\fP & node () const\fR [inline]\fP"

.SS "void Reset ()"

.SS "int rowCount (const QModelIndex & parent = \fRQModelIndex()\fP) const\fR [override]\fP"

.SS "bool setData (const QModelIndex & index, const QVariant & value, int role = \fRQt::EditRole\fP)\fR [override]\fP"

.SS "void setDisplayUnit (const QVariant & new_unit)"
Updates current unit in memory, settings and emits displayUnitChanged(new_unit) signal 
.SS "bool setOption (\fBOptionID\fP option, const QVariant & value, const std::string & suffix = \fR''\fP)"

.SS "void SetPruneTargetGB (int prune_target_gb)"

.SS "void setRestartRequired (bool fRequired)"

.SS "void showTrayIconChanged (bool )\fR [signal]\fP"

.SH "Field Documentation"
.PP 
.SS "const \fBFontChoice\fP UseBestSystemFont {\fBFontChoiceAbstract::BestSystemFont\fP}\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
