.TH "OptionsDialog" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionsDialog
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <optionsdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTab\fP { \fBTAB_MAIN\fP, \fBTAB_NETWORK\fP }"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBproxyIpChecks\fP (\fBQValidatedLineEdit\fP *pUiProxyIp, uint16_t nProxyPort)"
.br
.ti -1c
.RI "void \fBquitOnReset\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionsDialog\fP (QWidget *parent, bool enableWallet)"
.br
.ti -1c
.RI "\fB~OptionsDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetClientModel\fP (\fBClientModel\fP *client_model)"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBOptionsModel\fP *model)"
.br
.ti -1c
.RI "void \fBsetMapper\fP ()"
.br
.ti -1c
.RI "void \fBsetCurrentTab\fP (\fBOptionsDialog::Tab\fP tab)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Preferences dialog\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBTab\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BITAB_MAIN \fP
.TP
\f(BITAB_NETWORK \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBOptionsDialog\fP (QWidget * parent, bool enableWallet)\fR [explicit]\fP"
check if the locale name consists of 2 parts (language_country)

.PP
display language strings as "native language - native country/territory (locale name)", e\&.g\&. "Deutsch - Deutschland (de)"

.PP
display language strings as "native language (locale name)", e\&.g\&. "Deutsch (de)"
.SS "~\fBOptionsDialog\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void proxyIpChecks (\fBQValidatedLineEdit\fP * pUiProxyIp, uint16_t nProxyPort)\fR [signal]\fP"

.SS "void quitOnReset ()\fR [signal]\fP"

.SS "void setClientModel (\fBClientModel\fP * client_model)"

.SS "void setCurrentTab (\fBOptionsDialog::Tab\fP tab)"

.SS "void setMapper ()"

.SS "void setModel (\fBOptionsModel\fP * model)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
