.TH "OtherParamChecker" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OtherParamChecker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Checker for value of \fBOtherParam\fP\&. When being serialized, serializes the param to the stream\&. When being unserialized, verifies the value in the stream matches the param\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream> void Serialize (Stream & s) const\fR [inline]\fP"

.SS "template<typename Stream> void Unserialize (Stream & s) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
