.TH "src/outputtype.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/outputtype.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <outputtype\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <script/sign\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::optional< \fBOutputType\fP > \fBParseOutputType\fP (std::string_view type)"
.br
.ti -1c
.RI "const std::string & \fBFormatOutputType\fP (\fBOutputType\fP type)"
.br
.ti -1c
.RI "std::string \fBFormatAllOutputTypes\fP ()"
.br
.ti -1c
.RI "\fBCTxDestination\fP \fBAddAndGetDestinationForScript\fP (\fBFlatSigningProvider\fP &keystore, const \fBCScript\fP &\fBscript\fP, \fBOutputType\fP type)"
.br
.ti -1c
.RI "std::optional< \fBOutputType\fP > \fBOutputTypeFromDestination\fP (const \fBCTxDestination\fP &dest)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCTxDestination\fP AddAndGetDestinationForScript (\fBFlatSigningProvider\fP & keystore, const \fBCScript\fP & script, \fBOutputType\fP type)"
Get a destination of the requested type (if possible) to the specified script\&. This function will automatically add the script (and any other necessary scripts) to the keystore\&. 
.SS "std::string FormatAllOutputTypes ()"

.SS "const std::string & FormatOutputType (\fBOutputType\fP type)"

.SS "std::optional< \fBOutputType\fP > OutputTypeFromDestination (const \fBCTxDestination\fP & dest)"
Get the \fBOutputType\fP for a \fBCTxDestination\fP 
.SS "std::optional< \fBOutputType\fP > ParseOutputType (std::string_view type)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
