.TH "PackageValidationState" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PackageValidationState
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <packages\&.h>\fP
.PP
Inherits \fBValidationState< PackageValidationResult >\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBValidationState< PackageValidationResult >\fP
.in +1c
.ti -1c
.RI "bool \fBInvalid\fP (\fBPackageValidationResult\fP result, const std::string &reject_reason='', const std::string &debug_message='')"
.br
.ti -1c
.RI "bool \fBError\fP (const std::string &reject_reason)"
.br
.ti -1c
.RI "bool \fBIsValid\fP () const"
.br
.ti -1c
.RI "bool \fBIsInvalid\fP () const"
.br
.ti -1c
.RI "bool \fBIsError\fP () const"
.br
.ti -1c
.RI "\fBPackageValidationResult\fP \fBGetResult\fP () const"
.br
.ti -1c
.RI "std::string \fBGetRejectReason\fP () const"
.br
.ti -1c
.RI "std::string \fBGetDebugMessage\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
