.TH "src/consensus/params.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/consensus/params.h
.SH SYNOPSIS
.br
.PP
\fR#include <script/verify_flags\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <array>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <limits>\fP
.br
\fR#include <map>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBIP9Deployment\fP"
.br
.ti -1c
.RI "struct \fBParams\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBConsensus\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBuriedDeployment\fP : int16_t { \fBDEPLOYMENT_HEIGHTINCB\fP = std::numeric_limits<int16_t>::min(), \fBDEPLOYMENT_CLTV\fP, \fBDEPLOYMENT_DERSIG\fP, \fBDEPLOYMENT_CSV\fP, \fBDEPLOYMENT_SEGWIT\fP }"
.br
.ti -1c
.RI "enum \fBDeploymentPos\fP : uint16_t { \fBDEPLOYMENT_TESTDUMMY\fP, \fBDEPLOYMENT_TAPROOT\fP, \fBMAX_VERSION_BITS_DEPLOYMENTS\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr bool \fBValidDeployment\fP (\fBBuriedDeployment\fP dep)"
.br
.ti -1c
.RI "constexpr bool \fBValidDeployment\fP (\fBDeploymentPos\fP dep)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
