.TH "src/script/parsing.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/script/parsing.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <script/parsing\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscript\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBConst\fP (const std::string &str, std::span< const char > &sp, bool skip)"
.br
.ti -1c
.RI "bool \fBFunc\fP (const std::string &str, std::span< const char > &sp)"
.br
.ti -1c
.RI "std::span< const char > \fBExpr\fP (std::span< const char > &sp)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
