.TH "src/bench/parse_hex.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bench/parse_hex.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bench/bench\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBgenerateHexString\fP (size_t length)"
.br
.ti -1c
.RI "\fBBENCHMARK\fP (HexParse, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BENCHMARK (HexParse , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SS "std::string generateHexString (size_t length)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
