.TH "PartiallySignedTransaction" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartiallySignedTransaction
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <psbt\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsNull\fP () const"
.br
.ti -1c
.RI "uint32_t \fBGetVersion\fP () const"
.br
.ti -1c
.RI "bool \fBMerge\fP (const \fBPartiallySignedTransaction\fP &psbt)"
.br
.ti -1c
.RI "bool \fBAddInput\fP (const \fBCTxIn\fP &txin, \fBPSBTInput\fP &psbtin)"
.br
.ti -1c
.RI "bool \fBAddOutput\fP (const \fBCTxOut\fP &txout, const \fBPSBTOutput\fP &psbtout)"
.br
.ti -1c
.RI "\fBPartiallySignedTransaction\fP ()=default"
.br
.ti -1c
.RI "\fBPartiallySignedTransaction\fP (const \fBCMutableTransaction\fP &\fBtx\fP)"
.br
.ti -1c
.RI "bool \fBGetInputUTXO\fP (\fBCTxOut\fP &utxo, int input_index) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.ti -1c
.RI "template<typename Stream> \fBPartiallySignedTransaction\fP (\fBdeserialize_type\fP, Stream &s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::optional< \fBCMutableTransaction\fP > \fBtx\fP"
.br
.ti -1c
.RI "std::map< \fBKeyOriginInfo\fP, std::set< \fBCExtPubKey\fP > > \fBm_xpubs\fP"
.br
.ti -1c
.RI "std::vector< \fBPSBTInput\fP > \fBinputs\fP"
.br
.ti -1c
.RI "std::vector< \fBPSBTOutput\fP > \fBoutputs\fP"
.br
.ti -1c
.RI "std::map< std::vector< unsigned char >, std::vector< unsigned char > > \fBunknown\fP"
.br
.ti -1c
.RI "std::optional< uint32_t > \fBm_version\fP"
.br
.ti -1c
.RI "std::set< \fBPSBTProprietary\fP > \fBm_proprietary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A version of \fBCTransaction\fP with the PSBT format 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPartiallySignedTransaction\fP ()\fR [default]\fP"

.SS "\fBPartiallySignedTransaction\fP (const \fBCMutableTransaction\fP & tx)\fR [explicit]\fP"

.SS "template<typename Stream> \fBPartiallySignedTransaction\fP (\fBdeserialize_type\fP , Stream & s)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool AddInput (const \fBCTxIn\fP & txin, \fBPSBTInput\fP & psbtin)"

.SS "bool AddOutput (const \fBCTxOut\fP & txout, const \fBPSBTOutput\fP & psbtout)"

.SS "bool GetInputUTXO (\fBCTxOut\fP & utxo, int input_index) const"
Finds the UTXO for a given input index

.PP
\fBParameters\fP
.RS 4
\fIutxo\fP The UTXO of the input if found 
.br
\fIinput_index\fP Index of the input to retrieve the UTXO of 
.RE
.PP
\fBReturns\fP
.RS 4
Whether the UTXO for the specified input was found 
.RE
.PP

.SS "uint32_t GetVersion () const"

.SS "bool IsNull () const"

.SS "bool Merge (const \fBPartiallySignedTransaction\fP & psbt)\fR [nodiscard]\fP"
Merge psbt into this\&. The two psbts must have the same underlying \fBCTransaction\fP (i\&.e\&. the same actual Bitcoin transaction\&.) Returns true if the merge succeeded, false otherwise\&. 
.SS "template<typename Stream> void Serialize (Stream & s) const\fR [inline]\fP"

.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::vector<\fBPSBTInput\fP> inputs"

.SS "std::set<\fBPSBTProprietary\fP> m_proprietary"

.SS "std::optional<uint32_t> m_version"

.SS "std::map<\fBKeyOriginInfo\fP, std::set<\fBCExtPubKey\fP> > m_xpubs"

.SS "std::vector<\fBPSBTOutput\fP> outputs"

.SS "std::optional<\fBCMutableTransaction\fP> tx"

.SS "std::map<std::vector<unsigned char>, std::vector<unsigned char> > unknown"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
