.TH "PartiallyDownloadedBlock" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartiallyDownloadedBlock
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <blockencodings\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBIsBlockMutatedFn\fP = std::function<bool(const \fBCBlock\fP&, bool)>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartiallyDownloadedBlock\fP (\fBCTxMemPool\fP *poolIn)"
.br
.ti -1c
.RI "\fBReadStatus\fP \fBInitData\fP (const \fBCBlockHeaderAndShortTxIDs\fP &cmpctblock, const std::vector< std::pair< \fBWtxid\fP, \fBCTransactionRef\fP > > &extra_txn)"
.br
.ti -1c
.RI "bool \fBIsTxAvailable\fP (size_t index) const"
.br
.ti -1c
.RI "\fBReadStatus\fP \fBFillBlock\fP (\fBCBlock\fP &block, const std::vector< \fBCTransactionRef\fP > &vtx_missing, bool segwit_active)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCBlockHeader\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBIsBlockMutatedFn\fP \fBm_check_block_mutated_mock\fP {nullptr}"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCTransactionRef\fP > \fBtxn_available\fP"
.br
.ti -1c
.RI "size_t \fBprefilled_count\fP = 0"
.br
.ti -1c
.RI "size_t \fBmempool_count\fP = 0"
.br
.ti -1c
.RI "size_t \fBextra_count\fP = 0"
.br
.ti -1c
.RI "const \fBCTxMemPool\fP * \fBpool\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBIsBlockMutatedFn\fP = std::function<bool(const \fBCBlock\fP&, bool)>"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPartiallyDownloadedBlock\fP (\fBCTxMemPool\fP * poolIn)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBReadStatus\fP FillBlock (\fBCBlock\fP & block, const std::vector< \fBCTransactionRef\fP > & vtx_missing, bool segwit_active)"

.SS "\fBReadStatus\fP InitData (const \fBCBlockHeaderAndShortTxIDs\fP & cmpctblock, const std::vector< std::pair< \fBWtxid\fP, \fBCTransactionRef\fP > > & extra_txn)"

.SS "bool IsTxAvailable (size_t index) const"

.SH "Field Documentation"
.PP 
.SS "size_t extra_count = 0\fR [protected]\fP"

.SS "\fBCBlockHeader\fP header"

.SS "\fBIsBlockMutatedFn\fP m_check_block_mutated_mock {nullptr}"

.SS "size_t mempool_count = 0\fR [protected]\fP"

.SS "const \fBCTxMemPool\fP* pool\fR [protected]\fP"

.SS "size_t prefilled_count = 0\fR [protected]\fP"

.SS "std::vector<\fBCTransactionRef\fP> txn_available\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
