.TH "src/test/pcp_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/pcp_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/pcp\&.h>\fP
.br
\fR#include <netbase\&.h>\fP
.br
\fR#include <test/util/logging\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <deque>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTestOp\fP"
.br
.RI "UDP test server operation\&. "
.ti -1c
.RI "class \fBPCPTestingSetup\fP"
.br
.RI "Save the value of CreateSock and restore when the test ends\&. "
.ti -1c
.RI "class \fBPCPTestSock\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (natpmp_ipv4)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (pcp_ipv4)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (pcp_ipv6)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (pcp_timeout)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (pcp_connrefused)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (pcp_ipv6_timeout_success)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (pcp_ipv4_fail_no_resources)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (pcp_ipv4_fail_unsupported_version)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (natpmp_protocol_error)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (pcp_protocol_error)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (natpmp_ipv4 )"

.SS "BOOST_AUTO_TEST_CASE (natpmp_protocol_error )"

.SS "BOOST_AUTO_TEST_CASE (pcp_connrefused )"

.SS "BOOST_AUTO_TEST_CASE (pcp_ipv4 )"

.SS "BOOST_AUTO_TEST_CASE (pcp_ipv4_fail_no_resources )"

.SS "BOOST_AUTO_TEST_CASE (pcp_ipv4_fail_unsupported_version )"

.SS "BOOST_AUTO_TEST_CASE (pcp_ipv6 )"

.SS "BOOST_AUTO_TEST_CASE (pcp_ipv6_timeout_success )"

.SS "BOOST_AUTO_TEST_CASE (pcp_protocol_error )"

.SS "BOOST_AUTO_TEST_CASE (pcp_timeout )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
