.TH "src/qt/peertablesortproxy.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/peertablesortproxy.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/peertablesortproxy\&.h>\fP
.br
\fR#include <qt/peertablemodel\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <QModelIndex>\fP
.br
\fR#include <QString>\fP
.br
\fR#include <QVariant>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
