.TH "PeerTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeerTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLogIPsTestingSetup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddPeer\fP (\fBNodeId\fP &id, std::vector< \fBCNode\fP * > &nodes, \fBPeerManager\fP &peerman, \fBConnmanTestMsg\fP &connman, \fBConnectionType\fP conn_type, bool onion_peer=false, std::optional< std::string > address=std::nullopt)"
.br
.in -1c

Public Member Functions inherited from \fBLogIPsTestingSetup\fP
.in +1c
.ti -1c
.RI "\fBLogIPsTestingSetup\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBTestingSetup\fP
.in +1c
.ti -1c
.RI "\fBTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.in -1c

Public Member Functions inherited from \fBChainTestingSetup\fP
.in +1c
.ti -1c
.RI "\fBChainTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~ChainTestingSetup\fP ()"
.br
.ti -1c
.RI "void \fBLoadVerifyActivateChainstate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "void \fBSeedRandomForTest\fP (\fBSeedRand\fP seed)"
.br
.ti -1c
.RI "\fBBasicTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~BasicTestingSetup\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Data Fields inherited from \fBChainTestingSetup\fP
.in +1c
.ti -1c
.RI "\fBkernel::CacheSizes\fP \fBm_kernel_cache_sizes\fP {\fBnode::CalculateCacheSizes\fP(\fBm_args\fP)\&.\fBkernel\fP}"
.br
.ti -1c
.RI "bool \fBm_coins_db_in_memory\fP {true}"
.br
.ti -1c
.RI "bool \fBm_block_tree_db_in_memory\fP {true}"
.br
.ti -1c
.RI "std::function< void()> \fBm_make_chainman\fP {}"
.br
.in -1c

Data Fields inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "\fButil::SignalInterrupt\fP \fBm_interrupt\fP"
.br
.ti -1c
.RI "\fBnode::NodeContext\fP \fBm_node\fP"
.br
.ti -1c
.RI "\fBFastRandomContext\fP \fBm_rng\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_root\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_lock\fP"
.br
.ti -1c
.RI "bool \fBm_has_custom_datadir\fP {false}"
.br
.ti -1c
.RI "\fBArgsManager\fP \fBm_args\fP"
.br
.RI "Test-specific arguments and settings\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AddPeer (\fBNodeId\fP & id, std::vector< \fBCNode\fP * > & nodes, \fBPeerManager\fP & peerman, \fBConnmanTestMsg\fP & connman, \fBConnectionType\fP conn_type, bool onion_peer = \fRfalse\fP, std::optional< std::string > address = \fRstd::nullopt\fP)\fR [inline]\fP"
Create a peer and connect to it\&. If the optional \fRaddress\fP (IP/CJDNS only) isn't passed, a random address is created\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
