.TH "PeerTableSortProxy" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeerTableSortProxy
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <peertablesortproxy\&.h>\fP
.PP
Inherits QSortFilterProxyModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPeerTableSortProxy\fP (QObject *parent=nullptr)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBlessThan\fP (const QModelIndex &left_index, const QModelIndex &right_index) const override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPeerTableSortProxy\fP (QObject * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool lessThan (const QModelIndex & left_index, const QModelIndex & right_index) const\fR [override]\fP, \fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
