.TH "PeerIdViewDelegate" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeerIdViewDelegate
.SH SYNOPSIS
.br
.PP
.PP
Inherits QStyledItemDelegate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPeerIdViewDelegate\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QString \fBdisplayText\fP (const QVariant &value, const QLocale &locale) const override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPeerIdViewDelegate\fP (QObject * parent = \fRnullptr\fP)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QString displayText (const QVariant & value, const QLocale & locale) const\fR [inline]\fP, \fR [override]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
