.TH "PeerManager::Options" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeerManager::Options
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <net_processing\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBignore_incoming_txs\fP {DEFAULT_BLOCKSONLY}"
.br
.RI "Whether this node is running in -blocksonly mode\&. "
.ti -1c
.RI "bool \fBreconcile_txs\fP {DEFAULT_TXRECONCILIATION_ENABLE}"
.br
.RI "Whether transaction reconciliation protocol is enabled\&. "
.ti -1c
.RI "uint32_t \fBmax_extra_txs\fP {DEFAULT_BLOCK_RECONSTRUCTION_EXTRA_TXN}"
.br
.ti -1c
.RI "bool \fBcapture_messages\fP {false}"
.br
.RI "Whether all P2P messages are captured to disk\&. "
.ti -1c
.RI "bool \fBdeterministic_rng\fP {false}"
.br
.ti -1c
.RI "uint32_t \fBmax_headers_result\fP {MAX_HEADERS_RESULTS}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool capture_messages {false}"

.PP
Whether all P2P messages are captured to disk\&. 
.SS "bool deterministic_rng {false}"
Whether or not the internal RNG behaves deterministically (this is a test-only option)\&. 
.SS "bool ignore_incoming_txs {DEFAULT_BLOCKSONLY}"

.PP
Whether this node is running in -blocksonly mode\&. 
.SS "uint32_t max_extra_txs {DEFAULT_BLOCK_RECONSTRUCTION_EXTRA_TXN}"
Number of non-mempool transactions to keep around for block reconstruction\&. Includes orphan, replaced, and rejected transactions\&. 
.SS "uint32_t max_headers_result {MAX_HEADERS_RESULTS}"
Number of headers sent in one getheaders message result (this is a test-only option)\&. 
.SS "bool reconcile_txs {DEFAULT_TXRECONCILIATION_ENABLE}"

.PP
Whether transaction reconciliation protocol is enabled\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
