.TH "PerBlockConnectTrace" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PerBlockConnectTrace
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerBlockConnectTrace\fP ()=default"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCBlockIndex\fP * \fBpindex\fP = nullptr"
.br
.ti -1c
.RI "std::shared_ptr< const \fBCBlock\fP > \fBpblock\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPerBlockConnectTrace\fP ()\fR [default]\fP"

.SH "Field Documentation"
.PP 
.SS "std::shared_ptr<const \fBCBlock\fP> pblock"

.SS "\fBCBlockIndex\fP* pindex = nullptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
