.TH "PKHash" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PKHash
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <addresstype\&.h>\fP
.PP
Inherits \fBBaseHash< uint160 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPKHash\fP ()"
.br
.ti -1c
.RI "\fBPKHash\fP (const \fBuint160\fP &hash)"
.br
.ti -1c
.RI "\fBPKHash\fP (const \fBCPubKey\fP &pubkey)"
.br
.ti -1c
.RI "\fBPKHash\fP (const \fBCKeyID\fP &pubkey_id)"
.br
.in -1c

Public Member Functions inherited from \fBBaseHash< uint160 >\fP
.in +1c
.ti -1c
.RI "\fBBaseHash\fP ()"
.br
.ti -1c
.RI "unsigned char * \fBbegin\fP ()"
.br
.ti -1c
.RI "unsigned char * \fBend\fP ()"
.br
.ti -1c
.RI "\fBoperator std::vector< unsigned char >\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBBaseHash\fP< \fBuint160\fP > &other) const noexcept"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBBaseHash\fP< \fBuint160\fP > &other) const noexcept"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBBaseHash< uint160 >\fP
.in +1c
.ti -1c
.RI "\fBuint160\fP \fBm_hash\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPKHash\fP ()\fR [inline]\fP"

.SS "\fBPKHash\fP (const \fBuint160\fP & hash)\fR [inline]\fP, \fR [explicit]\fP"

.SS "\fBPKHash\fP (const \fBCPubKey\fP & pubkey)\fR [explicit]\fP"

.SS "\fBPKHash\fP (const \fBCKeyID\fP & pubkey_id)\fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
