.TH "src/qt/platformstyle.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/platformstyle.h
.SH SYNOPSIS
.br
.PP
\fR#include <QIcon>\fP
.br
\fR#include <QPixmap>\fP
.br
\fR#include <QString>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPlatformStyle\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
