.TH "src/qt/platformstyle.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/platformstyle.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/platformstyle\&.h>\fP
.br
\fR#include <QApplication>\fP
.br
\fR#include <QColor>\fP
.br
\fR#include <QImage>\fP
.br
\fR#include <QPalette>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
