.TH "PlatformStyle" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlatformStyle
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <platformstyle\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const QString & \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBgetImagesOnButtons\fP () const"
.br
.ti -1c
.RI "bool \fBgetUseExtraSpacing\fP () const"
.br
.ti -1c
.RI "QColor \fBTextColor\fP () const"
.br
.ti -1c
.RI "QColor \fBSingleColor\fP () const"
.br
.ti -1c
.RI "QImage \fBSingleColorImage\fP (const QString &filename) const"
.br
.ti -1c
.RI "QIcon \fBSingleColorIcon\fP (const QString &filename) const"
.br
.ti -1c
.RI "QIcon \fBSingleColorIcon\fP (const QIcon &icon) const"
.br
.ti -1c
.RI "QIcon \fBTextColorIcon\fP (const QIcon &icon) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBPlatformStyle\fP * \fBinstantiate\fP (const QString &platformId)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool getImagesOnButtons () const\fR [inline]\fP"

.SS "const QString & getName () const\fR [inline]\fP"

.SS "bool getUseExtraSpacing () const\fR [inline]\fP"

.SS "const \fBPlatformStyle\fP * instantiate (const QString & platformId)\fR [static]\fP"
Get style associated with provided platform name, or 0 if not known 
.SS "QColor SingleColor () const"

.SS "QIcon SingleColorIcon (const QIcon & icon) const"
Colorize an icon (given object) with the icon color 
.SS "QIcon SingleColorIcon (const QString & filename) const"
Colorize an icon (given filename) with the icon color 
.SS "QImage SingleColorImage (const QString & filename) const"
Colorize an image (given filename) with the icon color 
.SS "QColor TextColor () const"

.SS "QIcon TextColorIcon (const QIcon & icon) const"
Colorize an icon (given object) with the text color 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
