.TH "src/test/fuzz/policy_estimator.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/policy_estimator.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <kernel/mempool_entry\&.h>\fP
.br
\fR#include <policy/fees/block_policy_estimator\&.h>\fP
.br
\fR#include <policy/fees/block_policy_estimator_args\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <test/fuzz/util/mempool\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_policy_estimator\fP ()"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (policy_estimator,\&.\fBinit\fP=\fBinitialize_policy_estimator\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (policy_estimator , \&. init = \fR\fBinitialize_policy_estimator\fP\fP)"

.SS "void initialize_policy_estimator ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
