.TH "Poly1305" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poly1305
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <poly1305\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoly1305\fP (std::span< const std::byte > key) noexcept"
.br
.ti -1c
.RI "\fBPoly1305\fP & \fBUpdate\fP (std::span< const std::byte > msg) noexcept"
.br
.ti -1c
.RI "void \fBFinalize\fP (std::span< std::byte > out) noexcept"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr unsigned \fBTAGLEN\fP {16}"
.br
.ti -1c
.RI "static constexpr unsigned \fBKEYLEN\fP {32}"
.br
.in -1c
.SH "Detailed Description"
.PP 
C++ wrapper with std::byte span interface around \fBpoly1305_donna\fP code\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPoly1305\fP (std::span< const std::byte > key)\fR [inline]\fP, \fR [noexcept]\fP"
Construct a \fBPoly1305\fP object with a given 32-byte key\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Finalize (std::span< std::byte > out)\fR [inline]\fP, \fR [noexcept]\fP"
Write authentication tag to 16-byte out\&. 
.SS "\fBPoly1305\fP & Update (std::span< const std::byte > msg)\fR [inline]\fP, \fR [noexcept]\fP"
Process message bytes\&. 
.SH "Field Documentation"
.PP 
.SS "unsigned KEYLEN {32}\fR [static]\fP, \fR [constexpr]\fP"
Length of the keys expected by the constructor\&. 
.SS "unsigned TAGLEN {16}\fR [static]\fP, \fR [constexpr]\fP"
Length of the output produced by \fBFinalize()\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
