.TH "PoolAllocator< T, MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoolAllocator< T, MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pool\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBrebind\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_type\fP = \fBT\fP"
.br
.ti -1c
.RI "using \fBResourceType\fP = \fBPoolResource\fP<MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoolAllocator\fP (\fBResourceType\fP *\fBresource\fP) noexcept"
.br
.ti -1c
.RI "\fBPoolAllocator\fP (const \fBPoolAllocator\fP &other) noexcept=default"
.br
.ti -1c
.RI "\fBPoolAllocator\fP & \fBoperator=\fP (const \fBPoolAllocator\fP &other) noexcept=default"
.br
.ti -1c
.RI "template<class U> \fBPoolAllocator\fP (const \fBPoolAllocator\fP< U, MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES > &other) noexcept"
.br
.ti -1c
.RI "\fBT\fP * \fBallocate\fP (size_t n)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (\fBT\fP *p, size_t n) noexcept"
.br
.ti -1c
.RI "\fBResourceType\fP * \fBresource\fP () const noexcept"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename U, std::size_t M, std::size_t A> class \fBPoolAllocator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)>
.br
class PoolAllocator< T, MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES >"Forwards all allocations/deallocations to the \fBPoolResource\fP\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)> using \fBResourceType\fP = \fBPoolResource\fP<MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES>"

.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)> using \fBvalue_type\fP = \fBT\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)> \fBPoolAllocator\fP (\fBResourceType\fP * resource)\fR [inline]\fP, \fR [noexcept]\fP"
Not explicit so we can easily construct it with the correct resource 
.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)> \fBPoolAllocator\fP (const \fBPoolAllocator\fP< \fBT\fP, MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES > & other)\fR [default]\fP, \fR [noexcept]\fP"

.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)> template<class U> \fBPoolAllocator\fP (const \fBPoolAllocator\fP< U, MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES > & other)\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)> \fBT\fP * allocate (size_t n)\fR [inline]\fP"
Forwards each call to the resource\&. 
.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)> void deallocate (\fBT\fP * p, size_t n)\fR [inline]\fP, \fR [noexcept]\fP"
Forwards each call to the resource\&. 
.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)> \fBPoolAllocator\fP & operator= (const \fBPoolAllocator\fP< \fBT\fP, MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES > & other)\fR [default]\fP, \fR [noexcept]\fP"

.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)> \fBResourceType\fP * resource () const\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "template<class \fBT\fP, std::size_t MAX_BLOCK_SIZE_BYTES, std::size_t ALIGN_BYTES = alignof(T)> template<typename U, std::size_t M, std::size_t A> friend class \fBPoolAllocator\fP\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
