.TH "src/test/pool_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/pool_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <memusage\&.h>\fP
.br
\fR#include <support/allocators/pool\&.h>\fP
.br
\fR#include <test/util/poolresourcetester\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (basic_allocating)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (allocate_any_byte)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (random_allocations)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (memusage_test)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (allocate_any_byte )"

.SS "BOOST_AUTO_TEST_CASE (basic_allocating )"

.SS "BOOST_AUTO_TEST_CASE (memusage_test )"

.SS "BOOST_AUTO_TEST_CASE (random_allocations )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
