.TH "src/test/pow_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/pow_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <chain\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <pow\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (get_next_work)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (get_next_work_pow_limit)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (get_next_work_lower_limit_actual)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (get_next_work_upper_limit_actual)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (CheckProofOfWork_test_negative_target)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (CheckProofOfWork_test_overflow_target)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (CheckProofOfWork_test_too_easy_target)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (CheckProofOfWork_test_biger_hash_than_target)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (CheckProofOfWork_test_zero_target)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (GetBlockProofEquivalentTime_test)"
.br
.ti -1c
.RI "void \fBsanity_check_chainparams\fP (const \fBArgsManager\fP &\fBargs\fP, \fBChainType\fP chain_type)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (ChainParams_MAIN_sanity)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (ChainParams_REGTEST_sanity)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (ChainParams_TESTNET_sanity)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (ChainParams_TESTNET4_sanity)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (ChainParams_SIGNET_sanity)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (ChainParams_MAIN_sanity )"

.SS "BOOST_AUTO_TEST_CASE (ChainParams_REGTEST_sanity )"

.SS "BOOST_AUTO_TEST_CASE (ChainParams_SIGNET_sanity )"

.SS "BOOST_AUTO_TEST_CASE (ChainParams_TESTNET4_sanity )"

.SS "BOOST_AUTO_TEST_CASE (ChainParams_TESTNET_sanity )"

.SS "BOOST_AUTO_TEST_CASE (CheckProofOfWork_test_biger_hash_than_target )"

.SS "BOOST_AUTO_TEST_CASE (CheckProofOfWork_test_negative_target )"

.SS "BOOST_AUTO_TEST_CASE (CheckProofOfWork_test_overflow_target )"

.SS "BOOST_AUTO_TEST_CASE (CheckProofOfWork_test_too_easy_target )"

.SS "BOOST_AUTO_TEST_CASE (CheckProofOfWork_test_zero_target )"

.SS "BOOST_AUTO_TEST_CASE (get_next_work )"

.SS "BOOST_AUTO_TEST_CASE (get_next_work_lower_limit_actual )"

.SS "BOOST_AUTO_TEST_CASE (get_next_work_pow_limit )"

.SS "BOOST_AUTO_TEST_CASE (get_next_work_upper_limit_actual )"

.SS "BOOST_AUTO_TEST_CASE (GetBlockProofEquivalentTime_test )"

.SS "void sanity_check_chainparams (const \fBArgsManager\fP & args, \fBChainType\fP chain_type)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
