.TH "src/secp256k1/src/precomputed_ecmult_gen.c" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/precomputed_ecmult_gen.c
.SH SYNOPSIS
.br
.PP
\fR#include 'group\&.h'\fP
.br
\fR#include 'ecmult_gen\&.h'\fP
.br
\fR#include 'precomputed_ecmult_gen\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBS\fP(a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBsecp256k1_ge_storage\fP \fBsecp256k1_ecmult_gen_prec_table\fP [\fBCOMB_BLOCKS\fP][\fBCOMB_POINTS\fP]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define S( a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p)"
\fBValue:\fP
.nf
SECP256K1_GE_STORAGE_CONST(0x##a##u,0x##b##u,0x##c##u,0x##d##u,0x##e##u,0x##f##u,0x##g##u,0x##h##u,0x##i##u,0x##j##u,0x##k##u,0x##l##u,0x##m##u,0x##n##u,0x##o##u,0x##p##u)
.PP
.fi

.SH "Variable Documentation"
.PP 
.SS "const \fBsecp256k1_ge_storage\fP secp256k1_ecmult_gen_prec_table[\fBCOMB_BLOCKS\fP][\fBCOMB_POINTS\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
