.TH "src/secp256k1/src/precomputed_ecmult.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/precomputed_ecmult.h
.SH SYNOPSIS
.br
.PP
\fR#include 'ecmult\&.h'\fP
.br
\fR#include 'group\&.h'\fP
.br
\fR#include 'util_local_visibility\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWINDOW_G\fP   \fBECMULT_WINDOW_SIZE\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSECP256K1_LOCAL_VAR\fP const \fBsecp256k1_ge_storage\fP \fBsecp256k1_pre_g\fP [\fBECMULT_TABLE_SIZE\fP(\fBWINDOW_G\fP)]"
.br
.ti -1c
.RI "\fBSECP256K1_LOCAL_VAR\fP const \fBsecp256k1_ge_storage\fP \fBsecp256k1_pre_g_128\fP [\fBECMULT_TABLE_SIZE\fP(\fBWINDOW_G\fP)]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define WINDOW_G   \fBECMULT_WINDOW_SIZE\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBSECP256K1_LOCAL_VAR\fP const \fBsecp256k1_ge_storage\fP secp256k1_pre_g[\fBECMULT_TABLE_SIZE\fP(\fBWINDOW_G\fP)]"

.SS "\fBSECP256K1_LOCAL_VAR\fP const \fBsecp256k1_ge_storage\fP secp256k1_pre_g_128[\fBECMULT_TABLE_SIZE\fP(\fBWINDOW_G\fP)]"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
