.TH "PreSelectInputs" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PreSelectInputs
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnum_of_internal_inputs\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int num_of_internal_inputs"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
