.TH "PresaltedSipHasher" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PresaltedSipHasher
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <siphash\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPresaltedSipHasher\fP (uint64_t k0, uint64_t k1) noexcept"
.br
.ti -1c
.RI "uint64_t \fBoperator()\fP (const \fBuint256\fP &val) const noexcept"
.br
.ti -1c
.RI "uint64_t \fBoperator()\fP (const \fBuint256\fP &val, uint32_t extra) const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Optimized SipHash-2-4 implementation for \fBuint256\fP\&.

.PP
This class caches the initial SipHash v[0\&.\&.3] state derived from (k0, k1) and implements a specialized hashing path for \fBuint256\fP values, with or without an extra 32-bit word\&. The internal state is immutable, so \fBPresaltedSipHasher\fP instances can be reused for multiple hashes with the same key\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPresaltedSipHasher\fP (uint64_t k0, uint64_t k1)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "uint64_t operator() (const \fBuint256\fP & val) const\fR [noexcept]\fP"
Equivalent to \fBCSipHasher(k0, k1)\fP\&.Write(val)\&.Finalize()\&. 
.SS "uint64_t operator() (const \fBuint256\fP & val, uint32_t extra) const\fR [noexcept]\fP"
Equivalent to \fBCSipHasher(k0, k1)\fP\&.Write(val)\&.Write(extra)\&.Finalize(), with \fRextra\fP encoded as 4 little-endian bytes\&.

.PP
Specialized implementation for efficiency 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
