.TH "src/ipc/process.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc/process.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <ipc/process\&.h>\fP
.br
\fR#include <ipc/protocol\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <mp/util\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/syserror\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <cerrno>\fP
.br
\fR#include <exception>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <sys/socket\&.h>\fP
.br
\fR#include <sys/un\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBipc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBProcess\fP > \fBMakeProcess\fP ()"
.br
.ti -1c
.RI "std::string_view \fBRemovePrefixView\fP (std::string_view str, std::string_view \fBprefix\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string_view RemovePrefixView (std::string_view str, std::string_view prefix)\fR [inline]\fP, \fR [nodiscard]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
