.TH "src/ipc/libmultiprocess/include/mp/proxy-io.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc/libmultiprocess/include/mp/proxy-io.h
.SH SYNOPSIS
.br
.PP
\fR#include <mp/proxy\&.h>\fP
.br
\fR#include <mp/util\&.h>\fP
.br
\fR#include <mp/proxy\&.capnp\&.h>\fP
.br
\fR#include <capnp/rpc\-twoparty\&.h>\fP
.br
\fR#include <assert\&.h>\fP
.br
\fR#include <condition_variable>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <kj/function\&.h>\fP
.br
\fR#include <map>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <thread>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBInvokeContext\fP"
.br
.ti -1c
.RI "struct \fBClientInvokeContext\fP"
.br
.ti -1c
.RI "struct \fBServerInvokeContext< ProxyServer, CallContext_ >\fP"
.br
.ti -1c
.RI "struct \fBProxyClient< Thread >\fP"
.br
.ti -1c
.RI "struct \fBProxyServer< Thread >\fP"
.br
.ti -1c
.RI "class \fBLoggingErrorHandler\fP"
.br
.RI "\fBHandler\fP for kj::TaskSet failed task events\&. "
.ti -1c
.RI "struct \fBLogMessage\fP"
.br
.ti -1c
.RI "struct \fBLogOptions\fP"
.br
.ti -1c
.RI "class \fBLogger\fP"
.br
.ti -1c
.RI "class \fBEventLoop\fP"
.br
.ti -1c
.RI "struct \fBWaiter\fP"
.br
.ti -1c
.RI "class \fBConnection\fP"
.br
.ti -1c
.RI "struct \fBServerVatId\fP"
.br
.ti -1c
.RI "struct \fBThreadContext\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmp\fP"
.br
.RI "Functions to serialize / deserialize common bitcoin types\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMP_LOGPLAIN\fP(loop, \&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBMP_LOG\fP(loop, \&.\&.\&.)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename Interface, typename \fBParams\fP, typename Results> using \fBServerContext\fP = \fBServerInvokeContext\fP<\fBProxyServer\fP<Interface>, ::capnp::CallContext<\fBParams\fP, Results>>"
.br
.ti -1c
.RI "using \fBLogFn\fP = std::function<void(\fBLogMessage\fP)>"
.br
.ti -1c
.RI "using \fBConnThreads\fP = std::map<\fBConnection\fP*, std::optional<\fBProxyClient\fP<Thread>>>"
.br
.ti -1c
.RI "using \fBConnThread\fP = ConnThreads::iterator"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBLog\fP { \fBTrace\fP = 0, \fBDebug\fP, \fBInfo\fP, \fBWarning\fP, \fBError\fP, \fBRaise\fP }"
.br
.RI "Log flags\&. Update stringify function if changed! "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "kj::StringPtr \fBKJ_STRINGIFY\fP (\fBLog\fP \fBflags\fP)"
.br
.ti -1c
.RI "std::string \fBLongThreadName\fP (const char *exe_name)"
.br
.ti -1c
.RI "std::tuple< \fBConnThread\fP, bool > \fBSetThread\fP (\fBGuardedRef\fP< \fBConnThreads\fP > threads, \fBConnection\fP *connection, const std::function< Thread::Client()> &make_thread)"
.br
.ti -1c
.RI "template<typename InitInterface> std::unique_ptr< \fBProxyClient\fP< InitInterface > > \fBConnectStream\fP (\fBEventLoop\fP &loop, int fd)"
.br
.ti -1c
.RI "template<typename InitInterface, typename \fBInitImpl\fP> void \fB_Serve\fP (\fBEventLoop\fP &loop, kj::Own< kj::AsyncIoStream > &&stream, \fBInitImpl\fP &\fBinit\fP)"
.br
.ti -1c
.RI "template<typename InitInterface, typename \fBInitImpl\fP> void \fB_Listen\fP (\fBEventLoop\fP &loop, kj::Own< kj::ConnectionReceiver > &&listener, \fBInitImpl\fP &\fBinit\fP)"
.br
.ti -1c
.RI "template<typename InitInterface, typename \fBInitImpl\fP> void \fBServeStream\fP (\fBEventLoop\fP &loop, int fd, \fBInitImpl\fP &\fBinit\fP)"
.br
.ti -1c
.RI "template<typename InitInterface, typename \fBInitImpl\fP> void \fBListenConnections\fP (\fBEventLoop\fP &loop, int fd, \fBInitImpl\fP &\fBinit\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBThreadContext\fP \fBg_thread_context\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MP_LOG( loop,  \&.\&.\&.)"
\fBValue:\fP
.nf
MP_LOGPLAIN(loop, __VA_ARGS__) << "{" << LongThreadName((loop)\&.m_exe_name) << "} "
.PP
.fi

.SS "#define MP_LOGPLAIN( loop,  \&.\&.\&.)"
\fBValue:\fP
.nf
if (mp::Logger logger{(loop)\&.m_log_opts, __VA_ARGS__}; logger) logger
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
