.TH "Proxy" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Proxy
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <netbase\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProxy\fP ()"
.br
.ti -1c
.RI "\fBProxy\fP (const \fBCService\fP &_proxy, bool tor_stream_isolation=false)"
.br
.ti -1c
.RI "\fBProxy\fP (const std::string path, bool tor_stream_isolation=false)"
.br
.ti -1c
.RI "bool \fBIsValid\fP () const"
.br
.ti -1c
.RI "sa_family_t \fBGetFamily\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "std::unique_ptr< \fBSock\fP > \fBConnect\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCService\fP \fBproxy\fP"
.br
.ti -1c
.RI "std::string \fBm_unix_socket_path\fP"
.br
.ti -1c
.RI "bool \fBm_is_unix_socket\fP"
.br
.ti -1c
.RI "bool \fBm_tor_stream_isolation\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBProxy\fP ()\fR [inline]\fP"

.SS "\fBProxy\fP (const \fBCService\fP & _proxy, bool tor_stream_isolation = \fRfalse\fP)\fR [inline]\fP, \fR [explicit]\fP"

.SS "\fBProxy\fP (const std::string path, bool tor_stream_isolation = \fRfalse\fP)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::unique_ptr< \fBSock\fP > Connect () const"

.SS "sa_family_t GetFamily () const\fR [inline]\fP"

.SS "bool IsValid () const\fR [inline]\fP"

.SS "std::string ToString () const\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "bool m_is_unix_socket"

.SS "bool m_tor_stream_isolation"

.SS "std::string m_unix_socket_path"

.SS "\fBCService\fP proxy"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
