.TH "PSBTOutput" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSBTOutput
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <psbt\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsNull\fP () const"
.br
.ti -1c
.RI "void \fBFillSignatureData\fP (\fBSignatureData\fP &sigdata) const"
.br
.ti -1c
.RI "void \fBFromSignatureData\fP (const \fBSignatureData\fP &sigdata)"
.br
.ti -1c
.RI "void \fBMerge\fP (const \fBPSBTOutput\fP &output)"
.br
.ti -1c
.RI "\fBPSBTOutput\fP ()=default"
.br
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.ti -1c
.RI "template<typename Stream> \fBPSBTOutput\fP (\fBdeserialize_type\fP, Stream &s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCScript\fP \fBredeem_script\fP"
.br
.ti -1c
.RI "\fBCScript\fP \fBwitness_script\fP"
.br
.ti -1c
.RI "std::map< \fBCPubKey\fP, \fBKeyOriginInfo\fP > \fBhd_keypaths\fP"
.br
.ti -1c
.RI "\fBXOnlyPubKey\fP \fBm_tap_internal_key\fP"
.br
.ti -1c
.RI "std::vector< std::tuple< uint8_t, uint8_t, std::vector< unsigned char > > > \fBm_tap_tree\fP"
.br
.ti -1c
.RI "std::map< \fBXOnlyPubKey\fP, std::pair< std::set< \fBuint256\fP >, \fBKeyOriginInfo\fP > > \fBm_tap_bip32_paths\fP"
.br
.ti -1c
.RI "std::map< \fBCPubKey\fP, std::vector< \fBCPubKey\fP > > \fBm_musig2_participants\fP"
.br
.ti -1c
.RI "std::map< std::vector< unsigned char >, std::vector< unsigned char > > \fBunknown\fP"
.br
.ti -1c
.RI "std::set< \fBPSBTProprietary\fP > \fBm_proprietary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure for PSBTs which contains per output information 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPSBTOutput\fP ()\fR [default]\fP"

.SS "template<typename Stream> \fBPSBTOutput\fP (\fBdeserialize_type\fP , Stream & s)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void FillSignatureData (\fBSignatureData\fP & sigdata) const"

.SS "void FromSignatureData (const \fBSignatureData\fP & sigdata)"

.SS "bool IsNull () const"

.SS "void Merge (const \fBPSBTOutput\fP & output)"

.SS "template<typename Stream> void Serialize (Stream & s) const\fR [inline]\fP"

.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::map<\fBCPubKey\fP, \fBKeyOriginInfo\fP> hd_keypaths"

.SS "std::map<\fBCPubKey\fP, std::vector<\fBCPubKey\fP> > m_musig2_participants"

.SS "std::set<\fBPSBTProprietary\fP> m_proprietary"

.SS "std::map<\fBXOnlyPubKey\fP, std::pair<std::set<\fBuint256\fP>, \fBKeyOriginInfo\fP> > m_tap_bip32_paths"

.SS "\fBXOnlyPubKey\fP m_tap_internal_key"

.SS "std::vector<std::tuple<uint8_t, uint8_t, std::vector<unsigned char> > > m_tap_tree"

.SS "\fBCScript\fP redeem_script"

.SS "std::map<std::vector<unsigned char>, std::vector<unsigned char> > unknown"

.SS "\fBCScript\fP witness_script"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
