.TH "PSBTOperationsDialog" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSBTOperationsDialog
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <psbtoperationsdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsignTransaction\fP ()"
.br
.ti -1c
.RI "void \fBbroadcastTransaction\fP ()"
.br
.ti -1c
.RI "void \fBcopyToClipboard\fP ()"
.br
.ti -1c
.RI "void \fBsaveTransaction\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPSBTOperationsDialog\fP (QWidget *parent, \fBWalletModel\fP *walletModel, \fBClientModel\fP *clientModel)"
.br
.ti -1c
.RI "\fB~PSBTOperationsDialog\fP ()"
.br
.ti -1c
.RI "void \fBopenWithPSBT\fP (\fBPartiallySignedTransaction\fP psbtx)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dialog showing transaction details\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPSBTOperationsDialog\fP (QWidget * parent, \fBWalletModel\fP * walletModel, \fBClientModel\fP * clientModel)\fR [explicit]\fP"

.SS "~\fBPSBTOperationsDialog\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void broadcastTransaction ()\fR [slot]\fP"

.SS "void copyToClipboard ()\fR [slot]\fP"

.SS "void openWithPSBT (\fBPartiallySignedTransaction\fP psbtx)"

.SS "void saveTransaction ()\fR [slot]\fP"

.SS "void signTransaction ()\fR [slot]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
