.TH "src/test/fuzz/psbt.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/psbt.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/psbt\&.h>\fP
.br
\fR#include <psbt\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBPSBTInputAnalysis\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFUZZ_TARGET\fP (psbt)"
.br
.ti -1c
.RI "\fBPSBTAnalysis\fP \fBAnalyzePSBT\fP (\fBPartiallySignedTransaction\fP psbtx)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPSBTAnalysis\fP AnalyzePSBT (\fBPartiallySignedTransaction\fP psbtx)"
Provides helpful miscellaneous information about where a PSBT is in the signing workflow\&.

.PP
\fBParameters\fP
.RS 4
\fIpsbtx\fP the PSBT to analyze 
.RE
.PP
\fBReturns\fP
.RS 4
A \fBPSBTAnalysis\fP with information about the provided PSBT\&. 
.RE
.PP

.SS "FUZZ_TARGET (psbt )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
