.TH "src/pubkey.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pubkey.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <pubkey\&.h>\fP
.br
\fR#include <hash\&.h>\fP
.br
\fR#include <secp256k1\&.h>\fP
.br
\fR#include <secp256k1_ellswift\&.h>\fP
.br
\fR#include <secp256k1_extrakeys\&.h>\fP
.br
\fR#include <secp256k1_recovery\&.h>\fP
.br
\fR#include <secp256k1_schnorrsig\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cassert>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBecdsa_signature_parse_der_lax\fP (\fBsecp256k1_ecdsa_signature\fP *sig, const unsigned char *input, size_t inputlen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ecdsa_signature_parse_der_lax (\fBsecp256k1_ecdsa_signature\fP * sig, const unsigned char * input, size_t inputlen)"
This function is taken from the libsecp256k1 distribution and implements DER parsing for ECDSA signatures, while supporting an arbitrary subset of format violations\&.

.PP
Supported violations include negative integers, excessive padding, garbage at the end, and overly long length descriptors\&. This is safe to use in Bitcoin because since the activation of BIP66, signatures are verified to be strict DER before being passed to this module, and we know it supports all violations present in the blockchain before that point\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
