.TH "src/minisketch/tests/pyminisketch.py" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/minisketch/tests/pyminisketch.py
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBGF2Ops\fP"
.br
.ti -1c
.RI "class \fBTestGF2Ops\fP"
.br
.ti -1c
.RI "class \fBTestPolyFindRoots\fP"
.br
.ti -1c
.RI "class \fBMinisketch\fP"
.br
.ti -1c
.RI "class \fBTestMinisketch\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpyminisketch\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpoly_monic\fP (poly, gf)"
.br
.ti -1c
.RI "\fBpoly_divmod\fP (poly, mod, gf)"
.br
.ti -1c
.RI "\fBpoly_gcd\fP (a, b, gf)"
.br
.ti -1c
.RI "\fBpoly_sqr\fP (poly, gf)"
.br
.ti -1c
.RI "\fBpoly_tracemod\fP (poly, param, gf)"
.br
.ti -1c
.RI "\fBpoly_frobeniusmod\fP (poly, gf)"
.br
.ti -1c
.RI "\fBpoly_find_roots\fP (poly, gf)"
.br
.ti -1c
.RI "\fBberlekamp_massey\fP (syndromes, gf)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBGF2_MODULI\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
