.TH "QRImageWidget" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRImageWidget
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <qrimagewidget\&.h>\fP
.PP
Inherits QLabel\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsaveImage\fP ()"
.br
.ti -1c
.RI "void \fBcopyImage\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQRImageWidget\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "bool \fBsetQR\fP (const QString &data, const QString &text='')"
.br
.ti -1c
.RI "QImage \fBexportImage\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBmousePressEvent\fP (QMouseEvent *event) override"
.br
.ti -1c
.RI "virtual void \fBcontextMenuEvent\fP (QContextMenuEvent *event) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBQRImageWidget\fP (QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void contextMenuEvent (QContextMenuEvent * event)\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.SS "void copyImage ()\fR [slot]\fP"

.SS "QImage exportImage ()"

.SS "void mousePressEvent (QMouseEvent * event)\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.SS "void saveImage ()\fR [slot]\fP"

.SS "bool setQR (const QString & data, const QString & text = \fR''\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
