.TH "src/test/random_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/random_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <random\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <random>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (osrandom_tests)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (fastrandom_tests_deterministic)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (fastrandom_tests_nondeterministic)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (fastrandom_randbits)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (randbits_test)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (stdrandom_test)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (shuffle_stat_test)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (xoroshiro128plusplus_reference_values)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (fastrandom_randbits )"

.SS "BOOST_AUTO_TEST_CASE (fastrandom_tests_deterministic )"

.SS "BOOST_AUTO_TEST_CASE (fastrandom_tests_nondeterministic )"

.SS "BOOST_AUTO_TEST_CASE (osrandom_tests )"

.SS "BOOST_AUTO_TEST_CASE (randbits_test )"
Verify that \fBRandomMixin::randbits\fP returns 0 and 1 for every requested bit\&. < RNG for producing the lengths requested from ctx_test\&.

.PP
< The RNGs being tested\&.

.PP
< (Assumed value of) ctx_test::bitbuf_len
.SS "BOOST_AUTO_TEST_CASE (shuffle_stat_test )"
Test that Shuffle reaches every permutation with equal probability\&. 
.SS "BOOST_AUTO_TEST_CASE (stdrandom_test )"
Does-it-compile test for compatibility with standard library RNG interface\&. 
.SS "BOOST_AUTO_TEST_CASE (xoroshiro128plusplus_reference_values )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
