.TH "RandomNumberGenerator" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomNumberGenerator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <random\&.h>\fP
.SH "Concept definition"
.PP 

.nf
template<typename T>
concept RandomNumberGenerator =  requires(T& rng, std::span<std::byte> s) {
    
    { rng\&.rand64() } noexcept \-> std::same_as<uint64_t>;
    
    requires std::derived_from<std::remove_reference_t<T>, RandomMixin<std::remove_reference_t<T>>>;
}
.PP
.fi
.SH "Detailed Description"
.PP 
A concept for RandomMixin-based random number generators\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
