.TH "src/bench/readwriteblock.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bench/readwriteblock.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bench/bench\&.h>\fP
.br
\fR#include <bench/data/block413567\&.raw\&.h>\fP
.br
\fR#include <flatfile\&.h>\fP
.br
\fR#include <node/blockstorage\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBENCHMARK\fP (WriteBlockBench, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.ti -1c
.RI "\fBBENCHMARK\fP (ReadBlockBench, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.ti -1c
.RI "\fBBENCHMARK\fP (ReadRawBlockBench, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BENCHMARK (ReadBlockBench , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SS "BENCHMARK (ReadRawBlockBench , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SS "BENCHMARK (WriteBlockBench , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
