.TH "ReceiveCoinsDialog" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReceiveCoinsDialog
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <receivecoinsdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBColumnWidths\fP { \fBDATE_COLUMN_WIDTH\fP = 130, \fBLABEL_COLUMN_WIDTH\fP = 120, \fBAMOUNT_MINIMUM_COLUMN_WIDTH\fP = 180, \fBMINIMUM_COLUMN_WIDTH\fP = 130 }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBreject\fP () override"
.br
.ti -1c
.RI "void \fBaccept\fP () override"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReceiveCoinsDialog\fP (const \fBPlatformStyle\fP *platformStyle, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~ReceiveCoinsDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBWalletModel\fP *model)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dialog for requesting payment of bitcoins 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBColumnWidths\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIDATE_COLUMN_WIDTH \fP
.TP
\f(BILABEL_COLUMN_WIDTH \fP
.TP
\f(BIAMOUNT_MINIMUM_COLUMN_WIDTH \fP
.TP
\f(BIMINIMUM_COLUMN_WIDTH \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBReceiveCoinsDialog\fP (const \fBPlatformStyle\fP * platformStyle, QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SS "~\fBReceiveCoinsDialog\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void accept ()\fR [override]\fP, \fR [slot]\fP"

.SS "void clear ()\fR [slot]\fP"

.SS "void reject ()\fR [override]\fP, \fR [slot]\fP"

.SS "void setModel (\fBWalletModel\fP * model)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
