.TH "RecentRequestEntry" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecentRequestEntry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <recentrequeststablemodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRecentRequestEntry\fP ()=default"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBRecentRequestEntry\fP, obj)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnVersion\fP {\fBRecentRequestEntry::CURRENT_VERSION\fP}"
.br
.ti -1c
.RI "int64_t \fBid\fP {0}"
.br
.ti -1c
.RI "QDateTime \fBdate\fP"
.br
.ti -1c
.RI "\fBSendCoinsRecipient\fP \fBrecipient\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBCURRENT_VERSION\fP = 1"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBRecentRequestEntry\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "SERIALIZE_METHODS (\fBRecentRequestEntry\fP , obj )\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "const int CURRENT_VERSION = 1\fR [static]\fP"

.SS "QDateTime date"

.SS "int64_t id {0}"

.SS "int nVersion {\fBRecentRequestEntry::CURRENT_VERSION\fP}"

.SS "\fBSendCoinsRecipient\fP recipient"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
