.TH "RecLinTrans< I, N >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecLinTrans< I, N >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lintrans\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBRecLinTrans\fP (const I *p, \fBNum\fP< \fBBITS\fP >)"
.br
.ti -1c
.RI "constexpr \fBRecLinTrans\fP ()=default"
.br
.ti -1c
.RI "constexpr \fBRecLinTrans\fP (const I(&\fBinit\fP)[\fBBITS\fP])"
.br
.ti -1c
.RI "template<typename O, int P = 0> I constexpr \fBMap\fP (I a) const"
.br
.ti -1c
.RI "template<I(*)(const I &) F> void \fBBuild\fP (I a)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBBITS\fP = N"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename I, int N> \fBRecLinTrans\fP (const I * p, \fBNum\fP< \fBBITS\fP > )\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<typename I, int N> \fBRecLinTrans\fP ()\fR [constexpr]\fP, \fR [default]\fP"

.SS "template<typename I, int N> \fBRecLinTrans\fP (const I(&) init[BITS])\fR [inline]\fP, \fR [constexpr]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename I, int N> template<I(*)(const I &) F> void Build (I a)\fR [inline]\fP"

.SS "template<typename I, int N> template<typename O, int P = 0> I constexpr Map (I a) const\fR [inline]\fP, \fR [constexpr]\fP"

.SH "Field Documentation"
.PP 
.SS "template<typename I, int N> int BITS = N\fR [static]\fP, \fR [constexpr]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
