.TH "RecLinTrans< I, N >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecLinTrans< I, N >
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename I, int\&.\&.\&. N>
.br
class RecLinTrans< I, N >"A linear transformation constructed using \fBLinTrans\fP tables for sections of bits\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
