.TH "src/leveldb/db/recovery_test.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/db/recovery_test.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'db/db_impl\&.h'\fP
.br
\fR#include 'db/filename\&.h'\fP
.br
\fR#include 'db/version_set\&.h'\fP
.br
\fR#include 'db/write_batch_internal\&.h'\fP
.br
\fR#include 'leveldb/db\&.h'\fP
.br
\fR#include 'leveldb/env\&.h'\fP
.br
\fR#include 'leveldb/write_batch\&.h'\fP
.br
\fR#include 'util/logging\&.h'\fP
.br
\fR#include 'util/testharness\&.h'\fP
.br
\fR#include 'util/testutil\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBRecoveryTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBRecoveryTest\fP, ManifestReused)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBRecoveryTest\fP, LargeManifestCompacted)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBRecoveryTest\fP, NoLogFiles)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBRecoveryTest\fP, LogFileReuse)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBRecoveryTest\fP, MultipleMemTables)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBRecoveryTest\fP, MultipleLogFiles)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBRecoveryTest\fP, ManifestMissing)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
