.TH "src/rpc/register.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rpc/register.h
.SH SYNOPSIS
.br
.PP
\fR#include <bitcoin\-build\-config\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterBlockchainRPCCommands\fP (\fBCRPCTable\fP &\fBtableRPC\fP)"
.br
.ti -1c
.RI "void \fBRegisterFeeRPCCommands\fP (\fBCRPCTable\fP &)"
.br
.ti -1c
.RI "void \fBRegisterMempoolRPCCommands\fP (\fBCRPCTable\fP &)"
.br
.ti -1c
.RI "void \fBRegisterMiningRPCCommands\fP (\fBCRPCTable\fP &\fBtableRPC\fP)"
.br
.ti -1c
.RI "void \fBRegisterNodeRPCCommands\fP (\fBCRPCTable\fP &)"
.br
.ti -1c
.RI "void \fBRegisterNetRPCCommands\fP (\fBCRPCTable\fP &)"
.br
.ti -1c
.RI "void \fBRegisterOutputScriptRPCCommands\fP (\fBCRPCTable\fP &)"
.br
.ti -1c
.RI "void \fBRegisterRawTransactionRPCCommands\fP (\fBCRPCTable\fP &\fBtableRPC\fP)"
.br
.ti -1c
.RI "void \fBRegisterSignMessageRPCCommands\fP (\fBCRPCTable\fP &)"
.br
.ti -1c
.RI "void \fBRegisterSignerRPCCommands\fP (\fBCRPCTable\fP &\fBtableRPC\fP)"
.br
.ti -1c
.RI "void \fBRegisterTxoutProofRPCCommands\fP (\fBCRPCTable\fP &)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void RegisterBlockchainRPCCommands (\fBCRPCTable\fP & tableRPC)"

.SS "void RegisterFeeRPCCommands (\fBCRPCTable\fP & t)"

.SS "void RegisterMempoolRPCCommands (\fBCRPCTable\fP & t)"

.SS "void RegisterMiningRPCCommands (\fBCRPCTable\fP & tableRPC)"

.SS "void RegisterNetRPCCommands (\fBCRPCTable\fP & t)"

.SS "void RegisterNodeRPCCommands (\fBCRPCTable\fP & t)"

.SS "void RegisterOutputScriptRPCCommands (\fBCRPCTable\fP & t)"

.SS "void RegisterRawTransactionRPCCommands (\fBCRPCTable\fP & tableRPC)"

.SS "void RegisterSignerRPCCommands (\fBCRPCTable\fP & tableRPC)"

.SS "void RegisterSignMessageRPCCommands (\fBCRPCTable\fP & t)"

.SS "void RegisterTxoutProofRPCCommands (\fBCRPCTable\fP & t)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
