.TH "RemovedMempoolTransactionInfo" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RemovedMempoolTransactionInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mempool_entry\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRemovedMempoolTransactionInfo\fP (const \fBCTxMemPoolEntry\fP &entry)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTransactionInfo\fP \fBinfo\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBRemovedMempoolTransactionInfo\fP (const \fBCTxMemPoolEntry\fP & entry)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBTransactionInfo\fP info"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
