.TH "src/test/fuzz/rpc.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/rpc.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <base58\&.h>\fP
.br
\fR#include <key\&.h>\fP
.br
\fR#include <key_io\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <psbt\&.h>\fP
.br
\fR#include <rpc/client\&.h>\fP
.br
\fR#include <rpc/request\&.h>\fP
.br
\fR#include <rpc/server\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <exception>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_rpc\fP ()"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (rpc,\&.\fBinit\fP=\fBinitialize_rpc\fP)"
.br
.ti -1c
.RI "template<typename C, typename \fBS\fP, typename UnaryOp> auto \fBJoin\fP (const C &container, const \fBS\fP &separator, UnaryOp unary_op)"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::string \fBToString\fP (const \fBT\fP &t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (rpc , \&. init = \fR\fBinitialize_rpc\fP\fP)"

.SS "void initialize_rpc ()"

.SS "template<typename C, typename \fBS\fP, typename UnaryOp> auto Join (const C & container, const \fBS\fP & separator, UnaryOp unary_op)"
Join all container items\&. Typically used to concatenate strings but accepts containers with elements of any type\&.

.PP
\fBParameters\fP
.RS 4
\fIcontainer\fP The items to join 
.br
\fIseparator\fP The separator 
.br
\fIunary_op\fP Apply this operator to each item 
.RE
.PP

.SS "template<typename \fBT\fP> std::string ToString (const \fBT\fP & t)"
Locale-independent version of std::to_string 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
