.TH "rpc_convert" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rpc_convert
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBCRPCConvertParam\fP * \fBFromPosition\fP (std::string_view method, size_t pos)"
.br
.ti -1c
.RI "const \fBCRPCConvertParam\fP * \fBFromName\fP (std::string_view method, std::string_view \fBname\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const \fBCRPCConvertParam\fP * FromName (std::string_view method, std::string_view name)"

.SS "const \fBCRPCConvertParam\fP * FromPosition (std::string_view method, size_t pos)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
