.TH "src/test/rpc_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/rpc_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <core_io\&.h>\fP
.br
\fR#include <interfaces/chain\&.h>\fP
.br
\fR#include <node/context\&.h>\fP
.br
\fR#include <rpc/blockchain\&.h>\fP
.br
\fR#include <rpc/client\&.h>\fP
.br
\fR#include <rpc/server\&.h>\fP
.br
\fR#include <rpc/util\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <any>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBHasJSON\fP"
.br
.ti -1c
.RI "class \fBRPCTestingSetup\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_namedparams)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_namedonlyparams)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_rawparams)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_togglenetwork)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_rawsign)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_createraw_op_return)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_format_monetary_values)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_parse_monetary_values)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_ban)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_convert_values_generatetoaddress)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_getblockstats_calculate_percentiles_by_weight)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (check_dup_param_names)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (help_example)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (rpc_arg_helper)"
.br
.ti -1c
.RI "std::vector< std::string > \fBSplitString\fP (std::string_view str, char sep)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (check_dup_param_names )"

.SS "BOOST_AUTO_TEST_CASE (help_example )"

.SS "BOOST_AUTO_TEST_CASE (rpc_arg_helper )"
Parameters with which the \fBRPCHelpMan\fP is instantiated

.PP
Check that \fRself\&.Arg\fP returns the same value as the \fRrequest\&.params\fP accessors
.SS "BOOST_AUTO_TEST_CASE (rpc_ban )"

.SS "BOOST_AUTO_TEST_CASE (rpc_convert_values_generatetoaddress )"

.SS "BOOST_AUTO_TEST_CASE (rpc_createraw_op_return )"

.SS "BOOST_AUTO_TEST_CASE (rpc_format_monetary_values )"

.SS "BOOST_AUTO_TEST_CASE (rpc_getblockstats_calculate_percentiles_by_weight )"

.SS "BOOST_AUTO_TEST_CASE (rpc_namedonlyparams )"

.SS "BOOST_AUTO_TEST_CASE (rpc_namedparams )"

.SS "BOOST_AUTO_TEST_CASE (rpc_parse_monetary_values )"

.SS "BOOST_AUTO_TEST_CASE (rpc_rawparams )"

.SS "BOOST_AUTO_TEST_CASE (rpc_rawsign )"

.SS "BOOST_AUTO_TEST_CASE (rpc_togglenetwork )"

.SS "std::vector< std::string > SplitString (std::string_view str, char sep)\fR [inline]\fP, \fR [nodiscard]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
