.TH "RPCConsole" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RPCConsole
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <rpcconsole\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMessageClass\fP { \fBMC_ERROR\fP, \fBMC_DEBUG\fP, \fBCMD_REQUEST\fP, \fBCMD_REPLY\fP, \fBCMD_ERROR\fP }"
.br
.ti -1c
.RI "enum class \fBTabTypes\fP { \fBINFO\fP, \fBCONSOLE\fP, \fBGRAPH\fP, \fBPEERS\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBclear\fP (bool keep_prompt=false)"
.br
.ti -1c
.RI "void \fBfontBigger\fP ()"
.br
.ti -1c
.RI "void \fBfontSmaller\fP ()"
.br
.ti -1c
.RI "void \fBsetFontSize\fP (int newSize)"
.br
.ti -1c
.RI "void \fBmessage\fP (int category, const QString &msg)"
.br
.ti -1c
.RI "void \fBmessage\fP (int category, const QString &message, bool html)"
.br
.ti -1c
.RI "void \fBsetNumConnections\fP (int count)"
.br
.ti -1c
.RI "void \fBsetNetworkActive\fP (bool networkActive)"
.br
.ti -1c
.RI "void \fBsetNumBlocks\fP (int count, const QDateTime &blockDate, double nVerificationProgress, \fBSyncType\fP synctype)"
.br
.ti -1c
.RI "void \fBsetMempoolSize\fP (long numberOfTxs, size_t dynUsage, size_t maxUsage)"
.br
.ti -1c
.RI "void \fBbrowseHistory\fP (int offset)"
.br
.ti -1c
.RI "void \fBscrollToEnd\fP ()"
.br
.ti -1c
.RI "void \fBdisconnectSelectedNode\fP ()"
.br
.ti -1c
.RI "void \fBbanSelectedNode\fP (int bantime)"
.br
.ti -1c
.RI "void \fBunbanSelectedNode\fP ()"
.br
.ti -1c
.RI "void \fBsetTabFocus\fP (enum \fBTabTypes\fP tabType)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRPCConsole\fP (\fBinterfaces::Node\fP &\fBnode\fP, const \fBPlatformStyle\fP *platformStyle, QWidget *parent)"
.br
.ti -1c
.RI "\fB~RPCConsole\fP ()"
.br
.ti -1c
.RI "void \fBsetClientModel\fP (\fBClientModel\fP *model=nullptr, int bestblock_height=0, int64_t bestblock_date=0, double verification_progress=0\&.0)"
.br
.ti -1c
.RI "std::vector< \fBTabTypes\fP > \fBtabs\fP () const"
.br
.ti -1c
.RI "QString \fBtabTitle\fP (\fBTabTypes\fP tab_type) const"
.br
.ti -1c
.RI "QKeySequence \fBtabShortcut\fP (\fBTabTypes\fP tab_type) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBRPCParseCommandLine\fP (\fBinterfaces::Node\fP *\fBnode\fP, std::string &strResult, const std::string &strCommand, bool fExecute, std::string *const pstrFilteredOut=nullptr, const QString &wallet_name={})"
.br
.ti -1c
.RI "static bool \fBRPCExecuteCommandLine\fP (\fBinterfaces::Node\fP &\fBnode\fP, std::string &strResult, const std::string &strCommand, std::string *const pstrFilteredOut=nullptr, const QString &wallet_name={})"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBeventFilter\fP (QObject *obj, QEvent *event) override"
.br
.ti -1c
.RI "void \fBkeyPressEvent\fP (QKeyEvent *) override"
.br
.ti -1c
.RI "void \fBchangeEvent\fP (QEvent *e) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Local Bitcoin RPC console\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMessageClass\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIMC_ERROR \fP
.TP
\f(BIMC_DEBUG \fP
.TP
\f(BICMD_REQUEST \fP
.TP
\f(BICMD_REPLY \fP
.TP
\f(BICMD_ERROR \fP
.SS "enum class \fBTabTypes\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIINFO \fP
.TP
\f(BICONSOLE \fP
.TP
\f(BIGRAPH \fP
.TP
\f(BIPEERS \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBRPCConsole\fP (\fBinterfaces::Node\fP & node, const \fBPlatformStyle\fP * platformStyle, QWidget * parent)\fR [explicit]\fP"

.SS "~\fBRPCConsole\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void banSelectedNode (int bantime)\fR [slot]\fP"
Ban a selected node on the Peers tab 
.SS "void browseHistory (int offset)\fR [slot]\fP"
Go forward or back in history 
.SS "void changeEvent (QEvent * e)\fR [override]\fP, \fR [protected]\fP"

.SS "void clear (bool keep_prompt = \fRfalse\fP)\fR [slot]\fP"

.SS "void disconnectSelectedNode ()\fR [slot]\fP"
Disconnect a selected node on the Peers tab 
.SS "bool eventFilter (QObject * obj, QEvent * event)\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.SS "void fontBigger ()\fR [slot]\fP"

.SS "void fontSmaller ()\fR [slot]\fP"

.SS "void keyPressEvent (QKeyEvent * event)\fR [override]\fP, \fR [protected]\fP"

.SS "void message (int category, const QString & message, bool html)\fR [slot]\fP"

.SS "void message (int category, const QString & msg)\fR [inline]\fP, \fR [slot]\fP"
Append the message to the message widget 
.SS "bool RPCExecuteCommandLine (\fBinterfaces::Node\fP & node, std::string & strResult, const std::string & strCommand, std::string *const pstrFilteredOut = \fRnullptr\fP, const QString & wallet_name = \fR{}\fP)\fR [inline]\fP, \fR [static]\fP"

.SS "bool RPCParseCommandLine (\fBinterfaces::Node\fP * node, std::string & strResult, const std::string & strCommand, bool fExecute, std::string *const pstrFilteredOut = \fRnullptr\fP, const QString & wallet_name = \fR{}\fP)\fR [static]\fP"
Split shell command line into a list of arguments and optionally execute the \fBcommand(s)\fP\&. Aims to emulate \fRbash\fP and friends\&.

.PP
.IP "\(bu" 2
Command nesting is possible with parenthesis; for example: validateaddress(getnewaddress())
.IP "\(bu" 2
Arguments are delimited with whitespace or comma
.IP "\(bu" 2
Extra whitespace at the beginning and end and between arguments will be ignored
.IP "\(bu" 2
Text can be "double" or 'single' quoted
.IP "\(bu" 2
The backslash \fR\\\fP is used as escape character
.IP "  \(bu" 4
Outside quotes, any character can be escaped
.IP "  \(bu" 4
Within double quotes, only escape \fR" and backslashes before a \\c "\fP or another backslash
.IP "  \(bu" 4
Within single quotes, no escaping is possible and no special interpretation takes place
.PP

.PP

.PP
\fBParameters\fP
.RS 4
\fInode\fP optional node to execute command on 
.br
\fIstrResult\fP stringified result from the executed \fBcommand(chain)\fP 
.br
\fIstrCommand\fP Command line to split 
.br
\fIfExecute\fP set true if you want the command to be executed 
.br
\fIpstrFilteredOut\fP Command line, filtered to remove any sensitive data 
.RE
.PP

.SS "void scrollToEnd ()\fR [slot]\fP"
Scroll console view to end 
.SS "void setClientModel (\fBClientModel\fP * model = \fRnullptr\fP, int bestblock_height = \fR0\fP, int64_t bestblock_date = \fR0\fP, double verification_progress = \fR0\&.0\fP)"

.SS "void setFontSize (int newSize)\fR [slot]\fP"

.SS "void setMempoolSize (long numberOfTxs, size_t dynUsage, size_t maxUsage)\fR [slot]\fP"
Set size (number of transactions and memory usage) of the mempool in the UI 
.SS "void setNetworkActive (bool networkActive)\fR [slot]\fP"
Set network state shown in the UI 
.SS "void setNumBlocks (int count, const QDateTime & blockDate, double nVerificationProgress, \fBSyncType\fP synctype)\fR [slot]\fP"
Set number of blocks and last block date shown in the UI 
.SS "void setNumConnections (int count)\fR [slot]\fP"
Set number of connections shown in the UI 
.SS "void setTabFocus (enum \fBTabTypes\fP tabType)\fR [slot]\fP"
set which tab has the focus (is visible) 
.SS "std::vector< \fBTabTypes\fP > tabs () const\fR [inline]\fP"

.SS "QKeySequence tabShortcut (\fBTabTypes\fP tab_type) const"

.SS "QString tabTitle (\fBTabTypes\fP tab_type) const"

.SS "void unbanSelectedNode ()\fR [slot]\fP"
Unban a selected node on the Bans tab 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
