.TH "RPCExamples" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RPCExamples
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRPCExamples\fP (std::string examples)"
.br
.ti -1c
.RI "std::string \fBToDescriptionString\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const std::string \fBm_examples\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBRPCExamples\fP (std::string examples)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string ToDescriptionString () const"

.SH "Field Documentation"
.PP 
.SS "const std::string m_examples"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
