.TH "RPCHelpMan" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RPCHelpMan
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBRPCMethodImpl\fP = std::function<\fBUniValue\fP(const \fBRPCHelpMan\fP&, const \fBJSONRPCRequest\fP&)>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRPCHelpMan\fP (std::string \fBname\fP, std::string description, std::vector< \fBRPCArg\fP > \fBargs\fP, \fBRPCResults\fP results, \fBRPCExamples\fP examples)"
.br
.ti -1c
.RI "\fBRPCHelpMan\fP (std::string \fBname\fP, std::string description, std::vector< \fBRPCArg\fP > \fBargs\fP, \fBRPCResults\fP results, \fBRPCExamples\fP examples, \fBRPCMethodImpl\fP fun)"
.br
.ti -1c
.RI "\fBUniValue\fP \fBHandleRequest\fP (const \fBJSONRPCRequest\fP &request) const"
.br
.ti -1c
.RI "template<typename R> auto \fBArg\fP (std::string_view key) const"
.br
.RI "Helper to get a required or default-valued request argument\&. "
.ti -1c
.RI "template<typename R> auto \fBMaybeArg\fP (std::string_view key) const"
.br
.RI "Helper to get an optional request argument\&. "
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "\fBUniValue\fP \fBGetArgMap\fP () const"
.br
.ti -1c
.RI "bool \fBIsValidNumArgs\fP (size_t num_args) const"
.br
.ti -1c
.RI "std::vector< std::pair< std::string, bool > > \fBGetArgNames\fP () const"
.br
.RI "Return list of arguments and whether they are named-only\&. "
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const std::string \fBm_name\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBRPCMethodImpl\fP = std::function<\fBUniValue\fP(const \fBRPCHelpMan\fP&, const \fBJSONRPCRequest\fP&)>"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBRPCHelpMan\fP (std::string name, std::string description, std::vector< \fBRPCArg\fP > args, \fBRPCResults\fP results, \fBRPCExamples\fP examples)"

.SS "\fBRPCHelpMan\fP (std::string name, std::string description, std::vector< \fBRPCArg\fP > args, \fBRPCResults\fP results, \fBRPCExamples\fP examples, \fBRPCMethodImpl\fP fun)"

.SH "Member Function Documentation"
.PP 
.SS "template<typename R> auto Arg (std::string_view key) const\fR [inline]\fP"

.PP
Helper to get a required or default-valued request argument\&. Use this function when the argument is required or when it has a default value\&. If the argument is optional and may not be provided, use MaybeArg instead\&.

.PP
This function only works during m_fun(), i\&.e\&., it should only be used in RPC method implementations\&. It internally checks whether the user-passed argument isNull() and parses (from JSON) and returns the user-passed argument, or the default value derived from the \fBRPCArg\fP documentation\&.

.PP
The instantiation of this helper for type R must match the corresponding \fBRPCArg::Type\fP\&.

.PP
\fBReturns\fP
.RS 4
The value of the RPC argument (or the default value) cast to type R\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBMaybeArg\fP \fBfor\fP handling optional arguments without default values\&. 
.RE
.PP

.SS "\fBUniValue\fP GetArgMap () const"
Return the named args that need to be converted from string to another JSON type 
.SS "std::vector< std::pair< std::string, bool > > GetArgNames () const"

.PP
Return list of arguments and whether they are named-only\&. 
.SS "\fBUniValue\fP HandleRequest (const \fBJSONRPCRequest\fP & request) const"

.SS "bool IsValidNumArgs (size_t num_args) const"
If the supplied number of args is neither too small nor too high 
.SS "template<typename R> auto MaybeArg (std::string_view key) const\fR [inline]\fP"

.PP
Helper to get an optional request argument\&. Use this function when the argument is optional and does not have a default value\&. If the argument is required or has a default value, use Arg instead\&.

.PP
This function only works during m_fun(), i\&.e\&., it should only be used in RPC method implementations\&. It internally checks whether the user-passed argument isNull() and parses (from JSON) and returns the user-passed argument, or a falsy value if no argument was passed\&.

.PP
The instantiation of this helper for type R must match the corresponding \fBRPCArg::Type\fP\&.

.PP
\fBReturns\fP
.RS 4
For trivially copyable types, a std::optional<R> is returned\&. For other types, a R* pointer to the argument is returned\&. If the argument is not provided, std::nullopt or a null pointer is returned\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBArg\fP \fBfor\fP handling arguments that are required or have a default value\&. 
.RE
.PP

.SS "std::string ToString () const"

.SH "Field Documentation"
.PP 
.SS "const std::string m_name"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
