.TH "RPCTestingSetup" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RPCTestingSetup
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestingSetup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniValue\fP \fBTransformParams\fP (const \fBUniValue\fP &params, std::vector< std::pair< std::string, bool > > arg_names) const"
.br
.ti -1c
.RI "\fBUniValue\fP \fBCallRPC\fP (std::string \fBargs\fP)"
.br
.in -1c

Public Member Functions inherited from \fBTestingSetup\fP
.in +1c
.ti -1c
.RI "\fBTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.in -1c

Public Member Functions inherited from \fBChainTestingSetup\fP
.in +1c
.ti -1c
.RI "\fBChainTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~ChainTestingSetup\fP ()"
.br
.ti -1c
.RI "void \fBLoadVerifyActivateChainstate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "void \fBSeedRandomForTest\fP (\fBSeedRand\fP seed)"
.br
.ti -1c
.RI "\fBBasicTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~BasicTestingSetup\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Data Fields inherited from \fBChainTestingSetup\fP
.in +1c
.ti -1c
.RI "\fBkernel::CacheSizes\fP \fBm_kernel_cache_sizes\fP {\fBnode::CalculateCacheSizes\fP(\fBm_args\fP)\&.\fBkernel\fP}"
.br
.ti -1c
.RI "bool \fBm_coins_db_in_memory\fP {true}"
.br
.ti -1c
.RI "bool \fBm_block_tree_db_in_memory\fP {true}"
.br
.ti -1c
.RI "std::function< void()> \fBm_make_chainman\fP {}"
.br
.in -1c

Data Fields inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "\fButil::SignalInterrupt\fP \fBm_interrupt\fP"
.br
.ti -1c
.RI "\fBnode::NodeContext\fP \fBm_node\fP"
.br
.ti -1c
.RI "\fBFastRandomContext\fP \fBm_rng\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_root\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_lock\fP"
.br
.ti -1c
.RI "bool \fBm_has_custom_datadir\fP {false}"
.br
.ti -1c
.RI "\fBArgsManager\fP \fBm_args\fP"
.br
.RI "Test-specific arguments and settings\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBUniValue\fP CallRPC (std::string args)"

.SS "\fBUniValue\fP TransformParams (const \fBUniValue\fP & params, std::vector< std::pair< std::string, bool > > arg_names) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
