.TH "SaltedTxidHasher" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaltedTxidHasher
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hasher\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSaltedTxidHasher\fP ()"
.br
.ti -1c
.RI "size_t \fBoperator()\fP (const \fBTxid\fP &txid) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSaltedTxidHasher\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "size_t operator() (const \fBTxid\fP & txid) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
