.TH "src/secp256k1/src/scalar.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/scalar.h
.SH SYNOPSIS
.br
.PP
\fR#include 'util\&.h'\fP
.br
\fR#include 'scalar_4x64\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSECP256K1_SCALAR_VERIFY\fP(r)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SECP256K1_SCALAR_VERIFY( r)"
\fBValue:\fP
.nf
secp256k1_scalar_verify(r)
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
