.TH "ScopedScheduler" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScopedScheduler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedScheduler\fP ()"
.br
.ti -1c
.RI "\fB~ScopedScheduler\fP ()"
.br
.ti -1c
.RI "void \fBMockForwardAndSync\fP (std::chrono::seconds duration)"
.br
.ti -1c
.RI "std::shared_ptr< \fBBCLog::LogRateLimiter\fP > \fBGetLimiter\fP (size_t max_bytes, std::chrono::seconds window)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCScheduler\fP \fBscheduler\fP {}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBScopedScheduler\fP ()\fR [inline]\fP"

.SS "~\fBScopedScheduler\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBBCLog::LogRateLimiter\fP > GetLimiter (size_t max_bytes, std::chrono::seconds window)\fR [inline]\fP"

.SS "void MockForwardAndSync (std::chrono::seconds duration)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBCScheduler\fP scheduler {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
