.TH "script_verify_flags" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
script_verify_flags
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <verify_flags\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_type\fP = uint64_t"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "consteval \fBscript_verify_flags\fP ()=default"
.br
.ti -1c
.RI "consteval \fBexplicit\fP (false) \fBscript_verify_flags\fP(\fBvalue_type\fP f)"
.br
.ti -1c
.RI "constexpr \fBexplicit\fP (false) \fBscript_verify_flags\fP(\fBscript_verify_flag_name\fP f)"
.br
.ti -1c
.RI "constexpr \fBscript_verify_flags\fP (const \fBscript_verify_flags\fP &)=default"
.br
.ti -1c
.RI "constexpr \fBscript_verify_flags\fP (\fBscript_verify_flags\fP &&)=default"
.br
.ti -1c
.RI "constexpr \fBscript_verify_flags\fP & \fBoperator=\fP (const \fBscript_verify_flags\fP &)=default"
.br
.ti -1c
.RI "constexpr \fBscript_verify_flags\fP & \fBoperator=\fP (\fBscript_verify_flags\fP &&)=default"
.br
.ti -1c
.RI "constexpr \fB~script_verify_flags\fP ()=default"
.br
.ti -1c
.RI "constexpr \fBvalue_type\fP \fBas_int\fP () const"
.br
.ti -1c
.RI "constexpr \fBscript_verify_flags\fP \fBoperator~\fP () const"
.br
.ti -1c
.RI "constexpr \fBscript_verify_flags\fP & \fBoperator|=\fP (\fBscript_verify_flags\fP vf)"
.br
.ti -1c
.RI "constexpr \fBscript_verify_flags\fP & \fBoperator&=\fP (\fBscript_verify_flags\fP vf)"
.br
.ti -1c
.RI "constexpr \fBoperator bool\fP () const"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (\fBscript_verify_flags\fP other) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr \fBscript_verify_flags\fP \fBfrom_int\fP (\fBvalue_type\fP f)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "constexpr \fBscript_verify_flags\fP \fBoperator|\fP (\fBscript_verify_flags\fP a, \fBscript_verify_flags\fP b)"
.br
.ti -1c
.RI "constexpr \fBscript_verify_flags\fP \fBoperator&\fP (\fBscript_verify_flags\fP a, \fBscript_verify_flags\fP b)"
.br
.ti -1c
.RI "constexpr std::strong_ordering \fBoperator<=>\fP (const \fBscript_verify_flags\fP &a, const \fBscript_verify_flags\fP &b) noexcept"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBvalue_type\fP = uint64_t"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBscript_verify_flags\fP ()\fR [consteval]\fP, \fR [default]\fP"

.SS "\fBscript_verify_flags\fP (const \fBscript_verify_flags\fP & )\fR [constexpr]\fP, \fR [default]\fP"

.SS "\fBscript_verify_flags\fP (\fBscript_verify_flags\fP && )\fR [constexpr]\fP, \fR [default]\fP"

.SS "~\fBscript_verify_flags\fP ()\fR [constexpr]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvalue_type\fP as_int () const\fR [inline]\fP, \fR [constexpr]\fP"

.SS "explicit (false )\fR [inline]\fP, \fR [constexpr]\fP"

.SS "explicit (false )\fR [inline]\fP, \fR [consteval]\fP"

.SS "constexpr \fBscript_verify_flags\fP from_int (\fBvalue_type\fP f)\fR [inline]\fP, \fR [static]\fP, \fR [constexpr]\fP"

.SS "operator bool () const\fR [inline]\fP, \fR [explicit]\fP, \fR [constexpr]\fP"

.SS "\fBscript_verify_flags\fP & operator&= (\fBscript_verify_flags\fP vf)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "\fBscript_verify_flags\fP & operator= (const \fBscript_verify_flags\fP & )\fR [constexpr]\fP, \fR [default]\fP"

.SS "\fBscript_verify_flags\fP & operator= (\fBscript_verify_flags\fP && )\fR [constexpr]\fP, \fR [default]\fP"

.SS "bool operator== (\fBscript_verify_flags\fP other) const\fR [inline]\fP, \fR [constexpr]\fP"

.SS "\fBscript_verify_flags\fP & operator|= (\fBscript_verify_flags\fP vf)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "\fBscript_verify_flags\fP operator~ () const\fR [inline]\fP, \fR [constexpr]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBscript_verify_flags\fP operator& (\fBscript_verify_flags\fP a, \fBscript_verify_flags\fP b)\fR [friend]\fP"

.SS "std::strong_ordering operator<=> (const \fBscript_verify_flags\fP & a, const \fBscript_verify_flags\fP & b)\fR [friend]\fP"
Compare two \fBscript_verify_flags\fP\&. <, >, <=, and >= are auto-generated from this\&. 
.SS "\fBscript_verify_flags\fP operator| (\fBscript_verify_flags\fP a, \fBscript_verify_flags\fP b)\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
