.TH "src/test/fuzz/script_sign.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/script_sign.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <chainparams\&.h>\fP
.br
\fR#include <key\&.h>\fP
.br
\fR#include <psbt\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <script/keyorigin\&.h>\fP
.br
\fR#include <script/sign\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <test/util/transaction_utils\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <map>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_script_sign\fP ()"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (script_sign,\&.\fBinit\fP=\fBinitialize_script_sign\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (script_sign , \&. init = \fR\fBinitialize_script_sign\fP\fP)"

.SS "void initialize_script_sign ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
