.TH "src/wallet/scriptpubkeyman.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/scriptpubkeyman.h
.SH SYNOPSIS
.br
.PP
\fR#include <addresstype\&.h>\fP
.br
\fR#include <common/messages\&.h>\fP
.br
\fR#include <common/signmessage\&.h>\fP
.br
\fR#include <common/types\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <musig\&.h>\fP
.br
\fR#include <node/types\&.h>\fP
.br
\fR#include <psbt\&.h>\fP
.br
\fR#include <script/descriptor\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br
\fR#include <util/result\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <wallet/crypter\&.h>\fP
.br
\fR#include <wallet/types\&.h>\fP
.br
\fR#include <wallet/walletdb\&.h>\fP
.br
\fR#include <wallet/walletutil\&.h>\fP
.br
\fR#include <boost/signals2/signal\&.hpp>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <unordered_map>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWalletStorage\fP"
.br
.ti -1c
.RI "struct \fBWalletDestination\fP"
.br
.ti -1c
.RI "class \fBScriptPubKeyMan\fP"
.br
.ti -1c
.RI "class \fBLegacyDataSPKM\fP"
.br
.ti -1c
.RI "class \fBLegacySigningProvider\fP"
.br
.ti -1c
.RI "class \fBDescriptorScriptPubKeyMan\fP"
.br
.ti -1c
.RI "struct \fBMigrationData\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< \fBCKeyID\fP > \fBGetAffectedKeys\fP (const \fBCScript\fP &spk, const \fBSigningProvider\fP &provider)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
