.TH "src/test/scriptnum_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/scriptnum_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <script/script\&.h>\fP
.br
\fR#include <test/scriptnum10\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <climits>\fP
.br
\fR#include <cstdint>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (creation)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (operators)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (creation )"

.SS "BOOST_AUTO_TEST_CASE (operators )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
