.TH "src/test/script_standard_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/script_standard_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/data/bip341_wallet_vectors\&.json\&.h>\fP
.br
\fR#include <addresstype\&.h>\fP
.br
\fR#include <key\&.h>\fP
.br
\fR#include <key_io\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br
\fR#include <script/solver\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <univalue\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (dest_default_is_no_dest)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_standard_Solver_success)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_standard_Solver_failure)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_standard_ExtractDestination)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_standard_GetScriptFor_)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_standard_taproot_builder)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (bip341_spk_test_vectors)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (bip341_spk_test_vectors )"

.SS "BOOST_AUTO_TEST_CASE (dest_default_is_no_dest )"

.SS "BOOST_AUTO_TEST_CASE (script_standard_ExtractDestination )"

.SS "BOOST_AUTO_TEST_CASE (script_standard_GetScriptFor_ )"

.SS "BOOST_AUTO_TEST_CASE (script_standard_Solver_failure )"

.SS "BOOST_AUTO_TEST_CASE (script_standard_Solver_success )"

.SS "BOOST_AUTO_TEST_CASE (script_standard_taproot_builder )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
