.TH "src/test/fuzz/script_interpreter.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/script_interpreter.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <script/interpreter\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBCastToBool\fP (const std::vector< unsigned char > &vch)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (script_interpreter)"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (sighash_cache)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool CastToBool (const std::vector< unsigned char > & vch)"

.SS "FUZZ_TARGET (script_interpreter )"

.SS "FUZZ_TARGET (sighash_cache )"
Differential fuzzing for SignatureHash with and without cache\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
