.TH "src/test/script_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/script_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/data/script_tests\&.json\&.h>\fP
.br
\fR#include <test/data/bip341_wallet_vectors\&.json\&.h>\fP
.br
\fR#include <common/system\&.h>\fP
.br
\fR#include <core_io\&.h>\fP
.br
\fR#include <key\&.h>\fP
.br
\fR#include <rpc/util\&.h>\fP
.br
\fR#include <script/interpreter\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <script/script_error\&.h>\fP
.br
\fR#include <script/sigcache\&.h>\fP
.br
\fR#include <script/sign\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br
\fR#include <script/solver\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/util/json\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <test/util/transaction_utils\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <secp256k1\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBScriptErrorDesc\fP"
.br
.ti -1c
.RI "struct \fBScriptTest\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHECK_SCRIPT_STATIC_SIZE\fP(\fBscript\fP,  expected_size)"
.br
.ti -1c
.RI "#define \fBCHECK_SCRIPT_DYNAMIC_SIZE\fP(\fBscript\fP,  expected_size,  expected_extra)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscript_verify_flags\fP \fBParseScriptFlags\fP (std::string strFlags)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_build)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_json_test)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_PushData)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_cltv_truncated)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_CHECKMULTISIG12)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_CHECKMULTISIG23)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_size_and_capacity_test)"
.br
.ti -1c
.RI "\fBSignatureData\fP \fBCombineSignatures\fP (const \fBCTxOut\fP &txout, const \fBCMutableTransaction\fP &tx, const \fBSignatureData\fP &scriptSig1, const \fBSignatureData\fP &scriptSig2)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_combineSigs)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (sign_invalid_miniscript)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (sign_paytoanchor)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_standard_push)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_IsPushOnly_on_invalid_scripts)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_GetScriptAsm)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBCScript\fP \fBToScript\fP (const \fBT\fP &byte_container)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_byte_array_u8_vector_equivalence)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_FindAndDelete)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (script_HasValidOps)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (bip341_keypath_test_vectors)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (compute_tapbranch)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (compute_tapleaf)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (formatscriptflags)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHECK_SCRIPT_DYNAMIC_SIZE( \fBscript\fP,  expected_size,  expected_extra)"
\fBValue:\fP
.nf
    do {                                                                 \\
        BOOST_CHECK_EQUAL((script)\&.size(), (expected_size));             \\
        BOOST_CHECK_EQUAL((script)\&.capacity(), (expected_extra));         \\
        BOOST_CHECK_EQUAL((script)\&.allocated_memory(), (expected_extra)); \\
    } while (0)
.PP
.fi

.SS "#define CHECK_SCRIPT_STATIC_SIZE( \fBscript\fP,  expected_size)"
\fBValue:\fP
.nf
    do {                                                                  \\
        BOOST_CHECK_EQUAL((script)\&.size(), (expected_size));              \\
        BOOST_CHECK_EQUAL((script)\&.capacity(), CScriptBase::STATIC_SIZE); \\
        BOOST_CHECK_EQUAL((script)\&.allocated_memory(), 0);                \\
    } while (0)
.PP
.fi

.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (bip341_keypath_test_vectors )"

.SS "BOOST_AUTO_TEST_CASE (compute_tapbranch )"

.SS "BOOST_AUTO_TEST_CASE (compute_tapleaf )"

.SS "BOOST_AUTO_TEST_CASE (formatscriptflags )"

.SS "BOOST_AUTO_TEST_CASE (script_build )"

.SS "BOOST_AUTO_TEST_CASE (script_byte_array_u8_vector_equivalence )"

.SS "BOOST_AUTO_TEST_CASE (script_CHECKMULTISIG12 )"

.SS "BOOST_AUTO_TEST_CASE (script_CHECKMULTISIG23 )"

.SS "BOOST_AUTO_TEST_CASE (script_cltv_truncated )"

.SS "BOOST_AUTO_TEST_CASE (script_combineSigs )"

.SS "BOOST_AUTO_TEST_CASE (script_FindAndDelete )"

.SS "BOOST_AUTO_TEST_CASE (script_GetScriptAsm )"

.SS "BOOST_AUTO_TEST_CASE (script_HasValidOps )"

.SS "BOOST_AUTO_TEST_CASE (script_IsPushOnly_on_invalid_scripts )"

.SS "BOOST_AUTO_TEST_CASE (script_json_test )"

.SS "BOOST_AUTO_TEST_CASE (script_PushData )"

.SS "BOOST_AUTO_TEST_CASE (script_size_and_capacity_test )"

.SS "BOOST_AUTO_TEST_CASE (script_standard_push )"

.SS "BOOST_AUTO_TEST_CASE (sign_invalid_miniscript )"
Reproduction of an exception incorrectly raised when parsing a public key inside a TapMiniscript\&. 
.SS "BOOST_AUTO_TEST_CASE (sign_paytoanchor )"

.SS "\fBSignatureData\fP CombineSignatures (const \fBCTxOut\fP & txout, const \fBCMutableTransaction\fP & tx, const \fBSignatureData\fP & scriptSig1, const \fBSignatureData\fP & scriptSig2)"

.SS "\fBscript_verify_flags\fP ParseScriptFlags (std::string strFlags)"

.SS "template<typename \fBT\fP> \fBCScript\fP ToScript (const \fBT\fP & byte_container)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
