.TH "ScriptExecutionData" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScriptExecutionData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <interpreter\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBm_tapleaf_hash_init\fP = false"
.br
.RI "Whether m_tapleaf_hash is initialized\&. "
.ti -1c
.RI "\fBuint256\fP \fBm_tapleaf_hash\fP"
.br
.RI "The tapleaf hash\&. "
.ti -1c
.RI "bool \fBm_codeseparator_pos_init\fP = false"
.br
.RI "Whether m_codeseparator_pos is initialized\&. "
.ti -1c
.RI "uint32_t \fBm_codeseparator_pos\fP"
.br
.RI "Opcode position of the last executed OP_CODESEPARATOR (or 0xFFFFFFFF if none executed)\&. "
.ti -1c
.RI "bool \fBm_annex_init\fP = false"
.br
.RI "Whether m_annex_present and (when needed) m_annex_hash are initialized\&. "
.ti -1c
.RI "bool \fBm_annex_present\fP"
.br
.RI "Whether an annex is present\&. "
.ti -1c
.RI "\fBuint256\fP \fBm_annex_hash\fP"
.br
.RI "Hash of the annex data\&. "
.ti -1c
.RI "bool \fBm_validation_weight_left_init\fP = false"
.br
.RI "Whether m_validation_weight_left is initialized\&. "
.ti -1c
.RI "int64_t \fBm_validation_weight_left\fP"
.br
.RI "How much validation weight is left (decremented for every successful non-empty signature check)\&. "
.ti -1c
.RI "std::optional< \fBuint256\fP > \fBm_output_hash\fP"
.br
.RI "The hash of the corresponding output\&. "
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP m_annex_hash"

.PP
Hash of the annex data\&. 
.SS "bool m_annex_init = false"

.PP
Whether m_annex_present and (when needed) m_annex_hash are initialized\&. 
.SS "bool m_annex_present"

.PP
Whether an annex is present\&. 
.SS "uint32_t m_codeseparator_pos"

.PP
Opcode position of the last executed OP_CODESEPARATOR (or 0xFFFFFFFF if none executed)\&. 
.SS "bool m_codeseparator_pos_init = false"

.PP
Whether m_codeseparator_pos is initialized\&. 
.SS "std::optional<\fBuint256\fP> m_output_hash"

.PP
The hash of the corresponding output\&. 
.SS "\fBuint256\fP m_tapleaf_hash"

.PP
The tapleaf hash\&. 
.SS "bool m_tapleaf_hash_init = false"

.PP
Whether m_tapleaf_hash is initialized\&. 
.SS "int64_t m_validation_weight_left"

.PP
How much validation weight is left (decremented for every successful non-empty signature check)\&. 
.SS "bool m_validation_weight_left_init = false"

.PP
Whether m_validation_weight_left is initialized\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
