.TH "ScriptCompression" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScriptCompression
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <compressor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream> void \fBSer\fP (Stream &s, const \fBCScript\fP &\fBscript\fP)"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnser\fP (Stream &s, \fBCScript\fP &\fBscript\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const unsigned int \fBnSpecialScripts\fP = 6"
.br
.in -1c
.SH "Detailed Description"
.PP 
Compact serializer for scripts\&.

.PP
It detects common cases and encodes them much more efficiently\&. 3 special cases are defined:
.IP "\(bu" 2
Pay to pubkey hash (encoded as 21 bytes)
.IP "\(bu" 2
Pay to script hash (encoded as 21 bytes)
.IP "\(bu" 2
Pay to pubkey starting with 0x02, 0x03 or 0x04 (encoded as 33 bytes)
.PP

.PP
Other scripts up to 121 bytes require 1 byte + script length\&. Above that, scripts up to 16505 bytes require 2 bytes + script length\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream> void Ser (Stream & s, const \fBCScript\fP & script)\fR [inline]\fP"

.SS "template<typename Stream> void Unser (Stream & s, \fBCScript\fP & script)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "const unsigned int nSpecialScripts = 6\fR [static]\fP"
make this static for now (there are only 6 special scripts defined) this can potentially be extended together with a new version for transactions, in which case this value becomes dependent on version and nHeight of the enclosing transaction\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
