.TH "secp256k1_musig_keyagg_cache" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_musig_keyagg_cache
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <secp256k1_musig\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBdata\fP [197]"
.br
.in -1c
.SH "Detailed Description"
.PP 
This module implements BIP 327 "MuSig2 for BIP340-compatibleMulti-Signatures" (https://github.com/bitcoin/bips/blob/master/bip-0327.mediawiki) v1\&.0\&.0\&. You can find an example demonstrating the musig module in \fBexamples/musig\&.c\fP\&.

.PP
The module also supports BIP 341 ("Taproot") public key tweaking\&.

.PP
It is recommended to read the documentation in this include file carefully\&. Further notes on API usage can be found in \fBdoc/musig\&.md\fP

.PP
Since the first version of MuSig is essentially replaced by MuSig2, we use MuSig, musig and MuSig2 synonymously unless noted otherwise\&. Opaque data structures

.PP
The exact representation of data inside the opaque data structures is implementation defined and not guaranteed to be portable between different platforms or versions\&. With the exception of \fR\fBsecp256k1_musig_secnonce\fP\fP, the data structures can be safely copied/moved\&. If you need to convert to a format suitable for storage, transmission, or comparison, use the corresponding serialization and parsing functions\&. Opaque data structure that caches information about public key aggregation\&.

.PP
Guaranteed to be 197 bytes in size\&. No serialization and parsing functions (yet)\&. 
.SH "Field Documentation"
.PP 
.SS "unsigned char data[197]"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
