.TH "secp256k1_modinv64_trans2x2" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_modinv64_trans2x2
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <modinv64_impl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int64_t \fBu\fP"
.br
.ti -1c
.RI "int64_t \fBv\fP"
.br
.ti -1c
.RI "int64_t \fBq\fP"
.br
.ti -1c
.RI "int64_t \fBr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int64_t q"

.SS "int64_t r"

.SS "int64_t u"

.SS "int64_t v"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
