.TH "secp256k1_keyagg_cache_internal" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_keyagg_cache_internal
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <keyagg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsecp256k1_ge\fP \fBpk\fP"
.br
.ti -1c
.RI "\fBsecp256k1_ge\fP \fBsecond_pk\fP"
.br
.ti -1c
.RI "unsigned char \fBpks_hash\fP [32]"
.br
.ti -1c
.RI "\fBsecp256k1_scalar\fP \fBtweak\fP"
.br
.ti -1c
.RI "int \fBparity_acc\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int parity_acc"

.SS "\fBsecp256k1_ge\fP pk"

.SS "unsigned char pks_hash[32]"

.SS "\fBsecp256k1_ge\fP second_pk"

.SS "\fBsecp256k1_scalar\fP tweak"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
