.TH "secp256k1_rfc6979_hmac_sha256" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_rfc6979_hmac_sha256
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hash\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBv\fP [32]"
.br
.ti -1c
.RI "unsigned char \fBk\fP [32]"
.br
.ti -1c
.RI "int \fBretry\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char k[32]"

.SS "int retry"

.SS "unsigned char v[32]"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
