.TH "secp256k1_keypair" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_keypair
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <secp256k1_extrakeys\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBdata\fP [96]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Opaque data structure that holds a keypair consisting of a secret and a public key\&.

.PP
The exact representation of data inside is implementation defined and not guaranteed to be portable between different platforms or versions\&. It is however guaranteed to be 96 bytes in size, and can be safely copied/moved\&. 
.SH "Field Documentation"
.PP 
.SS "unsigned char data[96]"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
