.TH "src/secp256k1/include/secp256k1_ecdh.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/include/secp256k1_ecdh.h
.SH SYNOPSIS
.br
.PP
\fR#include 'secp256k1\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int(* \fBsecp256k1_ecdh_hash_function\fP) (unsigned char *output, const unsigned char *x32, const unsigned char *y32, void *data)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSECP256K1_API\fP \fBSECP256K1_WARN_UNUSED_RESULT\fP int \fBsecp256k1_ecdh\fP (const \fBsecp256k1_context\fP *ctx, unsigned char *output, const \fBsecp256k1_pubkey\fP *pubkey, const unsigned char *seckey, \fBsecp256k1_ecdh_hash_function\fP hashfp, void *data) \fBSECP256K1_ARG_NONNULL\fP(1) \fBSECP256K1_ARG_NONNULL\fP(2) \fBSECP256K1_ARG_NONNULL\fP(3) \fBSECP256K1_ARG_NONNULL\fP(4)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSECP256K1_API\fP const \fBsecp256k1_ecdh_hash_function\fP \fBsecp256k1_ecdh_hash_function_sha256\fP"
.br
.ti -1c
.RI "\fBSECP256K1_API\fP const \fBsecp256k1_ecdh_hash_function\fP \fBsecp256k1_ecdh_hash_function_default\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int(* secp256k1_ecdh_hash_function) (unsigned char *output, const unsigned char *x32, const unsigned char *y32, void *data)"
A pointer to a function that hashes an EC point to obtain an ECDH secret

.PP
Returns: 1 if the point was successfully hashed\&. 0 will cause secp256k1_ecdh to fail and return 0\&. Other return values are not allowed, and the behaviour of secp256k1_ecdh is undefined for other return values\&. Out: output: pointer to an array to be filled by the function In: x32: pointer to a 32-byte x coordinate y32: pointer to a 32-byte y coordinate data: arbitrary data pointer that is passed through 
.SH "Function Documentation"
.PP 
.SS "\fBSECP256K1_API\fP \fBSECP256K1_WARN_UNUSED_RESULT\fP int secp256k1_ecdh (const \fBsecp256k1_context\fP * ctx, unsigned char * output, const \fBsecp256k1_pubkey\fP * pubkey, const unsigned char * seckey, \fBsecp256k1_ecdh_hash_function\fP hashfp, void * data)"
Compute an EC Diffie-Hellman secret in constant time

.PP
Returns: 1: exponentiation was successful 0: scalar was invalid (zero or overflow) or hashfp returned 0 Args: ctx: pointer to a context object\&. Out: output: pointer to an array to be filled by hashfp\&. In: pubkey: pointer to a \fBsecp256k1_pubkey\fP containing an initialized public key\&. seckey: a 32-byte scalar with which to multiply the point\&. hashfp: pointer to a hash function\&. If NULL, secp256k1_ecdh_hash_function_sha256 is used (in which case, 32 bytes will be written to output)\&. data: arbitrary data pointer that is passed through to hashfp (can be NULL for secp256k1_ecdh_hash_function_sha256)\&. 
.SH "Variable Documentation"
.PP 
.SS "\fBSECP256K1_API\fP const \fBsecp256k1_ecdh_hash_function\fP secp256k1_ecdh_hash_function_default"
A default ECDH hash function (currently equal to secp256k1_ecdh_hash_function_sha256)\&. Populates the output parameter with 32 bytes\&. 
.SS "\fBSECP256K1_API\fP const \fBsecp256k1_ecdh_hash_function\fP secp256k1_ecdh_hash_function_sha256"
An implementation of SHA256 hash function that applies to compressed public key\&. Populates the output parameter with 32 bytes\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
