.TH "secp256k1_scalar" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_scalar
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scalar_4x64\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBd\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBd\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A scalar modulo the group order of the secp256k1 curve\&. 
.SH "Field Documentation"
.PP 
.SS "uint64_t d[4]"

.SS "uint32_t d[8]"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
