.TH "secp256k1_pippenger_state" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_pippenger_state
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ecmult_impl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int * \fBwnaf_na\fP"
.br
.ti -1c
.RI "struct \fBsecp256k1_pippenger_point_state\fP * \fBps\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBsecp256k1_pippenger_point_state\fP* ps"

.SS "int* wnaf_na"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
