.TH "secp256k1_musig_pubkey_agg_ecmult_data" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_musig_pubkey_agg_ecmult_data
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <keyagg_impl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBsecp256k1_context\fP * \fBctx\fP"
.br
.ti -1c
.RI "unsigned char \fBpks_hash\fP [32]"
.br
.ti -1c
.RI "const \fBsecp256k1_pubkey\fP *const  * \fBpks\fP"
.br
.ti -1c
.RI "\fBsecp256k1_ge\fP \fBsecond_pk\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const \fBsecp256k1_context\fP* ctx"

.SS "const \fBsecp256k1_pubkey\fP* const* pks"

.SS "unsigned char pks_hash[32]"

.SS "\fBsecp256k1_ge\fP second_pk"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
