.TH "secp256k1_scratch_space_struct" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_scratch_space_struct
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scratch\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBmagic\fP [8]"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBalloc_size\fP"
.br
.ti -1c
.RI "size_t \fBmax_size\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t alloc_size"
amount that has been allocated (i\&.e\&. \fR\fBdata\fP + offset\fP is the next available pointer) 
.SS "void* data"
actual allocated data 
.SS "unsigned char magic[8]"
guard against interpreting this object as other types 
.SS "size_t max_size"
maximum size available to allocate 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
