.TH "secp256k1_uint128" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_uint128
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <int128_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBlo\fP"
.br
.ti -1c
.RI "uint64_t \fBhi\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint64_t hi"

.SS "uint64_t lo"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
