.TH "secp256k1_ge" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_ge
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <group\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsecp256k1_fe\fP \fBx\fP"
.br
.ti -1c
.RI "\fBsecp256k1_fe\fP \fBy\fP"
.br
.ti -1c
.RI "int \fBinfinity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A group element in affine coordinates on the secp256k1 curve, or occasionally on an isomorphic curve of the form y^2 = x^3 + 7*t^6\&. Note: For exhaustive test mode, secp256k1 is replaced by a small subgroup of a different curve\&. 
.SH "Field Documentation"
.PP 
.SS "int infinity"

.SS "\fBsecp256k1_fe\fP x"

.SS "\fBsecp256k1_fe\fP y"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
