.TH "Section" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Section
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSection\fP (const std::string &left, const std::string &right)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBm_left\fP"
.br
.ti -1c
.RI "const std::string \fBm_right\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A pair of strings that can be aligned (through padding) with other \fBSections\fP later on 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSection\fP (const std::string & left, const std::string & right)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::string m_left"

.SS "const std::string m_right"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
