.TH "Sections" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sections
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPushSection\fP (const \fBSection\fP &s)"
.br
.ti -1c
.RI "void \fBPush\fP (const \fBRPCArg\fP &arg, const size_t current_indent=5, const \fBOuterType\fP outer_type=\fBOuterType::NONE\fP)"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< \fBSection\fP > \fBm_sections\fP"
.br
.ti -1c
.RI "size_t \fBm_max_pad\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Keeps track of RPCArgs by transforming them into sections for the purpose of serializing everything to a single string 
.SH "Member Function Documentation"
.PP 
.SS "void Push (const \fBRPCArg\fP & arg, const size_t current_indent = \fR5\fP, const \fBOuterType\fP outer_type = \fR\fBOuterType::NONE\fP\fP)\fR [inline]\fP"
Recursive helper to translate an \fBRPCArg\fP into sections 
.SS "void PushSection (const \fBSection\fP & s)\fR [inline]\fP"

.SS "std::string ToString () const\fR [inline]\fP"
Concatenate all sections with proper padding 
.SH "Field Documentation"
.PP 
.SS "size_t m_max_pad {0}"

.SS "std::vector<\fBSection\fP> m_sections"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
