.TH "src/semaphore_grant.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/semaphore_grant.h
.SH SYNOPSIS
.br
.PP
\fR#include <semaphore>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCountingSemaphoreGrant< LeastMaxValue >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBBinarySemaphoreGrant\fP = \fBCountingSemaphoreGrant\fP<1>"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBBinarySemaphoreGrant\fP = \fBCountingSemaphoreGrant\fP<1>"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
