.TH "src/qt/sendcoinsentry.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/sendcoinsentry.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/sendcoinsentry\&.h>\fP
.br
\fR#include <qt/forms/ui_sendcoinsentry\&.h>\fP
.br
\fR#include <qt/addressbookpage\&.h>\fP
.br
\fR#include <qt/addresstablemodel\&.h>\fP
.br
\fR#include <qt/guiutil\&.h>\fP
.br
\fR#include <qt/optionsmodel\&.h>\fP
.br
\fR#include <qt/platformstyle\&.h>\fP
.br
\fR#include <qt/walletmodel\&.h>\fP
.br
\fR#include <QApplication>\fP
.br
\fR#include <QClipboard>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
