.TH "SequentialFile" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SequentialFile
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <env\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSequentialFile\fP ()=default"
.br
.ti -1c
.RI "\fBSequentialFile\fP (const \fBSequentialFile\fP &)=delete"
.br
.ti -1c
.RI "\fBSequentialFile\fP & \fBoperator=\fP (const \fBSequentialFile\fP &)=delete"
.br
.ti -1c
.RI "virtual \fB~SequentialFile\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBRead\fP (size_t n, \fBSlice\fP *result, char *scratch)=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBSkip\fP (uint64_t n)=0"
.br
.ti -1c
.RI "virtual std::string \fBGetName\fP () const=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSequentialFile\fP ()\fR [default]\fP"

.SS "\fBSequentialFile\fP (const \fBSequentialFile\fP & )\fR [delete]\fP"

.SS "~\fBSequentialFile\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::string GetName () const\fR [pure virtual]\fP"

.SS "\fBSequentialFile\fP & operator= (const \fBSequentialFile\fP & )\fR [delete]\fP"

.SS "virtual \fBStatus\fP Read (size_t n, \fBSlice\fP * result, char * scratch)\fR [pure virtual]\fP"

.SS "virtual \fBStatus\fP Skip (uint64_t n)\fR [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
