.TH "src/test/serfloat_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/serfloat_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <hash\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/serfloat\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <limits>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (double_serfloat_tests)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (doubles)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (double_serfloat_tests )"

.SS "BOOST_AUTO_TEST_CASE (doubles )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
