.TH "Serializable" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serializable
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <serialize\&.h>\fP
.SH "Concept definition"
.PP 

.nf
template<class T, class Stream>
concept Serializable =  requires(T a, Stream s) { a\&.Serialize(s); }
.PP
.fi
.SH "Detailed Description"
.PP 
If none of the specialized versions above matched, default to calling member function\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
