.TH "src/rpc/server_util.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rpc/server_util.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <rpc/server_util\&.h>\fP
.br
\fR#include <chain\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <net_processing\&.h>\fP
.br
\fR#include <node/context\&.h>\fP
.br
\fR#include <node/miner\&.h>\fP
.br
\fR#include <policy/fees/block_policy_estimator\&.h>\fP
.br
\fR#include <pow\&.h>\fP
.br
\fR#include <rpc/protocol\&.h>\fP
.br
\fR#include <rpc/request\&.h>\fP
.br
\fR#include <txmempool\&.h>\fP
.br
\fR#include <util/any\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <any>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBNodeContext\fP & \fBEnsureAnyNodeContext\fP (const std::any &context)"
.br
.ti -1c
.RI "\fBCTxMemPool\fP & \fBEnsureMemPool\fP (const \fBNodeContext\fP &\fBnode\fP)"
.br
.ti -1c
.RI "\fBCTxMemPool\fP & \fBEnsureAnyMemPool\fP (const std::any &context)"
.br
.ti -1c
.RI "\fBBanMan\fP & \fBEnsureBanman\fP (const \fBNodeContext\fP &\fBnode\fP)"
.br
.ti -1c
.RI "\fBBanMan\fP & \fBEnsureAnyBanman\fP (const std::any &context)"
.br
.ti -1c
.RI "\fBArgsManager\fP & \fBEnsureArgsman\fP (const \fBNodeContext\fP &\fBnode\fP)"
.br
.ti -1c
.RI "\fBArgsManager\fP & \fBEnsureAnyArgsman\fP (const std::any &context)"
.br
.ti -1c
.RI "\fBChainstateManager\fP & \fBEnsureChainman\fP (const \fBNodeContext\fP &\fBnode\fP)"
.br
.ti -1c
.RI "\fBChainstateManager\fP & \fBEnsureAnyChainman\fP (const std::any &context)"
.br
.ti -1c
.RI "\fBCBlockPolicyEstimator\fP & \fBEnsureFeeEstimator\fP (const \fBNodeContext\fP &\fBnode\fP)"
.br
.ti -1c
.RI "\fBCBlockPolicyEstimator\fP & \fBEnsureAnyFeeEstimator\fP (const std::any &context)"
.br
.ti -1c
.RI "\fBCConnman\fP & \fBEnsureConnman\fP (const \fBNodeContext\fP &\fBnode\fP)"
.br
.ti -1c
.RI "\fBinterfaces::Mining\fP & \fBEnsureMining\fP (const \fBNodeContext\fP &\fBnode\fP)"
.br
.ti -1c
.RI "\fBPeerManager\fP & \fBEnsurePeerman\fP (const \fBNodeContext\fP &\fBnode\fP)"
.br
.ti -1c
.RI "\fBAddrMan\fP & \fBEnsureAddrman\fP (const \fBNodeContext\fP &\fBnode\fP)"
.br
.ti -1c
.RI "\fBAddrMan\fP & \fBEnsureAnyAddrman\fP (const std::any &context)"
.br
.ti -1c
.RI "void \fBNextEmptyBlockIndex\fP (\fBCBlockIndex\fP &tip, const \fBConsensus::Params\fP &consensusParams, \fBCBlockIndex\fP &next_index)"
.br
.ti -1c
.RI "int64_t \fBUpdateTime\fP (\fBCBlockHeader\fP *pblock, const \fBConsensus::Params\fP &consensusParams, const \fBCBlockIndex\fP *pindexPrev)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAddrMan\fP & EnsureAddrman (const \fBNodeContext\fP & node)"

.SS "\fBAddrMan\fP & EnsureAnyAddrman (const std::any & context)"

.SS "\fBArgsManager\fP & EnsureAnyArgsman (const std::any & context)"

.SS "\fBBanMan\fP & EnsureAnyBanman (const std::any & context)"

.SS "\fBChainstateManager\fP & EnsureAnyChainman (const std::any & context)"

.SS "\fBCBlockPolicyEstimator\fP & EnsureAnyFeeEstimator (const std::any & context)"

.SS "\fBCTxMemPool\fP & EnsureAnyMemPool (const std::any & context)"

.SS "\fBNodeContext\fP & EnsureAnyNodeContext (const std::any & context)"

.SS "\fBArgsManager\fP & EnsureArgsman (const \fBNodeContext\fP & node)"

.SS "\fBBanMan\fP & EnsureBanman (const \fBNodeContext\fP & node)"

.SS "\fBChainstateManager\fP & EnsureChainman (const \fBNodeContext\fP & node)"

.SS "\fBCConnman\fP & EnsureConnman (const \fBNodeContext\fP & node)"

.SS "\fBCBlockPolicyEstimator\fP & EnsureFeeEstimator (const \fBNodeContext\fP & node)"

.SS "\fBCTxMemPool\fP & EnsureMemPool (const \fBNodeContext\fP & node)"

.SS "\fBinterfaces::Mining\fP & EnsureMining (const \fBNodeContext\fP & node)"

.SS "\fBPeerManager\fP & EnsurePeerman (const \fBNodeContext\fP & node)"

.SS "void NextEmptyBlockIndex (\fBCBlockIndex\fP & tip, const \fBConsensus::Params\fP & consensusParams, \fBCBlockIndex\fP & next_index)"
Return an empty block index on top of the tip, with height, time and nBits set 
.SS "int64_t UpdateTime (\fBCBlockHeader\fP * pblock, const \fBConsensus::Params\fP & consensusParams, const \fBCBlockIndex\fP * pindexPrev)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
