.TH "src/secp256k1/src/modules/musig/session.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/modules/musig/session.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./include/secp256k1\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./\&.\&./include/secp256k1_musig\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./scalar\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsecp256k1_musig_session_internal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
