.TH "src/policy/settings.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/policy/settings.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <policy/settings\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned int \fBnBytesPerSigOp\fP = DEFAULT_BYTES_PER_SIGOP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "unsigned int nBytesPerSigOp = DEFAULT_BYTES_PER_SIGOP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
