.TH "src/test/settings_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/settings_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/settings\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <test/util/str\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <map>\fP
.br
\fR#include <string>\fP
.br
\fR#include <system_error>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBMergeTestingSetup\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBcommon::SettingsValue\fP &a, const \fBcommon::SettingsValue\fP &b)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBcommon::SettingsValue\fP &value)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const std::pair< std::string, \fBcommon::SettingsValue\fP > &kv)"
.br
.ti -1c
.RI "void \fBWriteText\fP (const \fBfs::path\fP &path, const std::string &text)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (ReadWrite)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (Simple)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (NullOverride)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (Merge, \fBMergeTestingSetup\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::string \fBToString\fP (const \fBT\fP &t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (NullOverride )"

.SS "BOOST_AUTO_TEST_CASE (ReadWrite )"

.SS "BOOST_AUTO_TEST_CASE (Simple )"

.SS "BOOST_FIXTURE_TEST_CASE (Merge , \fBMergeTestingSetup\fP )"

.SS "std::ostream & operator<< (std::ostream & os, const \fBcommon::SettingsValue\fP & value)\fR [inline]\fP"

.SS "std::ostream & operator<< (std::ostream & os, const std::pair< std::string, \fBcommon::SettingsValue\fP > & kv)\fR [inline]\fP"

.SS "bool operator== (const \fBcommon::SettingsValue\fP & a, const \fBcommon::SettingsValue\fP & b)\fR [inline]\fP"

.SS "template<typename \fBT\fP> std::string ToString (const \fBT\fP & t)"
Locale-independent version of std::to_string 
.SS "void WriteText (const \fBfs::path\fP & path, const std::string & text)\fR [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
