.TH "sha256_arm_shani" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sha256_arm_shani
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTransform\fP (uint32_t *s, const unsigned char *chunk, size_t blocks)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Transform (uint32_t * s, const unsigned char * chunk, size_t blocks)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
