.TH "src/util/signalinterrupt.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/signalinterrupt.h
.SH SYNOPSIS
.br
.PP
\fR#include <util/tokenpipe\&.h>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <cstdlib>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSignalInterrupt\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButil\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
