.TH "src/qt/signverifymessagedialog.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/signverifymessagedialog.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/signverifymessagedialog\&.h>\fP
.br
\fR#include <qt/forms/ui_signverifymessagedialog\&.h>\fP
.br
\fR#include <qt/addressbookpage\&.h>\fP
.br
\fR#include <qt/guiutil\&.h>\fP
.br
\fR#include <qt/platformstyle\&.h>\fP
.br
\fR#include <qt/walletmodel\&.h>\fP
.br
\fR#include <common/signmessage\&.h>\fP
.br
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <key_io\&.h>\fP
.br
\fR#include <wallet/wallet\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include <variant>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <QClipboard>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
