.TH "src/common/signmessage.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/common/signmessage.h
.SH SYNOPSIS
.br
.PP
\fR#include <uint256\&.h>\fP
.br
\fR#include <string>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBMessageVerificationResult\fP { \fBERR_INVALID_ADDRESS\fP, \fBERR_ADDRESS_NO_KEY\fP, \fBERR_MALFORMED_SIGNATURE\fP, \fBERR_PUBKEY_NOT_RECOVERED\fP, \fBERR_NOT_SIGNED\fP, \fBOK\fP }"
.br
.ti -1c
.RI "enum class \fBSigningResult\fP { \fBOK\fP, \fBPRIVATE_KEY_NOT_AVAILABLE\fP, \fBSIGNING_FAILED\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBMessageVerificationResult\fP \fBMessageVerify\fP (const std::string &address, const std::string &signature, const std::string &message)"
.br
.ti -1c
.RI "bool \fBMessageSign\fP (const \fBCKey\fP &privkey, const std::string &message, std::string &signature)"
.br
.ti -1c
.RI "\fBuint256\fP \fBMessageHash\fP (const std::string &message)"
.br
.ti -1c
.RI "std::string \fBSigningResultString\fP (const \fBSigningResult\fP res)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBMESSAGE_MAGIC\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBMessageVerificationResult\fP\fR [strong]\fP"
The result of a signed message verification\&. Message verification takes as an input:
.IP "\(bu" 2
address (with whose private key the message is supposed to have been signed)
.IP "\(bu" 2
signature
.IP "\(bu" 2
message 
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIERR_INVALID_ADDRESS \fP
The provided address is invalid\&. 
.TP
\f(BIERR_ADDRESS_NO_KEY \fP
The provided address is valid but does not refer to a public key\&. 
.TP
\f(BIERR_MALFORMED_SIGNATURE \fP
The provided signature couldn't be parsed (maybe invalid base64)\&. 
.TP
\f(BIERR_PUBKEY_NOT_RECOVERED \fP
A public key could not be recovered from the provided signature and message\&. 
.TP
\f(BIERR_NOT_SIGNED \fP
The message was not signed with the private key of the provided address\&. 
.TP
\f(BIOK \fP
The message verification was successful\&. 
.SS "enum class \fBSigningResult\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIOK \fP
No error\&. 
.TP
\f(BIPRIVATE_KEY_NOT_AVAILABLE \fP
.TP
\f(BISIGNING_FAILED \fP
.SH "Function Documentation"
.PP 
.SS "\fBuint256\fP MessageHash (const std::string & message)"
Hashes a message for signing and verification in a manner that prevents inadvertently signing a transaction\&. 
.SS "bool MessageSign (const \fBCKey\fP & privkey, const std::string & message, std::string & signature)"
Sign a message\&. 
.PP
\fBParameters\fP
.RS 4
\fIprivkey\fP Private key to sign with\&. 
.br
\fImessage\fP The message to sign\&. 
.br
\fIsignature\fP Signature, base64 encoded, only set if true is returned\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if signing was successful\&. 
.RE
.PP

.SS "\fBMessageVerificationResult\fP MessageVerify (const std::string & address, const std::string & signature, const std::string & message)"
Verify a signed message\&. 
.PP
\fBParameters\fP
.RS 4
\fIaddress\fP Signer's bitcoin address, it must refer to a public key\&. 
.br
\fIsignature\fP The signature in base64 format\&. 
.br
\fImessage\fP The message that was signed\&. 
.RE
.PP
\fBReturns\fP
.RS 4
result code 
.RE
.PP

.SS "std::string SigningResultString (const \fBSigningResult\fP res)"

.SH "Variable Documentation"
.PP 
.SS "const std::string MESSAGE_MAGIC\fR [extern]\fP"
Text used to signify that a signed message follows and to prevent inadvertently signing a transaction\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
