.TH "SigningProvider" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SigningProvider
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <signingprovider\&.h>\fP
.PP
Inherited by \fBFillableSigningProvider\fP, \fBFlatSigningProvider\fP, \fBHidingSigningProvider\fP, \fBMultiSigningProvider\fP, and \fBLegacySigningProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SigningProvider\fP ()=default"
.br
.ti -1c
.RI "virtual bool \fBGetCScript\fP (const \fBCScriptID\fP &scriptid, \fBCScript\fP &\fBscript\fP) const"
.br
.ti -1c
.RI "virtual bool \fBHaveCScript\fP (const \fBCScriptID\fP &scriptid) const"
.br
.ti -1c
.RI "virtual bool \fBGetPubKey\fP (const \fBCKeyID\fP &address, \fBCPubKey\fP &pubkey) const"
.br
.ti -1c
.RI "virtual bool \fBGetKey\fP (const \fBCKeyID\fP &address, \fBCKey\fP &key) const"
.br
.ti -1c
.RI "virtual bool \fBHaveKey\fP (const \fBCKeyID\fP &address) const"
.br
.ti -1c
.RI "virtual bool \fBGetKeyOrigin\fP (const \fBCKeyID\fP &keyid, \fBKeyOriginInfo\fP &info) const"
.br
.ti -1c
.RI "virtual bool \fBGetTaprootSpendData\fP (const \fBXOnlyPubKey\fP &output_key, \fBTaprootSpendData\fP &spenddata) const"
.br
.ti -1c
.RI "virtual bool \fBGetTaprootBuilder\fP (const \fBXOnlyPubKey\fP &output_key, \fBTaprootBuilder\fP &builder) const"
.br
.ti -1c
.RI "virtual std::vector< \fBCPubKey\fP > \fBGetMuSig2ParticipantPubkeys\fP (const \fBCPubKey\fP &pubkey) const"
.br
.ti -1c
.RI "virtual std::map< \fBCPubKey\fP, std::vector< \fBCPubKey\fP > > \fBGetAllMuSig2ParticipantPubkeys\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetMuSig2SecNonce\fP (const \fBuint256\fP &id, \fBMuSig2SecNonce\fP &&\fBnonce\fP) const"
.br
.ti -1c
.RI "virtual std::optional< std::reference_wrapper< \fBMuSig2SecNonce\fP > > \fBGetMuSig2SecNonce\fP (const \fBuint256\fP &session_id) const"
.br
.ti -1c
.RI "virtual void \fBDeleteMuSig2Session\fP (const \fBuint256\fP &session_id) const"
.br
.ti -1c
.RI "bool \fBGetKeyByXOnly\fP (const \fBXOnlyPubKey\fP &pubkey, \fBCKey\fP &key) const"
.br
.ti -1c
.RI "bool \fBGetPubKeyByXOnly\fP (const \fBXOnlyPubKey\fP &pubkey, \fBCPubKey\fP &out) const"
.br
.ti -1c
.RI "bool \fBGetKeyOriginByXOnly\fP (const \fBXOnlyPubKey\fP &pubkey, \fBKeyOriginInfo\fP &info) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
An interface to be implemented by keystores that support signing\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBSigningProvider\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void DeleteMuSig2Session (const \fBuint256\fP & session_id) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFlatSigningProvider\fP, and \fBHidingSigningProvider\fP\&.
.SS "virtual std::map< \fBCPubKey\fP, std::vector< \fBCPubKey\fP > > GetAllMuSig2ParticipantPubkeys () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFlatSigningProvider\fP, and \fBHidingSigningProvider\fP\&.
.SS "virtual bool GetCScript (const \fBCScriptID\fP & scriptid, \fBCScript\fP & script) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFillableSigningProvider\fP, \fBFlatSigningProvider\fP, \fBHidingSigningProvider\fP, \fBMultiSigningProvider\fP, and \fBLegacySigningProvider\fP\&.
.SS "virtual bool GetKey (const \fBCKeyID\fP & address, \fBCKey\fP & key) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFillableSigningProvider\fP, \fBFlatSigningProvider\fP, \fBHidingSigningProvider\fP, \fBMultiSigningProvider\fP, \fBLegacyDataSPKM\fP, and \fBLegacySigningProvider\fP\&.
.SS "bool GetKeyByXOnly (const \fBXOnlyPubKey\fP & pubkey, \fBCKey\fP & key) const\fR [inline]\fP"

.SS "virtual bool GetKeyOrigin (const \fBCKeyID\fP & keyid, \fBKeyOriginInfo\fP & info) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFlatSigningProvider\fP, \fBHidingSigningProvider\fP, \fBMultiSigningProvider\fP, \fBLegacyDataSPKM\fP, and \fBLegacySigningProvider\fP\&.
.SS "bool GetKeyOriginByXOnly (const \fBXOnlyPubKey\fP & pubkey, \fBKeyOriginInfo\fP & info) const\fR [inline]\fP"

.SS "virtual std::vector< \fBCPubKey\fP > GetMuSig2ParticipantPubkeys (const \fBCPubKey\fP & pubkey) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFlatSigningProvider\fP, and \fBHidingSigningProvider\fP\&.
.SS "virtual std::optional< std::reference_wrapper< \fBMuSig2SecNonce\fP > > GetMuSig2SecNonce (const \fBuint256\fP & session_id) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFlatSigningProvider\fP, and \fBHidingSigningProvider\fP\&.
.SS "virtual bool GetPubKey (const \fBCKeyID\fP & address, \fBCPubKey\fP & pubkey) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFillableSigningProvider\fP, \fBFlatSigningProvider\fP, \fBHidingSigningProvider\fP, \fBMultiSigningProvider\fP, \fBLegacyDataSPKM\fP, and \fBLegacySigningProvider\fP\&.
.SS "bool GetPubKeyByXOnly (const \fBXOnlyPubKey\fP & pubkey, \fBCPubKey\fP & out) const\fR [inline]\fP"

.SS "virtual bool GetTaprootBuilder (const \fBXOnlyPubKey\fP & output_key, \fBTaprootBuilder\fP & builder) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFlatSigningProvider\fP, \fBHidingSigningProvider\fP, and \fBMultiSigningProvider\fP\&.
.SS "virtual bool GetTaprootSpendData (const \fBXOnlyPubKey\fP & output_key, \fBTaprootSpendData\fP & spenddata) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFlatSigningProvider\fP, \fBHidingSigningProvider\fP, and \fBMultiSigningProvider\fP\&.
.SS "virtual bool HaveCScript (const \fBCScriptID\fP & scriptid) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFillableSigningProvider\fP, and \fBLegacySigningProvider\fP\&.
.SS "virtual bool HaveKey (const \fBCKeyID\fP & address) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFillableSigningProvider\fP, \fBFlatSigningProvider\fP, \fBLegacyDataSPKM\fP, and \fBLegacySigningProvider\fP\&.
.SS "virtual void SetMuSig2SecNonce (const \fBuint256\fP & id, \fBMuSig2SecNonce\fP && nonce) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBFlatSigningProvider\fP, and \fBHidingSigningProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
