.TH "src/test/sigopcount_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/sigopcount_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <addresstype\&.h>\fP
.br
\fR#include <coins\&.h>\fP
.br
\fR#include <consensus/consensus\&.h>\fP
.br
\fR#include <consensus/tx_verify\&.h>\fP
.br
\fR#include <key\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <script/interpreter\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <script/solver\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (GetSigOpCount)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (GetTxSigOpCost)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (GetSigOpCount )"

.SS "BOOST_AUTO_TEST_CASE (GetTxSigOpCost )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
