.TH "SingleEntryCacheTest" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SingleEntryCacheTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleEntryCacheTest\fP (const \fBCAmount\fP base_value, const \fBMaybeCoin\fP &cache_coin)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCCoinsView\fP \fBroot\fP"
.br
.ti -1c
.RI "CCoinsViewCacheTest \fBbase\fP {&\fBroot\fP}"
.br
.ti -1c
.RI "CCoinsViewCacheTest \fBcache\fP {&\fBbase\fP}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSingleEntryCacheTest\fP (const \fBCAmount\fP base_value, const \fBMaybeCoin\fP & cache_coin)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "CCoinsViewCacheTest base {&\fBroot\fP}"

.SS "CCoinsViewCacheTest cache {&\fBbase\fP}"

.SS "\fBCCoinsView\fP root"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
