.TH "src/crypto/siphash.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/crypto/siphash.h
.SH SYNOPSIS
.br
.PP
\fR#include <array>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <span>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSipHashState\fP"
.br
.ti -1c
.RI "class \fBCSipHasher\fP"
.br
.ti -1c
.RI "class \fBPresaltedSipHasher\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
