.TH "SipHashState" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SipHashState
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <siphash\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSipHashState\fP (uint64_t k0, uint64_t k1) noexcept"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::array< uint64_t, 4 > \fBv\fP {}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Shared SipHash internal state v[0\&.\&.3], initialized from (k0, k1)\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSipHashState\fP (uint64_t k0, uint64_t k1)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SH "Field Documentation"
.PP 
.SS "std::array<uint64_t, 4> v {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
