.TH "SizeComputer" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SizeComputer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <serialize\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSizeComputer\fP ()=default"
.br
.ti -1c
.RI "void \fBwrite\fP (std::span< const std::byte > src)"
.br
.ti -1c
.RI "void \fBseek\fP (uint64_t num)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBSizeComputer\fP & \fBoperator<<\fP (const \fBT\fP &obj)"
.br
.ti -1c
.RI "uint64_t \fBsize\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBm_size\fP {0}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSizeComputer\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBT\fP> \fBSizeComputer\fP & operator<< (const \fBT\fP & obj)\fR [inline]\fP"

.SS "void seek (uint64_t num)\fR [inline]\fP"
Pretend this many bytes are written, without specifying them\&. 
.SS "uint64_t size () const\fR [inline]\fP"

.SS "void write (std::span< const std::byte > src)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "uint64_t m_size {0}\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
