.TH "SketchImpl< F >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SketchImpl< F >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sketch_impl\&.h>\fP
.PP
Inherits \fBSketch\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBSketchImpl\fP (int implementation, int bits, const Args &\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "size_t \fBSyndromes\fP () const override"
.br
.ti -1c
.RI "void \fBInit\fP (size_t count) override"
.br
.ti -1c
.RI "void \fBAdd\fP (uint64_t val) override"
.br
.ti -1c
.RI "void \fBSerialize\fP (unsigned char *ptr) const override"
.br
.ti -1c
.RI "void \fBDeserialize\fP (const unsigned char *ptr) override"
.br
.ti -1c
.RI "int \fBDecode\fP (int max_count, uint64_t *out) const override"
.br
.ti -1c
.RI "size_t \fBMerge\fP (const \fBSketch\fP *other_sketch) override"
.br
.ti -1c
.RI "void \fBSetSeed\fP (uint64_t seed) override"
.br
.in -1c

Public Member Functions inherited from \fBSketch\fP
.in +1c
.ti -1c
.RI "\fBSketch\fP (int implementation, int bits)"
.br
.ti -1c
.RI "void \fBReady\fP ()"
.br
.ti -1c
.RI "void \fBCheck\fP () const"
.br
.ti -1c
.RI "void \fBUnReady\fP ()"
.br
.ti -1c
.RI "int \fBImplementation\fP () const"
.br
.ti -1c
.RI "int \fBBits\fP () const"
.br
.ti -1c
.RI "virtual \fB~Sketch\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename F> template<typename\&.\&.\&. Args> \fBSketchImpl\fP (int implementation, int bits, const Args &\&.\&.\&. args)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename F> void Add (uint64_t val)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBSketch\fP\&.
.SS "template<typename F> int Decode (int max_count, uint64_t * out) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBSketch\fP\&.
.SS "template<typename F> void Deserialize (const unsigned char * ptr)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBSketch\fP\&.
.SS "template<typename F> void \fBInit\fP (size_t count)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBSketch\fP\&.
.SS "template<typename F> size_t Merge (const \fBSketch\fP * other_sketch)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBSketch\fP\&.
.SS "template<typename F> void Serialize (unsigned char * ptr) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBSketch\fP\&.
.SS "template<typename F> void SetSeed (uint64_t seed)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBSketch\fP\&.
.SS "template<typename F> size_t Syndromes () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBSketch\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
