.TH "Sock::EqualSharedPtrSock" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sock::EqualSharedPtrSock
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sock\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const std::shared_ptr< const \fBSock\fP > &lhs, const std::shared_ptr< const \fBSock\fP > &rhs) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool operator() (const std::shared_ptr< const \fBSock\fP > & lhs, const std::shared_ptr< const \fBSock\fP > & rhs) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
