.TH "SourceLocationEqual" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceLocationEqual
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <logging\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBSourceLocation\fP &lhs, const \fBSourceLocation\fP &rhs) const noexcept"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool operator() (const \fBSourceLocation\fP & lhs, const \fBSourceLocation\fP & rhs) const\fR [inline]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
