.TH "SourceLocation" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceLocation \- Like std::source_location, but allowing to override the function name\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <logging\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSourceLocation\fP (const char *func, std::source_location loc=std::source_location::current())"
.br
.ti -1c
.RI "std::string_view \fBfile_name\fP () const"
.br
.ti -1c
.RI "std::uint_least32_t \fBline\fP () const"
.br
.ti -1c
.RI "std::string_view \fBfunction_name_short\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Like std::source_location, but allowing to override the function name\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSourceLocation\fP (const char * func, std::source_location loc = \fRstd::source_location::current()\fP)\fR [inline]\fP"
The func argument must be constructed from the C++11 \fBfunc\fP macro\&. Ref: https://en.cppreference.com/w/cpp/language/function.html#func Non-static string literals are not supported\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::string_view file_name () const\fR [inline]\fP"

.SS "std::string_view function_name_short () const\fR [inline]\fP"

.SS "std::uint_least32_t line () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
