.TH "SpannableYes" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpannableYes
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int * \fBdata\fP ()"
.br
.ti -1c
.RI "int * \fBbegin\fP ()"
.br
.ti -1c
.RI "int * \fBend\fP ()"
.br
.ti -1c
.RI "size_t \fBsize\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int * begin ()"

.SS "int * data ()"

.SS "int * end ()"

.SS "size_t size ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
