.TH "SpanReader" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpanReader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <streams\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpanReader\fP (std::span< const unsigned char > data)"
.br
.ti -1c
.RI "\fBSpanReader\fP (std::span< const std::byte > data)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBSpanReader\fP & \fBoperator>>\fP (\fBT\fP &&obj)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "void \fBread\fP (std::span< std::byte > dst)"
.br
.ti -1c
.RI "void \fBignore\fP (size_t n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Minimal stream for reading from an existing byte array by std::span\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSpanReader\fP (std::span< const unsigned char > data)\fR [inline]\fP, \fR [explicit]\fP"

.PP
\fBParameters\fP
.RS 4
\fIdata\fP Referenced byte vector to overwrite/append 
.RE
.PP

.SS "\fBSpanReader\fP (std::span< const std::byte > data)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool empty () const\fR [inline]\fP"

.SS "void ignore (size_t n)\fR [inline]\fP"

.SS "template<typename \fBT\fP> \fBSpanReader\fP & operator>> (\fBT\fP && obj)\fR [inline]\fP"

.SS "void read (std::span< std::byte > dst)\fR [inline]\fP"

.SS "size_t size () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
