.TH "Ignore" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ignore
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP> \fBIgnore\fP (\fBT\fP &&)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBT\fP> Ignore (\fBT\fP && )\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
