.TH "src/wallet/spend.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/spend.h
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <policy/fees/block_policy_estimator\&.h>\fP
.br
\fR#include <util/result\&.h>\fP
.br
\fR#include <wallet/coinselection\&.h>\fP
.br
\fR#include <wallet/transaction\&.h>\fP
.br
\fR#include <wallet/wallet\&.h>\fP
.br
\fR#include <map>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <set>\fP
.br
\fR#include <unordered_set>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTxSize\fP"
.br
.ti -1c
.RI "struct \fBCoinsResult\fP"
.br
.ti -1c
.RI "struct \fBCoinFilterParams\fP"
.br
.ti -1c
.RI "struct \fBSelectionFilter\fP"
.br
.ti -1c
.RI "struct \fBPreSelectedInputs\fP"
.br
.ti -1c
.RI "struct \fBCreatedTransactionResult\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBCalculateMaximumSignedInputSize\fP (const \fBCTxOut\fP &txout, const \fBCWallet\fP *\fBwallet\fP, const \fBCCoinControl\fP *coin_control)"
.br
.ti -1c
.RI "int \fBCalculateMaximumSignedInputSize\fP (const \fBCTxOut\fP &txout, const \fBCOutPoint\fP outpoint, const \fBSigningProvider\fP *provider, bool can_grind_r, const \fBCCoinControl\fP *coin_control)"
.br
.ti -1c
.RI "\fBTxSize\fP \fBCalculateMaximumSignedTxSize\fP (const \fBCTransaction\fP &tx, const \fBCWallet\fP *\fBwallet\fP, const std::vector< \fBCTxOut\fP > &txouts, const \fBCCoinControl\fP *coin_control)"
.br
.ti -1c
.RI "\fBTxSize\fP \fBCalculateMaximumSignedTxSize\fP (const \fBCTransaction\fP &tx, const \fBCWallet\fP *\fBwallet\fP, const \fBCCoinControl\fP *coin_control=nullptr) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(\fBwallet\fP \-> cs_wallet)"
.br
.ti -1c
.RI "\fBCoinsResult\fP \fBAvailableCoins\fP (const \fBCWallet\fP &\fBwallet\fP, const \fBCCoinControl\fP *coinControl, std::optional< \fBCFeeRate\fP > feerate, const \fBCoinFilterParams\fP &params)"
.br
.ti -1c
.RI "const \fBCTxOut\fP & \fBFindNonChangeParentOutput\fP (const \fBCWallet\fP &\fBwallet\fP, const \fBCOutPoint\fP &outpoint)"
.br
.ti -1c
.RI "std::map< \fBCTxDestination\fP, std::vector< \fBCOutput\fP > > \fBListCoins\fP (const \fBCWallet\fP &\fBwallet\fP)"
.br
.ti -1c
.RI "\fBFilteredOutputGroups\fP \fBGroupOutputs\fP (const \fBCWallet\fP &\fBwallet\fP, const \fBCoinsResult\fP &coins, const \fBCoinSelectionParams\fP &params, const std::vector< \fBSelectionFilter\fP > &filters)"
.br
.ti -1c
.RI "\fButil::Result\fP< \fBSelectionResult\fP > \fBAttemptSelection\fP (\fBinterfaces::Chain\fP &chain, const \fBCAmount\fP &nTargetValue, \fBOutputGroupTypeMap\fP &groups, const \fBCoinSelectionParams\fP &coin_selection_params, bool allow_mixed_output_types)"
.br
.ti -1c
.RI "\fButil::Result\fP< \fBSelectionResult\fP > \fBChooseSelectionResult\fP (\fBinterfaces::Chain\fP &chain, const \fBCAmount\fP &nTargetValue, \fBGroups\fP &groups, const \fBCoinSelectionParams\fP &coin_selection_params)"
.br
.ti -1c
.RI "\fButil::Result\fP< \fBPreSelectedInputs\fP > \fBFetchSelectedInputs\fP (const \fBCWallet\fP &\fBwallet\fP, const \fBCCoinControl\fP &coin_control, const \fBCoinSelectionParams\fP &coin_selection_params)"
.br
.ti -1c
.RI "\fButil::Result\fP< \fBSelectionResult\fP > \fBAutomaticCoinSelection\fP (const \fBCWallet\fP &\fBwallet\fP, \fBCoinsResult\fP &available_coins, const \fBCAmount\fP &value_to_select, const \fBCoinSelectionParams\fP &coin_selection_params)"
.br
.ti -1c
.RI "\fButil::Result\fP< \fBSelectionResult\fP > \fBSelectCoins\fP (const \fBCWallet\fP &\fBwallet\fP, \fBCoinsResult\fP &available_coins, const \fBPreSelectedInputs\fP &pre_set_inputs, const \fBCAmount\fP &nTargetValue, const \fBCCoinControl\fP &coin_control, const \fBCoinSelectionParams\fP &coin_selection_params)"
.br
.ti -1c
.RI "void \fBDiscourageFeeSniping\fP (\fBCMutableTransaction\fP &tx, \fBFastRandomContext\fP &rng_fast, \fBinterfaces::Chain\fP &chain, const \fBuint256\fP &block_hash, int block_height)"
.br
.ti -1c
.RI "\fButil::Result\fP< \fBCreatedTransactionResult\fP > \fBCreateTransaction\fP (\fBCWallet\fP &\fBwallet\fP, const std::vector< \fBCRecipient\fP > &vecSend, std::optional< unsigned int > change_pos, const \fBCCoinControl\fP &coin_control, bool sign)"
.br
.ti -1c
.RI "\fButil::Result\fP< \fBCreatedTransactionResult\fP > \fBFundTransaction\fP (\fBCWallet\fP &\fBwallet\fP, const \fBCMutableTransaction\fP &tx, const std::vector< \fBCRecipient\fP > &vecSend, std::optional< unsigned int > change_pos, bool lockUnspents, \fBCCoinControl\fP coinControl)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
