.TH "SplashScreen" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashScreen
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <splashscreen\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBshowMessage\fP (const QString &message, int alignment, const QColor &color)"
.br
.ti -1c
.RI "void \fBhandleLoadWallet\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashScreen\fP (const \fBNetworkStyle\fP *networkStyle)"
.br
.ti -1c
.RI "\fB~SplashScreen\fP ()"
.br
.ti -1c
.RI "void \fBsetNode\fP (\fBinterfaces::Node\fP &\fBnode\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event) override"
.br
.ti -1c
.RI "void \fBcloseEvent\fP (QCloseEvent *event) override"
.br
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *obj, QEvent *ev) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for the splashscreen with information of the running client\&.

.PP
\fBNote\fP
.RS 4
this is intentionally not a QSplashScreen\&. Bitcoin Core initialization can take a long time, and in that case a progress window that cannot be moved around and minimized has turned out to be frustrating to the user\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSplashScreen\fP (const \fBNetworkStyle\fP * networkStyle)\fR [explicit]\fP"

.SS "~\fBSplashScreen\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void closeEvent (QCloseEvent * event)\fR [override]\fP, \fR [protected]\fP"

.SS "bool eventFilter (QObject * obj, QEvent * ev)\fR [override]\fP, \fR [protected]\fP"

.SS "void handleLoadWallet ()\fR [slot]\fP"
Handle wallet load notifications\&. 
.SS "void paintEvent (QPaintEvent * event)\fR [override]\fP, \fR [protected]\fP"

.SS "void setNode (\fBinterfaces::Node\fP & node)"

.SS "void showMessage (const QString & message, int alignment, const QColor & color)\fR [slot]\fP"
Show message and progress 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
