.TH "src/qt/splashscreen.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/splashscreen.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <qt/splashscreen\&.h>\fP
.br
\fR#include <clientversion\&.h>\fP
.br
\fR#include <common/system\&.h>\fP
.br
\fR#include <interfaces/handler\&.h>\fP
.br
\fR#include <interfaces/node\&.h>\fP
.br
\fR#include <interfaces/wallet\&.h>\fP
.br
\fR#include <qt/guiutil\&.h>\fP
.br
\fR#include <qt/networkstyle\&.h>\fP
.br
\fR#include <qt/walletmodel\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <QApplication>\fP
.br
\fR#include <QCloseEvent>\fP
.br
\fR#include <QPainter>\fP
.br
\fR#include <QRadialGradient>\fP
.br
\fR#include <QScreen>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
