.TH "src/wallet/sqlite.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/sqlite.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <wallet/sqlite\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <crypto/common\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/fs_helpers\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <wallet/db\&.h>\fP
.br
\fR#include <sqlite3\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBSQLiteDatabase\fP > \fBMakeSQLiteDatabase\fP (const \fBfs::path\fP &path, const \fBDatabaseOptions\fP &options, \fBDatabaseStatus\fP &status, \fBbilingual_str\fP &error)"
.br
.ti -1c
.RI "std::string \fBSQLiteDatabaseVersion\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
