.TH "src/wallet/sqlite.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/sqlite.h
.SH SYNOPSIS
.br
.PP
\fR#include <sync\&.h>\fP
.br
\fR#include <wallet/db\&.h>\fP
.br
\fR#include <semaphore>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSQLiteCursor\fP"
.br
.ti -1c
.RI "class \fBSQliteExecHandler\fP"
.br
.ti -1c
.RI "class \fBSQLiteBatch\fP"
.br
.ti -1c
.RI "class \fBSQLiteDatabase\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBSQLiteDatabase\fP > \fBMakeSQLiteDatabase\fP (const \fBfs::path\fP &path, const \fBDatabaseOptions\fP &options, \fBDatabaseStatus\fP &status, \fBbilingual_str\fP &error)"
.br
.ti -1c
.RI "std::string \fBSQLiteDatabaseVersion\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
