.TH "StaticContentsSock" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaticContentsSock
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <net\&.h>\fP
.PP
Inherits \fBZeroSock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStaticContentsSock\fP (const std::string &contents)"
.br
.ti -1c
.RI "ssize_t \fBRecv\fP (void *buf, size_t len, int \fBflags\fP) const override"
.br
.ti -1c
.RI "bool \fBIsConnected\fP (std::string &) const override"
.br
.in -1c

Public Member Functions inherited from \fBZeroSock\fP
.in +1c
.ti -1c
.RI "\fBZeroSock\fP ()"
.br
.ti -1c
.RI "\fB~ZeroSock\fP () override"
.br
.ti -1c
.RI "ssize_t \fBSend\fP (const void *, size_t len, int) const override"
.br
.ti -1c
.RI "ssize_t \fBRecv\fP (void *buf, size_t len, int \fBflags\fP) const override"
.br
.ti -1c
.RI "int \fBConnect\fP (const sockaddr *, socklen_t) const override"
.br
.ti -1c
.RI "int \fBBind\fP (const sockaddr *, socklen_t) const override"
.br
.ti -1c
.RI "int \fBListen\fP (int) const override"
.br
.ti -1c
.RI "std::unique_ptr< \fBSock\fP > \fBAccept\fP (sockaddr *addr, socklen_t *addr_len) const override"
.br
.ti -1c
.RI "int \fBGetSockOpt\fP (int level, int opt_name, void *opt_val, socklen_t *opt_len) const override"
.br
.ti -1c
.RI "int \fBSetSockOpt\fP (int, int, const void *, socklen_t) const override"
.br
.ti -1c
.RI "int \fBGetSockName\fP (sockaddr *\fBname\fP, socklen_t *name_len) const override"
.br
.ti -1c
.RI "bool \fBSetNonBlocking\fP () const override"
.br
.ti -1c
.RI "bool \fBIsSelectable\fP () const override"
.br
.ti -1c
.RI "bool \fBWait\fP (std::chrono::milliseconds timeout, \fBEvent\fP requested, \fBEvent\fP *occurred=nullptr) const override"
.br
.ti -1c
.RI "bool \fBWaitMany\fP (std::chrono::milliseconds timeout, \fBEventsPerSock\fP &events_per_sock) const override"
.br
.in -1c

Public Member Functions inherited from \fBSock\fP
.in +1c
.ti -1c
.RI "\fBSock\fP ()=delete"
.br
.ti -1c
.RI "\fBSock\fP (\fBSOCKET\fP s)"
.br
.ti -1c
.RI "\fBSock\fP (const \fBSock\fP &)=delete"
.br
.ti -1c
.RI "\fBSock\fP (\fBSock\fP &&other)"
.br
.ti -1c
.RI "virtual \fB~Sock\fP ()"
.br
.ti -1c
.RI "\fBSock\fP & \fBoperator=\fP (const \fBSock\fP &)=delete"
.br
.ti -1c
.RI "virtual void \fBSendComplete\fP (std::span< const unsigned char > data, std::chrono::milliseconds timeout, \fBCThreadInterrupt\fP &interrupt) const"
.br
.ti -1c
.RI "virtual void \fBSendComplete\fP (std::span< const char > data, std::chrono::milliseconds timeout, \fBCThreadInterrupt\fP &interrupt) const"
.br
.ti -1c
.RI "virtual std::string \fBRecvUntilTerminator\fP (uint8_t terminator, std::chrono::milliseconds timeout, \fBCThreadInterrupt\fP &interrupt, size_t max_data) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBSOCKET\fP s) const"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBSock\fP
.in +1c
.ti -1c
.RI "using \fBEvent\fP = uint8_t"
.br
.ti -1c
.RI "using \fBEventsPerSock\fP = std::unordered_map<std::shared_ptr<const \fBSock\fP>, \fBEvents\fP, \fBHashSharedPtrSock\fP, \fBEqualSharedPtrSock\fP>"
.br
.in -1c

Static Public Attributes inherited from \fBSock\fP
.in +1c
.ti -1c
.RI "static constexpr \fBEvent\fP \fBRECV\fP = 0b001"
.br
.ti -1c
.RI "static constexpr \fBEvent\fP \fBSEND\fP = 0b010"
.br
.ti -1c
.RI "static constexpr \fBEvent\fP \fBERR\fP = 0b100"
.br
.in -1c

Protected Attributes inherited from \fBSock\fP
.in +1c
.ti -1c
.RI "\fBSOCKET\fP \fBm_socket\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A mocked \fBSock\fP alternative that returns a statically contained data upon read and succeeds and ignores all writes\&. The data to be returned is given to the constructor and when it is exhausted an EOF is returned by further reads\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBStaticContentsSock\fP (const std::string & contents)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool IsConnected (std::string & errmsg) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Check if still connected\&. 
.PP
\fBParameters\fP
.RS 4
\fIerrmsg\fP The error string, if the socket has been disconnected\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if connected 
.RE
.PP

.PP
Reimplemented from \fBSock\fP\&.
.SS "ssize_t Recv (void * buf, size_t len, int flags) const\fR [override]\fP, \fR [virtual]\fP"
Return parts of the contents that was provided at construction until it is exhausted and then return 0 (EOF)\&. 
.PP
Reimplemented from \fBSock\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
