.TH "Status" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Status
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <status\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatus\fP () noexcept"
.br
.ti -1c
.RI "\fBStatus\fP (const \fBStatus\fP &rhs)"
.br
.ti -1c
.RI "\fBStatus\fP (\fBStatus\fP &&rhs) noexcept"
.br
.ti -1c
.RI "\fB~Status\fP ()"
.br
.ti -1c
.RI "\fBStatus\fP & \fBoperator=\fP (const \fBStatus\fP &rhs)"
.br
.ti -1c
.RI "\fBStatus\fP & \fBoperator=\fP (\fBStatus\fP &&rhs) noexcept"
.br
.ti -1c
.RI "bool \fBok\fP () const"
.br
.ti -1c
.RI "bool \fBIsNotFound\fP () const"
.br
.ti -1c
.RI "bool \fBIsCorruption\fP () const"
.br
.ti -1c
.RI "bool \fBIsIOError\fP () const"
.br
.ti -1c
.RI "bool \fBIsNotSupportedError\fP () const"
.br
.ti -1c
.RI "bool \fBIsInvalidArgument\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBStatus\fP \fBOK\fP ()"
.br
.ti -1c
.RI "static \fBStatus\fP \fBNotFound\fP (const \fBSlice\fP &msg, const \fBSlice\fP &msg2=\fBSlice\fP())"
.br
.ti -1c
.RI "static \fBStatus\fP \fBCorruption\fP (const \fBSlice\fP &msg, const \fBSlice\fP &msg2=\fBSlice\fP())"
.br
.ti -1c
.RI "static \fBStatus\fP \fBNotSupported\fP (const \fBSlice\fP &msg, const \fBSlice\fP &msg2=\fBSlice\fP())"
.br
.ti -1c
.RI "static \fBStatus\fP \fBInvalidArgument\fP (const \fBSlice\fP &msg, const \fBSlice\fP &msg2=\fBSlice\fP())"
.br
.ti -1c
.RI "static \fBStatus\fP \fBIOError\fP (const \fBSlice\fP &msg, const \fBSlice\fP &msg2=\fBSlice\fP())"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBStatus\fP ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "\fBStatus\fP (const \fBStatus\fP & rhs)\fR [inline]\fP"

.SS "\fBStatus\fP (\fBStatus\fP && rhs)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "~\fBStatus\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBStatus\fP Corruption (const \fBSlice\fP & msg, const \fBSlice\fP & msg2 = \fR\fBSlice\fP()\fP)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBStatus\fP InvalidArgument (const \fBSlice\fP & msg, const \fBSlice\fP & msg2 = \fR\fBSlice\fP()\fP)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBStatus\fP IOError (const \fBSlice\fP & msg, const \fBSlice\fP & msg2 = \fR\fBSlice\fP()\fP)\fR [inline]\fP, \fR [static]\fP"

.SS "bool IsCorruption () const\fR [inline]\fP"

.SS "bool IsInvalidArgument () const\fR [inline]\fP"

.SS "bool IsIOError () const\fR [inline]\fP"

.SS "bool IsNotFound () const\fR [inline]\fP"

.SS "bool IsNotSupportedError () const\fR [inline]\fP"

.SS "\fBStatus\fP NotFound (const \fBSlice\fP & msg, const \fBSlice\fP & msg2 = \fR\fBSlice\fP()\fP)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBStatus\fP NotSupported (const \fBSlice\fP & msg, const \fBSlice\fP & msg2 = \fR\fBSlice\fP()\fP)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBStatus\fP OK ()\fR [inline]\fP, \fR [static]\fP"

.SS "bool ok () const\fR [inline]\fP"

.SS "\fBStatus\fP & operator= (const \fBStatus\fP & rhs)\fR [inline]\fP"

.SS "\fBStatus\fP & operator= (\fBStatus\fP && rhs)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "std::string ToString () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
