.TH "src/leveldb/util/status_test.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/util/status_test.cc
.SH SYNOPSIS
.br
.PP
\fR#include <utility>\fP
.br
\fR#include 'leveldb/slice\&.h'\fP
.br
\fR#include 'leveldb/status\&.h'\fP
.br
\fR#include 'util/testharness\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBStatus\fP, MoveConstructor)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
