.TH "StdChronoDuration" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StdChronoDuration
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <random\&.h>\fP
.SH "Concept definition"
.PP 

.nf
template<typename T>
concept StdChronoDuration =  requires {
    []<class Rep, class Period>(std::type_identity<std::chrono::duration<Rep, Period>>){}(
        std::type_identity<T>());
}
.PP
.fi
.SH "Detailed Description"
.PP 
A concept for C++ std::chrono durations\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
