.TH "src/compat/stdin.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/compat/stdin.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <compat/stdin\&.h>\fP
.br
\fR#include <cstdio>\fP
.br
\fR#include <termios\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <poll\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSetStdinEcho\fP (bool enable)"
.br
.ti -1c
.RI "bool \fBStdinTerminal\fP ()"
.br
.ti -1c
.RI "bool \fBStdinReady\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void SetStdinEcho (bool enable)"

.SS "bool StdinReady ()"

.SS "bool StdinTerminal ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
