.TH "StdLockGuard" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StdLockGuard
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <threadsafety\&.h>\fP
.PP
Inherits lock_guard< StdMutex >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStdLockGuard\fP (\fBStdMutex\fP &\fBcs\fP) \fBEXCLUSIVE_LOCK_FUNCTION\fP(\fBcs\fP)"
.br
.ti -1c
.RI "\fB~StdLockGuard\fP () \fBUNLOCK_FUNCTION\fP()=default"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBStdLockGuard\fP (\fBStdMutex\fP & cs)\fR [inline]\fP, \fR [explicit]\fP"

.SS "~\fBStdLockGuard\fP ()\fR [default]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
