.TH "src/test/util/str.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/util/str.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/util/str\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBCaseInsensitiveEqual\fP (const std::string &s1, const std::string &s2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool CaseInsensitiveEqual (const std::string & s1, const std::string & s2)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
