.TH "src/bench/streams_findbyte.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bench/streams_findbyte.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bench/bench\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdio>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBENCHMARK\fP (FindByte, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BENCHMARK (FindByte , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
