.TH "src/util/string.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/string.h
.SH SYNOPSIS
.br
.PP
\fR#include <span\&.h>\fP
.br
\fR#include <array>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <locale>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBConstevalFormatString< num_params >\fP"
.br
.RI "A wrapper for a compile-time partially validated format string\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButil\fP"
.br
.ti -1c
.RI "namespace \fButil::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBReplaceAll\fP (std::string &in_out, const std::string &search, const std::string &substitute)"
.br
.ti -1c
.RI "template<typename \fBT\fP = std::span<const char>> std::vector< \fBT\fP > \fBSplit\fP (const std::span< const char > &sp, std::string_view separators, bool include_sep=false)"
.br
.ti -1c
.RI "template<typename \fBT\fP = std::span<const char>> std::vector< \fBT\fP > \fBSplit\fP (const std::span< const char > &sp, char sep, bool include_sep=false)"
.br
.ti -1c
.RI "std::vector< std::string > \fBSplitString\fP (std::string_view str, char sep)"
.br
.ti -1c
.RI "std::vector< std::string > \fBSplitString\fP (std::string_view str, std::string_view separators)"
.br
.ti -1c
.RI "std::string_view \fBTrimStringView\fP (std::string_view str, std::string_view pattern=' \\f\\n\\r\\t\\v')"
.br
.ti -1c
.RI "std::string \fBTrimString\fP (std::string_view str, std::string_view pattern=' \\f\\n\\r\\t\\v')"
.br
.ti -1c
.RI "std::string_view \fBRemoveSuffixView\fP (std::string_view str, std::string_view suffix)"
.br
.ti -1c
.RI "std::string_view \fBRemovePrefixView\fP (std::string_view str, std::string_view \fBprefix\fP)"
.br
.ti -1c
.RI "std::string \fBRemovePrefix\fP (std::string_view str, std::string_view \fBprefix\fP)"
.br
.ti -1c
.RI "template<typename C, typename \fBS\fP, typename UnaryOp> auto \fBJoin\fP (const C &container, const \fBS\fP &separator, UnaryOp unary_op)"
.br
.ti -1c
.RI "template<typename C, typename \fBS\fP> auto \fBJoin\fP (const C &container, const \fBS\fP &separator)"
.br
.ti -1c
.RI "std::string \fBMakeUnorderedList\fP (const std::vector< std::string > &items)"
.br
.ti -1c
.RI "bool \fBContainsNoNUL\fP (std::string_view str) noexcept"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::string \fBToString\fP (const \fBT\fP &t)"
.br
.ti -1c
.RI "template<typename T1, size_t PREFIX_LEN> bool \fBHasPrefix\fP (const T1 &obj, const std::array< uint8_t, PREFIX_LEN > &\fBprefix\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
