.TH "submitblock_StateCatcher" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
submitblock_StateCatcher
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCValidationInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsubmitblock_StateCatcher\fP (const \fBuint256\fP &hashIn)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBhash\fP"
.br
.ti -1c
.RI "bool \fBfound\fP {false}"
.br
.ti -1c
.RI "\fBBlockValidationState\fP \fBstate\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBBlockChecked\fP (const std::shared_ptr< const \fBCBlock\fP > &block, const \fBBlockValidationState\fP &stateIn) override"
.br
.in -1c

Protected Member Functions inherited from \fBCValidationInterface\fP
.in +1c
.ti -1c
.RI "\fB~CValidationInterface\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBUpdatedBlockTip\fP (const \fBCBlockIndex\fP *pindexNew, const \fBCBlockIndex\fP *pindexFork, bool fInitialDownload)"
.br
.ti -1c
.RI "virtual void \fBActiveTipChange\fP (const \fBCBlockIndex\fP &new_tip, bool is_ibd)"
.br
.ti -1c
.RI "virtual void \fBTransactionAddedToMempool\fP (const \fBNewMempoolTransactionInfo\fP &tx, uint64_t mempool_sequence)"
.br
.ti -1c
.RI "virtual void \fBTransactionRemovedFromMempool\fP (const \fBCTransactionRef\fP &tx, \fBMemPoolRemovalReason\fP reason, uint64_t mempool_sequence)"
.br
.ti -1c
.RI "virtual void \fBMempoolTransactionsRemovedForBlock\fP (const std::vector< \fBRemovedMempoolTransactionInfo\fP > &txs_removed_for_block, unsigned int nBlockHeight)"
.br
.ti -1c
.RI "virtual void \fBBlockConnected\fP (const \fBkernel::ChainstateRole\fP &role, const std::shared_ptr< const \fBCBlock\fP > &block, const \fBCBlockIndex\fP *pindex)"
.br
.ti -1c
.RI "virtual void \fBBlockDisconnected\fP (const std::shared_ptr< const \fBCBlock\fP > &block, const \fBCBlockIndex\fP *pindex)"
.br
.ti -1c
.RI "virtual void \fBChainStateFlushed\fP (const \fBkernel::ChainstateRole\fP &role, const \fBCBlockLocator\fP &locator)"
.br
.ti -1c
.RI "virtual void \fBNewPoWValidBlock\fP (const \fBCBlockIndex\fP *pindex, const std::shared_ptr< const \fBCBlock\fP > &block)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBsubmitblock_StateCatcher\fP (const \fBuint256\fP & hashIn)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void BlockChecked (const std::shared_ptr< const \fBCBlock\fP > & , const \fBBlockValidationState\fP & )\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"
Notifies listeners of a block validation result\&. If the provided \fBBlockValidationState\fP IsValid, the provided block is guaranteed to be the current best block at the time the callback was generated (not necessarily now)\&. 
.PP
Reimplemented from \fBCValidationInterface\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool found {false}"

.SS "\fBuint256\fP hash"

.SS "\fBBlockValidationState\fP state"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
