.TH "Communication" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Communication
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <subprocess\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommunication\fP (\fBStreams\fP *stream)"
.br
.ti -1c
.RI "\fBCommunication\fP (const Communication &)=delete"
.br
.ti -1c
.RI "\fBCommunication\fP & \fBoperator=\fP (const \fBCommunication\fP &)=delete"
.br
.ti -1c
.RI "\fBCommunication\fP (Communication &&)=default"
.br
.ti -1c
.RI "\fBCommunication\fP & \fBoperator=\fP (\fBCommunication\fP &&)=default"
.br
.ti -1c
.RI "int \fBsend\fP (const char *msg, size_t length)"
.br
.ti -1c
.RI "int \fBsend\fP (const std::vector< char > &msg)"
.br
.ti -1c
.RI "std::pair< \fBOutBuffer\fP, \fBErrBuffer\fP > \fBcommunicate\fP (const char *msg, size_t length)"
.br
.ti -1c
.RI "std::pair< \fBOutBuffer\fP, \fBErrBuffer\fP > \fBcommunicate\fP (const std::vector< char > &msg)"
.br
.ti -1c
.RI "void \fBset_out_buf_cap\fP (size_t cap)"
.br
.ti -1c
.RI "void \fBset_err_buf_cap\fP (size_t cap)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A helper class to \fBStreams\fP\&. This takes care of management of communicating with the child process with the means of the correct file descriptor\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Communication (\fBStreams\fP * stream)\fR [inline]\fP"

.SS "Communication (const Communication & )\fR [delete]\fP"

.SS "Communication (Communication && )\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::pair< \fBOutBuffer\fP, \fBErrBuffer\fP > communicate (const char * msg, size_t length)\fR [inline]\fP"

.SS "std::pair< \fBOutBuffer\fP, \fBErrBuffer\fP > communicate (const std::vector< char > & msg)\fR [inline]\fP"

.SS "\fBCommunication\fP & operator= (\fBCommunication\fP && )\fR [default]\fP"

.SS "\fBCommunication\fP & operator= (const \fBCommunication\fP & )\fR [delete]\fP"

.SS "int send (const char * msg, size_t length)\fR [inline]\fP"

.SS "int send (const std::vector< char > & msg)\fR [inline]\fP"

.SS "void set_err_buf_cap (size_t cap)\fR [inline]\fP"

.SS "void set_out_buf_cap (size_t cap)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
