.TH "subprocess" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
subprocess
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButil\fP"
.br
.ti -1c
.RI "namespace \fBdetail\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCalledProcessError\fP"
.br
.ti -1c
.RI "class \fBOSError\fP"
.br
.ti -1c
.RI "struct \fBstring_arg\fP"
.br
.ti -1c
.RI "struct \fBexecutable\fP"
.br
.ti -1c
.RI "struct \fBinput\fP"
.br
.ti -1c
.RI "struct \fBoutput\fP"
.br
.ti -1c
.RI "struct \fBerror\fP"
.br
.ti -1c
.RI "class \fBBuffer\fP"
.br
.ti -1c
.RI "class \fBPopen\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBOutBuffer\fP = \fBBuffer\fP"
.br
.ti -1c
.RI "using \fBErrBuffer\fP = \fBBuffer\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBIOTYPE\fP { \fBSTDOUT\fP = 1, \fBSTDERR\fP, \fBPIPE\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Getting started with reading this source code\&. The source is mainly divided into four parts:
.IP "1." 4
Exception Classes: These are very basic exception classes derived from runtime_error exception\&. There are two types of exception thrown from subprocess library: \fBOSError\fP and \fBCalledProcessError\fP
.IP "2." 4
\fBPopen\fP Class This is the main class the users will deal with\&. It provides with all the API's to deal with processes\&.
.IP "3." 4
Util namespace It includes some helper functions to split/join a string, reading from file descriptors, waiting on a process, fcntl options on file descriptors etc\&.
.IP "4." 4
Detail namespace This includes some metaprogramming and helper classes\&. 
.PP

.SH "Typedef Documentation"
.PP 
.SS "using \fBErrBuffer\fP = \fBBuffer\fP"

.SS "using \fBOutBuffer\fP = \fBBuffer\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBIOTYPE\fP"
Used for redirecting input/output/error 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BISTDOUT \fP
.TP
\f(BISTDERR \fP
.TP
\f(BIPIPE \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
