.TH "Child" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Child
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <subprocess\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChild\fP (\fBPopen\fP *p, int err_wr_pipe)"
.br
.ti -1c
.RI "void \fBexecute_child\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A helper class to \fBPopen\fP\&. This takes care of all the fork-exec logic in the execute_child API\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Child (\fBPopen\fP * p, int err_wr_pipe)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void execute_child ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
