.TH "Buffer" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Buffer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <subprocess\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuffer\fP ()=default"
.br
.ti -1c
.RI "\fBBuffer\fP (size_t cap)"
.br
.ti -1c
.RI "void \fBadd_cap\fP (size_t cap)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< char > \fBbuf\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
class: \fBBuffer\fP This class is a very thin wrapper around std::vector<char> This is basically used to determine the length of the actual data stored inside the dynamically resized vector\&.

.PP
This is what is returned as the output to the communicate function, so, users must know about this class\&.

.PP
\fBOutBuffer\fP and \fBErrBuffer\fP are just different typedefs to this class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Buffer ()\fR [default]\fP"

.SS "Buffer (size_t cap)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void add_cap (size_t cap)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::vector<char> buf"

.SS "size_t length = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
