.TH "subprocess::detail" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
subprocess::detail
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBArgumentDeducer\fP"
.br
.ti -1c
.RI "class \fBChild\fP"
.br
.ti -1c
.RI "class \fBCommunication\fP"
.br
.ti -1c
.RI "class \fBStreams\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
