.TH "symbol" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
symbol \- -check  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
-check 


.PP
.nf
Check that a libsecp256k1 shared library exports only expected symbols\&.

Usage examples:
  - When building with Autotools:
    \&./tools/symbol-check\&.py \&.libs/libsecp256k1\&.so
    \&./tools/symbol-check\&.py \&.libs/libsecp256k1-<V>\&.dll
    \&./tools/symbol-check\&.py \&.libs/libsecp256k1\&.dylib

  - When building with CMake:
    \&./tools/symbol-check\&.py build/lib/libsecp256k1\&.so
    \&./tools/symbol-check\&.py build/bin/libsecp256k1-<V>\&.dll
    \&./tools/symbol-check\&.py build/lib/libsecp256k1\&.dylib
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
