.TH "src/secp256k1/tools/symbol-check.py" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/tools/symbol-check.py
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBUnexpectedExport\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsymbol\-check\fP"
.br
.ti -1c
.RI "namespace \fBsymbol\fP"
.br
.RI "-check "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "list[str] \fBget_exported_exports\fP (library)"
.br
.ti -1c
.RI "list[str] \fBgrep_expected_symbols\fP ()"
.br
.ti -1c
.RI "None \fBcheck_symbols\fP (library, expected_exports)"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
