.TH "src/test/sync_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/sync_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <sync\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <mutex>\fP
.br
\fR#include <stdexcept>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (potential_deadlock_detected)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (inconsistent_lock_order_detected)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (inconsistent_lock_order_detected )"

.SS "BOOST_AUTO_TEST_CASE (potential_deadlock_detected )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
