.TH "src/util/syserror.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/syserror.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <util/syserror\&.h>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBSysErrorString\fP (int err)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string SysErrorString (int err)"
Return system error string from errno value\&. Use this instead of std::strerror, which is not thread-safe\&. For network errors use NetworkErrorString from \fBsock\&.h\fP instead\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
