.TH "src/test/system_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/system_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <common/run_command\&.h>\fP
.br
\fR#include <univalue\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
