.TH "src/common/system.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/common/system.h
.SH SYNOPSIS
.br
.PP
\fR#include <bitcoin\-build\-config\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int64_t \fBGetStartupTime\fP ()"
.br
.ti -1c
.RI "void \fBSetupEnvironment\fP ()"
.br
.ti -1c
.RI "bool \fBSetupNetworking\fP ()"
.br
.ti -1c
.RI "std::string \fBShellEscape\fP (const std::string &arg)"
.br
.ti -1c
.RI "int \fBGetNumCores\fP ()"
.br
.ti -1c
.RI "std::optional< size_t > \fBGetTotalRAM\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int GetNumCores ()"
Return the number of cores available on the current system\&. 
.PP
\fBNote\fP
.RS 4
This does count virtual cores, such as those provided by HyperThreading\&. 
.RE
.PP

.SS "int64_t GetStartupTime ()"

.SS "std::optional< size_t > GetTotalRAM ()"
Return the total RAM available on the current system, if detectable\&. 
.SS "void SetupEnvironment ()"

.SS "bool SetupNetworking ()\fR [nodiscard]\fP"

.SS "std::string ShellEscape (const std::string & arg)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
