.TH "src/leveldb/table/table_test.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/table/table_test.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'leveldb/table\&.h'\fP
.br
\fR#include <map>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'db/dbformat\&.h'\fP
.br
\fR#include 'db/memtable\&.h'\fP
.br
\fR#include 'db/write_batch_internal\&.h'\fP
.br
\fR#include 'leveldb/db\&.h'\fP
.br
\fR#include 'leveldb/env\&.h'\fP
.br
\fR#include 'leveldb/iterator\&.h'\fP
.br
\fR#include 'leveldb/table_builder\&.h'\fP
.br
\fR#include 'table/block\&.h'\fP
.br
\fR#include 'table/block_builder\&.h'\fP
.br
\fR#include 'table/format\&.h'\fP
.br
\fR#include 'util/random\&.h'\fP
.br
\fR#include 'util/testharness\&.h'\fP
.br
\fR#include 'util/testutil\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBStringSink\fP"
.br
.ti -1c
.RI "class \fBStringSource\fP"
.br
.ti -1c
.RI "class \fBConstructor\fP"
.br
.ti -1c
.RI "class \fBBlockConstructor\fP"
.br
.ti -1c
.RI "class \fBTableConstructor\fP"
.br
.ti -1c
.RI "class \fBKeyConvertingIterator\fP"
.br
.ti -1c
.RI "class \fBMemTableConstructor\fP"
.br
.ti -1c
.RI "class \fBDBConstructor\fP"
.br
.ti -1c
.RI "struct \fBTestArgs\fP"
.br
.ti -1c
.RI "class \fBHarness\fP"
.br
.ti -1c
.RI "class \fBMemTableTest\fP"
.br
.ti -1c
.RI "class \fBTableTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< std::string, std::string, STLLessThan > \fBKVMap\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTestType\fP { \fBTABLE_TEST\fP, \fBBLOCK_TEST\fP, \fBMEMTABLE_TEST\fP, \fBDB_TEST\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBHarness\fP, Empty)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBHarness\fP, ZeroRestartPointsInBlock)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBHarness\fP, SimpleEmptyKey)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBHarness\fP, SimpleSingle)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBHarness\fP, SimpleMulti)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBHarness\fP, SimpleSpecialKey)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBHarness\fP, Randomized)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBHarness\fP, RandomizedLongDB)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMemTableTest\fP, Simple)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTableTest\fP, ApproximateOffsetOfPlain)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTableTest\fP, ApproximateOffsetOfCompressed)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
