.TH "TaprootSpendData" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TaprootSpendData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <signingprovider\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMerge\fP (\fBTaprootSpendData\fP other)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXOnlyPubKey\fP \fBinternal_key\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBmerkle_root\fP"
.br
.ti -1c
.RI "std::map< std::pair< std::vector< unsigned char >, int >, std::set< std::vector< unsigned char >, \fBShortestVectorFirstComparator\fP > > \fBscripts\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Merge (\fBTaprootSpendData\fP other)"
Merge other \fBTaprootSpendData\fP (for the same scriptPubKey) into this\&. 
.SH "Field Documentation"
.PP 
.SS "\fBXOnlyPubKey\fP internal_key"
The BIP341 internal key\&. 
.SS "\fBuint256\fP merkle_root"
The Merkle root of the script tree (0 if no scripts)\&. 
.SS "std::map<std::pair<std::vector<unsigned char>, int>, std::set<std::vector<unsigned char>, \fBShortestVectorFirstComparator\fP> > scripts"
Map from (script, leaf_version) to (sets of) control blocks\&. More than one control block for a given script is only possible if it appears in multiple branches of the tree\&. We keep them all so that inference can reconstruct the full tree\&. Within each set, the control blocks are sorted by size, so that the signing logic can easily prefer the cheapest one\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
