.TH "src/test/testnet4_miner_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/testnet4_miner_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <common/system\&.h>\fP
.br
\fR#include <interfaces/mining\&.h>\fP
.br
\fR#include <node/miner\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTestnet4MinerTestingSetup\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtestnet4_miner_tests\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (MiningInterface)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (MiningInterface )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
