.TH "TestConditionChecker" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestConditionChecker
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVersionBitsConditionChecker\fP, and \fBVersionBitsConditionChecker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexplicit\fP (false) \fBTestConditionChecker\fP(const \fBConsensus\fP"
.br
.ti -1c
.RI "\fB~TestConditionChecker\fP () override=default"
.br
.ti -1c
.RI "\fBThresholdState\fP \fBStateFor\fP (const \fBCBlockIndex\fP *pindexPrev) const"
.br
.ti -1c
.RI "int \fBStateSinceHeightFor\fP (const \fBCBlockIndex\fP *pindexPrev) const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBVersionBitsConditionChecker\fP
.in +1c
.ti -1c
.RI "\fBVersionBitsConditionChecker\fP (const \fBConsensus::BIP9Deployment\fP &dep)"
.br
.ti -1c
.RI "\fBVersionBitsConditionChecker\fP (const \fBConsensus::Params\fP &params, \fBConsensus::DeploymentPos\fP id)"
.br
.ti -1c
.RI "uint32_t \fBMask\fP () const"
.br
.ti -1c
.RI "bool \fBCondition\fP (int32_t nVersion) const"
.br
.in -1c

Public Member Functions inherited from \fBAbstractThresholdConditionChecker\fP
.in +1c
.ti -1c
.RI "virtual \fB~AbstractThresholdConditionChecker\fP ()=default"
.br
.ti -1c
.RI "\fBBIP9Stats\fP \fBGetStateStatisticsFor\fP (const \fBCBlockIndex\fP *pindex, std::vector< bool > *signalling_blocks=nullptr) const"
.br
.ti -1c
.RI "\fBThresholdState\fP \fBGetStateFor\fP (const \fBCBlockIndex\fP *pindexPrev, \fBThresholdConditionCache\fP &cache) const"
.br
.ti -1c
.RI "int \fBGetStateSinceHeightFor\fP (const \fBCBlockIndex\fP *pindexPrev, \fBThresholdConditionCache\fP &cache) const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBVersionBitsConditionChecker\fP
.in +1c
.ti -1c
.RI "int64_t \fBBeginTime\fP () const override"
.br
.ti -1c
.RI "int64_t \fBEndTime\fP () const override"
.br
.ti -1c
.RI "int \fBMinActivationHeight\fP () const override"
.br
.ti -1c
.RI "int \fBPeriod\fP () const override"
.br
.ti -1c
.RI "int \fBThreshold\fP () const override"
.br
.ti -1c
.RI "bool \fBCondition\fP (const \fBCBlockIndex\fP *pindex) const override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "~\fBTestConditionChecker\fP ()\fR [override]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void clear ()\fR [inline]\fP"

.SS "explicit (false ) const\fR [inline]\fP"

.SS "\fBThresholdState\fP StateFor (const \fBCBlockIndex\fP * pindexPrev) const\fR [inline]\fP"

.SS "int StateSinceHeightFor (const \fBCBlockIndex\fP * pindexPrev) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
