.TH "src/secp256k1/tools/test_vectors_musig2_generate.py" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/tools/test_vectors_musig2_generate.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtest_vectors_musig2_generate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBhexstr_to_intarray\fP (str)"
.br
.ti -1c
.RI "\fBcreate_init\fP (\fBname\fP)"
.br
.ti -1c
.RI "\fBinit_array\fP (key)"
.br
.ti -1c
.RI "\fBinit_arrays\fP (key)"
.br
.ti -1c
.RI "\fBinit_indices\fP (array)"
.br
.ti -1c
.RI "\fBinit_is_xonly\fP (case)"
.br
.ti -1c
.RI "\fBinit_optional_expected\fP (case)"
.br
.ti -1c
.RI "\fBinit_cases\fP (cases, f)"
.br
.ti -1c
.RI "\fBfinish_init\fP ()"
.br
.ti -1c
.RI "\fBcomment_to_error\fP (case)"
.br
.ti -1c
.RI "\fBinit_array_maybe\fP (array)"
.br
.ti -1c
.RI "\fBfilter_msg32\fP (k)"
.br
.ti -1c
.RI "\fBsign_error\fP (case)"
.br
.ti -1c
.RI "\fBverify_error\fP (case)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBmax_pubkeys\fP = 0"
.br
.ti -1c
.RI "tuple \fBs\fP"
.br
.ti -1c
.RI "\fBdata\fP = json\&.load(f)"
.br
.ti -1c
.RI "\fBmax_key_indices\fP"
.br
.ti -1c
.RI "\fBmax_tweak_indices\fP"
.br
.ti -1c
.RI "\fBnum_pubkeys\fP = len(\fBdata\fP['pubkeys'])"
.br
.ti -1c
.RI "\fBnum_tweaks\fP = len(\fBdata\fP['tweaks'])"
.br
.ti -1c
.RI "\fBnum_valid_cases\fP = len(\fBdata\fP['valid_test_cases'])"
.br
.ti -1c
.RI "\fBnum_error_cases\fP = len(\fBdata\fP['error_test_cases'])"
.br
.ti -1c
.RI "\fBnum_tests\fP = len(\fBdata\fP['test_cases'])"
.br
.ti -1c
.RI "\fBnum_pnonces\fP = len(\fBdata\fP['pnonces'])"
.br
.ti -1c
.RI "int \fBpnonce_indices_len\fP = 2"
.br
.ti -1c
.RI "\fBnum_secnonces\fP = len(\fBdata\fP['secnonces'])"
.br
.ti -1c
.RI "\fBnum_pubnonces\fP = len(\fBdata\fP['pnonces'])"
.br
.ti -1c
.RI "\fBnum_aggnonces\fP = len(\fBdata\fP['aggnonces'])"
.br
.ti -1c
.RI "\fBnum_msgs\fP = len(\fBdata\fP['msgs'])"
.br
.ti -1c
.RI "\fBnum_sign_error_cases\fP = len(\fBdata\fP['sign_error_test_cases'])"
.br
.ti -1c
.RI "\fBnum_verify_fail_cases\fP = len(\fBdata\fP['verify_fail_test_cases'])"
.br
.ti -1c
.RI "\fBnum_verify_error_cases\fP = len(\fBdata\fP['verify_error_test_cases'])"
.br
.ti -1c
.RI "tuple \fBall_cases\fP"
.br
.ti -1c
.RI "\fBmax_nonce_indices\fP"
.br
.ti -1c
.RI "\fBnum_psigs\fP = len(\fBdata\fP['psigs'])"
.br
.ti -1c
.RI "\fBmax_psig_indices\fP = max(len(test_case['psig_indices']) \fBfor\fP test_case in \fBall_cases\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
