.TH "TestOpts" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestOpts
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <setup_common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< const char * > \fBextra_args\fP {}"
.br
.ti -1c
.RI "bool \fBcoins_db_in_memory\fP {true}"
.br
.ti -1c
.RI "bool \fBblock_tree_db_in_memory\fP {true}"
.br
.ti -1c
.RI "bool \fBsetup_net\fP {true}"
.br
.ti -1c
.RI "bool \fBsetup_validation_interface\fP {true}"
.br
.ti -1c
.RI "bool \fBmin_validation_cache\fP {false}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool block_tree_db_in_memory {true}"

.SS "bool coins_db_in_memory {true}"

.SS "std::vector<const char*> extra_args {}"

.SS "bool min_validation_cache {false}"

.SS "bool setup_net {true}"

.SS "bool setup_validation_interface {true}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
