.TH "src/secp256k1/src/tests.c" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/tests.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <time\&.h>\fP
.br
\fR#include 'secp256k1\&.c'\fP
.br
\fR#include '\&.\&./include/secp256k1\&.h'\fP
.br
\fR#include '\&.\&./include/secp256k1_preallocated\&.h'\fP
.br
\fR#include 'testrand_impl\&.h'\fP
.br
\fR#include 'checkmem\&.h'\fP
.br
\fR#include 'testutil\&.h'\fP
.br
\fR#include 'util\&.h'\fP
.br
\fR#include 'unit_test\&.h'\fP
.br
\fR#include 'unit_test\&.c'\fP
.br
\fR#include '\&.\&./contrib/lax_der_parsing\&.c'\fP
.br
\fR#include '\&.\&./contrib/lax_der_privatekey_parsing\&.c'\fP
.br
\fR#include 'modinv32_impl\&.h'\fP
.br
\fR#include 'modinv64_impl\&.h'\fP
.br
\fR#include 'int128_impl\&.h'\fP
.br
\fR#include 'wycheproof/ecdsa_secp256k1_sha256_bitcoin_test\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtest_hsort_cmp_data\fP"
.br
.ti -1c
.RI "struct \fBecmult_multi_data\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONDITIONAL_TEST\fP(cnt,  nam)"
.br
.ti -1c
.RI "#define \fBCHECK_COUNTING_CALLBACK_VOID\fP(ctx,  expr_or_stmt,  callback,  callback_setter)"
.br
.ti -1c
.RI "#define \fBCHECK_ERROR_VOID\fP(ctx,  expr_or_stmt)"
.br
.ti -1c
.RI "#define \fBCHECK_ILLEGAL_VOID\fP(ctx,  expr_or_stmt)"
.br
.ti -1c
.RI "#define \fBCHECK_ILLEGAL\fP(ctx,  expr)"
.br
.ti -1c
.RI "#define \fBCHECK_ERROR\fP(ctx,  expr)"
.br
.ti -1c
.RI "#define \fBNUM\fP   65"
.br
.ti -1c
.RI "#define \fBMAX_ELEMENT_LEN\fP   65"
.br
.ti -1c
.RI "#define \fBSECP256K1_EC_PARSE_TEST_NVALID\fP   (12)"
.br
.ti -1c
.RI "#define \fBSECP256K1_EC_PARSE_TEST_NXVALID\fP   (4)"
.br
.ti -1c
.RI "#define \fBSECP256K1_EC_PARSE_TEST_NINVALID\fP   (7)"
.br
.ti -1c
.RI "#define \fBSECP256K1_ECDSA_WYCHEPROOF_NUMBER_TESTVECTORS\fP   (463)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHECK_COUNTING_CALLBACK_VOID( ctx,  expr_or_stmt,  callback,  callback_setter)"
\fBValue:\fP
.nf
    do { \\
    int32_t _calls_to_callback = 0; \\
    secp256k1_callback _saved_callback = ctx\->callback; \\
    callback_setter(ctx, counting_callback_fn, &_calls_to_callback); \\
    { expr_or_stmt; } \\
    ctx\->callback = _saved_callback; \\
    CHECK(_calls_to_callback == 1); \\
} while(0);
.PP
.fi

.SS "#define CHECK_ERROR( ctx,  expr)"
\fBValue:\fP
.nf
CHECK_ERROR_VOID(ctx, CHECK((expr) == 0))
.PP
.fi

.SS "#define CHECK_ERROR_VOID( ctx,  expr_or_stmt)"
\fBValue:\fP
.nf
    CHECK_COUNTING_CALLBACK_VOID(ctx, expr_or_stmt, error_callback, secp256k1_context_set_error_callback)
.PP
.fi

.SS "#define CHECK_ILLEGAL( ctx,  expr)"
\fBValue:\fP
.nf
CHECK_ILLEGAL_VOID(ctx, CHECK((expr) == 0))
.PP
.fi

.SS "#define CHECK_ILLEGAL_VOID( ctx,  expr_or_stmt)"
\fBValue:\fP
.nf
    CHECK_COUNTING_CALLBACK_VOID(ctx, expr_or_stmt, illegal_callback, secp256k1_context_set_illegal_callback)
.PP
.fi

.SS "#define CONDITIONAL_TEST( cnt,  nam)"
\fBValue:\fP
.nf
if (COUNT < (cnt)) { printf("Skipping %s (iteration count too low)\\n", nam); } else
.PP
.fi

.SS "#define MAX_ELEMENT_LEN   65"

.SS "#define NUM   65"

.SS "#define SECP256K1_EC_PARSE_TEST_NINVALID   (7)"

.SS "#define SECP256K1_EC_PARSE_TEST_NVALID   (12)"

.SS "#define SECP256K1_EC_PARSE_TEST_NXVALID   (4)"

.SS "#define SECP256K1_ECDSA_WYCHEPROOF_NUMBER_TESTVECTORS   (463)"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
