.TH "tests_wycheproof_generate_ecdh" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests_wycheproof_generate_ecdh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBshould_skip_flags\fP (test_vector_flags)"
.br
.ti -1c
.RI "\fBshould_skip_tcid\fP (test_vector_tcid)"
.br
.ti -1c
.RI "\fBparse_der_pk\fP (s)"
.br
.ti -1c
.RI "\fBparse_public_key\fP (\fBpk\fP)"
.br
.ti -1c
.RI "\fBnormalize_private_key\fP (\fBsk\fP)"
.br
.ti -1c
.RI "\fBnormalize_expected_result\fP (er)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfilename_input\fP = sys\&.argv[1]"
.br
.ti -1c
.RI "\fBdoc\fP = json\&.load(f)"
.br
.ti -1c
.RI "int \fBnum_vectors\fP = 0"
.br
.ti -1c
.RI "\fBoffset_sk_running\fP"
.br
.ti -1c
.RI "\fBoffset_pk_running\fP"
.br
.ti -1c
.RI "\fBoffset_shared\fP"
.br
.ti -1c
.RI "str \fBtest_vectors_out\fP = ''"
.br
.ti -1c
.RI "str \fBprivate_keys\fP = ''"
.br
.ti -1c
.RI "str \fBshared_secrets\fP = ''"
.br
.ti -1c
.RI "str \fBpublic_keys\fP = ''"
.br
.ti -1c
.RI "dict \fBcache_sks\fP = {}"
.br
.ti -1c
.RI "dict \fBcache_public_keys\fP = {}"
.br
.ti -1c
.RI "\fBpublic_key\fP = \fBparse_public_key\fP(test_vector['public'])"
.br
.ti -1c
.RI "\fBprivate_key\fP = \fBnormalize_private_key\fP(test_vector['private'])"
.br
.ti -1c
.RI "\fBexpected_result\fP = \fBnormalize_expected_result\fP(test_vector['result'])"
.br
.ti -1c
.RI "int \fBshared_size\fP = len(test_vector['shared']) // 2"
.br
.ti -1c
.RI "int \fBsk_size\fP = len(\fBprivate_key\fP) // 2"
.br
.ti -1c
.RI "int \fBpk_size\fP = len(\fBpublic_key\fP) // 2"
.br
.ti -1c
.RI "bool \fBnew_sk\fP = False"
.br
.ti -1c
.RI "\fBsk\fP = to_c_array(\fBprivate_key\fP)"
.br
.ti -1c
.RI "\fBsk_offset\fP = \fBoffset_sk_running\fP"
.br
.ti -1c
.RI "bool \fBnew_pk\fP = False"
.br
.ti -1c
.RI "str \fBpk\fP = '0x' else ''"
.br
.ti -1c
.RI "\fBpk_offset\fP = \fBoffset_pk_running\fP"
.br
.ti -1c
.RI "\fBwycheproof_tcid\fP = test_vector['tcId']"
.br
.ti -1c
.RI "str \fBstruct_definition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Generate a C file with ECDH testvectors from the Wycheproof project\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "normalize_expected_result ( er)"

.SS "normalize_private_key ( sk)"

.SS "parse_der_pk ( s)"

.SS "parse_public_key ( pk)"

.SS "should_skip_flags ( test_vector_flags)"

.SS "should_skip_tcid ( test_vector_tcid)"

.SH "Variable Documentation"
.PP 
.SS "dict cache_public_keys = {}"

.SS "dict cache_sks = {}"

.SS "doc = json\&.load(f)"

.SS "expected_result = \fBnormalize_expected_result\fP(test_vector['result'])"

.SS "filename_input = sys\&.argv[1]"

.SS "bool new_pk = False"

.SS "bool new_sk = False"

.SS "int num_vectors = 0"

.SS "offset_pk_running"

.SS "offset_shared"

.SS "offset_sk_running"

.SS "str pk = '0x' else ''"

.SS "dict pk_offset = \fBoffset_pk_running\fP"

.SS "int pk_size = len(\fBpublic_key\fP) // 2"

.SS "private_key = \fBnormalize_private_key\fP(test_vector['private'])"

.SS "str private_keys = ''"

.SS "public_key = \fBparse_public_key\fP(test_vector['public'])"

.SS "str public_keys = ''"

.SS "str shared_secrets = ''"

.SS "int shared_size = len(test_vector['shared']) // 2"

.SS "sk = to_c_array(\fBprivate_key\fP)"

.SS "dict sk_offset = \fBoffset_sk_running\fP"

.SS "int sk_size = len(\fBprivate_key\fP) // 2"

.SS "str struct_definition"
\fBInitial value:\fP
.nf
1 =  """
2 typedef struct {
3     size_t pk_offset;
4     size_t pk_len;
5     size_t sk_offset;
6     size_t sk_len;
7     size_t shared_offset;
8     size_t shared_len;
9     int expected_result;
10     int wycheproof_tcid;
11 } wycheproof_ecdh_testvector;
12 """
.PP
.fi

.SS "str test_vectors_out = ''"

.SS "wycheproof_tcid = test_vector['tcId']"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
