.TH "src/leveldb/util/testharness.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/util/testharness.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'util/testharness\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <sys/stat\&.h>\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'leveldb/env\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.ti -1c
.RI "namespace \fBleveldb::test\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBRegisterTest\fP (const char *base, const char *\fBname\fP, void(*func)())"
.br
.ti -1c
.RI "int \fBRunAllTests\fP ()"
.br
.ti -1c
.RI "std::string \fBTmpDir\fP ()"
.br
.ti -1c
.RI "int \fBRandomSeed\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
