.TH "TestOp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestOp \- UDP test server operation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBOp\fP { \fBSEND\fP, \fBRECV\fP, \fBNOP\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestOp\fP (std::chrono::milliseconds delay_in, \fBOp\fP op_in, const std::vector< uint8_t > &data_in, int error_in)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::chrono::milliseconds \fBdelay\fP"
.br
.ti -1c
.RI "enum \fBTestOp::Op\fP \fBop\fP"
.br
.ti -1c
.RI "std::vector< uint8_t > \fBdata\fP"
.br
.ti -1c
.RI "int \fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
UDP test server operation\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBOp\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BISEND \fP
.TP
\f(BIRECV \fP
.TP
\f(BINOP \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTestOp\fP (std::chrono::milliseconds delay_in, \fBOp\fP op_in, const std::vector< uint8_t > & data_in, int error_in)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::vector<uint8_t> data"

.SS "std::chrono::milliseconds delay"

.SS "int error"
Injected error\&. Set this field to a non-zero value to return the errno code from send or receive operation\&. 
.SS "enum \fBTestOp::Op\fP op"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
