.TH "test_vectors_musig2_generate" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_vectors_musig2_generate
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBhexstr_to_intarray\fP (str)"
.br
.ti -1c
.RI "\fBcreate_init\fP (\fBname\fP)"
.br
.ti -1c
.RI "\fBinit_array\fP (key)"
.br
.ti -1c
.RI "\fBinit_arrays\fP (key)"
.br
.ti -1c
.RI "\fBinit_indices\fP (array)"
.br
.ti -1c
.RI "\fBinit_is_xonly\fP (case)"
.br
.ti -1c
.RI "\fBinit_optional_expected\fP (case)"
.br
.ti -1c
.RI "\fBinit_cases\fP (cases, f)"
.br
.ti -1c
.RI "\fBfinish_init\fP ()"
.br
.ti -1c
.RI "\fBcomment_to_error\fP (case)"
.br
.ti -1c
.RI "\fBinit_array_maybe\fP (array)"
.br
.ti -1c
.RI "\fBfilter_msg32\fP (k)"
.br
.ti -1c
.RI "\fBsign_error\fP (case)"
.br
.ti -1c
.RI "\fBverify_error\fP (case)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBmax_pubkeys\fP = 0"
.br
.ti -1c
.RI "tuple \fBs\fP"
.br
.ti -1c
.RI "\fBdata\fP = json\&.load(f)"
.br
.ti -1c
.RI "\fBmax_key_indices\fP"
.br
.ti -1c
.RI "\fBmax_tweak_indices\fP"
.br
.ti -1c
.RI "\fBnum_pubkeys\fP = len(\fBdata\fP['pubkeys'])"
.br
.ti -1c
.RI "\fBnum_tweaks\fP = len(\fBdata\fP['tweaks'])"
.br
.ti -1c
.RI "\fBnum_valid_cases\fP = len(\fBdata\fP['valid_test_cases'])"
.br
.ti -1c
.RI "\fBnum_error_cases\fP = len(\fBdata\fP['error_test_cases'])"
.br
.ti -1c
.RI "\fBnum_tests\fP = len(\fBdata\fP['test_cases'])"
.br
.ti -1c
.RI "\fBnum_pnonces\fP = len(\fBdata\fP['pnonces'])"
.br
.ti -1c
.RI "int \fBpnonce_indices_len\fP = 2"
.br
.ti -1c
.RI "\fBnum_secnonces\fP = len(\fBdata\fP['secnonces'])"
.br
.ti -1c
.RI "\fBnum_pubnonces\fP = len(\fBdata\fP['pnonces'])"
.br
.ti -1c
.RI "\fBnum_aggnonces\fP = len(\fBdata\fP['aggnonces'])"
.br
.ti -1c
.RI "\fBnum_msgs\fP = len(\fBdata\fP['msgs'])"
.br
.ti -1c
.RI "\fBnum_sign_error_cases\fP = len(\fBdata\fP['sign_error_test_cases'])"
.br
.ti -1c
.RI "\fBnum_verify_fail_cases\fP = len(\fBdata\fP['verify_fail_test_cases'])"
.br
.ti -1c
.RI "\fBnum_verify_error_cases\fP = len(\fBdata\fP['verify_error_test_cases'])"
.br
.ti -1c
.RI "tuple \fBall_cases\fP"
.br
.ti -1c
.RI "\fBmax_nonce_indices\fP"
.br
.ti -1c
.RI "\fBnum_psigs\fP = len(\fBdata\fP['psigs'])"
.br
.ti -1c
.RI "\fBmax_psig_indices\fP = max(len(test_case['psig_indices']) \fBfor\fP test_case in \fBall_cases\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "comment_to_error ( case)"

.SS "create_init ( name)"

.SS "filter_msg32 ( k)"

.SS "finish_init ()"

.SS "hexstr_to_intarray ( str)"

.SS "init_array ( key)"

.SS "init_array_maybe ( array)"

.SS "init_arrays ( key)"

.SS "init_cases ( cases,  f)"

.SS "init_indices ( array)"

.SS "init_is_xonly ( case)"

.SS "init_optional_expected ( case)"

.SS "sign_error ( case)"

.SS "verify_error ( case)"

.SH "Variable Documentation"
.PP 
.SS "all_cases"
\fBInitial value:\fP
.nf
1 =  (
2         data["valid_test_cases"]
3         + data["sign_error_test_cases"]
4         + data["verify_error_test_cases"]
5         + data["verify_fail_test_cases"]
6     )
.PP
.fi

.SS "data = json\&.load(f)"

.SS "max_key_indices"
\fBInitial value:\fP
.nf
1 =  max(
2         len(test_case["key_indices"]) for test_case in data["valid_test_cases"]
3     )
.PP
.fi

.SS "max_nonce_indices"
\fBInitial value:\fP
.nf
1 =  max(
2         len(test_case["nonce_indices"]) if "nonce_indices" in test_case else 0
3         for test_case in all_cases
4     )
.PP
.fi

.SS "max_psig_indices = max(len(test_case['psig_indices']) \fBfor\fP test_case in \fBall_cases\fP)"

.SS "max_pubkeys = 0"

.SS "max_tweak_indices"
\fBInitial value:\fP
.nf
1 =  max(
2         len(test_case["tweak_indices"]) for test_case in data["error_test_cases"]
3     )
.PP
.fi

.SS "num_aggnonces = len(\fBdata\fP['aggnonces'])"

.SS "num_error_cases = len(\fBdata\fP['error_test_cases'])"

.SS "num_msgs = len(\fBdata\fP['msgs'])"

.SS "num_pnonces = len(\fBdata\fP['pnonces'])"

.SS "num_psigs = len(\fBdata\fP['psigs'])"

.SS "num_pubkeys = len(\fBdata\fP['pubkeys'])"

.SS "num_pubnonces = len(\fBdata\fP['pnonces'])"

.SS "num_secnonces = len(\fBdata\fP['secnonces'])"

.SS "num_sign_error_cases = len(\fBdata\fP['sign_error_test_cases'])"

.SS "num_tests = len(\fBdata\fP['test_cases'])"

.SS "num_tweaks = len(\fBdata\fP['tweaks'])"

.SS "num_valid_cases = len(\fBdata\fP['valid_test_cases'])"

.SS "num_verify_error_cases = len(\fBdata\fP['verify_error_test_cases'])"

.SS "num_verify_fail_cases = len(\fBdata\fP['verify_fail_test_cases'])"

.SS "int pnonce_indices_len = 2"

.SS "tuple s"
\fBInitial value:\fP
.nf
1 =  (
2     
3     % sys\&.argv[0]
4 )
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
