.TH "src/secp256k1/src/modules/schnorrsig/tests_exhaustive_impl.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/modules/schnorrsig/tests_exhaustive_impl.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./include/secp256k1_schnorrsig\&.h'\fP
.br
\fR#include 'main_impl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUM_INVALID_KEYS\fP   (sizeof(invalid_pubkey_bytes) / sizeof(invalid_pubkey_bytes[0]))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NUM_INVALID_KEYS   (sizeof(invalid_pubkey_bytes) / sizeof(invalid_pubkey_bytes[0]))"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
