.TH "src/leveldb/util/testharness.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/util/testharness.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include 'leveldb/status\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTester\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.ti -1c
.RI "namespace \fBleveldb::test\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBINARY_OP\fP(\fBname\fP,  op)"
.br
.ti -1c
.RI "#define \fBASSERT_TRUE\fP(c)"
.br
.ti -1c
.RI "#define \fBASSERT_OK\fP(s)"
.br
.ti -1c
.RI "#define \fBASSERT_EQ\fP(a,  b)"
.br
.ti -1c
.RI "#define \fBASSERT_NE\fP(a,  b)"
.br
.ti -1c
.RI "#define \fBASSERT_GE\fP(a,  b)"
.br
.ti -1c
.RI "#define \fBASSERT_GT\fP(a,  b)"
.br
.ti -1c
.RI "#define \fBASSERT_LE\fP(a,  b)"
.br
.ti -1c
.RI "#define \fBASSERT_LT\fP(a,  b)"
.br
.ti -1c
.RI "#define \fBTCONCAT\fP(a,  b)"
.br
.ti -1c
.RI "#define \fBTCONCAT1\fP(a,  b)"
.br
.ti -1c
.RI "#define \fBTEST\fP(base,  \fBname\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBRunAllTests\fP ()"
.br
.ti -1c
.RI "std::string \fBTmpDir\fP ()"
.br
.ti -1c
.RI "int \fBRandomSeed\fP ()"
.br
.ti -1c
.RI "bool \fBRegisterTest\fP (const char *base, const char *\fBname\fP, void(*func)())"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASSERT_EQ( a,  b)"
\fBValue:\fP
.nf
  ::leveldb::test::Tester(__FILE__, __LINE__)\&.IsEq((a), (b))
.PP
.fi

.SS "#define ASSERT_GE( a,  b)"
\fBValue:\fP
.nf
  ::leveldb::test::Tester(__FILE__, __LINE__)\&.IsGe((a), (b))
.PP
.fi

.SS "#define ASSERT_GT( a,  b)"
\fBValue:\fP
.nf
  ::leveldb::test::Tester(__FILE__, __LINE__)\&.IsGt((a), (b))
.PP
.fi

.SS "#define ASSERT_LE( a,  b)"
\fBValue:\fP
.nf
  ::leveldb::test::Tester(__FILE__, __LINE__)\&.IsLe((a), (b))
.PP
.fi

.SS "#define ASSERT_LT( a,  b)"
\fBValue:\fP
.nf
  ::leveldb::test::Tester(__FILE__, __LINE__)\&.IsLt((a), (b))
.PP
.fi

.SS "#define ASSERT_NE( a,  b)"
\fBValue:\fP
.nf
  ::leveldb::test::Tester(__FILE__, __LINE__)\&.IsNe((a), (b))
.PP
.fi

.SS "#define ASSERT_OK( s)"
\fBValue:\fP
.nf
::leveldb::test::Tester(__FILE__, __LINE__)\&.IsOk((s))
.PP
.fi

.SS "#define ASSERT_TRUE( c)"
\fBValue:\fP
.nf
::leveldb::test::Tester(__FILE__, __LINE__)\&.Is((c), #c)
.PP
.fi

.SS "#define BINARY_OP( \fBname\fP,  op)"
\fBValue:\fP
.nf
  template <class X, class Y>                        \\
  Tester& name(const X& x, const Y& y) {             \\
    if (!(x op y)) {                                 \\
      ss_ << " failed: " << x << (" " #op " ") << y; \\
      ok_ = false;                                   \\
    }                                                \\
    return *this;                                    \\
  }
.PP
.fi

.SS "#define TCONCAT( a,  b)"
\fBValue:\fP
.nf
TCONCAT1(a, b)
.PP
.fi

.SS "#define TCONCAT1( a,  b)"
\fBValue:\fP
.nf
a##b
.PP
.fi

.SS "#define TEST( base,  \fBname\fP)"
\fBValue:\fP
.nf
  class TCONCAT(_Test_, name) : public base {                         \\
   public:                                                            \\
    void _Run();                                                      \\
    static void _RunIt() {                                            \\
      TCONCAT(_Test_, name) t;                                        \\
      t\&._Run();                                                       \\
    }                                                                 \\
  };                                                                  \\
  bool TCONCAT(_Test_ignored_, name) = ::leveldb::test::RegisterTest( \\
      #base, #name, &TCONCAT(_Test_, name)::_RunIt);                  \\
  void TCONCAT(_Test_, name)::_Run()
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
