.TH "TestMemPoolEntryHelper" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestMemPoolEntryHelper
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <txmempool\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCTxMemPoolEntry\fP \fBFromTx\fP (const \fBCMutableTransaction\fP &tx) const"
.br
.ti -1c
.RI "\fBCTxMemPoolEntry\fP \fBFromTx\fP (const \fBCTransactionRef\fP &tx) const"
.br
.ti -1c
.RI "\fBTestMemPoolEntryHelper\fP & \fBFee\fP (\fBCAmount\fP _fee)"
.br
.ti -1c
.RI "\fBTestMemPoolEntryHelper\fP & \fBTime\fP (\fBNodeSeconds\fP tp)"
.br
.ti -1c
.RI "\fBTestMemPoolEntryHelper\fP & \fBHeight\fP (unsigned int _height)"
.br
.ti -1c
.RI "\fBTestMemPoolEntryHelper\fP & \fBSequence\fP (uint64_t _seq)"
.br
.ti -1c
.RI "\fBTestMemPoolEntryHelper\fP & \fBSpendsCoinbase\fP (bool _flag)"
.br
.ti -1c
.RI "\fBTestMemPoolEntryHelper\fP & \fBSigOpsCost\fP (unsigned int _sigopsCost)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCAmount\fP \fBnFee\fP {0}"
.br
.ti -1c
.RI "\fBNodeSeconds\fP \fBtime\fP {}"
.br
.ti -1c
.RI "unsigned int \fBnHeight\fP {1}"
.br
.ti -1c
.RI "uint64_t \fBm_sequence\fP {0}"
.br
.ti -1c
.RI "bool \fBspendsCoinbase\fP {false}"
.br
.ti -1c
.RI "unsigned int \fBsigOpCost\fP {4}"
.br
.ti -1c
.RI "\fBLockPoints\fP \fBlp\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBTestMemPoolEntryHelper\fP & Fee (\fBCAmount\fP _fee)\fR [inline]\fP"

.SS "\fBCTxMemPoolEntry\fP FromTx (const \fBCMutableTransaction\fP & tx) const"

.SS "\fBCTxMemPoolEntry\fP FromTx (const \fBCTransactionRef\fP & tx) const"

.SS "\fBTestMemPoolEntryHelper\fP & Height (unsigned int _height)\fR [inline]\fP"

.SS "\fBTestMemPoolEntryHelper\fP & Sequence (uint64_t _seq)\fR [inline]\fP"

.SS "\fBTestMemPoolEntryHelper\fP & SigOpsCost (unsigned int _sigopsCost)\fR [inline]\fP"

.SS "\fBTestMemPoolEntryHelper\fP & SpendsCoinbase (bool _flag)\fR [inline]\fP"

.SS "\fBTestMemPoolEntryHelper\fP & Time (\fBNodeSeconds\fP tp)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBLockPoints\fP lp"

.SS "uint64_t m_sequence {0}"

.SS "\fBCAmount\fP nFee {0}"

.SS "unsigned int nHeight {1}"

.SS "unsigned int sigOpCost {4}"

.SS "bool spendsCoinbase {false}"

.SS "\fBNodeSeconds\fP time {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
