.TH "src/util/threadnames.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/threadnames.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButil\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBThreadRename\fP (const std::string &)"
.br
.ti -1c
.RI "void \fBThreadSetInternalName\fP (const std::string &)"
.br
.RI "Set the internal (in-memory) name of the current thread only\&. "
.ti -1c
.RI "std::string \fBThreadGetInternalName\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
