.TH "src/test/fuzz/timeoffsets.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/timeoffsets.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/timeoffsets\&.h>\fP
.br
\fR#include <node/warnings\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <functional>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_timeoffsets\fP ()"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (timeoffsets,\&.\fBinit\fP=\fBinitialize_timeoffsets\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (timeoffsets , \&. init = \fR\fBinitialize_timeoffsets\fP\fP)"

.SS "void initialize_timeoffsets ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
