.TH "TimeOffsets" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeOffsets
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <timeoffsets\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeOffsets\fP (\fBnode::Warnings\fP &warnings)"
.br
.ti -1c
.RI "void \fBAdd\fP (std::chrono::seconds offset) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_mutex)"
.br
.ti -1c
.RI "std::chrono::seconds \fBMedian\fP () const \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_mutex)"
.br
.ti -1c
.RI "bool \fBWarnIfOutOfSync\fP () const \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!m_mutex)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTimeOffsets\fP (\fBnode::Warnings\fP & warnings)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Add (std::chrono::seconds offset)"
Add a new time offset sample\&. 
.SS "std::chrono::seconds Median () const"
Compute and return the median of the collected time offset samples\&. The median is returned as 0 when there are less than 5 samples\&. 
.SS "bool WarnIfOutOfSync () const"
Raise warnings if the median time offset exceeds the warnings threshold\&. Returns true if warnings were raised\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
