.TH "src/util/time.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/time.h
.SH SYNOPSIS
.br
.PP
\fR#include <chrono>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBNodeClock\fP"
.br
.ti -1c
.RI "struct \fBMockableSteadyClock\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBNodeSeconds\fP = std::chrono::time_point<\fBNodeClock\fP, std::chrono::seconds>"
.br
.ti -1c
.RI "using \fBSteadyClock\fP = std::chrono::steady_clock"
.br
.ti -1c
.RI "using \fBSteadySeconds\fP = std::chrono::time_point<std::chrono::steady_clock, std::chrono::seconds>"
.br
.ti -1c
.RI "using \fBSteadyMilliseconds\fP = std::chrono::time_point<std::chrono::steady_clock, std::chrono::milliseconds>"
.br
.ti -1c
.RI "using \fBSteadyMicroseconds\fP = std::chrono::time_point<std::chrono::steady_clock, std::chrono::microseconds>"
.br
.ti -1c
.RI "using \fBSystemClock\fP = std::chrono::system_clock"
.br
.ti -1c
.RI "using \fBHoursDouble\fP = std::chrono::duration<double, std::chrono::hours::period>"
.br
.ti -1c
.RI "using \fBSecondsDouble\fP = std::chrono::duration<double, std::chrono::seconds::period>"
.br
.ti -1c
.RI "using \fBMillisecondsDouble\fP = std::chrono::duration<double, std::chrono::milliseconds::period>"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBUninterruptibleSleep\fP (const std::chrono::microseconds &n)"
.br
.ti -1c
.RI "template<typename Dur1, typename Dur2> constexpr auto \fBTicks\fP (Dur2 d)"
.br
.ti -1c
.RI "template<typename Duration, typename Timepoint> constexpr auto \fBTicksSinceEpoch\fP (Timepoint t)"
.br
.ti -1c
.RI "constexpr int64_t \fBcount_seconds\fP (std::chrono::seconds t)"
.br
.ti -1c
.RI "constexpr int64_t \fBcount_milliseconds\fP (std::chrono::milliseconds t)"
.br
.ti -1c
.RI "constexpr int64_t \fBcount_microseconds\fP (std::chrono::microseconds t)"
.br
.ti -1c
.RI "int64_t \fBGetTime\fP ()"
.br
.ti -1c
.RI "void \fBSetMockTime\fP (int64_t nMockTimeIn)"
.br
.ti -1c
.RI "void \fBSetMockTime\fP (std::chrono::seconds mock_time_in)"
.br
.ti -1c
.RI "void \fBSetMockTime\fP (std::chrono::time_point< \fBNodeClock\fP, std::chrono::seconds > mock)"
.br
.ti -1c
.RI "std::chrono::seconds \fBGetMockTime\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP \fBNow\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBT\fP \fBGetTime\fP ()"
.br
.ti -1c
.RI "std::string \fBFormatISO8601DateTime\fP (int64_t nTime)"
.br
.ti -1c
.RI "std::string \fBFormatISO8601Date\fP (int64_t nTime)"
.br
.ti -1c
.RI "std::optional< int64_t > \fBParseISO8601DateTime\fP (std::string_view str)"
.br
.ti -1c
.RI "struct timeval \fBMillisToTimeval\fP (int64_t nTimeout)"
.br
.ti -1c
.RI "struct timeval \fBMillisToTimeval\fP (std::chrono::milliseconds ms)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBHoursDouble\fP = std::chrono::duration<double, std::chrono::hours::period>"

.SS "using \fBMillisecondsDouble\fP = std::chrono::duration<double, std::chrono::milliseconds::period>"

.SS "using \fBNodeSeconds\fP = std::chrono::time_point<\fBNodeClock\fP, std::chrono::seconds>"

.SS "using \fBSecondsDouble\fP = std::chrono::duration<double, std::chrono::seconds::period>"

.SS "using \fBSteadyClock\fP = std::chrono::steady_clock"

.SS "using \fBSteadyMicroseconds\fP = std::chrono::time_point<std::chrono::steady_clock, std::chrono::microseconds>"

.SS "using \fBSteadyMilliseconds\fP = std::chrono::time_point<std::chrono::steady_clock, std::chrono::milliseconds>"

.SS "using \fBSteadySeconds\fP = std::chrono::time_point<std::chrono::steady_clock, std::chrono::seconds>"

.SS "using \fBSystemClock\fP = std::chrono::system_clock"

.SH "Function Documentation"
.PP 
.SS "int64_t count_microseconds (std::chrono::microseconds t)\fR [constexpr]\fP"

.SS "int64_t count_milliseconds (std::chrono::milliseconds t)\fR [constexpr]\fP"

.SS "int64_t count_seconds (std::chrono::seconds t)\fR [constexpr]\fP"

.SS "std::string FormatISO8601Date (int64_t nTime)"

.SS "std::string FormatISO8601DateTime (int64_t nTime)"
ISO 8601 formatting is preferred\&. Use the FormatISO8601{DateTime,Date} helper functions if possible\&. 
.SS "std::chrono::seconds GetMockTime ()"
For testing 
.SS "template<typename \fBT\fP> \fBT\fP GetTime ()"
DEPRECATED, see GetTime 
.SS "int64_t GetTime ()"
DEPRECATED Use either ClockType::now() or \fBNow<TimePointType>()\fP if a cast is needed\&. ClockType is
.IP "\(bu" 2
SteadyClock/std::chrono::steady_clock for steady time
.IP "\(bu" 2
SystemClock/std::chrono::system_clock for system time
.IP "\(bu" 2
\fBNodeClock\fP for mockable system time 
.PP

.SS "struct timeval MillisToTimeval (int64_t nTimeout)"
Convert milliseconds to a struct timeval for e\&.g\&. select\&. 
.SS "struct timeval MillisToTimeval (std::chrono::milliseconds ms)"
Convert milliseconds to a struct timeval for e\&.g\&. select\&. 
.SS "template<typename \fBT\fP> \fBT\fP Now ()"
Return the current time point cast to the given precision\&. Only use this when an exact precision is needed, otherwise use T::clock::now() directly\&. 
.SS "std::optional< int64_t > ParseISO8601DateTime (std::string_view str)"

.SS "void SetMockTime (int64_t nMockTimeIn)"
DEPRECATED Use SetMockTime with chrono type

.PP
\fBParameters\fP
.RS 4
\fInMockTimeIn\fP Time in seconds\&. 
.RE
.PP

.SS "void SetMockTime (std::chrono::seconds mock_time_in)"
For testing\&. Set e\&.g\&. with the setmocktime rpc, or -mocktime argument 
.SS "void SetMockTime (std::chrono::time_point< \fBNodeClock\fP, std::chrono::seconds > mock)"

.SS "template<typename Dur1, typename Dur2> auto Ticks (Dur2 d)\fR [constexpr]\fP"
Helper to count the seconds of a duration/time_point\&.

.PP
All durations/time_points should be using std::chrono and calling this should generally be avoided in code\&. Though, it is still preferred to an inline t\&.count() to protect against a reliance on the exact type of t\&.

.PP
This helper is used to convert durations/time_points before passing them over an interface that doesn't support std::chrono (e\&.g\&. RPC, debug log, or the GUI) 
.SS "template<typename Duration, typename Timepoint> auto TicksSinceEpoch (Timepoint t)\fR [constexpr]\fP"

.SS "void UninterruptibleSleep (const std::chrono::microseconds & n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
