.TH "FormatStringCheck< num_params >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormatStringCheck< num_params >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tinyformat\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "consteval \fBFormatStringCheck\fP (const char *str)"
.br
.ti -1c
.RI "\fBFormatStringCheck\fP (\fBLIFETIMEBOUND\fP const \fBRuntimeFormat\fP &run)"
.br
.ti -1c
.RI "\fBFormatStringCheck\fP (\fButil::ConstevalFormatString\fP< num_params > str)"
.br
.ti -1c
.RI "\fBoperator const char *\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBfmt\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<unsigned num_params> FormatStringCheck (const char * str)\fR [inline]\fP, \fR [consteval]\fP"

.SS "template<unsigned num_params> FormatStringCheck (\fBLIFETIMEBOUND\fP const \fBRuntimeFormat\fP & run)\fR [inline]\fP"

.SS "template<unsigned num_params> FormatStringCheck (\fButil::ConstevalFormatString\fP< num_params > str)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<unsigned num_params> operator const char * ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "template<unsigned num_params> const char* fmt"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
