.TH "is_convertible< T1, T2 >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_convertible< T1, T2 >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tinyformat\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "template<typename T1, typename T2> const bool value\fR [static]\fP"
\fBInitial value:\fP
.nf
=
            sizeof(tryConvert(makeT1())) == sizeof(succeed)
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
