.TH "FormatArg" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormatArg
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tinyformat\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormatArg\fP ()=default"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBFormatArg\fP (const \fBT\fP &value)"
.br
.ti -1c
.RI "void \fBformat\fP (std::ostream &out, const char *fmtBegin, const char *fmtEnd, int ntrunc) const"
.br
.ti -1c
.RI "int \fBtoInt\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FormatArg ()\fR [default]\fP"

.SS "template<typename \fBT\fP> FormatArg (const \fBT\fP & value)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void format (std::ostream & out, const char * fmtBegin, const char * fmtEnd, int ntrunc) const\fR [inline]\fP"

.SS "int toInt () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
