.TH "convertToInt< T, convertible >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
convertToInt< T, convertible >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tinyformat\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBinvoke\fP (const \fBT\fP &)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBT\fP, bool convertible = is_convertible<T,int>::value> int invoke (const \fBT\fP & )\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
