.TH "formatValueAsType< T, fmtT, convertible >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatValueAsType< T, fmtT, convertible >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tinyformat\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinvoke\fP (std::ostream &, const \fBT\fP &)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBT\fP, typename fmtT, bool convertible = is_convertible<T, fmtT>::value> void invoke (std::ostream & , const \fBT\fP & )\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
