.TH "TokenPipeEnd" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TokenPipeEnd
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tokenpipe\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBStatus\fP { \fBTS_ERR\fP = -1, \fBTS_EOS\fP = -2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTokenPipeEnd\fP (int fd=\-1)"
.br
.ti -1c
.RI "\fB~TokenPipeEnd\fP ()"
.br
.ti -1c
.RI "int \fBTokenWrite\fP (uint8_t token)"
.br
.ti -1c
.RI "int \fBTokenRead\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "bool \fBIsOpen\fP ()"
.br
.ti -1c
.RI "\fBTokenPipeEnd\fP (\fBTokenPipeEnd\fP &&other)"
.br
.ti -1c
.RI "\fBTokenPipeEnd\fP & \fBoperator=\fP (\fBTokenPipeEnd\fP &&other)"
.br
.ti -1c
.RI "\fBTokenPipeEnd\fP (const \fBTokenPipeEnd\fP &)=delete"
.br
.ti -1c
.RI "\fBTokenPipeEnd\fP & \fBoperator=\fP (const \fBTokenPipeEnd\fP &)=delete"
.br
.in -1c
.SH "Detailed Description"
.PP 
One end of a token pipe\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBStatus\fP\fBStatus\fP"
Return value constants for TokenWrite and TokenRead\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BITS_ERR \fP
I/O error\&. 
.TP
\f(BITS_EOS \fP
Unexpected end of stream\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTokenPipeEnd\fP (int fd = \fR\-1\fP)"

.SS "~\fBTokenPipeEnd\fP ()"

.SS "\fBTokenPipeEnd\fP (\fBTokenPipeEnd\fP && other)\fR [inline]\fP"

.SS "\fBTokenPipeEnd\fP (const \fBTokenPipeEnd\fP & )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Close ()"
Explicit close function\&. 
.SS "bool IsOpen ()\fR [inline]\fP"
Return whether endpoint is open\&. 
.SS "\fBTokenPipeEnd\fP & operator= (const \fBTokenPipeEnd\fP & )\fR [delete]\fP"

.SS "\fBTokenPipeEnd\fP & operator= (\fBTokenPipeEnd\fP && other)\fR [inline]\fP"

.SS "int TokenRead ()"
Read token from endpoint\&.

.PP
\fBReturns\fP
.RS 4
>=0 Token value, if successful\&. <0 if error: TS_ERR If an error happened\&. TS_EOS If end of stream happened\&. 
.RE
.PP

.SS "int TokenWrite (uint8_t token)"
Write token to endpoint\&.

.PP
\fBReturns\fP
.RS 4
0 If successful\&. <0 if error: TS_ERR If an error happened\&. TS_EOS If end of stream happened\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
