.TH "TokenPipe" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TokenPipe
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tokenpipe\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~TokenPipe\fP ()"
.br
.ti -1c
.RI "\fBTokenPipeEnd\fP \fBTakeReadEnd\fP ()"
.br
.ti -1c
.RI "\fBTokenPipeEnd\fP \fBTakeWriteEnd\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "\fBTokenPipe\fP (\fBTokenPipe\fP &&other)"
.br
.ti -1c
.RI "\fBTokenPipe\fP & \fBoperator=\fP (\fBTokenPipe\fP &&other)"
.br
.ti -1c
.RI "\fBTokenPipe\fP (const \fBTokenPipe\fP &)=delete"
.br
.ti -1c
.RI "\fBTokenPipe\fP & \fBoperator=\fP (const \fBTokenPipe\fP &)=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::optional< \fBTokenPipe\fP > \fBMake\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
An interprocess or interthread pipe for sending tokens (one-byte values) over\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "~\fBTokenPipe\fP ()"

.SS "\fBTokenPipe\fP (\fBTokenPipe\fP && other)\fR [inline]\fP"

.SS "\fBTokenPipe\fP (const \fBTokenPipe\fP & )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Close ()"
Close and end of the pipe that hasn't been moved out\&. 
.SS "std::optional< \fBTokenPipe\fP > Make ()\fR [static]\fP"
Create a new pipe\&. 
.PP
\fBReturns\fP
.RS 4
The created \fBTokenPipe\fP, or an empty std::nullopt in case of error\&. 
.RE
.PP

.SS "\fBTokenPipe\fP & operator= (const \fBTokenPipe\fP & )\fR [delete]\fP"

.SS "\fBTokenPipe\fP & operator= (\fBTokenPipe\fP && other)\fR [inline]\fP"

.SS "\fBTokenPipeEnd\fP TakeReadEnd ()"
Take the read end of this pipe\&. This can only be called once, as the object will be moved out\&. 
.SS "\fBTokenPipeEnd\fP TakeWriteEnd ()"
Take the write end of this pipe\&. This should only be called once, as the object will be moved out\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
