.TH "src/torcontrol.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/torcontrol.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <torcontrol\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <chainparamsbase\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <compat/compat\&.h>\fP
.br
\fR#include <crypto/hmac_sha256\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <net\&.h>\fP
.br
\fR#include <netaddress\&.h>\fP
.br
\fR#include <netbase\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/readwritefile\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <util/thread\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <deque>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <map>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <set>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <event2/buffer\&.h>\fP
.br
\fR#include <event2/bufferevent\&.h>\fP
.br
\fR#include <event2/event\&.h>\fP
.br
\fR#include <event2/thread\&.h>\fP
.br
\fR#include <event2/util\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::pair< std::string, std::string > \fBSplitTorReplyLine\fP (const std::string &s)"
.br
.ti -1c
.RI "std::map< std::string, std::string > \fBParseTorReplyMapping\fP (const std::string &s)"
.br
.ti -1c
.RI "void \fBStartTorControl\fP (\fBCService\fP onion_service_target)"
.br
.ti -1c
.RI "void \fBInterruptTorControl\fP ()"
.br
.ti -1c
.RI "void \fBStopTorControl\fP ()"
.br
.ti -1c
.RI "\fBCService\fP \fBDefaultOnionServiceTarget\fP (uint16_t port)"
.br
.ti -1c
.RI "void \fBReplaceAll\fP (std::string &in_out, const std::string &search, const std::string &substitute)"
.br
.ti -1c
.RI "std::vector< std::string > \fBSplitString\fP (std::string_view str, char sep)"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::string \fBToString\fP (const \fBT\fP &t)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBDEFAULT_TOR_CONTROL\fP = '127\&.0\&.0\&.1:' + \fBToString\fP(\fBDEFAULT_TOR_CONTROL_PORT\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCService\fP DefaultOnionServiceTarget (uint16_t port)"

.SS "void InterruptTorControl ()"

.SS "std::map< std::string, std::string > ParseTorReplyMapping (const std::string & s)"
Parse reply arguments in the form 'METHODS=COOKIE,SAFECOOKIE COOKIEFILE="\&.\&.\&./control_auth_cookie"'\&. Returns a map of keys to values, or an empty map if there was an error\&. Grammar is implicitly defined in https://spec.torproject.org/control-spec by the server reply formats for PROTOCOLINFO (S3\&.21), AUTHCHALLENGE (S3\&.24), and ADD_ONION (S3\&.27)\&. See also sections 2\&.1 and 2\&.3\&. Unescape value\&. Per https://spec.torproject.org/control-spec section 2\&.1\&.1:

.PP
For future-proofing, controller implementers MAY use the following rules to be compatible with buggy Tor implementations and with future ones that implement the spec as intended:

.PP
Read 
.br
 \\t \\r and \\0 \&.\&.\&. \\377 as C escapes\&. Treat a backslash followed by any other character as that character\&.
.SS "void ReplaceAll (std::string & in_out, const std::string & search, const std::string & substitute)"

.SS "std::vector< std::string > SplitString (std::string_view str, char sep)\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "std::pair< std::string, std::string > SplitTorReplyLine (const std::string & s)"

.SS "void StartTorControl (\fBCService\fP onion_service_target)"

.SS "void StopTorControl ()"

.SS "template<typename \fBT\fP> std::string ToString (const \fBT\fP & t)"
Locale-independent version of std::to_string 
.SH "Variable Documentation"
.PP 
.SS "const std::string DEFAULT_TOR_CONTROL = '127\&.0\&.0\&.1:' + \fBToString\fP(\fBDEFAULT_TOR_CONTROL_PORT\fP)"
Default control ip and port 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
