.TH "TorController" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TorController
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <torcontrol\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTorController\fP (struct event_base *base, const std::string &tor_control_center, const \fBCService\fP &target)"
.br
.ti -1c
.RI "\fBTorController\fP ()"
.br
.ti -1c
.RI "\fB~TorController\fP ()"
.br
.ti -1c
.RI "\fBfs::path\fP \fBGetPrivateKeyFile\fP ()"
.br
.ti -1c
.RI "void \fBReconnect\fP ()"
.br
.ti -1c
.RI "void \fBget_socks_cb\fP (\fBTorControlConnection\fP &conn, const \fBTorControlReply\fP &reply)"
.br
.ti -1c
.RI "void \fBadd_onion_cb\fP (\fBTorControlConnection\fP &conn, const \fBTorControlReply\fP &reply)"
.br
.ti -1c
.RI "void \fBauth_cb\fP (\fBTorControlConnection\fP &conn, const \fBTorControlReply\fP &reply)"
.br
.ti -1c
.RI "void \fBauthchallenge_cb\fP (\fBTorControlConnection\fP &conn, const \fBTorControlReply\fP &reply)"
.br
.ti -1c
.RI "void \fBprotocolinfo_cb\fP (\fBTorControlConnection\fP &conn, const \fBTorControlReply\fP &reply)"
.br
.ti -1c
.RI "void \fBconnected_cb\fP (\fBTorControlConnection\fP &conn)"
.br
.ti -1c
.RI "void \fBdisconnected_cb\fP (\fBTorControlConnection\fP &conn)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBreconnect_cb\fP (evutil_socket_t fd, short what, void *arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Controller that connects to Tor control socket, authenticate, then create and maintain an ephemeral onion service\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTorController\fP (struct event_base * base, const std::string & tor_control_center, const \fBCService\fP & target)"

.SS "\fBTorController\fP ()\fR [inline]\fP"

.SS "~\fBTorController\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void add_onion_cb (\fBTorControlConnection\fP & conn, const \fBTorControlReply\fP & reply)"
Callback for ADD_ONION result 
.SS "void auth_cb (\fBTorControlConnection\fP & conn, const \fBTorControlReply\fP & reply)"
Callback for AUTHENTICATE result 
.SS "void authchallenge_cb (\fBTorControlConnection\fP & conn, const \fBTorControlReply\fP & reply)"
Callback for AUTHCHALLENGE result 
.SS "void connected_cb (\fBTorControlConnection\fP & conn)"
Callback after successful connection 
.SS "void disconnected_cb (\fBTorControlConnection\fP & conn)"
Callback after connection lost or failed connection attempt 
.SS "void get_socks_cb (\fBTorControlConnection\fP & conn, const \fBTorControlReply\fP & reply)"
Callback for GETINFO net/listeners/socks result 
.SS "\fBfs::path\fP GetPrivateKeyFile ()"
Get name of file to store private key in 
.SS "void protocolinfo_cb (\fBTorControlConnection\fP & conn, const \fBTorControlReply\fP & reply)"
Callback for PROTOCOLINFO result 
.SS "void Reconnect ()"
Reconnect, after getting disconnected 
.SS "void reconnect_cb (evutil_socket_t fd, short what, void * arg)\fR [static]\fP"
Callback for reconnect timer 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
