.TH "TorControlReply" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TorControlReply
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <torcontrol\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTorControlReply\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBlines\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reply from Tor, can be single or multi-line 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTorControlReply\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Clear ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "int code"

.SS "std::vector<std::string> lines"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
