.TH "src/test/torcontrol_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/torcontrol_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <map>\fP
.br
\fR#include <string>\fP
.br
\fR#include <utility>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::pair< std::string, std::string > \fBSplitTorReplyLine\fP (const std::string &s)"
.br
.ti -1c
.RI "std::map< std::string, std::string > \fBParseTorReplyMapping\fP (const std::string &s)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (util_SplitTorReplyLine)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (util_ParseTorReplyMapping)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (util_ParseTorReplyMapping )"

.SS "BOOST_AUTO_TEST_CASE (util_SplitTorReplyLine )"

.SS "std::map< std::string, std::string > ParseTorReplyMapping (const std::string & s)"
Parse reply arguments in the form 'METHODS=COOKIE,SAFECOOKIE COOKIEFILE="\&.\&.\&./control_auth_cookie"'\&. Returns a map of keys to values, or an empty map if there was an error\&. Grammar is implicitly defined in https://spec.torproject.org/control-spec by the server reply formats for PROTOCOLINFO (S3\&.21), AUTHCHALLENGE (S3\&.24), and ADD_ONION (S3\&.27)\&. See also sections 2\&.1 and 2\&.3\&. Unescape value\&. Per https://spec.torproject.org/control-spec section 2\&.1\&.1:

.PP
For future-proofing, controller implementers MAY use the following rules to be compatible with buggy Tor implementations and with future ones that implement the spec as intended:

.PP
Read 
.br
 \\t \\r and \\0 \&.\&.\&. \\377 as C escapes\&. Treat a backslash followed by any other character as that character\&.
.SS "std::pair< std::string, std::string > SplitTorReplyLine (const std::string & s)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
