.TH "TrafficGraphWidget" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrafficGraphWidget
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <trafficgraphwidget\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateRates\fP ()"
.br
.ti -1c
.RI "void \fBsetGraphRange\fP (std::chrono::minutes new_range)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrafficGraphWidget\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBsetClientModel\fP (\fBClientModel\fP *model)"
.br
.ti -1c
.RI "std::chrono::minutes \fBgetGraphRange\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTrafficGraphWidget\fP (QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void clear ()\fR [slot]\fP"

.SS "std::chrono::minutes getGraphRange () const"

.SS "void paintEvent (QPaintEvent * )\fR [override]\fP, \fR [protected]\fP"

.SS "void setClientModel (\fBClientModel\fP * model)"

.SS "void setGraphRange (std::chrono::minutes new_range)\fR [slot]\fP"

.SS "void updateRates ()\fR [slot]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
