.TH "src/qt/trafficgraphwidget.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/trafficgraphwidget.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <interfaces/node\&.h>\fP
.br
\fR#include <qt/trafficgraphwidget\&.h>\fP
.br
\fR#include <qt/clientmodel\&.h>\fP
.br
\fR#include <QPainter>\fP
.br
\fR#include <QPainterPath>\fP
.br
\fR#include <QColor>\fP
.br
\fR#include <QTimer>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <cmath>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDESIRED_SAMPLES\fP   800"
.br
.ti -1c
.RI "#define \fBXMARGIN\fP   10"
.br
.ti -1c
.RI "#define \fBYMARGIN\fP   10"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DESIRED_SAMPLES   800"

.SS "#define XMARGIN   10"

.SS "#define YMARGIN   10"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
