.TH "src/test/transaction_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/transaction_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/data/tx_invalid\&.json\&.h>\fP
.br
\fR#include <test/data/tx_valid\&.json\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <checkqueue\&.h>\fP
.br
\fR#include <clientversion\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <consensus/tx_check\&.h>\fP
.br
\fR#include <consensus/tx_verify\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <core_io\&.h>\fP
.br
\fR#include <key\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <policy/settings\&.h>\fP
.br
\fR#include <primitives/transaction_identifier\&.h>\fP
.br
\fR#include <script/interpreter\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <script/script_error\&.h>\fP
.br
\fR#include <script/sigcache\&.h>\fP
.br
\fR#include <script/sign\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br
\fR#include <script/solver\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/util/json\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/script\&.h>\fP
.br
\fR#include <test/util/transaction_utils\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <map>\fP
.br
\fR#include <string>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <univalue\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< unsigned char > \fBvaltype\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscript_verify_flags\fP \fBParseScriptFlags\fP (std::string strFlags)"
.br
.ti -1c
.RI "bool \fBCheckMapFlagNames\fP ()"
.br
.ti -1c
.RI "bool \fBCheckTxScripts\fP (const \fBCTransaction\fP &tx, const std::map< \fBCOutPoint\fP, \fBCScript\fP > &map_prevout_scriptPubKeys, const std::map< \fBCOutPoint\fP, int64_t > &map_prevout_values, \fBscript_verify_flags\fP \fBflags\fP, const \fBPrecomputedTransactionData\fP &txdata, const std::string &strTest, bool expect_valid)"
.br
.ti -1c
.RI "\fBscript_verify_flags\fP \fBTrimFlags\fP (\fBscript_verify_flags\fP \fBflags\fP)"
.br
.ti -1c
.RI "\fBscript_verify_flags\fP \fBFillFlags\fP (\fBscript_verify_flags\fP \fBflags\fP)"
.br
.ti -1c
.RI "std::set< \fBscript_verify_flags\fP > \fBExcludeIndividualFlags\fP (\fBscript_verify_flags\fP \fBflags\fP)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (tx_valid)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (tx_invalid)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (tx_no_inputs)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (tx_oversized)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (basic_transaction_tests)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_Get)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_big_witness_transaction)"
.br
.ti -1c
.RI "\fBSignatureData\fP \fBCombineSignatures\fP (const \fBCMutableTransaction\fP &input1, const \fBCMutableTransaction\fP &input2, const \fBCTransactionRef\fP tx)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_witness)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_IsStandard)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (max_standard_legacy_sigops)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (spends_witness_prog)"
.br
.ti -1c
.RI "std::vector< std::string > \fBSplitString\fP (std::string_view str, char sep)"
.br
.ti -1c
.RI "template<typename \fBT\fP> std::string \fBToString\fP (const \fBT\fP &t)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<unsigned char> \fBvaltype\fP"

.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (basic_transaction_tests )"

.SS "BOOST_AUTO_TEST_CASE (max_standard_legacy_sigops )"

.SS "BOOST_AUTO_TEST_CASE (spends_witness_prog )"
Sanity check the return value of SpendsNonAnchorWitnessProg for various output types\&. 
.SS "BOOST_AUTO_TEST_CASE (test_big_witness_transaction )"

.SS "BOOST_AUTO_TEST_CASE (test_Get )"

.SS "BOOST_AUTO_TEST_CASE (test_IsStandard )"

.SS "BOOST_AUTO_TEST_CASE (test_witness )"

.SS "BOOST_AUTO_TEST_CASE (tx_invalid )"

.SS "BOOST_AUTO_TEST_CASE (tx_no_inputs )"

.SS "BOOST_AUTO_TEST_CASE (tx_oversized )"

.SS "BOOST_AUTO_TEST_CASE (tx_valid )"

.SS "bool CheckMapFlagNames ()"

.SS "bool CheckTxScripts (const \fBCTransaction\fP & tx, const std::map< \fBCOutPoint\fP, \fBCScript\fP > & map_prevout_scriptPubKeys, const std::map< \fBCOutPoint\fP, int64_t > & map_prevout_values, \fBscript_verify_flags\fP flags, const \fBPrecomputedTransactionData\fP & txdata, const std::string & strTest, bool expect_valid)"

.SS "\fBSignatureData\fP CombineSignatures (const \fBCMutableTransaction\fP & input1, const \fBCMutableTransaction\fP & input2, const \fBCTransactionRef\fP tx)"

.SS "std::set< \fBscript_verify_flags\fP > ExcludeIndividualFlags (\fBscript_verify_flags\fP flags)"

.SS "\fBscript_verify_flags\fP FillFlags (\fBscript_verify_flags\fP flags)"

.SS "\fBscript_verify_flags\fP ParseScriptFlags (std::string strFlags)"

.SS "std::vector< std::string > SplitString (std::string_view str, char sep)\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "template<typename \fBT\fP> std::string ToString (const \fBT\fP & t)"
Locale-independent version of std::to_string 
.SS "\fBscript_verify_flags\fP TrimFlags (\fBscript_verify_flags\fP flags)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
