.TH "TransactionTablePriv" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionTablePriv
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionTablePriv\fP (\fBTransactionTableModel\fP *_parent)"
.br
.ti -1c
.RI "void \fBNotifyTransactionChanged\fP (const \fBTxid\fP &hash, \fBChangeType\fP status)"
.br
.ti -1c
.RI "void \fBDispatchNotifications\fP ()"
.br
.ti -1c
.RI "void \fBrefreshWallet\fP (\fBinterfaces::Wallet\fP &\fBwallet\fP)"
.br
.ti -1c
.RI "void \fBupdateWallet\fP (\fBinterfaces::Wallet\fP &\fBwallet\fP, const \fBTxid\fP &hash, int status, bool showTransaction)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "\fBTransactionRecord\fP * \fBindex\fP (\fBinterfaces::Wallet\fP &\fBwallet\fP, const \fBuint256\fP &cur_block_hash, const int idx)"
.br
.ti -1c
.RI "QString \fBdescribe\fP (\fBinterfaces::Node\fP &\fBnode\fP, \fBinterfaces::Wallet\fP &\fBwallet\fP, \fBTransactionRecord\fP *rec, \fBBitcoinUnit\fP unit)"
.br
.ti -1c
.RI "QString \fBgetTxHex\fP (\fBinterfaces::Wallet\fP &\fBwallet\fP, \fBTransactionRecord\fP *rec)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTransactionTableModel\fP * \fBparent\fP"
.br
.ti -1c
.RI "QList< \fBTransactionRecord\fP > \fBcachedWallet\fP"
.br
.RI "Local cache of wallet sorted by transaction hash\&. "
.ti -1c
.RI "bool \fBm_loaded\fP = false"
.br
.ti -1c
.RI "bool \fBm_loading\fP = false"
.br
.ti -1c
.RI "std::vector< \fBTransactionNotification\fP > \fBvQueueNotifications\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTransactionTablePriv\fP (\fBTransactionTableModel\fP * _parent)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QString describe (\fBinterfaces::Node\fP & node, \fBinterfaces::Wallet\fP & wallet, \fBTransactionRecord\fP * rec, \fBBitcoinUnit\fP unit)\fR [inline]\fP"

.SS "void DispatchNotifications ()"

.SS "QString getTxHex (\fBinterfaces::Wallet\fP & wallet, \fBTransactionRecord\fP * rec)\fR [inline]\fP"

.SS "\fBTransactionRecord\fP * index (\fBinterfaces::Wallet\fP & wallet, const \fBuint256\fP & cur_block_hash, const int idx)\fR [inline]\fP"

.SS "void NotifyTransactionChanged (const \fBTxid\fP & hash, \fBChangeType\fP status)"

.SS "void refreshWallet (\fBinterfaces::Wallet\fP & wallet)\fR [inline]\fP"

.SS "int size ()\fR [inline]\fP"

.SS "void updateWallet (\fBinterfaces::Wallet\fP & wallet, const \fBTxid\fP & hash, int status, bool showTransaction)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "QList<\fBTransactionRecord\fP> cachedWallet"

.PP
Local cache of wallet sorted by transaction hash\&. 
.SS "bool m_loaded = false"
True when model finishes loading all wallet transactions on start 
.SS "bool m_loading = false"
True when transactions are being notified, for instance when scanning 
.SS "\fBTransactionTableModel\fP* parent"

.SS "std::vector< \fBTransactionNotification\fP > vQueueNotifications"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
