.TH "src/test/util/transaction_utils.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/util/transaction_utils.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <coins\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <script/signingprovider\&.h>\fP
.br
\fR#include <test/util/transaction_utils\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCMutableTransaction\fP \fBBuildCreditingTransaction\fP (const \fBCScript\fP &scriptPubKey, int nValue)"
.br
.ti -1c
.RI "\fBCMutableTransaction\fP \fBBuildSpendingTransaction\fP (const \fBCScript\fP &scriptSig, const \fBCScriptWitness\fP &scriptWitness, const \fBCTransaction\fP &txCredit)"
.br
.ti -1c
.RI "std::vector< \fBCMutableTransaction\fP > \fBSetupDummyInputs\fP (\fBFillableSigningProvider\fP &keystoreRet, \fBCCoinsViewCache\fP &coinsRet, const std::array< \fBCAmount\fP, 4 > &nValues)"
.br
.ti -1c
.RI "void \fBBulkTransaction\fP (\fBCMutableTransaction\fP &tx, int32_t target_weight)"
.br
.ti -1c
.RI "bool \fBSignSignature\fP (const \fBSigningProvider\fP &provider, const \fBCScript\fP &fromPubKey, \fBCMutableTransaction\fP &txTo, unsigned int nIn, const \fBCAmount\fP &amount, int nHashType, \fBSignatureData\fP &sig_data)"
.br
.ti -1c
.RI "bool \fBSignSignature\fP (const \fBSigningProvider\fP &provider, const \fBCTransaction\fP &txFrom, \fBCMutableTransaction\fP &txTo, unsigned int nIn, int nHashType, \fBSignatureData\fP &sig_data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCMutableTransaction\fP BuildCreditingTransaction (const \fBCScript\fP & scriptPubKey, int nValue)"

.SS "\fBCMutableTransaction\fP BuildSpendingTransaction (const \fBCScript\fP & scriptSig, const \fBCScriptWitness\fP & scriptWitness, const \fBCTransaction\fP & txCredit)"

.SS "void BulkTransaction (\fBCMutableTransaction\fP & tx, int32_t target_weight)"

.SS "std::vector< \fBCMutableTransaction\fP > SetupDummyInputs (\fBFillableSigningProvider\fP & keystoreRet, \fBCCoinsViewCache\fP & coinsRet, const std::array< \fBCAmount\fP, 4 > & nValues)"

.SS "bool SignSignature (const \fBSigningProvider\fP & provider, const \fBCScript\fP & fromPubKey, \fBCMutableTransaction\fP & txTo, unsigned int nIn, const \fBCAmount\fP & amount, int nHashType, \fBSignatureData\fP & sig_data)"
Produce a satisfying script (scriptSig or witness)\&.

.PP
\fBParameters\fP
.RS 4
\fIprovider\fP Utility containing the information necessary to solve a script\&. 
.br
\fIfromPubKey\fP The script to produce a satisfaction for\&. 
.br
\fItxTo\fP The spending transaction\&. 
.br
\fInIn\fP The index of the input in \fRtxTo\fP referring the output being spent\&. 
.br
\fIamount\fP The value of the output being spent\&. 
.br
\fInHashType\fP Signature hash type\&. 
.br
\fIsig_data\fP Additional data provided to solve a script\&. Filled with the resulting satisfying script and whether the satisfaction is complete\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the produced script is entirely satisfying \fRfromPubKey\fP\&. 
.RE
.PP

.SS "bool SignSignature (const \fBSigningProvider\fP & provider, const \fBCTransaction\fP & txFrom, \fBCMutableTransaction\fP & txTo, unsigned int nIn, int nHashType, \fBSignatureData\fP & sig_data)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
