.TH "transaction_identifier< has_witness >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transaction_identifier< has_witness >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transaction_identifier\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtransaction_identifier\fP ()"
.br
.ti -1c
.RI "consteval \fBtransaction_identifier\fP (std::string_view hex_str)"
.br
.ti -1c
.RI "template<typename Other> bool \fBoperator==\fP (const Other &other) const"
.br
.ti -1c
.RI "template<typename Other> bool \fBoperator<\fP (const Other &other) const"
.br
.ti -1c
.RI "const \fBuint256\fP & \fBToUint256\fP () const \fBLIFETIMEBOUND\fP"
.br
.ti -1c
.RI "constexpr bool \fBIsNull\fP () const"
.br
.ti -1c
.RI "constexpr void \fBSetNull\fP ()"
.br
.ti -1c
.RI "std::string \fBGetHex\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "constexpr const std::byte * \fBdata\fP () const"
.br
.ti -1c
.RI "constexpr const std::byte * \fBbegin\fP () const"
.br
.ti -1c
.RI "constexpr const std::byte * \fBend\fP () const"
.br
.ti -1c
.RI "template<typename Stream> void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBtransaction_identifier\fP \fBFromUint256\fP (const \fBuint256\fP &id)"
.br
.ti -1c
.RI "static std::optional< \fBtransaction_identifier\fP > \fBFromHex\fP (std::string_view hex)"
.br
.ti -1c
.RI "static constexpr auto \fBsize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool has_witness>
.br
class transaction_identifier< has_witness >"\fBtransaction_identifier\fP represents the two canonical transaction identifier types (txid, wtxid)\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<bool has_witness> \fBtransaction_identifier\fP ()\fR [inline]\fP"

.SS "template<bool has_witness> \fBtransaction_identifier\fP (std::string_view hex_str)\fR [inline]\fP, \fR [explicit]\fP, \fR [consteval]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<bool has_witness> const std::byte * begin () const\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<bool has_witness> const std::byte * data () const\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<bool has_witness> const std::byte * end () const\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<bool has_witness> std::optional< \fBtransaction_identifier\fP > FromHex (std::string_view hex)\fR [inline]\fP, \fR [static]\fP"

.SS "template<bool has_witness> \fBtransaction_identifier\fP FromUint256 (const \fBuint256\fP & id)\fR [inline]\fP, \fR [static]\fP"

.SS "template<bool has_witness> std::string GetHex () const\fR [inline]\fP"

.SS "template<bool has_witness> bool IsNull () const\fR [inline]\fP, \fR [constexpr]\fP"
Wrapped \fR\fBuint256\fP\fP methods\&. 
.SS "template<bool has_witness> template<typename Other> bool operator< (const Other & other) const\fR [inline]\fP"

.SS "template<bool has_witness> template<typename Other> bool operator== (const Other & other) const\fR [inline]\fP"

.SS "template<bool has_witness> template<typename Stream> void Serialize (Stream & s) const\fR [inline]\fP"

.SS "template<bool has_witness> void SetNull ()\fR [inline]\fP, \fR [constexpr]\fP"

.SS "template<bool has_witness> constexpr auto size ()\fR [inline]\fP, \fR [static]\fP, \fR [constexpr]\fP"

.SS "template<bool has_witness> std::string ToString () const\fR [inline]\fP"

.SS "template<bool has_witness> const \fBuint256\fP & ToUint256 () const\fR [inline]\fP"

.SS "template<bool has_witness> template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
