.TH "src/wallet/transaction.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/transaction.h
.SH SYNOPSIS
.br
.PP
\fR#include <attributes\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/overloaded\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <wallet/types\&.h>\fP
.br
\fR#include <bitset>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <map>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <variant>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTxStateConfirmed\fP"
.br
.RI "\fBState\fP of transaction confirmed in a block\&. "
.ti -1c
.RI "struct \fBTxStateInMempool\fP"
.br
.RI "\fBState\fP of transaction added to mempool\&. "
.ti -1c
.RI "struct \fBTxStateBlockConflicted\fP"
.br
.RI "\fBState\fP of rejected transaction that conflicts with a confirmed block\&. "
.ti -1c
.RI "struct \fBTxStateInactive\fP"
.br
.ti -1c
.RI "struct \fBTxStateUnrecognized\fP"
.br
.ti -1c
.RI "struct \fBCachableAmount\fP"
.br
.ti -1c
.RI "class \fBCMerkleTx\fP"
.br
.ti -1c
.RI "class \fBCWalletTx\fP"
.br
.ti -1c
.RI "struct \fBWalletTxOrderComparator\fP"
.br
.ti -1c
.RI "class \fBWalletTXO\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinterfaces\fP"
.br
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBTxState\fP = std::variant<\fBTxStateConfirmed\fP, \fBTxStateInMempool\fP, \fBTxStateBlockConflicted\fP, \fBTxStateInactive\fP, \fBTxStateUnrecognized\fP>"
.br
.RI "All possible \fBCWalletTx\fP states\&. "
.ti -1c
.RI "using \fBSyncTxState\fP = std::variant<\fBTxStateConfirmed\fP, \fBTxStateInMempool\fP, \fBTxStateInactive\fP>"
.br
.RI "Subset of states transaction sync logic is implemented to handle\&. "
.ti -1c
.RI "typedef std::map< std::string, std::string > \fBmapValue_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP> std::string \fBTxStateString\fP (const \fBT\fP &state)"
.br
.RI "Return \fBTxState\fP or \fBSyncTxState\fP as a string for logging or debugging\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
