.TH "TransactionSerParams" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionSerParams
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transaction\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const bool \fBallow_witness\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const bool allow_witness"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
