.TH "src/test/translation_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/translation_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "consteval auto \fB_t\fP (\fButil::TranslatedLiteral\fP str)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (translation_namedparams)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "auto _t (\fButil::TranslatedLiteral\fP str)\fR [consteval]\fP"

.SS "BOOST_AUTO_TEST_CASE (translation_namedparams )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
