.TH "TransactionRecord" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionRecord
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transactionrecord\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBOther\fP, \fBGenerated\fP, \fBSendToAddress\fP, \fBSendToOther\fP, \fBRecvWithAddress\fP, \fBRecvFromOther\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionRecord\fP ()"
.br
.ti -1c
.RI "\fBTransactionRecord\fP (\fBTxid\fP _hash, qint64 _time)"
.br
.ti -1c
.RI "\fBTransactionRecord\fP (\fBTxid\fP _hash, qint64 _time, \fBType\fP _type, const std::string &_address, const \fBCAmount\fP &_debit, const \fBCAmount\fP &_credit)"
.br
.ti -1c
.RI "QString \fBgetTxHash\fP () const"
.br
.ti -1c
.RI "int \fBgetOutputIndex\fP () const"
.br
.ti -1c
.RI "void \fBupdateStatus\fP (const \fBinterfaces::WalletTxStatus\fP &wtx, const \fBuint256\fP &block_hash, int numBlocks, int64_t block_time)"
.br
.ti -1c
.RI "bool \fBstatusUpdateNeeded\fP (const \fBuint256\fP &block_hash) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBshowTransaction\fP ()"
.br
.ti -1c
.RI "static QList< \fBTransactionRecord\fP > \fBdecomposeTransaction\fP (const \fBinterfaces::WalletTx\fP &wtx)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBidx\fP"
.br
.ti -1c
.RI "\fBTransactionStatus\fP \fBstatus\fP"
.br
.in -1c
.PP
.RI "\fBImmutable transaction attributes\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBTxid\fP \fBhash\fP"
.br
.ti -1c
.RI "qint64 \fBtime\fP"
.br
.ti -1c
.RI "\fBType\fP \fBtype\fP"
.br
.ti -1c
.RI "std::string \fBaddress\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBdebit\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBcredit\fP"
.br
.in -1c
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBRecommendedNumConfirmations\fP = 6"
.br
.in -1c
.SH "Detailed Description"
.PP 
UI model for a transaction\&. A core transaction can be represented by multiple UI transactions if it has multiple outputs\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIOther \fP
.TP
\f(BIGenerated \fP
.TP
\f(BISendToAddress \fP
.TP
\f(BISendToOther \fP
.TP
\f(BIRecvWithAddress \fP
.TP
\f(BIRecvFromOther \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTransactionRecord\fP ()\fR [inline]\fP"

.SS "\fBTransactionRecord\fP (\fBTxid\fP _hash, qint64 _time)\fR [inline]\fP"

.SS "\fBTransactionRecord\fP (\fBTxid\fP _hash, qint64 _time, \fBType\fP _type, const std::string & _address, const \fBCAmount\fP & _debit, const \fBCAmount\fP & _credit)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QList< \fBTransactionRecord\fP > decomposeTransaction (const \fBinterfaces::WalletTx\fP & wtx)\fR [static]\fP"

.SS "int getOutputIndex () const"
Return the output index of the subtransaction 
.SS "QString getTxHash () const"
Return the unique identifier for this transaction (part) 
.SS "bool showTransaction ()\fR [static]\fP"
Decompose \fBCWallet\fP transaction to model transaction records\&. 
.SS "bool statusUpdateNeeded (const \fBuint256\fP & block_hash) const"
Return whether a status update is needed\&. 
.SS "void updateStatus (const \fBinterfaces::WalletTxStatus\fP & wtx, const \fBuint256\fP & block_hash, int numBlocks, int64_t block_time)"
Update status from core wallet tx\&. 
.SH "Field Documentation"
.PP 
.SS "std::string address"

.SS "\fBCAmount\fP credit"

.SS "\fBCAmount\fP debit"

.SS "\fBTxid\fP hash"

.SS "int idx"
Subtransaction index, for sort key 
.SS "const int RecommendedNumConfirmations = 6\fR [static]\fP"
Number of confirmation recommended for accepting a transaction 
.SS "\fBTransactionStatus\fP status"
\fBStatus\fP: can change with block chain update 
.SS "qint64 time"

.SS "\fBType\fP type"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
