.TH "src/leveldb/table/two_level_iterator.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/table/two_level_iterator.h
.SH SYNOPSIS
.br
.PP
\fR#include 'leveldb/iterator\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP * \fBNewTwoLevelIterator\fP (\fBIterator\fP *index_iter, \fBIterator\fP *(*block_function)(void *arg, const \fBReadOptions\fP &options, const \fBSlice\fP &index_value), void *arg, const \fBReadOptions\fP &options)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
