.TH "src/leveldb/table/two_level_iterator.cc" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/table/two_level_iterator.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'table/two_level_iterator\&.h'\fP
.br
\fR#include 'leveldb/table\&.h'\fP
.br
\fR#include 'table/block\&.h'\fP
.br
\fR#include 'table/format\&.h'\fP
.br
\fR#include 'table/iterator_wrapper\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP * \fBNewTwoLevelIterator\fP (\fBIterator\fP *index_iter, BlockFunction block_function, void *arg, const \fBReadOptions\fP &options)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
