.TH "src/consensus/tx_check.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/consensus/tx_check.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <consensus/tx_check\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBCheckTransaction\fP (const \fBCTransaction\fP &tx, \fBTxValidationState\fP &state)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool CheckTransaction (const \fBCTransaction\fP & tx, \fBTxValidationState\fP & state)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
