.TH "src/test/txgraph_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/txgraph_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <txgraph\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (txgraph_trim_zigzag)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (txgraph_trim_flower)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (txgraph_trim_huge)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (txgraph_trim_big_singletons)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (txgraph_trim_big_singletons )"

.SS "BOOST_AUTO_TEST_CASE (txgraph_trim_flower )"
The maximum cluster count used in this test\&.

.PP
The number of "top" transactions, which come from disconnected blocks\&. These are re-added to the mempool and, connecting them to the already-in-mempool transactions, we discover the resulting cluster is oversized\&.

.PP
The total number of transactions in this test\&.

.PP
Set a very large cluster size limit so that only the count limit is triggered\&.
.SS "BOOST_AUTO_TEST_CASE (txgraph_trim_huge )"
The maximum cluster count used in this test\&.

.PP
The number of "top" (from-block) chains of transactions\&.

.PP
The number of transactions per top chain\&.

.PP
The (maximum) number of dependencies per bottom transaction\&.

.PP
The number of bottom transactions that are expected to be created\&.

.PP
The total number of transactions created in this test\&.

.PP
Set a very large cluster size limit so that only the count limit is triggered\&.

.PP
Refs to all top transactions\&.

.PP
Refs to all bottom transactions\&.

.PP
Indexes into top_refs for some transaction of each component, in arbitrary order\&. Initially these are the last transactions in each chains, but as bottom transactions are added, entries will be removed when they get merged, and randomized\&.
.SS "BOOST_AUTO_TEST_CASE (txgraph_trim_zigzag )"
The maximum cluster count used in this test\&.

.PP
The number of "bottom" transactions, which are in the mempool already\&.

.PP
The number of "top" transactions, which come from disconnected blocks\&. These are re-added to the mempool and, while connecting them to the already-in-mempool transactions, we discover the resulting cluster is oversized\&.

.PP
The total number of transactions in the test\&.

.PP
Set a very large cluster size limit so that only the count limit is triggered\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
