.TH "src/txgraph.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/txgraph.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <txgraph\&.h>\fP
.br
\fR#include <cluster_linearize\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <util/bitset\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/feefrac\&.h>\fP
.br
\fR#include <util/vector\&.h>\fP
.br
\fR#include <compare>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <set>\fP
.br
\fR#include <span>\fP
.br
\fR#include <unordered_set>\fP
.br
\fR#include <utility>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBTxGraph\fP > \fBMakeTxGraph\fP (unsigned max_cluster_count, uint64_t max_cluster_size, uint64_t acceptable_iters) noexcept"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::unique_ptr< \fBTxGraph\fP > MakeTxGraph (unsigned max_cluster_count, uint64_t max_cluster_size, uint64_t acceptable_iters)\fR [noexcept]\fP"
Construct a new \fBTxGraph\fP with the specified limit on the number of transactions within a cluster, and on the sum of transaction sizes within a cluster\&. max_cluster_count cannot exceed MAX_CLUSTER_COUNT_LIMIT\&. acceptable_iters controls how many linearization optimization steps will be performed per cluster before they are considered to be of acceptable quality\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
