.TH "TxIndex" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxIndex
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <txindex\&.h>\fP
.PP
Inherits \fBBaseIndex\fP\&.
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDB\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTxIndex\fP (std::unique_ptr< \fBinterfaces::Chain\fP > chain, size_t n_cache_size, bool f_memory=false, bool f_wipe=false)"
.br
.RI "Constructs the index, which becomes available to be queried\&. "
.ti -1c
.RI "virtual \fB~TxIndex\fP () override"
.br
.ti -1c
.RI "bool \fBFindTx\fP (const \fBTxid\fP &tx_hash, \fBuint256\fP &block_hash, \fBCTransactionRef\fP &tx) const"
.br
.in -1c

Public Member Functions inherited from \fBBaseIndex\fP
.in +1c
.ti -1c
.RI "\fBBaseIndex\fP (std::unique_ptr< \fBinterfaces::Chain\fP > chain, std::string \fBname\fP)"
.br
.ti -1c
.RI "virtual \fB~BaseIndex\fP ()"
.br
.RI "Destructor interrupts sync thread if running and blocks until it exits\&. "
.ti -1c
.RI "const std::string & \fBGetName\fP () const \fBLIFETIMEBOUND\fP"
.br
.RI "Get the name of the index for display in logs\&. "
.ti -1c
.RI "bool BlockUntilSyncedToCurrentChain() const \fBLOCKS_EXCLUDED\fP(void \fBInterrupt\fP ()"
.br
.ti -1c
.RI "bool \fBInit\fP ()"
.br
.ti -1c
.RI "bool \fBStartBackgroundSync\fP ()"
.br
.RI "Starts the initial sync process on a background thread\&. "
.ti -1c
.RI "void \fBSync\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.RI "Stops the instance from staying in sync with blockchain updates\&. "
.ti -1c
.RI "\fBIndexSummary\fP \fBGetSummary\fP () const"
.br
.RI "Get a summary of the index and its state\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCustomAppend\fP (const \fBinterfaces::BlockInfo\fP &block) override"
.br
.RI "Write update index entries for a newly connected block\&. "
.ti -1c
.RI "\fBBaseIndex::DB\fP & \fBGetDB\fP () const override"
.br
.in -1c

Protected Member Functions inherited from \fBBaseIndex\fP
.in +1c
.ti -1c
.RI "void \fBBlockConnected\fP (const \fBkernel::ChainstateRole\fP &role, const std::shared_ptr< const \fBCBlock\fP > &block, const \fBCBlockIndex\fP *pindex) override"
.br
.ti -1c
.RI "void \fBChainStateFlushed\fP (const \fBkernel::ChainstateRole\fP &role, const \fBCBlockLocator\fP &locator) override"
.br
.ti -1c
.RI "virtual \fBinterfaces::Chain::NotifyOptions\fP \fBCustomOptions\fP ()"
.br
.RI "Return custom notification options for index\&. "
.ti -1c
.RI "virtual bool \fBCustomInit\fP (const std::optional< \fBinterfaces::BlockRef\fP > &block)"
.br
.RI "Initialize internal state from the database and block index\&. "
.ti -1c
.RI "virtual bool \fBCustomCommit\fP (\fBCDBBatch\fP &batch)"
.br
.ti -1c
.RI "virtual bool \fBCustomRemove\fP (const \fBinterfaces::BlockInfo\fP &block)"
.br
.RI "Rewind index by one block during a chain reorg\&. "
.ti -1c
.RI "void \fBSetBestBlockIndex\fP (const \fBCBlockIndex\fP *block)"
.br
.RI "Update the internal best block index as well as the prune lock\&. "
.in -1c

Protected Member Functions inherited from \fBCValidationInterface\fP
.in +1c
.ti -1c
.RI "\fB~CValidationInterface\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBUpdatedBlockTip\fP (const \fBCBlockIndex\fP *pindexNew, const \fBCBlockIndex\fP *pindexFork, bool fInitialDownload)"
.br
.ti -1c
.RI "virtual void \fBActiveTipChange\fP (const \fBCBlockIndex\fP &new_tip, bool is_ibd)"
.br
.ti -1c
.RI "virtual void \fBTransactionAddedToMempool\fP (const \fBNewMempoolTransactionInfo\fP &tx, uint64_t mempool_sequence)"
.br
.ti -1c
.RI "virtual void \fBTransactionRemovedFromMempool\fP (const \fBCTransactionRef\fP &tx, \fBMemPoolRemovalReason\fP reason, uint64_t mempool_sequence)"
.br
.ti -1c
.RI "virtual void \fBMempoolTransactionsRemovedForBlock\fP (const std::vector< \fBRemovedMempoolTransactionInfo\fP > &txs_removed_for_block, unsigned int nBlockHeight)"
.br
.ti -1c
.RI "virtual void \fBBlockDisconnected\fP (const std::shared_ptr< const \fBCBlock\fP > &block, const \fBCBlockIndex\fP *pindex)"
.br
.ti -1c
.RI "virtual void \fBBlockChecked\fP (const std::shared_ptr< const \fBCBlock\fP > &, const \fBBlockValidationState\fP &)"
.br
.ti -1c
.RI "virtual void \fBNewPoWValidBlock\fP (const \fBCBlockIndex\fP *pindex, const std::shared_ptr< const \fBCBlock\fP > &block)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBBaseIndex\fP
.in +1c
.ti -1c
.RI "std::unique_ptr< \fBinterfaces::Chain\fP > \fBm_chain\fP"
.br
.ti -1c
.RI "\fBChainstate\fP * \fBm_chainstate\fP {nullptr}"
.br
.ti -1c
.RI "const std::string \fBm_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTxIndex\fP is used to look up transactions included in the blockchain by hash\&. The index is written to a LevelDB database and records the filesystem location of each transaction by transaction hash\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTxIndex\fP (std::unique_ptr< \fBinterfaces::Chain\fP > chain, size_t n_cache_size, bool f_memory = \fRfalse\fP, bool f_wipe = \fRfalse\fP)\fR [explicit]\fP"

.PP
Constructs the index, which becomes available to be queried\&. 
.SS "~\fBTxIndex\fP ()\fR [override]\fP, \fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool CustomAppend (const \fBinterfaces::BlockInfo\fP & block)\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Write update index entries for a newly connected block\&. 
.PP
Reimplemented from \fBBaseIndex\fP\&.
.SS "bool FindTx (const \fBTxid\fP & tx_hash, \fBuint256\fP & block_hash, \fBCTransactionRef\fP & tx) const"
Look up a transaction by hash\&.

.PP
\fBParameters\fP
.RS 4
\fItx_hash\fP The hash of the transaction to be returned\&. 
.br
\fIblock_hash\fP The hash of the block the transaction is found in\&. 
.br
\fItx\fP The transaction itself\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if transaction is found, false otherwise 
.RE
.PP

.SS "\fBBaseIndex::DB\fP & GetDB () const\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBBaseIndex\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
