.TH "src/index/txindex.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/index/txindex.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <index/txindex\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <dbwrapper\&.h>\fP
.br
\fR#include <flatfile\&.h>\fP
.br
\fR#include <index/base\&.h>\fP
.br
\fR#include <index/disktxpos\&.h>\fP
.br
\fR#include <interfaces/chain\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <node/blockstorage\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdio>\fP
.br
\fR#include <exception>\fP
.br
\fR#include <iterator>\fP
.br
\fR#include <span>\fP
.br
\fR#include <string>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTxIndex::DB\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr uint8_t \fBDB_TXINDEX\fP {'t'}"
.br
.ti -1c
.RI "std::unique_ptr< \fBTxIndex\fP > \fBg_txindex\fP"
.br
.RI "The global transaction index, used in GetTransaction\&. May be null\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "uint8_t DB_TXINDEX {'t'}\fR [constexpr]\fP"

.SS "std::unique_ptr<\fBTxIndex\fP> g_txindex"

.PP
The global transaction index, used in GetTransaction\&. May be null\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
