.TH "src/index/txindex.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/index/txindex.h
.SH SYNOPSIS
.br
.PP
\fR#include <index/base\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <memory>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTxIndex\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinterfaces\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBTxIndex\fP > \fBg_txindex\fP"
.br
.RI "The global transaction index, used in GetTransaction\&. May be null\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::unique_ptr<\fBTxIndex\fP> g_txindex\fR [extern]\fP"

.PP
The global transaction index, used in GetTransaction\&. May be null\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
