.TH "src/test/txindex_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/txindex_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <addresstype\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <index/txindex\&.h>\fP
.br
\fR#include <interfaces/chain\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (txindex_initial_sync, \fBTestChain100Setup\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_FIXTURE_TEST_CASE (txindex_initial_sync , \fBTestChain100Setup\fP )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
