.TH "src/txmempool.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/txmempool.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <txmempool\&.h>\fP
.br
\fR#include <chain\&.h>\fP
.br
\fR#include <coins\&.h>\fP
.br
\fR#include <common/system\&.h>\fP
.br
\fR#include <consensus/consensus\&.h>\fP
.br
\fR#include <consensus/tx_verify\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br
\fR#include <policy/settings\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/feefrac\&.h>\fP
.br
\fR#include <util/moneystr\&.h>\fP
.br
\fR#include <util/overflow\&.h>\fP
.br
\fR#include <util/result\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <util/trace\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <validationinterface\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <numeric>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <ranges>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include <utility>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTRACEPOINT_SEMAPHORE\fP (mempool, added)"
.br
.ti -1c
.RI "\fBTRACEPOINT_SEMAPHORE\fP (mempool, removed)"
.br
.ti -1c
.RI "bool \fBTestLockPointValidity\fP (\fBCChain\fP &active_chain, const \fBLockPoints\fP &\fBlp\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool TestLockPointValidity (\fBCChain\fP & active_chain, const \fBLockPoints\fP & lp)"
Test whether the \fBLockPoints\fP height and time are still valid on the current chain 
.SS "TRACEPOINT_SEMAPHORE (mempool , added )"

.SS "TRACEPOINT_SEMAPHORE (mempool , removed )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
