.TH "src/test/txreconciliation_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/txreconciliation_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/txreconciliation\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (RegisterPeerTest)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (ForgetPeerTest)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (IsPeerRegisteredTest)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (ForgetPeerTest )"

.SS "BOOST_AUTO_TEST_CASE (IsPeerRegisteredTest )"

.SS "BOOST_AUTO_TEST_CASE (RegisterPeerTest )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
