.TH "src/node/txreconciliation.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/txreconciliation.h
.SH SYNOPSIS
.br
.PP
\fR#include <net\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <tuple>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTxReconciliationTracker\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBReconciliationRegisterResult\fP { \fBNOT_FOUND\fP, \fBSUCCESS\fP, \fBALREADY_REGISTERED\fP, \fBPROTOCOL_VIOLATION\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBReconciliationRegisterResult\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINOT_FOUND \fP
.TP
\f(BISUCCESS \fP
.TP
\f(BIALREADY_REGISTERED \fP
.TP
\f(BIPROTOCOL_VIOLATION \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
