.TH "src/ipc/libmultiprocess/include/mp/type-interface.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc/libmultiprocess/include/mp/type-interface.h
.SH SYNOPSIS
.br
.PP
\fR#include <mp/util\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmp\fP"
.br
.RI "Functions to serialize / deserialize common bitcoin types\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Interface, typename Impl> kj::Own< typename Interface::Server > \fBMakeProxyServer\fP (\fBInvokeContext\fP &context, std::shared_ptr< Impl > impl)"
.br
.ti -1c
.RI "template<typename Interface, typename Impl> kj::Own< typename Interface::Server > \fBCustomMakeProxyServer\fP (\fBInvokeContext\fP &context, std::shared_ptr< Impl > &&impl)"
.br
.ti -1c
.RI "template<typename Impl, typename Value, typename Output> void \fBCustomBuildField\fP (\fBTypeList\fP< std::unique_ptr< Impl > >, \fBPriority\fP< 1 >, \fBInvokeContext\fP &invoke_context, Value &&value, Output &&output, typename \fBDecay\fP< decltype(output\&.get())>::Calls *enable=nullptr)"
.br
.ti -1c
.RI "template<typename Impl, typename Value, typename Output> void \fBCustomBuildField\fP (\fBTypeList\fP< std::shared_ptr< Impl > >, \fBPriority\fP< 2 >, \fBInvokeContext\fP &invoke_context, Value &&value, Output &&output, typename \fBDecay\fP< decltype(output\&.get())>::Calls *enable=nullptr)"
.br
.ti -1c
.RI "template<typename Impl, typename Output> void \fBCustomBuildField\fP (\fBTypeList\fP< Impl & >, \fBPriority\fP< 1 >, \fBInvokeContext\fP &invoke_context, Impl &value, Output &&output, typename decltype(output\&.get())::Calls *enable=nullptr)"
.br
.ti -1c
.RI "template<typename Interface, typename Impl> std::unique_ptr< Impl > \fBMakeProxyClient\fP (\fBInvokeContext\fP &context, typename Interface::Client &&client)"
.br
.ti -1c
.RI "template<typename Interface, typename Impl> std::unique_ptr< Impl > \fBCustomMakeProxyClient\fP (\fBInvokeContext\fP &context, typename Interface::Client &&client)"
.br
.ti -1c
.RI "template<typename LocalType, typename Input, typename ReadDest> decltype(auto) \fBCustomReadField\fP (\fBTypeList\fP< std::unique_ptr< LocalType > >, \fBPriority\fP< 1 >, \fBInvokeContext\fP &invoke_context, Input &&input, ReadDest &&read_dest, typename \fBDecay\fP< decltype(input\&.get())>::Calls *enable=nullptr)"
.br
.ti -1c
.RI "template<typename LocalType, typename Input, typename ReadDest> decltype(auto) \fBCustomReadField\fP (\fBTypeList\fP< std::shared_ptr< LocalType > >, \fBPriority\fP< 1 >, \fBInvokeContext\fP &invoke_context, Input &&input, ReadDest &&read_dest, typename \fBDecay\fP< decltype(input\&.get())>::Calls *enable=nullptr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
