.TH "src/ipc/libmultiprocess/include/mp/type-char.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipc/libmultiprocess/include/mp/type-char.h
.SH SYNOPSIS
.br
.PP
\fR#include <mp/util\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmp\fP"
.br
.RI "Functions to serialize / deserialize common bitcoin types\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Output, size_t size> void \fBCustomBuildField\fP (\fBTypeList\fP< const unsigned char * >, \fBPriority\fP< 3 >, \fBInvokeContext\fP &invoke_context, const unsigned char(&value)[size], Output &&output)"
.br
.ti -1c
.RI "template<size_t size, typename Input, typename ReadDest> decltype(auto) \fBCustomReadField\fP (\fBTypeList\fP< unsigned char[size]>, \fBPriority\fP< 1 >, \fBInvokeContext\fP &invoke_context, Input &&input, ReadDest &&read_dest)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
