.TH "src/util/ui_change_type.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/ui_change_type.h
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBChangeType\fP { \fBCT_NEW\fP, \fBCT_UPDATED\fP, \fBCT_DELETED\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBChangeType\fP"
General change type (added, updated, removed)\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BICT_NEW \fP
.TP
\f(BICT_UPDATED \fP
.TP
\f(BICT_DELETED \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
