.TH "uint_error" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uint_error
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <arith_uint256\&.h>\fP
.PP
Inherits runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuint_error\fP (const std::string &str)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBuint_error\fP (const std::string & str)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
