.TH "uint256" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uint256
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <uint256\&.h>\fP
.PP
Inherits \fBbase_blob< 256 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBuint256\fP ()=default"
.br
.ti -1c
.RI "consteval \fBuint256\fP (std::string_view hex_str)"
.br
.ti -1c
.RI "constexpr \fBuint256\fP (uint8_t v)"
.br
.ti -1c
.RI "constexpr \fBuint256\fP (std::span< const unsigned char > vch)"
.br
.in -1c

Public Member Functions inherited from \fBbase_blob< 256 >\fP
.in +1c
.ti -1c
.RI "constexpr \fBbase_blob\fP ()"
.br
.ti -1c
.RI "constexpr bool \fBIsNull\fP () const"
.br
.ti -1c
.RI "constexpr void \fBSetNull\fP ()"
.br
.ti -1c
.RI "constexpr int \fBCompare\fP (const \fBbase_blob\fP &other) const"
.br
.ti -1c
.RI "constexpr const unsigned char * \fBdata\fP () const"
.br
.ti -1c
.RI "constexpr unsigned char * \fBbegin\fP ()"
.br
.ti -1c
.RI "constexpr unsigned char * \fBend\fP ()"
.br
.ti -1c
.RI "constexpr uint64_t \fBGetUint64\fP (int pos) const"
.br
.ti -1c
.RI "void \fBSerialize\fP (Stream &s) const"
.br
.ti -1c
.RI "void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.in +1c
.ti -1c
.RI "std::string \fBGetHex\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::optional< \fBuint256\fP > \fBFromHex\fP (std::string_view str)"
.br
.ti -1c
.RI "static std::optional< \fBuint256\fP > \fBFromUserHex\fP (std::string_view str)"
.br
.in -1c

Static Public Member Functions inherited from \fBbase_blob< 256 >\fP
.in +1c
.ti -1c
.RI "static constexpr unsigned int \fBsize\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBuint256\fP \fBZERO\fP"
.br
.ti -1c
.RI "static const \fBuint256\fP \fBONE\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBbase_blob< 256 >\fP
.in +1c
.ti -1c
.RI "std::array< uint8_t, \fBWIDTH\fP > \fBm_data\fP"
.br
.in -1c

Static Protected Attributes inherited from \fBbase_blob< 256 >\fP
.in +1c
.ti -1c
.RI "static constexpr int \fBWIDTH\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
256-bit opaque blob\&. 
.PP
\fBNote\fP
.RS 4
This type is called \fBuint256\fP for historical reasons only\&. It is an opaque blob of 256 bits and has no integer operations\&. Use \fBarith_uint256\fP if those are required\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBuint256\fP ()\fR [constexpr]\fP, \fR [default]\fP"

.SS "\fBuint256\fP (std::string_view hex_str)\fR [inline]\fP, \fR [explicit]\fP, \fR [consteval]\fP"

.SS "\fBuint256\fP (uint8_t v)\fR [inline]\fP, \fR [explicit]\fP, \fR [constexpr]\fP"

.SS "\fBuint256\fP (std::span< const unsigned char > vch)\fR [inline]\fP, \fR [explicit]\fP, \fR [constexpr]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::optional< \fBuint256\fP > FromHex (std::string_view str)\fR [inline]\fP, \fR [static]\fP"

.SS "std::optional< \fBuint256\fP > FromUserHex (std::string_view str)\fR [inline]\fP, \fR [static]\fP"

.SH "Field Documentation"
.PP 
.SS "const \fBuint256\fP ONE\fR [static]\fP"

.SS "const \fBuint256\fP ZERO\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
