.TH "src/test/uint256_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/uint256_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <primitives/transaction_identifier\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <iomanip>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBR1S\&.ToString\fP(), ArrayToString(\fBR1Array\fP, 20))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBR2L\&.ToString\fP(), ArrayToString(\fBR2Array\fP, 32))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBR2S\&.ToString\fP(), ArrayToString(\fBR2Array\fP, 20))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBZeroL\&.ToString\fP(), ArrayToString(\fBZeroArray\fP, 32))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBZeroS\&.ToString\fP(), ArrayToString(\fBZeroArray\fP, 20))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBOneL\&.ToString\fP(), ArrayToString(\fBOneArray\fP, 32))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBOneS\&.ToString\fP(), ArrayToString(\fBOneArray\fP, 20))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBMaxL\&.ToString\fP(), ArrayToString(\fBMaxArray\fP, 32))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBMaxS\&.ToString\fP(), ArrayToString(\fBMaxArray\fP, 20))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_NE\fP (\fBOneL\&.ToString\fP(), ArrayToString(\fBZeroArray\fP, 32))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_NE\fP (\fBOneS\&.ToString\fP(), ArrayToString(\fBZeroArray\fP, 20))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_NE\fP (\fBR1L\fP, \fBR2L\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_NE\fP (\fBR1S\fP, \fBR2S\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_NE\fP (\fBZeroL\fP, \fBOneL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_NE\fP (\fBZeroS\fP, \fBOneS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_NE\fP (\fBOneL\fP, \fBZeroL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_NE\fP (\fBOneS\fP, \fBZeroS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_NE\fP (\fBMaxL\fP, \fBZeroL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_NE\fP (\fBMaxS\fP, \fBZeroS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint256::FromHex\fP(\fBR1L\&.ToString\fP())\&.value(), \fBR1L\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint256::FromHex\fP(\fBR2L\&.ToString\fP())\&.value(), \fBR2L\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint256::FromHex\fP(\fBZeroL\&.ToString\fP())\&.value(), \fBZeroL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint256::FromHex\fP(\fBOneL\&.ToString\fP())\&.value(), \fBOneL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint256::FromHex\fP(\fBMaxL\&.ToString\fP())\&.value(), \fBMaxL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint256::FromHex\fP(\fBR1ArrayHex\fP)\&.value(), \fBR1L\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint256\fP(\fBR1L\fP), \fBR1L\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint256\fP(\fBZeroL\fP), \fBZeroL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint256\fP(\fBOneL\fP), \fBOneL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint160::FromHex\fP(\fBR1S\&.ToString\fP())\&.value(), \fBR1S\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint160::FromHex\fP(\fBR2S\&.ToString\fP())\&.value(), \fBR2S\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint160::FromHex\fP(\fBZeroS\&.ToString\fP())\&.value(), \fBZeroS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint160::FromHex\fP(\fBOneS\&.ToString\fP())\&.value(), \fBOneS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint160::FromHex\fP(\fBMaxS\&.ToString\fP())\&.value(), \fBMaxS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint160::FromHex\fP(std::string_view{\fBR1ArrayHex\fP+24, 40})\&.value(), \fBR1S\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint160\fP(\fBR1S\fP), \fBR1S\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint160\fP(\fBZeroS\fP), \fBZeroS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint160\fP(\fBOneS\fP), \fBOneS\fP)"
.br
.ti -1c
.RI "\fBfor\fP (int i=255;i >=0;\-\-i)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBZeroL\fP, \fBR1L\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBR2L\fP, \fBR1L\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBZeroL\fP, \fBOneL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBOneL\fP, \fBMaxL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBR1L\fP, \fBMaxL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBR2L\fP, \fBMaxL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBZeroS\fP, \fBR1S\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBR2S\fP, \fBR1S\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBZeroS\fP, \fBOneS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBOneS\fP, \fBMaxS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBR1S\fP, \fBMaxS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBR2S\fP, \fBMaxS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_LT\fP (\fBuint256\fP{'1000000000000000000000000000000000000000000000000000000000000000'}, \fBuint256\fP{'0000000000000000000000000000000000000000000000000000000000000001'})"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R2L\&.GetHex(), \fBR2L\&.ToString\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (OneL\&.GetHex(), \fBOneL\&.ToString\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (MaxL\&.GetHex(), \fBMaxL\&.ToString\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBTmpL\fP, \fBR1L\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint256::FromHex\fP(\fBZeroL\&.ToString\fP())\&.value(), \fBuint256\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL_COLLECTIONS\fP (R1L\&.begin(), R1L\&.end(), \fBR1Array\fP, \fBR1Array\fP+\fBuint256::size\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL_COLLECTIONS\fP (TmpL\&.begin(), TmpL\&.end(), \fBR1Array\fP, \fBR1Array\fP+\fBuint256::size\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL_COLLECTIONS\fP (R2L\&.begin(), R2L\&.end(), \fBR2Array\fP, \fBR2Array\fP+\fBuint256::size\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL_COLLECTIONS\fP (ZeroL\&.begin(), ZeroL\&.end(), \fBZeroArray\fP, \fBZeroArray\fP+\fBuint256::size\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL_COLLECTIONS\fP (OneL\&.begin(), OneL\&.end(), \fBOneArray\fP, \fBOneArray\fP+\fBuint256::size\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R1L\&.size(), sizeof(\fBR1L\fP))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (sizeof(\fBR1L\fP), 32)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R1L\&.size(), 32)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R2L\&.size(), 32)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (ZeroL\&.size(), 32)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (MaxL\&.size(), 32)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R1L\&.begin()+32, R1L\&.end())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R2L\&.begin()+32, R2L\&.end())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (OneL\&.begin()+32, OneL\&.end())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (MaxL\&.begin()+32, MaxL\&.end())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (TmpL\&.begin()+32, TmpL\&.end())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBGetSerializeSize\fP(\fBR1L\fP), 32)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBGetSerializeSize\fP(\fBZeroL\fP), 32)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBR1L\fP, \fBTmpL\fP)"
.br
.ti -1c
.RI "\fBss\fP \fBclear\fP ()"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBZeroL\fP, \fBTmpL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBMaxL\fP, \fBTmpL\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R1S\&.GetHex(), \fBR1S\&.ToString\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R2S\&.GetHex(), \fBR2S\&.ToString\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (OneS\&.GetHex(), \fBOneS\&.ToString\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (MaxS\&.GetHex(), \fBMaxS\&.ToString\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBTmpS\fP, \fBR1S\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBuint160::FromHex\fP(\fBZeroS\&.ToString\fP())\&.value(), \fBuint160\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL_COLLECTIONS\fP (R1S\&.begin(), R1S\&.end(), \fBR1Array\fP, \fBR1Array\fP+\fBuint160::size\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL_COLLECTIONS\fP (TmpS\&.begin(), TmpS\&.end(), \fBR1Array\fP, \fBR1Array\fP+\fBuint160::size\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL_COLLECTIONS\fP (R2S\&.begin(), R2S\&.end(), \fBR2Array\fP, \fBR2Array\fP+\fBuint160::size\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL_COLLECTIONS\fP (ZeroS\&.begin(), ZeroS\&.end(), \fBZeroArray\fP, \fBZeroArray\fP+\fBuint160::size\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL_COLLECTIONS\fP (OneS\&.begin(), OneS\&.end(), \fBOneArray\fP, \fBOneArray\fP+\fBuint160::size\fP())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R1S\&.size(), sizeof(\fBR1S\fP))"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (sizeof(\fBR1S\fP), 20)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R1S\&.size(), 20)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R2S\&.size(), 20)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (ZeroS\&.size(), 20)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (MaxS\&.size(), 20)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R1S\&.begin()+20, R1S\&.end())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (R2S\&.begin()+20, R2S\&.end())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (OneS\&.begin()+20, OneS\&.end())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (MaxS\&.begin()+20, MaxS\&.end())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (TmpS\&.begin()+20, TmpS\&.end())"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBGetSerializeSize\fP(\fBR1S\fP), 20)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBGetSerializeSize\fP(\fBZeroS\fP), 20)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBR1S\fP, \fBTmpS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBZeroS\fP, \fBTmpS\fP)"
.br
.ti -1c
.RI "\fBBOOST_CHECK_EQUAL\fP (\fBMaxS\fP, \fBTmpS\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP> void \fBTestFromHex\fP ()"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (from_hex)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (from_user_hex)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (check_ONE)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (FromHex_vs_uint256)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned char \fBR1Array\fP []"
.br
.ti -1c
.RI "const char \fBR1ArrayHex\fP [] = '7D1DE5EAF9B156D53208F033B5AA8122D2d2355d5e12292b121156cfdb4a529c'"
.br
.ti -1c
.RI "const \fBuint256\fP \fBR1L\fP = \fBuint256\fP(std::vector<unsigned char>(\fBR1Array\fP,\fBR1Array\fP+32))"
.br
.ti -1c
.RI "const \fBuint160\fP \fBR1S\fP = \fBuint160\fP(std::vector<unsigned char>(\fBR1Array\fP,\fBR1Array\fP+20))"
.br
.ti -1c
.RI "const unsigned char \fBR2Array\fP []"
.br
.ti -1c
.RI "const \fBuint256\fP \fBR2L\fP = \fBuint256\fP(std::vector<unsigned char>(\fBR2Array\fP,\fBR2Array\fP+32))"
.br
.ti -1c
.RI "const \fBuint160\fP \fBR2S\fP = \fBuint160\fP(std::vector<unsigned char>(\fBR2Array\fP,\fBR2Array\fP+20))"
.br
.ti -1c
.RI "const unsigned char \fBZeroArray\fP []"
.br
.ti -1c
.RI "const \fBuint256\fP \fBZeroL\fP = \fBuint256\fP(std::vector<unsigned char>(\fBZeroArray\fP,\fBZeroArray\fP+32))"
.br
.ti -1c
.RI "const \fBuint160\fP \fBZeroS\fP = \fBuint160\fP(std::vector<unsigned char>(\fBZeroArray\fP,\fBZeroArray\fP+20))"
.br
.ti -1c
.RI "const unsigned char \fBOneArray\fP []"
.br
.ti -1c
.RI "const \fBuint256\fP \fBOneL\fP = \fBuint256\fP(std::vector<unsigned char>(\fBOneArray\fP,\fBOneArray\fP+32))"
.br
.ti -1c
.RI "const \fBuint160\fP \fBOneS\fP = \fBuint160\fP(std::vector<unsigned char>(\fBOneArray\fP,\fBOneArray\fP+20))"
.br
.ti -1c
.RI "const unsigned char \fBMaxArray\fP []"
.br
.ti -1c
.RI "const \fBuint256\fP \fBMaxL\fP = \fBuint256\fP(std::vector<unsigned char>(\fBMaxArray\fP,\fBMaxArray\fP+32))"
.br
.ti -1c
.RI "const \fBuint160\fP \fBMaxS\fP = \fBuint160\fP(std::vector<unsigned char>(\fBMaxArray\fP,\fBMaxArray\fP+20))"
.br
.ti -1c
.RI "\fBuint160\fP \fBLastS\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBTmpL\fP (\fBR1L\fP) = \fBuint256::FromHex\fP(\fBR1L\&.ToString\fP())\&.value()"
.br
.ti -1c
.RI "\fBDataStream\fP \fBss\fP {}"
.br
.ti -1c
.RI "\fBuint160\fP \fBTmpS\fP (\fBR1S\fP) = \fBuint160::FromHex\fP(\fBR1S\&.ToString\fP())\&.value()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (check_ONE )"

.SS "BOOST_AUTO_TEST_CASE (from_hex )"

.SS "BOOST_AUTO_TEST_CASE (from_user_hex )"

.SS "BOOST_AUTO_TEST_CASE (FromHex_vs_uint256 )"

.SS "BOOST_CHECK_EQUAL (\fBGetSerializeSize\fP(\fBR1L\fP) , 32 )"

.SS "BOOST_CHECK_EQUAL (\fBGetSerializeSize\fP(\fBR1S\fP) , 20 )"

.SS "BOOST_CHECK_EQUAL (\fBGetSerializeSize\fP(\fBZeroL\fP) , 32 )"

.SS "BOOST_CHECK_EQUAL (\fBGetSerializeSize\fP(\fBZeroS\fP) , 20 )"

.SS "BOOST_CHECK_EQUAL (\fBMaxL\fP , \fBTmpL\fP )"

.SS "BOOST_CHECK_EQUAL (MaxL\&.begin()+ 32, MaxL\&. end())"

.SS "BOOST_CHECK_EQUAL (MaxL\&. GetHex(), MaxL\&. ToString())"

.SS "BOOST_CHECK_EQUAL (MaxL\&. size(), 32 )"

.SS "BOOST_CHECK_EQUAL (MaxL\&. ToString(), ArrayToString(\fBMaxArray\fP, 32) )"

.SS "BOOST_CHECK_EQUAL (\fBMaxS\fP , \fBTmpS\fP )"

.SS "BOOST_CHECK_EQUAL (MaxS\&.begin()+ 20, MaxS\&. end())"

.SS "BOOST_CHECK_EQUAL (MaxS\&. GetHex(), MaxS\&. ToString())"

.SS "BOOST_CHECK_EQUAL (MaxS\&. size(), 20 )"

.SS "BOOST_CHECK_EQUAL (MaxS\&. ToString(), ArrayToString(\fBMaxArray\fP, 20) )"

.SS "BOOST_CHECK_EQUAL (OneL\&.begin()+ 32, OneL\&. end())"

.SS "BOOST_CHECK_EQUAL (OneL\&. GetHex(), OneL\&. ToString())"

.SS "BOOST_CHECK_EQUAL (OneL\&. ToString(), ArrayToString(\fBOneArray\fP, 32) )"

.SS "BOOST_CHECK_EQUAL (OneS\&.begin()+ 20, OneS\&. end())"

.SS "BOOST_CHECK_EQUAL (OneS\&. GetHex(), OneS\&. ToString())"

.SS "BOOST_CHECK_EQUAL (OneS\&. ToString(), ArrayToString(\fBOneArray\fP, 20) )"

.SS "BOOST_CHECK_EQUAL (\fBR1L\fP , \fBTmpL\fP )"

.SS "BOOST_CHECK_EQUAL (R1L\&.begin()+ 32, R1L\&. end())"

.SS "BOOST_CHECK_EQUAL (R1L\&. size(), 32 )"

.SS "BOOST_CHECK_EQUAL (R1L\&. size(), sizeof(\fBR1L\fP) )"

.SS "BOOST_CHECK_EQUAL (\fBR1S\fP , \fBTmpS\fP )"

.SS "BOOST_CHECK_EQUAL (R1S\&.begin()+ 20, R1S\&. end())"

.SS "BOOST_CHECK_EQUAL (R1S\&. GetHex(), R1S\&. ToString())"

.SS "BOOST_CHECK_EQUAL (R1S\&. size(), 20 )"

.SS "BOOST_CHECK_EQUAL (R1S\&. size(), sizeof(\fBR1S\fP) )"

.SS "BOOST_CHECK_EQUAL (R1S\&. ToString(), ArrayToString(\fBR1Array\fP, 20) )"

.SS "BOOST_CHECK_EQUAL (R2L\&.begin()+ 32, R2L\&. end())"

.SS "BOOST_CHECK_EQUAL (R2L\&. GetHex(), R2L\&. ToString())"

.SS "BOOST_CHECK_EQUAL (R2L\&. size(), 32 )"

.SS "BOOST_CHECK_EQUAL (R2L\&. ToString(), ArrayToString(\fBR2Array\fP, 32) )"

.SS "BOOST_CHECK_EQUAL (R2S\&.begin()+ 20, R2S\&. end())"

.SS "BOOST_CHECK_EQUAL (R2S\&. GetHex(), R2S\&. ToString())"

.SS "BOOST_CHECK_EQUAL (R2S\&. size(), 20 )"

.SS "BOOST_CHECK_EQUAL (R2S\&. ToString(), ArrayToString(\fBR2Array\fP, 20) )"

.SS "BOOST_CHECK_EQUAL (sizeof(\fBR1L\fP) , 32 )"

.SS "BOOST_CHECK_EQUAL (sizeof(\fBR1S\fP) , 20 )"

.SS "BOOST_CHECK_EQUAL (\fBTmpL\fP , \fBR1L\fP )"

.SS "BOOST_CHECK_EQUAL (TmpL\&.begin()+ 32, TmpL\&. end())"

.SS "BOOST_CHECK_EQUAL (\fBTmpS\fP , \fBR1S\fP )"

.SS "BOOST_CHECK_EQUAL (TmpS\&.begin()+ 20, TmpS\&. end())"

.SS "BOOST_CHECK_EQUAL (\fBuint160\fP(\fBOneS\fP) , \fBOneS\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint160\fP(\fBR1S\fP) , \fBR1S\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint160\fP(\fBZeroS\fP) , \fBZeroS\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint160::FromHex\fP(\fBMaxS\&.ToString\fP())\&.value() , \fBMaxS\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint160::FromHex\fP(\fBOneS\&.ToString\fP())\&.value() , \fBOneS\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint160::FromHex\fP(\fBR1S\&.ToString\fP())\&.value() , \fBR1S\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint160::FromHex\fP(\fBR2S\&.ToString\fP())\&.value() , \fBR2S\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint160::FromHex\fP(std::string_view{\fBR1ArrayHex\fP+24, 40})\&.value() , \fBR1S\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint160::FromHex\fP(\fBZeroS\&.ToString\fP())\&.value() , \fBuint160\fP() )"

.SS "BOOST_CHECK_EQUAL (\fBuint160::FromHex\fP(\fBZeroS\&.ToString\fP())\&.value() , \fBZeroS\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint256\fP(\fBOneL\fP) , \fBOneL\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint256\fP(\fBR1L\fP) , \fBR1L\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint256\fP(\fBZeroL\fP) , \fBZeroL\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint256::FromHex\fP(\fBMaxL\&.ToString\fP())\&.value() , \fBMaxL\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint256::FromHex\fP(\fBOneL\&.ToString\fP())\&.value() , \fBOneL\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint256::FromHex\fP(\fBR1ArrayHex\fP)\&.value() , \fBR1L\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint256::FromHex\fP(\fBR1L\&.ToString\fP())\&.value() , \fBR1L\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint256::FromHex\fP(\fBR2L\&.ToString\fP())\&.value() , \fBR2L\fP )"

.SS "BOOST_CHECK_EQUAL (\fBuint256::FromHex\fP(\fBZeroL\&.ToString\fP())\&.value() , \fBuint256\fP() )"

.SS "BOOST_CHECK_EQUAL (\fBuint256::FromHex\fP(\fBZeroL\&.ToString\fP())\&.value() , \fBZeroL\fP )"

.SS "BOOST_CHECK_EQUAL (\fBZeroL\fP , \fBTmpL\fP )"

.SS "BOOST_CHECK_EQUAL (ZeroL\&. size(), 32 )"

.SS "BOOST_CHECK_EQUAL (ZeroL\&. ToString(), ArrayToString(\fBZeroArray\fP, 32) )"

.SS "BOOST_CHECK_EQUAL (\fBZeroS\fP , \fBTmpS\fP )"

.SS "BOOST_CHECK_EQUAL (ZeroS\&. size(), 20 )"

.SS "BOOST_CHECK_EQUAL (ZeroS\&. ToString(), ArrayToString(\fBZeroArray\fP, 20) )"

.SS "BOOST_CHECK_EQUAL_COLLECTIONS (OneL\&. begin(), OneL\&. end(), \fBOneArray\fP , \fBOneArray\fP+ uint256::size())"

.SS "BOOST_CHECK_EQUAL_COLLECTIONS (OneS\&. begin(), OneS\&. end(), \fBOneArray\fP , \fBOneArray\fP+ uint160::size())"

.SS "BOOST_CHECK_EQUAL_COLLECTIONS (R1L\&. begin(), R1L\&. end(), \fBR1Array\fP , \fBR1Array\fP+ uint256::size())"

.SS "BOOST_CHECK_EQUAL_COLLECTIONS (R1S\&. begin(), R1S\&. end(), \fBR1Array\fP , \fBR1Array\fP+ uint160::size())"

.SS "BOOST_CHECK_EQUAL_COLLECTIONS (R2L\&. begin(), R2L\&. end(), \fBR2Array\fP , \fBR2Array\fP+ uint256::size())"

.SS "BOOST_CHECK_EQUAL_COLLECTIONS (R2S\&. begin(), R2S\&. end(), \fBR2Array\fP , \fBR2Array\fP+ uint160::size())"

.SS "BOOST_CHECK_EQUAL_COLLECTIONS (TmpL\&. begin(), TmpL\&. end(), \fBR1Array\fP , \fBR1Array\fP+ uint256::size())"

.SS "BOOST_CHECK_EQUAL_COLLECTIONS (TmpS\&. begin(), TmpS\&. end(), \fBR1Array\fP , \fBR1Array\fP+ uint160::size())"

.SS "BOOST_CHECK_EQUAL_COLLECTIONS (ZeroL\&. begin(), ZeroL\&. end(), \fBZeroArray\fP , \fBZeroArray\fP+ uint256::size())"

.SS "BOOST_CHECK_EQUAL_COLLECTIONS (ZeroS\&. begin(), ZeroS\&. end(), \fBZeroArray\fP , \fBZeroArray\fP+ uint160::size())"

.SS "BOOST_CHECK_LT (\fBOneL\fP , \fBMaxL\fP )"

.SS "BOOST_CHECK_LT (\fBOneS\fP , \fBMaxS\fP )"

.SS "BOOST_CHECK_LT (\fBR1L\fP , \fBMaxL\fP )"

.SS "BOOST_CHECK_LT (\fBR1S\fP , \fBMaxS\fP )"

.SS "BOOST_CHECK_LT (\fBR2L\fP , \fBMaxL\fP )"

.SS "BOOST_CHECK_LT (\fBR2L\fP , \fBR1L\fP )"

.SS "BOOST_CHECK_LT (\fBR2S\fP , \fBMaxS\fP )"

.SS "BOOST_CHECK_LT (\fBR2S\fP , \fBR1S\fP )"

.SS "BOOST_CHECK_LT (\fBuint256\fP{'1000000000000000000000000000000000000000000000000000000000000000'} , \fBuint256\fP{'0000000000000000000000000000000000000000000000000000000000000001'} )"

.SS "BOOST_CHECK_LT (\fBZeroL\fP , \fBOneL\fP )"

.SS "BOOST_CHECK_LT (\fBZeroL\fP , \fBR1L\fP )"

.SS "BOOST_CHECK_LT (\fBZeroS\fP , \fBOneS\fP )"

.SS "BOOST_CHECK_LT (\fBZeroS\fP , \fBR1S\fP )"

.SS "BOOST_CHECK_NE (\fBMaxL\fP , \fBZeroL\fP )"

.SS "BOOST_CHECK_NE (\fBMaxS\fP , \fBZeroS\fP )"

.SS "BOOST_CHECK_NE (\fBOneL\fP , \fBZeroL\fP )"

.SS "BOOST_CHECK_NE (OneL\&. ToString(), ArrayToString(\fBZeroArray\fP, 32) )"

.SS "BOOST_CHECK_NE (\fBOneS\fP , \fBZeroS\fP )"

.SS "BOOST_CHECK_NE (OneS\&. ToString(), ArrayToString(\fBZeroArray\fP, 20) )"

.SS "BOOST_CHECK_NE (\fBR1L\fP , \fBR2L\fP )"

.SS "BOOST_CHECK_NE (\fBR1S\fP , \fBR2S\fP )"

.SS "BOOST_CHECK_NE (\fBZeroL\fP , \fBOneL\fP )"

.SS "BOOST_CHECK_NE (\fBZeroS\fP , \fBOneS\fP )"

.SS "\fBss\fP clear ()"

.SS "for (int i = \fR255; i >= 0; \-\-i\fP)"

.SS "template<typename \fBT\fP> void TestFromHex ()"
Implemented as a templated function so it can be reused by other classes that have a FromHex() method that wraps base_blob::FromHex(), such as \fBtransaction_identifier::FromHex()\fP\&. 
.SH "Variable Documentation"
.PP 
.SS "\fBuint160\fP LastS"

.SS "const unsigned char MaxArray[]"
\fBInitial value:\fP
.nf
=
    "\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff"
    "\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff"
.PP
.fi

.SS "const \fBuint256\fP MaxL = \fBuint256\fP(std::vector<unsigned char>(\fBMaxArray\fP,\fBMaxArray\fP+32))"

.SS "const \fBuint160\fP MaxS = \fBuint160\fP(std::vector<unsigned char>(\fBMaxArray\fP,\fBMaxArray\fP+20))"

.SS "const unsigned char OneArray[]"
\fBInitial value:\fP
.nf
=
    "\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00"
    "\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00"
.PP
.fi

.SS "const \fBuint256\fP OneL = \fBuint256\fP(std::vector<unsigned char>(\fBOneArray\fP,\fBOneArray\fP+32))"

.SS "const \fBuint160\fP OneS = \fBuint160\fP(std::vector<unsigned char>(\fBOneArray\fP,\fBOneArray\fP+20))"

.SS "const unsigned char R1Array[]"
\fBInitial value:\fP
.nf
=
    "\\x9c\\x52\\x4a\\xdb\\xcf\\x56\\x11\\x12\\x2b\\x29\\x12\\x5e\\x5d\\x35\\xd2\\xd2"
    "\\x22\\x81\\xaa\\xb5\\x33\\xf0\\x08\\x32\\xd5\\x56\\xb1\\xf9\\xea\\xe5\\x1d\\x7d"
.PP
.fi

.SS "const char R1ArrayHex[] = '7D1DE5EAF9B156D53208F033B5AA8122D2d2355d5e12292b121156cfdb4a529c'"

.SS "const \fBuint256\fP R1L = \fBuint256\fP(std::vector<unsigned char>(\fBR1Array\fP,\fBR1Array\fP+32))"

.SS "const \fBuint160\fP R1S = \fBuint160\fP(std::vector<unsigned char>(\fBR1Array\fP,\fBR1Array\fP+20))"

.SS "const unsigned char R2Array[]"
\fBInitial value:\fP
.nf
=
    "\\x70\\x32\\x1d\\x7c\\x47\\xa5\\x6b\\x40\\x26\\x7e\\x0a\\xc3\\xa6\\x9c\\xb6\\xbf"
    "\\x13\\x30\\x47\\xa3\\x19\\x2d\\xda\\x71\\x49\\x13\\x72\\xf0\\xb4\\xca\\x81\\xd7"
.PP
.fi

.SS "const \fBuint256\fP R2L = \fBuint256\fP(std::vector<unsigned char>(\fBR2Array\fP,\fBR2Array\fP+32))"

.SS "const \fBuint160\fP R2S = \fBuint160\fP(std::vector<unsigned char>(\fBR2Array\fP,\fBR2Array\fP+20))"

.SS "ss<< \fBMaxS\fP \fBBOOST_CHECK_EQUAL\fP(ss\&.str(), std::string(\fBMaxArray\fP, \fBMaxArray\fP+20)) ss > \fBTmpS\fP {}"

.SS "\fBss\fP<< \fBMaxL\fP; \fBBOOST_CHECK_EQUAL\fP(ss\&.str(), std::string(\fBMaxArray\fP,\fBMaxArray\fP+32)); \fBss\fP > TmpL (\fBR1L\fP ) = \fBuint256::FromHex\fP(\fBR1L\&.ToString\fP())\&.value()"

.SS "\fBss\fP<< \fBMaxS\fP; \fBBOOST_CHECK_EQUAL\fP(ss\&.str(), std::string(\fBMaxArray\fP,\fBMaxArray\fP+20)); \fBss\fP > TmpS (\fBR1S\fP ) = \fBuint160::FromHex\fP(\fBR1S\&.ToString\fP())\&.value()"

.SS "const unsigned char ZeroArray[]"
\fBInitial value:\fP
.nf
=
    "\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00"
    "\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00"
.PP
.fi

.SS "const \fBuint256\fP ZeroL = \fBuint256\fP(std::vector<unsigned char>(\fBZeroArray\fP,\fBZeroArray\fP+32))"

.SS "const \fBuint160\fP ZeroS = \fBuint160\fP(std::vector<unsigned char>(\fBZeroArray\fP,\fBZeroArray\fP+20))"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
