.TH "src/undo.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/undo.h
.SH SYNOPSIS
.br
.PP
\fR#include <coins\&.h>\fP
.br
\fR#include <compressor\&.h>\fP
.br
\fR#include <consensus/consensus\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <serialize\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTxInUndoFormatter\fP"
.br
.ti -1c
.RI "class \fBCTxUndo\fP"
.br
.ti -1c
.RI "class \fBCBlockUndo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
