.TH "UniqueCheck" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniqueCheck
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniqueCheck\fP (size_t check_id_in)"
.br
.ti -1c
.RI "std::optional< int > \fBoperator()\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::unordered_multiset< size_t > results \fBGUARDED_BY\fP (\fBm\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBcheck_id\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBMutex\fP \fBm\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBUniqueCheck\fP (size_t check_id_in)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::unordered_multiset< size_t > results GUARDED_BY (\fBm\fP )\fR [static]\fP"

.SS "std::optional< int > operator() ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "size_t check_id"

.SS "\fBMutex\fP m\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
