.TH "UniqueLock< MutexType >::reverse_lock" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniqueLock< MutexType >::reverse_lock
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sync\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBreverse_lock\fP (\fBUniqueLock\fP &_lock, const MutexType &mutex, const char *_guardname, const char *_file, int _line) \fBUNLOCK_FUNCTION\fP(mutex)"
.br
.ti -1c
.RI "\fB~reverse_lock\fP () \fBUNLOCK_FUNCTION\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MutexType>
.br
class UniqueLock< MutexType >::reverse_lock"An RAII-style reverse lock\&. Unlocks on construction and locks on destruction\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename MutexType> reverse_lock (\fBUniqueLock\fP & _lock, const MutexType & mutex, const char * _guardname, const char * _file, int _line)\fR [inline]\fP, \fR [explicit]\fP"

.SS "template<typename MutexType> ~\fBreverse_lock\fP ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
