.TH "src/secp256k1/src/unit_test.c" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/unit_test.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include 'unit_test\&.h'\fP
.br
\fR#include 'testrand\&.h'\fP
.br
\fR#include 'tests_common\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBArgMap\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNUSED\fP(x)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int(* \fBArgHandler\fP) (const char *key, const char *value, struct \fBtf_framework\fP *tf)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBCOUNT\fP = 16"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UNUSED( x)"
\fBValue:\fP
.nf
(void)(x)
.PP
.fi

.SH "Typedef Documentation"
.PP 
.SS "typedef int(* ArgHandler) (const char *key, const char *value, struct \fBtf_framework\fP *tf)"

.SH "Variable Documentation"
.PP 
.SS "int COUNT = 16"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
