.TH "src/univalue/test/unitester.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/univalue/test/unitester.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <univalue\&.h>\fP
.br
\fR#include <univalue/test/fail1\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail10\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail11\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail12\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail13\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail14\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail15\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail16\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail17\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail18\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail19\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail2\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail20\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail21\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail22\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail23\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail24\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail25\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail26\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail27\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail28\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail29\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail3\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail30\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail31\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail32\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail33\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail34\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail35\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail36\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail37\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail38\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail39\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail4\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail40\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail41\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail42\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail44\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail45\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail5\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail6\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail7\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail8\&.json\&.h>\fP
.br
\fR#include <univalue/test/fail9\&.json\&.h>\fP
.br
\fR#include <univalue/test/pass1\&.json\&.h>\fP
.br
\fR#include <univalue/test/pass2\&.json\&.h>\fP
.br
\fR#include <univalue/test/pass3\&.json\&.h>\fP
.br
\fR#include <univalue/test/pass4\&.json\&.h>\fP
.br
\fR#include <univalue/test/round1\&.json\&.h>\fP
.br
\fR#include <univalue/test/round2\&.json\&.h>\fP
.br
\fR#include <univalue/test/round3\&.json\&.h>\fP
.br
\fR#include <univalue/test/round4\&.json\&.h>\fP
.br
\fR#include <univalue/test/round5\&.json\&.h>\fP
.br
\fR#include <univalue/test/round6\&.json\&.h>\fP
.br
\fR#include <univalue/test/round7\&.json\&.h>\fP
.br
\fR#include <array>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdio>\fP
.br
\fR#include <string>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTEST_FILE\fP(\fBname\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBunescape_unicode_test\fP ()"
.br
.ti -1c
.RI "void \fBno_nul_test\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr std::array \fBtests\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TEST_FILE( \fBname\fP)"
\fBValue:\fP
.nf
{#name, json_tests::name}
.PP
.fi

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SS "void no_nul_test ()"

.SS "void unescape_unicode_test ()"

.SH "Variable Documentation"
.PP 
.SS "std::array tests\fR [inline]\fP, \fR [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
