.TH "src/secp256k1/src/unit_test.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/secp256k1/src/unit_test.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtf_test_entry\fP"
.br
.ti -1c
.RI "struct \fBtf_test_module\fP"
.br
.ti -1c
.RI "struct \fBtf_targets\fP"
.br
.ti -1c
.RI "struct \fBtf_args\fP"
.br
.ti -1c
.RI "struct \fBtf_framework\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_ARGS\fP   150"
.br
.ti -1c
.RI "#define \fBMAX_SUBPROCESSES\fP   16"
.br
.ti -1c
.RI "#define \fBCASE\fP(\fBname\fP)"
.br
.ti -1c
.RI "#define \fBCASE1\fP(\fBname\fP)"
.br
.ti -1c
.RI "#define \fBMAKE_TEST_MODULE\fP(\fBname\fP)"
.br
.ti -1c
.RI "#define \fBREPEAT_TEST\fP(fn)"
.br
.ti -1c
.RI "#define \fBREPEAT_TEST_MULT\fP(fn,  multiplier)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBtest_fn\fP) (void)"
.br
.ti -1c
.RI "typedef int(* \fBsetup_ctx_fn\fP) (void)"
.br
.ti -1c
.RI "typedef int(* \fBteardown_fn\fP) (void)"
.br
.ti -1c
.RI "typedef void(* \fBrun_test_fn\fP) (const struct \fBtf_test_entry\fP *)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CASE( \fBname\fP)"
\fBValue:\fP
.nf
{ #name, run_##name }
.PP
.fi

.SS "#define CASE1( \fBname\fP)"
\fBValue:\fP
.nf
{ #name, name }
.PP
.fi

.SS "#define MAKE_TEST_MODULE( \fBname\fP)"
\fBValue:\fP
.nf
    { \\
    #name, \\
    tests_##name, \\
    sizeof(tests_##name) / sizeof(tests_##name[0]) \\
}
.PP
.fi

.SS "#define MAX_ARGS   150"

.SS "#define MAX_SUBPROCESSES   16"

.SS "#define REPEAT_TEST( fn)"
\fBValue:\fP
.nf
REPEAT_TEST_MULT(fn, 1)
.PP
.fi

.SS "#define REPEAT_TEST_MULT( fn,  multiplier)"
\fBValue:\fP
.nf
    static void fn(void) {                          \\
        int i;                                      \\
        int repeat = COUNT * (multiplier);          \\
        for (i = 0; i < repeat; i++)                \\
            fn##_internal();                        \\
    }
.PP
.fi

.SH "Typedef Documentation"
.PP 
.SS "typedef void(* run_test_fn) (const struct \fBtf_test_entry\fP *)"

.SS "typedef int(* setup_ctx_fn) (void)"

.SS "typedef int(* teardown_fn) (void)"

.SS "typedef void(* test_fn) (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
