.TH "UniValue" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniValue
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <univalue\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBtype_error\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBVType\fP { \fBVNULL\fP, \fBVOBJ\fP, \fBVARR\fP, \fBVSTR\fP, \fBVNUM\fP, \fBVBOOL\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniValue\fP ()"
.br
.ti -1c
.RI "\fBUniValue\fP (\fBUniValue::VType\fP \fBtype\fP, std::string str={})"
.br
.ti -1c
.RI "template<typename Ref, typename \fBT\fP = std::remove_cv_t<std::remove_reference_t<Ref>>, std::enable_if_t< std::is_floating_point_v< \fBT\fP >||std::is_same_v< bool, \fBT\fP >||std::is_signed_v< \fBT\fP >||std::is_unsigned_v< \fBT\fP >||std::is_constructible_v< std::string, \fBT\fP >, bool > = true> \fBUniValue\fP (Ref &&val)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBsetNull\fP ()"
.br
.ti -1c
.RI "void \fBsetBool\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetNumStr\fP (std::string str)"
.br
.ti -1c
.RI "void \fBsetInt\fP (uint64_t val)"
.br
.ti -1c
.RI "void \fBsetInt\fP (int64_t val)"
.br
.ti -1c
.RI "void \fBsetInt\fP (int val_)"
.br
.ti -1c
.RI "void \fBsetFloat\fP (double val)"
.br
.ti -1c
.RI "void \fBsetStr\fP (std::string str)"
.br
.ti -1c
.RI "void \fBsetArray\fP ()"
.br
.ti -1c
.RI "void \fBsetObject\fP ()"
.br
.ti -1c
.RI "enum \fBVType\fP \fBgetType\fP () const"
.br
.ti -1c
.RI "const std::string & \fBgetValStr\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBreserve\fP (size_t new_cap)"
.br
.ti -1c
.RI "void \fBgetObjMap\fP (std::map< std::string, \fBUniValue\fP > &kv) const"
.br
.ti -1c
.RI "bool \fBcheckObject\fP (const std::map< std::string, \fBUniValue::VType\fP > &memberTypes) const"
.br
.ti -1c
.RI "const \fBUniValue\fP & \fBoperator[]\fP (const std::string &key) const"
.br
.ti -1c
.RI "const \fBUniValue\fP & \fBoperator[]\fP (size_t index) const"
.br
.ti -1c
.RI "bool \fBexists\fP (const std::string &key) const"
.br
.ti -1c
.RI "bool \fBisNull\fP () const"
.br
.ti -1c
.RI "bool \fBisTrue\fP () const"
.br
.ti -1c
.RI "bool \fBisFalse\fP () const"
.br
.ti -1c
.RI "bool \fBisBool\fP () const"
.br
.ti -1c
.RI "bool \fBisStr\fP () const"
.br
.ti -1c
.RI "bool \fBisNum\fP () const"
.br
.ti -1c
.RI "bool \fBisArray\fP () const"
.br
.ti -1c
.RI "bool \fBisObject\fP () const"
.br
.ti -1c
.RI "void \fBpush_back\fP (\fBUniValue\fP val)"
.br
.ti -1c
.RI "void \fBpush_backV\fP (const std::vector< \fBUniValue\fP > &vec)"
.br
.ti -1c
.RI "template<class It> void \fBpush_backV\fP (It first, It last)"
.br
.ti -1c
.RI "void \fBpushKVEnd\fP (std::string key, \fBUniValue\fP val)"
.br
.ti -1c
.RI "void \fBpushKV\fP (std::string key, \fBUniValue\fP val)"
.br
.ti -1c
.RI "void \fBpushKVs\fP (\fBUniValue\fP obj)"
.br
.ti -1c
.RI "std::string \fBwrite\fP (unsigned int prettyIndent=0, unsigned int indentLevel=0) const"
.br
.ti -1c
.RI "bool \fBread\fP (std::string_view raw)"
.br
.ti -1c
.RI "const std::vector< std::string > & \fBgetKeys\fP () const"
.br
.ti -1c
.RI "const std::vector< \fBUniValue\fP > & \fBgetValues\fP () const"
.br
.ti -1c
.RI "template<typename Int> Int \fBgetInt\fP () const"
.br
.ti -1c
.RI "bool \fBget_bool\fP () const"
.br
.ti -1c
.RI "const std::string & \fBget_str\fP () const"
.br
.ti -1c
.RI "double \fBget_real\fP () const"
.br
.ti -1c
.RI "const \fBUniValue\fP & \fBget_obj\fP () const"
.br
.ti -1c
.RI "const \fBUniValue\fP & \fBget_array\fP () const"
.br
.ti -1c
.RI "enum \fBVType\fP \fBtype\fP () const"
.br
.ti -1c
.RI "const \fBUniValue\fP & \fBfind_value\fP (std::string_view key) const"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBVType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIVNULL \fP
.TP
\f(BIVOBJ \fP
.TP
\f(BIVARR \fP
.TP
\f(BIVSTR \fP
.TP
\f(BIVNUM \fP
.TP
\f(BIVBOOL \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBUniValue\fP ()\fR [inline]\fP"

.SS "\fBUniValue\fP (\fBUniValue::VType\fP type, std::string str = \fR{}\fP)\fR [inline]\fP"

.SS "template<typename Ref, typename \fBT\fP = std::remove_cv_t<std::remove_reference_t<Ref>>, std::enable_if_t< std::is_floating_point_v< \fBT\fP >||std::is_same_v< bool, \fBT\fP >||std::is_signed_v< \fBT\fP >||std::is_unsigned_v< \fBT\fP >||std::is_constructible_v< std::string, \fBT\fP >, bool > = true> \fBUniValue\fP (Ref && val)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool checkObject (const std::map< std::string, \fBUniValue::VType\fP > & memberTypes) const"

.SS "void clear ()"

.SS "bool empty () const\fR [inline]\fP"

.SS "bool exists (const std::string & key) const\fR [inline]\fP"

.SS "const \fBUniValue\fP & find_value (std::string_view key) const"

.SS "const \fBUniValue\fP & get_array () const"

.SS "bool get_bool () const"

.SS "const \fBUniValue\fP & get_obj () const"

.SS "double get_real () const"

.SS "const std::string & get_str () const"

.SS "template<typename Int> Int getInt () const"

.SS "const std::vector< std::string > & getKeys () const"

.SS "void getObjMap (std::map< std::string, \fBUniValue\fP > & kv) const"

.SS "enum \fBVType\fP getType () const\fR [inline]\fP"

.SS "const std::string & getValStr () const\fR [inline]\fP"

.SS "const std::vector< \fBUniValue\fP > & getValues () const"

.SS "bool isArray () const\fR [inline]\fP"

.SS "bool isBool () const\fR [inline]\fP"

.SS "bool isFalse () const\fR [inline]\fP"

.SS "bool isNull () const\fR [inline]\fP"

.SS "bool isNum () const\fR [inline]\fP"

.SS "bool isObject () const\fR [inline]\fP"

.SS "bool isStr () const\fR [inline]\fP"

.SS "bool isTrue () const\fR [inline]\fP"

.SS "const \fBUniValue\fP & operator[] (const std::string & key) const"

.SS "const \fBUniValue\fP & operator[] (size_t index) const"

.SS "void push_back (\fBUniValue\fP val)"

.SS "void push_backV (const std::vector< \fBUniValue\fP > & vec)"

.SS "template<class It> void push_backV (It first, It last)"

.SS "void pushKV (std::string key, \fBUniValue\fP val)"

.SS "void pushKVEnd (std::string key, \fBUniValue\fP val)"

.SS "void pushKVs (\fBUniValue\fP obj)"

.SS "bool read (std::string_view raw)"

.SS "void reserve (size_t new_cap)"

.SS "void setArray ()"

.SS "void setBool (bool val)"

.SS "void setFloat (double val)"

.SS "void setInt (int val_)\fR [inline]\fP"

.SS "void setInt (int64_t val)"

.SS "void setInt (uint64_t val)"

.SS "void setNull ()"

.SS "void setNumStr (std::string str)"

.SS "void setObject ()"

.SS "void setStr (std::string str)"

.SS "size_t size () const\fR [inline]\fP"

.SS "enum \fBVType\fP type () const\fR [inline]\fP"

.SS "std::string write (unsigned int prettyIndent = \fR0\fP, unsigned int indentLevel = \fR0\fP) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
