.TH "src/univalue/lib/univalue_read.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/univalue/lib/univalue_read.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <univalue\&.h>\fP
.br
\fR#include <univalue_utffilter\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdio>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include <vector>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBexpect\fP(bit)"
.br
.ti -1c
.RI "#define \fBsetExpect\fP(bit)"
.br
.ti -1c
.RI "#define \fBclearExpect\fP(bit)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBexpect_bits\fP : unsigned { \fBEXP_OBJ_NAME\fP = (1U << 0), \fBEXP_COLON\fP = (1U << 1), \fBEXP_ARR_VALUE\fP = (1U << 2), \fBEXP_VALUE\fP = (1U << 3), \fBEXP_NOT_VALUE\fP = (1U << 4) }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "enum \fBjtokentype\fP \fBgetJsonToken\fP (std::string &tokenVal, unsigned int &consumed, const char *raw, const char *end)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define clearExpect( bit)"
\fBValue:\fP
.nf
(expectMask &= ~EXP_##bit)
.PP
.fi

.SS "#define expect( bit)"
\fBValue:\fP
.nf
(expectMask & (EXP_##bit))
.PP
.fi

.SS "#define setExpect( bit)"
\fBValue:\fP
.nf
(expectMask |= EXP_##bit)
.PP
.fi

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBexpect_bits\fP : unsigned"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIEXP_OBJ_NAME \fP
.TP
\f(BIEXP_COLON \fP
.TP
\f(BIEXP_ARR_VALUE \fP
.TP
\f(BIEXP_VALUE \fP
.TP
\f(BIEXP_NOT_VALUE \fP
.SH "Function Documentation"
.PP 
.SS "enum \fBjtokentype\fP getJsonToken (std::string & tokenVal, unsigned int & consumed, const char * raw, const char * end)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
