.TH "UniValueType" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniValueType
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniValueType\fP (\fBUniValue::VType\fP _type)"
.br
.ti -1c
.RI "\fBUniValueType\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBtypeAny\fP"
.br
.ti -1c
.RI "\fBUniValue::VType\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWrapper\fP for \fBUniValue::VType\fP, which includes typeAny: Used to denote don't care type\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBUniValueType\fP (\fBUniValue::VType\fP _type)\fR [inline]\fP"

.SS "\fBUniValueType\fP ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBUniValue::VType\fP type"

.SS "bool typeAny"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
