.TH "src/qt/test/uritests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/test/uritests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/test/uritests\&.h>\fP
.br
\fR#include <qt/guiutil\&.h>\fP
.br
\fR#include <qt/walletmodel\&.h>\fP
.br
\fR#include <QUrl>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
