.TH "TranslatedLiteral" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TranslatedLiteral \- Compile-time literal string that can be translated with an optional translation function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <translation\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "consteval \fBTranslatedLiteral\fP (const char *str, const \fBTranslateFn\fP *fn=&\fBG_TRANSLATION_FUN\fP)"
.br
.ti -1c
.RI "\fBoperator std::string\fP () const"
.br
.ti -1c
.RI "\fBoperator bilingual_str\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char *const \fBoriginal\fP"
.br
.ti -1c
.RI "const \fBTranslateFn\fP * \fBtranslate_fn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Compile-time literal string that can be translated with an optional translation function\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TranslatedLiteral (const char * str, const \fBTranslateFn\fP * fn = \fR&\fBG_TRANSLATION_FUN\fP\fP)\fR [inline]\fP, \fR [consteval]\fP"

.SH "Member Function Documentation"
.PP 
.SS "operator \fBbilingual_str\fP () const\fR [inline]\fP"

.SS "operator std::string () const\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "const char* const original"

.SS "const \fBTranslateFn\fP* translate_fn"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
