.TH "src/test/util_trace_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/util_trace_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <util/trace\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTRACEPOINT_SEMAPHORE\fP (test, zero_args)"
.br
.ti -1c
.RI "\fBTRACEPOINT_SEMAPHORE\fP (test, one_arg)"
.br
.ti -1c
.RI "\fBTRACEPOINT_SEMAPHORE\fP (test, six_args)"
.br
.ti -1c
.RI "\fBTRACEPOINT_SEMAPHORE\fP (test, twelve_args)"
.br
.ti -1c
.RI "\fBTRACEPOINT_SEMAPHORE\fP (test, check_if_attached)"
.br
.ti -1c
.RI "\fBTRACEPOINT_SEMAPHORE\fP (test, expensive_section)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_tracepoints)"
.br
.ti -1c
.RI "int \fBfail_test_if_executed\fP ()"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_tracepoint_check_if_attached)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_tracepoint_manual_tracepoint_active_check)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (test_tracepoint_check_if_attached )"

.SS "BOOST_AUTO_TEST_CASE (test_tracepoint_manual_tracepoint_active_check )"

.SS "BOOST_AUTO_TEST_CASE (test_tracepoints )"

.SS "int fail_test_if_executed ()"

.SS "TRACEPOINT_SEMAPHORE (test , check_if_attached )"

.SS "TRACEPOINT_SEMAPHORE (test , expensive_section )"

.SS "TRACEPOINT_SEMAPHORE (test , one_arg )"

.SS "TRACEPOINT_SEMAPHORE (test , six_args )"

.SS "TRACEPOINT_SEMAPHORE (test , twelve_args )"

.SS "TRACEPOINT_SEMAPHORE (test , zero_args )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
