.TH "Unexpected< E >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unexpected< E >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <expected\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBUnexpected\fP (\fBE\fP e)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBE\fP \fBerr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class \fBE\fP>
.br
class util::Unexpected< E >"The \fButil::Unexpected\fP class represents an unexpected value stored in \fButil::Expected\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class \fBE\fP> Unexpected (\fBE\fP e)\fR [inline]\fP, \fR [explicit]\fP, \fR [constexpr]\fP"

.SH "Field Documentation"
.PP 
.SS "template<class \fBE\fP> \fBE\fP err"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
