.TH "ConstevalFormatString< num_params >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstevalFormatString< num_params > \- A wrapper for a compile-time partially validated format string\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <string\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "consteval \fBConstevalFormatString\fP (const char *str)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char *const \fBfmt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<unsigned num_params>
.br
struct util::ConstevalFormatString< num_params >"A wrapper for a compile-time partially validated format string\&. 

This struct can be used to enforce partial compile-time validation of format strings, to reduce the likelihood of tinyformat throwing exceptions at run-time\&. Validation is partial to try and prevent the most common errors while avoiding re-implementing the entire parsing logic\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<unsigned num_params> ConstevalFormatString (const char * str)\fR [inline]\fP, \fR [consteval]\fP"

.SH "Field Documentation"
.PP 
.SS "template<unsigned num_params> const char* const fmt"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
