.TH "src/node/utxo_snapshot.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/utxo_snapshot.h
.SH SYNOPSIS
.br
.PP
\fR#include <kernel/chainparams\&.h>\fP
.br
\fR#include <kernel/cs_main\&.h>\fP
.br
\fR#include <kernel/messagestartchars\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <array>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <ios>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <set>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSnapshotMetadata\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::optional< \fBfs::path\fP > \fBFindAssumeutxoChainstateDir\fP (const \fBfs::path\fP &data_dir)"
.br
.RI "Return a path to the snapshot-based chainstate dir, if one exists\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBfs::path\fP \fBSNAPSHOT_BLOCKHASH_FILENAME\fP {'base_blockhash'}"
.br
.ti -1c
.RI "bool \fBWriteSnapshotBaseBlockhash\fP(\fBChainstate\fP &snapshot_chainstate) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(std::optional< \fBuint256\fP > \fBReadSnapshotBaseBlockhash\fP(\fBfs::path\fP chaindir) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(constexpr std::string_vie \fBSNAPSHOT_CHAINSTATE_SUFFIX\fP ) = '_snapshot'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
