.TH "src/test/fuzz/utxo_total_supply.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/utxo_total_supply.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <chainparams\&.h>\fP
.br
\fR#include <consensus/consensus\&.h>\fP
.br
\fR#include <consensus/merkle\&.h>\fP
.br
\fR#include <kernel/coinstats\&.h>\fP
.br
\fR#include <node/miner\&.h>\fP
.br
\fR#include <script/interpreter\&.h>\fP
.br
\fR#include <streams\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <test/util/mining\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFUZZ_TARGET\fP (utxo_total_supply)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (utxo_total_supply )"
The testing setup that creates a chainman only (no chainstate)

.PP
The block template this fuzzer is working on

.PP
Append-only set of tx outpoints, entries are not removed when spent

.PP
The utxo stats at the chain tip

.PP
The total amount of coins in the utxo set
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
