.TH "src/test/validation_chainstatemanager_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/validation_chainstatemanager_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <chainparams\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <kernel/disconnected_transactions\&.h>\fP
.br
\fR#include <node/chainstatemanager_args\&.h>\fP
.br
\fR#include <node/kernel_notifications\&.h>\fP
.br
\fR#include <node/utxo_snapshot\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <rpc/blockchain\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <test/util/chainstate\&.h>\fP
.br
\fR#include <test/util/logging\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <test/util/validation\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/result\&.h>\fP
.br
\fR#include <util/vector\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <validationinterface\&.h>\fP
.br
\fR#include <tinyformat\&.h>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSnapshotTestSetup\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (chainstatemanager, \fBTestChain100Setup\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (chainstatemanager_rebalance_caches, \fBTestChain100Setup\fP)"
.br
.RI "Test rebalancing the caches associated with each chainstate\&. "
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (chainstatemanager_activate_snapshot, \fBSnapshotTestSetup\fP)"
.br
.RI "Test basic snapshot activation\&. "
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (chainstatemanager_loadblockindex, \fBTestChain100Setup\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (chainstatemanager_snapshot_init, \fBSnapshotTestSetup\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (chainstatemanager_snapshot_completion, \fBSnapshotTestSetup\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (chainstatemanager_snapshot_completion_hash_mismatch, \fBSnapshotTestSetup\fP)"
.br
.ti -1c
.RI "template<typename \fBOptions\fP> \fButil::Result\fP< \fBOptions\fP > \fBSetOptsFromArgs\fP (\fBArgsManager\fP &args_man, \fBOptions\fP opts, const std::vector< const char * > &\fBargs\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (chainstatemanager_args, \fBBasicTestingSetup\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_FIXTURE_TEST_CASE (chainstatemanager , \fBTestChain100Setup\fP )"
Basic tests for \fBChainstateManager\fP\&.

.PP
First create a legacy (IBD) chainstate, then create a snapshot chainstate\&. 
.SS "BOOST_FIXTURE_TEST_CASE (chainstatemanager_activate_snapshot , \fBSnapshotTestSetup\fP )"

.PP
Test basic snapshot activation\&. 
.SS "BOOST_FIXTURE_TEST_CASE (chainstatemanager_args , \fBBasicTestingSetup\fP )"
Try to apply the provided args to a \fBChainstateManager::Options\fP

.PP
Like get_opts, but requires the provided args to be valid and unwraps the result
.SS "BOOST_FIXTURE_TEST_CASE (chainstatemanager_loadblockindex , \fBTestChain100Setup\fP )"
Test LoadBlockIndex behavior when multiple chainstates are in use\&.

.PP
.IP "\(bu" 2
First, verify that setBlockIndexCandidates is as expected when using a single, fully-validating chainstate\&.
.IP "\(bu" 2
Then mark a region of the chain as missing data and introduce a second chainstate that will tolerate assumed-valid blocks\&. Run LoadBlockIndex() and ensure that the first chainstate only contains fully validated blocks and the other chainstate contains all blocks, except those marked assume-valid, because those entries don't HAVE_DATA\&. 
.PP

.SS "BOOST_FIXTURE_TEST_CASE (chainstatemanager_rebalance_caches , \fBTestChain100Setup\fP )"

.PP
Test rebalancing the caches associated with each chainstate\&. 
.SS "BOOST_FIXTURE_TEST_CASE (chainstatemanager_snapshot_completion , \fBSnapshotTestSetup\fP )"

.SS "BOOST_FIXTURE_TEST_CASE (chainstatemanager_snapshot_completion_hash_mismatch , \fBSnapshotTestSetup\fP )"

.SS "BOOST_FIXTURE_TEST_CASE (chainstatemanager_snapshot_init , \fBSnapshotTestSetup\fP )"
Ensure that snapshot chainstate can be loaded when found on disk after a restart, and that new blocks can be connected to both chainstates\&. 
.SS "template<typename \fBOptions\fP> \fButil::Result\fP< \fBOptions\fP > SetOptsFromArgs (\fBArgsManager\fP & args_man, \fBOptions\fP opts, const std::vector< const char * > & args)"
Helper function to parse args into args_man and return the result of applying them to opts 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
