.TH "src/test/validation_block_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/validation_block_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <consensus/merkle\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <node/miner\&.h>\fP
.br
\fR#include <pow\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/script\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <validationinterface\&.h>\fP
.br
\fR#include <thread>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBMinerTestingSetup\fP"
.br
.ti -1c
.RI "struct \fBTestSubscriber\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvalidation_block_tests\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (processnewblock_signals_ordering)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (mempool_locks_reorg)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (witness_commitment_index)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (mempool_locks_reorg )"
Test that mempool updates happen atomically with reorgs\&.

.PP
This prevents RPC clients, among others, from retrieving immediately-out-of-date mempool data during large reorgs\&.

.PP
The test verifies this by creating a chain of \fRnum_txs\fP blocks, matures their coinbases, and then submits txns spending from their coinbase to the mempool\&. A fork chain is then processed, invalidating the txns and evicting them from the mempool\&.

.PP
We verify that the mempool updates atomically by polling it continuously from another thread during the reorg and checking that its size only changes once\&. The size changing exactly once indicates that the polling thread's view of the mempool is either consistent with the chain state before reorg, or consistent with the chain state after the reorg, and not just consistent with some intermediate state during the reorg\&. 
.SS "BOOST_AUTO_TEST_CASE (processnewblock_signals_ordering )"

.SS "BOOST_AUTO_TEST_CASE (witness_commitment_index )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
