.TH "src/test/validation_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/validation_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <chainparams\&.h>\fP
.br
\fR#include <consensus/amount\&.h>\fP
.br
\fR#include <consensus/merkle\&.h>\fP
.br
\fR#include <core_io\&.h>\fP
.br
\fR#include <hash\&.h>\fP
.br
\fR#include <net\&.h>\fP
.br
\fR#include <signet\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (block_subsidy_test)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (subsidy_limit_test)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (signet_parse_tests)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (test_assumeutxo)"
.br
.RI "Test retrieval of valid assumeutxo values\&. "
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (block_malleation)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (block_malleation )"

.SS "BOOST_AUTO_TEST_CASE (block_subsidy_test )"

.SS "BOOST_AUTO_TEST_CASE (signet_parse_tests )"

.SS "BOOST_AUTO_TEST_CASE (subsidy_limit_test )"

.SS "BOOST_AUTO_TEST_CASE (test_assumeutxo )"

.PP
Test retrieval of valid assumeutxo values\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
