.TH "src/test/fuzz/validation_load_mempool.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/fuzz/validation_load_mempool.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <node/mempool_persist\&.h>\fP
.br
\fR#include <node/mempool_args\&.h>\fP
.br
\fR#include <node/mempool_persist_args\&.h>\fP
.br
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <test/fuzz/util/mempool\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <test/util/txmempool\&.h>\fP
.br
\fR#include <txmempool\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_validation_load_mempool\fP ()"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (validation_load_mempool,\&.\fBinit\fP=\fBinitialize_validation_load_mempool\fP)"
.br
.ti -1c
.RI "bool \fBDumpMempool\fP (const \fBCTxMemPool\fP &pool, const \fBfs::path\fP &dump_path, \fBFopenFn\fP mockable_fopen_function, bool skip_file_commit)"
.br
.ti -1c
.RI "bool \fBLoadMempool\fP (\fBCTxMemPool\fP &pool, const \fBfs::path\fP &load_path, \fBChainstate\fP &active_chainstate, ImportMempoolOptions &&opts)"
.br
.ti -1c
.RI "\fBfs::path\fP \fBMempoolPath\fP (const \fBArgsManager\fP &argsman)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool DumpMempool (const \fBCTxMemPool\fP & pool, const \fBfs::path\fP & dump_path, \fBfsbridge::FopenFn\fP mockable_fopen_function = \fR\fBfsbridge::fopen\fP\fP, bool skip_file_commit = \fRfalse\fP)"
Dump the mempool to a file\&. 
.SS "FUZZ_TARGET (validation_load_mempool , \&. init = \fR\fBinitialize_validation_load_mempool\fP\fP)"

.SS "void initialize_validation_load_mempool ()"

.SS "bool LoadMempool (\fBCTxMemPool\fP & pool, const \fBfs::path\fP & load_path, \fBChainstate\fP & active_chainstate, ImportMempoolOptions && opts)"
Import the file and attempt to add its contents to the mempool\&. 
.SS "\fBfs::path\fP MempoolPath (const \fBArgsManager\fP & argsman)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
