.TH "src/test/validation_chainstate_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/validation_chainstate_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <chainparams\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <node/kernel_notifications\&.h>\fP
.br
\fR#include <random\&.h>\fP
.br
\fR#include <rpc/blockchain\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <test/util/chainstate\&.h>\fP
.br
\fR#include <test/util/coins\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (validation_chainstate_resize_caches)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (chainstate_update_tip, \fBTestChain100Setup\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (validation_chainstate_resize_caches )"
Test resizing coins-related \fBChainstate\fP caches during runtime\&. 
.SS "BOOST_FIXTURE_TEST_CASE (chainstate_update_tip , \fBTestChain100Setup\fP )"
Test UpdateTip behavior for both active and background chainstates\&.

.PP
When run on the background chainstate, UpdateTip should do a subset of what it does for the active chainstate\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
