.TH "ValidationState< Result >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValidationState< Result >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <validation\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBInvalid\fP (Result result, const std::string &reject_reason='', const std::string &debug_message='')"
.br
.ti -1c
.RI "bool \fBError\fP (const std::string &reject_reason)"
.br
.ti -1c
.RI "bool \fBIsValid\fP () const"
.br
.ti -1c
.RI "bool \fBIsInvalid\fP () const"
.br
.ti -1c
.RI "bool \fBIsError\fP () const"
.br
.ti -1c
.RI "Result \fBGetResult\fP () const"
.br
.ti -1c
.RI "std::string \fBGetRejectReason\fP () const"
.br
.ti -1c
.RI "std::string \fBGetDebugMessage\fP () const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Result>
.br
class ValidationState< Result >"Template for capturing information about block/transaction validation\&. This is instantiated by \fBTxValidationState\fP and \fBBlockValidationState\fP for validation information on transactions and blocks respectively\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename Result> bool Error (const std::string & reject_reason)\fR [inline]\fP"

.SS "template<typename Result> std::string GetDebugMessage () const\fR [inline]\fP"

.SS "template<typename Result> std::string GetRejectReason () const\fR [inline]\fP"

.SS "template<typename Result> Result GetResult () const\fR [inline]\fP"

.SS "template<typename Result> bool Invalid (Result result, const std::string & reject_reason = \fR''\fP, const std::string & debug_message = \fR''\fP)\fR [inline]\fP"

.SS "template<typename Result> bool IsError () const\fR [inline]\fP"

.SS "template<typename Result> bool IsInvalid () const\fR [inline]\fP"

.SS "template<typename Result> bool IsValid () const\fR [inline]\fP"

.SS "template<typename Result> std::string ToString () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
