.TH "src/test/validationinterface_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/validationinterface_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <boost/test/unit_test\&.hpp>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <scheduler\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <validationinterface\&.h>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <memory>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTestSubscriberNoop\fP"
.br
.ti -1c
.RI "class \fBTestInterface\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (unregister_validation_interface_race)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (unregister_all_during_call)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (unregister_all_during_call )"

.SS "BOOST_AUTO_TEST_CASE (unregister_validation_interface_race )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
