.TH "src/validationinterface.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/validationinterface.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <validationinterface\&.h>\fP
.br
\fR#include <chain\&.h>\fP
.br
\fR#include <consensus/validation\&.h>\fP
.br
\fR#include <kernel/mempool_entry\&.h>\fP
.br
\fR#include <kernel/mempool_removal_reason\&.h>\fP
.br
\fR#include <kernel/types\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <util/check\&.h>\fP
.br
\fR#include <util/task_runner\&.h>\fP
.br
\fR#include <future>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <utility>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBValidationSignalsImpl\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENQUEUE_AND_LOG_EVENT\fP(event,  fmt,  \fBname\fP, \&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOG_EVENT\fP(fmt, \&.\&.\&.)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENQUEUE_AND_LOG_EVENT( event,  fmt,  \fBname\fP,  \&.\&.\&.)"
\fBValue:\fP
.nf
    do {                                                       \\
        auto local_name = (name);                              \\
        LOG_EVENT("Enqueuing " fmt, local_name, __VA_ARGS__);  \\
        m_internals\->m_task_runner\->insert([=] { \\
            LOG_EVENT(fmt, local_name, __VA_ARGS__);           \\
            event();                                           \\
        });                                                    \\
    } while (0)
.PP
.fi

.SS "#define LOG_EVENT( fmt,  \&.\&.\&.)"
\fBValue:\fP
.nf
    LogDebug(BCLog::VALIDATION, fmt "\\n", __VA_ARGS__)
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
