.TH "src/validationinterface.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/validationinterface.h
.SH SYNOPSIS
.br
.PP
\fR#include <kernel/cs_main\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCValidationInterface\fP"
.br
.ti -1c
.RI "class \fBValidationSignals\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBkernel\fP"
.br
.ti -1c
.RI "namespace \fButil\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
