.TH "VectorWriter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VectorWriter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <streams\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVectorWriter\fP (std::vector< unsigned char > &vchDataIn, size_t nPosIn)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBVectorWriter\fP (std::vector< unsigned char > &vchDataIn, size_t nPosIn, Args &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "void \fBwrite\fP (std::span< const std::byte > src)"
.br
.ti -1c
.RI "template<typename \fBT\fP> \fBVectorWriter\fP & \fBoperator<<\fP (const \fBT\fP &obj)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBVectorWriter\fP (std::vector< unsigned char > & vchDataIn, size_t nPosIn)\fR [inline]\fP"

.SS "template<typename\&.\&.\&. Args> \fBVectorWriter\fP (std::vector< unsigned char > & vchDataIn, size_t nPosIn, Args &&\&.\&.\&. args)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBT\fP> \fBVectorWriter\fP & operator<< (const \fBT\fP & obj)\fR [inline]\fP"

.SS "void write (std::span< const std::byte > src)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
