.TH "src/bench/verify_script.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bench/verify_script.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bench/bench\&.h>\fP
.br
\fR#include <hash\&.h>\fP
.br
\fR#include <key\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <pubkey\&.h>\fP
.br
\fR#include <script/interpreter\&.h>\fP
.br
\fR#include <script/script\&.h>\fP
.br
\fR#include <span\&.h>\fP
.br
\fR#include <test/util/transaction_utils\&.h>\fP
.br
\fR#include <uint256\&.h>\fP
.br
\fR#include <array>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBENCHMARK\fP (VerifyScriptBench, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.ti -1c
.RI "\fBBENCHMARK\fP (VerifyNestedIfScript, \fBbenchmark::PriorityLevel::HIGH\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BENCHMARK (VerifyNestedIfScript , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SS "BENCHMARK (VerifyScriptBench , \fBbenchmark::PriorityLevel::HIGH\fP )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
