.TH "VersionBitsConditionChecker" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VersionBitsConditionChecker
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <versionbits_impl\&.h>\fP
.PP
Inherits \fBAbstractThresholdConditionChecker\fP\&.
.PP
Inherited by \fBTestConditionChecker\fP, and \fBTestConditionChecker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVersionBitsConditionChecker\fP (const \fBConsensus::BIP9Deployment\fP &dep)"
.br
.ti -1c
.RI "\fBVersionBitsConditionChecker\fP (const \fBConsensus::Params\fP &params, \fBConsensus::DeploymentPos\fP id)"
.br
.ti -1c
.RI "uint32_t \fBMask\fP () const"
.br
.ti -1c
.RI "bool \fBCondition\fP (int32_t nVersion) const"
.br
.in -1c

Public Member Functions inherited from \fBAbstractThresholdConditionChecker\fP
.in +1c
.ti -1c
.RI "virtual \fB~AbstractThresholdConditionChecker\fP ()=default"
.br
.ti -1c
.RI "\fBBIP9Stats\fP \fBGetStateStatisticsFor\fP (const \fBCBlockIndex\fP *pindex, std::vector< bool > *signalling_blocks=nullptr) const"
.br
.ti -1c
.RI "\fBThresholdState\fP \fBGetStateFor\fP (const \fBCBlockIndex\fP *pindexPrev, \fBThresholdConditionCache\fP &cache) const"
.br
.ti -1c
.RI "int \fBGetStateSinceHeightFor\fP (const \fBCBlockIndex\fP *pindexPrev, \fBThresholdConditionCache\fP &cache) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "int64_t \fBBeginTime\fP () const override"
.br
.ti -1c
.RI "int64_t \fBEndTime\fP () const override"
.br
.ti -1c
.RI "int \fBMinActivationHeight\fP () const override"
.br
.ti -1c
.RI "int \fBPeriod\fP () const override"
.br
.ti -1c
.RI "int \fBThreshold\fP () const override"
.br
.ti -1c
.RI "bool \fBCondition\fP (const \fBCBlockIndex\fP *pindex) const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class to implement versionbits logic\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBVersionBitsConditionChecker\fP (const \fBConsensus::BIP9Deployment\fP & dep)\fR [inline]\fP, \fR [explicit]\fP"

.SS "\fBVersionBitsConditionChecker\fP (const \fBConsensus::Params\fP & params, \fBConsensus::DeploymentPos\fP id)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int64_t BeginTime () const\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBAbstractThresholdConditionChecker\fP\&.
.SS "bool Condition (const \fBCBlockIndex\fP * pindex) const\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBAbstractThresholdConditionChecker\fP\&.
.SS "bool Condition (int32_t nVersion) const\fR [inline]\fP"

.SS "int64_t EndTime () const\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBAbstractThresholdConditionChecker\fP\&.
.SS "uint32_t Mask () const\fR [inline]\fP"

.SS "int MinActivationHeight () const\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBAbstractThresholdConditionChecker\fP\&.
.SS "int Period () const\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBAbstractThresholdConditionChecker\fP\&.
.SS "int Threshold () const\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBAbstractThresholdConditionChecker\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
