.TH "src/leveldb/db/version_set.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/leveldb/db/version_set.h
.SH SYNOPSIS
.br
.PP
\fR#include <map>\fP
.br
\fR#include <set>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'db/dbformat\&.h'\fP
.br
\fR#include 'db/version_edit\&.h'\fP
.br
\fR#include 'port/port\&.h'\fP
.br
\fR#include 'port/thread_annotations\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBVersion\fP"
.br
.ti -1c
.RI "struct \fBVersion::GetStats\fP"
.br
.ti -1c
.RI "class \fBVersionSet\fP"
.br
.ti -1c
.RI "struct \fBVersionSet::LevelSummaryStorage\fP"
.br
.ti -1c
.RI "class \fBCompaction\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBleveldb\fP"
.br
.ti -1c
.RI "namespace \fBleveldb::log\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBFindFile\fP (const \fBInternalKeyComparator\fP &icmp, const std::vector< \fBFileMetaData\fP * > &files, const \fBSlice\fP &key)"
.br
.ti -1c
.RI "bool \fBSomeFileOverlapsRange\fP (const \fBInternalKeyComparator\fP &icmp, bool disjoint_sorted_files, const std::vector< \fBFileMetaData\fP * > &files, const \fBSlice\fP *smallest_user_key, const \fBSlice\fP *largest_user_key)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
