.TH "src/versionbits_impl.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/versionbits_impl.h
.SH SYNOPSIS
.br
.PP
\fR#include <chain\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <versionbits\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAbstractThresholdConditionChecker\fP"
.br
.ti -1c
.RI "class \fBVersionBitsConditionChecker\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBThresholdState\fP : uint8_t { \fBDEFINED\fP, \fBSTARTED\fP, \fBLOCKED_IN\fP, \fBACTIVE\fP, \fBFAILED\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBStateName\fP (\fBThresholdState\fP state)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBThresholdState\fP : uint8_t\fR [strong]\fP"
BIP 9 defines a finite-state-machine to deploy a softfork in multiple stages\&. \fBState\fP transitions happen during retarget period if conditions are met In case of reorg, transitions can go backward\&. Without transition, state is inherited between periods\&. All blocks of a period share the same state\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIDEFINED \fP
.TP
\f(BISTARTED \fP
.TP
\f(BILOCKED_IN \fP
.TP
\f(BIACTIVE \fP
.TP
\f(BIFAILED \fP
.SH "Function Documentation"
.PP 
.SS "std::string StateName (\fBThresholdState\fP state)"
Get a string with the state name 
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
