.TH "src/test/versionbits_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/versionbits_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <chain\&.h>\fP
.br
\fR#include <chainparams\&.h>\fP
.br
\fR#include <consensus/params\&.h>\fP
.br
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/chaintype\&.h>\fP
.br
\fR#include <versionbits\&.h>\fP
.br
\fR#include <versionbits_impl\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTestConditionChecker\fP"
.br
.ti -1c
.RI "class \fBVersionBitsTester\fP"
.br
.ti -1c
.RI "struct \fBBlockVersionTest\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHECKERS\fP   6"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (versionbits_test)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (versionbits_computeblockversion, \fBBlockVersionTest\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHECKERS   6"

.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (versionbits_test )"

.SS "BOOST_FIXTURE_TEST_CASE (versionbits_computeblockversion , \fBBlockVersionTest\fP )"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
