.TH "OutputGroupTypeMap" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutputGroupTypeMap
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <coinselection\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPush\fP (const \fBOutputGroup\fP &group, \fBOutputType\fP type, bool insert_positive, bool insert_mixed)"
.br
.ti -1c
.RI "size_t \fBTypesCount\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::map< \fBOutputType\fP, \fBGroups\fP > \fBgroups_by_type\fP"
.br
.ti -1c
.RI "\fBGroups\fP \fBall_groups\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores several '\fBGroups\fP' whose were mapped by output type\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Push (const \fBOutputGroup\fP & group, \fBOutputType\fP type, bool insert_positive, bool insert_mixed)"

.SS "size_t TypesCount ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBGroups\fP all_groups"

.SS "std::map<\fBOutputType\fP, \fBGroups\fP> groups_by_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
