.TH "CHDChain" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CHDChain
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <walletdb\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCHDChain\fP ()"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCHDChain\fP, obj)"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCHDChain\fP &chain) const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBnExternalChainCounter\fP"
.br
.ti -1c
.RI "uint32_t \fBnInternalChainCounter\fP"
.br
.ti -1c
.RI "\fBCKeyID\fP \fBseed_id\fP"
.br
.RI "seed hash160 "
.ti -1c
.RI "int64_t \fBm_next_external_index\fP {0}"
.br
.ti -1c
.RI "int64_t \fBm_next_internal_index\fP {0}"
.br
.ti -1c
.RI "int \fBnVersion\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBVERSION_HD_BASE\fP = 1"
.br
.ti -1c
.RI "static const int \fBVERSION_HD_CHAIN_SPLIT\fP = 2"
.br
.ti -1c
.RI "static const int \fBCURRENT_VERSION\fP = \fBVERSION_HD_CHAIN_SPLIT\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CHDChain ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool operator== (const \fBCHDChain\fP & chain) const\fR [inline]\fP"

.SS "SERIALIZE_METHODS (\fBCHDChain\fP , obj )\fR [inline]\fP"

.SS "void SetNull ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "const int CURRENT_VERSION = \fBVERSION_HD_CHAIN_SPLIT\fP\fR [static]\fP"

.SS "int64_t m_next_external_index {0}"

.SS "int64_t m_next_internal_index {0}"

.SS "uint32_t nExternalChainCounter"

.SS "uint32_t nInternalChainCounter"

.SS "int nVersion"

.SS "\fBCKeyID\fP seed_id"

.PP
seed hash160 
.SS "const int VERSION_HD_BASE = 1\fR [static]\fP"

.SS "const int VERSION_HD_CHAIN_SPLIT = 2\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
