.TH "MockableDatabase" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MockableDatabase
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.PP
Inherits \fBWalletDatabase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMockableDatabase\fP (\fBMockableData\fP records={})"
.br
.ti -1c
.RI "\fB~MockableDatabase\fP ()=default"
.br
.ti -1c
.RI "void \fBOpen\fP () override"
.br
.ti -1c
.RI "bool \fBRewrite\fP () override"
.br
.ti -1c
.RI "bool \fBBackup\fP (const std::string &strDest) const override"
.br
.ti -1c
.RI "void \fBClose\fP () override"
.br
.ti -1c
.RI "std::string \fBFilename\fP () override"
.br
.ti -1c
.RI "std::vector< \fBfs::path\fP > \fBFiles\fP () override"
.br
.ti -1c
.RI "std::string \fBFormat\fP () override"
.br
.ti -1c
.RI "std::unique_ptr< \fBDatabaseBatch\fP > \fBMakeBatch\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBWalletDatabase\fP
.in +1c
.ti -1c
.RI "\fBWalletDatabase\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~WalletDatabase\fP ()=default"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMockableData\fP \fBm_records\fP"
.br
.ti -1c
.RI "bool \fBm_pass\fP {true}"
.br
.in -1c

Data Fields inherited from \fBWalletDatabase\fP
.in +1c
.ti -1c
.RI "std::atomic< int > \fBm_refcount\fP {0}"
.br
.RI "Counts the number of active database users to be sure that the database is not closed while someone is using it\&. "
.in -1c
.SH "Detailed Description"
.PP 
A \fBWalletDatabase\fP whose contents and return values can be modified as needed for testing 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MockableDatabase (\fBMockableData\fP records = \fR{}\fP)\fR [inline]\fP"

.SS "~\fBMockableDatabase\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool Backup (const std::string & strDest) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Back up the entire database to a file\&. 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "void Close ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Flush to the database file and close the database\&. Also close the environment if no other databases are open in it\&. 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "std::string Filename ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Return path to main database file for logs and error messages\&. 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "std::vector< \fBfs::path\fP > Files ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Return paths to all database created files 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "std::string \fBFormat\fP ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBWalletDatabase\fP\&.
.SS "std::unique_ptr< \fBDatabaseBatch\fP > MakeBatch ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Make a \fBDatabaseBatch\fP connected to this database 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "void Open ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Open the database if it is not already opened\&. 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "bool Rewrite ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Rewrite the entire database on disk 
.PP
Implements \fBWalletDatabase\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool m_pass {true}"

.SS "\fBMockableData\fP m_records"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
