.TH "CRecipient" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRecipient
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wallet\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCTxDestination\fP \fBdest\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBnAmount\fP"
.br
.ti -1c
.RI "bool \fBfSubtractFeeFromAmount\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBCTxDestination\fP dest"

.SS "bool fSubtractFeeFromAmount"

.SS "\fBCAmount\fP nAmount"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
