.TH "DatabaseCursor" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseCursor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <db\&.h>\fP
.PP
Inherited by \fBBerkeleyROCursor\fP, \fBMockableCursor\fP, and \fBSQLiteCursor\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBStatus\fP { \fBFAIL\fP, \fBMORE\fP, \fBDONE\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDatabaseCursor\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~DatabaseCursor\fP ()=default"
.br
.ti -1c
.RI "\fBDatabaseCursor\fP (const DatabaseCursor &)=delete"
.br
.ti -1c
.RI "\fBDatabaseCursor\fP & \fBoperator=\fP (const \fBDatabaseCursor\fP &)=delete"
.br
.ti -1c
.RI "virtual \fBStatus\fP\fBStatus\fP \fBNext\fP (\fBDataStream\fP &key, \fBDataStream\fP &value)"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBStatus\fP\fBStatus\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIFAIL \fP
.TP
\f(BIMORE \fP
.TP
\f(BIDONE \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DatabaseCursor ()\fR [explicit]\fP, \fR [default]\fP"

.SS "virtual ~\fBDatabaseCursor\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SS "DatabaseCursor (const DatabaseCursor & )\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBStatus\fP\fBStatus\fP Next (\fBDataStream\fP & key, \fBDataStream\fP & value)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBBerkeleyROCursor\fP, \fBMockableCursor\fP, and \fBSQLiteCursor\fP\&.
.SS "\fBDatabaseCursor\fP & operator= (const \fBDatabaseCursor\fP & )\fR [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
