.TH "WalletMigrationResult" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletMigrationResult \- Migrated wallet info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wallet\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBWallet\fP > \fBwallet\fP"
.br
.ti -1c
.RI "std::optional< std::string > \fBwatchonly_wallet_name\fP"
.br
.ti -1c
.RI "std::optional< std::string > \fBsolvables_wallet_name\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBbackup_path\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Migrated wallet info\&. 
.SH "Field Documentation"
.PP 
.SS "\fBfs::path\fP backup_path"

.SS "std::optional<std::string> solvables_wallet_name"

.SS "std::unique_ptr<\fBWallet\fP> wallet"

.SS "std::optional<std::string> watchonly_wallet_name"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
