.TH "src/wallet/test/wallet_crypto_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/test/wallet_crypto_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/util/random\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/strencodings\&.h>\fP
.br
\fR#include <wallet/crypter\&.h>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTestCrypter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (passphrase)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (encrypt)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (decrypt)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
