.TH "SQLiteDatabase" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLiteDatabase
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sqlite\&.h>\fP
.PP
Inherits \fBWalletDatabase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSQLiteDatabase\fP ()=delete"
.br
.ti -1c
.RI "\fBSQLiteDatabase\fP (const \fBfs::path\fP &dir_path, const \fBfs::path\fP &file_path, const \fBDatabaseOptions\fP &options, bool mock=false)"
.br
.ti -1c
.RI "\fB~SQLiteDatabase\fP ()"
.br
.ti -1c
.RI "bool \fBVerify\fP (\fBbilingual_str\fP &error)"
.br
.ti -1c
.RI "void \fBOpen\fP () override"
.br
.ti -1c
.RI "void \fBClose\fP () override"
.br
.ti -1c
.RI "bool \fBRewrite\fP () override"
.br
.ti -1c
.RI "bool \fBBackup\fP (const std::string &dest) const override"
.br
.ti -1c
.RI "std::string \fBFilename\fP () override"
.br
.ti -1c
.RI "std::vector< \fBfs::path\fP > \fBFiles\fP () override"
.br
.ti -1c
.RI "std::string \fBFormat\fP () override"
.br
.ti -1c
.RI "std::unique_ptr< \fBDatabaseBatch\fP > \fBMakeBatch\fP () override"
.br
.ti -1c
.RI "bool \fBHasActiveTxn\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBWalletDatabase\fP
.in +1c
.ti -1c
.RI "\fBWalletDatabase\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~WalletDatabase\fP ()=default"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::binary_semaphore \fBm_write_semaphore\fP"
.br
.ti -1c
.RI "sqlite3 * \fBm_db\fP {nullptr}"
.br
.ti -1c
.RI "bool \fBm_use_unsafe_sync\fP"
.br
.in -1c

Data Fields inherited from \fBWalletDatabase\fP
.in +1c
.ti -1c
.RI "std::atomic< int > \fBm_refcount\fP {0}"
.br
.RI "Counts the number of active database users to be sure that the database is not closed while someone is using it\&. "
.in -1c
.SH "Detailed Description"
.PP 
An instance of this class represents one SQLite3 database\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLiteDatabase ()\fR [delete]\fP"

.SS "SQLiteDatabase (const \fBfs::path\fP & dir_path, const \fBfs::path\fP & file_path, const \fBDatabaseOptions\fP & options, bool mock = \fRfalse\fP)"
Create \fBDB\fP handle to real database 
.SS "~\fBSQLiteDatabase\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "bool Backup (const std::string & dest) const\fR [override]\fP, \fR [virtual]\fP"
Back up the entire database to a file\&. 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "void Close ()\fR [override]\fP, \fR [virtual]\fP"
Close the database 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "std::string Filename ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Return path to main database file for logs and error messages\&. 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "std::vector< \fBfs::path\fP > Files ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"
Return paths to all database created files 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "std::string \fBFormat\fP ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBWalletDatabase\fP\&.
.SS "bool HasActiveTxn ()"
Return true if there is an on-going txn in this connection 
.SS "std::unique_ptr< \fBDatabaseBatch\fP > MakeBatch ()\fR [override]\fP, \fR [virtual]\fP"
Make a \fBSQLiteBatch\fP connected to this database 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "void Open ()\fR [override]\fP, \fR [virtual]\fP"
Open the database if it is not already opened 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "bool Rewrite ()\fR [override]\fP, \fR [virtual]\fP"
Rewrite the entire database on disk 
.PP
Implements \fBWalletDatabase\fP\&.
.SS "bool Verify (\fBbilingual_str\fP & error)"

.SH "Field Documentation"
.PP 
.SS "sqlite3* m_db {nullptr}"

.SS "bool m_use_unsafe_sync"

.SS "std::binary_semaphore m_write_semaphore"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
