.TH "src/qt/test/wallettests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/test/wallettests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/test/wallettests\&.h>\fP
.br
\fR#include <qt/test/util\&.h>\fP
.br
\fR#include <wallet/coincontrol\&.h>\fP
.br
\fR#include <interfaces/chain\&.h>\fP
.br
\fR#include <interfaces/node\&.h>\fP
.br
\fR#include <key_io\&.h>\fP
.br
\fR#include <qt/bitcoinamountfield\&.h>\fP
.br
\fR#include <qt/bitcoinunits\&.h>\fP
.br
\fR#include <qt/clientmodel\&.h>\fP
.br
\fR#include <qt/optionsmodel\&.h>\fP
.br
\fR#include <qt/overviewpage\&.h>\fP
.br
\fR#include <qt/platformstyle\&.h>\fP
.br
\fR#include <qt/qvalidatedlineedit\&.h>\fP
.br
\fR#include <qt/receivecoinsdialog\&.h>\fP
.br
\fR#include <qt/receiverequestdialog\&.h>\fP
.br
\fR#include <qt/recentrequeststablemodel\&.h>\fP
.br
\fR#include <qt/sendcoinsdialog\&.h>\fP
.br
\fR#include <qt/sendcoinsentry\&.h>\fP
.br
\fR#include <qt/transactiontablemodel\&.h>\fP
.br
\fR#include <qt/transactionview\&.h>\fP
.br
\fR#include <qt/walletmodel\&.h>\fP
.br
\fR#include <script/solver\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <validation\&.h>\fP
.br
\fR#include <wallet/test/util\&.h>\fP
.br
\fR#include <wallet/wallet\&.h>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <QAbstractButton>\fP
.br
\fR#include <QAction>\fP
.br
\fR#include <QApplication>\fP
.br
\fR#include <QCheckBox>\fP
.br
\fR#include <QClipboard>\fP
.br
\fR#include <QObject>\fP
.br
\fR#include <QPushButton>\fP
.br
\fR#include <QTimer>\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QTextEdit>\fP
.br
\fR#include <QListView>\fP
.br
\fR#include <QDialogButtonBox>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWalletDescriptor\fP"
.br
.ti -1c
.RI "class \fBWalletRescanReserver\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBAddWallet\fP (\fBWalletContext\fP &context, const std::shared_ptr< \fBCWallet\fP > &\fBwallet\fP)"
.br
.ti -1c
.RI "std::unique_ptr< WalletDatabase > \fBCreateMockableWalletDatabase\fP (MockableData records)"
.br
.ti -1c
.RI "bool \fBRemoveWallet\fP (\fBWalletContext\fP &context, const std::shared_ptr< \fBCWallet\fP > &\fBwallet\fP, std::optional< bool > load_on_start, std::vector< \fBbilingual_str\fP > &warnings)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool AddWallet (\fBWalletContext\fP & context, const std::shared_ptr< \fBCWallet\fP > & wallet)"

.SS "std::unique_ptr< WalletDatabase > CreateMockableWalletDatabase (MockableData records = \fR{}\fP)"

.SS "bool RemoveWallet (\fBWalletContext\fP & context, const std::shared_ptr< \fBCWallet\fP > & wallet, std::optional< bool > load_on_start, std::vector< \fBbilingual_str\fP > & warnings)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
