.TH "src/wallet/walletutil.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/walletutil.h
.SH SYNOPSIS
.br
.PP
\fR#include <script/descriptor\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWalletDescriptor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBWalletFlags\fP : uint64_t { \fBWALLET_FLAG_AVOID_REUSE\fP = (1ULL << 0), \fBWALLET_FLAG_KEY_ORIGIN_METADATA\fP = (1ULL << 1), \fBWALLET_FLAG_LAST_HARDENED_XPUB_CACHED\fP = (1ULL << 2), \fBWALLET_FLAG_DISABLE_PRIVATE_KEYS\fP = (1ULL << 32), \fBWALLET_FLAG_BLANK_WALLET\fP = (1ULL << 33), \fBWALLET_FLAG_DESCRIPTORS\fP = (1ULL << 34), \fBWALLET_FLAG_EXTERNAL_SIGNER\fP = (1ULL << 35) }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfs::path\fP \fBGetWalletDir\fP ()"
.br
.RI "Get the path of the wallet directory\&. "
.ti -1c
.RI "\fBWalletDescriptor\fP \fBGenerateWalletDescriptor\fP (const \fBCExtPubKey\fP &master_key, const \fBOutputType\fP &addr_type, bool internal)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
