.TH "src/qt/walletcontroller.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/walletcontroller.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/walletcontroller\&.h>\fP
.br
\fR#include <qt/askpassphrasedialog\&.h>\fP
.br
\fR#include <qt/clientmodel\&.h>\fP
.br
\fR#include <qt/createwalletdialog\&.h>\fP
.br
\fR#include <qt/guiconstants\&.h>\fP
.br
\fR#include <qt/guiutil\&.h>\fP
.br
\fR#include <qt/walletmodel\&.h>\fP
.br
\fR#include <external_signer\&.h>\fP
.br
\fR#include <interfaces/handler\&.h>\fP
.br
\fR#include <interfaces/node\&.h>\fP
.br
\fR#include <util/string\&.h>\fP
.br
\fR#include <util/threadnames\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <wallet/wallet\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <QApplication>\fP
.br
\fR#include <QMessageBox>\fP
.br
\fR#include <QMetaObject>\fP
.br
\fR#include <QMutexLocker>\fP
.br
\fR#include <QThread>\fP
.br
\fR#include <QTimer>\fP
.br
\fR#include <QWindow>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename C, typename \fBS\fP, typename UnaryOp> auto \fBJoin\fP (const C &container, const \fBS\fP &separator, UnaryOp unary_op)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename C, typename \fBS\fP, typename UnaryOp> auto Join (const C & container, const \fBS\fP & separator, UnaryOp unary_op)"
Join all container items\&. Typically used to concatenate strings but accepts containers with elements of any type\&.

.PP
\fBParameters\fP
.RS 4
\fIcontainer\fP The items to join 
.br
\fIseparator\fP The separator 
.br
\fIunary_op\fP Apply this operator to each item 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
