.TH "SelectionFilter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SelectionFilter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <spend\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCoinEligibilityFilter\fP \fBfilter\fP"
.br
.ti -1c
.RI "bool \fBallow_mixed_output_types\fP {true}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool allow_mixed_output_types {true}"

.SS "\fBCoinEligibilityFilter\fP filter"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
