.TH "FuzzedWallet" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuzzedWallet
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wallet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFuzzedWallet\fP (\fBinterfaces::Chain\fP &chain, const std::string &\fBname\fP, const std::string &seed_insecure)"
.br
.ti -1c
.RI "void \fBImportDescriptors\fP (const std::string &seed_insecure)"
.br
.ti -1c
.RI "\fBCTxDestination\fP \fBGetDestination\fP (\fBFuzzedDataProvider\fP &fuzzed_data_provider)"
.br
.ti -1c
.RI "\fBCScript\fP \fBGetScriptPubKey\fP (\fBFuzzedDataProvider\fP &fuzzed_data_provider)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBCWallet\fP > \fBwallet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wraps a descriptor wallet for fuzzing\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FuzzedWallet (\fBinterfaces::Chain\fP & chain, const std::string & name, const std::string & seed_insecure)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBCTxDestination\fP GetDestination (\fBFuzzedDataProvider\fP & fuzzed_data_provider)\fR [inline]\fP"

.SS "\fBCScript\fP GetScriptPubKey (\fBFuzzedDataProvider\fP & fuzzed_data_provider)\fR [inline]\fP"

.SS "void ImportDescriptors (const std::string & seed_insecure)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::shared_ptr<\fBCWallet\fP> wallet"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
