.TH "src/qt/walletmodeltransaction.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/walletmodeltransaction.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <qt/walletmodeltransaction\&.h>\fP
.br
\fR#include <policy/policy\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
