.TH "WalletInitInterface" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletInitInterface
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <walletinitinterface\&.h>\fP
.PP
Inherited by \fBDummyWalletInit\fP, and \fBWalletInit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBHasWalletSupport\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBAddWalletOptions\fP (\fBArgsManager\fP &argsman) const =0"
.br
.ti -1c
.RI "virtual bool \fBParameterInteraction\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBConstruct\fP (\fBnode::NodeContext\fP &\fBnode\fP) const =0"
.br
.ti -1c
.RI "virtual \fB~WalletInitInterface\fP ()=default"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBWalletInitInterface\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void AddWalletOptions (\fBArgsManager\fP & argsman) const\fR [pure virtual]\fP"
Get wallet help string 
.PP
Implemented in \fBDummyWalletInit\fP, and \fBWalletInit\fP\&.
.SS "virtual void Construct (\fBnode::NodeContext\fP & node) const\fR [pure virtual]\fP"
Add wallets that should be opened to list of chain clients\&. 
.PP
Implemented in \fBDummyWalletInit\fP, and \fBWalletInit\fP\&.
.SS "virtual bool HasWalletSupport () const\fR [pure virtual]\fP"
Is the wallet component enabled 
.PP
Implemented in \fBDummyWalletInit\fP, and \fBWalletInit\fP\&.
.SS "virtual bool ParameterInteraction () const\fR [pure virtual]\fP"
Check wallet parameter interaction 
.PP
Implemented in \fBDummyWalletInit\fP, and \fBWalletInit\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
