.TH "OverflowRecord" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OverflowRecord
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOverflowRecord\fP (const \fBRecordHeader\fP &header)"
.br
.ti -1c
.RI "\fBOverflowRecord\fP ()=delete"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBRecordHeader\fP \fBm_header\fP"
.br
.ti -1c
.RI "uint8_t \fBunused2\fP"
.br
.ti -1c
.RI "uint32_t \fBpage_number\fP"
.br
.ti -1c
.RI "uint32_t \fBitem_len\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr size_t \fBSIZE\fP = 9"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for records representing overflow records of the BTree\&. Overflow records point to a page which contains the data in the record\&. Those pages may point to further pages with the rest of the data if it does not fit in one page 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OverflowRecord (const \fBRecordHeader\fP & header)\fR [inline]\fP"

.SS "OverflowRecord ()\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "uint32_t item_len"

.SS "\fBRecordHeader\fP m_header"

.SS "uint32_t page_number"

.SS "size_t SIZE = 9\fR [static]\fP, \fR [constexpr]\fP"

.SS "uint8_t unused2"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
