.TH "WalletTestingSetup" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletTestingSetup
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wallet_test_fixture\&.h>\fP
.PP
Inherits \fBTestingSetup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWalletTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP)"
.br
.ti -1c
.RI "\fB~WalletTestingSetup\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBTestingSetup\fP
.in +1c
.ti -1c
.RI "\fBTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.in -1c

Public Member Functions inherited from \fBChainTestingSetup\fP
.in +1c
.ti -1c
.RI "\fBChainTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~ChainTestingSetup\fP ()"
.br
.ti -1c
.RI "void \fBLoadVerifyActivateChainstate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "void \fBSeedRandomForTest\fP (\fBSeedRand\fP seed)"
.br
.ti -1c
.RI "\fBBasicTestingSetup\fP (const \fBChainType\fP chainType=\fBChainType::MAIN\fP, \fBTestOpts\fP={})"
.br
.ti -1c
.RI "\fB~BasicTestingSetup\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBinterfaces::WalletLoader\fP > \fBm_wallet_loader\fP"
.br
.ti -1c
.RI "\fBCWallet\fP \fBm_wallet\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBinterfaces::Handler\fP > \fBm_chain_notifications_handler\fP"
.br
.in -1c

Data Fields inherited from \fBChainTestingSetup\fP
.in +1c
.ti -1c
.RI "\fBkernel::CacheSizes\fP \fBm_kernel_cache_sizes\fP {\fBnode::CalculateCacheSizes\fP(\fBm_args\fP)\&.\fBkernel\fP}"
.br
.ti -1c
.RI "bool \fBm_coins_db_in_memory\fP {true}"
.br
.ti -1c
.RI "bool \fBm_block_tree_db_in_memory\fP {true}"
.br
.ti -1c
.RI "std::function< void()> \fBm_make_chainman\fP {}"
.br
.in -1c

Data Fields inherited from \fBBasicTestingSetup\fP
.in +1c
.ti -1c
.RI "\fButil::SignalInterrupt\fP \fBm_interrupt\fP"
.br
.ti -1c
.RI "\fBnode::NodeContext\fP \fBm_node\fP"
.br
.ti -1c
.RI "\fBFastRandomContext\fP \fBm_rng\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_root\fP"
.br
.ti -1c
.RI "\fBfs::path\fP \fBm_path_lock\fP"
.br
.ti -1c
.RI "bool \fBm_has_custom_datadir\fP {false}"
.br
.ti -1c
.RI "\fBArgsManager\fP \fBm_args\fP"
.br
.RI "Test-specific arguments and settings\&. "
.in -1c
.SH "Detailed Description"
.PP 
Testing setup and teardown for wallet\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WalletTestingSetup (const \fBChainType\fP chainType = \fR\fBChainType::MAIN\fP\fP)\fR [explicit]\fP"

.SS "~\fBWalletTestingSetup\fP ()"

.SH "Field Documentation"
.PP 
.SS "std::unique_ptr<\fBinterfaces::Handler\fP> m_chain_notifications_handler"

.SS "\fBCWallet\fP m_wallet"

.SS "std::unique_ptr<\fBinterfaces::WalletLoader\fP> m_wallet_loader"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
