.TH "tallyitem" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tallyitem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtallyitem\fP ()=default"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCAmount\fP \fBnAmount\fP {0}"
.br
.ti -1c
.RI "int \fBnConf\fP {std::numeric_limits<int>::max()}"
.br
.ti -1c
.RI "std::vector< \fBTxid\fP > \fBtxids\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tallyitem ()\fR [default]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBCAmount\fP nAmount {0}"

.SS "int nConf {std::numeric_limits<int>::max()}"

.SS "std::vector<\fBTxid\fP> txids"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
