.TH "WalletModelTransaction" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletModelTransaction
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <walletmodeltransaction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWalletModelTransaction\fP (const QList< \fBSendCoinsRecipient\fP > &recipients)"
.br
.ti -1c
.RI "QList< \fBSendCoinsRecipient\fP > \fBgetRecipients\fP () const"
.br
.ti -1c
.RI "\fBCTransactionRef\fP & \fBgetWtx\fP ()"
.br
.ti -1c
.RI "void \fBsetWtx\fP (const \fBCTransactionRef\fP &)"
.br
.ti -1c
.RI "unsigned int \fBgetTransactionSize\fP ()"
.br
.ti -1c
.RI "void \fBsetTransactionFee\fP (const \fBCAmount\fP &newFee)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBgetTransactionFee\fP () const"
.br
.ti -1c
.RI "\fBCAmount\fP \fBgetTotalTransactionAmount\fP () const"
.br
.ti -1c
.RI "void \fBreassignAmounts\fP (int nChangePosRet)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data model for a walletmodel transaction\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBWalletModelTransaction\fP (const QList< \fBSendCoinsRecipient\fP > & recipients)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QList< \fBSendCoinsRecipient\fP > getRecipients () const"

.SS "\fBCAmount\fP getTotalTransactionAmount () const"

.SS "\fBCAmount\fP getTransactionFee () const"

.SS "unsigned int getTransactionSize ()"

.SS "\fBCTransactionRef\fP & getWtx ()"

.SS "void reassignAmounts (int nChangePosRet)"

.SS "void setTransactionFee (const \fBCAmount\fP & newFee)"

.SS "void setWtx (const \fBCTransactionRef\fP & newTx)"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
