.TH "Balance" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Balance
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <receive\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCAmount\fP \fBm_mine_trusted\fP {0}"
.br
.RI "Trusted, at depth=GetBalance\&.min_depth or more\&. "
.ti -1c
.RI "\fBCAmount\fP \fBm_mine_untrusted_pending\fP {0}"
.br
.RI "Untrusted, but in mempool (pending)\&. "
.ti -1c
.RI "\fBCAmount\fP \fBm_mine_immature\fP {0}"
.br
.RI "Immature coinbases in the main chain\&. "
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBCAmount\fP m_mine_immature {0}"

.PP
Immature coinbases in the main chain\&. 
.SS "\fBCAmount\fP m_mine_trusted {0}"

.PP
Trusted, at depth=GetBalance\&.min_depth or more\&. 
.SS "\fBCAmount\fP m_mine_untrusted_pending {0}"

.PP
Untrusted, but in mempool (pending)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
