.TH "WalletModel::SendCoinsReturn" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletModel::SendCoinsReturn
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <walletmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSendCoinsReturn\fP (\fBStatusCode\fP _status=\fBOK\fP, QString _reasonCommitFailed='')"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBStatusCode\fP \fBstatus\fP"
.br
.ti -1c
.RI "QString \fBreasonCommitFailed\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SendCoinsReturn (\fBStatusCode\fP _status = \fR\fBOK\fP\fP, QString _reasonCommitFailed = \fR''\fP)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "QString reasonCommitFailed"

.SS "\fBStatusCode\fP status"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
