.TH "src/qt/walletcontroller.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/walletcontroller.h
.SH SYNOPSIS
.br
.PP
\fR#include <qt/sendcoinsrecipient\&.h>\fP
.br
\fR#include <support/allocators/secure\&.h>\fP
.br
\fR#include <sync\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <map>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <QMessageBox>\fP
.br
\fR#include <QMutex>\fP
.br
\fR#include <QProgressDialog>\fP
.br
\fR#include <QThread>\fP
.br
\fR#include <QTimer>\fP
.br
\fR#include <QString>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWalletController\fP"
.br
.ti -1c
.RI "class \fBWalletControllerActivity\fP"
.br
.ti -1c
.RI "class \fBCreateWalletActivity\fP"
.br
.ti -1c
.RI "class \fBOpenWalletActivity\fP"
.br
.ti -1c
.RI "class \fBLoadWalletsActivity\fP"
.br
.ti -1c
.RI "class \fBRestoreWalletActivity\fP"
.br
.ti -1c
.RI "class \fBMigrateWalletActivity\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinterfaces\fP"
.br
.ti -1c
.RI "namespace \fBfs\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
