.TH "SQliteExecHandler" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQliteExecHandler
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sqlite\&.h>\fP
.PP
Inherited by \fBDbExecBlocker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SQliteExecHandler\fP ()=default"
.br
.ti -1c
.RI "virtual int \fBExec\fP (\fBSQLiteDatabase\fP &database, const std::string &statement)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for executing SQL statements in SQLite databases\&. Methods are virtual so they can be overridden by unit tests testing unusual database conditions\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBSQliteExecHandler\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int Exec (\fBSQLiteDatabase\fP & database, const std::string & statement)\fR [virtual]\fP"

.PP
Reimplemented in \fBDbExecBlocker\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
