.TH "CreatedTransactionResult" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreatedTransactionResult
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <spend\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreatedTransactionResult\fP (\fBCTransactionRef\fP _tx, \fBCAmount\fP _fee, std::optional< unsigned int > _change_pos, const \fBFeeCalculation\fP &_fee_calc)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCTransactionRef\fP \fBtx\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBfee\fP"
.br
.ti -1c
.RI "\fBFeeCalculation\fP \fBfee_calc\fP"
.br
.ti -1c
.RI "std::optional< unsigned int > \fBchange_pos\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CreatedTransactionResult (\fBCTransactionRef\fP _tx, \fBCAmount\fP _fee, std::optional< unsigned int > _change_pos, const \fBFeeCalculation\fP & _fee_calc)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::optional<unsigned int> change_pos"

.SS "\fBCAmount\fP fee"

.SS "\fBFeeCalculation\fP fee_calc"

.SS "\fBCTransactionRef\fP tx"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
