.TH "TxStateConfirmed" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxStateConfirmed \- \fBState\fP of transaction confirmed in a block\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transaction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTxStateConfirmed\fP (const \fBuint256\fP &block_hash, int height, int index)"
.br
.ti -1c
.RI "std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBconfirmed_block_hash\fP"
.br
.ti -1c
.RI "int \fBconfirmed_block_height\fP"
.br
.ti -1c
.RI "int \fBposition_in_block\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBState\fP of transaction confirmed in a block\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TxStateConfirmed (const \fBuint256\fP & block_hash, int height, int index)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string toString () const\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP confirmed_block_hash"

.SS "int confirmed_block_height"

.SS "int position_in_block"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
