.TH "ReserveDestination" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReserveDestination
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wallet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReserveDestination\fP (\fBCWallet\fP *\fBpwallet\fP, \fBOutputType\fP \fBtype\fP)"
.br
.RI "Construct a \fBReserveDestination\fP object\&. This does NOT reserve an address yet\&. "
.ti -1c
.RI "\fBReserveDestination\fP (const ReserveDestination &)=delete"
.br
.ti -1c
.RI "\fBReserveDestination\fP & \fBoperator=\fP (const \fBReserveDestination\fP &)=delete"
.br
.ti -1c
.RI "\fB~ReserveDestination\fP ()"
.br
.RI "Destructor\&. If a key has been reserved and not KeepKey'ed, it will be returned to the keypool\&. "
.ti -1c
.RI "\fButil::Result\fP< \fBCTxDestination\fP > \fBGetReservedDestination\fP (bool internal)"
.br
.RI "Reserve an address\&. "
.ti -1c
.RI "void \fBReturnDestination\fP ()"
.br
.RI "Return reserved address\&. "
.ti -1c
.RI "void \fBKeepDestination\fP ()"
.br
.RI "Keep the address\&. Do not return its key to the keypool when this object goes out of scope\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBCWallet\fP *const \fBpwallet\fP"
.br
.RI "The wallet to reserve from\&. "
.ti -1c
.RI "\fBScriptPubKeyMan\fP * \fBm_spk_man\fP {nullptr}"
.br
.RI "The \fBScriptPubKeyMan\fP to reserve from\&. Based on type when GetReservedDestination is called\&. "
.ti -1c
.RI "\fBOutputType\fP const \fBtype\fP"
.br
.ti -1c
.RI "int64_t \fBnIndex\fP {\-1}"
.br
.RI "The index of the address's key in the keypool\&. "
.ti -1c
.RI "\fBCTxDestination\fP \fBaddress\fP"
.br
.RI "The destination\&. "
.ti -1c
.RI "bool \fBfInternal\fP {false}"
.br
.RI "Whether this is from the internal (change output) keypool\&. "
.in -1c
.SH "Detailed Description"
.PP 
A wrapper to reserve an address from a wallet

.PP
\fBReserveDestination\fP is used to reserve an address\&. It is currently only used inside of CreateTransaction\&.

.PP
Instantiating a \fBReserveDestination\fP does not reserve an address\&. To do so, \fBGetReservedDestination()\fP needs to be called on the object\&. Once an address has been reserved, call \fBKeepDestination()\fP on the \fBReserveDestination\fP object to make sure it is not returned\&. Call \fBReturnDestination()\fP to return the address so it can be reused (for example, if the address was used in a new transaction and that transaction was not completed and needed to be aborted)\&.

.PP
If an address is reserved and \fBKeepDestination()\fP is not called, then the address will be returned when the \fBReserveDestination\fP goes out of scope\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ReserveDestination (\fBCWallet\fP * pwallet, \fBOutputType\fP type)\fR [inline]\fP, \fR [explicit]\fP"

.PP
Construct a \fBReserveDestination\fP object\&. This does NOT reserve an address yet\&. 
.SS "ReserveDestination (const ReserveDestination & )\fR [delete]\fP"

.SS "~\fBReserveDestination\fP ()\fR [inline]\fP"

.PP
Destructor\&. If a key has been reserved and not KeepKey'ed, it will be returned to the keypool\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fButil::Result\fP< \fBCTxDestination\fP > GetReservedDestination (bool internal)"

.PP
Reserve an address\&. 
.SS "void KeepDestination ()"

.PP
Keep the address\&. Do not return its key to the keypool when this object goes out of scope\&. 
.SS "\fBReserveDestination\fP & operator= (const \fBReserveDestination\fP & )\fR [delete]\fP"

.SS "void ReturnDestination ()"

.PP
Return reserved address\&. 
.SH "Field Documentation"
.PP 
.SS "\fBCTxDestination\fP address\fR [protected]\fP"

.PP
The destination\&. 
.SS "bool fInternal {false}\fR [protected]\fP"

.PP
Whether this is from the internal (change output) keypool\&. 
.SS "\fBScriptPubKeyMan\fP* m_spk_man {nullptr}\fR [protected]\fP"

.PP
The \fBScriptPubKeyMan\fP to reserve from\&. Based on type when GetReservedDestination is called\&. 
.SS "int64_t nIndex {\-1}\fR [protected]\fP"

.PP
The index of the address's key in the keypool\&. 
.SS "const \fBCWallet\fP* const pwallet\fR [protected]\fP"

.PP
The wallet to reserve from\&. 
.SS "\fBOutputType\fP const type\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
