.TH "CKeyMetadata" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CKeyMetadata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <walletdb\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCKeyMetadata\fP ()"
.br
.ti -1c
.RI "\fBCKeyMetadata\fP (int64_t nCreateTime_)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBCKeyMetadata\fP, obj)"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnVersion\fP"
.br
.ti -1c
.RI "int64_t \fBnCreateTime\fP"
.br
.ti -1c
.RI "std::string \fBhdKeypath\fP"
.br
.ti -1c
.RI "\fBCKeyID\fP \fBhd_seed_id\fP"
.br
.ti -1c
.RI "\fBKeyOriginInfo\fP \fBkey_origin\fP"
.br
.ti -1c
.RI "bool \fBhas_key_origin\fP = false"
.br
.RI "Whether the key_origin is useful\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBVERSION_BASIC\fP =1"
.br
.ti -1c
.RI "static const int \fBVERSION_WITH_HDDATA\fP =10"
.br
.ti -1c
.RI "static const int \fBVERSION_WITH_KEY_ORIGIN\fP = 12"
.br
.ti -1c
.RI "static const int \fBCURRENT_VERSION\fP =\fBVERSION_WITH_KEY_ORIGIN\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CKeyMetadata ()\fR [inline]\fP"

.SS "CKeyMetadata (int64_t nCreateTime_)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "SERIALIZE_METHODS (\fBCKeyMetadata\fP , obj )\fR [inline]\fP"

.SS "void SetNull ()\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "const int CURRENT_VERSION =\fBVERSION_WITH_KEY_ORIGIN\fP\fR [static]\fP"

.SS "bool has_key_origin = false"

.PP
Whether the key_origin is useful\&. 
.SS "\fBCKeyID\fP hd_seed_id"

.SS "std::string hdKeypath"

.SS "\fBKeyOriginInfo\fP key_origin"

.SS "int64_t nCreateTime"

.SS "int nVersion"

.SS "const int VERSION_BASIC =1\fR [static]\fP"

.SS "const int VERSION_WITH_HDDATA =10\fR [static]\fP"

.SS "const int VERSION_WITH_KEY_ORIGIN = 12\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
