.TH "LegacyDataSPKM" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LegacyDataSPKM
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scriptpubkeyman\&.h>\fP
.PP
Inherits \fBScriptPubKeyMan\fP, and \fBFillableSigningProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::map< \fBCKeyID\fP, \fBCKeyMetadata\fP > mapKeyMetadata \fBGUARDED_BY\fP (\fBcs_KeyStore\fP)"
.br
.ti -1c
.RI "std::map< \fBCScriptID\fP, \fBCKeyMetadata\fP > m_script_metadata \fBGUARDED_BY\fP (\fBcs_KeyStore\fP)"
.br
.ti -1c
.RI "bool \fBCheckDecryptionKey\fP (const \fBCKeyingMaterial\fP &master_key) override"
.br
.RI "Check that the given decryption key is valid for this \fBScriptPubKeyMan\fP, i\&.e\&. it decrypts all of the keys handled by it\&. "
.ti -1c
.RI "std::unordered_set< \fBCScript\fP, \fBSaltedSipHasher\fP > \fBGetScriptPubKeys\fP () const override"
.br
.ti -1c
.RI "std::unique_ptr< \fBSigningProvider\fP > \fBGetSolvingProvider\fP (const \fBCScript\fP &\fBscript\fP) const override"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetID\fP () const override"
.br
.ti -1c
.RI "bool \fBHaveKey\fP (const \fBCKeyID\fP &address) const override"
.br
.ti -1c
.RI "bool \fBGetKey\fP (const \fBCKeyID\fP &address, \fBCKey\fP &keyOut) const override"
.br
.ti -1c
.RI "bool \fBGetPubKey\fP (const \fBCKeyID\fP &address, \fBCPubKey\fP &vchPubKeyOut) const override"
.br
.ti -1c
.RI "bool \fBGetKeyOrigin\fP (const \fBCKeyID\fP &keyid, \fBKeyOriginInfo\fP &info) const override"
.br
.ti -1c
.RI "virtual void \fBLoadKeyMetadata\fP (const \fBCKeyID\fP &keyID, const \fBCKeyMetadata\fP &metadata)"
.br
.RI "Load metadata (used by LoadWallet)\&. "
.ti -1c
.RI "virtual void \fBLoadScriptMetadata\fP (const \fBCScriptID\fP &script_id, const \fBCKeyMetadata\fP &metadata)"
.br
.ti -1c
.RI "bool \fBLoadWatchOnly\fP (const \fBCScript\fP &dest)"
.br
.RI "Adds a watch-only address to the store, without saving it to disk (used by LoadWallet)\&. "
.ti -1c
.RI "bool \fBHaveWatchOnly\fP (const \fBCScript\fP &dest) const"
.br
.RI "Returns whether the watch-only script is in the wallet\&. "
.ti -1c
.RI "bool \fBLoadKey\fP (const \fBCKey\fP &key, const \fBCPubKey\fP &pubkey)"
.br
.RI "Adds a key to the store, without saving it to disk (used by LoadWallet)\&. "
.ti -1c
.RI "bool \fBLoadCryptedKey\fP (const \fBCPubKey\fP &vchPubKey, const std::vector< unsigned char > &vchCryptedSecret, bool checksum_valid)"
.br
.RI "Adds an encrypted key to the store, without saving it to disk (used by LoadWallet)\&. "
.ti -1c
.RI "bool \fBLoadCScript\fP (const \fBCScript\fP &redeemScript)"
.br
.RI "Adds a \fBCScript\fP to the store\&. "
.ti -1c
.RI "void \fBLoadHDChain\fP (const \fBCHDChain\fP &chain)"
.br
.RI "Load a HD chain model (used by LoadWallet)\&. "
.ti -1c
.RI "void \fBAddInactiveHDChain\fP (const \fBCHDChain\fP &chain)"
.br
.ti -1c
.RI "const \fBCHDChain\fP & \fBGetHDChain\fP () const"
.br
.ti -1c
.RI "bool \fBGetWatchPubKey\fP (const \fBCKeyID\fP &address, \fBCPubKey\fP &pubkey_out) const"
.br
.RI "Fetches a pubkey from mapWatchKeys if it exists there\&. "
.ti -1c
.RI "std::unordered_set< \fBCScript\fP, \fBSaltedSipHasher\fP > \fBGetNotMineScriptPubKeys\fP () const"
.br
.ti -1c
.RI "std::optional< \fBMigrationData\fP > \fBMigrateToDescriptor\fP ()"
.br
.ti -1c
.RI "bool \fBDeleteRecordsWithDB\fP (\fBWalletBatch\fP &batch)"
.br
.ti -1c
.RI "\fBScriptPubKeyMan\fP (\fBWalletStorage\fP &storage)"
.br
.in -1c

Public Member Functions inherited from \fBScriptPubKeyMan\fP
.in +1c
.ti -1c
.RI "\fBScriptPubKeyMan\fP (\fBWalletStorage\fP &storage)"
.br
.ti -1c
.RI "virtual \fB~ScriptPubKeyMan\fP ()=default"
.br
.ti -1c
.RI "virtual \fButil::Result\fP< \fBCTxDestination\fP > \fBGetNewDestination\fP (const \fBOutputType\fP type)"
.br
.ti -1c
.RI "virtual bool \fBEncrypt\fP (const \fBCKeyingMaterial\fP &master_key, \fBWalletBatch\fP *batch)"
.br
.ti -1c
.RI "virtual \fButil::Result\fP< \fBCTxDestination\fP > \fBGetReservedDestination\fP (const \fBOutputType\fP type, bool internal, int64_t &index)"
.br
.ti -1c
.RI "virtual void \fBKeepDestination\fP (int64_t index, const \fBOutputType\fP &type)"
.br
.ti -1c
.RI "virtual void \fBReturnDestination\fP (int64_t index, bool internal, const \fBCTxDestination\fP &addr)"
.br
.ti -1c
.RI "virtual bool \fBTopUp\fP (unsigned int size=0)"
.br
.ti -1c
.RI "virtual std::vector< \fBWalletDestination\fP > \fBMarkUnusedAddresses\fP (const \fBCScript\fP &\fBscript\fP)"
.br
.ti -1c
.RI "virtual bool \fBIsHDEnabled\fP () const"
.br
.ti -1c
.RI "virtual bool \fBCanGetAddresses\fP (bool internal=false) const"
.br
.ti -1c
.RI "virtual bool \fBHavePrivateKeys\fP () const"
.br
.ti -1c
.RI "virtual bool \fBHaveCryptedKeys\fP () const"
.br
.ti -1c
.RI "virtual void \fBRewriteDB\fP ()"
.br
.RI "The action to do when the \fBDB\fP needs rewrite\&. "
.ti -1c
.RI "virtual unsigned int \fBGetKeyPoolSize\fP () const"
.br
.ti -1c
.RI "virtual int64_t \fBGetTimeFirstKey\fP () const"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBCKeyMetadata\fP > \fBGetMetadata\fP (const \fBCTxDestination\fP &dest) const"
.br
.ti -1c
.RI "virtual bool \fBSignTransaction\fP (\fBCMutableTransaction\fP &tx, const std::map< \fBCOutPoint\fP, \fBCoin\fP > &coins, int sighash, std::map< int, \fBbilingual_str\fP > &input_errors) const"
.br
.ti -1c
.RI "virtual \fBSigningResult\fP \fBSignMessage\fP (const std::string &message, const \fBPKHash\fP &pkhash, std::string &str_sig) const"
.br
.ti -1c
.RI "virtual std::optional< \fBcommon::PSBTError\fP > \fBFillPSBT\fP (\fBPartiallySignedTransaction\fP &psbt, const \fBPrecomputedTransactionData\fP &txdata, std::optional< int > sighash_type=std::nullopt, bool sign=true, bool bip32derivs=false, int *n_signed=nullptr, bool finalize=true) const"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Params> void \fBWalletLogPrintf\fP (\fButil::ConstevalFormatString\fP< sizeof\&.\&.\&.(\fBParams\fP)> wallet_fmt, const \fBParams\fP &\&.\&.\&. params) const"
.br
.in -1c

Public Member Functions inherited from \fBFillableSigningProvider\fP
.in +1c
.ti -1c
.RI "virtual bool \fBAddKeyPubKey\fP (const \fBCKey\fP &key, const \fBCPubKey\fP &pubkey)"
.br
.ti -1c
.RI "virtual bool \fBAddKey\fP (const \fBCKey\fP &key)"
.br
.ti -1c
.RI "virtual std::set< \fBCKeyID\fP > \fBGetKeys\fP () const"
.br
.ti -1c
.RI "virtual bool \fBAddCScript\fP (const \fBCScript\fP &redeemScript)"
.br
.ti -1c
.RI "virtual bool \fBHaveCScript\fP (const \fBCScriptID\fP &hash) const override"
.br
.ti -1c
.RI "virtual std::set< \fBCScriptID\fP > \fBGetCScripts\fP () const"
.br
.ti -1c
.RI "virtual bool \fBGetCScript\fP (const \fBCScriptID\fP &hash, \fBCScript\fP &redeemScriptOut) const override"
.br
.in -1c

Public Member Functions inherited from \fBSigningProvider\fP
.in +1c
.ti -1c
.RI "virtual \fB~SigningProvider\fP ()=default"
.br
.ti -1c
.RI "virtual bool \fBGetTaprootSpendData\fP (const \fBXOnlyPubKey\fP &output_key, \fBTaprootSpendData\fP &spenddata) const"
.br
.ti -1c
.RI "virtual bool \fBGetTaprootBuilder\fP (const \fBXOnlyPubKey\fP &output_key, \fBTaprootBuilder\fP &builder) const"
.br
.ti -1c
.RI "virtual std::vector< \fBCPubKey\fP > \fBGetMuSig2ParticipantPubkeys\fP (const \fBCPubKey\fP &pubkey) const"
.br
.ti -1c
.RI "virtual std::map< \fBCPubKey\fP, std::vector< \fBCPubKey\fP > > \fBGetAllMuSig2ParticipantPubkeys\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetMuSig2SecNonce\fP (const \fBuint256\fP &id, \fBMuSig2SecNonce\fP &&\fBnonce\fP) const"
.br
.ti -1c
.RI "virtual std::optional< std::reference_wrapper< \fBMuSig2SecNonce\fP > > \fBGetMuSig2SecNonce\fP (const \fBuint256\fP &session_id) const"
.br
.ti -1c
.RI "virtual void \fBDeleteMuSig2Session\fP (const \fBuint256\fP &session_id) const"
.br
.ti -1c
.RI "bool \fBGetKeyByXOnly\fP (const \fBXOnlyPubKey\fP &pubkey, \fBCKey\fP &key) const"
.br
.ti -1c
.RI "bool \fBGetPubKeyByXOnly\fP (const \fBXOnlyPubKey\fP &pubkey, \fBCPubKey\fP &out) const"
.br
.ti -1c
.RI "bool \fBGetKeyOriginByXOnly\fP (const \fBXOnlyPubKey\fP &pubkey, \fBKeyOriginInfo\fP &info) const"
.br
.in -1c
.SS "Additional Inherited Members"


Data Fields inherited from \fBScriptPubKeyMan\fP
.in +1c
.ti -1c
.RI "boost::signals2::signal< void()> \fBNotifyCanGetAddressesChanged\fP"
.br
.ti -1c
.RI "boost::signals2::signal< void(const \fBScriptPubKeyMan\fP *spkm, int64_t new_birth_time)> \fBNotifyFirstKeyTimeChanged\fP"
.br
.in -1c

Data Fields inherited from \fBFillableSigningProvider\fP
.in +1c
.ti -1c
.RI "\fBRecursiveMutex\fP \fBcs_KeyStore\fP"
.br
.in -1c

Protected Types inherited from \fBFillableSigningProvider\fP
.in +1c
.ti -1c
.RI "using \fBKeyMap\fP = std::map<\fBCKeyID\fP, \fBCKey\fP>"
.br
.ti -1c
.RI "using \fBScriptMap\fP = std::map<\fBCScriptID\fP, \fBCScript\fP>"
.br
.in -1c

Protected Member Functions inherited from \fBFillableSigningProvider\fP
.in +1c
.ti -1c
.RI "\fBKeyMap\fP mapKeys \fBGUARDED_BY\fP (\fBcs_KeyStore\fP)"
.br
.ti -1c
.RI "\fBScriptMap\fP mapScripts \fBGUARDED_BY\fP (\fBcs_KeyStore\fP)"
.br
.ti -1c
.RI "void \fBImplicitlyLearnRelatedKeyScripts\fP (const \fBCPubKey\fP &pubkey) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(\fBcs_KeyStore\fP)"
.br
.in -1c

Protected Attributes inherited from \fBScriptPubKeyMan\fP
.in +1c
.ti -1c
.RI "\fBWalletStorage\fP & \fBm_storage\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AddInactiveHDChain (const \fBCHDChain\fP & chain)"

.SS "bool CheckDecryptionKey (const \fBCKeyingMaterial\fP & master_key)\fR [override]\fP, \fR [virtual]\fP"

.PP
Check that the given decryption key is valid for this \fBScriptPubKeyMan\fP, i\&.e\&. it decrypts all of the keys handled by it\&. 
.PP
Reimplemented from \fBScriptPubKeyMan\fP\&.
.SS "bool DeleteRecordsWithDB (\fBWalletBatch\fP & batch)"
Delete all the records of this LegacyScriptPubKeyMan from disk 
.SS "const \fBCHDChain\fP & GetHDChain () const\fR [inline]\fP"

.SS "\fBuint256\fP GetID () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBScriptPubKeyMan\fP\&.
.SS "bool GetKey (const \fBCKeyID\fP & address, \fBCKey\fP & keyOut) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBFillableSigningProvider\fP\&.
.SS "bool GetKeyOrigin (const \fBCKeyID\fP & keyid, \fBKeyOriginInfo\fP & info) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBSigningProvider\fP\&.
.SS "std::unordered_set< \fBCScript\fP, \fBSaltedSipHasher\fP > GetNotMineScriptPubKeys () const"
Retrieves scripts that were imported by bugs into the legacy spkm and are simply invalid, such as a sh(sh(pkh())) script, or not watched\&. 
.SS "bool GetPubKey (const \fBCKeyID\fP & address, \fBCPubKey\fP & vchPubKeyOut) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBFillableSigningProvider\fP\&.
.SS "std::unordered_set< \fBCScript\fP, \fBSaltedSipHasher\fP > GetScriptPubKeys () const\fR [override]\fP, \fR [virtual]\fP"
Returns a set of all the scriptPubKeys that this \fBScriptPubKeyMan\fP watches 
.PP
Reimplemented from \fBScriptPubKeyMan\fP\&.
.SS "std::unique_ptr< \fBSigningProvider\fP > GetSolvingProvider (const \fBCScript\fP & script) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBScriptPubKeyMan\fP\&.
.SS "bool GetWatchPubKey (const \fBCKeyID\fP & address, \fBCPubKey\fP & pubkey_out) const"

.PP
Fetches a pubkey from mapWatchKeys if it exists there\&. 
.SS "std::map< \fBCScriptID\fP, \fBCKeyMetadata\fP > m_script_metadata GUARDED_BY (\fBcs_KeyStore\fP )"

.SS "std::map< \fBCKeyID\fP, \fBCKeyMetadata\fP > mapKeyMetadata GUARDED_BY (\fBcs_KeyStore\fP )"

.SS "bool HaveKey (const \fBCKeyID\fP & address) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBFillableSigningProvider\fP\&.
.SS "bool HaveWatchOnly (const \fBCScript\fP & dest) const"

.PP
Returns whether the watch-only script is in the wallet\&. 
.SS "bool LoadCryptedKey (const \fBCPubKey\fP & vchPubKey, const std::vector< unsigned char > & vchCryptedSecret, bool checksum_valid)"

.PP
Adds an encrypted key to the store, without saving it to disk (used by LoadWallet)\&. 
.SS "bool LoadCScript (const \fBCScript\fP & redeemScript)"

.PP
Adds a \fBCScript\fP to the store\&. 
.SS "void LoadHDChain (const \fBCHDChain\fP & chain)"

.PP
Load a HD chain model (used by LoadWallet)\&. 
.SS "bool LoadKey (const \fBCKey\fP & key, const \fBCPubKey\fP & pubkey)"

.PP
Adds a key to the store, without saving it to disk (used by LoadWallet)\&. 
.SS "void LoadKeyMetadata (const \fBCKeyID\fP & keyID, const \fBCKeyMetadata\fP & metadata)\fR [virtual]\fP"

.PP
Load metadata (used by LoadWallet)\&. 
.SS "void LoadScriptMetadata (const \fBCScriptID\fP & script_id, const \fBCKeyMetadata\fP & metadata)\fR [virtual]\fP"

.SS "bool LoadWatchOnly (const \fBCScript\fP & dest)"

.PP
Adds a watch-only address to the store, without saving it to disk (used by LoadWallet)\&. 
.SS "std::optional< \fBMigrationData\fP > MigrateToDescriptor ()"
Get the DescriptorScriptPubKeyMans (with private keys) that have the same scriptPubKeys as this LegacyScriptPubKeyMan\&. Does not modify this \fBScriptPubKeyMan\fP\&. 
.SS "ScriptPubKeyMan (\fBWalletStorage\fP & storage)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
