.TH "SignatureWeights" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SignatureWeights
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <feebumper\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddSigWeight\fP (const size_t weight, const \fBSigVersion\fP sigversion)"
.br
.ti -1c
.RI "int64_t \fBGetWeightDiffToMax\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AddSigWeight (const size_t weight, const \fBSigVersion\fP sigversion)\fR [inline]\fP"

.SS "int64_t GetWeightDiffToMax () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
