.TH "InternalRecord" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InternalRecord
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInternalRecord\fP (const \fBRecordHeader\fP &header)"
.br
.ti -1c
.RI "\fBInternalRecord\fP ()=delete"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBRecordHeader\fP \fBm_header\fP"
.br
.ti -1c
.RI "uint8_t \fBunused\fP"
.br
.ti -1c
.RI "uint32_t \fBpage_num\fP"
.br
.ti -1c
.RI "uint32_t \fBrecords\fP"
.br
.ti -1c
.RI "std::vector< std::byte > \fBdata\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr size_t \fBFIXED_SIZE\fP = 9"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for records representing internal nodes of the BTree\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InternalRecord (const \fBRecordHeader\fP & header)\fR [inline]\fP"

.SS "InternalRecord ()\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::vector<std::byte> data"

.SS "size_t FIXED_SIZE = 9\fR [static]\fP, \fR [constexpr]\fP"

.SS "\fBRecordHeader\fP m_header"

.SS "uint32_t page_num"

.SS "uint32_t records"

.SS "uint8_t unused"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
