.TH "RecordHeader" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecordHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRecordHeader\fP (bool \fBother_endian\fP)"
.br
.ti -1c
.RI "\fBRecordHeader\fP ()=delete"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBlen\fP"
.br
.ti -1c
.RI "\fBRecordType\fP \fBtype\fP"
.br
.ti -1c
.RI "bool \fBdeleted\fP"
.br
.ti -1c
.RI "bool \fBother_endian\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr size_t \fBSIZE\fP = 3"
.br
.in -1c
.SH "Detailed Description"
.PP 
General class for records in a BDB BTree database\&. Contains common fields\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RecordHeader (bool other_endian)\fR [inline]\fP"

.SS "RecordHeader ()\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "bool deleted"

.SS "uint16_t len"

.SS "bool other_endian"

.SS "size_t SIZE = 3\fR [static]\fP, \fR [constexpr]\fP"

.SS "\fBRecordType\fP type"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
