.TH "InternalPage" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InternalPage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInternalPage\fP (const \fBPageHeader\fP &header)"
.br
.ti -1c
.RI "\fBInternalPage\fP ()=delete"
.br
.ti -1c
.RI "template<typename Stream> void \fBUnserialize\fP (Stream &s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPageHeader\fP \fBm_header\fP"
.br
.ti -1c
.RI "std::vector< uint16_t > \fBindexes\fP"
.br
.ti -1c
.RI "std::vector< \fBInternalRecord\fP > \fBrecords\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A page of records in the database 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InternalPage (const \fBPageHeader\fP & header)\fR [inline]\fP"

.SS "InternalPage ()\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream> void Unserialize (Stream & s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::vector<uint16_t> indexes"

.SS "\fBPageHeader\fP m_header"

.SS "std::vector<\fBInternalRecord\fP> records"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
