.TH "WalletInit" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletInit
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWalletInitInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBHasWalletSupport\fP () const override"
.br
.RI "Was the wallet component compiled in\&. "
.ti -1c
.RI "void \fBAddWalletOptions\fP (\fBArgsManager\fP &argsman) const override"
.br
.RI "Return the wallets help message\&. "
.ti -1c
.RI "bool \fBParameterInteraction\fP () const override"
.br
.RI "Wallets parameter interaction\&. "
.ti -1c
.RI "void \fBConstruct\fP (\fBNodeContext\fP &\fBnode\fP) const override"
.br
.RI "Add wallets that should be opened to list of chain clients\&. "
.in -1c

Public Member Functions inherited from \fBWalletInitInterface\fP
.in +1c
.ti -1c
.RI "virtual \fB~WalletInitInterface\fP ()=default"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AddWalletOptions (\fBArgsManager\fP & argsman) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Return the wallets help message\&. 
.PP
Implements \fBWalletInitInterface\fP\&.
.SS "void Construct (\fBNodeContext\fP & node) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Add wallets that should be opened to list of chain clients\&. 
.PP
Implements \fBWalletInitInterface\fP\&.
.SS "bool HasWalletSupport () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Was the wallet component compiled in\&. 
.PP
Implements \fBWalletInitInterface\fP\&.
.SS "bool ParameterInteraction () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Wallets parameter interaction\&. 
.PP
Implements \fBWalletInitInterface\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
