.TH "WalletBalances" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletBalances \- Collection of wallet balances\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wallet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBbalanceChanged\fP (const \fBWalletBalances\fP &prev) const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCAmount\fP \fBbalance\fP = 0"
.br
.ti -1c
.RI "\fBCAmount\fP \fBunconfirmed_balance\fP = 0"
.br
.ti -1c
.RI "\fBCAmount\fP \fBimmature_balance\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Collection of wallet balances\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool balanceChanged (const \fBWalletBalances\fP & prev) const\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBCAmount\fP balance = 0"

.SS "\fBCAmount\fP immature_balance = 0"

.SS "\fBCAmount\fP unconfirmed_balance = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
