.TH "TxStateBlockConflicted" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxStateBlockConflicted \- \fBState\fP of rejected transaction that conflicts with a confirmed block\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transaction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTxStateBlockConflicted\fP (const \fBuint256\fP &block_hash, int height)"
.br
.ti -1c
.RI "std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBconflicting_block_hash\fP"
.br
.ti -1c
.RI "int \fBconflicting_block_height\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBState\fP of rejected transaction that conflicts with a confirmed block\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TxStateBlockConflicted (const \fBuint256\fP & block_hash, int height)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string toString () const\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP conflicting_block_hash"

.SS "int conflicting_block_height"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
