.TH "CoinFilterParams" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoinFilterParams
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <spend\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCAmount\fP \fBmin_amount\fP {1}"
.br
.ti -1c
.RI "\fBCAmount\fP \fBmax_amount\fP {MAX_MONEY}"
.br
.ti -1c
.RI "\fBCAmount\fP \fBmin_sum_amount\fP {MAX_MONEY}"
.br
.ti -1c
.RI "uint64_t \fBmax_count\fP {0}"
.br
.ti -1c
.RI "bool \fBinclude_immature_coinbase\fP {false}"
.br
.ti -1c
.RI "bool \fBskip_locked\fP {true}"
.br
.ti -1c
.RI "bool \fBcheck_version_trucness\fP {true}"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool check_version_trucness {true}"

.SS "bool include_immature_coinbase {false}"

.SS "\fBCAmount\fP max_amount {MAX_MONEY}"

.SS "uint64_t max_count {0}"

.SS "\fBCAmount\fP min_amount {1}"

.SS "\fBCAmount\fP min_sum_amount {MAX_MONEY}"

.SS "bool skip_locked {true}"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
