.TH "src/wallet/wallettool.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/wallettool.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.ti -1c
.RI "namespace \fBwallet::WalletTool\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBExecuteWalletToolFunc\fP (const \fBArgsManager\fP &\fBargs\fP, const std::string &\fBcommand\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
