.TH "CCoinControl" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCoinControl
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <coincontrol\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCCoinControl\fP ()"
.br
.ti -1c
.RI "bool \fBHasSelected\fP () const"
.br
.ti -1c
.RI "bool \fBIsSelected\fP (const \fBCOutPoint\fP &outpoint) const"
.br
.ti -1c
.RI "bool \fBIsExternalSelected\fP (const \fBCOutPoint\fP &outpoint) const"
.br
.ti -1c
.RI "std::optional< \fBCTxOut\fP > \fBGetExternalOutput\fP (const \fBCOutPoint\fP &outpoint) const"
.br
.ti -1c
.RI "\fBPreselectedInput\fP & \fBSelect\fP (const \fBCOutPoint\fP &outpoint)"
.br
.ti -1c
.RI "void \fBUnSelect\fP (const \fBCOutPoint\fP &outpoint)"
.br
.ti -1c
.RI "void \fBUnSelectAll\fP ()"
.br
.ti -1c
.RI "std::vector< \fBCOutPoint\fP > \fBListSelected\fP () const"
.br
.ti -1c
.RI "void \fBSetInputWeight\fP (const \fBCOutPoint\fP &outpoint, int64_t weight)"
.br
.ti -1c
.RI "std::optional< int64_t > \fBGetInputWeight\fP (const \fBCOutPoint\fP &outpoint) const"
.br
.ti -1c
.RI "std::optional< uint32_t > \fBGetSequence\fP (const \fBCOutPoint\fP &outpoint) const"
.br
.ti -1c
.RI "std::pair< std::optional< \fBCScript\fP >, std::optional< \fBCScriptWitness\fP > > \fBGetScripts\fP (const \fBCOutPoint\fP &outpoint) const"
.br
.ti -1c
.RI "bool \fBHasSelectedOrder\fP () const"
.br
.ti -1c
.RI "std::optional< unsigned int > \fBGetSelectionPos\fP (const \fBCOutPoint\fP &outpoint) const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCTxDestination\fP \fBdestChange\fP = \fBCNoDestination\fP()"
.br
.RI "Custom change destination, if not set an address is generated\&. "
.ti -1c
.RI "std::optional< \fBOutputType\fP > \fBm_change_type\fP"
.br
.RI "Override the default change type if set, ignored if destChange is set\&. "
.ti -1c
.RI "bool \fBm_include_unsafe_inputs\fP = false"
.br
.RI "If false, only safe inputs will be used\&. "
.ti -1c
.RI "bool \fBm_allow_other_inputs\fP = true"
.br
.ti -1c
.RI "bool \fBfOverrideFeeRate\fP = false"
.br
.RI "Override automatic min/max checks on fee, m_feerate must be set if true\&. "
.ti -1c
.RI "std::optional< \fBCFeeRate\fP > \fBm_feerate\fP"
.br
.RI "Override the wallet's m_pay_tx_fee if set\&. "
.ti -1c
.RI "std::optional< unsigned int > \fBm_confirm_target\fP"
.br
.RI "Override the default confirmation target if set\&. "
.ti -1c
.RI "std::optional< bool > \fBm_signal_bip125_rbf\fP"
.br
.RI "Override the wallet's m_signal_rbf if set\&. "
.ti -1c
.RI "bool \fBm_avoid_partial_spends\fP = DEFAULT_AVOIDPARTIALSPENDS"
.br
.RI "Avoid partial use of funds sent to a given address\&. "
.ti -1c
.RI "bool \fBm_avoid_address_reuse\fP = false"
.br
.RI "Forbids inclusion of dirty (previously used) addresses\&. "
.ti -1c
.RI "\fBFeeEstimateMode\fP \fBm_fee_mode\fP = \fBFeeEstimateMode::UNSET\fP"
.br
.RI "Fee estimation mode to control arguments to estimateSmartFee\&. "
.ti -1c
.RI "int \fBm_min_depth\fP = \fBDEFAULT_MIN_DEPTH\fP"
.br
.RI "Minimum chain depth value for coin availability\&. "
.ti -1c
.RI "int \fBm_max_depth\fP = \fBDEFAULT_MAX_DEPTH\fP"
.br
.RI "Maximum chain depth value for coin availability\&. "
.ti -1c
.RI "\fBFlatSigningProvider\fP \fBm_external_provider\fP"
.br
.RI "\fBSigningProvider\fP that has pubkeys and scripts to do spend size estimation for external inputs\&. "
.ti -1c
.RI "uint32_t \fBm_version\fP = \fBDEFAULT_WALLET_TX_VERSION\fP"
.br
.RI "Version\&. "
.ti -1c
.RI "std::optional< uint32_t > \fBm_locktime\fP"
.br
.RI "Locktime\&. "
.ti -1c
.RI "std::optional< int > \fBm_max_tx_weight\fP {std::nullopt}"
.br
.RI "Caps weight of resulting tx\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBCoin\fP Control Features\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCCoinControl\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "std::optional< \fBCTxOut\fP > GetExternalOutput (const \fBCOutPoint\fP & outpoint) const"
Returns the external output for the given outpoint if it exists\&. 
.SS "std::optional< int64_t > GetInputWeight (const \fBCOutPoint\fP & outpoint) const"
Returns the input weight\&. 
.SS "std::pair< std::optional< \fBCScript\fP >, std::optional< \fBCScriptWitness\fP > > GetScripts (const \fBCOutPoint\fP & outpoint) const"
Retrieves the scriptSig and scriptWitness for an input\&. 
.SS "std::optional< unsigned int > GetSelectionPos (const \fBCOutPoint\fP & outpoint) const\fR [inline]\fP"

.SS "std::optional< uint32_t > GetSequence (const \fBCOutPoint\fP & outpoint) const"
Retrieve the sequence for an input 
.SS "bool HasSelected () const"
Returns true if there are pre-selected inputs\&. 
.SS "bool HasSelectedOrder () const\fR [inline]\fP"

.SS "bool IsExternalSelected (const \fBCOutPoint\fP & outpoint) const"
Returns true if the given output is selected as an external input\&. 
.SS "bool IsSelected (const \fBCOutPoint\fP & outpoint) const"
Returns true if the given output is pre-selected\&. 
.SS "std::vector< \fBCOutPoint\fP > ListSelected () const"
List the selected inputs\&. 
.SS "\fBPreselectedInput\fP & Select (const \fBCOutPoint\fP & outpoint)"
Lock-in the given output for spending\&. The output will be included in the transaction even if it's not the most optimal choice\&. 
.SS "void SetInputWeight (const \fBCOutPoint\fP & outpoint, int64_t weight)"
Set an input's weight\&. 
.SS "void UnSelect (const \fBCOutPoint\fP & outpoint)"
Unselects the given output\&. 
.SS "void UnSelectAll ()"
Unselects all outputs\&. 
.SH "Field Documentation"
.PP 
.SS "\fBCTxDestination\fP destChange = \fBCNoDestination\fP()"

.PP
Custom change destination, if not set an address is generated\&. 
.SS "bool fOverrideFeeRate = false"

.PP
Override automatic min/max checks on fee, m_feerate must be set if true\&. 
.SS "bool m_allow_other_inputs = true"
If true, the selection process can add extra unselected inputs from the wallet while requires all selected inputs be used 
.SS "bool m_avoid_address_reuse = false"

.PP
Forbids inclusion of dirty (previously used) addresses\&. 
.SS "bool m_avoid_partial_spends = DEFAULT_AVOIDPARTIALSPENDS"

.PP
Avoid partial use of funds sent to a given address\&. 
.SS "std::optional<\fBOutputType\fP> m_change_type"

.PP
Override the default change type if set, ignored if destChange is set\&. 
.SS "std::optional<unsigned int> m_confirm_target"

.PP
Override the default confirmation target if set\&. 
.SS "\fBFlatSigningProvider\fP m_external_provider"

.PP
\fBSigningProvider\fP that has pubkeys and scripts to do spend size estimation for external inputs\&. 
.SS "\fBFeeEstimateMode\fP m_fee_mode = \fBFeeEstimateMode::UNSET\fP"

.PP
Fee estimation mode to control arguments to estimateSmartFee\&. 
.SS "std::optional<\fBCFeeRate\fP> m_feerate"

.PP
Override the wallet's m_pay_tx_fee if set\&. 
.SS "bool m_include_unsafe_inputs = false"

.PP
If false, only safe inputs will be used\&. 
.SS "std::optional<uint32_t> m_locktime"

.PP
Locktime\&. 
.SS "int m_max_depth = \fBDEFAULT_MAX_DEPTH\fP"

.PP
Maximum chain depth value for coin availability\&. 
.SS "std::optional<int> m_max_tx_weight {std::nullopt}"

.PP
Caps weight of resulting tx\&. 
.SS "int m_min_depth = \fBDEFAULT_MIN_DEPTH\fP"

.PP
Minimum chain depth value for coin availability\&. 
.SS "std::optional<bool> m_signal_bip125_rbf"

.PP
Override the wallet's m_signal_rbf if set\&. 
.SS "uint32_t m_version = \fBDEFAULT_WALLET_TX_VERSION\fP"

.PP
Version\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
