.TH "CCrypter" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCrypter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <crypter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBSetKeyFromPassphrase\fP (const \fBSecureString\fP &key_data, std::span< const unsigned char > salt, const unsigned int rounds, const unsigned int derivation_method)"
.br
.ti -1c
.RI "bool \fBEncrypt\fP (const \fBCKeyingMaterial\fP &vchPlaintext, std::vector< unsigned char > &vchCiphertext) const"
.br
.ti -1c
.RI "bool \fBDecrypt\fP (std::span< const unsigned char > ciphertext, \fBCKeyingMaterial\fP &plaintext) const"
.br
.ti -1c
.RI "bool \fBSetKey\fP (const \fBCKeyingMaterial\fP &new_key, std::span< const unsigned char > new_iv)"
.br
.ti -1c
.RI "void \fBCleanKey\fP ()"
.br
.ti -1c
.RI "\fBCCrypter\fP ()"
.br
.ti -1c
.RI "\fB~CCrypter\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBwallet_crypto_tests::TestCrypter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Encryption/decryption context with key information 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CCrypter ()\fR [inline]\fP"

.SS "~\fBCCrypter\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CleanKey ()\fR [inline]\fP"

.SS "bool Decrypt (std::span< const unsigned char > ciphertext, \fBCKeyingMaterial\fP & plaintext) const"

.SS "bool Encrypt (const \fBCKeyingMaterial\fP & vchPlaintext, std::vector< unsigned char > & vchCiphertext) const"

.SS "bool SetKey (const \fBCKeyingMaterial\fP & new_key, std::span< const unsigned char > new_iv)"

.SS "bool SetKeyFromPassphrase (const \fBSecureString\fP & key_data, std::span< const unsigned char > salt, const unsigned int rounds, const unsigned int derivation_method)"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class wallet_crypto_tests::TestCrypter\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
