.TH "MockableBatch" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MockableBatch
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <util\&.h>\fP
.PP
Inherits \fBDatabaseBatch\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMockableBatch\fP (\fBMockableData\fP &records, bool pass)"
.br
.ti -1c
.RI "\fB~MockableBatch\fP ()=default"
.br
.ti -1c
.RI "void \fBClose\fP () override"
.br
.ti -1c
.RI "std::unique_ptr< \fBDatabaseCursor\fP > \fBGetNewCursor\fP () override"
.br
.ti -1c
.RI "std::unique_ptr< \fBDatabaseCursor\fP > \fBGetNewPrefixCursor\fP (std::span< const std::byte > \fBprefix\fP) override"
.br
.ti -1c
.RI "bool \fBTxnBegin\fP () override"
.br
.ti -1c
.RI "bool \fBTxnCommit\fP () override"
.br
.ti -1c
.RI "bool \fBTxnAbort\fP () override"
.br
.ti -1c
.RI "bool \fBHasActiveTxn\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBDatabaseBatch\fP
.in +1c
.ti -1c
.RI "\fBDatabaseBatch\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~DatabaseBatch\fP ()=default"
.br
.ti -1c
.RI "\fBDatabaseBatch\fP (const DatabaseBatch &)=delete"
.br
.ti -1c
.RI "\fBDatabaseBatch\fP & \fBoperator=\fP (const \fBDatabaseBatch\fP &)=delete"
.br
.ti -1c
.RI "template<typename K, typename \fBT\fP> bool \fBRead\fP (const K &key, \fBT\fP &value)"
.br
.ti -1c
.RI "template<typename K, typename \fBT\fP> bool \fBWrite\fP (const K &key, const \fBT\fP &value, bool fOverwrite=true)"
.br
.ti -1c
.RI "template<typename K> bool \fBErase\fP (const K &key)"
.br
.ti -1c
.RI "template<typename K> bool \fBExists\fP (const K &key)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MockableBatch (\fBMockableData\fP & records, bool pass)\fR [inline]\fP, \fR [explicit]\fP"

.SS "~\fBMockableBatch\fP ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Close ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBDatabaseBatch\fP\&.
.SS "std::unique_ptr< \fBDatabaseCursor\fP > GetNewCursor ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBDatabaseBatch\fP\&.
.SS "std::unique_ptr< \fBDatabaseCursor\fP > GetNewPrefixCursor (std::span< const std::byte > prefix)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBDatabaseBatch\fP\&.
.SS "bool HasActiveTxn ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBDatabaseBatch\fP\&.
.SS "bool TxnAbort ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBDatabaseBatch\fP\&.
.SS "bool TxnBegin ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBDatabaseBatch\fP\&.
.SS "bool TxnCommit ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBDatabaseBatch\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
