.TH "WalletTests" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletTests
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wallettests\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWalletTests\fP (\fBinterfaces::Node\fP &\fBnode\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBinterfaces::Node\fP & \fBm_node\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBWalletTests\fP (\fBinterfaces::Node\fP & node)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBinterfaces::Node\fP& m_node"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
