.TH "TxStateUnrecognized" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxStateUnrecognized
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transaction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTxStateUnrecognized\fP (const \fBuint256\fP &\fBblock_hash\fP, int \fBindex\fP)"
.br
.ti -1c
.RI "std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBblock_hash\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBState\fP of transaction loaded in an unrecognized state with unexpected hash or index values\&. Treated as inactive (with serialized hash and index values preserved) by default, but may enter another state if transaction is added to the mempool, or confirmed, or abandoned, or found conflicting\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TxStateUnrecognized (const \fBuint256\fP & block_hash, int index)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string toString () const\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBuint256\fP block_hash"

.SS "int index"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
