.TH "CoinsResult" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoinsResult
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <spend\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::vector< \fBCOutput\fP > \fBAll\fP () const"
.br
.ti -1c
.RI "size_t \fBSize\fP () const"
.br
.ti -1c
.RI "size_t \fBTypesCount\fP () const"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBErase\fP (const std::unordered_set< \fBCOutPoint\fP, \fBSaltedOutpointHasher\fP > &coins_to_remove)"
.br
.ti -1c
.RI "void \fBShuffle\fP (\fBFastRandomContext\fP &rng_fast)"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBOutputType\fP type, const \fBCOutput\fP &out)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetTotalAmount\fP ()"
.br
.ti -1c
.RI "std::optional< \fBCAmount\fP > \fBGetEffectiveTotalAmount\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::map< \fBOutputType\fP, std::vector< \fBCOutput\fP > > \fBcoins\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
COutputs available for spending, stored by \fBOutputType\fP\&. This struct is really just a wrapper around \fBOutputType\fP vectors with a convenient method for concatenating and returning all COutputs as one vector\&.

.PP
\fBSize()\fP, \fBClear()\fP, \fBErase()\fP, \fBShuffle()\fP, and \fBAdd()\fP methods are implemented to allow easy interaction with the struct\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Add (\fBOutputType\fP type, const \fBCOutput\fP & out)"

.SS "std::vector< \fBCOutput\fP > All () const"
Concatenate and return all COutputs as one vector 
.SS "void Clear ()"

.SS "void Erase (const std::unordered_set< \fBCOutPoint\fP, \fBSaltedOutpointHasher\fP > & coins_to_remove)"

.SS "std::optional< \fBCAmount\fP > GetEffectiveTotalAmount ()\fR [inline]\fP"

.SS "\fBCAmount\fP GetTotalAmount ()\fR [inline]\fP"

.SS "void Shuffle (\fBFastRandomContext\fP & rng_fast)"

.SS "size_t Size () const"
The following methods are provided so that \fBCoinsResult\fP can mimic a vector, i\&.e\&., methods can work with individual \fBOutputType\fP vectors or on the entire object 
.SS "size_t TypesCount () const\fR [inline]\fP"
Return how many different output types this struct stores 
.SH "Field Documentation"
.PP 
.SS "std::map<\fBOutputType\fP, std::vector<\fBCOutput\fP> > coins"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
