.TH "WalletDescriptor" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletDescriptor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <walletutil\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDeserializeDescriptor\fP (const std::string &str)"
.br
.ti -1c
.RI "\fBSERIALIZE_METHODS\fP (\fBWalletDescriptor\fP, obj)"
.br
.ti -1c
.RI "\fBWalletDescriptor\fP ()=default"
.br
.ti -1c
.RI "\fBWalletDescriptor\fP (std::shared_ptr< \fBDescriptor\fP > \fBdescriptor\fP, uint64_t \fBcreation_time\fP, int32_t \fBrange_start\fP, int32_t \fBrange_end\fP, int32_t \fBnext_index\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBDescriptor\fP > \fBdescriptor\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBid\fP"
.br
.ti -1c
.RI "uint64_t \fBcreation_time\fP = 0"
.br
.ti -1c
.RI "int32_t \fBrange_start\fP = 0"
.br
.ti -1c
.RI "int32_t \fBrange_end\fP = 0"
.br
.ti -1c
.RI "int32_t \fBnext_index\fP = 0"
.br
.ti -1c
.RI "\fBDescriptorCache\fP \fBcache\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDescriptor\fP with some wallet metadata 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBWalletDescriptor\fP ()\fR [default]\fP"

.SS "\fBWalletDescriptor\fP (std::shared_ptr< \fBDescriptor\fP > descriptor, uint64_t creation_time, int32_t range_start, int32_t range_end, int32_t next_index)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void DeserializeDescriptor (const std::string & str)\fR [inline]\fP"

.SS "SERIALIZE_METHODS (\fBWalletDescriptor\fP , obj )\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBDescriptorCache\fP cache"

.SS "uint64_t creation_time = 0"

.SS "std::shared_ptr<\fBDescriptor\fP> descriptor"

.SS "\fBuint256\fP id"

.SS "int32_t next_index = 0"

.SS "int32_t range_end = 0"

.SS "int32_t range_start = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
