.TH "SQLiteCursor" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLiteCursor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sqlite\&.h>\fP
.PP
Inherits \fBDatabaseCursor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSQLiteCursor\fP ()=default"
.br
.ti -1c
.RI "\fBSQLiteCursor\fP (std::vector< std::byte > start_range, std::vector< std::byte > end_range)"
.br
.ti -1c
.RI "\fB~SQLiteCursor\fP () override"
.br
.ti -1c
.RI "\fBStatus\fP\fBStatus\fP \fBNext\fP (\fBDataStream\fP &key, \fBDataStream\fP &value) override"
.br
.in -1c

Public Member Functions inherited from \fBDatabaseCursor\fP
.in +1c
.ti -1c
.RI "\fBDatabaseCursor\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~DatabaseCursor\fP ()=default"
.br
.ti -1c
.RI "\fBDatabaseCursor\fP (const DatabaseCursor &)=delete"
.br
.ti -1c
.RI "\fBDatabaseCursor\fP & \fBoperator=\fP (const \fBDatabaseCursor\fP &)=delete"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sqlite3_stmt * \fBm_cursor_stmt\fP {nullptr}"
.br
.ti -1c
.RI "std::vector< std::byte > \fBm_prefix_range_start\fP"
.br
.ti -1c
.RI "std::vector< std::byte > \fBm_prefix_range_end\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBDatabaseCursor\fP
.in +1c
.ti -1c
.RI "enum class \fBStatus\fP { \fBFAIL\fP, \fBMORE\fP, \fBDONE\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
RAII class that provides a database cursor 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLiteCursor ()\fR [explicit]\fP, \fR [default]\fP"

.SS "SQLiteCursor (std::vector< std::byte > start_range, std::vector< std::byte > end_range)\fR [inline]\fP, \fR [explicit]\fP"

.SS "~\fBSQLiteCursor\fP ()\fR [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBDatabaseCursor::Status\fP Next (\fBDataStream\fP & key, \fBDataStream\fP & value)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBDatabaseCursor\fP\&.
.SH "Field Documentation"
.PP 
.SS "sqlite3_stmt* m_cursor_stmt {nullptr}"

.SS "std::vector<std::byte> m_prefix_range_end"

.SS "std::vector<std::byte> m_prefix_range_start"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
