.TH "src/wallet/test/fuzz/wallet_bdb_parser.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/test/fuzz/wallet_bdb_parser.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <test/fuzz/FuzzedDataProvider\&.h>\fP
.br
\fR#include <test/fuzz/fuzz\&.h>\fP
.br
\fR#include <test/fuzz/util\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <util/fs\&.h>\fP
.br
\fR#include <util/time\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <wallet/db\&.h>\fP
.br
\fR#include <wallet/dump\&.h>\fP
.br
\fR#include <wallet/migrate\&.h>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBDatabaseOptions\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBDatabaseStatus\fP "
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_wallet_bdb_parser\fP ()"
.br
.ti -1c
.RI "\fBFUZZ_TARGET\fP (wallet_bdb_parser,\&.\fBinit\fP=\fBinitialize_wallet_bdb_parser\fP)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBDatabaseStatus\fP\fR [strong]\fP"

.SH "Function Documentation"
.PP 
.SS "FUZZ_TARGET (wallet_bdb_parser , \&. init = \fR\fBinitialize_wallet_bdb_parser\fP\fP)"

.SS "void initialize_wallet_bdb_parser ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
