.TH "src/wallet/walletdb.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/walletdb.h
.SH SYNOPSIS
.br
.PP
\fR#include <key\&.h>\fP
.br
\fR#include <primitives/transaction_identifier\&.h>\fP
.br
\fR#include <script/sign\&.h>\fP
.br
\fR#include <wallet/db\&.h>\fP
.br
\fR#include <wallet/walletutil\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCHDChain\fP"
.br
.ti -1c
.RI "class \fBCKeyMetadata\fP"
.br
.ti -1c
.RI "struct \fBDbTxnListener\fP"
.br
.ti -1c
.RI "class \fBWalletBatch\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.ti -1c
.RI "namespace \fBwallet::DBKeys\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBDBErrors\fP : int { \fBLOAD_OK\fP = 0, \fBNEED_RESCAN\fP = 1, \fBNEED_REWRITE\fP = 2, \fBEXTERNAL_SIGNER_SUPPORT_REQUIRED\fP = 3, \fBNONCRITICAL_ERROR\fP = 4, \fBTOO_NEW\fP = 5, \fBUNKNOWN_DESCRIPTOR\fP = 6, \fBLOAD_FAIL\fP = 7, \fBUNEXPECTED_LEGACY_ENTRY\fP = 8, \fBLEGACY_WALLET\fP = 9, \fBCORRUPT\fP = 10 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLogDBInfo\fP ()"
.br
.ti -1c
.RI "bool \fBRunWithinTxn\fP (\fBWalletDatabase\fP &database, std::string_view process_desc, const std::function< bool(\fBWalletBatch\fP &)> &func)"
.br
.ti -1c
.RI "bool \fBLoadKey\fP (\fBCWallet\fP *pwallet, \fBDataStream\fP &ssKey, \fBDataStream\fP &ssValue, std::string &strErr)"
.br
.ti -1c
.RI "bool \fBLoadCryptedKey\fP (\fBCWallet\fP *pwallet, \fBDataStream\fP &ssKey, \fBDataStream\fP &ssValue, std::string &strErr)"
.br
.ti -1c
.RI "bool \fBLoadEncryptionKey\fP (\fBCWallet\fP *pwallet, \fBDataStream\fP &ssKey, \fBDataStream\fP &ssValue, std::string &strErr)"
.br
.ti -1c
.RI "bool \fBLoadHDChain\fP (\fBCWallet\fP *pwallet, \fBDataStream\fP &ssValue, std::string &strErr)"
.br
.ti -1c
.RI "bool \fBHasLegacyRecords\fP (\fBCWallet\fP &\fBwallet\fP)"
.br
.RI "Returns true if there are any \fBDBKeys::LEGACY_TYPES\fP record in the wallet db\&. "
.ti -1c
.RI "bool \fBHasLegacyRecords\fP (\fBCWallet\fP &\fBwallet\fP, \fBDatabaseBatch\fP &batch)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
