.TH "wallet::WalletTool" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wallet::WalletTool
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBExecuteWalletToolFunc\fP (const \fBArgsManager\fP &\fBargs\fP, const std::string &\fBcommand\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool ExecuteWalletToolFunc (const \fBArgsManager\fP & args, const std::string & command)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
