.TH "CachableAmount" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachableAmount
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transaction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBSet\fP (bool avoid_reuse, \fBCAmount\fP value)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGet\fP (bool avoid_reuse)"
.br
.ti -1c
.RI "bool \fBIsCached\fP (bool avoid_reuse)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::optional< \fBCAmount\fP > \fBm_avoid_reuse_value\fP"
.br
.ti -1c
.RI "std::optional< \fBCAmount\fP > \fBm_all_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cachable amount subdivided into avoid reuse and all balances 
.SH "Member Function Documentation"
.PP 
.SS "\fBCAmount\fP Get (bool avoid_reuse)\fR [inline]\fP"

.SS "bool IsCached (bool avoid_reuse)\fR [inline]\fP"

.SS "void Reset ()\fR [inline]\fP"

.SS "void Set (bool avoid_reuse, \fBCAmount\fP value)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::optional<\fBCAmount\fP> m_all_value"

.SS "std::optional<\fBCAmount\fP> m_avoid_reuse_value"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
