.TH "WalletStorage" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletStorage
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scriptpubkeyman\&.h>\fP
.PP
Inherited by \fBCWallet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~WalletStorage\fP ()=default"
.br
.ti -1c
.RI "virtual std::string \fBLogName\fP () const =0"
.br
.ti -1c
.RI "virtual \fBWalletDatabase\fP & \fBGetDatabase\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBIsWalletFlagSet\fP (uint64_t) const =0"
.br
.ti -1c
.RI "virtual void \fBUnsetBlankWalletFlag\fP (\fBWalletBatch\fP &)=0"
.br
.ti -1c
.RI "virtual bool \fBWithEncryptionKey\fP (std::function< bool(const \fBCKeyingMaterial\fP &)> cb) const =0"
.br
.RI "Pass the encryption key to cb()\&. "
.ti -1c
.RI "virtual bool \fBHasEncryptionKeys\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBIsLocked\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBTopUpCallback\fP (const std::set< \fBCScript\fP > &, \fBScriptPubKeyMan\fP *)=0"
.br
.RI "Callback function for after TopUp completes containing any scripts that were added by a SPKMan\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBWalletStorage\fP ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBWalletDatabase\fP & GetDatabase () const\fR [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP, and \fBCWallet\fP\&.
.SS "virtual bool HasEncryptionKeys () const\fR [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP, and \fBCWallet\fP\&.
.SS "virtual bool IsLocked () const\fR [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP, and \fBCWallet\fP\&.
.SS "virtual bool IsWalletFlagSet (uint64_t ) const\fR [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP, and \fBCWallet\fP\&.
.SS "virtual std::string LogName () const\fR [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP, and \fBCWallet\fP\&.
.SS "virtual void TopUpCallback (const std::set< \fBCScript\fP > & , \fBScriptPubKeyMan\fP * )\fR [pure virtual]\fP"

.PP
Callback function for after TopUp completes containing any scripts that were added by a SPKMan\&. 
.PP
Implemented in \fBCWallet\fP\&.
.SS "virtual void UnsetBlankWalletFlag (\fBWalletBatch\fP & )\fR [pure virtual]\fP"

.SS "virtual bool WithEncryptionKey (std::function< bool(const \fBCKeyingMaterial\fP &)> cb) const\fR [pure virtual]\fP"

.PP
Pass the encryption key to cb()\&. 
.PP
Implemented in \fBCWallet\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
