.TH "src/qt/walletmodel.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/qt/walletmodel.h
.SH SYNOPSIS
.br
.PP
\fR#include <key\&.h>\fP
.br
\fR#include <qt/walletmodeltransaction\&.h>\fP
.br
\fR#include <interfaces/wallet\&.h>\fP
.br
\fR#include <primitives/transaction_identifier\&.h>\fP
.br
\fR#include <support/allocators/secure\&.h>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <QObject>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWalletModel\fP"
.br
.ti -1c
.RI "struct \fBWalletModel::SendCoinsReturn\fP"
.br
.ti -1c
.RI "class \fBWalletModel::UnlockContext\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinterfaces\fP"
.br
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
