.TH "src/wallet/test/walletload_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/test/walletload_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <wallet/test/util\&.h>\fP
.br
\fR#include <wallet/wallet\&.h>\fP
.br
\fR#include <test/util/logging\&.h>\fP
.br
\fR#include <test/util/setup_common\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDummyDescriptor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (wallet_load_descriptors, \fBTestingSetup\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
