.TH "Groups" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Groups
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <coinselection\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< \fBOutputGroup\fP > \fBpositive_group\fP"
.br
.ti -1c
.RI "std::vector< \fBOutputGroup\fP > \fBmixed_group\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "std::vector<\fBOutputGroup\fP> mixed_group"

.SS "std::vector<\fBOutputGroup\fP> positive_group"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
