.TH "src/wallet/test/wallet_transaction_tests.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wallet/test/wallet_transaction_tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <wallet/transaction\&.h>\fP
.br
\fR#include <wallet/test/wallet_test_fixture\&.h>\fP
.br
\fR#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwallet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (roundtrip)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
