.TH "src/node/warnings.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/node/warnings.h
.SH SYNOPSIS
.br
.PP
\fR#include <sync\&.h>\fP
.br
\fR#include <util/translation\&.h>\fP
.br
\fR#include <map>\fP
.br
\fR#include <variant>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWarnings\fP"
.br
.RI "Manages warning messages within a node\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBkernel\fP"
.br
.ti -1c
.RI "namespace \fBnode\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBWarning\fP { \fBCLOCK_OUT_OF_SYNC\fP, \fBPRE_RELEASE_TEST_BUILD\fP, \fBFATAL_INTERNAL_ERROR\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUniValue\fP \fBGetWarningsForRpc\fP (const \fBWarnings\fP &warnings, bool use_deprecated)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
