.TH "WitnessUnknown" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WitnessUnknown \- \fBCTxDestination\fP subtype to encode any future Witness version\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <addresstype\&.h>\fP
.PP
Inherited by \fBPayToAnchor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWitnessUnknown\fP (unsigned int version, const std::vector< unsigned char > &program)"
.br
.ti -1c
.RI "\fBWitnessUnknown\fP (int version, const std::vector< unsigned char > &program)"
.br
.ti -1c
.RI "unsigned int \fBGetWitnessVersion\fP () const"
.br
.ti -1c
.RI "const std::vector< unsigned char > & \fBGetWitnessProgram\fP () const \fBLIFETIMEBOUND\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBWitnessUnknown\fP &w1, const \fBWitnessUnknown\fP &w2)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBWitnessUnknown\fP &w1, const \fBWitnessUnknown\fP &w2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCTxDestination\fP subtype to encode any future Witness version\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBWitnessUnknown\fP (unsigned int version, const std::vector< unsigned char > & program)\fR [inline]\fP"

.SS "\fBWitnessUnknown\fP (int version, const std::vector< unsigned char > & program)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const std::vector< unsigned char > & GetWitnessProgram () const\fR [inline]\fP"

.SS "unsigned int GetWitnessVersion () const\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "bool operator< (const \fBWitnessUnknown\fP & w1, const \fBWitnessUnknown\fP & w2)\fR [friend]\fP"

.SS "bool operator== (const \fBWitnessUnknown\fP & w1, const \fBWitnessUnknown\fP & w2)\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
