.TH "WorkQueue< WorkItem >" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorkQueue< WorkItem >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorkQueue\fP (size_t _maxDepth)"
.br
.ti -1c
.RI "\fB~WorkQueue\fP ()=default"
.br
.ti -1c
.RI "bool \fBEnqueue\fP (WorkItem *item) \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!\fBcs\fP)"
.br
.ti -1c
.RI "void \fBRun\fP () \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!\fBcs\fP)"
.br
.ti -1c
.RI "void \fBInterrupt\fP () \fBEXCLUSIVE_LOCKS_REQUIRED\fP(!\fBcs\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename WorkItem>
.br
class WorkQueue< WorkItem >"Simple work queue for distributing work over multiple threads\&. Work items are simply callable objects\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename WorkItem> \fBWorkQueue\fP (size_t _maxDepth)\fR [inline]\fP, \fR [explicit]\fP"

.SS "template<typename WorkItem> ~\fBWorkQueue\fP ()\fR [default]\fP"
Precondition: worker threads have all stopped (they have been joined)\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename WorkItem> bool Enqueue (WorkItem * item)\fR [inline]\fP"
Enqueue a work item 
.SS "template<typename WorkItem> void Interrupt ()\fR [inline]\fP"
Interrupt and exit loops 
.SS "template<typename WorkItem> void Run ()\fR [inline]\fP"
Thread function 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
