.TH "WshSatisfier" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WshSatisfier
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSatisfier< CPubKey >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWshSatisfier\fP (const \fBSigningProvider\fP &provider \fBLIFETIMEBOUND\fP, \fBSignatureData\fP &sig_data \fBLIFETIMEBOUND\fP, const \fBBaseSignatureCreator\fP &creator \fBLIFETIMEBOUND\fP, const \fBCScript\fP &witscript \fBLIFETIMEBOUND\fP)"
.br
.ti -1c
.RI "template<typename I> std::optional< \fBCPubKey\fP > \fBFromPKBytes\fP (I first, I last) const"
.br
.RI "Conversion from a raw compressed public key\&. "
.ti -1c
.RI "template<typename I> std::optional< \fBCPubKey\fP > \fBFromPKHBytes\fP (I first, I last) const"
.br
.RI "Conversion from a raw compressed public key hash\&. "
.ti -1c
.RI "\fBminiscript::Availability\fP \fBSign\fP (const \fBCPubKey\fP &key, std::vector< unsigned char > &sig) const"
.br
.RI "Satisfy an ECDSA signature check\&. "
.in -1c

Public Member Functions inherited from \fBSatisfier< CPubKey >\fP
.in +1c
.ti -1c
.RI "\fBSatisfier\fP (const \fBSigningProvider\fP &provider \fBLIFETIMEBOUND\fP, \fBSignatureData\fP &sig_data \fBLIFETIMEBOUND\fP, const \fBBaseSignatureCreator\fP &creator \fBLIFETIMEBOUND\fP, const \fBCScript\fP &witscript \fBLIFETIMEBOUND\fP, \fBminiscript::MiniscriptContext\fP script_ctx)"
.br
.ti -1c
.RI "std::optional< \fBCPubKey\fP > \fBCPubFromPKHBytes\fP (I first, I last) const"
.br
.RI "Get a \fBCPubKey\fP from a key hash\&. Note the key hash may be of an xonly pubkey\&. "
.ti -1c
.RI "std::vector< unsigned char > \fBToPKBytes\fP (const \fBKey\fP &key) const"
.br
.RI "Conversion to raw public key\&. "
.ti -1c
.RI "bool \fBCheckAfter\fP (uint32_t value) const"
.br
.RI "Time lock satisfactions\&. "
.ti -1c
.RI "bool \fBCheckOlder\fP (uint32_t value) const"
.br
.ti -1c
.RI "\fBminiscript::Availability\fP \fBSatSHA256\fP (const std::vector< unsigned char > &hash, std::vector< unsigned char > &preimage) const"
.br
.RI "Hash preimage satisfactions\&. "
.ti -1c
.RI "\fBminiscript::Availability\fP \fBSatRIPEMD160\fP (const std::vector< unsigned char > &hash, std::vector< unsigned char > &preimage) const"
.br
.ti -1c
.RI "\fBminiscript::Availability\fP \fBSatHASH256\fP (const std::vector< unsigned char > &hash, std::vector< unsigned char > &preimage) const"
.br
.ti -1c
.RI "\fBminiscript::Availability\fP \fBSatHASH160\fP (const std::vector< unsigned char > &hash, std::vector< unsigned char > &preimage) const"
.br
.ti -1c
.RI "\fBminiscript::MiniscriptContext\fP \fBMsContext\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBSatisfier< CPubKey >\fP
.in +1c
.ti -1c
.RI "using \fBKey\fP"
.br
.in -1c

Static Public Member Functions inherited from \fBSatisfier< CPubKey >\fP
.in +1c
.ti -1c
.RI "static bool \fBKeyCompare\fP (const \fBKey\fP &a, const \fBKey\fP &b)"
.br
.in -1c

Data Fields inherited from \fBSatisfier< CPubKey >\fP
.in +1c
.ti -1c
.RI "const \fBSigningProvider\fP & \fBm_provider\fP"
.br
.ti -1c
.RI "\fBSignatureData\fP & \fBm_sig_data\fP"
.br
.ti -1c
.RI "const \fBBaseSignatureCreator\fP & \fBm_creator\fP"
.br
.ti -1c
.RI "const \fBCScript\fP & \fBm_witness_script\fP"
.br
.ti -1c
.RI "const \fBminiscript::MiniscriptContext\fP \fBm_script_ctx\fP"
.br
.RI "The context of the script we are satisfying (either P2WSH or Tapscript)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Miniscript satisfier specific to P2WSH context\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBWshSatisfier\fP (const \fBSigningProvider\fP &provider LIFETIMEBOUND, \fBSignatureData\fP &sig_data LIFETIMEBOUND, const \fBBaseSignatureCreator\fP &creator LIFETIMEBOUND, const \fBCScript\fP &witscript LIFETIMEBOUND)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename I> std::optional< \fBCPubKey\fP > FromPKBytes (I first, I last) const\fR [inline]\fP"

.PP
Conversion from a raw compressed public key\&. 
.SS "template<typename I> std::optional< \fBCPubKey\fP > FromPKHBytes (I first, I last) const\fR [inline]\fP"

.PP
Conversion from a raw compressed public key hash\&. 
.SS "\fBminiscript::Availability\fP Sign (const \fBCPubKey\fP & key, std::vector< unsigned char > & sig) const\fR [inline]\fP"

.PP
Satisfy an ECDSA signature check\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
