.TH "wycheproof_ecdsa_testvector" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wycheproof_ecdsa_testvector
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ecdsa_secp256k1_sha256_bitcoin_test\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBpk_offset\fP"
.br
.ti -1c
.RI "size_t \fBmsg_offset\fP"
.br
.ti -1c
.RI "size_t \fBmsg_len\fP"
.br
.ti -1c
.RI "size_t \fBsig_offset\fP"
.br
.ti -1c
.RI "size_t \fBsig_len\fP"
.br
.ti -1c
.RI "int \fBexpected_verify\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int expected_verify"

.SS "size_t msg_len"

.SS "size_t msg_offset"

.SS "size_t pk_offset"

.SS "size_t sig_len"

.SS "size_t sig_offset"


.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
