.TH "src/zmq/zmqnotificationinterface.h" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/zmq/zmqnotificationinterface.h
.SH SYNOPSIS
.br
.PP
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <validationinterface\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <list>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCZMQNotificationInterface\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBCZMQNotificationInterface\fP > \fBg_zmq_notification_interface\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::unique_ptr<\fBCZMQNotificationInterface\fP> g_zmq_notification_interface\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
