.TH "src/zmq/zmqnotificationinterface.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/zmq/zmqnotificationinterface.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <zmq/zmqnotificationinterface\&.h>\fP
.br
\fR#include <common/args\&.h>\fP
.br
\fR#include <kernel/mempool_entry\&.h>\fP
.br
\fR#include <kernel/types\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <netbase\&.h>\fP
.br
\fR#include <primitives/block\&.h>\fP
.br
\fR#include <primitives/transaction\&.h>\fP
.br
\fR#include <validationinterface\&.h>\fP
.br
\fR#include <zmq/zmqabstractnotifier\&.h>\fP
.br
\fR#include <zmq/zmqpublishnotifier\&.h>\fP
.br
\fR#include <zmq/zmqutil\&.h>\fP
.br
\fR#include <zmq\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <map>\fP
.br
\fR#include <string>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBCZMQNotificationInterface\fP > \fBg_zmq_notification_interface\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::unique_ptr<\fBCZMQNotificationInterface\fP> g_zmq_notification_interface"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
