.TH "src/zmq/zmqutil.cpp" 3 "Version 2.8" "bitcoind" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/zmq/zmqutil.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <zmq/zmqutil\&.h>\fP
.br
\fR#include <logging\&.h>\fP
.br
\fR#include <zmq\&.h>\fP
.br
\fR#include <cerrno>\fP
.br
\fR#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBzmqError\fP (const std::string &str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void zmqError (const std::string & str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for bitcoind from the source code\&.
